### ISSUE TITLE
SPAdes automatic phred offset prediction incorrect?

### ISSUE THREAD

**Issue by brymerr921** [ablab/spades#10]
Hi,

I am trying to assemble some reads in FASTQ format that were sequenced on a HiSeq 4000 and the quality scores are in Illumina 1.9 format, which have a phred offset of 33. However, when I ran SPAdes, it thought the reads had an offset of 64 and resulted in a very bad assembly. The incorrect auto-detection may be because the ASCII character "K" is a valid score of very high quality for this format of Illumina reads. Fortunately, I caught this and re-ran the assembly with --phred_offset 33 and everything came out great. In a future version it might be helpful to edit the auto-detection to make sure Illumina 1.9 quality scores are auto-detected as phred + 33.

Bryan

**Comment by asl** [comment]
Thanks, will be fixed in 3.10
