### ISSUE TITLE
metaspades, Exception caught vector::reserve, finished abnormally, err code: 4

### ISSUE THREAD

**Issue by weihongqi** [ablab/spades#100]
Dear SPAdes team,

I tried to used metaspades (in 3.11.0) assemble a large dataset (220 M PE reads), and got err code 4. 
[metaspades.log](https://github.com/ablab/spades/files/1903111/metaspades.log)

May I ask what could be the reason? The server has I Tb RAM:
Linux 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u2~bpo8+1 (2017-06-27) x86_64 GNU/Linux

I would be happy to prove more information if needed,

Kind regards,

Weihong

**Comment by asl** [comment]
Hello

Does the problem reproduces with SPAdes 3.12?

**Comment by asl** [comment]
I believe we identified the problem that might cause this and the fix will be in SPAdes 3.12.1

**Comment by asl** [comment]
Fixed in 3.13.0

**Comment by RolandFaure** [comment]
Hello, I am meeting the same problem as in this issue. I am running ariadne (lauren-mak/ariadne), which is a SPAdes 3.12.0 based software, so I guess from this issue that it is not surprising. 
However, as I can't change the SPAdes version, could you give some insight as to why this error occur and how to work around it ?

Thanks in advance,
Roland

**Comment by asl** [comment]
@RolandFaure The issues is fixed in the mentioned SPAdes version, there is no way to workaround. You may want to contact the authors of this pipeline to upgrade SPAdes / cherry-pick necessary changes. SPAdes 3.12 is quite old and is known to contain many issues here and there.

**Comment by RolandFaure** [comment]
Thank you :)
