### ISSUE TITLE
mmap(2) failed. Reason: Cannot allocate memory. Error code: 12

### ISSUE THREAD

**Issue by sersancar** [ablab/spades#1000]
### Description of bug

Hi, 

I am trying to assemble a metagenomic sample with paired reads with a size of 25GB each. I tried with several number of nodes , but I always find the same memory allocating error. My server has 125GB of RAM and 24 CPUs.

### spades.log

[spades.log](https://github.com/ablab/spades/files/9108933/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9108935/params.txt)

### SPAdes version

3.15.2

### Operating System

Ubuntu 21.04 

### Python Version

Python 3.8.8

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Per error message you are running out of RAM. Given the size of input dataset (13 billion distinct k-mers) I doubt you will be able to fit into 125 Gb.

**Comment by sersancar** [comment]
I has also access to a HPC cluster with machines with 36 CPUs and 400GB of RAM. Do you think that would it be possible to assemble the reads on that machine?

**Comment by asl** [comment]
There is no way to predict memory consumption in advance as it depends on many factors. So you will never know before running actual assembly.
