### ISSUE TITLE
Error in read correction by using spades command in ubuntu 22.04 (Windows subsystem linux)

### ISSUE THREAD

**Issue by masterrohan143** [ablab/spades#1002]
### Description of bug

spades.py -1 mycoplasma_pneumoniae_F_Paired_100K.fastq -2 mycoplasma_pneumoniae_R_Paired_100K.fastq -s  mycoplasma_pneumoniae_F_Unpaired_100K.fastq -s mycoplasma_pneumoniae_R_Unpaired_100K.fastq -o genome_assembly -t 4 -k 35,55,75,105,127
Command line: /usr/lib/spades/bin/spades.py     -1      /mnt/e/genome_assembly/mycoplasma_pneumoniae_F_Paired_100K.fastq        -2 /mnt/e/genome_assembly/mycoplasma_pneumoniae_R_Paired_100K.fastq               -s       /mnt/e/genome_assembly/mycoplasma_pneumoniae_F_Unpaired_100K.fastq      -s      /mnt/e/genome_assembly/mycoplasma_pneumoniae_R_Unpaired_100K.fastq                                                        -o       /mnt/e/genome_assembly/genome_assembly  -t      4       -k      35,55,75,105,127

System information:
  SPAdes version: 3.13.1
  Python version: 3.10.4
  OS: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.35

Output dir: /mnt/e/genome_assembly/genome_assembly
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/mnt/e/genome_assembly/mycoplasma_pneumoniae_F_Paired_100K.fastq']
      right reads: ['/mnt/e/genome_assembly/mycoplasma_pneumoniae_R_Paired_100K.fastq']
      interlaced reads: not specified
      single reads: ['/mnt/e/genome_assembly/mycoplasma_pneumoniae_F_Unpaired_100K.fastq', '/mnt/e/genome_assembly/mycoplasma_pneumoniae_R_Unpaired_100K.fastq']
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [35, 55, 75, 105, 127]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /mnt/e/genome_assembly/genome_assembly/tmp
  Threads: 4
  Memory limit (in Gb): 7

======= SPAdes pipeline started. Log can be found here: /mnt/e/genome_assembly/genome_assembly/spades.log

[('/usr/lib/spades/../../share/spades/configs/corrector', '/mnt/e/genome_assembly/genome_assembly/configs/corrector', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs/debruijn', '/mnt/e/genome_assembly/genome_assembly/configs/debruijn', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs/hammer', '/mnt/e/genome_assembly/genome_assembly/configs/hammer', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs/ionhammer', '/mnt/e/genome_assembly/genome_assembly/configs/ionhammer', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs', '/mnt/e/genome_assembly/genome_assembly/configs', '[Errno 1] Operation not permitted')]
Traceback (most recent call last):
  File "/usr/lib/spades/bin/spades.py", line 800, in main
    copy_tree(os.path.join(spades_home, "configs"), tmp_configs_dir, preserve_times=False, preserve_mode=False)
  File "/usr/lib/spades/bin/spades.py", line 661, in copy_tree
    shutil.copytree(src, dst, copy_function = copy_fn, dirs_exist_ok = True)
  File "/usr/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/usr/lib/spades/../../share/spades/configs/corrector', '/mnt/e/genome_assembly/genome_assembly/configs/corrector', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs/debruijn', '/mnt/e/genome_assembly/genome_assembly/configs/debruijn', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs/hammer', '/mnt/e/genome_assembly/genome_assembly/configs/hammer', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs/ionhammer', '/mnt/e/genome_assembly/genome_assembly/configs/ionhammer', '[Errno 1] Operation not permitted'), ('/usr/lib/spades/../../share/spades/configs', '/mnt/e/genome_assembly/genome_assembly/configs', '[Errno 1] Operation not permitted')]

== Error ==  exception caught: <class 'shutil.Error'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

### spades.log

[spades.log](https://github.com/ablab/spades/files/9119615/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9119619/params.txt)

### SPAdes version

SPAdes v3.13.1

### Operating System

Ubuntu linux 22.04 64 bit

### Python Version

Python 3.10.4

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
Permission denied: '/mnt/e/genome_assembly/spades_test/corrected/configs'
```

So, there is an I/O error on your end.
