### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hfmahmoud** [ablab/spades#101]
File "/usr/local/bin/spades.py", line 1051, in <module>
    main(sys.argv)
  File "/usr/local/bin/spades.py", line 617, in main
    cfg, dataset_data = fill_cfg(options, log)
  File "/usr/local/bin/spades.py", line 501, in fill_cfg
    cfg["assembly"].__dict__["lcer_cutoff"] = options_storage.lcer_cutoff
AttributeError: 'module' object has no attribute 'lcer_cutoff'

I installed SPAdes on Mac, every time I'm running it this error keeps appearing

**Comment by alexeigurevich** [comment]
Hi, 
It looks like you have a mix of an old SPAdes release (I suppose SPAdes-3.10.1) and a new one (I suppose SPAdes-3.11.1). 
The new version files are under `/usr/local/bin/` (in particular `spades.py` script) and the old version is still present under `/usr/local/share/spades/` (in particular `spades_pipeline/options_storage.py` where `lcer_cutoff` attribute was added in SPAdes-3.11).
Could you please completely remove `/usr/local/share/spades/` directory and reinstall the new SPAdes from scratch?

**Comment by asl** [comment]
Please reopen if this still an issue.
