### ISSUE TITLE
problem running spades OS return value: 22

### ISSUE THREAD

**Issue by camolina-vet** [ablab/spades#1012]
### Description of bug

I try to run spades and this error always come:

== Error ==  system call for: "['/Users/camilamolina/miniconda3/bin/spades-hammer', '/Users/camilamolina/Desktop/FLU_A/H1N1/spades_output/corrected/configs/config.info']" finished abnormally, OS return value: 22

I tryed to run the test also, the same error comes. 

### spades.log

[spades.log](https://github.com/ablab/spades/files/9309874/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9309875/params.txt)

### SPAdes version

SPAdes version: 3.15.2

### Operating System

 OS: macOS-12.3.1-x86_64-i386-64bi

### Python Version

 Python version: 3.9.12

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is a known problem with SPAdes 3.15.2 Consider upgrading to the latest SPAdes version.
