### ISSUE TITLE
== Error ==  system call for: "['/group/pathogens/Bioinfo_Software/SPAdes-3.15.5-Linux/bin/spades-hammer', '/group/pathogens/Akshita/Sequencing_Run3/error_correction/Output_EC/2-A/corrected/configs/config.info']" finished abnormally, OS return value: 12

### ISSUE THREAD

**Issue by AkshitaJain2709** [ablab/spades#1014]
### Description of bug

Error correction module not running. I have 4 different isolates, and error correction is working for two isolates and not working for two isolates. 

### spades.log

[spades.log](https://github.com/ablab/spades/files/9422167/spades.log)

### params.txt

[Uploading params.txt…]()

### SPAdes version

v3.15.5

### Operating System

Windows

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
  0:49:39.111     1M / 24G   ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
```

So, you're running out of RAM

**Comment by AkshitaJain2709** [comment]
I have given it 256 gb of memory. Do I need to increase it more? Thanks in advance

**Comment by asl** [comment]
Please ensure that this RAM is indeed free. One cannot estimate memory consumption in advance.
