### ISSUE TITLE
macOS Monterey: Not able to update spades

### ISSUE THREAD

**Issue by ajkarloss** [ablab/spades#1015]
### Description of bug

I have installed spades and shovill using conda. They have been working properly until I updated to macOS Monterey. And, I am not able to update from spades 3.15.2 to the latest one. It says "# All requested packages already installed.". Even if i try to install a fresh one, it installs only 3.15.2. 

### spades.log

[spades] == Error ==  system call for: "['/Users/jeevka/galaxy/database/dependencies/_conda/envs/__shovill@1.1.0/bin/spades-core', '/Users/jeevka/out/spades/K31/configs/config.info', '/Users/jeevka/out/spades/K31/configs/isolate_mode.info']" finished abnormally, OS return value: 22
[spades]
[spades] In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
[spades] or report an issue on our GitHub repository github.com/ablab/spades
[spades] Please provide us with params.txt and spades.log files from the output directory.
[spades]
[spades] SPAdes log can be found here: /Users/jeevka/out/spades/spades.log
[spades]
[spades] Thank you for using SPAdes!
[shovill] Assembly failed - spades.fasta has zero contigs!

### params.txt

 shovill --outdir out --cpus 1 --ram 4 --R1 Test_Fastq_Files/R1_001.fastq --R2 Test_Fastq_Files/R2_001.fastq --namefmt contig%05d --depth 100 --gsize 2800000 --nocorr --minlen 0 --mincov 2 --assembler spades

### SPAdes version

3.15.2

### Operating System

macOS monterey

### Python Version

3.8.13

### Method of SPAdes installation

conda 

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Will you please attache the `spades.log` file as you were instructed in the error message?

**Comment by ajkarloss** [comment]
[shovill] Running: spades.py -1 flash.notCombined_1.fastq.gz -2 flash.notCombined_2.fastq.gz --isolate --threads 1 --memory 4 -o spades --tmp-dir /var/folders/z4/598z4x912_d17v8k299nqtkw0000gn/T/ -k 31,55,79,103,127  --merged flash.extendedFrags.fastq.gz 2>&1 | sed 's/^/[spades] /' | tee -a shovill.log
[spades] Command line: /Users/jeevka/galaxy/database/dependencies/_conda/envs/__shovill@1.1.0/bin/spades.py	-1	/Users/jeevka/out/flash.notCombined_1.fastq.gz	-2	/Users/jeevka/out/flash.notCombined_2.fastq.gz	--isolate	--threads	1	--memory	4	-o	/Users/jeevka/out/spades	--tmp-dir	/var/folders/z4/598z4x912_d17v8k299nqtkw0000gn/T	-k	31,55,79,103,127	--merged	/Users/jeevka/out/flash.extendedFrags.fastq.gz
[spades]
[spades] System information:
[spades]   SPAdes version: 3.15.2
[spades]   Python version: 3.8.13
[spades]   OS: macOS-10.16-x86_64-i386-64bit
[spades]
[spades] Output dir: /Users/jeevka/out/spades
[spades] Mode: ONLY assembling (without read error correction)
[spades] Debug mode is turned OFF
[spades]
[spades] Dataset parameters:
[spades]   Isolate mode
[spades]   Reads:
[spades]     Library number: 1, library type: paired-end
[spades]       orientation: fr
[spades]       left reads: ['/Users/jeevka/out/flash.notCombined_1.fastq.gz']
[spades]       right reads: ['/Users/jeevka/out/flash.notCombined_2.fastq.gz']
[spades]       interlaced reads: not specified
[spades]       single reads: not specified
[spades]       merged reads: ['/Users/jeevka/out/flash.extendedFrags.fastq.gz']
[spades] Assembly parameters:
[spades]   k: [31, 55, 79, 103, 127]
[spades]   Repeat resolution is enabled
[spades]   Mismatch careful mode is turned OFF
[spades]   MismatchCorrector will be SKIPPED
[spades]   Coverage cutoff is turned OFF
[spades] Other parameters:
[spades]   Dir for temp files: /var/folders/z4/598z4x912_d17v8k299nqtkw0000gn/T
[spades]   Threads: 1
[spades]   Memory limit (in Gb): 4
[spades]
[spades]
[spades] ======= SPAdes pipeline started. Log can be found here: /Users/jeevka/out/spades/spades.log
[spades]
[spades] /Users/jeevka/out/flash.notCombined_1.fastq.gz: max reads length: 301
[spades] /Users/jeevka/out/flash.notCombined_2.fastq.gz: max reads length: 301
[spades] Files with merged reads were ignored.
[spades]
[spades] Reads length: 301
[spades]
[spades]
[spades] ===== Before start started.
[spades]
[spades]
[spades] ===== Assembling started.
[spades]
[spades]
[spades] ===== K31 started.
[spades]
[spades]
[spades] == Running: /Users/jeevka/galaxy/database/dependencies/_conda/envs/__shovill@1.1.0/bin/spades-core /Users/jeevka/out/spades/K31/configs/config.info /Users/jeevka/out/spades/K31/configs/isolate_mode.info
[spades]
[spades]   0:00:00.000     1M / 7M    INFO    General                 (main.cpp                  :  99)   Loaded config from /Users/jeevka/out/spades/K31/configs/config.info
[spades]   0:00:00.000     1M / 7M    INFO    General                 (main.cpp                  :  99)   Loaded config from /Users/jeevka/out/spades/K31/configs/isolate_mode.info
[spades]   0:00:00.000     1M / 7M    ERROR   General                 (memory_limit.cpp          :  47)   setrlimit(2) call failed, errno = 22
[spades]
[spades]
[spades] == Error ==  system call for: "['/Users/jeevka/galaxy/database/dependencies/_conda/envs/__shovill@1.1.0/bin/spades-core', '/Users/jeevka/out/spades/K31/configs/config.info', '/Users/jeevka/out/spades/K31/configs/isolate_mode.info']" finished abnormally, OS return value: 22
[spades]
[spades] In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
[spades] or report an issue on our GitHub repository github.com/ablab/spades
[spades] Please provide us with params.txt and spades.log files from the output directory.
[spades]
[spades] SPAdes log can be found here: /Users/jeevka/out/spades/spades.log
[spades]
[spades] Thank you for using SPAdes!
[shovill] Assembly failed - spades.fasta has zero contigs!

**Comment by asl** [comment]
Well, this is not quite the spades.log file mentioned in the error message. Anyway, this is a known problem of SPAdes 3.15.2, consider upgrade to SPAdes 3.15.5. Installation instructions could be found at https://cab.spbu.ru/files/release3.15.5/manual.html#sec2

We do not maintain conda packages or other wrappers or package repositories. So, if the problem is there, I would suggest to report issue to them.

**Comment by ajkarloss** [comment]
Hi there, The problem is the "conda install spades" does not install the latest (3.15.5) Spades both in macOS and centOS. In macOS it install 3.15.2 and in centOS 5.13.0. When I try to upgrade to 3.15.5 it complains about incompatibilities with Python and glibc.

**Comment by asl** [comment]
As I said, we do not maintain conda packages. So, I would suggest to report these issues to conda (especially those with CentOS).
