### ISSUE TITLE
Abnormal results using --trusted-contig

### ISSUE THREAD

**Issue by eggiscute** [ablab/spades#1016]
### Description of bug

We made three hybrid assemblies with spades using different parameters for each. One with --nanopore, one with --trusted-contigs and one with --untrusted-contigs. When comparing the resulting assemblies, the ones using nanopore and untrusted contigs have similar values for N50, genome size, L50, etc. But the results for trusted contigs are drastically worse.

We wonder if this could be explained logically or is likely due to an error in the commands used?

### spades.log

[spades.log](https://github.com/ablab/spades/files/9446147/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9446151/params.txt)

### SPAdes version

3.13.0

### Operating System

Linux-4.12.14-197.40-default-x86_64-with-glibc2.26

### Python Version

3.10.4

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
What have you submitted as trusted contigs? 

Also, it seems that your paired-end reads are corrupted:
```
   0:08:52.180     3G / 15G   INFO    General                 (pair_info_count.cpp       : 213)   0 paired reads (0% of all) aligned to long edges
  0:08:52.182     3G / 15G   WARN    General                 (pair_info_count.cpp       : 339)   Unable to estimate insert size for paired library #0
  0:08:52.182     3G / 15G   WARN    General                 (pair_info_count.cpp       : 345)   None of paired reads aligned properly. Please, check orientation of your read pairs.
```

**Comment by eggiscute** [comment]
We used a file with long nanopore reads from a bacteria that we think is the same species.
Would this corrupted paired-end reads affect only the one using --trusted-contigs?

I am sending you also the log and parameters from the run using the --untrusted-contigs option in case it helps.

[spades.log](https://github.com/ablab/spades/files/9446345/spades.log)
[params.txt](https://github.com/ablab/spades/files/9446347/params.txt)

**Comment by asl** [comment]
> We used a file with long nanopore reads from a bacteria that we think is the same species.

The outcome if perfectly expected then. Long reads != contigs. See https://cab.spbu.ru/files/release3.15.5/manual.html#sec3.1 for more information about SPAdes input.

> Would this corrupted paired-end reads affect only the one using --trusted-contigs?

No. But it causes overall suboptimal assembly.

I'm closing this since the outcome is perfectly expected – this is a user error with inappropriate input.
