### ISSUE TITLE
spades.py --test Error

### ISSUE THREAD

**Issue by ElfLiu** [ablab/spades#1017]
### Description of bug

System was ubuntn 20.04.3 LTS, also tried with centos7, all reported incorrectly. Only versions below spades3.0 do not report errors and i do not known what is the problem with installation.

### spades.log

===== Copy files finished. 

===== Assembling finished. 

===== Check test started. 

== Running: /home/liujingling/miniconda3/envs/Resequencing/bin/python /home/liujingling/miniconda3/envs/Resequencing/share/spades/spades_pipeline/scripts/check_test_script.py --mode common --result_contigs_filename /home/liujingling/7120/Resequencing/2/clean_data/spades_test/contigs.fasta --result_scaffolds_filename /home/liujingling/7120/Resequencing/2/clean_data/spades_test/scaffolds.fasta

========= TEST PASSED CORRECTLY.

===== Check test finished. 

===== Breaking scaffolds started. 

== Running: /home/liujingling/miniconda3/envs/Resequencing/bin/python /home/liujingling/miniconda3/envs/Resequencing/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/liujingling/7120/Resequencing/2/clean_data/spades_test/scaffolds.fasta --misc_dir /home/liujingling/7120/Resequencing/2/clean_data/spades_test/misc --threshold_for_breaking_scaffolds 3

===== Breaking scaffolds finished. 

===== Terminate started. 

===== Terminate finished. 

 * Corrected reads are in /home/liujingling/7120/Resequencing/2/clean_data/spades_test/corrected/
 * Assembled contigs are in /home/liujingling/7120/Resequencing/2/clean_data/spades_test/contigs.fasta
 * Assembled scaffolds are in /home/liujingling/7120/Resequencing/2/clean_data/spades_test/scaffolds.fasta
 * Paths in the assembly graph corresponding to the contigs are in /home/liujingling/7120/Resequencing/2/clean_data/spades_test/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in /home/liujingling/7120/Resequencing/2/clean_data/spades_test/scaffolds.paths
 * Assembly graph is in /home/liujingling/7120/Resequencing/2/clean_data/spades_test/assembly_graph.fastg
 * Assembly graph in GFA format is in /home/liujingling/7120/Resequencing/2/clean_data/spades_test/assembly_graph_with_scaffolds.gfa

======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:07.010     1M / 292M  WARN    General                 (launcher.cpp              : 178)   Your data seems to have high uniform coverage depth. It is strongly recommended to use --isolate option.
======= Warnings saved to /home/liujingling/7120/Resequencing/2/clean_data/spades_test/warnings.log

SPAdes log can be found here: /home/liujingling/7120/Resequencing/2/clean_data/spades_test/spades.log

Thank you for using SPAdes!

### params.txt

/home/liujingling/miniconda3/envs/Resequencing/bin/spades.py	--test

### SPAdes version

 SPAdes version: 3.15.5 

### Operating System

OS: Linux-5.15.0-41-generic-x86_64-with-glibc2.10

### Python Version

Python version: 3.8.13

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

There are no errors in the log:

```
========= TEST PASSED CORRECTLY.
```

Please reopen with the log from the failed run, if you still think there is a problem
