### ISSUE TITLE
No contigs.fasta file in my kmer subfolders

### ISSUE THREAD

**Issue by Terriceratops** [ablab/spades#1019]
### Description of bug

I just ran Spades for kmer sizes from 31,41,51,... to 111. In my output folder for the whole run, I can find one contigs.fasta file for the best assembly. But I can not find any contigs.fasta files in my kmer subfolders? 

### spades.log

[spades.log](https://github.com/ablab/spades/files/9468641/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9468647/params.txt)

### SPAdes version

3.13.0

### Operating System

Linux-4.12.14-197.40-default-x86_64-with-glibc2.26

### Python Version

3.10.4

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [x] Yes

**Comment by asl** [comment]
Hello

The log reads:

```
 * Corrected reads are in /dss/dsshome1/lxc0A/csgeo005/Data/Spades_F_111/corrected/
 * Assembled contigs are in /dss/dsshome1/lxc0A/csgeo005/Data/Spades_F_111/contigs.fasta
 * Assembly graph is in /dss/dsshome1/lxc0A/csgeo005/Data/Spades_F_111/assembly_graph.fastg
 * Assembly graph in GFA format is in /dss/dsshome1/lxc0A/csgeo005/Data/Spades_F_111/assembly_graph_with_scaffolds.gfa
```


However, you removed all the sequences as:
```
  0:00:32.521     5M / 13G   INFO   Simplification           (parallel_processing.hpp   : 170)   Removing isolated edges triggered 5 times
  0:00:32.521     5M / 13G   INFO    General                 (simplification.cpp        : 337)   Removing all the edges having coverage 9 and less
  0:00:32.529     4M / 13G   INFO    General                 (simplification.cpp        : 495)   After simplification:
  0:00:32.529     4M / 13G   INFO    General                 (simplification.cpp        : 496)     Average coverage = 0
  0:00:32.532     4M / 13G   INFO    General                 (simplification.cpp        : 497)     Total length = 0
  0:00:32.532     4M / 13G   INFO    General                 (simplification.cpp        : 498)     Median edge length: 0
  0:00:32.532     4M / 13G   INFO    General                 (simplification.cpp        : 499)     Edges: 0
  0:00:32.532     4M / 13G   INFO    General                 (simplification.cpp        : 500)     Vertices: 0
```

Since you're having only 125 bp reads, running up to k=111 is unwise and you've obtained pretty expected results.

Please refer to SPAdes manual for the description of SPAdes output: https://cab.spbu.ru/files/release3.15.5/manual.html#spadesoutput

**Comment by Terriceratops** [comment]
Since I am a masters student that just started working with Linux/PowerShell/Spades, I am not familiar with the program and the theory behind it. 
Could you explain to me how I removed all sequences?

I chose the kmer size 111, to see if the N50 value for the assembly increases compared to choosing kmer sizes up to 101 or 91. I also expected the assembly to not improve since the kmer size is too high for 125bp length as you said. But since I am just getting familiar with Spades, I wanted to confirm this expectation.
Is the high kmer size the reason for the removement of my sequences? 

If this is not the right forum to ask, could you recommend another one? 

Thank you a lot!

**Comment by asl** [comment]
The solution is pretty simple: if you're newcomer and unsure what to do, then simply stick to the defaults. More information could be obtained from the manual and other sources, e.g. https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cpbi.102
