### ISSUE TITLE
rnaSpades hybrid assembly

### ISSUE THREAD

**Issue by mictadlo** [ablab/spades#102]
Hi,
Does `rnaSpades` support hybrid assembly? I have RNA-Seq Illumina and ISO-seq.

If yes then could you please provide an example command and which type of ISO-seq has to be provided to rnaSpades?

Thank you in advance.

Michal

**Comment by andrewprzh** [comment]
Dear Michal

Currently, hybrid assembly for transcriptomic data is under development. We can share an experimental version of rnaSPAdes if you'd like to try it.

Best
Andrey

**Comment by mictadlo** [comment]
Yes, would like to try it out. When do you think it would be stable?

**Comment by mictadlo** [comment]
p.s. where can I find it?

**Comment by andrewprzh** [comment]
For sure, it won't be included in the nearest release. Most likely, the next one. 

Could you, please, write me directly to andrewprzh@gmail.com and I will send you the binaries?

Best
Andrey

**Comment by asl** [comment]
RNA hybrid assemblies are well supported in SPAdes 3.15.2
