### ISSUE TITLE
Error while running spades for denovo assembly on fastq files

### ISSUE THREAD

**Issue by 24JESS** [ablab/spades#1027]
### Description of bug

Hello I am doing denovo assembly on my fastq files but I've been getting the error below;
== Error ==  system call for: "['/home/jesca/miniconda3/share/spades-3.13.0-0/bin/spades-core', '/mnt/d/JESCA/E. coli/Results/assembly/Hosp-KAT_039/K21/configs/config.info', '/mnt/d/JESCA/E. coli/Results/assembly/Hosp-KAT_039/K21/configs/careful_mode.info']" finished abnormally, err code: -11

Below is my script;

 Run_path=$1
cd $Run_path
for file in *_trim1.fastq;
do
        base=$(basename ${file} _trim1.fastq)
        spades.py -1 ${file} -2 ${base}_trim2.fastq --careful --only-assembler -o /mnt/d/JESCA/E.\ coli/Results/assembly/${base}
done

Please help me figure out what the problem could be.
Thank you.

### spades.log

[spades.log](https://github.com/ablab/spades/files/9597756/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9597762/params.txt)

### SPAdes version

SPAdes v3.13.0

### Operating System

Windows 11

### Python Version

Python 3.9.7

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

WSL is not a supported platform per manual (https://cab.spbu.ru/files/release3.15.5/manual.html#sec2). Others reported limited success compiling SPAdes from sources and running these binaries.

**Comment by 24JESS** [comment]
Thanks for the feedback
