### ISSUE TITLE
wn to 2 in order to fit the memory limits during the index construction

### ISSUE THREAD

**Issue by Yanfei-Geng** [ablab/spades#103]
3.10.1 SPAdes 
[params.txt](https://github.com/ablab/spades/files/1937351/params.txt)
[spades.log](https://github.com/ablab/spades/files/1937353/spades.log)

**Comment by Yanfei-Geng** [comment]
what is meaning of wn to 2? thx

**Comment by Yanfei-Geng** [comment]
![423](https://user-images.githubusercontent.com/34390393/39117181-f97e9396-4718-11e8-8d1b-32f9093fcdc3.png)
it stays like this for half an hour already?what should i do?

**Comment by asl** [comment]
Please attach the full spades.log file from the failed run.

**Comment by Yanfei-Geng** [comment]
[warnings.log](https://github.com/ablab/spades/files/1937555/warnings.log)
[params.txt](https://github.com/ablab/spades/files/1937556/params.txt)
[spades.log](https://github.com/ablab/spades/files/1937557/spades.log)
FYI. THX.

**Comment by asl** [comment]
The log reads:

```
=== ERRORs:
 * 0:29:00.167   712M / 7G    ERROR  K-mer Counting           (kmer_data.cpp             : 356)   The reads contain too many k-mers to fit into available memory. You need approx. 76.3148GB of free RAM to assemble your dataset
```

Hope everything is clear
