### ISSUE TITLE
Finished abnormally, OS return value -11

### ISSUE THREAD

**Issue by mbyott** [ablab/spades#1030]
### Description of bug

`== Error ==  system call for: "['/media/user/SPAdes-3.15.5-Linux/bin/spades-core', '/media/user/1TB.Adata/hiv.hsl.out/PHE-A/work/SPAdes.out/K21/configs/config.info', '/media/user/1TB.Adata/test.out/PHE-A/work/SPAdes.out/K21/configs/mda_mode.info', '/media/user/1TB.Adata/test.out.out/PHE-A/work/SPAdes.out/K21/configs/meta_mode.info', '/media/user/1TB.Adata/test.out/PHE-A/work/SPAdes.out/K21/configs/rnaviral_mode.info']" finished abnormally, OS return value: -11`

command:
`$spadesLocation/spades.py --rnaviral -m 30 -o work/SPAdes.out -1 work/$sample.hq.1.fastq -2 work/$sample.hq.2.fastq`

### spades.log

[spades.log](https://github.com/ablab/spades/files/9665146/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9665148/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux, Ubuntu

### Python Version

3.9.7

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The problem likely stems from an I/O problem on your end – lack of support of memory mapped files on your external disk volume `/media/`

**Comment by mbyott** [comment]
The spades.log file shows that memory usage only gets into the MB, this machine has 32GB.

I have avoided this issue by downloading and compiling from source. I suspect this is due to SPAdes not supporting the latest Linux kernel.

**Comment by asl** [comment]
Great that the problem is fixed. However, I doubt it's the case.  Issues with prebuilt binaries are all-or-nothing. If the pre-built binaries do not work, they simply will not be run.

**Comment by ababaian** [comment]
Ditto on this fix:
```
$ uname -a
Linux rna 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Did not work with pre-built binaries but worked when compiling from source.

```
# Spades
cd ~/bio/tar/
    wget http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5.tar.gz
    tar -xzf SPAdes-3.15.5.tar.gz
    cd SPAdes-3.15.5
    PREFIX=/home/ab/bio/ ./spades_compile.sh
```

**Comment by YL1199** [comment]
@ababaian Can you pls explain spades_compile.sh? how do you do that.

**Comment by YL1199** [comment]
@mbyott can you explain how do you compiling from source?

**Comment by asl** [comment]
> @mbyott can you explain how do you compiling from source?

Please do not hijack old issues. If you're having something – open a new one. Compilation procedure is explained in manual, consider reading it.

**Comment by YL1199** [comment]
@asl OK, I see
