### ISSUE TITLE
PlasmidSPAdes report no plasmids

### ISSUE THREAD

**Issue by Ahmer1122** [ablab/spades#1032]
### Description of bug

PlasmidSPAdes report no plasmids and creates an empty contig file

[warnings.log](https://github.com/ablab/spades/files/9818284/warnings.log)

### spades.log

[spades.log](https://github.com/ablab/spades/files/9818294/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9818298/params.txt)

### SPAdes version

SPAdes V3

### Operating System

Linux

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
  0:00:28.572   164M / 9G    INFO    General                 (coverage_uniformity_analyz:  31)   genomic coverage is 29.3658 calculated of length 4046819
  0:00:28.572   164M / 9G    INFO    General                 (chromosome_removal.cpp    :  95)   0% of bases from long edges have coverage significantly different from median
...
 * 0:00:30.478   164M / 9G    WARN    General                 (chromosome_removal.cpp    : 207)   No putative plasmid contigs found!
```

**Comment by Ahmer1122** [comment]
Dear, I did not understand. Does it means that my genome has no plasmids?

**Comment by asl** [comment]
Likely. At least those that are high copy-number (the ones detected by plasmidSPAdes).

**Comment by Ahmer1122** [comment]
Thanks a lot.

Best regards :)
