### ISSUE TITLE
spades-hammer Error OS return value: -11

### ISSUE THREAD

**Issue by gaidaroc** [ablab/spades#1033]
### Description of bug

Hello,

I'm getting a similar error message, but I used to run spades without any problems on my 48gb ram pc...
I've searched on the internet quite a bit and couldn't find a bug report for error code -11, only errors with spades-hammer.
By the way, I got the same error with v. 3.15.4. Which indicates that the problem is on my end, but I couldn't find where the problem lies.

Edit: I'm getting the same error message with --only-assembler

== Error == system call for: "['/SPAdes-3.15.5-Linux/bin/spades-hammer', '/S1/corrected/configs/config.info']" finished abnormally, OS return value: -11

### spades.log

[spades.log](https://github.com/ablab/spades/files/9820605/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9820578/params.txt)

### SPAdes version

v3.15.5

### Operating System

Linux-5.15.0-50-generic-x86_64-with-glibc2.35

### Python Version

3.10.4

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [x] Yes

**Comment by asl** [comment]
Are you running in some kind of virtual machine?

**Comment by gaidaroc** [comment]
Thank you for your quick answer, but no. I'm not.

**Comment by chuym726** [comment]
I had the same problem. I used spades on Ubuntu 22.04.1 LTS system platform. I have tried the compiled and my own compiled installation, is the same error. @asl

**Comment by asl** [comment]
@chuym726 you might want to open a separate issue

**Comment by gaidaroc** [comment]
I managed to resolve the issue afew hours ago by re-downloading the source and re-building it from there, again. There might be a problem with my tar extraction being corrupt...

**Comment by YL1199** [comment]
I have the same issue, can you explain more? How do you solve it? Thanks~

**Comment by YL1199** [comment]
@berkayekren can you explain how do you re-downloading the source and re-building?

**Comment by byeX20** [comment]
Hi,
Just follow the instructions... First, make sure that you have all the requirements to build. I remember that I had some missing libraries when I first installed debian. Then follow the instructions, I currently have no problem running spades. But it has been a very long time since I had this issue. The version, too, got updated, as well.
