### ISSUE TITLE
Spades --continue not working

### ISSUE THREAD

**Issue by MohdKhairulNizam** [ablab/spades#1035]
### Description of bug

Hi,

I used the following script for assembly:

./spades.py -k 21,33,55,77,99,127 --checkpoints all --no-clear-after --pe1-1 sample_1.fastq.gz --pe1-2 sample_2.fastq.gz -o ./spades_output -t 56 -m 256

The run was terminated due to walltime. Next, I resumed the run using the following script:

./spades.py --restart-from last -o ./spades_output

However, spades restarted the run instead of resuming from the last checkpoint. Then I tried this script:

./spades.py --continue -o ./spades_output

Again, spades restarted the run instead of resuming. May I know why and how can I fix this?

Thanks

### spades.log

[spades.log](https://github.com/ablab/spades/files/9827297/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9827298/params.txt)

### SPAdes version

SPADES v3.15.5

### Operating System

Ubuntu

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

There are no checkpoints in the read error correction. Essentially everything was terminated before the very first checkpoint.
