### ISSUE TITLE
Highly improbable pattern in subset of samples failing to assemble

### ISSUE THREAD

**Issue by jorondo1** [ablab/spades#1036]
### Description of bug

Hi,

6/54 of my samples didn't assemble using metaSpades, producing the same error as https://github.com/ablab/spades/issues/722

The reason I am opening a different issue is twofold.

To begin, I found that ordering my 54 samples by unique kmers counts (from the first steps of K-mer counting) makes the 6 problematic samples contiguous. I had friends better at probabilites than I am help me figure out that the odds of any 6 items picked from an ordered set of 54 at random being contiguous by chance are in the order of 2e-6. So that's the first reason I'm thinking this might be worth reporting, in case this could point to a pattern. Visually: 
![Bildschirmfoto 2022-10-22 um 11 01 20](https://user-images.githubusercontent.com/97983060/197346383-dfe87082-ddc6-4c6d-91eb-4700266dcfc7.png)

Small odds aside, I also tried splitting one of the problematic samples in two. Both halves went through the same assembly command without error. For now, this will be my workaround, but I am worried about the impact assembling two halves of a metagenomes seperately will have on the subsequent co-binning of these two outputs. 

I don't think it has anything to do with memory, as peak RAM usage is usually around 20-30% of available ram depending on the sample.

In any case, I really hope this helps. Looking forward to hear from you on this!

### spades.log

For the problematic (non-subset) sample : 
[spades.log](https://github.com/ablab/spades/files/9862243/spades.log)

For one of the two subsets from the same sample : 
[spades.log](https://github.com/ablab/spades/files/9862254/spades.log)

### params.txt

Same params file for both (except the sample name):
[params.txt](https://github.com/ablab/spades/files/9862256/params.txt)

### SPAdes version

3.15.4

### Operating System

Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-debian-bullseye-sid

### Python Version

2.7.15

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Highly likely the crash is in CQF implementation (https://github.com/splatlab/cqf/) we are using.

Unfortunately, the only workaround is to skip the read error correction via (`--only-assembler`). You might want to perform quality trimming before this

**Comment by jorondo1** [comment]
Thanks for the quick reply. How do you think skipping error correction would affect the assembly process? Would you recommend higher-than-usual quality trimming if I can afford it?

**Comment by asl** [comment]
Unfortunately, it's not possible to predict outcome in advance :(

**Comment by jorondo1** [comment]
Thanks I'll look into that.

Cheers!

**Comment by jorondo1** [comment]
I confirm that using --only-assembler works. Am I correct to think that this will not have much impact on the assembly if the reads that I am using have been filter and trimmed for high quality?

**Comment by asl** [comment]
Assembly is an "unstable" process, e.g. small input changes could cause large output differences, unfortunately. But I think it's ok to proceed.
