### ISSUE TITLE
Finished abnormally, err code: -6

### ISSUE THREAD

**Issue by mmcardozo** [ablab/spades#104]
Hi,

I get this error repeately. What does it mean, and how can I fix it? 
[spades.log](https://github.com/ablab/spades/files/1937799/spades.log)
[params.txt](https://github.com/ablab/spades/files/1937800/params.txt)

Many thanks,
Magda

**Comment by asl** [comment]
The log reads:

```
Verification of expression 'cov_.size() > 10' failed in function 'void cov_model::KMerCoverageModel::Fit()'. In file '/spades/src/modules/math/kmer_coverage_model.cpp' on line 186. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```

And indeed, you're having only ~90k k-mers and you're assembling this in multi-cell mode that at least expects more or less uniform coverage
