### ISSUE TITLE
spades nanopore

### ISSUE THREAD

**Issue by antoine4ucsd** [ablab/spades#1048]
### Description of bug

Hello
I am trying to apply spades on merged fastq obtained from nanopore. I have one merged fastq file per sample.
I am probably missing something obvious here . I tried the following
```
spades.py --nanopore  sample_merged.fastq.gz  --careful  -t 16 -m 48  -o ./spades_out/
spades.py --merged  sample_merged.fastq.gz  --careful  -t 16 -m 48  -o ./spades_out/
spades.py --nanopore  sample_merged.fastq.gz --merged  sample_merged.fastq.gz  --careful  -t 16 -m 48  -o ./spades_out/
```

thank you!

### spades.log

[spades.log](https://github.com/ablab/spades/files/10045311/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10045312/params.txt)

### SPAdes version

3.15.

### Operating System

lnux

### Python Version

3.11.0

### Method of SPAdes installation

binary

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
From manual (https://cab.spbu.ru/files/release3.15.5/manual.html#sec3.1):

To run SPAdes 3.15.5 you need at least one library of the following types:

* Illumina paired-end/high-quality mate-pairs/unpaired reads
* IonTorrent paired-end/high-quality mate-pairs/unpaired reads
* PacBio CCS reads
