### ISSUE TITLE
another err -6

### ISSUE THREAD

**Issue by billyc59** [ablab/spades#105]
Hi, another unexplained error here.
I'm running SPAdes through a docker container (VM)
I've seen another ticket relating to this issue, and I've moved my output folder to an internal location, not a shared folder through the VM volume-mount

Is it simply failing because of an unequal amount of reads on the paired files?
If so, then is there an alternate solution, other than to fix my input data (which really isn't feasible).
Please and thanks! 

[params.txt](https://github.com/ablab/spades/files/1951734/params.txt)
[spades.log](https://github.com/ablab/spades/files/1951736/spades.log)

**Comment by asl** [comment]
I believe the error is clearly explained in the log:

```
Message 'Pair of read files /dump_loc/duplicate_repopulation/data/final_results/pair_1.fastq and /dump_loc/duplicate_repopulation/data/final_results/pair_2.fastq contain unequal amount of reads'.
```
