### ISSUE TITLE
Spades hammer

### ISSUE THREAD

**Issue by irene102497** [ablab/spades#1050]
### Description of bug

System error call for spades-hammer?
<img width="614" alt="Screen Shot 2022-11-22 at 12 43 34 PM" src="https://user-images.githubusercontent.com/62444085/203395868-8d34f0e5-daf6-44bb-a62f-310b12acd4fa.png">

### spades.log

[spades.log](https://github.com/ablab/spades/files/10070161/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10070163/params.txt)

### SPAdes version

SPAdes genome assembler v3.15.2

### Operating System

macOS Monterey 12.6

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
  0:05:03.380  1090M / 1090M ERROR   General                 (hammer_tools.cpp          : 191)   Pair of read files /Users/irenec/Team_project/Smultivorum_R1_paired.fastq and /Users/irenec/Team_project/Smultivorum_R2_paired.fastq contain unequal amount of reads
```

So your input files are corrupted
