### ISSUE TITLE
finished abnormally, OS return value: 21

### ISSUE THREAD

**Issue by Tata12306** [ablab/spades#1051]
### Description of bug

Hi，
I found the error, but I don't know how to solve it. Can you give me some advice?
In the first run, I thought there was something wrong with the file, and I used fastp to filter it, but the second run still had the same problem.

### spades.log

0:00:19.550     1M / 72M   ERROR   General                 (kmer_coverage_model.cpp   : 187)   Invalid kmer coverage histogram, make sure that the coverage is indeed uniform

== Error ==  system call for: "['/Bioinfo/home/liwei/miniconda3/envs/ttt/bin/spades-core', '/Bioinfo/home/liwei/project/HRN-2022041C01.Fz/flow/tmp/getorganelle/test2/result/check/1/animal_mt.check.fq.spades/K45/configs/config.info']" finished abnormally, OS return value: 21

### params.txt

Command line: /Bioinfo/home/liwei/miniconda3/envs/ttt/bin/spades.py     -t      30      -s      /Bioinfo/home/liwei/project/HRN-2022041C01.Fz/flow/tmp/getorganelle/test2/result/check/1/animal_mt.check.fq.more.fq     -k      45      --only-assembler        -o      /Bioinfo/home/liwei/project/HRN-2022041C01.Fz/flow/tmp/getorganelle/test2/result/check/1/animal_mt.check.fq.spades

System information:
  SPAdes version: 3.15.5
  Python version: 3.10.8
  OS: Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.17

Output dir: /Bioinfo/home/liwei/project/HRN-2022041C01.Fz/flow/tmp/getorganelle/test2/result/check/1/animal_mt.check.fq.spades
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: single
      left reads: not specified
      right reads: not specified
      interlaced reads: not specified
      single reads: ['/Bioinfo/home/liwei/project/HRN-2022041C01.Fz/flow/tmp/getorganelle/test2/result/check/1/animal_mt.check.fq.more.fq']
      merged reads: not specified
Assembly parameters:
  k: [45]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /Bioinfo/home/liwei/project/HRN-2022041C01.Fz/flow/tmp/getorganelle/test2/result/check/1/animal_mt.check.fq.spades/tmp
  Threads: 30

### SPAdes version

SPAdes 3.15.5

### Operating System

Linux

### Python Version

Python 3.10.8

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Please attach spades.log file as you were requested.

**Comment by Tata12306** [comment]
ok，these are my log
[params.txt](https://github.com/ablab/spades/files/10120901/params.txt)
[spades.log](https://github.com/ablab/spades/files/10120904/spades.log)

**Comment by asl** [comment]
So, from the log:

```
  0:00:02.826     2M / 43M   INFO    General                 (kmer_splitters.hpp        : 131)   Used 70 reads
```

You're having only 70 reads. This cannot be any meaningful part of any genome with even coverage (since you're assembling in normal multicell mode that expects decent part of a genome with even coverage), hence the error.

**Comment by Tata12306** [comment]
ok.Thank u
