### ISSUE TITLE
Assembling of multiple metatranscriptomics samples together? #1237

### ISSUE THREAD

**Issue by JSSaini** [ablab/spades#1056]
Hello,
I would like to co-assemble multiple metatranscriptomics samples together. Or giving multiple samples as input instead of one. Would it be possible to do it with rnaSPAdes? Thank you.

Kind regards,
Jaspreet

**Comment by andrewprzh** [comment]
Dear Jaspreet

Yes, I suggest to provide all samples as a sinlge library (if the were sequenced using the same protocol and have e.g. the same insert size) using --pe1-1 --pe1-2 options. This way you'll most likely get the most complete metatranscriptome assembly.
You can find some examples here: https://github.com/ablab/spades#examples

If you are interested in quantification, I suggest to further map reads back to assembled transcripts to estimate their per-sample abundances.

Best
Andrey

**Comment by JSSaini** [comment]
Thank you for taking time to answer this query. :D
I will give it a try.

**Comment by sumitra20** [comment]
Hi @andrewprzh , @JSSaini ,

I have over 32 paired-end metaT samples that i would to assembly. Just confused on how to give all the files as input. What does it mean by providing all the samples as **single library**? Does it mean that i should merge all by forward sequences into one file and reverse sequences into another and then provide them as an input using --pe1-1 --pe1-2 options?
