### ISSUE TITLE
finished abnormally, OS return value: -11

### ISSUE THREAD

**Issue by avinashkarkada** [ablab/spades#1063]
### Description of bug

Hello, I am facing the following error when running spades.

`==Error ==  system call for: "['/home/***/Documents/SPAdes-3.15.5-Linux/bin/spades-hammer', '/home/***/Documents/SPAdes-3.15.5-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11`

### spades.log

Here is the log file
[test.log](https://github.com/ablab/spades/files/10333308/test.log)
[spades.log](https://github.com/ablab/spades/files/10333314/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10333316/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux-5.15.0-56-generic-x86_64-with-glibc2.35

### Python Version

3.10.6

### Method of SPAdes installation

binaries

**Comment by avinashkarkada** [comment]
I no longer face the error once I compiled it :)

**Comment by asl** [comment]
Thanks for letting us know!

**Comment by Arthurdyu** [comment]
> I no longer face the error once I compiled it :)

can you tell me how to compiled it ? I don't understand, thanks a lot!

**Comment by asl** [comment]
> > I no longer face the error once I compiled it :)
> 
> can you tell me how to compiled it ? I don't understand, thanks a lot!

Do you happen to know that SPAdes manual does exist? Have you checked it? And that is contains lots of necessary information including this one: https://cab.spbu.ru/files/release3.15.5/manual.html#sec2.3

**Comment by Arthurdyu** [comment]
> > > I no longer face the error once I compiled it :)
> > 
> > 
> > can you tell me how to compiled it ? I don't understand, thanks a lot!
> 
> Do you happen to know that SPAdes manual does exist? Have you checked it? And that is contains lots of necessary information including this one: https://cab.spbu.ru/files/release3.15.5/manual.html#sec2.3🔄  ❓🔄  ❓

Really appreciate it!
`./spades_compile.sh`
 it looks like I'm succeeding,  there's a warming, but not an error.
[spades-log_20231211.txt](https://github.com/ablab/spades/files/13632765/spades-log_20231211.txt)
