### ISSUE TITLE
SPAdes-3.11.1-Linux finished abnormally, err code: -6

### ISSUE THREAD

**Issue by jnarayan81** [ablab/spades#107]
=== ITERATION 0 begins ===
  0:00:00.022     4M / 4M    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 289)   Building kmer index
  0:00:00.022     4M / 4M    INFO    General                 (kmer_index_builder.hpp    : 106)   Splitting kmer instances into 768 buckets using 48 threads. This might take a while.
  0:00:00.022     4M / 4M    INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1024
  0:00:00.022     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  74)   Memory available for splitting buffers: 1.73608 Gb
  0:00:00.022     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  82)   Using cell size of 87381
  0:00:00.208    26G / 26G   INFO   K-mer Splitting          (kmer_data.cpp             :  96)   Processing /home/urbe/Tools/SPAdes-3.11.1-Linux/bin/HybridSpades_Avaga/split_input/GC047403.170925_ARC__1.fastq
  0:00:56.968    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 6599609 reads
  0:03:24.390    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 13204051 reads
  0:07:50.977    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 19735912 reads
  0:11:39.846    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 26271185 reads
  0:14:02.996    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 32883381 reads
  0:15:28.017    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 39490119 reads
  0:16:07.473    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 46069893 reads
  0:16:49.442    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 52641564 reads
  0:17:29.381    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 59211441 reads
  0:18:09.609    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 65801220 reads
  0:18:40.730    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 71075556 reads
  0:18:40.730    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             :  96)   Processing /home/urbe/Tools/SPAdes-3.11.1-Linux/bin/HybridSpades_Avaga/split_input/GC047403.170925_ARC__2.fastq
  0:21:57.425    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 77670154 reads
  0:33:48.514    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 137417851 reads
  0:34:16.521    26G / 28G   INFO   K-mer Splitting          (kmer_data.cpp             : 111)   Total 142151112 reads processed
  0:34:19.117   192M / 28G   INFO    General                 (kmer_index_builder.hpp    : 109)   Starting k-mer counting.
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
[0x407a6a]
[0x448a0c]
[0x439b0b]
[0x537189]
[0x53fa3d]
[0x57e719]
[0x407a6a]
[0x448a0c]
[0x439b0b]
[0x537189]
[0x53fa3d]
[0x57e719]
hammer: /spades/src/common/utils/kmer_mph/kmer_index_builder.hpp:197: size_t utils::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&, unsigned int) [with Seq = Seq<21ul>; traits = utils::kmer_index_traits<Seq<21ul> >; size_t = long unsigned int; std::string = std::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed.

== Error ==  system call for: "['/home/urbe/Tools/SPAdes-3.11.1-Linux/bin/hammer', '/home/urbe/Tools/SPAdes-3.11.1-Linux/bin/HybridSpades_Avaga/corrected/configs/config.info']" finished abnormally, err code: -6

**Comment by asl** [comment]
Such error is usually happens due to prior I/O problem on your side. As the result some SPAdes' intermediate files got corrupted. The next version of SPAdes will include better error checking for I/O fails much earlier.
