### ISSUE TITLE
 ERROR: Too many erroneous kmers, the estimates might be unreliable

### ISSUE THREAD

**Issue by jmhallas** [ablab/spades#1071]
### Description of bug

Hello,

I have a looked up a few other posts about this error but still unsure how to correct it. Even though the spades.log says `SPAdes pipeline finished WITH WARNINGS!` a fasta file is not generated. After look at the get_org.log file, it looks like there was an error in slimming. So then I looked into the slim.log and it says `ERROR: BLAST Database error: No alias or index file found for nucleotide database [/home/jhallas/.GetOrganelle/LabelDatabase/animal_mt] in search path [/share/cdfwwildlife/hallas_dedicated/lc_deer/scripts::]`. I assembled 79 other genomes and this is the only one that encountered this error.  I am using a circular mtDNA genome from the same species as the seed. My sequencing coverage is 25X.

### spades.log

[spades.log](https://github.com/ablab/spades/files/10540566/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10540572/params.txt)

### SPAdes version

SPAdes version: 3.13.0

### Operating System

OS: Linux-4.15.0-142-generic-x86_64-with-glibc2.17

### Python Version

Python version: 3.8.15

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
SPAdes finished successfully:

```
 * Corrected reads are in /share/cdfwwildlife/hallas_dedicated/lc_deer/mtDNA/getorganelle/DB10020/extended_spades/corrected/
 * Assembled contigs are in /share/cdfwwildlife/hallas_dedicated/lc_deer/mtDNA/getorganelle/DB10020/extended_spades/contigs.fasta
 * Assembled scaffolds are in /share/cdfwwildlife/hallas_dedicated/lc_deer/mtDNA/getorganelle/DB10020/extended_spades/scaffolds.fasta
 * Assembly graph is in /share/cdfwwildlife/hallas_dedicated/lc_deer/mtDNA/getorganelle/DB10020/extended_spades/assembly_graph.fastg
 * Assembly graph in GFA format is in /share/cdfwwildlife/hallas_dedicated/lc_deer/mtDNA/getorganelle/DB10020/extended_spades/assembly_graph_with_scaffolds.gfa
 * Paths in the assembly graph corresponding to the contigs are in /share/cdfwwildlife/hallas_dedicated/lc_deer/mtDNA/getorganelle/DB10020/extended_spades/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in /share/cdfwwildlife/hallas_dedicated/lc_deer/mtDNA/getorganelle/DB10020/extended_spades/scaffolds.paths
```

SPAdes does not use BLAST and this is not from SPAdes log. Likely you're using some wrapper / pipeline, so the problem is not with SPAdes, I would suggest you to report your problem elsewhere
