### ISSUE TITLE
System call finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by MooseyGoosey** [ablab/spades#1073]
### Description of bug

I'm using spades through unicycler. Midway through running the assembly it fails proviing the following error: 

== Error ==  system call for: "['/shared/Project1_Resources/Group2/shared_envs/unicycler/bin/spades-core', '/shared/Project1_Resources/Group2/assemblies/hybrid/S5/spades_assembly/K15/configs/config.info', '/shared/Project1_Resources/Group2/assemblies/hybrid/S5/spades_assembly/K15/configs/isolate_mode.info']" finished abnormally, OS return value: -9
None

I looked at some other issues on the github and saw that it might be a memory problem, so I increased the memory from 15Gb to 30GB (the maximum I'm able to use) but am getting the same error. I'm not sure what else to do. My spades.log and params.txt are attached.

### spades.log

[spades.log](https://github.com/ablab/spades/files/10571885/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10571887/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux

### Python Version

3.10.8

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Why are you running with `-k 15` alone?

**Comment by MooseyGoosey** [comment]
> Why are you running with `-k 15` alone?

I'd just used the unicycler default, which says automatic

**Comment by asl** [comment]
This does not make any sense to me. Just run SPAdes with default parameters.

**Comment by MooseyGoosey** [comment]
> This does not make any sense to me. Just run SPAdes with default parameters.

As far as I'm aware this is default parameters as I didn't specify any command line options

**Comment by asl** [comment]
> > This does not make any sense to me. Just run SPAdes with default parameters.
> 
> As far as I'm aware this is default parameters as I didn't specify any command line options

No, it is not. We are not aware about any strange decisions Unicycler might do. Simple use SPAdes.

**Comment by MooseyGoosey** [comment]
> > > This does not make any sense to me. Just run SPAdes with default parameters.
> > 
> > 
> > As far as I'm aware this is default parameters as I didn't specify any command line options
> 
> No, it is not. We are not aware about any strange decisions Unicycler might do, though. Simple use SPAdes.

Thanks, will give it a try without unicycler

**Comment by MooseyGoosey** [comment]
Worked as expected with the above advice.
