### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by hkaur98** [ablab/spades#1075]
### Description of bug

I tried reading in the older/closed issues about error code -6 but couldn't find a similar error I see in my spades and params.txt. I am running Unicycler with SpAdes version: 3.13.1. Not sure if the error I am seeing is more likely SpAdes version problem or something else. Attached are my spades.log and params.txt files. 

Any help would be greatly appreciated. Thank you! 

### spades.log

[spades.log](https://github.com/ablab/spades/files/10677740/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10677741/params.txt)

### SPAdes version

SpAdes 3.13.1

### Operating System

Linux-5.15.0-58-generic-x86_64-with-glibc2.29

### Python Version

Python 3.8.10

### Method of SPAdes installation

command line

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:
```
Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```

And indeed, it seems you're only having 700 reads, which are highly unlikely to yield a genome of any bacteria known to me.

**Comment by hkaur98** [comment]
Sorry, just to add to that- these are Phage genomes and not bacteria. Would it produce errors if there are no bacterial genomes?

**Comment by hkaur98** [comment]
Sorry, I wasn't aware I needed to change the mode, but it worked perfectly fine! Thank you so much for your time and help.

**Comment by asl** [comment]
Well... you need to chose proper tool for the task.
