### ISSUE TITLE
Small viral contigs in denovo assembly using spades

### ISSUE THREAD

**Issue by MonicaSteffi** [ablab/spades#1086]
### Description of bug

Dear All,

I am trying spades to perform de novo assembly for my viral genomes. Unfortunately, these viral genomes have no references to compare with. For some of the samples, I got 40kb to 90kp contigs. But for some, I get only 3000 bp to 5000 bp contigs. What could be the reason (both technical and biological reasons) behind this? If this is due to technical issues, how do I improve the assembly to get a contig with more kb?

I also check the log file but couldn't find anything alarming

Thank you in advance

Regards Monica

### spades.log

[spades.log](https://github.com/ablab/spades/files/10791559/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10791570/params.txt)

### SPAdes version

 3.15.4

### Operating System

Linux-4.12.14-197.40-default-x86_64-with-glibc2.26

### Python Version

 3.10.9

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Tagging & assigning to metaviralSPAdes author @Dmitry-Antipov
