### ISSUE TITLE
Metagenome hybrid assembly with hybridspades or metaspades?

### ISSUE THREAD

**Issue by cmaggior** [ablab/spades#109]
Hello,

I'm interested in performing a hybrid assembly with Illumina and Oxford Nanopore data of an environmental metagenome. Is this currently supported in hybridspades or metaspades? Could you use the --meta option in spades for this?

Thank you!

**Comment by asl** [comment]
Yes, it is supported. Though, I would strongly suggest you to wait until SPAdes 3.12 release (hopefully until next week) that contains major improvements there.

**Comment by cmaggior** [comment]
Great news! Thanks for your response!

**Comment by asl** [comment]
Fixed in SPAdes 3.12
