### ISSUE TITLE
Shorten/Modify contig names

### ISSUE THREAD

**Issue by rialc13** [ablab/spades#1090]
### Is your feature request related to a problem? Please describe. For generic questions use Q&A section in the Discussions forum above.

Hi. Is there a way to shorten the contig names or limit the names to a specific character length? I encountered an issue while performing Prokka after Spades. The maximum contig id length in Prokka is set to 37 to comply with genbank file format rules. However, the contig id names generated from Spades are too long because of which I am unable to perform Prokka.

### Describe the solution you'd like

A solution could be limiting the number of characters in the contig id name with the help of a flag or a flag could be created as '--shorten' to generate short contig names.

**Comment by asl** [comment]
Hello

Well, there are plethora of possible formats and shortcomings of particular pieces of software. It is not possible to uniformly accommodate all of them. However. it's pretty easy to rename contigs externally via e.g. `bioawk` or similar tools.

This is the approach we are suggesting to tackle.
