### ISSUE TITLE
How to get multiple assembly sequences at the same time?

### ISSUE THREAD

**Issue by ZhouHY-77** [ablab/spades#1092]
### Description of bug

Hello, I want to use SPAdes to assemble Several Illumina bacterial sequencing data at the same time, the command I use is as follows:
python spades.py --isolate --pe1-1 /home/dell/spades/projects/demo/058_1.clean.fq.gz --pe1-2 /home/dell/spades/projects/demo/058_2.clean.fq.gz \
> --pe2-1 /home/dell/spades/projects/demo/059_1.clean.fq.gz --pe2-2 /home/dell/spades/projects/demo/059_2.clean.fq.gz \
> -o /home/dell/spades/projects/demo/output

I input the sequencing data for 2 strains, but in the output folder, only one scaffolds.fasta is shown. i would like to know what went wrong, thank you

### spades.log

[spades.log](https://github.com/ablab/spades/files/10809936/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/10809938/params.txt)

### SPAdes version

v3.15.5

### Operating System

CentOS Linux release 7.9.2009 (Core)

### Python Version

Python 3.9.13

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Nothing is wrong. You need to run SPAdes for your data separately for different samples
