### ISSUE TITLE
spades-hammer cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by scleractinia** [ablab/spades#1097]
### Description of bug

when i am running the test script 
spades.py --test

I am getting a mac error with this message "spades-hammer cannot be opened because the developer cannot be verified"  

Not sure haw to continue if this is failing 

### spades.log

None, I was running the spades.py --test command

### params.txt

None, I was running the spades.py --test command

### SPAdes version

SPAdes v3.15.5

### Operating System

macOS Ventura 13.0

### Python Version

Python 3.6.15

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

This is a standard macOS thing. Refer to https://support.apple.com/en-gb/guide/mac-help/mh40616/mac for instructions how you can make binaries run on your system. You'd need to do this for `spades-hammer` and `spades-core` at least.
