### ISSUE TITLE
metaspades errors

### ISSUE THREAD

**Issue by blondie5125** [ablab/spades#110]
Hi, I am trying to run MetaSPAdes and I am consistently getting an error code -6. I realize, this will be a fix in an upcoming release, but is there a way to work around it? My code is aborting at k value 55 due the the issues listed below. I have attached my params.txt for reference. The dataset I am using is too large to attach, but it is a fastq file of reads that have been processed, trimmed and merged. I have attached a similar, smaller file from the same source for example.
[2NoAdapt_AFRICAN6_lAGGCCTA_rCTTGGAC_R1R2_Collapsed.fastq.gz](https://github.com/ablab/spades/files/1981613/2NoAdapt_AFRICAN6_lAGGCCTA_rCTTGGAC_R1R2_Collapsed.fastq.gz)

== Error ==  system call for: "['/home/sjj0060/$HOME/SPAdes-3.11.1-Linux/bin/spades', '/storage/scratch2/sjj0060/SPYoldMetaspades2/K55/configs/config.info', '/storage/scratch2/sjj0060/SPYoldMetaspades2/K55/configs/mda_mode.info', '/storage/scratch2/sjj0060/SPYoldMetaspades2/K55/configs/meta_mode.info']" finished abnormally, err code: -6

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:06:26.246     1G / 17G   WARN    General                 (pair_info_count.cpp       : 200)   Too much reads aligned with negative insert size. Is the library orientation set properly?
 * 0:06:26.250     1G / 17G   WARN    General                 (pair_info_count.cpp       : 336)   Unable to estimate insert size for paired library #0
 * 0:06:26.250     1G / 17G   WARN    General                 (pair_info_count.cpp       : 342)   None of paired reads aligned properly. Please, check orientation of your read pairs.
 * 0:06:28.183     1G / 17G   WARN    General                 (repeat_resolving.cpp      :  63)   Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.
======= Warnings saved to /storage/scratch2/sjj0060/SPYoldMetaspades2/warnings.log

[params3.txt](https://github.com/ablab/spades/files/1981588/params3.txt)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Well, which part of warnings / errors messages is not clear to you? The problem seems to be directly seen from the log – your input files are corrupted somehow.

**Comment by blondie5125** [comment]
Thank you for the quick response,


I am confused as to why the process is successful for k values 21 and 33, but not 55, and subsequently unable to create contigs/scaffolds.

________________________________

**Comment by asl** [comment]
This is how the SPAdes works – the information from low k-mers is used to improve the results on larger k-mers (the so-called "iterative approach"). The last k-mer size is always the main one.

**Comment by blondie5125** [comment]
Question from a different dataset,

I have files I received from running FLASH, including one with extended fragments and two that remained uncombined.
The manual says if I have merged a paired-end library with overlapping read-pairs, I can provide the resulting reads as a single-read library.
Does this mean I can only use the output file with the merged ends and ignore the other two not-combined files? Or can I include all in the Metaspades analysis?




________________________________

**Comment by asl** [comment]
Per metaSPAdes manual (http://cab.spbu.ru/files/release3.11.1/manual.html#meta):

```
--meta   (same as metaspades.py)
    This flag is recommended when assembling metagenomic data sets (runs metaSPAdes, see paper for more details). Currently metaSPAdes supports only a single library which has to be paired-end (we hope to remove this restriction soon). It does not support careful mode (mismatch correction is not available). In addition, you cannot specify coverage cutoff for metaSPAdes. Note that metaSPAdes might be very sensitive to presence of the technical sequences remaining in the data (most notably adapter readthroughs), please run quality control and pre-process your data accordingly.
```

Therefore, please provide to metaSPAdes original (unmerged) reads.

**Comment by snurk** [comment]
Note that the 3.12 release will have a special option to include merged reads as well.
