### ISSUE TITLE
 finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by zzsunday** [ablab/spades#1108]
### Description of bug

  1:15:16.122    30G / 35G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 39984700 reads
  1:15:42.772    30G / 35G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 44257993 reads
  1:18:21.571    30G / 35G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 69950478 reads
  1:18:30.965    30G / 35G   INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 71428348 reads processed
  1:18:30.966    21G / 35G   INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  1:24:37.348    21G / 88G   INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 2999345676 kmers in total.
  1:24:40.311    18M / 88G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  1:26:35.634  2151M / 88G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 2999345676 kmers, 2166331632 bytes occupied (5.77814 bits per kmer).
  1:26:35.635  2151M / 88G   INFO   K-mer Counting           (kmer_data.cpp             : 354)   Arranging kmers in hash map order
  1:28:11.500    47G / 88G   INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  2:04:53.426    47G / 88G   INFO    General                 (main.cpp                  : 155)   Extracting clusters:
  2:04:53.427    47G / 88G   INFO    General                 (concurrent_dsu.cpp        :  18)   Connecting to root
  2:04:57.404    47G / 88G   INFO    General                 (concurrent_dsu.cpp        :  34)   Calculating counts

== Error ==  system call for: "['/public/home/bh2022044/00_softwares/micromamba/envs/asm/bin/spades-hammer', '/public/home/bh2022044/sunda/wastewater/04_metaspades/USAB/DZY09Y1A_asm/corrected/configs/config.info']" finished abnormally, OS return value: -9

### spades.log

[spades.log](https://github.com/ablab/spades/files/11013088/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11013090/params.txt)

### SPAdes version

SPAdes version: 3.15.5

### Operating System

Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core

### Python Version

 Python version: 3.6.15

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Your SPAdes job was killed. Likely more information could be found in the system log.

**Comment by zzsunday** [comment]
> 

thank you asl, it is do killed by system, because of out of memory
