### ISSUE TITLE
finished abnormally, OS return value: 2

### ISSUE THREAD

**Issue by Soumyadutta-basak** [ablab/spades#1109]
### Description of bug

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:21.925   143M / 6957M WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:00:41.686   201M / 6897M WARN    General                 (simplification.cpp        : 500)   The determined erroneous connection coverage threshold may be determined improperly
 * 0:00:52.956   538M / 6897M WARN    General                 (pair_info_count.cpp       : 376)   Estimated mean insert size 133.756 is very small compared to read length 151
======= Warnings saved to /home/student/Remove_Duplicates/mapped_reads/SPADES_62_B2/warnings.log

### spades.log

[spades.log](https://github.com/ablab/spades/files/11025472/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11025474/params.txt)

### SPAdes version

SPAdes genome assembler v3.15.2

### Operating System

Ubuntu 18.04.5 LTS

### Method of SPAdes installation

conda 

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
[mem_sam_pe] paired reads have different names: "VH00293:1:AAAG5HTHV:1:2305:51387:15862", "VH00293:1:AAAG5HTHV:1:2406:66801:45432"
```

So, your input reads are corrupted: the left ones do not correspond to the right ones.
