### ISSUE TITLE
Warnings using metaspades

### ISSUE THREAD

**Issue by kmkappa** [ablab/spades#1110]
### Description of bug

When running metaspades I get the error :

=== Error correction and assembling warnings:
 * 0:01:01.063   346M / 1830M WARN    General                 (pair_info_count.cpp       : 358)   Unable to estimate insert size for paired library #0
 * 0:01:01.063   346M / 1830M WARN    General                 (pair_info_count.cpp       : 364)   None of paired reads aligned properly. Please, check orientation of your read pairs.
 * 0:01:01.063   346M / 1830M WARN    General                 (repeat_resolving.cpp      :  81)   Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.
 * 0:01:23.567   252M / 1830M WARN    General                 (pair_info_count.cpp       : 187)   Single reads are not used in metagenomic mode
======= Warnings saved to /home/gs66/spades_assembly_atlasparams/warnings.log

### spades.log

[spades.log](https://github.com/ablab/spades/files/11034746/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11034765/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux-5.19.0-35-generic-x86_64-with-glibc2.36

### Python Version

3.11.0

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The message indicates that your input reads are corrupted: left ones do not correspond to the right ones. If you use any kind of pre-processing tools, ensure that they are paired-end aware.
