### ISSUE TITLE
finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by rajneeshdadwal** [ablab/spades#1112]
### Description of bug

I am receiving an error mentioned as title of issue when processing 250-300 read lengths of illumina datasets (no scaffolds.fasta or contigs.fasta is generated) whereas when running spades on datasets with 150 read length of illumina datasets it runs fine, I have attached the log file and params file for your consideration. please have a look at the same.

The error message is there in the spades.log file but still submitting the issue as i could not locate a solution for the same.

### spades.log

[spades.log](https://github.com/ablab/spades/files/11041760/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11041757/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-kali-rolling

### Python Version

3.7.12

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
The log reads:

```
mimalloc: error: unable to allocate OS memory (268435456 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
```

So you're running out of RAM. I'm afraid you cannot assemble your dataset having such low memory

**Comment by rajneeshdadwal** [comment]
the system has 16gb of ram and wsl uses 8 gb isnt that enough to use spades?

**Comment by asl** [comment]
Apparently not for your dataset

**Comment by rajneeshdadwal** [comment]
what is the minimum ram required for the same?

**Comment by asl** [comment]
There is no way to estimate required RAM as it depends on many things including e.g. coverage, error rate, genome size, 
repeat contents, etc.
