### ISSUE TITLE
SPAdes assembly error <error code:12 >

### ISSUE THREAD

**Issue by manas12jmp** [ablab/spades#1115]
### Description of bug

Hey there,
I run metagenomics data set  (Illumina 2x150) and got this after the firs iteration with Spades. I tried <--only-assembler> for concern like certain memory.
Please help me to understand my error.

### spades.log

[spades.log](https://github.com/ablab/spades/files/11075070/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11075067/params.txt)

### SPAdes version

v3.15.5

### Operating System

Ubuntu 22.04.2 LTS

### Python Version

Python 3.10.6

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
  0:15:26.036  5051M / 11G   ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
```

So, you're running out of RAM.

You cannot assemble dataset of such size having just 15 Gb of RAM. I'd estimate you need 10x of that at least.
