### ISSUE TITLE
run defeat

### ISSUE THREAD

**Issue by shujiuli** [ablab/spades#1116]
### Description of bug

After installed,I try to run spades.py --test,and use it assemble my dataset,both can't yield the result.The error log will be submited.Hope response

### spades.log

[spades.log](https://github.com/ablab/spades/files/11084943/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11084944/params.txt)

### SPAdes version

SPAdes v3.15.5

### Operating System

ubuntu 22.04.2

### Python Version

python 3.10.6

### Method of SPAdes installation

Linux binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
It seems that the file system on `/media/sjl/` does not support memory mapped files. Consider moving SPAdes scratch & output directories somewhere else, e.g. to proper file system and not some shared folder / external USB media.

**Comment by shujiuli** [comment]
Thank you for your help,I will retry
