### ISSUE TITLE
resume with more memory

### ISSUE THREAD

**Issue by tauanajc** [ablab/spades#1123]
By design you need just run with --checkpoint all and for restart run only spades only with --continue and  -o. 

_Originally posted by @olga24912 in https://github.com/ablab/spades/issues/956#issuecomment-1076734404_
            
Dear Olga,
I have an assembly that keeps failing due to memory (already gave it 500GB). Last time I used all checkpoints to be able to resume in case that happened again. I am trying to relaunch it using just flags --continue -o flags, and --memory 600, but it fails saying I cannot give it any flags other then --continue and -o. How can I restart with more memory without giving it the flag for memory?…

Thanks in advance!

Command:
spades.py -t 16 --memory 600 --continue -o spades

Log:

Fri Apr  7 15:03:45 CDT 2023

== Error ==  you cannot specify any option except -o with --continue option! Please use '--restart-from last' if you need to change some of the options from the initial run and continue from the last available checkpoint.

**Comment by asl** [comment]
The log clearly reads:
```
== Error == you cannot specify any option except -o with --continue option! Please use '--restart-from last' if you need to change some of the options from the initial run and continue from the last available checkpoint.
```

Have you tried to do as you were suggested? E.g. `spades.py -t 16 --memory 600 --restart-from last -o spades`?
