### ISSUE TITLE
Error: OS return value 21

### ISSUE THREAD

**Issue by pratibha-kadam** [ablab/spades#1124]
### Description of bug

I am running spade to assemble Contigs.

System info:
I am running spades on Ubuntu LTS in Windows 10
RAM: 32 GB 
Processors: 16

The error is about RAM which says-
The reads contain too many k-mers to fit into available memory. You need approx. 99.7624GB of free RAM to assemble your dataset   

Please let me know the soltution to run the command on my computer.

### spades.log

[spades.log](https://github.com/ablab/spades/files/11196782/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11196784/params.txt)

### SPAdes version

SPAdes v.3.15.5-Linux

### Operating System

Windows

### Python Version

Python 3.9.7

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Well, per error message – you need more RAM to assemble your dataset. Consider moving to larger machine / server.
