### ISSUE TITLE
finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by xhuang495** [ablab/spades#1126]
### Description of bug

Hello,

I have several viromic date on which I am trying to run metaviralspades. Some of them completed without issue, but one of them got problems. 

Here are the output documents:

### spades.log

[spades.log](https://github.com/ablab/spades/files/11234125/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11234127/params.txt)

### SPAdes version

SPAdes_v3.15.5

### Operating System

Linux

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
Hello

This bug was fixed in SPAdes 3.15.2 You are using 3.15.0. Consider upgrading to the latest 3.15.5

**Comment by xhuang495** [comment]
Hi,
Thank you for your quick reply, I have installed and tested different versions of SPAdes (including 3.15.0; 3.15.2; 3.15.5) and found that the spades version in the testing spades.log file is 3.15.0, how can I update it to 3.15.5? I suspect that the new version of spades.py is not loaded to the corresponding version. 

Here is the head lines of test spades.log in SPAdes_v3.15.2:
Command line: /slowdata/bin/spades.py	--test	

System information:
  SPAdes version: 3.15.0
  Python version: 2.7.17
  OS: Linux-5.4.0-144-generic-x86_64-with-Ubuntu-18.04-bionic

Output dir: /storage1/data25/miniconda3/envs/spades_v3.15.2/SPAdes-3.15.2-Linux/bin/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

**Comment by xhuang495** [comment]
It's work! Thank u so much!
