### ISSUE TITLE
spades-hammer: OS return value: -6

### ISSUE THREAD

**Issue by lmrodriguezr** [ablab/spades#1129]
### Description of bug

Dear all,

I'm encountering an exit code -6 from spades-hammer when trying to co-assemble a metagenomic sample with 3 paired-end runs. This is the message I receive:
```
== Error ==  system call for: "['/gpfs/gpfs1/scratch/c7181116/apps/SPAdes-3.15.5-Linux/bin/spades-hammer', '/gpfs/gpfs1/scratch/c7181116/projects/fire/02.metagenomes/03.assembly/BC/corrected/configs/config.info']" finished abnormally, OS return value: -6
```

Is there a list of error codes somewhere? I couldn't find what -6 return value means.

Thanks a lot!
Miguel.

### spades.log

[spades.log](https://github.com/ablab/spades/files/11276238/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11276242/params.txt)

### SPAdes version

v3.15.5

### Operating System

Rocky Linux 8.6 (Green Obsidian)

### Python Version

3.9.7

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:

```
  3:08:05.424    82G / 91G   ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
  3:08:05.424    82G / 91G   ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
```

So you're running out of RAM
