### ISSUE TITLE
mmapped_reader.hpp failing for two reasons

### ISSUE THREAD

**Issue by PlantDr430** [ablab/spades#113]
Hello,

Below is the log file:

[spades.log](https://github.com/ablab/spades/files/1988825/spades.log)

My kmer corrections are finishing, but I appear to be having errors occur during the assembly when the script is trying to run MMappedReader.

Any suggestions?

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes

The log reads
```
Message 'open(2) failed. Reason: Too many open files. Error code: 24
```

You may want to increase the open file limit via "ulimit -n" command
