### ISSUE TITLE
--assembly_graph parameter does not seem to work

### ISSUE THREAD

**Issue by rbtoscan** [ablab/spades#1132]
### Description of bug

Hello,

I am trying to run metaviralspades using metaspades assembly assembly graph as a parameter, but with no success.

This is my command:
```
spades.py--metaviral -t 100  -1 ZRH_6_tmp_1.fastq.gz -2 ZRH_6_tmp_2.fastq.gz --assembly_graph metaspades/K77/assembly_graph_with_scaffolds.gfa    -k77  -o metaviralspades_on_metaspades_graph
```
And this is message I get: 

```
SPAdes genome assembler v3.15.5 [metaviralSPAdes mode]
Usage: spades.py [options] -o <output_dir>
spades.py: error: Please specify option (e.g. -1, -2, -s, etc)) for the following paths: --assembly_graph, metaspades/K77/assembly_graph_with_scaffolds.gfa
```

Prior to that, I did a normal metaspades run:

`spades.py  -t 100  -1 ZRH_6_tmp_1.fastq.gz -2 ZRH_6_tmp_2.fastq.gz -o metaspades`

And the files inside my standard metaspades run seem to be okay, including the scaffolds and the gfa files.

```
cd metaspades
find . -name "*gfa"
./K77/assembly_graph_with_scaffolds.gfa
./K77/assembly_graph_after_simplification.gfa
./assembly_graph_with_scaffolds.gfa
./assembly_graph_after_simplification.gfa

 find . -name "*scaffolds*"
./scaffolds.paths
./K77/scaffolds.paths
./K77/assembly_graph_with_scaffolds.gfa
./K77/scaffolds.fasta
./assembly_graph_with_scaffolds.gfa
./scaffolds.fasta
./misc/broken_scaffolds.fasta
```

I believe I am providing the correct parameters. Could I please get some help with that? Has someone managed to run meta(viral)spades using .gfa file as parameter?

Thank you!

### spades.log

Is not generated.

### params.txt

Is not generated.

### SPAdes version

v3.15.5

### Operating System

Ubuntu 20.04.6 LTS

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Per manual, it's: `--assembly-graph <file_name>` not `--assembly_graph`

**Comment by rbtoscan** [comment]
Hi Anton,

thanks for the reply. It was a typo in my last command, but please see an updated version below:

```
spades.py --metaviral -t 100  -1 ZRH_6_tmp_1.fastq.gz -2 ZRH_6_tmp_2.fastq.gz --assembly-graph metaspades/K77/assembly_graph_with_scaffolds.gfa    -k77  -o metaviralspades_on_metaspades_graph


== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz are supported): /storage/testing_tools/camp_viral/TESTING_TOOLS/metaspades/K77/assembly_graph_with_scaffolds.gfa (single reads, library number: 1, library type: assembly-graph)

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
```

**Comment by rbtoscan** [comment]
As you can see, I still have an issue. I changed the issue title now.

**Comment by asl** [comment]
You need to add `--only-assembler` as well

**Comment by rbtoscan** [comment]
That worked. Awesome!! Thank you very much!
