### ISSUE TITLE
SPAdes-3.16.0-dev-Linux errors

### ISSUE THREAD

**Issue by EvolDoc** [ablab/spades#1141]
### Description of bug

[Errors.txt](https://github.com/ablab/spades/files/11511561/Errors.txt)

### spades.log

[spades.log](https://github.com/ablab/spades/files/11511550/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11511553/params.txt)

### SPAdes version

3.16.0-dev

### Operating System

Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.17

### Python Version

3.10.4

### Method of SPAdes installation

manual from https://cab.spbu.ru/software/wastewaterspades/

### No errors reported in spades.log

- [X] Yes

**Comment by 1dayac** [comment]
Hello @EvolDoc!

The problem was that an incorrect version of pyyaml3 has made it into the wastewaterspades build. 
We updated the build at the website, so it should run smoothly now, please give it a try

Thanks,
Dmitry

**Comment by EvolDoc** [comment]
Thank you! It now starts processing, but produces a different error now (GLIBC error?):

[spades.log](https://github.com/ablab/spades/files/11525695/spades.log)
[params.txt](https://github.com/ablab/spades/files/11525697/params.txt)

**Comment by asl** [comment]
It seems you compiled it with non-system compiler. So additional library search paths should be provided. I would suggest you to ask your system administrator for information how to do this locally

**Comment by 1dayac** [comment]
@EvolDoc, Also I checked your spades.log and not really sure that wastewaterSPAdes is what you need. I would suggest using coronaSPAdes if you want to assemble enteroviral genomes (maybe you will need to provide a non-standard set of HMMs using --custom-hmms options).
wastewaterSPAdes works only with SARS-CoV-2, since it uses SARS-CoV-2 variant matrix to assign relative abundances to the strains and will not work with Enteroviruses

**Comment by EvolDoc** [comment]
I see...I didn't realize it was limited to coronaviruses. Assembling the enteroviral genomes isn't the problem for us. Rather, it is variant deconvolution because we are sequencing enteroviruses (and other viruses) from wastewater. Thank you for your help! I'm wondering how difficult it would be to make variant matrices for other viruses.
