### ISSUE TITLE
/ Failed to load config file / == Error ==  system call for: "['/usr/lib/spades/bin/spades-corrector-core',

### ISSUE THREAD

**Issue by sudhan2709** [ablab/spades#1142]
### Description of bug

Hello, 

I am getting the below message, could u pls help me out, what to do next, if i get the below message at the end spades assembler complete.
-Thanks
                                           
== Running contig polishing tool: /usr/lib/spades/bin/spades-corrector-core /mnt/g/user/sc_analysis_files/spades-3.15.2-linux/spades_careful_assembly/mismatch_corrector/contigs/configs/corrector.info /mnt/g/user/sc_analysis_files/spades-3.15.2-linux/spades_careful_assembly/misc/assembled_contigs.fasta

== Dataset description file was created: /mnt/g/user/sc_analysis_files/spades-3.15.2-linux/spades_careful_assembly/mismatch_corrector/contigs/configs/corrector.info

/mnt/g/user/sc_analysis_files/spades-3.15.2-linux/spades_careful_assembly/mismatch_corrector/contigs/configs/corrector.info:4:23: error: invalid number
"max_nthreads": !!int "-6"
                      ^~~~
Failed to load config file /mnt/g/user/sc_analysis_files/spades-3.15.2-linux/spades_careful_assembly/mismatch_corrector/contigs/configs/corrector.info

== Error ==  system call for: "['/usr/lib/spades/bin/spades-corrector-core', '/mnt/g/user/sc_analysis_files/spades-3.15.2-linux/spades_careful_assembly/mismatch_corrector/contigs/configs/corrector.info', '/mnt/g/user/sc_analysis_files/spades-3.15.2-linux/spades_careful_assembly/misc/assembled_contigs.fasta']" finished abnormally, err code: 4

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

### spades.log

[spades.log](https://github.com/ablab/spades/files/11524976/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11524977/params.txt)

### SPAdes version

SPAdes genome assembler v3.13.1

### Operating System

windows

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

you are having in the cmdline:
```
-t	-6
```

which is not a correct value of number of threads
