### ISSUE TITLE
.... finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by Gennuo** [ablab/spades#1146]
### Description of bug

Dear SPAdes team,

I have several reads data (after assembly) on which I am trying to run metaviralspades. 
I test with a toy data set, and it works. But I use my paired-end reads in two files: R1.fastq and R2.fastq, this is the issue:
== Error ==  system call for: "['/gpfs1/work/wangg/SPAdes-3.15.5-Linux/bin/spades-hammer', '/work/wangg/SPAdes-3.15.5-Linux/bin/spades_test/test_output/corrected/configs/config.info']" finished abnormally, OS return value: -6

Do you have any suggestions to fix it?
Thank you in advance.

### spades.log

[spades.log](https://github.com/ablab/spades/files/11646559/spades.log)

### params.txt

Command line: /work/wangg/SPAdes-3.15.5-Linux/bin/metaviralspades.py	-1	/work/wangg/wang_1/preprocess/QC_outputs/UNDR04_DNA0-1I_/UNDR04_DNA0-1I_1.fastq	-2	/work/wangg/wang_1/preprocess/QC_outputs/UNDR04_DNA0-1I_/UNDR04_DNA0-1I_2.fastq	-o	/work/wangg/SPAdes-3.15.5-Linux/bin/spades_test/test_output	

System information:
  SPAdes version: 3.15.5
  Python version: 3.9.1
  OS: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.17

Output dir: /work/wangg/SPAdes-3.15.5-Linux/bin/spades_test/test_output
Mode: read error correction and assembling
Debug mode is turned OFF
Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/work/wangg/wang_1/preprocess/QC_outputs/UNDR04_DNA0-1I_/UNDR04_DNA0-1I_1.fastq']
      right reads: ['/work/wangg/wang_1/preprocess/QC_outputs/UNDR04_DNA0-1I_/UNDR04_DNA0-1I_2.fastq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Extrachromosomal mode is turned ON
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /work/wangg/SPAdes-3.15.5-Linux/bin/spades_test/test_output/tmp
  Threads: 16
  Memory limit (in Gb): 250

### SPAdes version

 SPAdes version: 3.15.5

### Operating System

 OS: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.17

### Python Version

 Python version: 3.9.1

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
mimalloc: error: unable to allocate OS memory (86981476352 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:    2791.806 s
   process: user: 2758.302 s, system: 25.436 s, faults: 0
       rss: current: 26214400, peak: 36044800
    commit: current: 26214400, peak: 26214400
```

So, you're running out of RAM. Looks like SPAdes was unable to allocate ~86 Gb.
