### ISSUE TITLE
error code #6

### ISSUE THREAD

**Issue by bioinfo17** [ablab/spades#115]
Hi,

I've been trying to run paired-end and mate-paired reads together and I keep getting the error as below:

<spades: /spades/src/common/modules/path_extend/path_extender.hpp:353: virtual size_t path_extend::PairedInfoLoopEstimator::EstimateSimpleCycleCount(const path_extend::BidirectionalPath&, path_extend::EdgeId, path_extend::EdgeId) const: Assertion `path.Size() > 1' failed.

== Error ==  system call for: "['programs/SPAdes-3.11.0-Linux/bin/spades', '/spades/K55/configs/config.info', 'spades/K55/configs/careful_mode.info']" finished abnormally, err code: -6">

I understand many other users have been experiencing a similar problem. Any advice please?

Thanks

**Comment by asl** [comment]
Dup of #43
