### ISSUE TITLE
Error [] call -6

### ISSUE THREAD

**Issue by namon1994** [ablab/spades#1152]
### Description of bug

Hi there,

I am attempting to use SPAdes to assemble some metagenomic data. Here is my input:

"spades --meta --pe1-1 004_1ee.fastq --pe1-2 004_2ee.fastq -k 55,77,99 -t 20 -m 150 -o 004_metaspades --phred-offset 33"

I am including the phred offset because I was previously getting an error 255 flashed, and saw that phred-offset might fix it.

I had done some other reading on error -6, and saw that it may happen because my input fastqs are two different sizes: this is not the case, they are the same size and contain the same number of reads. I even verified this with fastq_pair, which told me all my left and right reads were paired and produced no singles.

It may be worth noting that this data was generated by running the extract_reads.py script from Jennifer Lu's "KrakenTools", as I was trying to remove all non-microbial reads from my dataset prior to further downstream processing. SPAdes has no issue assembling my raw files, only these extracted ones. Any insight or help you could give would be greatly appreciated- thank you!

Best,
Nolan Amon

### spades.log

[spades.log](https://github.com/ablab/spades/files/11854273/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/11854274/params.txt)

### SPAdes version

SPAdes 3.13.1

### Operating System

Ubuntu 22.04.2

### Python Version

Python 3.10.9

### Method of SPAdes installation

Manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The error about phred offset highly likely indicates the corrupted reads. Simply overriding it manually almost surely would cause the issues downstream.

Can you show the beginning of your read files?

**Comment by namon1994** [comment]
Hi Anton,

Thanks for your prompt reply! Here are the first few lines of my forward fastq:

>A00589:519:HHJW5DMXY:2:1101:17879:1047 1:N:0:TATCCTCCAG+CATTGGTGCG
GCGTTTTTTTATTTCTCCTGTAGGAGCTGCCGAAGGCTGCGAAAGCGGTGTTTCAGGTAA
ATTGCTTTTTCAGCCTTCGTCAAACATAAAGTAACTAACTGAATTCAAATGCTTTATCTG
TAGGAGCGCGCTTGCCCACGATTGCGTCACC
>A00589:519:HHJW5DMXY:2:1101:17770:1078 1:N:0:TATCCTCCAG+CATTGGTGCG
GCGTTTTTTTATTTCTCCTGTAGGAGCTGCCGAAGGCTGCGAAAGCGGTGTTTCAGGTAA
ATTTCTTTTTCAGCCTTCGTCAAACATAAAGTAACTAACTGAATTCAAATGCTTTATCTG
TAGGAGCGCGCTTGCCCGCGATTGCGTCACC
>A00589:519:HHJW5DMXY:2:1101:20139:1078 1:N:0:TATCCTCCAG+CATTGGTGCG
GCGTCGACCGCCAACAACCTGAAGAAGGACGGCTGGCAGACCGGCCAGAGCTGGGGCTAC
GAGGTCTCGGTGCCGCAGGGTTTCAACTACATGCTGGCCGACCGCGCCAAGACCATGACT
TTCGCGCAGTGGCAGCAGCTCGGCGTCGTGC

If my reads are corrupted- is there any way to fix them? Thanks again!

**Comment by namon1994** [comment]
I think I may have made a novice mistake- with the extract kraken reads script, I may have had to use a --fastq-output flag, because I'm realizing my seqs look like fasta and not fastq. The .fastq ending might be what's upsetting SPAdes?

**Comment by asl** [comment]
> Hi Anton,
> 
> Thanks for your prompt reply! Here are the first few lines of my forward fastq:
> 
> > A00589:519:HHJW5DMXY:2:1101:17879:1047 1:N:0:TATCCTCCAG+CATTGGTGCG
> > GCGTTTTTTTATTTCTCCTGTAGGAGCTGCCGAAGGCTGCGAAAGCGGTGTTTCAGGTAA
> > ATTGCTTTTTCAGCCTTCGTCAAACATAAAGTAACTAACTGAATTCAAATGCTTTATCTG
> > TAGGAGCGCGCTTGCCCACGATTGCGTCACC
> > A00589:519:HHJW5DMXY:2:1101:17770:1078 1:N:0:TATCCTCCAG+CATTGGTGCG
> > GCGTTTTTTTATTTCTCCTGTAGGAGCTGCCGAAGGCTGCGAAAGCGGTGTTTCAGGTAA
> > ATTTCTTTTTCAGCCTTCGTCAAACATAAAGTAACTAACTGAATTCAAATGCTTTATCTG
> > TAGGAGCGCGCTTGCCCGCGATTGCGTCACC
> > A00589:519:HHJW5DMXY:2:1101:20139:1078 1:N:0:TATCCTCCAG+CATTGGTGCG
> > GCGTCGACCGCCAACAACCTGAAGAAGGACGGCTGGCAGACCGGCCAGAGCTGGGGCTAC
> > GAGGTCTCGGTGCCGCAGGGTTTCAACTACATGCTGGCCGACCGCGCCAAGACCATGACT
> > TTCGCGCAGTGGCAGCAGCTCGGCGTCGTGC
> 
> If my reads are corrupted- is there any way to fix them? Thanks again!

This is not a FASTQ file (and not a FASTA either).

You'd probably need to ask the author of whatever script you used to fix it.
