### ISSUE TITLE
spades.py: Error correction and assembling warnings

### ISSUE THREAD

**Issue by zhaohanshuang** [ablab/spades#1162]
### Description of bug

Hello，I get some error while running spades 3.15.4. I want to assemble Synechococcus genome b metagenomes sequence.
My command:time nohup spades.py --isolate  -1 syn02/fixed_R1.fq -2 syn02/fixed_R2.fq  -o syn05 -t 40 --trusted-contigs ~/GCF_000019485.1_ASM1948v1_genomic.fasta -m 450 &
error:
=== Error correction and assembling warnings:
 * 1:48:18.847    38G / 58G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 6
 * 1:48:18.855    38G / 58G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 6
 * 0:47:33.832    32G / 54G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 5
 * 0:47:33.837    32G / 54G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 5
 * 0:58:54.610    44G / 73G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 2
 * 0:58:54.615    44G / 73G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 2
 * 1:13:28.596    42G / 72G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 23
 * 1:13:28.604    42G / 72G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 23
 * 6:55:34.679   101G / 139G  WARN   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  72)   Less than half of genome in unique edges!

### spades.log

[spades.log](https://github.com/ablab/spades/files/12303420/spades.log)

### params.txt

[spades.log](https://github.com/ablab/spades/files/12303433/spades.log)

### SPAdes version

SPAdes 3.15.4

### Operating System

Linux

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
Hello

There are no errors in the log provided, assembler finished and produced some results. What is your problem?

**Comment by zhaohanshuang** [comment]
At the bottom of the spades.log file, there is a description of the error. For your convenience, I've put the problem below for your review.
=== Error correction and assembling warnings:

1:48:18.847 38G / 58G WARN General (kmer_coverage_model.cpp : 327) Valley value was estimated improperly, reset to 6
1:48:18.855 38G / 58G WARN General (kmer_coverage_model.cpp : 366) Failed to determine erroneous kmer threshold. Threshold set to: 6
0:47:33.832 32G / 54G WARN General (kmer_coverage_model.cpp : 327) Valley value was estimated improperly, reset to 5
0:47:33.837 32G / 54G WARN General (kmer_coverage_model.cpp : 366) Failed to determine erroneous kmer threshold. Threshold set to: 5
0:58:54.610 44G / 73G WARN General (kmer_coverage_model.cpp : 327) Valley value was estimated improperly, reset to 2
0:58:54.615 44G / 73G WARN General (kmer_coverage_model.cpp : 366) Failed to determine erroneous kmer threshold. Threshold set to: 2
1:13:28.596 42G / 72G WARN General (kmer_coverage_model.cpp : 327) Valley value was estimated improperly, reset to 23
1:13:28.604 42G / 72G WARN General (kmer_coverage_model.cpp : 366) Failed to determine erroneous kmer threshold. Threshold set to: 23
6:55:34.679 101G / 139G WARN ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp : 72) Less than half of genome in unique edges!

**Comment by zhaohanshuang** [comment]
Hello, I'm assembling the Synechococcus genome from a metagenome sequence, the Synechococcus PCC7002 genome is about 3M in size, but the contigs.fasta I ended up with is 100 times larger, I'm not sure what's causing this?

**Comment by asl** [comment]
Well, you are assembling a metagenome isn't it? Then it is expected that the output will contain the assembled metagenome :)

There are no errors in the log, only warnings. They are likely because you're assembling a metagenome dataset in a normal isolate mode.
