### ISSUE TITLE
Finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by NickJeff13** [ablab/spades#1164]
### Description of bug

SPAdes was running well for me with some Illumina reads for a crab species with a genome size ~2gb and the following input:
./spades.py -k 45 --isolate -t 40 -m 512 -1 /mnt/sdb/Snow_Crab_Genome/iChiOpi2-CL11_TRIMMED1.fastq -2 /mnt/sdb/Snow_Crab_Genome/iChiOpi2-CL11_TRIMMED2.fastq -o /mnt/sdb/Snow_Crab_Genome/SnowCrabSPAdes
 
After ~30 hours of running, I get this error. I don't think it's a memory issue as I have 512gb of ram available and it was only using 360gb last I checked. I am also the system administrator and cannot see if something killed this job, but no one else uses this computer. 

== Error ==  system call for: "['/home/mcrg/SPAdes-3.15.5/bin/spades-core', '/mnt/sdb/Snow_Crab_Genome/SnowCrabSPAdes/K45/configs/[config.info](http://config.info/)', '/mnt/sdb/Snow_Crab_Genome/SnowCrabSPAdes/K45/configs/[isolate_mode.info](http://isolate_mode.info/)']" finished abnormally, OS return value: -9
None

Is there anything I can do to complete my assembly in Spades? Thank you.

### spades.log

[spades.log](https://github.com/ablab/spades/files/12352274/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/12352284/params.txt)

### SPAdes version

SPAdes 3.15.5

### Operating System

Ubuntu 20.04

### Python Version

Python 3.10.9

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Well, still SPAdes received `SIGKILL` signal and therefore was terminated.
