### ISSUE TITLE
Spades-hammer issue

### ISSUE THREAD

**Issue by ManuelAOS** [ablab/spades#1166]
### Description of bug

Hi all!

I am trying to run spades to assemble some metagenomes and get the following error.

Thanks in advance for the help!

Best regards,

Manuel

### spades.log

spades-hammer: /spades/assembler/src/common/utils/kmer_mph/kmer_index_builder.hpp:297: size_t kmers::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&) [with Seq = Seq<21>; traits = kmers::kmer_index_traits<Seq<21> >; size_t = long unsigned int; std::string = std::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' **failed.**

**== Error ==  system call for: "['/srv/home/mochoa/SPAdes-3.15.5-Linux/bin/spades-hammer', '/srv/home/mochoa/SPADES/MG10_Mon_12_22_host_human_removed_host_penguin_removed_metaespades/corrected/configs/config.info']" finished abnormally, OS return value: -6
None**

### params.txt

Command line: /srv/home/mochoa/SPAdes-3.15.5-Linux/bin/spades.py        --meta  -1      /srv/home/mochoa/CLEAN_READS/MG10_Mon_12_22_host_human_removed_host_penguin_removed_R1.fastq.gz -2      /srv/home/mochoa/CLEAN_READS/MG10_Mon_12_22_host_human_removed_host_penguin_removed_R2.fastq.gz -o      /srv/home/mochoa/SPADES/MG10_Mon_12_22_host_human_removed_host_penguin_removed_metaespades

System information:
  SPAdes version: 3.15.5
  Python version: 3.11.4
  OS: Linux-4.19.0-12-amd64-x86_64-with-glibc2.31
Output dir: /srv/home/mochoa/SPADES/MG10_Mon_12_22_host_human_removed_host_penguin_removed_metaespades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/srv/home/mochoa/CLEAN_READS/MG10_Mon_12_22_host_human_removed_host_penguin_removed_R1.fastq.gz']
      right reads: ['/srv/home/mochoa/CLEAN_READS/MG10_Mon_12_22_host_human_removed_host_penguin_removed_R2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /srv/home/mochoa/SPADES/MG10_Mon_12_22_host_human_removed_host_penguin_removed_metaespades/tmp
  Threads: 16
  Memory limit (in Gb): 250

### SPAdes version

 SPAdes version: 3.15.5

### Operating System

  OS: Linux-4.19.0-12-amd64-x86_64-with-glibc2.31

### Python Version

  Python version: 3.11.4

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Will you please upload the spades.log as you were instructed?

Thanks!

**Comment by ManuelAOS** [comment]
Here it is the spades.log.

Thanks for the attention!
[spades.log](https://github.com/ablab/spades/files/12384298/spades.log)

**Comment by ManuelAOS** [comment]
I run spades again in a different server. It started 10 hrs ago and it has not generated the contigs.fasta file. I attached the log archive.

Thanks again for the attention! 
[spades.log](https://github.com/ablab/spades/files/12384818/spades.log)

**Comment by asl** [comment]
> Here it is the spades.log.
> 
> Thanks for the attention! [spades.log](https://github.com/ablab/spades/files/12384298/spades.log)
One of the SPAdes internal files was corrupted. Likely due to I/O problem on your storage. I would suggest you to contact your system administrator.

**Comment by asl** [comment]
> I run spades again in a different server. It started 10 hrs ago and it has not generated the contigs.fasta file. I attached the log archive.
> 
> Thanks again for the attention! [spades.log](https://github.com/ablab/spades/files/12384818/spades.log)

Do not hijack other issues. Also, your spades.log file is corrupted / truncated.
