### ISSUE TITLE
Stuck in Mismatch Correction

### ISSUE THREAD

**Issue by zagalom** [ablab/spades#1175]
### Description of bug

SPades got stuck in the Mismatch Correction part, specifically here:

`0:23:54.077   108M / 112M  INFO   DatasetProcessor         (dataset_processor.cpp     : 105)   processed 1000000reads, flushing`

I let it stay for more than 48 hours, but it just didn't budge. The resource usage was extremely low at this point, less than 150 MB of RAM. I tried to force stop it using Ctrl+C, but it just gave me a message (which I didn't save, I'm sorry), and didn't stop as usual. In fact, it seemed like the Command Prompt got stuck trying to stop it, if that makes sense.

After I restarted my computer, I tried to run it again with "--restart-from mc" but it gave me the folllowing error:

```
/usr/lib/spades/bin/spades.py:812: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  support.dataset_has_gzipped_reads(pyyaml.load(open(corrected_dataset_yaml_filename, 'r')), Loader=pyyaml.FullLoader):
dataset_has_gzipped_reads() got an unexpected keyword argument 'Loader'
Traceback (most recent call last):
  File "/usr/lib/spades/bin/spades.py", line 812, in main
    support.dataset_has_gzipped_reads(pyyaml.load(open(corrected_dataset_yaml_filename, 'r')), Loader=pyyaml.FullLoader):
TypeError: dataset_has_gzipped_reads() got an unexpected keyword argument 'Loader'


== Error ==  exception caught: <class 'TypeError'>
```

I'm trying to assemble a genome of of around 14.85 Mb (_Candida albicans_), from WGS with Illumina. The two .fastq files used have 744 Mb each. I'm using my PC, with 16 GB of RAM, 4 threads.

### spades.log

[spades.log](https://github.com/ablab/spades/files/12477835/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/12477836/params.txt)

### SPAdes version

SPades 13.5.4

### Operating System

Windows 10

### Method of SPAdes installation

Manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Looks like you're running old SPAdes 3.13.1. From the log:
```
  SPAdes version: 3.13.1
```

Note that you're running SPAdes inside WSL and it seems you're using some shared storage for intermediate files. WSL is not supported (as, despite the name, it's not Linux) and using shared storage is known to cause lots of issues as its implementation is buggy. Likely you're having issues due to this.

**Comment by zagalom** [comment]
Hello Anton,

Thanks for the answer. Although it does say that in the log, I assure you I installed the updated version of SPades, 3.15.4. I confirmed this by opening the file "VERSION". I don't know why it says that in the log file.

Indeed I am running SPades insides WSL, as I don't have a Linux system nor Mac OS available to use. However, the test run for the installation went smoothly, and I was able to run another case with the same files without using the "--careful" parameter. Only when I used that parameter it had this issue.

As for the shared storage, I'm not sure what you mean. Is there something I can do to change that? I have external storage available, if needed.

Is there anything I can try to still run it in a Windows? I remembered I could try to run it on an Ubuntu Virtual Machine, is that possible or will I run to similar problems?

**Comment by asl** [comment]
> Thanks for the answer. Although it does say that in the log, I assure you I installed the updated version of SPades, 3.15.4. I confirmed this by opening the file "VERSION". I don't know why it says that in the log file.

Well, while you might indeed installed it, you are not running it. You're running 3.13.1 via `/usr/lib/spades/bin/spades.py`.

> Indeed I am running SPades insides WSL, 

WSL is not a supported platform. It is known to have issues (and despite the name it's not proper Linux). We are not testing nor supporting it.

So, you need a proper Linux. Either natively or inside virtual machine. Just remember not to use shared folders to store any intermediate files.
