### ISSUE TITLE
Spades finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by yangchen2** [ablab/spades#1177]
### Description of bug

Hello, I am encountering the following error after running Spades metaplasmidspades for 36 hours with 400 GB of memory. However, the error still states it is unable allocate OS memory. Any suggestions here would be greatly appreciated. Thank you!
I've attached my spades.log and params.txt.

mimalloc: error: unable to allocate OS memory (268435456 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:   75139.141 s
   process: user: 292404.597 s, system: 3830.291 s, faults: 15
       rss: current: 268352106496, peak: 268299816960
    commit: current: 268352106496, peak: 268352106496

== Error ==  system call for: "['/home/yac027/mambaforge3/envs/VEBA-assembly_env/bin/spades-core', '/panfs/yac027/VEBA_analyses/Projects/Teru_peds-AD/veba_output/assembly/75_S3_L006/intermediate/1__assembly/K55/configs/config.info', '/panfs/yac027/VEBA_analyses/Projects/Teru_peds-AD/veba_output/assembly/75_S3_L006/intermediate/1__assembly/K55/configs/mda_mode.info', '/panfs/yac027/VEBA_analyses/Projects/Teru_peds-AD/veba_output/assembly/75_S3_L006/intermediate/1__assembly/K55/configs/meta_mode.info']" finished abnormally, OS return value: -6
None

### spades.log

[spades.log](https://github.com/ablab/spades/files/12479167/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/12479168/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.17

### Python Version

3.9.15

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
You're having hard memory limit set to 250 Gb:
```
Other parameters:
  Dir for temp files: /panfs/yac027/VEBA_analyses/Projects/Teru_peds-AD/veba_output/assembly/75_S3_L006/tmp/assembly
  Threads: 4
  Memory limit (in Gb): 250
```

So, error is expected
