### ISSUE TITLE
== Error ==  utf-8

### ISSUE THREAD

**Issue by ReemaSingh** [ablab/spades#1179]
### Description of bug

Hi,

I am using rnaspades.py to assemble a few RNAseq samples.  Here's my example command line parameters:

rnaspades.py --pe1-1 SRR17481213_1P.fq --pe1-2 SRR17481213_2P.fq --pe1-s SRR17481213_1S.fq --pe1-s SRR17481213_2S.fq --s1 SRR17509935.fq --s1 SRR17509936.fq --pe2-1 SRR4158188_1.fq --pe2-2 SRR4158188_2.fq --pe3-1 SRR4034962_1.fq --pe3-2 SRR4034962_2.fq --pe4-1 ERR4922196_1.fq --pe4-2 ERR4922196_2.fq --threads 20 -o OUTPUT

I would highly appreciate your response on this.

Thank you,
Reema,

### spades.log

== Warning ==  output dir is not empty! Please, clean output directory before run.

== Error ==  utf-8

Traceback (most recent call last):
  File "/scratch/reemas/SOFT/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/support.py", line 166, in check_file_not_empty
    if next(reads_iterator, None) is None:
  File "/scratch/reemas/SOFT/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/common/SeqIO.py", line 119, in parse_fastq
    while not reader.EOF():
  File "/scratch/reemas/SOFT/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/common/SeqIO.py", line 69, in EOF
    return self.Top() == ""
  File "/scratch/reemas/SOFT/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/common/SeqIO.py", line 36, in Top
    self.FillCash()
  File "/scratch/reemas/SOFT/SPAdes-3.15.5-Linux/share/spades/spades_pipeline/common/SeqIO.py", line 30, in FillCash
    self.cash = self.handler.readline()
  File "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/../../../lib/python3.7/codecs.py", line 705, in readline
    return self.reader.readline(size)
  File "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/../../../lib/python3.7/codecs.py", line 558, in readline
    data = self.read(readsize, firstline=True)
  File "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/../../../lib/python3.7/codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

### params.txt

rnaspades.py --pe1-1 SRR17481213_1P.fq --pe1-2 SRR17481213_2P.fq --pe1-s SRR17481213_1S.fq --pe1-s SRR17481213_2S.fq --s1 SRR17509935.fq --s1 SRR17509936.fq --pe2-1 SRR4158188_1.fq --pe2-2 SRR4158188_2.fq --pe3-1 SRR4034962_1.fq --pe3-2 SRR4034962_2.fq --pe4-1 ERR4922196_1.fq --pe4-2 ERR4922196_2.fq --threads 20 -o OUTPUT

### SPAdes version

SPAdes-3.15.5-Linux

### Operating System

Linux

### Method of SPAdes installation

SPAdes-3.15.5-Linux.tar.gz 

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Will you please attach a complete spades.log file?

Thanks

**Comment by ReemaSingh** [comment]
I am only getting the above attached "== Error == utf-8" message. My output directory is empty.

**Comment by asl** [comment]
> I am only getting the above attached "== Error == utf-8" message. My output directory is empty.

This looks like an input / output problem on your end then, the log should exist. I would suggest you to talk to your system administrator.

**Comment by ReemaSingh** [comment]
Thank you, Anton. I am writing to the system admin now and will get back to this thread as soon as I get a response.

**Comment by ReemaSingh** [comment]
So the problem is in the input file. Some of my paired files have an uneven number of reads. I am using fastq_pair to get the unpaired reads out from the paired-end FASTQ files. And somehow the program is generating the output in binary mode and these are the input files that are causing the problem. I will rerun fastq_pair to generate the file again and see if I am still getting the same error.  I hope this solves the problem.

**Comment by asl** [comment]
> So the problem is in the input file. Some of my paired files have an uneven number of reads. I am using fastq_pair to get the unpaired reads out from the paired-end FASTQ files. And somehow the program is generating the output in binary mode and these are the input files that are causing the problem. I will rerun fastq_pair to generate the file again and see if I am still getting the same error. I hope this solves the problem.

That's the second issue, yes. However, there are definitely I/O issues as log file should be there.
