### ISSUE TITLE
error code #6 remaining in spades 3.12

### ISSUE THREAD

**Issue by astridboehne** [ablab/spades#118]
Hi
as in previous posts, I get the error  * system call for: "['/scicore/home/salzburg/boehne/applications/SPAdes-3.12.0-Linux/bin/spades-core', '/scicore/home/salzburg/boehne/Ambizione/KmerTest_CichlidX/Tropheini/LG05/assemblies/SPADES/K125/configs/config.info']" finished abnormally, err code: -6
after updating to version 3.12.

Is this due to the data or a remaining bug?
I attach my log file, it is a particular dataset using a subset of reads from a whole genome sequencing experiment
Thanks for your help
Astrid
[spades.log](https://github.com/ablab/spades/files/2030258/spades.log)

**Comment by asl** [comment]
The log reads:

```
Verification of expression 'cov_.size() > 10' failed in function 'void coverage_model::KMerCoverageModel::Fit()'. In file '/spades/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```
And indeed, you're assembling the reads of 126 bp length using k=125. This will not work. In general, if you're not sure what you're doing, we're suggesting to use the default k-mer settings
