### ISSUE TITLE
SPAdes 3.15.5 error with kmer counting

### ISSUE THREAD

**Issue by aryehjc** [ablab/spades#1180]
### Description of bug

Hello, sorry if anything is unclear or poorly formatted in my description, this is my first report on github.

I am running SPAdes on Staphyloccocus aureus genome, the pipeline worked fine previously but I am currently getting errors on runs that i've done previously, as well as on new runs. Attached is an excerpt from the log, I attached the full log in the report.

Command I used in the log is spades.py -m 1000 --isolate -1 F1.fq -2 F2.fq -o spades 

I have tried several values for memory and obtain the same error below.

(kmer_index_builder.hpp    : 249)   Starting k-mer counting.
spades-core: /home/aryeh/spades-3.15.5/assembler/src/common/utils/kmer_mph/kmer_index_builder.hpp:297: size_t kmers::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&) [with Seq = RuntimeSeq<128>; traits = kmers::kmer_index_traits<RuntimeSeq<128> >; size_t = long unsigned int; std::string = std::__cxx11::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed.

== Error ==  system call for: "['/home/aryeh/spades-3.15.5/assembler/bin/spades-core', '/home/aryeh/Staphylococcus_Aureus_Assembly_Amended_Params/SAP1_Phage_Assembled_New_Params/spades/K21/configs/config.info', '/home/aryeh/Staphylococcus_Aureus_Assembly_Amended_Params/SAP1_Phage_Assembled_New_Params/spades/K21/configs/isolate_mode.info']" finished abnormally, OS return value: -6

### spades.log

[spades.log](https://github.com/ablab/spades/files/12544543/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/12544547/params.txt)

### SPAdes version

SPAdes version 3.15.5

### Operating System

Ubuntu 22.04.3 LTS Jammy Jellyfish

### Python Version

Python 3.10.12

### Method of SPAdes installation

Installed from source code

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
One of SPAdes intermediate files got corrupted. Usually this happens due to I/O issues. I would probably suggest you to ask your system administrator about this.

**Comment by aryehjc** [comment]
> One of SPAdes intermediate files got corrupted. Usually this happens due to I/O issues. I would probably suggest you to ask your system administrator about this.

Resolved, thank you so much.
