### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error' during Mismatch correction step

### ISSUE THREAD

**Issue by kmkocot** [ablab/spades#1194]
### Description of bug

I'm assembling some trim_galore-trimmed Illumina PE genomic data from an insect in SPAdes using a command formatted like this:
spades.py --careful	-m 999 -t 16 -1 forward.fastq	-2 reverse.fastq -o output

The machine I am using has 1 TB of RAM and 16 cores were requested.

During the mismatch step I am getting errors that say e.g.,:
"terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot create temporary dir /grps2/kmk/2023-03-01_Psomagen_dragonfly_genomic_data/Plsa72/Plsa72/tmp/corrector_PXtBJt/lib0_XXXXXX
mismatch correction finished abnormally: /grps2/kmk/2023-03-01_Psomagen_dragonfly_genomic_data/Plsa72/Plsa72/mismatch_corrector/contigs/corrected_contigs.fasta not found!"

See lines 2088-2090 of spades.log for the contigs and lines 2110-2112 for similar errors the scaffolds.

The genome is about 1 Gbp and I'm wondering if this is a RAM issue or if this indicates there might be something wrong with my data.

Thank you!
Kevin Kocot

### spades.log

[spades.log](https://github.com/ablab/spades/files/12861996/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/12861997/params.txt)

### SPAdes version

SPAdes 3.14.0

### Operating System

University of Alabama HPC running CentOS & Slurm (Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core)

### Python Version

2.7.15

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
So, the error clearly reads:
```
Cannot create temporary dir /grps2/kmk/2023-03-01_Psomagen_dragonfly_genomic_data/Plsa72/Plsa72/tmp/corrector_PXtBJt/lib0_XXXXXX
```

This indicates some I/O problem on your end. I would suggest talking to your system administrator about this.
