### ISSUE TITLE
error 21

### ISSUE THREAD

**Issue by 206sugarsaman** [ablab/spades#1195]
### Description of bug

== Error ==  system call for: "['/public2/home/lhd1/miniconda3/bin/spades-hammer', '/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/corrected/configs/config.info']" finished abnormally, OS return value: 21

### spades.log

Command line: /public2/home/lhd1/miniconda3/bin/spades.py	-1	/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq	-2	/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq	-o	/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y	

System information:
  SPAdes version: 3.15.5
  Python version: 3.9.15
  OS: Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17

Output dir: /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq']
      right reads: ['/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/tmp
  Threads: 16
  Memory limit (in Gb): 187

======= SPAdes pipeline started. Log can be found here: /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/spades.log

/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq: max reads length: 150
/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq: max reads length: 150

Reads length: 150

Default k-mer sizes were set to [21, 33, 55, 77] because estimated read length (150) is equal to or greater than 150

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /public2/home/lhd1/miniconda3/bin/spades-hammer /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/corrected/configs/config.info

  0:00:00.000     1M / 18M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.025     1M / 18M   INFO    General                 (main.cpp                  :  76)   Loading config from /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/corrected/configs/config.info
  0:00:00.043     1M / 18M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 16
  0:00:00.044     1M / 18M   INFO    General                 (memory_limit.cpp          :  54)   Memory limit set to 187 Gb
  0:00:00.044     1M / 18M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.044     1M / 18M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.045     1M / 18M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.045     1M / 18M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.145     1M / 18M   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 16 threads. This might take a while.
  0:00:00.149     1M / 18M   INFO    General                 (file_limit.hpp            :  42)   Open file limit set to 1024
  0:00:00.149     1M / 18M   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 3.89583 Gb
  0:00:00.149     1M / 18M   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 4194304
  0:00:00.293  9217M / 9217M INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq
  0:00:19.978  9217M / 10G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 2484075 reads
  0:00:19.978  9217M / 10G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq
  0:00:39.725  9217M / 10G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4960719 reads
  0:00:39.726  9217M / 10G   INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 4960719 reads processed
  0:00:39.728     1M / 10G   INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  0:00:58.251     1M / 10G   INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 107177736 kmers in total.
  0:00:58.254     1M / 10G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  0:01:07.223    77M / 10G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 107177736 kmers, 77422376 bytes occupied (5.77899 bits per kmer).
  0:01:07.223    77M / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 354)   Arranging kmers in hash map order
  0:01:10.305  1718M / 10G   INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  0:01:54.453  1718M / 10G   INFO    General                 (main.cpp                  : 155)   Extracting clusters:
  0:01:54.453  1718M / 10G   INFO    General                 (concurrent_dsu.cpp        :  18)   Connecting to root
  0:01:54.645  1718M / 10G   INFO    General                 (concurrent_dsu.cpp        :  34)   Calculating counts
  0:02:16.889  2806M / 10G   INFO    General                 (concurrent_dsu.cpp        :  63)   Writing down entries
  0:02:58.122  1718M / 10G   INFO    General                 (main.cpp                  : 167)   Clustering done. Total clusters: 53920027
  0:02:58.127   898M / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 371)   Collecting K-mer information, this takes a while.
  0:02:59.227  3354M / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 377)   Processing /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq
  0:03:18.899  3354M / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 377)   Processing /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq
  0:03:37.719  3354M / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 384)   Collection done, postprocessing.
  0:03:38.161  3354M / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 397)   There are 107177736 kmers in total. Among them 56091148 (52.3347%) are singletons.
  0:03:38.161  3354M / 10G   INFO    General                 (main.cpp                  : 173)   Subclustering Hamming graph
  0:07:11.959  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 650)   Subclustering done. Total 4021 non-read kmers were generated.
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 651)   Subclustering statistics:
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 652)     Total singleton hamming clusters: 41168570. Among them 28930178 (70.2725%) are good
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 653)     Total singleton subclusters: 1528232. Among them 1524706 (99.7693%) are good
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 654)     Total non-singleton subcluster centers: 14882424. Among them 10238251 (68.7942%) are good
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 655)     Average size of non-trivial subcluster: 4.43568 kmers
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 656)     Average number of sub-clusters per non-singleton cluster: 1.28696
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 657)     Total solid k-mers: 40693135
  0:07:11.960  3354M / 10G   INFO   Hamming Subclustering    (kmer_cluster.cpp          : 658)     Substitution probabilities: [4,4]((0.916175,0.0315028,0.0294417,0.0228807),(0.00995788,0.950283,0.0269804,0.012779),(0.0124117,0.0263661,0.950985,0.0102373),(0.0224868,0.0287073,0.0309623,0.917844))
  0:07:12.144  3354M / 10G   INFO    General                 (main.cpp                  : 178)   Finished clustering.
  0:07:12.145  3354M / 10G   INFO    General                 (main.cpp                  : 197)   Starting solid k-mers expansion in 16 threads.
  0:07:22.640  3354M / 10G   INFO    General                 (main.cpp                  : 218)   Solid k-mers iteration 0 produced 4363538 new k-mers.
  0:07:31.974  3354M / 10G   INFO    General                 (main.cpp                  : 218)   Solid k-mers iteration 1 produced 155103 new k-mers.
  0:07:41.410  3354M / 10G   INFO    General                 (main.cpp                  : 218)   Solid k-mers iteration 2 produced 3752 new k-mers.
  0:07:51.112  3354M / 10G   INFO    General                 (main.cpp                  : 218)   Solid k-mers iteration 3 produced 176 new k-mers.
  0:08:00.911  3354M / 10G   INFO    General                 (main.cpp                  : 218)   Solid k-mers iteration 4 produced 0 new k-mers.
  0:08:00.912  3354M / 10G   INFO    General                 (main.cpp                  : 222)   Solid k-mers finalized
  0:08:00.912  3354M / 10G   INFO    General                 (hammer_tools.cpp          : 222)   Starting read correction in 16 threads.
  0:08:00.912  3354M / 10G   INFO    General                 (hammer_tools.cpp          : 235)   Correcting pair of reads: /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq and /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq
  0:08:04.826  4761M / 10G   INFO    General                 (hammer_tools.cpp          : 170)   Prepared batch 0 of 1600000 reads.
  0:08:09.512  4859M / 10G   INFO    General                 (hammer_tools.cpp          : 177)   Processed batch 0
  0:08:12.647  4859M / 10G   INFO    General                 (hammer_tools.cpp          : 187)   Written batch 0
  0:08:14.434  4908M / 10G   INFO    General                 (hammer_tools.cpp          : 170)   Prepared batch 1 of 876644 reads.
  0:08:16.886  4908M / 10G   INFO    General                 (hammer_tools.cpp          : 177)   Processed batch 1
  0:08:26.311  4908M / 10G   INFO    General                 (hammer_tools.cpp          : 187)   Written batch 1
  0:08:26.312  4908M / 10G   ERROR   General                 (hammer_tools.cpp          : 191)   Pair of read files /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq and /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq contain unequal amount of reads

== Error ==  system call for: "['/public2/home/lhd1/miniconda3/bin/spades-hammer', '/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/corrected/configs/config.info']" finished abnormally, OS return value: 21
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/spades.log

Thank you for using SPAdes!

### params.txt

Command line: /public2/home/lhd1/miniconda3/bin/spades.py	-1	/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq	-2	/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq	-o	/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y	

System information:
  SPAdes version: 3.15.5
  Python version: 3.9.15
  OS: Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17

Output dir: /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq']
      right reads: ['/public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/result_assembly9Y/tmp
  Threads: 16
  Memory limit (in Gb): 187

### SPAdes version

SPAdes version: 3.15.5

### Operating System

OS: Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17

### Python Version

  Python version: 3.9.15

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by 206sugarsaman** [comment]
hope anybody helps me ！  the best wishes！

**Comment by asl** [comment]
The log clearly reads:
```
0:08:26.312 4908M / 10G ERROR General (hammer_tools.cpp : 191) Pair of read files /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_1.fq and /public2/home/lhd1/ONT-data/mapping_results/Burkholderia_cepacia/9Yass_2.fq contain unequal amount of reads
```

So your input reads are corrupted.

**Comment by 206sugarsaman** [comment]
So I don't know which step I made an error that led to this result, what
should I normally do in this situation? I went through bwa to match the
reference genome, I extracted the reads from the match, and then went
through samtools to sort and split into fq files of the forward and reverse
sequences, which I wanted to use to do a genome assembly with spades.
best wishes

**Comment by asl** [comment]
> So I don't know which step I made an error that led to this result, what should I normally do in this situation? I went through bwa to match the reference genome, I extracted the reads from the match, and then went through samtools to sort and split into fq files of the forward and reverse sequences, which I wanted to use to do a genome assembly with spades. best wishes

Whatever procedure you're using, you need to ensure it is paired-end aware, i.e. left reads should correspond the right ones

**Comment by asl** [comment]
> I thought that it is PE aware

What do you do if only one read from the pair matches? Are you extracting its unmatched mate as well? If so, do you correctly handle both combinations (mate could precede the matching read or might be the next)?
