### ISSUE TITLE
spades finished abnormally, OS return value -6

### ISSUE THREAD

**Issue by s-junguy** [ablab/spades#1196]
### Description of bug

Hi,
I use spades in the metagenomics pipeline atlas https://github.com/metagenome-atlas/atlas .
I use Illumina paired end libraries (10 GB per library) and tried to run the pipeline on 2 libraries.

### spades.log

[spadesatlas.log](https://github.com/ablab/spades/files/12879745/spadesatlas.log)

### params.txt

Error in rule run_spades:
    jobid: 41
    input: P19752-101/assembly/reads/QC.errorcorr.merged_R1.fastq.gz, P19752-101/assembly/reads/QC.errorcorr.merged_R2.fastq.gz, P19752-101/assembly/reads/QC.errorcorr.merged_me.fastq.gz
    output: P19752-101/assembly/contigs.fasta, P19752-101/assembly/scaffolds.fasta
    log: P19752-101/logs/assembly/spades.log (check log file(s) for error details)
    conda-env: /home/user/atlas/databases/conda_envs/f9b130b75c406b2ca1b149c2a4cd967f_
    shell:
         rm -f P19752-101/assembly/pipeline_state/stage_*_copy_files 2> P19752-101/logs/assembly/spades.log ;  spades.py  --threads 128  --memory 200  -o P19752-101/assembly  -k auto --meta     --pe1-1 P19752-101/assembly/reads/QC.errorcorr.merged_R1.fastq.gz --pe1-2 P19752-101/assembly/reads/QC.errorcorr.merged_R2.fastq.gz --pe1-m P19752-101/assembly/reads/QC.errorcorr.merged_me.fastq.gz     --only-assembler  >> P19752-101/logs/assembly/spades.log 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

### SPAdes version

3.15.5

### Operating System

Linux-5.15.0-86-generic-x86_64-with-glibc2.35

### Python Version

3.12.0

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
mimalloc: error: unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:    3343.469 s
   process: user: 234249.289 s, system: 3918.136 s, faults: 1151
       rss: current: 213667278848, peak: 211806064640
    commit: current: 213667278848, peak: 213667278848
```

So, you're running out of RAM
