### ISSUE TITLE
unknown error in filter_spades_contigs_weigthed.pl line 16

### ISSUE THREAD

**Issue by Jorge-82** [ablab/spades#1197]
### Description of bug

Hi
I`m running Fast-Plast (which uses Spades), and the script FP is stopped with a warning of an issue in Spades. 
Any guess about the problem? Could it be some missing package? Installation problem?
many thanks 

Sorry I am not posting the Spades error log because I am not running a stand-alone Spades but from Fast-Plast

### spades.log

readline() on closed filehandle $file at /home/jorge/Fast-Plast/bin/filter_spades_contigs_weigthed.pl line 16.

### params.txt

Use of uninitialized value $total_length in division (/) at /home/jorge/Fast-Plast/bin/filter_spades_contigs_weigthed.pl line 36.
Use of uninitialized value $accumulated_coverage in division (/) at /home/jorge/Fast-Plast/bin/filter_spades_contigs_weigthed.pl line 36.
Illegal division by zero at /home/jorge/Fast-Plast/bin/filter_spades_contigs_weigthed.pl line 36.
readline() on closed filehandle $file_filter at fast-plast.pl line 653.

### SPAdes version

Spades 3.15.4

### Operating System

Ubuntu 22.04

### Python Version

Python 3.10.12

### Method of SPAdes installation

by Fast-Plast script

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
```
readline() on closed filehandle $file at /home/jorge/Fast-Plast/bin/filter_spades_contigs_weigthed.pl line 16.
```

This is not part of SPAdes. Consider reporting the error to Fast-Plast

**Comment by Jorge-82** [comment]
well that was fast. Thank you
