### ISSUE TITLE
Assembling ONT data only using metaviral option

### ISSUE THREAD

**Issue by Jokendo-collab** [ablab/spades#1201]
### Description of bug

I only have the ONT data from the metaviral project. When I pass this ONT data to spades in fails and asking me to provide -R1 and -R2 illumina reads. How can I go around this since I do not have these short reads?

### spades.log

N/A

### params.txt

N/A

### SPAdes version

Spades version 3.15.5

### Operating System

Linux server

### Method of SPAdes installation

module

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Per SPAdes manual (https://cab.spbu.ru/files/release3.15.5/manual.html#sec3.1):

> To run SPAdes 3.15.5 you need at least one library of the following types:
>   * Illumina paired-end/high-quality mate-pairs/unpaired reads
>   * IonTorrent paired-end/high-quality mate-pairs/unpaired reads
>   * PacBio CCS reads

SPAdes cannot be used with ONT data alone
