### ISSUE TITLE
SPAdes hangs intermittently on Rocky8/kernel 4.18 when MI_OVERRIDE=ON

### ISSUE THREAD

**Issue by stevenvdb** [ablab/spades#1210]
### Description of bug

Recently we upgraded the OS on our cluster from CentOS 7.9 (kernel 3.10) to Rocky 8.8 (kernel 4.18). After this, we saw that the `spades-core` process would sometimes go into an uninterruptible sleep. For a certain test case, this would happen 8 out of 10 times on the new OS, while on the old OS it always runs correctly. The last line in the output of the failed runs differs from run to run, so it does not seem to be the case that it is hanging at a specific line of code. It does not seem to be a lack of memory, since the successful runs consume about 25GB out of the available 180GB. On the node where this happens, following message appears:

```INFO: task spades-core:17535 blocked for more than 120 seconds.```

When running `spades-core` with `strace -f`, these are the last lines of a hanging run:

```
[pid 1682422] getcpu([11], [0], NULL)   = 0
[pid 1682411] getcpu([22], [1], NULL)   = 0
[pid 1682406] getcpu([35], [1], NULL)   = 0
[pid 1682418] getcpu([1], [0], NULL)    = 0
[pid 1682393] getcpu([5], [0], NULL)    = 0
[pid 1682392] getcpu([10], [0], NULL)   = 0
[pid 1682423] getcpu([32], [1], NULL)   = 0
[pid 1682417] getcpu([23], [1], NULL)   = 0
[pid 1682404] getcpu([9], [0], NULL)    = 0
[pid 1682404] mmap(0x4609b000000, 268435456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0
```
Since this pointed to a problem with memory mapping, I recompiled SPAdes configuring it with `MI_OVERRIDE=OFF` (see https://github.com/microsoft/mimalloc/issues/535#issuecomment-1020553023).

With this new compilation, the same test case runs fine (10 out of 10 times) on the new OS. I am not entirely sure what is happening:
* A process that goes into uninterruptible sleep can indicate I/O problems. I have tried several file systems for writing output and the outcome is always the same. A filesystem problem would also not explain why `MI_OVERRIDE=OFF` solves the problem.
* The problem cannot purely come from SPAdes, since it does run correctly on the old OS and when compiled with a setting that only affects mimalloc. That being said, it is the only application for which we see this behavior.
* My current hypothesis is that mimalloc (or at least the version of it included with SPAdes) does not play well with Rocky 8.8 (kernel 4.18)

Since we have a workaround for this issue, the main intention here is to provide a hint for users that might bump into the same problem. If the SPAdes developers have some more insight on this, it would be of course appreciated if they can share it.

### spades.log

[spades.log](https://github.com/ablab/spades/files/13362771/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/13362787/params.txt)

### SPAdes version

SPAdes v3.15.5

### Operating System

Rocky 8.8 (kernel 4.18)

### Python Version

3.10.12, but also happens when executing spades-core directly

### Method of SPAdes installation

Happens both for conda installation and manuall compilation

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
It looks like a problem with very old kernel (4.18 was released more than 5 years ago) indeed. Note that this is not quite a workaround – you've effectively switched the memory allocator to the system default one (from glibc). The same functionality could be achieved by recompiling SPAdes via `-DSPADES_USE_MIMALLOC=OFF`. Note, however, that our tests show that use of system memory allocator could yield elevated memory consumption and suboptimal performance in the majority of cases.

**Comment by stevenvdb** [comment]
Thanks for your feedback. We can keep this issue closed, but I still wanted to mention I see lower memory consumption and better performance when using the executable compiled with `MI_OVERRIDE=OFF`:
```
MI_OVERRIDE=ON (default) - timings for K21,K33,K55,K77
  0:03:33.350     1M / 27G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 3 minutes 33 seconds
  0:02:56.137     1M / 27G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 2 minutes 56 seconds
  0:03:44.267     1M / 28G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 3 minutes 44 seconds
  0:12:29.298     1M / 28G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 12 minutes 29 seconds
MI_OVERRIDE=OFF
  0:03:06.738     0M / 13G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 3 minutes 6 seconds
  0:02:35.686     0M / 15G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 2 minutes 35 seconds
  0:03:32.876     0M / 14G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 3 minutes 32 seconds
  0:10:33.023     0M / 14G   INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 10 minutes 33 seconds
```
It is possible this is only true on our system for the specific case we are looking at.

**Comment by asl** [comment]
> it is possible this is only true on our system for the specific case we are looking at.

The numbers in the second case are bogus as they are reported by mimalloc and do not reflect the real memory consumption. Note that the first number - the current consumption is always zero and the second one is only partially correct. As for the performance – assembly process is very I/O bound, so the variation could be quite big (especially if the input data is in the buffer cache).

**Comment by stevenvdb** [comment]
> As for the performance – assembly process is very I/O bound, so the variation could be quite big (especially if the input data is in the buffer cache).

You are right; looking at timings for multiple runs shows some significant variation. If performance with `MI_OVERRIDE=OFF` is worse, the effect is much smaller than the variations from run to run.

**Comment by asl** [comment]
> You are right; looking at timings for multiple runs shows some significant variation. If performance with `MI_OVERRIDE=OFF` is worse, the effect is much smaller than the variations from run to run.

It's unlikely that you'd see the difference for assembly jobs that only run few minutes. For multi-day jobs the difference could be hours.
