### ISSUE TITLE
How to correctly input merged files from two references for assembly?

### ISSUE THREAD

**Issue by lukaskon** [ablab/spades#1211]
### Description of bug

Hello, I am interested in assembling a specific region of a genome for a single sample. I used the original filtered Illumina R1 and R2 fastq files to map to two different references for this specific region. I merged the 2 bam files, removed duplicates with picard, converted back to fastq, then tried to input for SPAdes but have the error below. How should I input this data so it will output an assembly of only the region I am interested in (not the entire genome)? Any advice appreciated! 

I am wondering if I need to use the read names in this merged fastq to create two new files as the R1 and R2 input fastq files. Is there a better route I am missing?

### spades.log

(base) CombineMat1-12$ spades.py -o BU9_Mat_assembly2 --careful -t 32 -m 800 --12 BU9_CombinedMat.fastq

== Warning ==  No assembly mode was specified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option.

Command line: /opt/software/SPAdes/3.15.2-GCC-10.2.0/bin/spades.py      -o      /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2      --careful       -t      32      -m      800     --12    /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_CombinedMat.fastq

System information:
  SPAdes version: 3.15.2
  Python version: 3.8.6
  OS: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.2.5

Output dir: /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: not specified
      right reads: not specified
      interlaced reads: ['/mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_CombinedMat.fastq']
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/tmp
  Threads: 32
  Memory limit (in Gb): 800

======= SPAdes pipeline started. Log can be found here: /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/spades.log

/mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_CombinedMat.fastq: max reads length: 135

Reads length: 135

===== Before start started.

===== Preprocess reads started.

===== Preprocess interlaced reads started.

== Running: /opt/software/Python/3.8.6-GCCcore-10.2.0-new/bin/python /opt/software/SPAdes/3.15.2-GCC-10.2.0/share/spades/spades_pipeline/scripts/preprocess_interlaced_reads.py --args_filename /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/split_input/tmp/interlaced --dst /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/split_input

== Splitting /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_CombinedMat.fastq into left and right reads (in /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/split_input directory)
== Error ==  the number of reads in file with interlaced reads (/mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_CombinedMat.fastq) should be EVEN!
In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

== Error ==  system call for: "['/opt/software/Python/3.8.6-GCCcore-10.2.0-new/bin/python', '/opt/software/SPAdes/3.15.2-GCC-10.2.0/share/spades/spades_pipeline/scripts/preprocess_interlaced_reads.py', '--args_filename', '/mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/split_input/tmp/interlaced', '--dst', '/mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/split_input']" finished abnormally, OS return value: 255

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

### params.txt

Command line: /opt/software/SPAdes/3.15.2-GCC-10.2.0/bin/spades.py      -o      /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat
_assembly2      --careful       -t      32      -m      800     --12    /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_CombinedMat
.fastq

System information:
  SPAdes version: 3.15.2
  Python version: 3.8.6
  OS: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.2.5

Output dir: /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: not specified
      right reads: not specified
      interlaced reads: ['/mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_CombinedMat.fastq']
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/MatingType/CombineMat1-12/BU9_Mat_assembly2/tmp
  Threads: 32
  Memory limit (in Gb): 800

### SPAdes version

3.15.2

### Operating System

Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.2.5

### Python Version

3.8.6

### Method of SPAdes installation

most likely manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Well, per error message – the # of reads in the interlaced read file should be even. So, for each read you'd need to have a corresponding mate.

You need to ensure that your procedure is paired-end aware, e.g. for left read there is already a corresponding right one (for example, what do you do when only one read from the pair matches?).

**Comment by lukaskon** [comment]
Thanks for the quick response. Do you have a tool you recommend for this?

I tried running this python script to filter out unpaired reads and it still giving me the same error.
```
def filter_paired_reads():
    input_file = 'BU9_CombinedMat.fastq'
    output_file = 'BU9_Combined_paired_batch.fastq'
    unpaired_count = 0
    buffer = []
    read_count = 0
    paired_count = 0

    with open(input_file, 'r') as infile:
        for line in infile:
            buffer.append(line.strip())
            if len(buffer) == 4:  # Process a read block
                read_id = buffer[0].split()[0]
                read_num = read_id.split('/')[1]

                if read_num == '1' or read_num == '2':
                    buffer[0] += '\n'
                    buffer[1] += '\n'
                    buffer[2] += '\n'
                    buffer[3] += '\n'

                    if read_id.endswith('/1'):  # Check if first read of a pair
                        paired_count += 1
                        with open(output_file, 'a') as outfile:
                            outfile.write(''.join(buffer))

                    # If it's the second read of a pair, skip writing and reset buffer
                    buffer = []
                    read_count += 1
                else:
                    unpaired_count += 1
                    buffer = []  # Reset buffer for unpaired reads
                    read_count += 1

                if read_count % 100000 == 0:  # Display progress for every 100,000 reads
                    print(f"Processed {read_count} reads")

    print(f"Number of unpaired reads filtered out: {unpaired_count}")
    print(f"Number of paired reads written to file: {paired_count}")

# Usage:
filter_paired_reads()

```

**Comment by asl** [comment]
> I tried running this python script to filter out unpaired reads and it still giving me the same error.

You whole pipeline should be paired-end aware. This includes e.g. picard.
