### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by mamunnoz** [ablab/spades#1212]
### Description of bug

I have installed SPAdes 3.15.5 from the binaries, as you specify in gitub page and when I verify the isntalation with
spades.py --test
I otained the followint error message 
== Error ==  system call for: "['/home/rivularia/SPAdes-3.15.5-Linux/bin/spades-hammer', '/home/rivularia/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11

### spades.log

[spades.log](https://github.com/ablab/spades/files/13417500/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/13417601/params.txt)

### SPAdes version

SPAdes v3.15.5

### Operating System

Ubuntu 22.04.3 LTS

### Python Version

Phyton 3.9.12

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Does the problem reproduce if you'd install SPAdes from the sources and / or conda?

**Comment by mamunnoz** [comment]
I don´t know, I will try. Do you recommend me to uninstall this version before trying other installations. In this case, is enough to simply remove the directory SPAdes-3.15.5-Linux/bin?
Anyway I tried before installing from conda and I obtained a older version

De: Anton Korobeynikov ***@***.***>
Enviado el: lunes, 20 de noviembre de 2023 18:21
Para: ablab/spades ***@***.***>
CC: Maria Angeles Muñoz Martin ***@***.***>; Author ***@***.***>
Asunto: Re: [ablab/spades] Problems with installation (Issue #1212)


Does the problem reproduce if you'd install SPAdes from the sources and / or conda?

**Comment by asl** [comment]
> I don´t know, I will try. Do you recommend me to uninstall this version before trying other installations. In this case, is enough to simply remove the directory SPAdes-3.15.5-Linux/bin?

Yes. There is no "installation" process.

**Comment by mamunnoz** [comment]
When I try to install SPAdes with conda, the version installed is 3..13.0-0 and not the latest (3.15.5)

De: Anton Korobeynikov ***@***.***>
Enviado el: lunes, 20 de noviembre de 2023 18:29
Para: ablab/spades ***@***.***>
CC: Maria Angeles Muñoz Martin ***@***.***>; Author ***@***.***>
Asunto: Re: [ablab/spades] Problems with installation (Issue #1212)


I don´t know, I will try. Do you recommend me to uninstall this version before trying other installations. In this case, is enough to simply remove the directory SPAdes-3.15.5-Linux/bin?

Yes. There is no "installation" process.

**Comment by mamunnoz** [comment]
I have installed SPAdes from the sources, and it seems to function when I run the test, but al the end of the log file I obtain the following message:
===== Breaking scaffolds finished.


===== Terminate started.


===== Terminate finished.

 * Corrected reads are in /home/rivularia/SPAdes-3.15.5/spades_test/corrected/
 * Assembled contigs are in /home/rivularia/SPAdes-3.15.5/spades_test/contigs.fasta
 * Assembled scaffolds are in /home/rivularia/SPAdes-3.15.5/spades_test/scaffolds.fasta
 * Paths in the assembly graph corresponding to the contigs are in /home/rivularia/SPAdes-3.15.5/spades_test/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in /home/rivularia/SPAdes-3.15.5/spades_test/scaffolds.paths
 * Assembly graph is in /home/rivularia/SPAdes-3.15.5/spades_test/assembly_graph.fastg
 * Assembly graph in GFA format is in /home/rivularia/SPAdes-3.15.5/spades_test/assembly_graph_with_scaffolds.gfa

======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:00.753     1M / 219M  WARN    General                 (launcher.cpp              : 178)   Your data seems to have high uniform coverage depth. It is strongly recommended to use --isolate option.
======= Warnings saved to /home/rivularia/SPAdes-3.15.5/spades_test/warnings.log

SPAdes log can be found here: /home/rivularia/SPAdes-3.15.5/spades_test/spades.log

Thank you for using SPAdes!

Is this correct?
________________________________
De: Anton Korobeynikov ***@***.***>
Enviado: lunes, 20 de noviembre de 2023 18:29
Para: ablab/spades ***@***.***>
Cc: Maria Angeles Muñoz Martin ***@***.***>; Author ***@***.***>
Asunto: Re: [ablab/spades] Problems with installation (Issue #1212)


I don´t know, I will try. Do you recommend me to uninstall this version before trying other installations. In this case, is enough to simply remove the directory SPAdes-3.15.5-Linux/bin?

Yes. There is no "installation" process.

**Comment by asl** [comment]
> When I try to install SPAdes with conda, the version installed is 3..13.0-0 and not the latest (3.15.5)

Well, this is something wrong with your conda installation. It's definitely 3.15.5 there: https://anaconda.org/bioconda/spades

**Comment by asl** [comment]
> Is this correct?

Yes, it's ok.
