### ISSUE TITLE
finished abnormally, OS return value: 28 None

### ISSUE THREAD

**Issue by manik-123** [ablab/spades#1215]
### Description of bug

I am getting this error, please help
Error ==  system call for: "['/project/liuguohong/manik/software/SPAdes-3.15.5-Linux/bin/spades-hammer', '/project/liuguohong/manik/hotspring/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: 28
None

### spades.log

[spades.log](https://github.com/ablab/spades/files/13461567/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/13461568/params.txt)

### SPAdes version

SPAdes-3.15.5

### Operating System

Linux

### Python Version

3.6.8

### Method of SPAdes installation

conda aswellas manual same error

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
  3:38:12.300    21G / 29G   ERROR   General                 (kmer_splitter.hpp         : 150)   I/O error! Incomplete write! Reason: No space left on device. Error code: 28
```

**Comment by manik-123** [comment]
Okay, thanks
