### ISSUE TITLE
Error Correction

### ISSUE THREAD

**Issue by sydelstan** [ablab/spades#1219]
### Description of bug

I thought BayesHammer error correction was default, but when I run the following command, I receive a note saying "ONLY assembling (without read error correction)>

### spades.log

[spades.log](https://github.com/ablab/spades/files/13550413/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/13550422/params.txt)

### SPAdes version

v3.15.5

### Operating System

macOS ventura 13.3

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
BayesHammer is disabled in isolate mode that expected decently- and uniformly-covered inputs.
