### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by siulung2005** [ablab/spades#122]
Hi, I encountered "The program was terminated by segmentation fault" when I was running Unicycler at the Spades step. I tried running Spades alone "spades.py --test -t 4 -m 16" and still gave me the error.

I'm using Ubuntu on Window 10, and my local computer has 8 threads and 64 GB RAM. I tried different installation method, both conda and binaries, and still no luck. Any help would be appreciated! Thanks
[
![default](https://user-images.githubusercontent.com/39837377/40853440-132e0d70-659c-11e8-9219-44d8975fb8a7.png)
](url)

**Comment by asl** [comment]
Most probably the problem is due to Windows Linux Subsystem deficiencies. That said, this is not the supported / tested setup from our side.
