### ISSUE TITLE
Performance statistics, where?

### ISSUE THREAD

**Issue by rbtoscan** [ablab/spades#1223]
### Is your feature request related to a problem? Please describe. For generic questions use Q&A section in the Discussions forum above.

hello,
it is said that as of version 3.14 there is performance statistics available. where, exactly? I am interested in the final runtime and amount of ram memory used for the process of metaspades assembly. thank you

### Describe the solution you'd like

i guess a simple line in the log file would be enough.

**Comment by asl** [comment]
Could you please elaborate what exactly and where is "said"?

**Comment by rbtoscan** [comment]
Readme.md file, line 158, last line on 'SPAdes performance', just before 'Installation'.

**Comment by asl** [comment]
You can certainly measure whatever performance statistics are relevant for your case and for your platform (as e.g. memory consumption could be really OS-dependent) as well as runtime.

Sill, lots of statistics were always readily available from the log, e.g.:
```
  0:00:02.286     8M / 317M  INFO    General                 (pipeline.cpp              : 287)   SPAdes finished
  0:00:02.287     1M / 127M  INFO    General                 (main.cpp                  : 136)   Assembling time: 0 hours 0 minutes 2 seconds
```

Here one can see the runtime of one SPAdes iteration as well as current and maximum RAM consumption. Overall running time could be obtained via system-standard `time` command.
