### ISSUE TITLE
curl http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz -o SPAdes-3.15.5-Darwin.tar.gz doesnt work 

### ISSUE THREAD

**Issue by scholaraspect** [ablab/spades#1225]
### Description of bug

they tehre, i was trying to install SPAdes on my mac machine but when i put in this command line

curl http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz -o SPAdes-3.15.5-Darwin.tar.gz

i download a zero byte file

### spades.log

NA

### params.txt

NA

### SPAdes version

v3.15.3

### Operating System

macOS Sonoma

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Likely there is some filtering in the middle. In any case, the binaries are available on github as well

**Comment by asl** [comment]
All releases are on github. Take 4.0.0 from https://github.com/ablab/spades/releases/tag/v4.0.0
