### ISSUE TITLE
How to calculate the coverage in the contig?

### ISSUE THREAD

**Issue by YeGuoZJU** [ablab/spades#1229]
### Description of bug

I use the metaspades to assemble the pair-end reads and get the contig.fata. I just want to know the sequence name of the coverage how to calculate?

such as "NODE_933_length_1534_cov_4.395538" ,I want to know how to calculate cov_4.395538?

### spades.log

NO

### params.txt

No

### SPAdes version

v3.15.5

### Operating System

Linux

### Python Version

python3.10

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is something outside of SPAdes scope. You could use your favourite scripting language to extract the information from FASTA headers.

For example:
```bash
grep NODE contigs.fasta | awk 'BEGIN { FS = "_" }; { print substr($1, 2)"_"$2"\t"$6 }'
```

or
```bash
grep NODE contigs.fasta | awk 'BEGIN { FS = "_" }; { print substr($0, 2)"\t"$6 }'
```

Would yield tab-separate list of contig names and corresponding coverages (depending on what you consider as contig name)

**Comment by YeGuoZJU** [comment]
> This is something outside of SPAdes scope. You could use your favourite scripting language to extract the information from FASTA headers.
> 
> For example:
> 
> ```shell
> grep NODE contigs.fasta | awk 'BEGIN { FS = "_" }; { print substr($1, 2)"_"$2"\t"$6 }'
> ```
> 
> or
> 
> ```shell
> grep NODE contigs.fasta | awk 'BEGIN { FS = "_" }; { print substr($0, 2)"\t"$6 }'
> ```
> 
> Would yield tab-separate list of contig names and corresponding coverages (depending on what you consider as contig name)

Sorry, I may not have described my problem clearly. I just want to known the "NODE_933_length_1534_cov_4.395538" term, what the mean "cov_4.395538"? and How to get this value?
