### ISSUE TITLE
err code:-7

### ISSUE THREAD

**Issue by sainthavy** [ablab/spades#123]
Please help me to solve this error, thanks.
Here is my log:
[spades.log](https://github.com/ablab/spades/files/2064739/spades.log)
[params.txt](https://github.com/ablab/spades/files/2064740/params.txt)
In my output folder, I got results for K21 and K33, but not K55.

**Comment by asl** [comment]
Hello

There might be a problem that cause this issue. We will fix this problem in SPAdes 3.12.1

**Comment by asl** [comment]
Fixed in 3.13.0
