### ISSUE TITLE
 finished abnormally, OS return value: 2

### ISSUE THREAD

**Issue by staright2001** [ablab/spades#1234]
### Description of bug

== Error ==  system call for: "['/mnt/hgfs/SPAdes-3.15.4-Linux/SPAdes-3.15.4-Linux/bin/spades-core', '/mnt/hgfs/result_spades/K21/configs/config.info', '/mnt/hgfs/result_spades/K21/configs/isolate_mode.info']" finished abnormally, OS return value: 2
None

### spades.log

[spades.log](https://github.com/ablab/spades/files/13903935/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/13903937/params.txt)

### SPAdes version

SPAdes-3.15.4

### Operating System

ubuntu 22.04

### Python Version

Python 3.9.18

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Let us read the log together:

```
  0:00:50.786    21M / 248M  ERROR   General                 (paired_readers.cpp        :  41)   Unequal number of read-pairs detected in the following files: /mnt/hgfs/output_forward_paired.fastq  /mnt/hgfs/output_reverse_paired.fastq.gz
```

So your input files are corrupted
