### ISSUE TITLE
Guidance: use of rnaspades in a study with matching microbial metagenomes and metatranscriptomes

### ISSUE THREAD

**Issue by ganiatgithub** [ablab/spades#1235]
## Description

Hi,

I'm a long-term fan of the SPAdes suite.
In a study where matching metagenomes and metatranscriptomes are sequenced from microbial communities, and high quality MAGs are already obtained, I was wondering whether using `rnaspades` is a recommended way to assembly transcripts?

By running `rnaspades` in a trial, I'm getting transcripts with length over 30kb, which makes me pause and consider whether I'm taking the right approach. Is it common to have such long transcripts?

I'm also considering using predicted coding sequences (as proxy for transcripts) from either contigs or MAGs with `--careful ` and `--trusted-contigs ` or `--untrusted-contigs ` for further improvement of the assembled transcripts in `rnaspades`. 

## Describe the solution you'd like

Could you share your thoughts on whether this is a valid approach?

### Length the initially assembled transcripts:
```
cat transcripts.fasta | grep ">" | head -100
>NODE_1_length_56125_cov_42.650095_g0_i0
>NODE_2_length_47681_cov_169.986226_g1_i0
>NODE_3_length_43177_cov_160.376167_g0_i1
>NODE_4_length_42213_cov_340.366844_g2_i0
>NODE_5_length_42191_cov_324.270730_g2_i1
>NODE_6_length_41397_cov_335.196414_g2_i2
>NODE_7_length_40672_cov_217.244395_g0_i2
>NODE_8_length_40379_cov_346.417420_g3_i0
>NODE_9_length_40331_cov_376.643966_g3_i1
>NODE_10_length_40222_cov_225.048510_g0_i3
...
```
### Code for the initial assembly
```
function run_rnaspades(){
    export PATH="/home/gnii0001/rp24/gaofeng/tools/SPAdes-3.15.5-Linux/bin:$PATH"
    echo "started assembly with rna on `date`"
    rnaspades.py -1 "$read_dir"/"$forward" -2 "$read_dir"/"$reverse" -t 96 -m 1600 -k 27,37,47,57,67,77,87,97,107,117,127 -o "$out_dir"/coassembly
    echo "completed assembly with rna on `date`"
}
```
### Code to reassemble with coding sequences from MAGs or contigs
```
function run_rnaspades_reassemble(){
    export PATH="/home/gnii0001/rp24/gaofeng/tools/SPAdes-3.15.5-Linux/bin:$PATH"
    echo "started assembly with rna on `date`"
    rnaspades.py -1 "$read_dir"/"$forward" -2 "$read_dir"/"$reverse" -t 64 -m 1000 -k 27,37,47,57,67,77,87,97,107,117,127 -o "$out_dir" \
    --trusted-contigs "$contig_file" --careful
    echo "completed assembly with rna on `date`"
}
```

**Comment by andrewprzh** [comment]
Dear @ganiatgithub 

If you have high-quality MAG, some reference-based / annotation based approach should give better results, probably even noticeably better. Something like, e.g. StringTie, might work. However, reference-based transcriptome assemblers are typically developed for eukaryotes and look for spliced isoforms.

As to long genes - could it be contamination or operons containing multiple transcripts?

We also have developed MetaGT pipeline, which assembles transcripts using rnaSPAdes and maps them to the metagenome assembly and matches against the prokka annotation. You may give it try as well.

Best
Andrey

**Comment by ganiatgithub** [comment]
Many thanks.
