### ISSUE TITLE
Build failure on `=SPAdes-3.15.5`

### ISSUE THREAD

**Issue by TheChymera** [ablab/spades#1238]
### Description of bug

I'm trying to package your software for Gentoo Linux, but the he build fails with this log → https://ppb.chymera.eu/76ee8e

### spades.log

I could sadly find neither `spades.log` nor `params.txt` in the build directories, here's me looking for them: https://ppb.chymera.eu/6a6f6f (build.log is the file I uploaded above, perhaps that contains the necessary information?)

I am trying to build the software by running `./spades_compile.sh` as described in the README, should I do something else?

### params.txt

see above

### SPAdes version

3.15.5

### Operating System

Gentoo Linux

### Python Version

3.11.7

### Method of SPAdes installation

build from source

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

You need to apply patches from https://github.com/ablab/spades/pull/1157 to build with gcc 13. This will be a part of next SPAdes release

**Comment by TheChymera** [comment]
@asl thank you, that worked!
