### ISSUE TITLE
metaspades stuck on large sample despite large increase in memory

### ISSUE THREAD

**Issue by clydeandforth** [ablab/spades#1240]
### Description of bug

I used metaspades to assemble 35 of my 36 metagenomes but for 1 sample the assembly freezes after only 10 minutes and does progress after many hours/days. It is the largest sample, i.e. with the most sequencing reads, but does not have substantially more reads than the other files. I have tried to add substantially more memory and threads but this does not resolve the problem.

### spades.log

[spades.log](https://github.com/ablab/spades/files/14113320/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/14113303/params.txt)

### SPAdes version

spades/3.15.5

### Operating System

Linux g-12-l0002 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Python Version

Python 3.10.9

### Method of SPAdes installation

computer cluster installed by administrator

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Yes, this is known issue with CQF implementation we are using. Consider performing some quality trimming and running `--only-assembler`.
