### ISSUE TITLE
Installer link not working

### ISSUE THREAD

**Issue by bombnattanon** [ablab/spades#1243]
### Description of bug

Hi, I was trying to download Spades on my Mac using this link [https://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz](url) (either using curl or open the link directly) but it seems like the link is not working as showed below.
<img width="877" alt="Screenshot 2024-02-13 at 15 03 15" src="https://github.com/ablab/spades/assets/56253006/4d1e6acf-db72-4ca7-8065-97780e48d11e">

### spades.log

$user curl http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz -o SPAdes-3.15.5-Darwin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

### params.txt

-

### SPAdes version

Not installed yet

### Operating System

macOS Sonoma 14.2.1

### Python Version

3.12.1

### Method of SPAdes installation

Not installed yet

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Consider using GitHub releases in the meantime: https://github.com/ablab/spades/releases/tag/v3.15.5

**Comment by bombnattanon** [comment]
Thank you!
