### ISSUE TITLE
can't download software

### ISSUE THREAD

**Issue by omaclean** [ablab/spades#1244]
### Description of bug

https://cab.spbu.ru/software/spades/ just gives 
"Account disabled by server administrator"

### spades.log

NA

### params.txt

NA

### SPAdes version

all

### Operating System

ubuntu

### Method of SPAdes installation

any

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Dup of https://github.com/ablab/spades/issues/1243

Consider using GitHub releases in the meantime: https://github.com/ablab/spades/releases/tag/v3.15.5

**Comment by omaclean** [comment]
Thanks!
