### ISSUE TITLE
metaSPAdes finished abnormally, err code: -6 and with warnings

### ISSUE THREAD

**Issue by kevinxchan** [ablab/spades#125]
Hi, I am trying to running metaSPAdes with default parameters on my dataset, but I encounter an error at K55. K21 and K33 work fine. I know there's also a warning, but I'm not sure if it has to do with the error. Could you please provide some insight into this? 

[params.txt](https://github.com/ablab/spades/files/2085195/params.txt)
[spades.log](https://github.com/ablab/spades/files/2085196/spades.log)

**Comment by asl** [comment]
Hello

This smells like an out of memory situation. How much of free RAM is available for your SPAdes job?

**Comment by kevinxchan** [comment]
I believe I allocated 110 GB (with the `--memory` flag). Is this enough?

**Comment by asl** [comment]
Well... the -m option does not pre-allocate any RAM. It only specifies the hard memory limit that SPAdes will never overshoot (potentially crashing).

**Comment by kevinxchan** [comment]
Sorry for the late reply. I ran metaSPAdes again on a cluster with more resources and it went to completetion, so I believe this was an out of memory problem. Thank you.
