### ISSUE TITLE
construction.cpp  Unknown error -1; OS return value: 4

### ISSUE THREAD

**Issue by nicolo-tellini** [ablab/spades#1254]
### Description of bug

Hello, 

I am getting "output dir is not empty!", when the dir is clearly empty as it is created directly by `spades.py`.
I am also getting `Exception caught Cannot tell the size of file /home/nico/proj/candidate-saccharomyces/spades/ARR/K11/simplified_contigs/contigs.off: Unknown error -1`. This is limited to a few samples I am assembling, I am wondering if it is due to my dataset.

### spades.log

== Warning ==  output dir is not empty! Please, clean output directory before run.

Command line: /home/nico/tools/SPAdes-3.15.5-Linux/bin/spades.py	-k	11,21,33,55,77	11,21,33,55,77	--threads	4	--pe1-1	/home/nico/proj/candidate-saccharomyces/seq/ARR_1.fastq.gz	--pe1-2	/home/nico/proj/candidate-saccharomyces/seq/ARR_2.fastq.gz	--isolate	--cov-cutoff	auto	-o	/home/nico/proj/candidate-saccharomyces/spades/ARR	

System information:
  SPAdes version: 3.15.5
  Python version: 3.8.10
  OS: Linux-5.15.0-97-generic-x86_64-with-glibc2.29

Output dir: /home/nico/proj/candidate-saccharomyces/spades/ARR
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Isolate mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/nico/proj/candidate-saccharomyces/seq/ARR_1.fastq.gz']
      right reads: ['/home/nico/proj/candidate-saccharomyces/seq/ARR_2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Assembly parameters:
  k: [11, 21, 33, 55, 77, 11, 21, 33, 55, 77]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned ON and threshold will be auto-detected
Other parameters:
  Dir for temp files: /home/nico/proj/candidate-saccharomyces/spades/ARR/tmp
  Threads: 4
  Memory limit (in Gb): 31

======= SPAdes pipeline started. Log can be found here: /home/nico/proj/candidate-saccharomyces/spades/ARR/spades.log

/home/nico/proj/candidate-saccharomyces/seq/ARR_1.fastq.gz: max reads length: 101
/home/nico/proj/candidate-saccharomyces/seq/ARR_2.fastq.gz: max reads length: 94

Reads length: 101

===== Before start started. 

===== Assembling started. 

===== K11 started. 

== Running: /home/nico/tools/SPAdes-3.15.5-Linux/bin/spades-core /home/nico/proj/candidate-saccharomyces/spades/ARR/K11/configs/config.info /home/nico/proj/candidate-saccharomyces/spades/ARR/K11/configs/isolate_mode.info

  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  99)   Loaded config from /home/nico/proj/candidate-saccharomyces/spades/ARR/K11/configs/config.info
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  99)   Loaded config from /home/nico/proj/candidate-saccharomyces/spades/ARR/K11/configs/isolate_mode.info
  0:00:00.000     1M / 10M   INFO    General                 (memory_limit.cpp          :  54)   Memory limit set to 31 Gb
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  : 107)   Starting SPAdes, built from refs/heads/spades_3.15.5, git revision e757b8216f9a038fb616e9551a2d4891b2d19ad7
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  : 108)   Maximum k-mer length: 128
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  : 109)   Assembling dataset (/home/nico/proj/candidate-saccharomyces/spades/ARR/dataset.info) with K=11
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  : 110)   Maximum # of threads to use (adjusted due to OMP capabilities): 4
  0:00:00.000     1M / 10M   INFO    General                 (pipeline.cpp              : 212)   SPAdes started
  0:00:00.000     1M / 10M   INFO    General                 (pipeline.cpp              : 225)   Starting from stage: read_conversion
  0:00:00.000     1M / 10M   INFO    General                 (pipeline.cpp              : 231)   Two-step repeat resolution disabled
  0:00:00.000     1M / 10M   INFO   GraphCore                (graph_core.hpp            : 672)   Graph created, vertex min_id: 3, edge min_id: 3
  0:00:00.000     1M / 10M   INFO   GraphCore                (graph_core.hpp            : 673)   Vertex size: 48, edge size: 40
  0:00:00.000     1M / 10M   INFO    General                 (edge_index.hpp            : 113)   Size of edge index entries: 12/8
  0:00:00.000     1M / 10M   INFO   StageManager             (stage.cpp                 : 185)   STAGE == Binary Read Conversion (id: read_conversion)
  0:00:00.000     1M / 10M   INFO    General                 (read_converter.cpp        :  72)   Converting reads to binary format for library #0 (takes a while)
  0:00:00.000     1M / 10M   INFO    General                 (read_converter.cpp        :  73)   Converting paired reads
  0:00:00.455    21M / 54M   INFO    General                 (binary_converter.cpp      :  96)   16384 reads processed
  0:00:00.460    21M / 55M   INFO    General                 (binary_converter.cpp      :  96)   32768 reads processed
  0:00:00.472    21M / 59M   INFO    General                 (binary_converter.cpp      :  96)   65536 reads processed
  0:00:00.672    21M / 80M   INFO    General                 (binary_converter.cpp      :  96)   131072 reads processed
  0:00:00.957    21M / 89M   INFO    General                 (binary_converter.cpp      :  96)   262144 reads processed
  0:00:01.696     9M / 119M  INFO    General                 (binary_converter.cpp      :  96)   524288 reads processed
  0:00:02.933     0M / 145M  INFO    General                 (binary_converter.cpp      :  96)   1048576 reads processed
  0:00:05.517     0M / 145M  INFO    General                 (binary_converter.cpp      :  96)   2097152 reads processed
  0:00:10.746     0M / 146M  INFO    General                 (binary_converter.cpp      :  96)   4194304 reads processed
  0:00:12.336     0M / 146M  INFO    General                 (binary_converter.cpp      : 111)   4800000 reads written
  0:00:12.336     0M / 146M  INFO    General                 (read_converter.cpp        :  86)   Converting single reads
  0:00:12.336     0M / 146M  INFO    General                 (binary_converter.cpp      : 111)   0 reads written
  0:00:12.336     0M / 146M  INFO    General                 (read_converter.cpp        :  92)   Converting merged reads
  0:00:12.336     0M / 146M  INFO    General                 (binary_converter.cpp      : 111)   0 reads written
  0:00:12.342     1M / 146M  INFO   StageManager             (stage.cpp                 : 185)   STAGE == de Bruijn graph construction (id: construction)
  0:00:12.342     1M / 146M  INFO    General                 (construction.cpp          : 118)   Contigs from previous K will be used: /home/nico/proj/candidate-saccharomyces/spades/ARR/K11/simplified_contigs
Exception caught Cannot tell the size of file /home/nico/proj/candidate-saccharomyces/spades/ARR/K11/simplified_contigs/contigs.off: Unknown error -1

== Error ==  system call for: "['/home/nico/tools/SPAdes-3.15.5-Linux/bin/spades-core', '/home/proj/candidate-saccharomyces/spades/ARR/K11/configs/config.info', '/home/nico/proj/candidate-saccharomyces/spades/ARR/K11/configs/isolate_mode.info']" finished abnormally, OS return value: 4
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/nico/proj/candidate-saccharomyces/spades/ARR/spades.log

Thank you for using SPAdes!

### params.txt

Command line: /home/nico/tools/SPAdes-3.15.5-Linux/bin/spades.py	-k	11,21,33,55,77	11,21,33,55,77	--threads	4	--pe1-1	/home/nico/proj/candidate-saccharomyces/seq/ARR_1.fastq.gz	--pe1-2	/home/nico/proj/candidate-saccharomyces/seq/ARR_2.fastq.gz	--isolate	--cov-cutoff	auto	-o	/home/nico/proj/candidate-saccharomyces/spades/ARR	

System information:
  SPAdes version: 3.15.5
  Python version: 3.8.10
  OS: Linux-5.15.0-97-generic-x86_64-with-glibc2.29

Output dir: /home/nico/proj/candidate-saccharomyces/spades/ARR
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Isolate mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/nico/proj/candidate-saccharomyces/seq/ARR_1.fastq.gz']
      right reads: ['/home/nico/proj/candidate-saccharomyces/seq/ARR_2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Assembly parameters:
  k: [11, 21, 33, 55, 77, 11, 21, 33, 55, 77]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned ON and threshold will be auto-detected
Other parameters:
  Dir for temp files: /home/nico/proj/candidate-saccharomyces/spades/ARR/tmp
  Threads: 4
  Memory limit (in Gb): 31

### SPAdes version

SPAdes genome assembler v3.15.5

### Operating System

Ubuntu 20.04.6 LTS x86_64 

### Python Version

Python 3.8.10 

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
Hello

All these look like an I/O problem on your end. Maybe there is more information in the system log? What if you'd move output directory somewhere else? On different volume? Can it be that you launched two SPAdes runs in parallel using the same output dir?

**Comment by nicolo-tellini** [comment]
Hi @asl ,

You are right my fault, I just noticed the k-mer option is repeated twice, wrong use of a `grep` command on my side. 

I apologize.

Thank you for your time

I close the issue 

nic

**Comment by asl** [comment]
(note that running with k-mer length of 11 does not make any sense)
