### ISSUE TITLE
finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by ChadKell** [ablab/spades#1261]
### Description of bug

Trying to do a hybrid assembly between illumina and nanopore data. Not too sure what is wrong with the code or what the error code means. 

### spades.log

[spades (2).log](https://github.com/ablab/spades/files/14706879/spades.2.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/14706884/params.txt)

### SPAdes version

3.15.15

### Operating System

Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.10

### Python Version

3.8.5

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

SPAdes was unable to read one of your input files (the short reads). Likely more information could be available from your system administrator (e.g. storage failures, etc.)
