### ISSUE TITLE
Error while running SPAdes

### ISSUE THREAD

**Issue by sahilrishav2** [ablab/spades#1273]
### Description of bug

Hi,

I am trying to use SPAdes tool for assembling the fungi genome but an unexpected error is showing:

`== Error ==  system call for: "['/data/jammu-univ/software/SPAdes-3.15.5-Linux/bin/spades-core', '/data/jammu-univ/data/ayushi_data/JNU/Endo_CSE15_sample/Pacbio_data/hybrid_spades_assembly/output_folder/K77/configs/config.info']" finished abnormally, OS return value: 34`

Kindly help me regarding this concern.

Thank You

### spades.log

[spades.log](https://github.com/ablab/spades/files/14961979/spades.log)

### params.txt

bin/spades.py -1 /data/jammu-univ/data/ayushi_data/JNU/Endo_CSE15_sample/illumina_data/Endo1_S101_R1_001.fastq -2 /data/jammu-univ/data/ayushi_data/JNU/Endo_CSE15_sample/illumina_data/Endo1_S101_R2_001.fastq --pacbio /data/jammu-univ/data/ayushi_data/JNU/Endo_CSE15_sample/Pacbio_data/Endo_combine.fastq -o /data/jammu-univ/data/ayushi_data/JNU/Endo_CSE15_sample/Pacbio_data/hybrid_spades_assembly/output_folder -t 80 -m 500

### SPAdes version

SPAdes v3.15.5

### Operating System

linux

### Python Version

Python 3.11.8

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:
```
  0:41:14.159  7030M / 70G   ERROR   General                 (single_read.hpp           :  74)   Invalid read: length of sequence should equal to length of quality line
```

So your input reads are corrupted (the long ones).
