### ISSUE TITLE
Several errors: finished abnormally, OS return value: 21 None, Too many erroneous kmers, the estimates might be unreliable, Invalid kmer coverage histogram, make sure that the coverage is indeed uniform and Failed to determine erroneous kmer threshold. Threshold set to: 3

### ISSUE THREAD

**Issue by Wyclif3** [ablab/spades#1276]
### Description of bug

Spades is failing to assemble some of my reads. I have tried to change the Kmer values and the problem still persists with several abnormalities. 

### spades.log

[spades.log](https://github.com/ablab/spades/files/14986118/spades.log)

### params.txt

[spades_redo.log](https://github.com/ablab/spades/files/14986256/spades_redo.log)

### SPAdes version

3.15.0

### Operating System

linux

### Python Version

3.8.4

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
You are only having 40 reads. This does not look like as something as a genome or some well-covered / well-formed part of it.

**Comment by Wyclif3** [comment]
This means some of the data are of low quality ? I already performed data cleaning in trimmomatic before assembling genes in hybpiper. What is the best solution for my problem at this point?
