### ISSUE TITLE
Cannot allocate memory. Error code: 12

### ISSUE THREAD

**Issue by ucassee** [ablab/spades#1279]
### Description of bug

Hi,
I meet the following error, how should I fix it?
Thanks

== Error ==  system call for: "['/Share/user/zhou/software/SPAdes-3.15.5-Linux/bin/spades-hammer', '/Share/sediment/02.assemble/00_metaspades/P22B56A/corrected/configs/config.info']" finished abnormally, OS return value: 12
None

### spades.log

[spades.log](https://github.com/ablab/spades/files/15047954/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/15047977/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux-3.10.0-1160.el7.x86_64-x86_64-with-centos-7.9.2009-Core

### Python Version

python 2.7.5

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
Log reads:
```
 31:58:29.810   325G / 404G  ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
```

So you are running out of RAM. If there is free RAM, then it might be possible that your server is improperly configured and it cannot allocate more than certainly amount to a single process (SPAdes). See https://github.com/ablab/spades/issues/871#issuecomment-965639427 for some suggestions here.
