### ISSUE TITLE
plasmidSPADES with Cosmids data 

### ISSUE THREAD

**Issue by OnlyHigh** [ablab/spades#128]
Hello, 
I'm writing this issue, mostly to ask about how plamidSPADES work with data from cosmids, 

Thanks, 
Luis Alfonso.

**Comment by Dmitry-Antipov** [comment]
Hi.
 plasmidSPAdes was designed to extract plasmid data from WGS  sequencing data, where plasmid sequence is mixed with chromosomal sequence. So, if you sequence only cosmids then there is no need in plasmidSPAdes - you should better use just SPAdes.
