### ISSUE TITLE
system call finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by almarch24** [ablab/spades#1281]
### Description of bug

I've run the command: python3 spades.py -1 ../share/spades/test_dataset/ecoli_1K_1.fq.gz -2 ../share/spades/test_dataset/ecoli_1K_2.fq.gz -o ~/ecoli
And then a message came:
== Error ==  system call for: "['/Applications/SPAdes-3.15.5-Darwin/bin/spades-hammer', '/Users/a.../ecoli/corrected/configs/config.info']" finished abnormally, OS return value: -9
None
Tell me please what the problem is.

### spades.log

[spades.log](https://github.com/ablab/spades/files/15066760/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/15066761/params.txt)

### SPAdes version

SPAdes-3.15.5-Darwin

### Operating System

macOS Ventura 13.6.6

### Python Version

Python 3.11.8

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by almarch24** [comment]
Macbook's system message was “spades-hammer” cannot be opened because the developer cannot be verified.

**Comment by asl** [comment]
Dup of https://github.com/ablab/spades/issues/1097
