### ISSUE TITLE
Error on installing Spades on Mac M2 Chip Macbook

### ISSUE THREAD

**Issue by Illynani** [ablab/spades#1283]
### Description of bug

I have tried to install the SPades package to run Unicycler for hybrid-short genome assembly.
However, I encountered an error while installing the SPades package on my laptop.

I am using a Macbook M2 Chip (Macbook Pro) on Sonoma 14.4.1.

I have tried several ways of installing such as ;

1. Downloaded the binary package for MacOs; Couldn't open the spade.py on my laptop (bash: command not found)
2. Downloaded the source code and compiled it manually - My Mac Terminal couldn't compile the source code.
3. Downloaded and installed it using the command: brew install spades (However it returned an error as the image attached).
4. Installed the Spades using Ubuntu on my Mac (ARM Visualization using Parallels software)

I have installed Python version 2 and version 3 on my laptop.

Is it because the SPades package is not compatible with M2 Mac Chip (ARM-based)? Do I have to use a laptop with an x86 chip?

I would appreciate very much appreciate your assistance in this matter
![Screenshot 2024-04-23 at 11 32 34 AM (2)](https://github.com/ablab/spades/assets/168262515/f84b6890-f2c9-4ea4-894c-54d7a4770e7b)

### spades.log

![Screenshot 2024-04-23 at 11 32 34 AM (2)](https://github.com/ablab/spades/assets/168262515/3abf9729-6ddb-42ac-bc42-e5b142579a2d)

### params.txt

![Screenshot 2024-04-23 at 11 32 34 AM (2)](https://github.com/ablab/spades/assets/168262515/fc83adb2-3d69-4180-9fe2-2a945a2fe935)

### SPAdes version

3.15.2

### Operating System

macOS Sonoma 14.4.1

### Python Version

Python 3.10.4

### Method of SPAdes installation

Binaries, Brew

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Dup of https://github.com/ablab/spades/issues/1062
