### ISSUE TITLE
finished abnormally

### ISSUE THREAD

**Issue by Tsingsjeen** [ablab/spades#1285]
### Description of bug

[spades.log](https://github.com/ablab/spades/files/15153227/spades.log)

### spades.log

[spades.log](https://github.com/ablab/spades/files/15153239/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/15153243/params.txt)

### SPAdes version

SPAdes genome assembler v3.15.5

### Operating System

Ubuntu 20.04.5 LTS

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
  0:00:00.234     1M / 24M   ERROR   General                 (pipeline.cpp              : 216)   Sorry, current version of metaSPAdes can work either with single library (paired-end only) or in hybrid paired-end + (TSLR or PacBio or Nanopore) mode.
```

You cannot use trusted contigs in metaSPAdes mode
