### ISSUE TITLE
OS return value: -6 

### ISSUE THREAD

**Issue by Nishofei** [ablab/spades#1290]
### Description of bug

Dear SPAdes team,
I'd like to use a mix of second- and third-generation sequencing data. However:
== Error ==  system call for: "['/home/sdae/Barley2/SPAdes-3.15.5-Linux/bin/spades-core', '/home/sdaf/Barley_data/THREE/target_pacbio_1/K55/configs/config.info']" finished abnormally, OS return value: -6
Do you have any suggestions to fix it?
Thank you in advance.

### spades.log

[spades.log](https://github.com/ablab/spades/files/15290760/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/15290763/params.txt)

### SPAdes version

3.15.5

### Operating System

Linux-5.4.0-150-generic-x86_64-with-debian-buster-sid

### Python Version

3.7.6

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
For the record, the log reads:
```
mimalloc: error: unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:   33574.535 s
   process: user: 968031.745 s, system: 5951.798 s, faults: 56
       rss: current: 643874893824, peak: 641814200320
    commit: current: 643874893824, peak: 643879088128
```

So the problem is quite clear.
