### ISSUE TITLE
== Error ==  system call for: "['SPAdes-3.15.5-Linux/bin/spades-hammer', 'spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11

### ISSUE THREAD

**Issue by Liuyw1217** [ablab/spades#1297]
### Description of bug

During the execution of 'spades.py --test', the process terminated abnormally with the following error message:
== Error ==  system call for: "['SPAdes-3.15.5-Linux/bin/spades-hammer', 'spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11

### spades.log

Command line: /home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades.py	--test	

System information:
  SPAdes version: 3.15.5
  Python version: 3.7.12
  OS: Linux-5.15.0-97-generic-x86_64-with-debian-bookworm-sid

Output dir: /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home4/liuyw/software/SPAdes-3.15.5-Linux/share/spades/test_dataset/ecoli_1K_1.fq.gz']
      right reads: ['/home4/liuyw/software/SPAdes-3.15.5-Linux/share/spades/test_dataset/ecoli_1K_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test/tmp
  Threads: 16
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test/spades.log

/home4/liuyw/software/SPAdes-3.15.5-Linux/share/spades/test_dataset/ecoli_1K_1.fq.gz: max reads length: 100
/home4/liuyw/software/SPAdes-3.15.5-Linux/share/spades/test_dataset/ecoli_1K_2.fq.gz: max reads length: 100

Reads length: 100

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test/corrected/configs/config.info

  0:00:00.000     1M / 11M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.15.5, git revision e757b8216f9a038fb616e9551a2d4891b2d19ad7
  0:00:00.057     1M / 11M   INFO    General                 (main.cpp                  :  76)   Loading config from /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test/corrected/configs/config.info
  0:00:00.087     1M / 11M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 16
  0:00:00.087     1M / 11M   INFO    General                 (memory_limit.cpp          :  54)   Memory limit set to 250 Gb
  0:00:00.087     1M / 11M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.093     1M / 11M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.093     1M / 11M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.093     1M / 11M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.094     1M / 11M   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 16 threads. This might take a while.
The program was terminated by segmentation fault
=== Stack Trace ===
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x421e29]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x423956]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f0a8b02c520]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer(cfree+0x10) [0x4849a0]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x494ffe]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x495c65]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x460f67]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x450515]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x461d47]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x457100]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x416300]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f0a8b013d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f0a8b013e40]
/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer() [0x420681]

== Error ==  system call for: "['/home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades-hammer', '/home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test/spades.log

Thank you for using SPAdes!

### params.txt

Command line: /home4/liuyw/software/SPAdes-3.15.5-Linux/bin/spades.py	--test	

System information:
  SPAdes version: 3.15.5
  Python version: 3.7.12
  OS: Linux-5.15.0-97-generic-x86_64-with-debian-bookworm-sid

Output dir: /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home4/liuyw/software/SPAdes-3.15.5-Linux/share/spades/test_dataset/ecoli_1K_1.fq.gz']
      right reads: ['/home4/liuyw/software/SPAdes-3.15.5-Linux/share/spades/test_dataset/ecoli_1K_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home4/liuyw/project/project2-virus/test-data/Cheng-data/spades_test/tmp
  Threads: 16
  Memory limit (in Gb): 250

### SPAdes version

SPAdes v3.15.5

### Operating System

Linux

### Python Version

Python 3.7.12

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is a known issue with pre-built binaries. Consider compiling from source

**Comment by daidiy1109** [comment]
module load python/3.8.6
module load gcc/12.2

the paoblem has been solved
