### ISSUE TITLE
can not restart from last 

### ISSUE THREAD

**Issue by catslu** [ablab/spades#1298]
### Description of bug

Hi dear, I am using spades.py --meta to process 10 metagenome data. I used -m 490 that our computer may no memory so the system got  stuck. I ctrl + c to stop it. And I used a lower memory limit with -m 455, it showed that:
$user   spades.py -o ./metaspades_out/ -m 455 --continue --restart-from last

== Error ==  you cannot specify reads with --restart-from option!

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

how  I can do next step?

### spades.log

[spades.log](https://github.com/ablab/spades/files/15365955/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/15365956/params.txt)

### SPAdes version

SPAdes genome assembler v3.15.4

### Operating System

Linux Red Hat 4.8.5-44

### Python Version

3.10.14

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

You'd need to use either `--restart-from` or `--continue`, not both

**Comment by catslu** [comment]
> Hello
> 
> You'd need to use either `--restart-from` or `--continue`, not both

(mpa) [liuxl@gnode5 con_lt_co-assemble]$ spades.py -o ./metaspades_out/ -m 455 --restart-from last


== Error ==  you cannot specify reads with --restart-from option!

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

**Comment by catslu** [comment]
(mpa) [liuxl@gnode5 con_lt_co-assemble]$ spades.py -o ./metaspades_out/ --continue


== Error ==  you cannot specify any option except -o with --continue option! Please use '--restart-from last' if you need to change some of the options from the initial run and continue from the last available checkpoint.

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

**Comment by asl** [comment]
I cannot reproduce this issue, it seems there is something extra on command line, but we do not see it here. The next version of SPAdes will print these extra arguments, so it will be easier to debug. Please reopen if the issue sill be there.
