### ISSUE TITLE
There is no contig.fasta in my output dir

### ISSUE THREAD

**Issue by SoSongzhi** [ablab/spades#1306]
### Description of bug

<img width="786" alt="image" src="https://github.com/ablab/spades/assets/74604653/20bfddbd-fbd4-4e44-8c22-5cbe282e292c">
even though i got several files after i use spades to assemble simulated reads, but i can not found contig fasta. Do you know why it happened? thanks.

### spades.log

[spades.log](https://github.com/ablab/spades/files/15400201/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/15400212/params.txt)

### SPAdes version

3.16.0-dev

### Operating System

macOS Ventura Version 13.6

### Python Version

Python 3.8.4

### Method of SPAdes installation

manual from github

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
=== ERRORs:
 * 0:00:01.264     1M / 18M   ERROR   General                 (kmer_coverage_model.cpp   : 188)   Invalid kmer coverage histogram, make sure that the coverage is indeed uniform
 * system call for: "['/Users/zhisong/Desktop/spades/bin/spades-core', '/Users/zhisong/Desktop/spades/testfasta1/K127/configs/config.info', '/Users/zhisong/Desktop/spades/testfasta1/K127/configs/isolate_mode.info']" finished abnormally, OS return value: 255
```

Given that you are having only 1000 reads and maximum read length is 6899 bp with average of 1728.57 bp, this does not look like a valid input data
