### ISSUE TITLE
Gb or GB as unit for RAM limit for SPAdes

### ISSUE THREAD

**Issue by AlesBucek** [ablab/spades#131]
I'm starting to use dipSPADES (SPAdes genome assembler v3.11.1) and I noticed that the -m parameter is, according to the option description, specified in Gb (gigabits) - is it correct or is it rather expected that the provided number is gigabytes (GB) of RAM?  
Thanks!

**Comment by asl** [comment]
Dear Ales,

Everything is in gigabytes.

PS: Note that dipSPAdes is unmaintained and will be removed soon. It is also contains known bugs.

**Comment by mmokrejs** [comment]
@AlesBucek You are not the first one to realize @asl uses Gb in places where GB should be used. @asl Why don't you fix those confusing places?
