### ISSUE TITLE
spades error #255 unequal amount of reads

### ISSUE THREAD

**Issue by ainurftn** [ablab/spades#1318]
### Description of bug

I cannot completed my spades operation because it says the files have unequal amount of reads. I have googled on how to solve the problem & some of them suggested using fastq-pair but it still does not work.

fastq_pair /home/colfax/Documents/AINUR/TK/TK_1unmapped.fastq /home/colfax/Documents/AINUR/TK/TK_2unmapped.fastq
Writing the paired reads to /home/colfax/Documents/AINUR/TK/TK_1unmapped.fastq.paired.fq and /home/colfax/Documents/AINUR/TK/TK_2unmapped.fastq.paired.fq.
Writing the single reads to /home/colfax/Documents/AINUR/TK/TK_1unmapped.fastq.single.fq and /home/colfax/Documents/AINUR/TK/TK_2unmapped.fastq.single.fq
Left paired: 0		Right paired: 0
Left single: 16723329		Right single: 17017982

I am confused as why the paired reads are 0. Please suggest me ways to match the paired reads.

### spades.log

Documents/AINUR/TK/TK_1unmapped.fastq.single.fq and /home/colfax/Documents/AINUR/TK/TK_2unmapped.fastq.single.fq contain unequal amount of reads

== Error ==  system call for: "['/home/colfax/anaconda3/share/spades-3.13.0-0/bin/spades-hammer', '/home/colfax/Documents/AINUR/TK/spades_TK/corrected/configs/config.info']" finished abnormally, err code: 255

### params.txt

Command line: /home/colfax/anaconda3/bin/spades.py	-k	127	--careful	-1	/home/colfax/Documents/AINUR/TK/TK_1unmapped.fastq.single.fq	-2	/home/colfax/Documents/AINUR/TK/TK_2unmapped.fastq.single.fq	-o	/home/colfax/Documents/AINUR/TK/spades_TK	-t	16	

System information:
  SPAdes version: 3.13.0
  Python version: 3.8.5
  OS: Linux-6.5.0-21-generic-x86_64-with-glibc2.10

Output dir: /home/colfax/Documents/AINUR/TK/spades_TK
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/colfax/Documents/AINUR/TK/TK_1unmapped.fastq.single.fq']
      right reads: ['/home/colfax/Documents/AINUR/TK/TK_2unmapped.fastq.single.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [127]
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/colfax/Documents/AINUR/TK/spades_TK/tmp
  Threads: 16
  Memory limit (in Gb): 125

### SPAdes version

SPAdes 4.0.0

### Operating System

Linux

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Well, the error message is pretty exact: your input reads are corrupted, left ones should correspond to right ones. SPAdes cannot fix your broken read for you, you need to ensure the input if correct. If you are using some kind of pre-processing or filtering, for example, make sure the process is paired-end aware.
