### ISSUE TITLE
SPAdes 4.0.0 incorrect Python version detection?

### ISSUE THREAD

**Issue by Kroh-N** [ablab/spades#1319]
### Description of bug

SPAdes 4.0.0
reports an error when trying to run spades.py or metaspades.py:

```
== Error ==  
Python version 3.6.8 is not supported!
Minimal supported version is 3.8
```
My current Python version is `Python 3.9.13` though

Any hint how to resolve would be appreciated

### spades.log

[spades.log](https://github.com/user-attachments/files/15945789/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/15945792/params.txt)

### SPAdes version

SPAdes 4.0.0

### Operating System

AlmaLinux 8.9

### Python Version

Python 3.9.13

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
What is the output of `/usr/bin/env python3 --version` for you?

**Comment by Kroh-N** [comment]
It was Python 3.6.x but now is Python 3.9.13

After a number of restarts SPAdes is now working  - I do not really know why, but thanks for the rapid reply!
All the best!
