### ISSUE TITLE
Combine contigs

### ISSUE THREAD

**Issue by SilasK** [ablab/spades#132]
If I understand the log file correctly, spades combine the different path created and fixes overlap and so on... 
```
  0:53:31.916     6G / 11G   INFO    General                 (path_extender.hpp         : 885)   Processed 80964 paths from 89953 (90%)
  0:53:33.811     6G / 11G   INFO    General                 (launcher.cpp              : 234)   Finalizing paths
  0:53:33.811     6G / 11G   INFO    General                 (launcher.cpp              : 236)   Deduplicating paths
  0:53:34.265     6G / 11G   INFO    General                 (launcher.cpp              : 240)   Paths deduplicated
  0:53:34.265     6G / 11G   INFO   PEResolver               (pe_resolver.hpp           : 295)   Removing overlaps
  0:53:34.265     6G / 11G   INFO   PEResolver               (pe_resolver.hpp           : 305)   Marking overlaps
```

Does spades also combine the different contigs generated with different k-mers? 
Would it be possible to access this functionality as a sperate application?

I thought about doing a second assembly with the reads that don't align to the first assembly and then combine the two.

**Comment by andrewprzh** [comment]
Not exactly. 

Regarding the iterative assembly graph construction -- SPAdes uses small k-mer sizes to generate contigs that (hopefully) restore low-covered regions and then passes them as reads to the next iteration with larger K.

The output contigs are generated only from the assembly graph constructed with the last K values by looking for paths in the graph (that are supported with read pairs or long reads). So in fact, no path / contig combining occurs in SPAdes. The part of the log that you've posted only removes duplicated parts in paths.

However, SPAdes can take additional contigs as input (see trusted and untrusted contigs in the manual http://cab.spbu.ru/files/release3.12.0/manual.html).  Untrusted are used in the way similar to long error-prone reads (for repeat resolution and scaffolding only), trusted are also added to the graph construction as long accurate reads.

**Comment by SilasK** [comment]
Thank you very much for your explication.
The trick with the additional contigs doesn't work (yet) for metaspades,
isn't it?

Wouldn't it also make sense to start with the high abundant reads and then
finishing with the low abundant reads?

**Comment by andrewprzh** [comment]
Yes, metaSPAdes does not support additional contigs yet. 

By the way, what is the main purpose of assembling reads separately, because metaSPAdes is actually designed to work with reads of different abundance?

**Comment by SilasK** [comment]
The idea of combing contigs comes from the observation that after
assembling reads with spades. The reads witch don't map to the contigs.
cancstill be assembled using spades again.

I suspect that some high abundant reads (or k ners) interfere with the
assembly of low abundant ones.

I vizualized my assembly with bandage and scanned trough the assembly graph
by depth (starting from high coverage nodes).

What seems to be a very nice contig at high coverage becomes a fuzzy ball
when displaying lowerabundant nodes. Apparently a high abundant contig
overlaps with low abundant contigs.
E.g. a sample of a two strains from the same species.

Idaly one would duplicate the common nodes and make two contigs out of it.

-> can  spades do that? Or can it be brought to do so?

**Comment by andrewprzh** [comment]
Could you provide the figure you described? How do you define "common nodes"?

If I understand correctly it is possible to make a script which separate the contigs the way you described just by using the graph and coverage values provided. I can try to discuss it with metaSPAdes developers as well.
