### ISSUE TITLE
Python warning on 3.12

### ISSUE THREAD

**Issue by asl** [ablab/spades#1320]
```
/usr/bin/env python3 --version
Python 3.12.3
```

```
spades/share/spades/spades_pipeline/support.py:488: SyntaxWarning: invalid escape sequence '\d'
  return [atoi(c) for c in re.split("(\d+)", text)]
SPAdes genome assembler v4.0.0
```

**Comment by PandengWang** [comment]
I encounter the same problem. And the spades.py is not work anymore with the error: `Usage: spades.py [options] -o <output_dir>
spades.py: error: argument -m/--memory: invalid int value: 'eta'`.

Do you have any ideas about how to resolve this problem?
Thanks!

**Comment by asl** [comment]
Fixed in https://github.com/ablab/spades/commit/60ad35e88074f9340d14e6a814c1cdd0fe30e13b
