### ISSUE TITLE
SPAdes: K21,33,55,77,99,127, didtn't generate any data in files: scaffolds.gfa and contigs.fasta

### ISSUE THREAD

**Issue by 02Julie2023** [ablab/spades#1322]
### Description of bug

After running the SPAdes, it doesn't generate any data in the files below:
assembly_graph_after_simplification.gfa
 assembly_graph.fastg
 assembly_graph_with_scaffolds.gfa
before_rr.fasta
 contigs.fasta
Could you please take a look at it? I appreciate it.

### spades.log

[warnings.log](https://github.com/user-attachments/files/16023286/warnings.log)
[stdout.12768013.pdf](https://github.com/user-attachments/files/16023340/stdout.12768013.pdf)

### params.txt

[params.txt](https://github.com/user-attachments/files/16023373/params.txt)

### SPAdes version

SPAdes / 3.15.5

### Operating System

macOS Sonoma Version 14.4.1

### Python Version

Python 3.11.1

### Method of SPAdes installation

pip

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
So, the log reads:

```
(simplification.cpp : 495) After simplification: 
0:01:14.501 1M / 5155M INFO General
(simplification.cpp : 496) Average coverage = 0
0:01:14.501 1M / 5155M INFO General
(simplification.cpp : 497) Total length = 0
0:01:14.502 1M / 5155M INFO General
(simplification.cpp : 498) Median edge length: 0
0:01:14.502 1M / 5155M INFO General
(simplification.cpp : 499) Edges: 0
0:01:14.502 1M / 5155M INFO General
(simplification.cpp : 500) Vertices: 0
0:01:14.502 1M / 5155M WARN General
```

Given that you're having less than 1k reads, it does not seem to be a genome or a part of any genome, so your reads simply do not assemble at all.
