### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\d' return [atoi(c) for c in re.split("(\d+)", text)]

### ISSUE THREAD

**Issue by sheikki** [ablab/spades#1326]
### Description of bug

This happens with the latest released binaries on Ubuntu 24.04. Just running spades.py:

```
spades.py
/usr/local/share/spades/spades_pipeline/support.py:488: SyntaxWarning: invalid escape sequence '\d'
  return [atoi(c) for c in re.split("(\d+)", text)]
SPAdes genome assembler v4.0.0

Usage: spades.py [options] -o <output_dir>

Basic options:     
...
```

As far as I can tell, the program works just fine though..

### spades.log

NA

### params.txt

NA

### SPAdes version

4.0.0

### Operating System

Ubuntu 24.04

### Python Version

 3.12.3

### Method of SPAdes installation

binaties

### No errors reported in spades.log

- [X] Yes

**Comment by zzzapperant** [comment]
i met the same warning when using 'SPAdes genome assembler v4.0.0'.

**Comment by asl** [comment]
This was fixed in https://github.com/ablab/spades/commit/60ad35e88074f9340d14e6a814c1cdd0fe30e13b

**Comment by IdoBar** [comment]
Hi @asl,

Is there a Docker container with a version that doesn't have this issue?

Thanks, Ido

**Comment by asl** [comment]
> Is there a Docker container with a version that doesn't have this issue?

No idea. We do not provide any containers. There are pre-built snapshots at https://github.com/ablab/spades/releases/tag/continuous Alternatively, you can always compile from the `main`.
