### ISSUE TITLE
Anaconda cannot download new version of spades

### ISSUE THREAD

**Issue by stopguessingwho1am** [ablab/spades#1327]
### Description of bug

Everytime I try to download Spades 4.0.0 from Anaconda, Conda downloaded Spades 3.13 instead. When I try to download Spades via the code conda install bioconda spades 4.0.0, conda replies with Packagenotfound error. 
(My Anaconda is the newest version 24.5.0)

<img width="261" alt="Screenshot 2024-07-05 at 9 12 21 AM" src="https://github.com/ablab/spades/assets/173384809/cd056f5f-fe0e-4116-a372-e0e30567ff66">
<img width="496" alt="Screenshot 2024-07-05 at 9 15 30 AM" src="https://github.com/ablab/spades/assets/173384809/a6a29512-665f-4afd-94db-0d1b16a24253">
<img width="499" alt="Screenshot 2024-07-05 at 9 14 19 AM" src="https://github.com/ablab/spades/assets/173384809/1aa8c613-7614-4642-9503-e012e29acd40">

### spades.log

N/A

### params.txt

N/A

### SPAdes version

Spades 3.13

### Operating System

Linux 64

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
We are not maintaining these packages, so I'd suggest you to report issue to Anaconda. But likely you are using old (broken) sysroot for your environments.
