### ISSUE TITLE
where can I find SPAdes version 3.7.1 for circlator

### ISSUE THREAD

**Issue by splaisan** [ablab/spades#133]
I do not find archives of your previous versions, could you please help
Thanks

**Comment by tolot27** [comment]
http://spades.bioinf.spbau.ru/release3.7.1/

**Comment by asl** [comment]
The releases are right over there: https://github.com/ablab/spades/releases

**Comment by splaisan** [comment]
my bad, overlooked this 'Releases' link. THANKS

**Comment by sihellem** [comment]
Hello!

I would also like to use SPAdes 3.7.1 for Circlator.

However, the latest available release now is 3.8.0.

Would it be possible to post a tar file for Linux here?

Thanks in advance,
Simon

**Comment by asl** [comment]
Hello

As we already mentioned many times, it does not make any sense to use this old version of SPAdes – it is known to contain many issues that were fixed afterwards. Though certainly you can compile it from source – there is corresponding release branch in the repo

**Comment by sihellem** [comment]
Dear Anton,

Thank you for your reply.

I was not able to find version 3.7.1. As mentioned previously, version in the repository starts at 3.8.0: https://github.com/ablab/spades/releases?after=v3.12.0

I just found your explanation on this thread, so I will ignore warnings and use an up-to-date SPAdes version: https://github.com/sanger-pathogens/circlator/issues/72

Cheers,
Simon

**Comment by asl** [comment]
As I said, it's in the branches, not releases. We never put ancient releases to github.
