### ISSUE TITLE
Spades finished abnormally 

### ISSUE THREAD

**Issue by stopguessingwho1am** [ablab/spades#1332]
### Description of bug

Spades finished abnormally after 16 hours. Not sure what is wrong. 

== Error ==  system call for: "['/gpfs1/home/xinylim/SPAdes-4.0.0-Linux/bin/spades-hammer', '/scratch/ResearchGroups/ace_amytan/rita_spades/Dig1_7_19_21B/corrected/configs/config.info']" finished abnormally, OS return value: 12

### spades.log

[diespades.log](https://github.com/user-attachments/files/16186504/diespades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16186516/params.txt)

### SPAdes version

Spades 4.0

### Operating System

linux hpc

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:
```
  0:15:49.423     1M / 16G   INFO    General                 (kmer_index_builder.hpp    : 264)   Starting k-mer counting.
  0:15:49.521     1M / 16G   ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
  0:15:49.521     1M / 16G   ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12=== Stack Trace ===
  0:15:49.521     1M / 16G   ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
```

So, you are running out of RAM. Please ensure that enough RAM is available to your SPAdes job (especially if you're running within some resource-constrained job submission system).
