### ISSUE TITLE
SPAdes: Running since 4 days 

### ISSUE THREAD

**Issue by pratibha-kadam** [ablab/spades#1333]
### Description of bug

Dear developer,

I am using SPAdes on my metagenomic illumina data, I have trimmed the adaptors and started the SPAdes analysis but it is not finishing the process and neither giving me the result.

I have found that in my trimmed paired end data the number of reads are not equal, is that a problem?
or 
memory allocation is the problem? 
I am using 4GB RAM computer with 16 threads but for the analysis I have given only 6 threads.

Please let me know whats wrong here

This is the command:
~/SPAdes-4.0.0-Linux$ bin/spades.py -1 /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz -2 /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R2.fastq.gz --meta -t 6 -o /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades

Following is the screenshot of the run:
![Screenshot from 2024-07-12 14-45-01](https://github.com/user-attachments/assets/58407154-a4c5-4391-975f-8fd2f99d0e21)

### spades.log

Command line: bin/spades.py	-1	/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz	-2	/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R2.fastq.gz	--meta	-t	6	-o	/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades	

System information:
  SPAdes version: 4.0.0
  Python version: 3.11.5
  OS: Linux-6.5.0-41-generic-x86_64-with-glibc2.35

Output dir: /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz']
      right reads: ['/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
  Assembly graph output will use GFA v1.2 format
Other parameters:
  Dir for temp files: /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades/tmp
  Threads: 6
  Memory limit (in Gb): 62

======= SPAdes pipeline started. Log can be found here: /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades/spades.log

/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz: max reads length: 151
/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R2.fastq.gz: max reads length: 151

Reads length: 151

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /home/fmr/SPAdes-4.0.0-Linux/bin/spades-hammer /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades/corrected/configs/config.info

  0:00:00.000     1M / 17M   INFO    General                 (main.cpp                  :  76)   Starting BayesHammer, built from N/A, git revision 38af83de44403f833a32073fd47ba469d998efd1
  0:00:00.002     1M / 17M   INFO    General                 (main.cpp                  :  77)   Loading config from "/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades/corrected/configs/config.info"
  0:00:00.004     1M / 17M   INFO    General                 (main.cpp                  :  79)   Maximum # of threads to use (adjusted due to OMP capabilities): 6
  0:00:00.005     1M / 17M   INFO    General                 (memory_limit.cpp          :  55)   Memory limit set to 62 Gb
  0:00:00.005     1M / 17M   INFO    General                 (main.cpp                  :  87)   Trying to determine PHRED offset
  0:00:00.005     1M / 17M   INFO    General                 (main.cpp                  :  93)   Determined value is 33
  0:00:00.005     1M / 17M   INFO    General                 (hammer_tools.cpp          :  40)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.005     1M / 17M   INFO    General                 (main.cpp                  : 114)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.005     1M / 17M   INFO   K-mer Counting           (kmer_data.cpp             : 284)   Estimating k-mer count
  0:00:00.063    97M / 102M  INFO   K-mer Counting           (kmer_data.cpp             : 289)   Processing "/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz"
  0:02:06.866    97M / 103M  INFO   K-mer Counting           (kmer_data.cpp             : 298)   Processed 30955479 reads
  0:02:06.866    97M / 103M  INFO   K-mer Counting           (kmer_data.cpp             : 289)   Processing "/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R2.fastq.gz"
  0:04:11.745    97M / 103M  INFO   K-mer Counting           (kmer_data.cpp             : 298)   Processed 61910958 reads
  0:04:11.745    97M / 103M  INFO   K-mer Counting           (kmer_data.cpp             : 303)   Total 61910958 reads processed
  0:04:11.988    97M / 103M  INFO   K-mer Counting           (kmer_data.cpp             : 306)   Estimated 4786539021 distinct kmers
  0:04:11.989     1M / 103M  INFO   K-mer Counting           (kmer_data.cpp             : 310)   Filtering singleton k-mers
mimalloc: warning: unable to allocate aligned OS memory directly, fall back to over-allocation (21751660544 bytes, address: 0x7dd5cb9f1000, alignment: 67108864, commit: 1)
  0:04:21.584    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 316)   Processing "/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz"

### params.txt

Command line: bin/spades.py	-1	/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz	-2	/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R2.fastq.gz	--meta	-t	6	-o	/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades	

System information:
  SPAdes version: 4.0.0
  Python version: 3.11.5
  OS: Linux-6.5.0-41-generic-x86_64-with-glibc2.35

Output dir: /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R1.fastq.gz']
      right reads: ['/media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/3.Cutadapt/MT_2024_0704/Trimmed_MT_2024_0704_R2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
  Assembly graph output will use GFA v1.2 format
Other parameters:
  Dir for temp files: /media/fmr/HDD1/Wastewater_AMR_Analysis_2024_06_27/7.Spades/tmp
  Threads: 6
  Memory limit (in Gb): 62

### SPAdes version

SPAdes v4.0.0

### Operating System

Linux

### Python Version

Python3

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by pratibha-kadam** [comment]
It could give the error this time.
![Screenshot from 2024-07-12 16-49-03](https://github.com/user-attachments/assets/6d54a0b6-ef90-4279-a57e-4d44ef5a84e9)

Please let me know what did go wrong?

**Comment by pratibha-kadam** [comment]
[spades.log](https://github.com/user-attachments/files/16192886/spades.log)

Please see this SPAdes log file for your reference.

**Comment by asl** [comment]
The error message is quite clear:
```
  2:08:44.263  2044M / 50G   ERROR  K-mer Counting           (kmer_data.cpp             : 350)   The reads contain too many k-mers to fit into available memory. You need approx. 105.877GB of free RAM to assemble your dataset
```

**Comment by pratibha-kadam** [comment]
@asl Thank you for your quick response. 
I did not see the error

What do I do now?
I have 64GB RAM and 16 threads computer. I was running the command on 6 threads with k-mer size was 75.

will an increase in the size of K-mer help?
