### ISSUE TITLE
Resuming Hybrid Assembly fails

### ISSUE THREAD

**Issue by byronverz9** [ablab/spades#1335]
### Description of bug

When resuming a hybrid assembly job with `spades.py -o outdir/ --continue` for a hybrid job, the job fails with
```
== Error ==  something went wrong and file with corrected reads (/home/biomineruser/coassembly/SU03052702/spades_out/corrected/SU03052702_S19_R_unpaired00.0_0.cor.fastq) is missing!
```
But the corrected directory looks like
```
        4096 Jul 17 06:16 ../
 39454348546 Jul 16 20:17 SU03052702_S19_R1_001_paired_human_clean.fastq00.0_0.cor.fastq
 39236860650 Jul 16 20:17 SU03052702_S19_R2_001_paired_human_clean.fastq00.0_0.cor.fastq
    50487778 Jul 16 20:17 SU03052702_S19_R_unpaired00.0_0.cor.fastq.gz
        4096 Jul 17 06:16 configs/
         504 Jul 16 20:17 corrected.yaml
         142 Jul 17 06:16 dont_correct.yaml
         294 Jul 17 06:16 to_correct.yaml
```

This looks like the script is expecting all files to be uncompressed, but the unpaired reads is already compressed.

### spades.log

[spades.log](https://github.com/user-attachments/files/16261124/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16261126/params.txt)

### SPAdes version

SPAdes version: 4.0.0

### Operating System

OS: Linux-6.5.0-1024-azure-x86_64-with-glibc2.35

### Python Version

Python version: 3.12.2

### Method of SPAdes installation

Downloaded binaries with wget

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
> This looks like the script is expecting all files to be uncompressed, but the unpaired reads is already compressed.

Yes. Unfortunately, the compression procedure is assumed to be atomic, however, if it is terminated, then everything might left in middle state. I would suggest you to uncompress the unpaired reads and restart.

Also, installing `pigz` will make compression faster

**Comment by byronverz9** [comment]
@asl that seems to have done the trick thanks.

And will do for `pigz` thank you.
