### ISSUE TITLE
SPAdes error -7 

### ISSUE THREAD

**Issue by MLee39** [ablab/spades#134]
I'm trying to do a denovo assembly with pair end reads and this is the linux command I used to run spades: 
SPAdes-3.11.0-Linux/bin/spades.py -1 ../ARSLN01003_014_LN14/raw/LN14_R1.fastq -2 ../ARSLN01003_014_LN14/raw/LN14_R2.fastq --rna -m 500 -t 30 -o denovo_LN14.alignment

I received the following error and I do not know what this error means and why I keep getting it. 
{
== Error ==  system call for: "['/scinet01/gov/usda/ars/scinet/project/nea_bioinformatics/nemchinov/virus/SPAdes-3.11.0-Linux/bin/hammer', '/scinet01/gov/usda/ars/scinet/project/nea_bioinformatics/nemchinov/virus/denovo_LN14.alignment/corrected/configs/config.info']" finished abnormally, err code: -7

}

Has anybody run into the same issue? Any advice you could give me?

Thank you in advance!

**Comment by asl** [comment]
Please attach the files mentioned just two lines below the ones you posted.

**Comment by asl** [comment]
Please reopen when you will have a chance to upload the files.
