### ISSUE TITLE
error while parsing GFA path record

### ISSUE THREAD

**Issue by IanDMedeiros** [ablab/spades#1342]
### Description of bug

binspreader threw an error while parsing assembly_graph_with_scaffolds.gfa. It looks like there are semicolons where the program was expecting tabs. I did not modify the assembly graph in any way after the assembly.

### spades.log

[binspreader.60.log](https://github.com/user-attachments/files/16353979/binspreader.60.log)

There was no spades.log file I can find from this run. I am attaching the log output from the hpc job.

### params.txt

There was no params.txt file for this run.

### SPAdes version

4.0.0

### Operating System

Linux Rocky 8.9

### Python Version

3.11.4

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
You need to use the latest BinSPreader that is capable of reading GFA v1.2 files. Alternatively, if you upgrading BinSPreader is not an option, you can emit graphs in old GFA v1.1 format via `--gfa11` option.

See https://ablab.github.io/spades/output.html#gfa for more information

Note that BinSPreader is a part of SPAdes package now, so you can just build it (https://ablab.github.io/spades/binspreader.html)

**Comment by IanDMedeiros** [comment]
Thanks for the quick response. I installed the binaries from the latest SPAdes release on github yesterday. That is not the latest version of BinSPreader?

**Comment by asl** [comment]
BinSPreader is a part of source release, but not a part of binary release (it is a separate tool after all). You'd need to build it from source.

**Comment by IanDMedeiros** [comment]
Ok. Thank you, I will build everything from source. But fyi the (apparently incorrect) BinSPreader binary was present in the SPAdes binary release that I downloaded from Github.

**Comment by asl** [comment]
> But fyi the (apparently incorrect) BinSPreader binary was present in the SPAdes binary release that I downloaded from Github.

Oh, right, sorry, my bad. Then we need to check what is going on, everything should be compatible.

**Comment by IanDMedeiros** [comment]
Unfortunately compiling BinSPreader from the source code has completely defeated me. The main SPAdes modules all compile, but no matter what I try* the compilation still has "binspreader project is disabled"

I noticed that the instructions at https://ablab.github.io/spades/binspreader.html still reference GFA 1.0 format; is that page outdated?

*Attempted following the instructions at https://ablab.github.io/spades/installation.html:
`SPADES_ENABLE_PROJECTS="binspreader" ./spades_compile.sh`
`SPADES_ENABLE_PROJECTS="all" ./spades_compile.sh`
`./spades_compile.sh SPADES_ENABLE_PROJECTS="all"`
`./spades_compile.sh -SPADES_ENABLE_PROJECTS="all"`
`./spades_compile.sh SPADES_ENABLE_PROJECTS="binspreader"`
`./spades_compile.sh -SPADES_ENABLE_PROJECTS="binspreader"`

**Comment by asl** [comment]
> EDITED: Never mind, I see now that it is DSPADES_ENABLE_PROJECT not SPADES_ENABLE_PROJECT. That seems to have worked.

Yes, it is `-DSPADES_ENABLE_PROJECTS="all"`. Looks like the line break is in unfortunate place, but we cannot limit this :(

**Comment by IanDMedeiros** [comment]
Hi @asl - Did you have a chance to check whether there is a problem with the BinSPreader binary packaged with the SPAdes 4.0 release for linux? Unfortunately I have not been able to successfully compile BinSPreader on our HPC.

**Comment by asl** [comment]
The fix should be available as a part of continuous build : https://github.com/ablab/spades/releases/tag/continuous
