### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by xiaobai5456** [ablab/spades#1344]
### Description of bug

== Error ==  system call for: "['/home/chn/miniconda3/envs/spades/bin/spades-hammer', '/mnt/e/gene/00.CleanData/G1-E1/output_dir/corrected/configs/config.info']" finished abnormally, OS return value: -6
None

### spades.log

[spades.log](https://github.com/user-attachments/files/16371531/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16371533/params.txt)

### SPAdes version

Spades v.4.0.0

### Operating System

Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

### Python Version

Python version: 3.12.4

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:
```
mimalloc: error: unable to allocate OS memory (884998144 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
```

So you are running out of RAM

**Comment by xiaobai5456** [comment]
What should I do

**Comment by asl** [comment]
> What should I do

Run you assembly job on machine with more RAM

**Comment by xiaobai5456** [comment]
But I installed spades on Ubuntu，Do I need to install spades separately?

**Comment by asl** [comment]
> But I installed spades on Ubuntu，Do I need to install spades separately?

Sorry, I do not follow. Certainly, in order to run SPAdes elsewhere you need to install it there
