### ISSUE TITLE
Error-6 can not open tmp folder 

### ISSUE THREAD

**Issue by emilyhokning** [ablab/spades#1345]
### Description of bug

Error-6 can not open tmp folder, the tmp folder exist but seems to be empty.

### spades.log

[spades.log](https://github.com/user-attachments/files/16407889/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16407927/params.txt)

### SPAdes version

v3.15.4

### Operating System

Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.10

### Python Version

3.8.12

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
This looks like and I/O problem on your end. I would suggest you to ask your system administrator.
