### ISSUE TITLE
== Error ==  system call for: finished abnormally, OS return value: 21 (Pair of read files contain unequal amount of reads)

### ISSUE THREAD

**Issue by yiasei** [ablab/spades#1348]
### Description of bug

Pair of read files "/home/ysein/nfs/Residential_training/results/mapping_no_vector/unaligned_reads/15-B104_230113_L004_R1.cleaned_unaligned.fastq.gz" and "/home/ysein/nfs/Residential_training/results/mapping_no_vector/unaligned_reads/15-B104_230113_L004_R2.cleaned_unaligned.fastq.gz" contain unequal amount of reads

== Error ==  system call for: "['/home/ysein/.conda/envs/spades/bin/spades-hammer', '/home/ysein/nfs/Residential_training/results/spades_assembly_results/corrected/configs/config.info']" finished abnormally, OS return value: 21

### spades.log

[spades.log](https://github.com/user-attachments/files/16462122/spades.log)

### params.txt

[spades_assembly_and_variant_calling.txt](https://github.com/user-attachments/files/16462188/spades_assembly_and_variant_calling.txt)

### SPAdes version

SPAdes v4.0.0

### Operating System

HPC: Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.17

### Python Version

Python 3.12.4

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
So, what is not clear in:
```
Pair of read files "/home/ysein/nfs/Residential_training/results/mapping_no_vector/unaligned_reads/15-B104_230113_L004_R1.cleaned_unaligned.fastq.gz" and "/home/ysein/nfs/Residential_training/results/mapping_no_vector/unaligned_reads/15-B104_230113_L004_R2.cleaned_unaligned.fastq.gz" contain unequal amount of reads
```
?

You input reads are corrupted.

**Comment by yiasei** [comment]
What do you mean the input reads are corrupted?
We trimmed the reads and made sure only paired reads were kept. How come the spades assembly still gives us an error at this position.

**Comment by asl** [comment]
> We trimmed the reads and made sure only paired reads were kept. How come the spades assembly still gives us an error at this position.

You need to ensure that your trimming procedure is paired-end aware, your left reads should correspond to the right ones. Currently there are unequal amount of reads, so this is certainly not so.

**Comment by yiasei** [comment]
The trimming and preprocessing procedures were paired-end aware. Here are the fastqc files showing that the R1 and R2 correspond. We have trimmed using fast, trimmomatic, and trim galore and for each the SPAdes assembly it would be terminated at this spot.

[15-B104_230113_L004_R1_R2.cleaned_fastqc.zip](https://github.com/user-attachments/files/16462495/15-B104_230113_L004_R1_R2.cleaned_fastqc.zip)

**Comment by asl** [comment]
> The trimming and preprocessing procedures were paired-end aware. Here are the fastqc files showing that the R1 and R2 correspond. We have trimmed using fast, trimmomatic, and trim galore and for each the SPAdes assembly it would be terminated at this spot.

Well, then you need to find out which step of your pipeline produces unequal read count.

Note that your report mentioned "15-B104_230113_L004_R1.cleaned.fastq.gz" though the error message is about "15-B104_230113_L004_R1.cleaned_unaligned.fastq.gz", these are different files.

Taking the educated guess about typical user issues: you tried to align reads to some reference, then took only unaligned ones and tried to assemble them? Then you need to ensure you are doing proper steps when only one mate is aligned and another one is not, i.e. you need to ensure you're picking either both reads from the pair or none, but not a single one.

**Comment by yiasei** [comment]
What I shared is the fastqc files from the trimming process. We then aligned using bowtie2 to remove the host genome so as to remain with what may potentially be our reads of interest. Here are the fastqc files after aligning and proceeding with the unaligned fastqc reads. 
[15-B104_230113_L004_R1_R2.cleaned_unaligned_fastqc.zip](https://github.com/user-attachments/files/16462737/15-B104_230113_L004_R1_R2.cleaned_unaligned_fastqc.zip)

**Comment by asl** [comment]
So, exactly the case I mentioned. From your report:


Measure | Value
-- | --
Filename | 15-B104_230113_L004_R1.cleaned_unaligned.fastq.gz
File type | Conventional base calls
Encoding | Sanger / Illumina 1.9
Total Sequences | 23607378
Total Bases | 3.4 Gbp
Sequences flagged as poor quality | 0
Sequence length | 15-151
%GC | 43


Filename | 15-B104_230113_L004_R2.cleaned_unaligned.fastq.gz
-- | --
File type | Conventional base calls
Encoding | Sanger / Illumina 1.9
Total Sequences | 23870131
Total Bases | 3.4 Gbp
Sequences flagged as poor quality | 0
Sequence length | 15-151
%GC | 43

Note the different read count (23607378 vs 23870131). You need to ensure your "host genome removal" process is paired-end aware.

**Comment by yiasei** [comment]
Thanks for the clarification. Much appreciated.
