### ISSUE TITLE
sequence name is empty

### ISSUE THREAD

**Issue by mmani4** [ablab/spades#1349]
### Description of bug

I run spades for the assembly and tried quast. I am getting this error     

ERROR! Skipping assembly1/spades-original/corrected/B54_R100.0_0.cor.fastq.gz because >sequence_name field is empty for the entry starting with "@K00124:531:HC23JBBX". can you assist me to resolve this isssue

### spades.log

[spades (1).log](https://github.com/user-attachments/files/16531157/spades.1.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16531190/params.txt)

### SPAdes version

 SPAdes version: 4.0.0

### Operating System

Linux-4.18.0-477.21.1.el8_8.x86_64-x86_64-with-glibc2.28

### Python Version

3.12.4

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
There are no errors in the attached `spades.log` file. Will you please attach the proper log with error?

**Comment by mmani4** [comment]
Hi,
I finished running spades,  but when I tried to run quast, it shows like there is an error in the assembly file (I mean the spades output)

The error is     ERROR! Skipping assembly1/spades-original/corrected/B54_R_unpaired00.0_0.cor.fastq.gz because >sequence_name field is empty for the entry starting with ***@***.***:531:HC23JBBX".


Best,
Monika

**Comment by asl** [comment]
> The error is     ERROR! Skipping assembly1/spades-original/corrected/B54_R_unpaired00.0_0.cor.fastq.gz because >sequence_name field is empty for the entry starting with ***@***.***:531:HC23JBBX".

It seems you are running QUAST on reads, not assembler output.
