### ISSUE TITLE
SPAdes err code: -6

### ISSUE THREAD

**Issue by SongF123** [ablab/spades#135]
I'm trying to do a denovo assembly with pair end reads,but something wrong with it 
I received the following error and I don't know what mean of this error, and how can i resolve it.

Command line: /home/ubuntu/soft/SPAdes-3.12.0-Linux/bin/spades.py	-o	/home/ubuntu/output/output_dir	-1	/home/ubuntu/output/1956-AGCGAGAT_R1.fastq	-2	/home/ubuntu/output/1956-AGCGAGAT_R2.fastq	-t	8	-k	45,61,91	--careful	

System information:
  SPAdes version: 3.12.0
  Python version: 3.6.5
  OS: Linux-4.4.0-91-generic-x86_64-with-debian-stretch-sid

Output dir: /home/ubuntu/output/output_dir
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/ubuntu/output/1956-AGCGAGAT_R1.fastq']
      right reads: ['/home/ubuntu/output/1956-AGCGAGAT_R2.fastq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [45, 61, 91]
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/ubuntu/output/output_dir/tmp
  Threads: 8
  Memory limit (in Gb): 0

======= SPAdes pipeline started. Log can be found here: /home/ubuntu/output/output_dir/spades.log

===== Read error correction started. 

== Running read error correction tool: /home/ubuntu/soft/SPAdes-3.12.0-Linux/bin/spades-hammer /home/ubuntu/output/output_dir/corrected/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from /home/ubuntu/output/output_dir/corrected/configs/config.info
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 1
  0:00:00.000     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 0 Gb
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.001     4M / 4M    INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.001     4M / 4M    INFO    General                 (hammer_tools.cpp          :  36)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.001     4M / 4M    INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.001     4M / 4M    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 301)   Building kmer index
  0:00:00.001     4M / 4M    INFO    General                 (kmer_index_builder.hpp    : 117)   Splitting kmer instances into 16 files using 1 threads. This might take a while.
  0:00:00.001     4M / 4M    INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1024
  0:00:00.002     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 5.72662e+09 Gb
  0:00:00.002     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 4194304
<jemalloc>: Error in malloc(): out of memory. Requested: 36909872, active: 4194304

== Error ==  system call for: "['/home/ubuntu/soft/SPAdes-3.12.0-Linux/bin/spades-hammer', '/home/ubuntu/output/output_dir/corrected/configs/config.info']" finished abnormally, err code: -6

Thank you in advance!

**Comment by asl** [comment]
The log reads:

```Error in malloc(): out of memory. Requested: 36909872, active: 4194304```

So, you're running out of RAM.
