### ISSUE TITLE
spades 4.0.0 mmap(2) failed. Reason: Cannot allocate memory. Error code: 12

### ISSUE THREAD

**Issue by WangYF1989** [ablab/spades#1354]
### Description of bug

Hi

I am using the spades 4.0.0 on ubuntu 22.04, and set Memory limit set to 300 Gb, however, only about 20G RAM used, and rasie errors frequentlly.

I tried three times with different params, two of which with "--careful" terminated with error "mmap(2) failed. Reason: Cannot allocate memory. Error code: 12", the other one with "--isolate" run with error "mimalloc: warning: unable to allocate aligned OS memory directly, fall back to over-allocation", but didnot termianted.

### spades.log

[spades3.log](https://github.com/user-attachments/files/16594031/spades3.log)
[spades-test.log](https://github.com/user-attachments/files/16594032/spades-test.log)
[spades1.log](https://github.com/user-attachments/files/16594033/spades1.log)
[spades2.log](https://github.com/user-attachments/files/16594034/spades2.log)

### params.txt

[params2.txt](https://github.com/user-attachments/files/16594036/params2.txt)
[params3.txt](https://github.com/user-attachments/files/16594037/params3.txt)
[params-test.txt](https://github.com/user-attachments/files/16594038/params-test.txt)
[params1.txt](https://github.com/user-attachments/files/16594039/params1.txt)

### SPAdes version

sapdes v4.0.0

### Operating System

ubuntu 22.04

### Python Version

python 3.9.12

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [ ] Yes

**Comment by WangYF1989** [comment]
![微信截图_20240813114100](https://github.com/user-attachments/assets/f1771f47-3f46-409c-8eab-9d1e922d9a42)
![微信截图_20240813114217](https://github.com/user-attachments/assets/06b146a7-3ce2-41ab-a0e6-1a904e9781f1)

**Comment by asl** [comment]
Well, the error is:
```
mmap(2) failed. Reason: Cannot allocate memory. Error code: 12"
```

So, SPAdes was unable to allocate memory. In fact, it is your OS that did not fulfil SPAdes' request for memory allocation. SPAdes cannot workaround this error neither it could proceed.

**Comment by WangYF1989** [comment]
Could you give some suggestion on my OS settings, is this caused by small swap partion(2.1 Gb)? or mimalloc memory allocation?

**Comment by asl** [comment]
You can definitely try to increase SPAdes' memory limit:
```
  Memory limit (in Gb): 250
```

For everything else I would suggest you to talk to your system administrator as different systems might have different settings.

**Comment by WangYF1989** [comment]
Thank you, I will try some other methods
