### ISSUE TITLE
Files with merged reads were ignored

### ISSUE THREAD

**Issue by braddmg** [ablab/spades#1355]
### Description of bug

Hello, I hope you are well!
I was running an assembly with a merged file and I received the following message: "Files with merged reads were ignored." I'm not sure if it means the entire assembly or just some specific step like estimating read length.
I really appreciate your help

### spades.log

[spades.log](https://github.com/user-attachments/files/16605387/spades.log)

### params.txt

/opt/bioinf/SPAdes-3.15.4/bin/metaspades.py       --merged        /work/bmendoza/PlasMet/Filtered_Data/A1/A1.fq.gz        -o     /work/bmendoza/PlasMet/ASSEMBLY/A1       -k      33,55,77,99,127 --only-assembler        -t      32      -s      /work/bmendoza/PlasMet/Filtered_Data/A1/A1_unpaired.fq.gz

### SPAdes version

v3.15.4

### Operating System

Linux

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Please attach your spades.log file

**Comment by braddmg** [comment]
Thank you for your quick answer!
The assembly is currently running, I just want to check if I need to worry about the message.

[spades.log](https://github.com/user-attachments/files/16605317/spades.log)

**Comment by asl** [comment]
Well, per SPAdes manual (https://ablab.github.io/spades/input.html):

> If you have merged some of the reads from your paired-end (not mate-pair or high-quality mate-pair) library (using tools s.a. [BBMerge](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbmerge-guide/) or [STORM](https://bitbucket.org/yaoornl/align_test/overview)), you should provide the file with resulting reads as a "merged read file" for the corresponding library. Note that non-empty files with the remaining unmerged left/right reads (separate or interlaced) must be provided for the same library (for SPAdes to correctly detect the original read length).

This is certainly not your case.

**Comment by braddmg** [comment]
> Well, per SPAdes manual (https://ablab.github.io/spades/input.html):
> 
> 
> 
> > If you have merged some of the reads from your paired-end (not mate-pair or high-quality mate-pair) library (using tools s.a. [BBMerge](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbmerge-guide/) or [STORM](https://bitbucket.org/yaoornl/align_test/overview)), you should provide the file with resulting reads as a "merged read file" for the corresponding library. Note that non-empty files with the remaining unmerged left/right reads (separate or interlaced) must be provided for the same library (for SPAdes to correctly detect the original read length).
> 
> 
> 
> This is certainly not your case.

I am using a merged file obtained from FLASH and I used --merged for that file and -s for unpaired file (concatenated R1 and R2 files). 
I just want to be sure that spades is using merged file (A1.fq.gz) for assembly and if the message that merged file was ignored is for other reasons.

**Comment by braddmg** [comment]
#UPDATE

The run just stopped with error value 122.
[spades.log](https://github.com/user-attachments/files/16605888/spades.log)

**Comment by asl** [comment]
Well, the log reads:

```
  0:57:04.601     2M / 19G   ERROR  Temporary                (temporary.cpp             :  54)   Cannot create temporary file
```

I would suggest you to talk to your system administrator as this is an I/O issue on your end.
