### ISSUE TITLE
Error OS 21

### ISSUE THREAD

**Issue by azat1391** [ablab/spades#1359]
### Description of bug

== Error ==  system call for: "['/home/azat/spades4/bin/spades-hammer', '/home/azat/6768_test/corrected/configs/config.info']" finished abnormally, OS return value: 21

### spades.log

[spades.log](https://github.com/user-attachments/files/16691081/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16691088/params.txt)

### SPAdes version

 SPAdes version: 4.0.0

### Operating System

Linux-5.4.0-192-generic-x86_64-with-glibc2.31

### Python Version

3.10.10

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
Pair of read files "/home/azat/202408081821_AE01-231201001_4P240605075US2S3238DX_B_SSP080820241140_SSP_760_WGS_1_L01_R1.fq.gz" and "/home/azat/202408081821_AE01-231201001_4P240605075US2S3238DX_B_SSP080820241140_SSP_760_WGS_1_L01_R2.fq.gz" contain unequal amount of reads
```

So, you input reads are corrupted.
