### ISSUE TITLE
finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by Asraid** [ablab/spades#1365]
### Description of bug

Hi, I have not been able to run a pair-ends reads metagenome assembly. I changed the memory limit from 31 Gb to 64 but it didn't work. I changed the Python version from 3.11 to 3.8 and nothing. Thanks.

### spades.log

![spades.log.txt](https://github.com/user-attachments/files/16937474/spades.log.txt)

### params.txt

![params.txt](https://github.com/user-attachments/files/16937413/params.txt)

### SPAdes version

Spades 4.0.0

### Operating System

Ubuntu 22.04.4 LTS

### Python Version

Python 3.8.19

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [x] Yes!

**Comment by asl** [comment]
Please upload your spades.log file and params.txt

**Comment by Asraid** [comment]
Sorry. I just upload the files. Thanks.

**Comment by asl** [comment]
The log reads:
```
mimalloc: error: unable to allocate OS memory (43494932480 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:     323.887 s
   process: user: 3902.244 s, system: 69.634 s, faults: 40
       rss: current: 67264512, peak: 288595968
    commit: current: 67264512, peak: 434266112
```

So, you are running out of RAM. Given the size of your dataset I doubt you will be able to assemble it using 31 Gb of RAM. 64 Gb is unlikely to help (though it does not seem you're having that amount of RAM on that machine).
