### ISSUE TITLE
== Error ==  system call for: "['/home/sd02/rww/install/miniconda3/bin/spades-core', '/home/sd02/rww/rawdata/RX3/fastp/spades/K77/configs/config.info']" finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by ranweiwei66** [ablab/spades#1372]
### Description of bug

mimalloc: error: unable to allocate OS memory (67108864 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:   14705.760 s
   process: user: 297715.802 s, system: 2142.413 s, faults: 597084
       rss: current: 295097335808, peak: 257784049664
    commit: current: 295097335808, peak: 295097335808

== Error ==  system call for: "['/home/sd02/rww/install/miniconda3/bin/spades-core', '/home/sd02/rww/rawdata/RX3/fastp/spades/K77/configs/config.info']" finished abnormally, OS return value: -6
None

In case you have troubles running SPAdes, you can report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/sd02/rww/rawdata/RX3/fastp/spades/spades.log

Thank you for using SPAdes! If you use it in your research, please cite:

  Prjibelski, A., Antipov, D., Meleshko, D., Lapidus, A. and Korobeynikov, A., 2020. Using SPAdes de novo assembler. Current protocols in bioinformatics, 70(1), p.e102.
  doi.org/10.1002/cpbi.102
Thanks much for your help.

### spades.log

[spades.log](https://github.com/user-attachments/files/16989758/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/16989756/params.txt)

### SPAdes version

4.0.0

### Operating System

Linux-5.15.0-117-generic-x86_64-with-glibc2.35

### Python Version

3.12.2

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
mimalloc: error: unable to allocate OS memory (67108864 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)

```

So your OS failed to fulfil SPAdes' request for memory allocation.

**Comment by ranweiwei66** [comment]
Does this mean that my system does not have enough memory to meet SPAdes' request? If I try to create a 1TB swap space for the operating server system, could this resolve the issue? Thank you for your help.

**Comment by ranweiwei66** [comment]
> The log clearly reads:
> 
> ```
> mimalloc: error: unable to allocate OS memory (67108864 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
> ```
> 
> So your OS failed to fulfil SPAdes' request for memory allocation.

Does this mean that my system does not have enough memory to meet SPAdes' request? If I try to create a 1TB swap space for the operating server system, could this resolve the issue? Thank you for your help.

**Comment by asl** [comment]
> Does this mean that my system does not have enough memory to meet SPAdes' request?

Maybe. Or maybe it cannot fulfil it for some other reasons (memory fragmentation, etc.).
