### ISSUE TITLE
os return value 5

### ISSUE THREAD

**Issue by LaurenceHdL** [ablab/spades#1377]
### Description of bug

i have the error os return value 5 and I don't understand how to fix it:

== Error ==  system call for: "['/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/Compiler/gcccore/spades/3.15.4/bin/spades-core', '/lustre04/scratch/lauhotte/norvege/CGVMWSH240419/CGVMWSH240419-48DNA/190623_02_P04/Assembly_190623_02_P04_output/K55/configs/config.info', '/lustre04/scratch/lauhotte/norvege/CGVMWSH240419/CGVMWSH240419-48DNA/190623_02_P04/Assembly_190623_02_P04_output/K55/configs/mda_mode.info', '/lustre04/scratch/lauhotte/norvege/CGVMWSH240419/CGVMWSH240419-48DNA/190623_02_P04/Assembly_190623_02_P04_output/K55/configs/meta_mode.info']" finished abnormally, OS return value: 5
None

### spades.log

[spades.log](https://github.com/user-attachments/files/17017368/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/17017372/params.txt)

### SPAdes version

SPAdes v.3.15.4

### Operating System

Béluga-Compute Canada

### Method of SPAdes installation

don't know

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
  3:23:41.953    17M / 2931M ERROR   General                 (kmer_index_builder.hpp    : 346)   I/O error! Incomplete write! Reason: Input/output error. Error code: 5
```

So, this is an I/O error on your system. I would suggest you to contact your system administrator
