### ISSUE TITLE
Error code 255. spades-hammer finished abnormally

### ISSUE THREAD

**Issue by Jessiyang** [ablab/spades#138]
Dear all, 
what does the following error mean? 

 "['/home/disk1/assemble/SPAdes-3.12.0/bin/spades-hammer', '/home/disk1/assemble/peeltre/corrected/configs/config.info']" finished abnormally, err code: 255

Could anyone who has come across this issue work it out?

Thanks!

**Comment by asl** [comment]
Please attach the files mentioned just two lines below the ones you copied.

**Comment by Jessiyang** [comment]
Dear asl,

Here is the file of config.info
Thanks!
[config.info.txt](https://github.com/ablab/spades/files/2175236/config.info.txt)

**Comment by asl** [comment]
Well... the ones that were mentioned in the message are "params.txt" and "spades.log"....

**Comment by Jessiyang** [comment]
Umm ..sorry for the misunderstanding. Here are the params.txt and spades.log
[params.txt](https://github.com/ablab/spades/files/2175254/params.txt)
[spades.log](https://github.com/ablab/spades/files/2175255/spades.log)

**Comment by asl** [comment]
So, the log reads:

  1:44:05.574     3G / 9G    ERROR  K-mer Counting           (kmer_data.cpp             : 353)   The reads contain too many k-mers to fit into available memory. You need approx. 279.37GB of free RAM to assemble your dataset
