### ISSUE TITLE
python3: relocation error

### ISSUE THREAD

**Issue by zivlang** [ablab/spades#1382]
### Description of bug

Hello.
I'm using the following command after installing glibc 2.33 in a conda environment:
`SPAdes-4.0.0-Linux/bin/spades.py --debug -o Ilumina_sequences/B199_S2_L001_R1_001.fastq -2 Ilumina_sequences/B199_S2_L001_R2_001.fastq --nanopore B199_long_reads.fasta --threads 64 --isolate`
Then the following error message is printed:

> python3: relocation error: python3: symbol pthread_sigmask, version GLIBC_2.2.5 not defined in file libpthread.so.0 with link time reference

### spades.log

No files were created.

### params.txt

No files were created.

### SPAdes version

SPAdes-4.0.0

### Operating System

Linux gandalf2 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Python Version

Python 3.8.20

### Method of SPAdes installation

Manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The error reads:

```
python3: relocation error: python3: symbol pthread_sigmask, version GLIBC_2.2.5 not defined in file libpthread.so.0 with link time reference
```

So, it is not a SPAdes problem at all. I would suggest you either to ask conda or your system administrator

**Comment by WangHaoZhe** [comment]
Hello. Have you solved this problem? I'm encountering the same issue.
