### ISSUE TITLE
The software did not run successfully

### ISSUE THREAD

**Issue by Ding327782** [ablab/spades#1390]
### Description of bug

The software did not run successfully

### spades.log

[spades.log](https://github.com/user-attachments/files/17294039/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/17294031/params.txt)

### SPAdes version

SPAdes 4.0

### Operating System

Centos 7

### Python Version

Python 3.12.4

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
The log reads:

```
/home/zhaoding/SPAdes-4.0.0-Linux/bin/spades-hammer: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/zhaoding/SPAdes-4.0.0-Linux/bin/spades-hammer)
/home/zhaoding/SPAdes-4.0.0-Linux/bin/spades-hammer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/zhaoding/SPAdes-4.0.0-Linux/bin/spades-hammer)
/home/zhaoding/SPAdes-4.0.0-Linux/bin/spades-hammer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/zhaoding/SPAdes-4.0.0-Linux/bin/spades-hammer)
```

So your system is too old to run SPAdes binaries. Consider compiling from sources or asking your system administrator.
