### ISSUE TITLE
finished abnormally, OS return value: -6 None

### ISSUE THREAD

**Issue by ZainBioBytes** [ablab/spades#1394]
### Description of bug

I am running many samples all together for the assembly, almost all others are finished with spades assembly process. However, few samples are giving some error:

== Error ==  system call for: "['/shared/homes/25180175/mambaforge/envs/metaenv/bin/spades-core', '/K101/configs/config.info', '/K101/configs/mda_mode.info', '/K101/configs/meta_mode.info']" finished abnormally, OS return value: -6
None

### spades.log

[log and params.zip](https://github.com/user-attachments/files/17357343/log.and.params.zip)

### params.txt

[log and params.zip](https://github.com/user-attachments/files/17357344/log.and.params.zip)

### SPAdes version

4.0.0

### Operating System

Windows 11 (VS code)

### Python Version

3.11.9

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
mimalloc: error: unable to allocate OS memory (17184063488 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:   18993.877 s
   process: user: 443327.951 s, system: 1509.456 s, faults: 498002
       rss: current: 183624851456, peak: 204591001600
    commit: current: 183624851456, peak: 216846753792
```

So you are running out of RAM

**Comment by ZainBioBytes** [comment]
Thank you! A quick question: I’m currently allocating "-m 235" to SPAdes and 240 to the PBS script. Should I increase both, or would it be better to keep "-m 235" for SPAdes and only increase the PBS memory allocation?

**Comment by asl** [comment]
Per SPAdes manual (https://ablab.github.io/spades/running.html#advanced-options):

> -m <int> (or --memory <int>) Set memory limit in Gb. SPAdes terminates if it reaches this limit.
