### ISSUE TITLE
Mismatch between Paths in GFA/.paths and scaffolds.fasta

### ISSUE THREAD

**Issue by schorlton-bugseq** [ablab/spades#1395]
### Description of bug

Not totally certain what's going on but I'm guessing this may have occurred because mismatch corrector changed the length of a scaffold, but the scaffold name was retained in the GFA?

Settings and log attached.

When I run `grep -R NODE_49_ spades_out/ ` on my output dir, I see                                                                                                            
```
spades_out/misc/assembled_contigs.fasta:>NODE_49_length_14984_cov_3.880727
spades_out/misc/assembled_contigs.fasta.ann:0 NODE_49_length_14984_cov_3.880727 (null)
spades_out/misc/assembled_scaffolds.fasta:>NODE_49_length_14984_cov_3.880727
spades_out/misc/assembled_scaffolds.fasta.ann:0 NODE_49_length_14984_cov_3.880727 (null)
spades_out/misc/broken_scaffolds.fasta:>NODE_49_length_14983_cov_3.880727_1 
spades_out/K77/before_rr.fasta:>NODE_49_length_329_cov_1.154762
spades_out/K77/assembly_graph_with_scaffolds.gfa:P       NODE_49_length_14984_cov_3.880727       4571+,48175+,3583-,122931+,18593+,128499+       *
spades_out/K77/final_contigs.fasta:>NODE_49_length_14984_cov_3.880727
spades_out/K77/final_contigs.paths:NODE_49_length_14984_cov_3.880727
spades_out/K77/final_contigs.paths:NODE_49_length_14984_cov_3.880727'
spades_out/K77/scaffolds.fasta:>NODE_49_length_14984_cov_3.880727
spades_out/K77/scaffolds.paths:NODE_49_length_14984_cov_3.880727
spades_out/K77/scaffolds.paths:NODE_49_length_14984_cov_3.880727'
spades_out/mismatch_corrector/contigs/corrected_contigs.fasta:>NODE_49_length_14983_cov_3.880727
spades_out/mismatch_corrector/scaffolds/corrected_contigs.fasta:>NODE_49_length_14983_cov_3.880727
spades_out/before_rr.fasta:>NODE_49_length_329_cov_1.154762
spades_out/scaffolds.paths:NODE_49_length_14984_cov_3.880727
spades_out/scaffolds.paths:NODE_49_length_14984_cov_3.880727'
spades_out/assembly_graph_with_scaffolds.gfa:P   NODE_49_length_14984_cov_3.880727       4571+,48175+,3583-,122931+,18593+,128499+       *
spades_out/contigs.paths:NODE_49_length_14984_cov_3.880727
spades_out/contigs.paths:NODE_49_length_14984_cov_3.880727'
spades_out/contigs.fasta:>NODE_49_length_14983_cov_3.880727
spades_out/scaffolds.fasta:>NODE_49_length_14983_cov_3.880727
```

You can see that the scaffold is 14983 bp in the scaffolds.fasta but 14984 bp in the scaffolds.paths and GFA?

Let me know if you need a reproducible example or more information. Thanks for your help!!

### spades.log

[spades.log](https://github.com/user-attachments/files/17357918/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/17357913/params.txt)

### SPAdes version

4.0.0

### Operating System

Linux

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Yes, mismatch corrector may change the length (and contents) of FASTA files. No changes to assembly graph are expected though as it represents the result of assembly itself, not further preprocessing.

**Comment by schorlton-bugseq** [comment]
Thanks for the quick response - is it safe to cross-reference node names (ie before `_length_...` in scaffold names) between graph and scaffolds FASTA?

**Comment by asl** [comment]
> Thanks for the quick response - is it safe to cross-reference node names (ie before `_length_...` in scaffold names) between graph and scaffolds FASTA?

Yes. Or, better yet, just do not run mismatch corrector :) It may not be the best default solution
