### ISSUE TITLE
Issues with pathracer after 4.0 update

### ISSUE THREAD

**Issue by myco-bradshaw** [ablab/spades#1401]
### Description of bug

Hello,

Since the update to Spades 4.0, it seems that Pathracer no longer functions the way it did in the 3.16dev version. Since updating to the newest version, whenever I run patherracer in the same way as the previous version I get numerous errors with parsing as well as a fatal error . 

error: while parsing GFA path record
     |
   1 | P\tNODE_734_length_3605_cov_30.846463\t1201783+;1176853-\t*
     |                                                ^ expected '\t'

Command:
pathracer ~/HMM/path/file.hmm \
*assembly_graph_with_scaffolds.gfa -t 12 --parallel-components --memory 64 --output ./pathracer_genes/gene

Fatal error:
Fatal exception (source file /__w/spades/spades/ext/src/hmmer/src/p7_pipeline.c, line 714):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)

### spades.log

n/a

### params.txt

n/a

### SPAdes version

4.0

### Operating System

Linux

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
@myco-bradshaw Will you please attach the example graph?

**Comment by myco-bradshaw** [comment]
[assembly_graph_with_scaffolds.zip](https://github.com/user-attachments/files/17542061/assembly_graph_with_scaffolds.zip)

Attached, I also noticed that patracher no longer seems to work with assemblies generated from older (3.15) spades builds.

**Comment by asl** [comment]
The fix should be available as a part of continuous build : https://github.com/ablab/spades/releases/tag/continuous
