### ISSUE TITLE
output

### ISSUE THREAD

**Issue by wanboqi** [ablab/spades#1408]
### Description of bug

I used spade for hybrid assembly of the second and third generations. The resulting file contains scaffold.fa and contig.fa. May I ask which file should I use as contig?

### spades.log

no

### params.txt

no

### SPAdes version

3.15.2

### Operating System

linux

### Python Version

3.10

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Please refer to SPAdes manual for information about SPAdes output: https://ablab.github.io/spades/output.html

**Comment by wanboqi** [comment]
@asl Yes I looked at the help document, but <output_dir>/scaffolds.fasta says here that it recommends this file as a result sequence, so I'm not sure which file I should use as contig after assembly

**Comment by asl** [comment]
> @asl Yes I looked at the help document, but <output_dir>/scaffolds.fasta says here that it recommends this file as a result sequence, so I'm not sure which file I should use as contig after assembly

Let us read manual together:

> <output_dir>/scaffolds.fasta contains resulting scaffolds
> <output_dir>/contigs.fasta contains resulting contigs
