### ISSUE TITLE
== Error ==  system call 

### ISSUE THREAD

**Issue by chonchayachi** [ablab/spades#1416]
### Is your feature request related to a problem? Please describe. For generic questions use Q&A section in the Discussions forum above.

== Error ==  system call for: "['/home/chonchayachi/Desktop/SPAdes/bin/spades-hammer', '/media/chonchayachi/Sandisk/dicty/ACR019_folder/corrected/configs/config.info']" finished abnormally, OS return value: 12
None

What should I do with this problem ??

**Comment by chonchayachi** [comment]
[spades.log](https://github.com/user-attachments/files/17971907/spades.log)
[params.txt](https://github.com/user-attachments/files/17971908/params.txt)

**Comment by asl** [comment]
Hello

Does the problem reproduce with the latest SPAdes 4.0?

**Comment by chonchayachi** [comment]
Yes

**Comment by asl** [comment]
> Yes

Will you please provide `spades.log` and `params.txt` files from SPAdes 4 run?

**Comment by chonchayachi** [comment]
[spades.log](https://github.com/user-attachments/files/17972333/spades.log)
[params.txt](https://github.com/user-attachments/files/17972334/params.txt)

Here are the files

**Comment by asl** [comment]
> [spades.log](https://github.com/user-attachments/files/17972333/spades.log) [params.txt](https://github.com/user-attachments/files/17972334/params.txt)
> 
> Here are the files

You are using SPAdes 3.15.5:
```
System information:
  SPAdes version: 3.15.5
```

Please give the latest SPAdes 4.0 a try and if the problem is there, attach correct logs.

**Comment by chonchayachi** [comment]
Sorry, Here are the latest version
[params.txt](https://github.com/user-attachments/files/17972424/params.txt)
[spades.log](https://github.com/user-attachments/files/17972426/spades.log)

**Comment by asl** [comment]
The log reads:

```
  0:03:24.113  2411M / 3004M ERROR   General                 (kmer_splitter.hpp         : 151)   I/O error! Incomplete write! Reason: No space left on device. Error code: 28
```
