### ISSUE TITLE
spades-hammer not reading 

### ISSUE THREAD

**Issue by poojancf** [ablab/spades#1417]
### Description of bug

I want to run spades.py for pair-end files and get the assembly. I installed spades from conda.
The error I get at the spades-hammer. 
When I run command 'spades-hammer' the following error pops up. 
There is no config.inp file in my system. The path to config.inp is not in my system. 

Loading config from "/home/snikolenko/algorithmic-biology/assembler/src/hammer/config.inp"
Exception caught /home/snikolenko/algorithmic-biology/assembler/src/hammer/config.inp: cannot open file for reading

### spades.log

Command line: /pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades.py        -1      /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R1.trimmed.fastq.gz -2      /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R2.trimmed.fastq.gz -o      /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades

System information:
  SPAdes version: 4.0.0
  Python version: 3.13.0
  OS: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28

Output dir: /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R1.trimmed.fastq.gz']
      right reads: ['/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R2.trimmed.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
  Assembly graph output will use GFA v1.2 format
Other parameters:
  Dir for temp files: /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades/tmp
  Threads: 16
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades/spades.log

/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R1.trimmed.fastq.gz: max reads length: 151
/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R2.trimmed.fastq.gz: max reads length: 151

Reads length: 151

Default k-mer sizes were set to [21, 33, 55, 77] because estimated read length (151) is equal to or greater than 150

===== Before start started.

===== Read error correction started.

===== Read error correction started.

== Running: /pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades/corrected/configs/config.info

  0:00:00.000     1M / 24M   INFO    General                 (main.cpp                  :  76)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.000     1M / 24M   INFO    General                 (main.cpp                  :  77)   Loading config from "/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades/corrected/configs/config.info"
  0:00:00.001     1M / 24M   INFO    General                 (main.cpp                  :  79)   Maximum # of threads to use (adjusted due to OMP capabilities): 10
  0:00:00.001     1M / 24M   INFO    General                 (memory_limit.cpp          :  55)   Memory limit set to 250 Gb
  0:00:00.001     1M / 24M   INFO    General                 (main.cpp                  :  87)   Trying to determine PHRED offset
  0:00:00.002     1M / 24M   INFO    General                 (main.cpp                  :  93)   Determined value is 33
  0:00:00.002     1M / 24M   INFO    General                 (hammer_tools.cpp          :  40)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.002     1M / 24M   INFO    General                 (main.cpp                  : 114)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.002     1M / 24M   INFO    General                 (kmer_index_builder.hpp    : 258)   Splitting kmer instances into 16 files using 10 threads. This might take a while.
  0:00:00.002     1M / 24M   INFO    General                 (file_limit.hpp            :  43)   Open file limit set to 16384
  0:00:00.002     1M / 24M   INFO    General                 (kmer_splitter.hpp         :  94)   Memory available for splitting buffers: 8.33333 Gb
  0:00:00.002     1M / 24M   INFO    General                 (kmer_splitter.hpp         : 102)   Using cell size of 4194304
  0:00:00.043  5761M / 5761M INFO   K-mer Splitting          (kmer_data.cpp             :  98)   Processing "/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R1.trimmed.fastq.gz"
  0:00:09.947  5761M / 7058M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 2145422 reads
  0:00:19.742  5761M / 7098M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 4294086 reads
  0:00:29.704  5761M / 7182M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 6469538 reads
  0:00:39.809  5761M / 7182M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 8628021 reads
  0:00:49.165  5761M / 7182M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 10767988 reads
  0:00:59.449  5761M / 7234M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 12965510 reads
  0:01:09.773  5761M / 7266M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 15171177 reads
  0:01:19.834  5761M / 7266M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 17326447 reads
  0:01:29.916  5761M / 7266M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 19483216 reads
  0:01:40.007  5761M / 7266M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 21637641 reads
  0:02:40.543  5761M / 7266M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 34631018 reads
  0:05:21.944  5761M / 7304M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 69217889 reads
  0:10:27.704  5761M / 7304M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 134385039 reads
  0:20:53.033  5761M / 7309M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 268483274 reads
  0:34:19.664  5761M / 7357M INFO   K-mer Splitting          (kmer_data.cpp             :  98)   Processing "/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R2.trimmed.fastq.gz"
  0:41:40.216  5761M / 7387M INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 537509960 reads
  1:07:56.752  5761M / 7417M INFO   K-mer Splitting          (kmer_data.cpp             : 113)   Total 882725520 reads processed
  1:07:56.767     1M / 7417M INFO    General                 (kmer_index_builder.hpp    : 264)   Starting k-mer counting.
  1:07:56.826     1M / 7417M ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12  1:07:56.826     1M / 7417M ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
  1:07:56.826     1M / 7417M ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
  1:07:56.826     1M / 7417M ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
  1:07:56.826     1M / 7417M ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
=== Stack Trace ===  1:07:56.826     1M / 7417M ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
=== Stack Trace ===
=== Stack Trace ===  1:07:56.826     1M / 7417M ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12=== Stack Trace ===
=== Stack Trace ====== Stack Trace ===
=== Stack Trace ===
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x1c5b7) [0x556efdc065b7]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x32f61) [0x556efdc1cf61]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x47804) [0x556efdc31804]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x1c5b7) [0x556efdc065b7]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x32f61) [0x556efdc1cf61]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x47804) [0x556efdc31804]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x62334) [0x556efdc4c334]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x63de3) [0x556efdc4dde3]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/../lib/libgomp.so.1(+0x18f09) [0x14b1d3205f09]/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x62334) [0x556efdc4c334]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x63de3) [0x556efdc4dde3]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/../lib/libgomp.so.1(+0x18f09) [0x14b1d3205f09]
/lib64/libpthread.so.0(+0x81ca) [0x14b1d2de81ca]
/lib64/libc.so.6(clone+0x43) [0x14b1d22e8e73]
/lib64/libpthread.so.0(+0x81ca) [0x14b1d2de81ca]
/lib64/libc.so.6(clone+0x43) [0x14b1d22e8e73]
The program was terminated by segmentation fault
=== Stack Trace ===/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x1c5b7) [0x556efdc065b7]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x32f61) [0x556efdc1cf61]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x47804) [0x556efdc31804]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x62334) [0x556efdc4c334]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x63de3) [0x556efdc4dde3]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/../lib/libgomp.so.1(+0x18f09) [0x14b1d3205f09]
/lib64/libpthread.so.0(+0x81ca) [0x14b1d2de81ca]
/lib64/libc.so.6(clone+0x43) [0x14b1d22e8e73]
The program was terminated by segmentation fault
=== Stack Trace ===
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x1c5b7) [0x556efdc065b7]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x32f61) [0x556efdc1cf61]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x47804) [0x556efdc31804]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x62334) [0x556efdc4c334]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x63de3) [0x556efdc4dde3]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/../lib/libgomp.so.1(+0x18f09) [0x14b1d3205f09]
/lib64/libpthread.so.0(+0x81ca) [0x14b1d2de81ca]
/lib64/libc.so.6(clone+0x43) [0x14b1d22e8e73]
The program was terminated by segmentation fault
=== Stack Trace ===
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x1c5b7) [0x556efdc065b7]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x1cd66) [0x556efdc06d66]
/lib64/libc.so.6(+0x4eb50) [0x14b1d22fdb50]
/lib64/libc.so.6(+0x51237) [0x14b1d2300237]
/lib64/libc.so.6(on_exit+0) [0x14b1d23003a0]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x32f78) [0x556efdc1cf78]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x47804) [0x556efdc31804]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x62334) [0x556efdc4c334]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer(+0x63de3) [0x556efdc4dde3]
/pfs/home/pragya/tools/anaconda3/envs/spades/bin/../lib/libgomp.so.1(+0x18f09) [0x14b1d3205f09]
/lib64/libpthread.so.0(+0x81ca) [0x14b1d2de81ca]
/lib64/libc.so.6(clone+0x43) [0x14b1d22e8e73]

== Error ==  system call for: "['/pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades-hammer', '/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades/corrected/configs/config.info']" finished abnormally, OS return value: -11

In case you have troubles running SPAdes, you can report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades/spades.log

Thank you for using SPAdes! If you use it in your research, please cite:

  Prjibelski, A., Antipov, D., Meleshko, D., Lapidus, A. and Korobeynikov, A., 2020. Using SPAdes de novo assembler. Current protocols in bioinformatics, 70(1), p.e102.
  doi.org/10.1002/cpbi.102

### params.txt

Command line: /pfs/home/pragya/tools/anaconda3/envs/spades/bin/spades.py        -1      /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R1.trimmed.fastq.gz -2      /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R2.trimmed.fastq.gz -o      /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades

System information:
  SPAdes version: 4.0.0
  Python version: 3.13.0
  OS: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28

Output dir: /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R1.trimmed.fastq.gz']
      right reads: ['/pfs/home/pragya/pooja/hornbill/mal_pied/analysis/fastp/MPH_Bakal/MPH_Bakal_R2.trimmed.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
  Assembly graph output will use GFA v1.2 format
Other parameters:
  Dir for temp files: /pfs/home/pragya/pooja/hornbill/mal_pied/analysis/spades/tmp
  Threads: 16
  Memory limit (in Gb): 250

### SPAdes version

 4.0.0

### Operating System

 Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28

### Python Version

3.13.0

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:
```
07:56.826 1M / 7417M ERROR General (mmapped_reader.hpp : 52) mmap(2) failed. Reason: Cannot allocate memory. Error code: 12 1:07:56.826 1M / 7417M ERROR General (mmapped_reader.hpp : 52) mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
```

So you are running out of RAM
