### ISSUE TITLE
error in  metaplasmidspades --assembly-graph 

### ISSUE THREAD

**Issue by ucaswhw** [ablab/spades#1427]
### Description of bug

Regarding the –assembly-graph parameter:
I have encountered an issue when running metaplasmidspades.py with the --assembly-graph parameter. The error message displayed is:
== Error ==  To run read error correction, reads should be in FASTQ format.
I have tried various combinations but have not found the correct input format. Additionally, I couldn’t find relevant examples in the user manual.
Could you please clarify how to properly use the --assembly-graph parameter?

### spades.log

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py -1 ../cleandata/P_Cu_2/P_Cu_2_R1.fq.gz -2 ../cleandata/P_Cu_2/P_Cu_2_R2.fq.gz --assembly-graph P_Cu_2/assembly_graph_with_scaffolds.gfa -k 21,33,55 -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph_with_scaffolds.gfa (single reads, library number: 1, library type: assembly-graph)

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py --assembly-graph P_Cu_2/assembly_graph_with_scaffolds.gfa -k 21,33,55 -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph_with_scaffolds.gfa (single reads, library number: 1, library type: assembly-graph)

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py --assembly-graph P_Cu_2/assembly_graph_with_scaffolds.gfa -k 21,33,55 -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph_with_scaffolds.gfa (single reads, library number: 1, library type: assembly-graph)

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py -1 ../cleandata/P_Cu_2/P_Cu_2_R1.fq.gz -2 ../cleandata/P_Cu_2/P_Cu_2_R2.fq.gz --assembly-graph P_Cu_2/assembly_graph.fastg -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  file with reads has unsupported format (only .fq, .fastq, .bam, .fq.gz, .fastq.gz, .fa, .fasta, .fa.gz, .fasta.gz, .gfa, .sra are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph.fastg (single reads, library number: 1, library type: assembly-graph)

### params.txt

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py -1 ../cleandata/P_Cu_2/P_Cu_2_R1.fq.gz -2 ../cleandata/P_Cu_2/P_Cu_2_R2.fq.gz --assembly-graph P_Cu_2/assembly_graph_with_scaffolds.gfa -k 21,33,55 -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph_with_scaffolds.gfa (single reads, library number: 1, library type: assembly-graph)

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py --assembly-graph P_Cu_2/assembly_graph_with_scaffolds.gfa -k 21,33,55 -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph_with_scaffolds.gfa (single reads, library number: 1, library type: assembly-graph)

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py --assembly-graph P_Cu_2/assembly_graph_with_scaffolds.gfa -k 21,33,55 -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph_with_scaffolds.gfa (single reads, library number: 1, library type: assembly-graph)

python ../SPAdes-4.0.0-Linux/bin/metaplasmidspades.py -1 ../cleandata/P_Cu_2/P_Cu_2_R1.fq.gz -2 ../cleandata/P_Cu_2/P_Cu_2_R2.fq.gz --assembly-graph P_Cu_2/assembly_graph.fastg -o P_Cu_2_plasmid_test -t 24 -m 1000

== Error ==  file with reads has unsupported format (only .fq, .fastq, .bam, .fq.gz, .fastq.gz, .fa, .fasta, .fa.gz, .fasta.gz, .gfa, .sra are supported): /mnt/sdb/yemao/wuhaowei/spades/P_Cu_2/assembly_graph.fastg (single reads, library number: 1, library type: assembly-graph)

### SPAdes version

SPAdes4.0.0

### Operating System

Linux version 5.15.0-72-generic

### Python Version

python 3.8

### Method of SPAdes installation

Linux binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
So, the documentation says:
>--assembly-graph <file_name> File with assembly graph. Could only be used in plasmid, metaplasmid, metaviral and biosynthetic mode. The primary purpose of this option is to run these pipelines on already constructed and simplified assembly graphs, thus skipping a large part of SPAdes pipeline. Original reads the graph was constructed from need to be specified as well. Exact k-mer length (via -k option) should be provided. Note that the output would be different as compared to standalone runs of these pipelines as they set up graph simplification options as well.

So, you need:
 - Specify original reads
 - Specify original single k-mer length
 - Skip read error correction
 - Graph should be in GFA format

In short: this is quite advanced option used in "manual` mode.

**Comment by ucaswhw** [comment]
Thank you, it is due to  the --only-assembler option was not added
