### ISSUE TITLE
The error encountered when running metaplasmidspades.py 

### ISSUE THREAD

**Issue by ucaswhw** [ablab/spades#1429]
### Description of bug

Here is my command:  metaplasmidspades.py --only-assembler -1 ../cleandata/P_Cu_2/P_Cu_2_R1.fq.gz -2 ../cleandata/P_Cu_2/P_Cu_2_R2.fq.gz --assembly-graph P_Cu_2/assembly_graph_with_scaffolds.gfa -k 55 -o P_Cu_2_plasmid_test -t 24 -m 1000
I used the assembly_graph_with_scaffolds.gfa output from MetaSPAdes without any modifications. Additionally, I tested both the precompiled and locally compiled versions of SPAdes 4.0.0, but the error still persists.

error1:
error: while parsing GFA path record
     |
   1 | P\tNODE_21572222_length_146_cov_7.527473\t512564113+;80180755+\t*
     |                                                     ^ expected '\t'
     
error2:
Verification of expression 'false' failed in function 'size_t debruijn_graph::DeBruijnGraph::link_length(debruijn_graph::DeBruijnGraph::VertexId, debruijn_graph::DeBruijnGraph::EdgeId, debruijn_graph::DeBruijnGraph::EdgeId) const'. In file '/mnt/sdb/yemao/wuhaowei/SPAdes-4.0.0/src/common/assembly_graph/core/graph.hpp' on line 141. Message 'Link 11459731 -> 7758781 was not found for vertex 15517558'.
Verification of expression 'false' failed in function 'size_t debruijn_graph::DeBruijnGraph::link_length(debruijn_graph::DeBruijnGraph::VertexId, debruijn_graph::DeBruijnGraph::EdgeId, debruijn_graph::DeBruijnGraph::EdgeId) const'. In file '/mnt/sdb/yemao/wuhaowei/SPAdes-4.0.0/src/common/assembly_graph/core/graph.hpp' on line 141. Message 'Link 11459731 -> 7758781 was not found for vertex 15517558'.
spades-core: /mnt/sdb/yemao/wuhaowei/SPAdes-4.0.0/src/common/assembly_graph/core/graph.hpp:141: size_t debruijn_graph::DeBruijnGraph::link_length(debruijn_graph::DeBruijnGraph::VertexId, debruijn_graph::DeBruijnGraph::EdgeId, debruijn_graph::DeBruijnGraph::EdgeId) const: Assertion `false' failed.

== Error ==  system call for: "['/mnt/sdb/yemao/wuhaowei/SPAdes-4.0.0/bin/spades-core', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/config.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/mda_mode.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/meta_mode.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/plasmid_mode.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/metaplasmid_mode.info']" finished abnormally, OS return value: -6

### spades.log

[spades.log](https://github.com/user-attachments/files/18224810/spades.log)

### params.txt

[params.txt](https://github.com/user-attachments/files/18224828/params.txt)

### SPAdes version

SPAdes 4.0.0

### Operating System

Linux version 5.15.0-72-generic

### Python Version

Python 3.8

### Method of SPAdes installation

manual compiled

### No errors reported in spades.log

- [X] Yes

**Comment by ucaswhw** [comment]
I used the version from https://github.com/ablab/spades/releases/tag/continuous, but the error still occurs.


/mnt/sdb/yemao/wuhaowei/spades-continuous/bin/spades-core(+0x7904e) [0x5561eeb5704e]
Verification of expression 'false' failed in function 'size_t debruijn_graph::DeBruijnGraph::link_length(debruijn_graph::DeBruijnGraph::VertexId, debruijn_graph::DeBruijnGraph::EdgeId, debruijn_graph::DeBruijnGraph::EdgeId) const'. In file '/mnt/sdb/yemao/wuhaowei/spades-continuous/src/common/assembly_graph/core/graph.hpp' on line 141. Message 'Link 10035250 -> 508102 was not found for vertex 1016200'.
Verification of expression 'false' failed in function 'size_t debruijn_graph::DeBruijnGraph::link_length(debruijn_graph::DeBruijnGraph::VertexId, debruijn_graph::DeBruijnGraph::EdgeId, debruijn_graph::DeBruijnGraph::EdgeId) const'. In file '/mnt/sdb/yemao/wuhaowei/spades-continuous/src/common/assembly_graph/core/graph.hpp' on line 141. Message 'Link 10035250 -> 508102 was not found for vertex 1016200'.
spades-core: /mnt/sdb/yemao/wuhaowei/spades-continuous/src/common/assembly_graph/core/graph.hpp:141: size_t debruijn_graph::DeBruijnGraph::link_length(debruijn_graph::DeBruijnGraph::VertexId, debruijn_graph::DeBruijnGraph::EdgeId, debruijn_graph::DeBruijnGraph::EdgeId) const: Assertion `false' failed.


== Error ==  system call for: "['/mnt/sdb/yemao/wuhaowei/spades-continuous/bin/spades-core', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/config.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/mda_mode.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/meta_mode.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/plasmid_mode.info', '/mnt/sdb/yemao/wuhaowei/spades/P_Cu_2_plasmid_test/K55/configs/metaplasmid_mode.info']" finished abnormally, OS return value: -6
None
[params.txt](https://github.com/user-attachments/files/18229433/params.txt)
[spades.log](https://github.com/user-attachments/files/18229435/spades.log)

**Comment by ucaswhw** [comment]
Is it caused by SPAdes exceeds the filesystem limit on open files?

**Comment by asl** [comment]
> Is it caused by SPAdes exceeds the filesystem limit on open files?

No. Will you please attach the graph so we can reproduce the issue?

**Comment by ucaswhw** [comment]
I'm very happy to provide you with the graph file. However, I need to download it from the server first and then upload it to GitHub, which may take some time. I will upload it as soon as possible. Is there anything else you need besides the graph file?

**Comment by asl** [comment]
Should be enough for now. I'll let you know if this will be required

**Comment by ucaswhw** [comment]
Since I have reached the Git LFS file transfer limit, I have uploaded my graph files to Google Drive. Here is the link to the files. If this method is not suitable for you, please let me know, and I will find an alternative way to upload them to GitHub. Thank you!

https://drive.google.com/file/d/1AIOVEpeJcK241ftbzpegYFeovGt4Gw7_/view?usp=share_link

**Comment by ucaswhw** [comment]
Hi, I seem to be encountering the same issue while testing MetaViralSPAdes. I was running it on a different dataset, and it appears to be stuck at the same poin
[spades.log](https://github.com/user-attachments/files/18243598/spades.log)
t. 
[params.txt](https://github.com/user-attachments/files/18243599/params.txt)

**Comment by asl** [comment]
@ucaswhw The second dataset is much smaller and it would be easier for us to reproduce. Will you please upload the graph and input files?
