### ISSUE TITLE
run spades.py and raised err code -6

### ISSUE THREAD

**Issue by JaneDY** [ablab/spades#143]
When I run spades.py to assembly genome data, and it raised such error: 
=== ERRORs:
 * system call for: "['/mnt/ilustre/users/yun.ding/newmdt/bin/spades/SPAdes-3.12.0-Linux/bin/spades-core', '/mnt/ilustre/users/yun.ding/newmdt/scripts/binning_test/zhangyuyu_MJ20171017049/data/spades_assem/sgassem/co.binning.214/D8_2/spades_output2/K55/configs/config.info']" finished abnormally, err code: -6

What's the problem and how can I to solve it?
Does anybody can help me?

**Comment by asl** [comment]
Sure. Please attache spades.log and params,txt files as you were suggested in the error message

**Comment by JaneDY** [comment]
[params.txt](https://github.com/ablab/spades/files/2183628/params.txt)
[spades.log](https://github.com/ablab/spades/files/2183629/spades.log)

**Comment by asl** [comment]
So, the log reads

```
Verification of expression 'cov_.size() > 10' failed in function 'void coverage_model::KMerCoverageModel::Fit()'. In file '/spades/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```

And indeed, it does not seem you're assembling some genome or part of it as you were told SPAdes via using multicell mode – you're only having 2.5k reads.

**Comment by JaneDY** [comment]
You mean, my data is too small, and the coverage is not enough, so spades couldn't assembly these reads

**Comment by asl** [comment]
No. Per error message – the coverage of your data is highly non-uniform. Still you're trying to assemble it in multi-cell mode that is intended for normal isolate assembly.

**Comment by JaneDY** [comment]
Sorry, I'm totally newer in genome assembly and know little about it. 
Actually my data is metagenomic data, and I have done binning. Now I try to use the reads which are mapped on one bin contigs to assemble genome. 
Can you give some advice on it , how to set spades params?
Thank you!
