### ISSUE TITLE
getting error while running

### ISSUE THREAD

**Issue by Ravindra-Raut** [ablab/spades#1430]
### Description of bug

== Error ==  system call for: "['/mnt/e/ravi/U_Ostrava/Test/SPAdes-4.0.0-Linux/bin/spades-hammer', '/mnt/e/ravi/U_Ostrava/Test/output_spades/corrected/configs/config.info']" finished abnormally, OS return value: 21
None

### spades.log

[spades.log](https://github.com/user-attachments/files/18246235/spades.log)

### params.txt

Command line: SPAdes-4.0.0-Linux/bin/spades.py	-1	/mnt/e/ravi/U_Ostrava/Test/trimmed_DNA_R1.part_002.fastq.gz	-2	/mnt/e/ravi/U_Ostrava/Test/trimmed_DNA_R2.part_002.fastq.gz	-o	/mnt/e/ravi/U_Ostrava/Test/output_spades	--threads	2	--tmp-dir	/mnt/e/tmp	
[params.txt](https://github.com/user-attachments/files/18246231/params.txt)

### SPAdes version

SPAdes version: 4.0.0

### Operating System

OS: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.29

### Python Version

Python version: 3.8.10

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by Ravindra-Raut** [comment]
any solution

**Comment by Chen-afk620** [comment]
[params.txt](https://github.com/user-attachments/files/21955696/params.txt)
[spades.log](https://github.com/user-attachments/files/21955695/spades.log)
