### ISSUE TITLE
rnaSPAdes 3.12 "finished abnormally" err code: -6

### ISSUE THREAD

**Issue by nologo68** [ablab/spades#145]
Hi all,

I've been trying many times to assemble paired end reads from a metatranscriptome using rnaSPAdes. Since it kept giving me the famous "err code: -6", I just tried with the v 3.12, but again gave the same error.
This is the .bat file I used:

#PBS -N rnaspades_upwelling2

#PBS -l walltime=26:00:00

#PBS -l nodes=1:ppn=48

#PBS -j oe

#PBS -m abe

#PBS -A PAA0034

set -x

cd $PBS_O_WORKDIR

module use /fs/project/PAS1117/modulefiles
module load spades/3.12.0

/usr/bin/time -v python /fs/project/PAS1117/modules/spades/3.12.0/bin/rnaspades.py -k 55 -1 /fs/project/PAS1117/Tara_Euk/upwelling-v2/ERR1719296_1.fastq.gz -2 /fs/project/PAS1117/Tara_Euk/upwelling-v2/ERR1719296_2.fastq.gz -o rnaspades2_out 

echo $PBS_JOBID
echo $PBS-JOBNAME

**Here are some files that could be useful to check what happened**
[spades.log](https://github.com/ablab/spades/files/2187095/spades.log)
[params.txt](https://github.com/ablab/spades/files/2187096/params.txt)

Thanks!

**Comment by asl** [comment]
The log reads

```
 6:30:58.385   232G / 232G  INFO    General                 (launcher.cpp              : 467)   Finalizing paths - hard
<jemalloc>: Error in malloc(): out of memory. Requested: 512, active: 259073769472
```

So, you're out of RAM.

**Comment by nologo68** [comment]
So what should I do then?

**Comment by tolot27** [comment]
Quite simple: upgrade your RAM or start spades on a machine with much more RAM (maybe by setting a PBS variable appropriately)

**Comment by nologo68** [comment]
How does it look now?

#PBS -N rnaspades_upwelling2
#PBS -l walltime=**168**:00:00
#PBS -l nodes=1:ppn=48
#PBS -j oe
#PBS -m abe
#PBS -A PAA0034
set -x

cd $PBS_O_WORKDIR

module use /fs/project/PAS1117/modulefiles
module load spades/3.12.0

cd /fs/project/PAS1117/GuiDH/Amanda_B/RNASPADES
/usr/bin/time -v python /fs/project/PAS1117/modules/spades/3.12.0/bin/rnaspades.py **-m 1450 -t 48** -k 55 -1 /fs/project/PAS1117/Tara_Euk/upwelling-v2/ERR1719296_1.fastq.gz -2 /fs/project/PAS1117/Tara_Euk/upwelling-v2/ERR1719296_2.fastq.gz -o rnaspades2_out 

echo $PBS_JOBID
echo $PBS-JOBNAME
