### ISSUE TITLE
SPAdes pipeline finished abnormally and WITH WARNINGS!

### ISSUE THREAD

**Issue by jtahir** [ablab/spades#146]
Hi 
I am getting following errors whilE running Spades. Please can you advise. Thanks Jibran
== Error ==  system call for: "['/software/bioinformatics/SPAdes-3.11.1/bin/spades', '/powerplant/workspace/hrpjxt/Spades/spades_output/K77/configs/config.info']" finished abnormally, err code: -6

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
* 12:57:34.276   130G / 130G  WARN    General                 (pair_info_count.cpp       : 200)   Too much reads aligned with negative insert size. Is the library orientation set properly?
* 35:55:18.336    77G / 149G  WARN   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  59)   Less than half of genome in unique edges!
======= Warnings saved to /powerplant/workspace/hrpjxt/Spades/spades_output/warnings.log

=== ERRORs:
* system call for: "['/software/bioinformatics/SPAdes-3.11.1/bin/spades', '/powerplant/workspace/hrpjxt/Spades/spades_output/K77/configs/config.info']" finished abnormally, err code: -6

**Comment by asl** [comment]
Please attach your spades.log and params.txt file as you were instructed just two lines below the ones you posted

**Comment by jtahir** [comment]
Please can you give me email so I can share you on that. The data info can't go public

**Comment by jtahir** [comment]
I have attached them. Please advise, thanks
[params.txt](https://github.com/ablab/spades/files/2194868/params.txt)
[spades.log](https://github.com/ablab/spades/files/2194869/spades.log)

**Comment by asl** [comment]
The support email is in the error message as well

**Comment by asl** [comment]
This is the known problem of SPAdes 3.11.1 that was fixed in SPAdes 3.12

**Comment by jtahir** [comment]
i have attached the files now
