### ISSUE TITLE
Error Code 255

### ISSUE THREAD

**Issue by cssulliv** [ablab/spades#150]
Hi,

I am trying to assemble contigs from metagnome sequences and when I run this script 

spades.py -1 sample1_QUALITY_PASSED_R1.fastq -2 sample1_QUALITY_PASSED_R2.fastq --meta --threads 4 --memory 10 -o 1362A_spades_defaultassembly 

I get the following error message: 
== Error ==  system call for: "['/anaconda3/share/spades-3.12.0-1/bin/spades-hammer', '/Volumes/MyPassport/Bioinformatics/Anvio_2018/Metagenomics_tutorial/PRACTICE2/01_RAWDATA/1362A_spades_defaultassembly/corrected/configs/config.info']" finished abnormally, err code: 255

I previously would get err code: 9 so I changed the memory setting but I cannot seem to figure out what err code 225 means. 

Attached are my spades.log and params.txt

[params.txt](https://github.com/ablab/spades/files/2225753/params.txt)
[spades.log](https://github.com/ablab/spades/files/2225754/spades.log)

**Comment by asl** [comment]
The log reads

```
 27:48:58.324   428M / 7G    ERROR  K-mer Counting           (kmer_data.cpp             : 353)   The reads contain too many k-mers to fit into available memory. You need approx. 27.5253GB of free RAM to assemble your dataset
```

So you're running out of RAM

**Comment by shakti83kumar** [comment]
I am Shakti Kumar and facing same problem. I request you to check the following files

[params.txt](https://github.com/ablab/spades/files/4963867/params.txt)
[spades.log](https://github.com/ablab/spades/files/4963868/spades.log)

**Comment by asl** [comment]
@shakti83kumar Please do not hijack old closed issues. In your case the problem is clearly written in the log:
```
  0:00:00.074    68M / 76M   ERROR   General                 (paired_readers.hpp        :  58)   The number of left read-pairs is larger than the number of right read-pairs
  0:00:00.074    68M / 76M   ERROR   General                 (paired_readers.hpp        :  60)   Unequal number of read-pairs detected in the following files: /home/drbhabatoshdas/DrBabhtoshSirProjects/PTM_TM_analysis/L.iners_raw_files_Run4_fastp/Lactobacillus_S1_L001_unicycler/spades_assembly/corrected_1.fastq.gz  /home/drbhabatoshdas/DrBabhtoshSirProjects/PTM_TM_analysis/L.iners_raw_files_Run4_fastp/Lactobacillus_S1_L001_unicycler/spades_assembly/corrected_2.fastq.gz
```
