### ISSUE TITLE
hqmp assemblies never finish in 3.12

### ISSUE THREAD

**Issue by osvatic** [ablab/spades#151]
I have been trying to run 2 hqmp assemblies in 3.12 and both stall (not exit or error) after the final kmer.

Is there a way around this? or is it a major bug?

Thank you!

**Comment by asl** [comment]
@andrewprzh will probably the best person to help with it

**Comment by andrewprzh** [comment]
Sorry for a delay -- replied by email.

**Comment by waterfleas** [comment]
I have the same problem in both 3.12 and 3.13 assemblies, but no with hqmp.  No error and no exit.

**Comment by andrewprzh** [comment]
Please re-open if the problem is not resolved in the latest release.
