### ISSUE TITLE
Error code -6 and no reads aligned properly

### ISSUE THREAD

**Issue by blondie5125** [ablab/spades#153]
Hi,

I am working with collapsed/merged reads from a paired-end library on a high performance computer at my university. 
My code: 
metaspades.py -t 27 --pe1-12 /path/to/project -o /path/to/METASPADESout/project

I have attached the spades.log. I was wondering what the error could be relating to? Any help would be much appreciated.

Thank you,

Sarah
[params.txt](https://github.com/ablab/spades/files/2258723/params.txt)

[spades.log](https://github.com/ablab/spades/files/2258642/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Well, the log reads:

```
  0:00:09.152   108M / 14G   INFO    General                 (kmer_splitters.hpp        : 310)   Used 9410 reads. Maximum read length 275
  0:00:09.152   108M / 14G   INFO    General                 (kmer_splitters.hpp        : 311)   Average read length 41.5775
```

It does not seems to be a metagenomic dataset and at k = 55 the output is simply empty.
