### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by laurafisch9** [ablab/spades#155]
I installed spades from bianary using 

```
curl http://cab.spbu.ru/files/release3.12.0/SPAdes-3.12.0-Darwin.tar.gz -o SPAdes-3.12.0-Darwin.tar.gz
    tar -zxf SPAdes-3.12.0-Darwin.tar.gz
    cd SPAdes-3.12.0-Darwin/bin/
```

But every time I try to run the test command for spades I get the following erorr

```
spades SPAdes-3.12.0-Darwin --test
-bash: spades: command not found
```

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Please refer to SPAdes manual (http://cab.spbu.ru/files/release3.12.0/manual.html#sec3) for SPAdes cmdline and options. As for generic Linux / MacOS cmdline usage you could ask your system administrator for an appropriate resource.

**Comment by tolot27** [comment]
Try `./spades` or `./spades.py`
