### ISSUE TITLE
how to specify merged reads in yaml?

### ISSUE THREAD

**Issue by notestaff** [ablab/spades#157]
The manual says merged pe reads can be specified with a command-line option.  Can they be specified in yaml?
Also, same question for unpaired reads from a paired-end library.

**Comment by andrewprzh** [comment]
Dear Ilya

Thank you for pointing that out -- we did not specify all possible data types for YAML files, will fix the manual.

So, the unpaired reads can be specified as "single reads" and merge as "merged reads". E.g. a YAML file for a library containg paired-end, unpaired and merged reads would look like this:

`    [
      {
        orientation: "fr",
        type: "paired-end",
        right reads: [
          "/FULL_PATH_TO_DATASET/lib_pe1_right_1.fastq"
        ],
        left reads: [
          "/FULL_PATH_TO_DATASET/lib_pe1_left_1.fastq"
        ],
        single reads: [
          "/FULL_PATH_TO_DATASET/lib_pe1_unpaired1.fastq",
          "/FULL_PATH_TO_DATASET/lib_pe1_unpaired2.fastq"
        ],
        merged reads: [
          "/FULL_PATH_TO_DATASET/lib_pe1_merged.fastq"
        ]

      }
    ]`

**Comment by asl** [comment]
Fixed in 3.13.0
