### ISSUE TITLE
SPAdes pipeline finished abnormally and WITH WARNINGS!

### ISSUE THREAD

**Issue by laurafisch9** [ablab/spades#158]
I am running SPAdes on a data set of long reads generated by oxford nanopore (10,000 bp or longer) for one bacterial genome. This data set has about 500 reads with an average quality of 9

here is the command I used 
```
~/assemblers/SPAdes-3.12.0-Linux/bin/spades.py -o spades_assembled -s ~/FN58_diamond_blast_runs/planktomarina/long_reads/plankto_reads.fastq ```

Here is the error code 

```
finished abnormally, err code: -6
```

here are the files from the run
[params.txt](https://github.com/ablab/spades/files/2274832/params.txt)
[spades.log](https://github.com/ablab/spades/files/2274833/spades.log)

**Comment by asl** [comment]
The log reads:

```
Verification of expression 'cov_.size() > 10' failed in function 'void coverage_model::KMerCoverageModel::Fit()'. In file '/spades/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```

And indeed, per SPAdes manual (http://cab.spbu.ru/files/release3.12.0/manual.html#sec3.1):

To run SPAdes 3.12.0 you need at least one library of the following types:

  * Illumina paired-end/high-quality mate-pairs/unpaired reads
  * IonTorrent paired-end/high-quality mate-pairs/unpaired reads
  * PacBio CCS reads

Illumina and IonTorrent libraries should not be assembled together. All other types of input data are compatible. SPAdes should not be used if only PacBio CLR, Oxford Nanopore, Sanger reads or additional contigs are available.

**Comment by laurafisch9** [comment]
I see. Thanks for clarifying! I cannot use spades on my data then since I only have oxford nanopore reads
