### ISSUE TITLE
Error: Multiple mate-pair libraries not being recognized

### ISSUE THREAD

**Issue by santiagosnchez** [ablab/spades#161]
Hello,

After running this command:

    spades.py --mp1-1 SRX3008884.PX534.4-7kb.mp.1.fq --mp1-2 SRX3008884.PX534.4-7kb.mp.2.fq --mp2-1 SRX3008886.PX534.9-12kb.mp.1.fq --mp2-2 SRX3008886.PX534.9-12kb.mp.2.fq -o test

I'm getting this error:

```
== Error ==  you should specify at least one unpaired, paired-end, or high-quality mate-pairs library!


In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.
```

I'm guessing `Spades` is not recognizing the `--mp<#>-#` arguments?

Running version: `SPAdes v3.12.0`

Thanks,

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

SPAdes clearly is recognizing the arguments hence the error.

From the SPAdes manual (http://cab.spbu.ru/files/release3.12.0/manual.html#sec3.1):

```
To run SPAdes 3.12.0 you need at least one library of the following types:

  Illumina paired-end/high-quality mate-pairs/unpaired reads
  IonTorrent paired-end/high-quality mate-pairs/unpaired reads
  PacBio CCS reads
```
