### ISSUE TITLE
multithreading issue: OMP capabilities?

### ISSUE THREAD

**Issue by willnotburn** [ablab/spades#163]
I work on a university cluster using nodes with 256Gb RAM and 28 threads. The SPAdes 3.12.0 command line is:

./bin/spades.py -t 28 -m 250 --meta -k 21,33,55,77,99,127 --12 228_all_pTrim.interleaved.fastq --12 218_all_pTrim.interleaved.fastq -s 228_all_uTrim.unpaired.fastq -s 218_all_uTrim.unpaired.fastq -o group_1_spades

**Good news:**
Other parameters:
  Dir for temp files: /mnt/ls15/scratch/users/wilburn4/2_results/shotgun/5.assembly/co-assembly-sourmash/group_1_spades/tmp
  Threads: 28
  Memory limit (in Gb): 250

**Bad news:**
0:00:00.005     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 1

**ISSUE:**
Do I wind up using only 1 (one) thread? Why? I do not know what OMP capabilities are.

**Comment by asl** [comment]
Paul,

You may want to check what are the OpenMP defaults are on your cluster. Sometimes you need to set a special environmental variable to override this default. Usually it's OMP_NUM_THREADS or something similar.

**Comment by willnotburn** [comment]
Your advice just 28X my productivity

export OMP_NUM_THREADS=28

Thanks!

**Comment by Benjamin-Lee** [comment]
For anyone coming here in the future, Snakemake seems to be doing something weird with the environment. @willnotburn's advice works perfectly.
