### ISSUE TITLE
Reads assembled

### ISSUE THREAD

**Issue by eleniadam** [ablab/spades#165]
Hello,

I started using SPAdes assembler and I would like to ask if I can find in the output folder the specific reads that contributed (are part of) the final assembly. I have not been able to locate a file specifying which of the input reads were finally used in the assembly.

Also, in the contigs.fasta and the scaffolds.fasta files, are the contigs ordered? 

Regarding the contigs.fasta, I believe I saw (in Quast) some overlaps and I am not certain what this means exactly.

Thank you,
Eleni

**Comment by asl** [comment]
> I started using SPAdes assembler and I would like to ask if I can find in the output folder the specific reads that contributed (are part of) the final assembly. I have not been able to locate a file specifying which of the input reads were finally used in the assembly.

There is no way to extract this information. You could align the reads back to the contigs.

> Also, in the contigs.fasta and the scaffolds.fasta files, are the contigs ordered?

Yes. Check http://cab.spbu.ru/files/release3.12.0/manual.html#sec3.5 for SPAdes output
