### ISSUE TITLE
K21,K33,K55 contigs not reported in final contigs.fasta (K77 did'nt have any)

### ISSUE THREAD

**Issue by cromozome** [ablab/spades#166]
I am seeing beautiful contigs with nice coverage in the K21, K33 and K55 runs, but K77 does not produce any contigs and surprisingly the final contigs.fasta file is empty.
Any insight into why this is so ?
I am using SPAdes-3.12.0
I have attached the spades.log and warnings.log

[spades.log](https://github.com/ablab/spades/files/2315945/spades.log)
[warnings.log](https://github.com/ablab/spades/files/2315948/warnings.log)

**Comment by asl** [comment]
As far as I can see, you're using coverage cutoff of 500. And at k=77 it simply removed everything hence the result is empty.

**Comment by cromozome** [comment]
Hi Anton
So if the K77 is empty, shouldn't the final contigs.fasta carry the contigs from the lower K (21,33, or 55) iterations ? Those contigs have great coverage and are what I want

**Comment by asl** [comment]
No, they should not, because they were used as a part of K77 assembly and were filtered out by your coverage cutoff.
