### ISSUE TITLE
How to get chromosome and plasmid assemblies from same run? 

### ISSUE THREAD

**Issue by AstrobioMike** [ablab/spades#168]
Hi there,

I don't think this is necessarily an issue, but maybe more that I'm just missing something. 

I'm running spades on isolate bacterial genomes (PE illumina only) and would like to generate a "full" assembly (chromosomal and all) and also use _plasmidspades_ to mark likely plasmid contigs. It seems the only way to do this is to run two assemblies separately and sort of merge the information afterwards – meaning doing a "normal" spades run without `--plasmid` turned on, then another with `--plasmid` turned on, and then find the contigs in the "full" assembly that were identified by plasmidspades based on their length and coverage. 

Impressively, many these seem to come out exactly the same length and coverage-wise, so no problem, but not for all, e.g.:

```
grep ">" ../s1_S1_plasmidspades_assembly/scaffolds.fasta | cut -f4-6 -d "_"
123679_cov_349.723
34799_cov_1217.17
7880_cov_967.559
7425_cov_1021.96
5389_cov_1291.3
3330_cov_942.903
2486_cov_1.63927
1993_cov_1.68476
695_cov_154.359
458_cov_131.693
361_cov_3930.68
347_cov_209.57
344_cov_92.0787
341_cov_412.167
335_cov_202.55
323_cov_134.394
191_cov_89.4386
121_cov_175.273

grep ">" ../s1_S1_plasmidspades_assembly/scaffolds.fasta | cut -f4-6 -d "_" > plasmid_contigs

for i in $(cat plasmid_contigs); do echo "$i"; grep "$i" scaffolds.fasta; done
123679_cov_349.723
>NODE_7_length_123679_cov_349.723
34799_cov_1217.17
>NODE_15_length_34799_cov_1217.17
7880_cov_967.559
>NODE_19_length_7880_cov_967.559
7425_cov_1021.96
>NODE_20_length_7425_cov_1021.96
5389_cov_1291.3
>NODE_21_length_5389_cov_1291.3
3330_cov_942.903
>NODE_23_length_3330_cov_942.903
2486_cov_1.63927
>NODE_26_length_2486_cov_1.63927
1993_cov_1.68476
>NODE_27_length_1993_cov_1.68476
695_cov_154.359
458_cov_131.693
361_cov_3930.68
>NODE_208_length_361_cov_3930.68
347_cov_209.57
344_cov_92.0787
341_cov_412.167
335_cov_202.55
323_cov_134.394
191_cov_89.4386
>NODE_735_length_191_cov_89.4386
121_cov_175.273
>NODE_745_length_121_cov_175.273
``` 

I tried a couple things with `--restart`, but didn't have any luck. Am I missing a cleaner way to combine the information from plasmidspades with a run that outputs the full assembly? 

Thanks!
-mike

**Comment by asl** [comment]
Hello Mike,

Thank you for your interest in SPAdes and plasmidSPAdes.

No, there is no way to "combine" the information because plasmidSPAdes does not "mark likely plasmid contigs". And this is exactly the reason why you're seeing different results.

See plasmidSPAdes paper https://www.ncbi.nlm.nih.gov/pubmed/27466620 for more information on how plasmidSPAdes extracts the putative plasmid graph components.

**Comment by AstrobioMike** [comment]
Hi Anton, 

Thanks for the response. Sorry if the colloquial expression I used seemed to diminish the approach, but i did look at the paper and documentation before posting here, and phrasing from the paper such as: 

_“In order to distinguish plasmids and chromosomes by coverage, PLASMIDSPADES first estimates the chromosome coverage.”_

and

_“PLASMIDSPADES uses coverage to remove chromosomal contigs from the assembly while retaining the plasmid contigs.”_

are actually why I worded it that way. If it is trying to remove chromosomal contigs and retain plasmid contigs, then "mark likely plasmid contigs" doesn't seem like all that much of a stretch in interpretation to me. 

Digressions over my careless terminology aside, the only reason i thought it was possible to combine this information was because of this line in the paper: 

_“We show that PLASMIDSPADES has the potential to massively increase the throughput of plasmid sequencing and to provide information about plasmids in thousands of sequenced bacterial genomes **by re-assembling their genomes, identifying their plasmids and supplementing the corresponding GenBank entries with the plasmid annotations**.”_

If you are not concurrently updating the genome assembly record that is the source of the newly identified plasmids, how do you know you are not ascribing stretches of DNA that are already in the genome assembly to a new plasmid (and therefore introducing artifactual duplications)?

**Comment by asl** [comment]
> PLASMIDSPADES uses coverage to remove chromosomal contigs from the assembly while retaining the plasmid contigs.

This part of the Discussion section is actually an over-simplified presentation of what is going on in reality. Such wording was used just for the sake of simplicity. The actual description of what plasmidSPAdes is doing could be found in the Section 2.2 of the paper. Note that plasmidSPAdes does not work on the output of SPAdes, but performs necessary steps in the middle of the whole assembly pipeline. Therefore it is not 100% true that the output of plasmidSPAdes is always a part of SPAdes output.

> If you are not concurrently updating the genome assembly record that is the source of the newly identified plasmids, how do you know you are not ascribing stretches of DNA that are already in the genome assembly to a new plasmid (and therefore introducing artifactual duplications)?

In general we don't know (and we're not updating any assembly records – note the "has the potential" wording). plasmidSPAdes outputs putative plasmid components of an (transformed & cleaned) assembly graph. It's up to the user to perform further analysis and decide whether these are true plasmids or some other artifacts.

**Comment by AstrobioMike** [comment]
Stellar, thank you. Happy to do so :) 

If there were a more robust/reproducible way already in place, I would have wanted to make sure I was doing that or showing why I was doing things my own way instead is all. 

Thanks!

**Comment by tolot27** [comment]
Just use blastn or even better `bwa mem -x intractg` to align the two scaffolds.fasta files against each other.

**Comment by zhaoxvwahaha** [comment]
@tolot27 Thank you for prompt reply, so we can't judge the plasmid contig only based on their sequence ID(name) in two scaffolds.fasta files, I should based on the sequence similarity (maybe, two sequence is almost same, but the sequence ID is different between two scaffold files ?) ?

**Comment by asl** [comment]
@zhaoxvwahaha This is correct. Note that the output of plasmidSPAdes may contain putative plasmid contigs that are absent in SPAdes contigs / scaffolds file due to removal of chromosomal edges in the de Bruijn graph.

**Comment by zhaoxvwahaha** [comment]
Thank you, so there is no function can output contigs both of plasmid and chromosome by one run now? Only run these two processes and then match them by other align software?

**Comment by asl** [comment]
Correct. So far there is no such possibility due to way how plasmidSPAdes works.
