### ISSUE TITLE
Crashes in spades-ionhammer from assertion

### ISSUE THREAD

**Issue by nivekkagicom** [ablab/spades#169]
I am seeing an assertion in spades-ionhammer that is crashing the program:
```
3   libsystem_c.dylib                   0x00007fffd8022893 __assert_rtn + 320
4   spades-ionhammer                    0x0000000109624113 hammer::correction::HRunSizeSearcher::HRunSizeSearcher(hammer::HSeq<16ul> const&, hammer::HomopolymerRun, std::function<bool (hammer::HSeq<16ul> const&)>&) + 179
```
I have attached the macOS crash reports if that provides additional details.

[spades-ionhammer_2018-08-27-145439_Herbert.crash.txt](https://github.com/ablab/spades/files/2325755/spades-ionhammer_2018-08-27-145439_Herbert.crash.txt)
[spades-ionhammer_2018-08-27-170318_Herbert.crash.txt](https://github.com/ablab/spades/files/2325756/spades-ionhammer_2018-08-27-170318_Herbert.crash.txt)
[spades-ionhammer_2018-08-27-150500_Herbert.crash.txt](https://github.com/ablab/spades/files/2325757/spades-ionhammer_2018-08-27-150500_Herbert.crash.txt)

**Comment by asl** [comment]
Please attach spades.log and params.txt files as you were instructed in the error message.

**Comment by nivekkagicom** [comment]
Sorry, SPAdes is embedded in another application and I do not directly see the errors. However, I have found and attached the requested files.

[params.txt](https://github.com/ablab/spades/files/2329062/params.txt)
[spades.log](https://github.com/ablab/spades/files/2329063/spades.log)
[spades-ionhammer_2018-08-28-124501_Herbert.crash.txt](https://github.com/ablab/spades/files/2329064/spades-ionhammer_2018-08-28-124501_Herbert.crash.txt)

**Comment by nivekkagicom** [comment]
FWIW SPAdes 3.11.0 does not crash using the same files. Is there any additional information that is needed to correct this issue in 3.12.0?

**Comment by asl** [comment]
There were no changes in IonHammer between 3.11 and 3.12 release.

I'm seeing that you're probably mixing both IonTorrent and Illumina data in the same run. Is this so?

**Comment by asl** [comment]
Please reopen if this still an issue
