### ISSUE TITLE
Building Spades 3.12.0 With GCC 7.1.0 and CMAKE 3.8.0 Fails With Internal Compiler Errors

### ISSUE THREAD

**Issue by drwhitehouse** [ablab/spades#171]
I'm getting internal compiler errors with both GCC 7.1.0 and GCC 6.3.0 (both with cmake 3.8.0) trying to build either Spades 3.11.0 or 3.12.0.

Things seem to start go wrong when it comes to the bamtools portion of the build. Any assistance would be appreciated.

**Comment by asl** [comment]
Well... please report gcc bug then with ICE. You could use our pre-built binaries, they are statically linked so should work.

**Comment by drwhitehouse** [comment]
Can you let me know what compiler you used to build those?

**Comment by asl** [comment]
We tend to use the minimum supported version for our release procedure to ensure we do not use the features that are not supported. So it is gcc 5.3.

Though, I could confirm that SPAdes builds fine for these gcc versions:

```
gcc-7 (Debian 7.3.0-22) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and

```
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
