### ISSUE TITLE
Error code: -10

### ISSUE THREAD

**Issue by wyon1** [ablab/spades#174]
I'm getting this error of which I cannot find mention of online. I have tried continuing multiple times but it seems to quit at the same place every time.

spades.py --only-assembler --12 reads_1.fastq --12 reads_2.fastq -o spades/

== Error ==  system call for: "['/Users/wesley/miniconda3/share/spades-3.12.0-1/bin/spades-core', '/Users/wesley/qbb2018-answers/week2/spades/K55/configs/config.info']" finished abnormally, err code: -10

[params.txt](https://github.com/ablab/spades/files/2386322/params.txt)
[spades.log](https://github.com/ablab/spades/files/2386323/spades.log)

**Comment by tolot27** [comment]
It looks like your input files are separated forward (`reads_1.fastq`) and reverse (`reads_2.fastq`) reads. The parameter `--12` expects interleaced reads (forward and reverse reads in one file). Try restarting it with: `spades.py --only-assembler -1 reads_1.fastq -2 reads_2.fastq -o spades/`.

**Comment by wyon1** [comment]
That worked.

Silly mistake on my part. Thank you!
