### ISSUE TITLE
Attempt at running spades err code: -6

### ISSUE THREAD

**Issue by GeorgiM26** [ablab/spades#175]
[params.txt](https://github.com/ablab/spades/files/2396244/params.txt)
[spades.log](https://github.com/ablab/spades/files/2396245/spades.log)

Hello,

So I am basically new at this.  I tried running spades but it is giving an error after 30 minutes of run time.  Apparently I am running out of memory, however I did specify the amount of allotted memory for the process ( 3 Gb max available). I tried rerunning multiple times and still stuck with the same error.

I just want to make sure if its purely a memory issue.

Thank you,
Georgi.

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes

The log clearly reads:

```
<jemalloc>: Error in malloc(): out of memory. Requested: 151, active: 3120562176
```

So, yes, you're running out of RAM. As far as I can see, you'd need slightly more than 3 Gb to continue.
