### ISSUE TITLE
Sensitivity for paired read metadata

### ISSUE THREAD

**Issue by jdarias93** [ablab/spades#177]
[spades.log](https://github.com/ablab/spades/files/2412493/spades.log)
[params.txt](https://github.com/ablab/spades/files/2412495/params.txt)

Hi SPAdes team,

Please see my attached logs and parameters. Basically, my question is: do the paired read metadata need to be **exactly** the same for both sets of reads?

In other words, for this error:
```
[mem_sam_pe] paired reads have different names: "NB501124:192:HH7HMBGX5:1:11101:10002:4936_1:N:0:GCCAAT", "NB501124:192:HH7HMBGX5:1:11101:10002:4936_2:N:0:GCCAAT"
```
Should I change the "2" in the second read to a "1"?

Thank you in advance.

**Comment by asl** [comment]
Well, the names of paired-end reads should match. In your case they do not and this is what bwa complains about. It seems that your reads were somehow preprocessed and this process screwed the read names (typically "1:N:0:GCCAAT" is a comment, not the part of the read name).
