### ISSUE TITLE
Failed in function 'void MMappedWriter::reserve(size_t)' & err code: -6

### ISSUE THREAD

**Issue by phhsieh1329** [ablab/spades#180]
Hi,

I have tried using SPAdes-3.12.0 (3.11.1 as well) to assemble Illumina reads and PacBio CCS reads, but got the errors as the attached files. I'm not so sure if it is due to memory issues as other posts, but tweeking with a few memory values didn't help. Thanks in advance for the help. The error message as follows:
[spades.log](https://github.com/ablab/spades/files/2422929/spades.log)
[params.txt](https://github.com/ablab/spades/files/2422930/params.txt)

=== Stack Trace ===
[0x40a709]
[0x40bdbf]
[0x40dfcc]
[0x403d47]
[0x5b4a5b]
[0x408f21]
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Function not implemented. Error code: 38'.
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Function not implemented. Error code: 38'.
spades-hammer: /spades/src/common/io/kmers/mmapped_writer.hpp:94: void MMappedWriter::reserve(size_t): Assertion `(intptr_t) MappedRegion != -1L' failed.

== Error ==  system call for: "['/spades/SPAdes-3.12.0-Linux/bin/spades-hammer', '/global/projectb/scratch/phhsieh/assembly/spades_test/corrected/configs/config.info']" finished abnormally, err code: -6

**Comment by asl** [comment]
Hello

Please attach the spades.log file from the failed run.

**Comment by phhsieh1329** [comment]
Hi asi,

I have moved the log file to the front and updated it. Thanks!

**Comment by asl** [comment]
So, the reason is that the file system you're using for the scratch storage (/global/projectb/scratch/) has broken implementation of memory mapped files.
