### ISSUE TITLE
spades hammer crashed due to out of memory (general_hard_memory_limit inconsistent in config files)

### ISSUE THREAD

**Issue by versaille** [ablab/spades#181]
VM specifics: 512 GB memory, 512 GB disk, 8cores
The 1st time I ran this command: 
`spades.py  -o $OUT_DIR/$name --only-error-correction -s $i -m 500`
and from the log file the error is:
```
0:31:26.739     4G / 8G    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 336)   Index built. Total 4927479962 bytes occupied (3.70969 bits per kmer).
  0:31:26.739     4G / 8G    INFO   K-mer Counting           (kmer_data.cpp             : 356)   Arranging kmers in hash map order
  0:46:49.244   163G / 163G  INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  9:55:58.032   163G / 163G  INFO    General                 (main.cpp                  : 155)   Extracting clusters
<jemalloc>: Error in malloc(): out of memory. Requested: 85009550896, active: 484026875904


== Error ==  system call for: "['/usr/local/bin/spades-hammer', '/var/opt/app/res/exome/anno_0043B1_I102_LG01/corrected/configs/config.info']" finished abnormally, err code: -6
```
I looked into the config file */corrected/configs/config.info:
```
; == HAMMER GENERAL ==
; general options
general_do_everything_after_first_iteration     1
general_hard_memory_limit 500
general_max_nthreads 16
general_tau                     1
general_max_iterations 1
general_debug                   0
```
It looks like there is enough memory. 

To debug this, I ran the same command with debug mode:

`2nd time:spades.py  -o $OUT_DIR/$name --only-error-correction --debug -s $i -m 500`

and with the debug mode, there are two config files:
1) */corrected/configs/config.info
2)*/configs/hammer/config.info

I checked both of them, and the parameter general_hard_memory limit in the two config files are inconsistent with each other. 
Here is what's in 1) */corrected/configs/config.info:
```
; == HAMMER GENERAL ==
; general options
general_do_everything_after_first_iteration     1
general_hard_memory_limit 500
general_max_nthreads 16
general_tau                     1
general_max_iterations 1
general_debug                   0
```
And here is what's in 2) */configs/hammer/config.info:
```
; == HAMMER GENERAL ==
; general options
general_do_everything_after_first_iteration     1
general_hard_memory_limit       150
general_max_nthreads            16
general_tau                     1
general_max_iterations          1
general_debug                   0

```
Could the author please do me a favor to answer two questions:
1. why the two config files have different general_hard_memory_limit ?
2. which config file does the program actually uses ?
3. how to make the */configs/hammer/config.info uses 500GB instead of 150GB ?

 I think what the general_hard_memory_limit the program actually uses is what's in */configs/hammer/config.info that is 150GB instead of 500GB, which is the reason why the program crashed with memory issue error even when there is enough memory available.

**Comment by asl** [comment]
Here is what happened: at the time of crash BayesHammer already used 450 Gb of RAM. And your OS failed to fulfill its request to allocate 80 Gb more (quite expected – you're only having 512 total and hard memory limit is set to 500 Gb). So, everything is crashing as expected due to lack of memory.

**Comment by versaille** [comment]
Thank you for your quick response. I will try with bigger RAM.
