### ISSUE TITLE
finished abnormally, err code: -11

### ISSUE THREAD

**Issue by wangxinbio** [ablab/spades#182]
Hi 
I used illumina data and PacBio data to assemble a genome. I got an error after several days. How can I fix this problem? Please see attached files for more details.

Thanks
[params.txt](https://github.com/ablab/spades/files/2426630/params.txt)
[spades.log](https://github.com/ablab/spades/files/2426631/spades.log)

**Comment by asl** [comment]
Please wait until SPAdes 3.12.1. It's likely that we fixed the problem there.

**Comment by wangxinbio** [comment]
> Please wait until SPAdes 3.12.1. It's likely that we fixed the problem there.

Thanks a lot.
