### ISSUE TITLE
contig/scaffold ID between Spades and plasmidSpades 

### ISSUE THREAD

**Issue by zhaoxvwahaha** [ablab/spades#188]
Hi,

I have used wonderful software Spades to assembly my NGS data of bacteria, but I need to distinguish  which contigs belong to plasmid and which belong to chromosome; 
Now I’m using the plasmidSPAdes to assembly my same data again, I wonder whether the contig ID of plasmid are still same with the result of Spades, i.e. if same contig ID represent same sequence between these two assembly process?

Looking forward to you reply

**Comment by asl** [comment]
See #168
