### ISSUE TITLE
SPAdes runs out of RAM even if it has enouth left on the machine 

### ISSUE THREAD

**Issue by smiksch** [ablab/spades#189]
Hi 
I try to use SPAdes for a very big and divers metagenome assembly. But it crashes and gives the well known error:

```
19:26:05.527   295G / 564G  INFO    General                 (kmer_index_builder.hpp    : 150)   Merging final buckets.
 19:43:04.431   295G / 564G  INFO   K-mer Index Building     (kmer_index_builder.hpp    : 336)   Index built. Total 24475877614 bytes occupied (3.70963 bits per kmer).
<jemalloc>: Error in malloc(): out of memory. Requested: 1266803878728, active: 317336846336


== Error ==  system call for: "['/home/smiksch/.pyenv/versions/miniconda2-latest/envs/SPAdes/share/spades-3.12.0-1/bin/spades-core', '/scratch/smiksch/PhD/JGI_seq/assemblies/crossassembly_assembly/K55/configs/config.info', '/scratch/smiksch/PhD/JGI_seq/assemblies/crossassembly_assembly/K55/configs/mda_mode.info', '/scratch/smiksch/PhD/JGI_seq/assemblies/crossassembly_assembly/K55/configs/meta_mode.info']" finished abnormally, err code: -6
````
If I read this right, SPAdes uses already 0.3 Tbytes of memory and failed to get another 1.2 Tbyts adding up to a total of 1.5 Tbytes. But the memory limit I set is at 1.9 Tbytes and the machine has 1.978 something, something Tbytes, so more than enough space for SPAdes to use, before it should crash. 

Do you have any clue why this happens?

Here is the log and parameters file

[params.txt](https://github.com/ablab/spades/files/2472003/params.txt)
[spades.log](https://github.com/ablab/spades/files/2472004/spades.log)

Thank you already in advance!

**Comment by Maya0801** [comment]
hi,

I also have a similar issue. Did you find a solution?

## sorry for double posting. 

[params.txt](https://github.com/ablab/spades/files/2768163/params.txt)
[spades.log](https://github.com/ablab/spades/files/2768164/spades.log)
[warnings.log](https://github.com/ablab/spades/files/2768165/warnings.log)


thanks!!

Maya
