### ISSUE TITLE
[Question] Can you assemble with merged paired end reads and unmatched reads as "single ended" reads?

### ISSUE THREAD

**Issue by jolespin** [ablab/spades#190]
I mapped metagenomic reads to a reference using `BBMap` which included `r1`, `r2`, and `unmatched` reads.  The result is a single fastq file for all the reads that mapped.  

**Can I use this as input into `SPAdes` as `single ended`?** 

There's an uneven amount of reads so I don't think they can be used as interlaced. 
Thanks in advance.

**Comment by asl** [comment]
Hello Josh,

Thank you for your interest in SPAdes.

Currently metaSPAdes requires a single paired-end library to run. So, I'm afraid you'd need to be able to properly "split" the resulting file.

**Comment by asl** [comment]
Well, you need to make sure that your left reads correspond to the right ones. You could keep singletons as single-end part of a paired-end library.
