### ISSUE TITLE
Error running metaspades spades-hammer err code: -4

### ISSUE THREAD

**Issue by euduca** [ablab/spades#199]
Hi, 
I got this error when running Metagenomic mode, the genome mode runs normally:

== Error ==  system call for: "['/usr/local/SPAdes/3.13.0/bin/spades-hammer', '/home_nfs/duca/curso/assemblies/Sample/spades_output.log/corrected/configs/config.info']" finished abnormally, err code: -4

The dmesg file contains:

spades-hammer[18512] trap invalid opcode ip:4b8d1b sp:7f23956fec58 error:0
spades-hammer[18518] trap invalid opcode ip:4b8d1b sp:7f2391af8c58 error:0
spades-hammer[18515] trap invalid opcode ip:4b8d1b sp:7f23938fbc58 error:0
spades-hammer[18516] trap invalid opcode ip:4b8d1b sp:7f2392efac58 error:0
spades-hammer[18517] trap invalid opcode ip:4b8d1b sp:7f23924f9c58 error:0 in spades-hammer[400000+14f000]
 in spades-hammer[400000+14f000] in spades-hammer[400000+14f000]
 in spades-hammer[400000+14f000]

My best regards. 

[spades.log](https://github.com/ablab/spades/files/2516019/spades.log)
[params.txt](https://github.com/ablab/spades/files/2516021/params.txt)

**Comment by asl** [comment]
Hello

Have you compiled SPAdes by yourself or used pre-build binaries?

**Comment by euduca** [comment]
Hi 

I used both (source and binaries), in our HPC.

I tried in a desktop (with CentOS 6, gcc 7) and the Metagenomic mode worked normally. 

What can I do ?

Thanks.

**Comment by asl** [comment]
> I used both (source and binaries), in our HPC.
What is the CPU of your HPC?

**Comment by asl** [comment]
And what is the system you're compiling the SPAdes on?

**Comment by euduca** [comment]
The error message is not so clear, so I can not think of a solution yet.

**Comment by asl** [comment]
Well, some parts of SPAdes that are used in metagenomic mode might use SSE 4.2 instructions. If the processor in question does not support such instructions, then "invalid opcode" error is quite possible. The selection is done in the compile time according to machine capabilities, so moving compiled binaries from one machine to another one might be non-trivial. However, it does not seem to be the problem in your case:
  - We ensure that pre-built binaries do not use these instructions
  - You said that you tried to compile from source

**Comment by asl** [comment]
Please reopen if this is still an issue
