### ISSUE TITLE
err code: -24 SPAdes/3.12.0

### ISSUE THREAD

**Issue by jzehnpfennig** [ablab/spades#200]
Hello, I am trying to run rnaSPAdes on my RNAseqdata, and I keep running into this error code: 
== Error ==  system call for: "['/opt/software/SPAdes/3.12.0-foss-2016b/bin/spades-hammer', '/mnt/home/zehnp1jrCMICH/ENV588/Trimmomatic/ENV588_Surface_zone.s pades.combined/corrected/configs/config.info']" finished abnormally, err code: -24.
I attached the params.txt and spades.log file! 

[params.txt](https://github.com/ablab/spades/files/2520112/params.txt)

[spades.log](https://github.com/ablab/spades/files/2520111/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

What is the filesystem on /mnt/home/zehnp1jrCMICH/ ?

**Comment by jzehnpfennig** [comment]
Hello, 
I work in a High Performance Computing Cluster (HPCC) through MSU. It is a Network File system. Home space is the storage created for each user account. By default, it is located at /mnt/home/$USER where users log into HPCC. It is set as accessible only by the user. It is often referred as “home directory”. This uses the ZFS file system, which is automatically backed-up hourly for the last 24 hours, daily for the last week and weekly for the last month. 
Does this help? 
Thank you, 
Jessica

**Comment by asl** [comment]
Most probably it has broken implementation of memory mapped files (as many network filesystems do). What if you move the SPAdes scratch directory (--tmp-dir) somewhere else?

**Comment by jzehnpfennig** [comment]
So something like this:

spades.py --rna --tem-dir /mnt/home/zehnp1jrCMICH/ENV588/Trimmomatic -t20 --pe1-1 C10S_S15_L008_R1_001.qc.fq.gz --pe1-2 C10S_S15_L008_R2_001.qc.fq.gz --pe1-1 C3S_S7_L008_R1_001.qc.fq.gz --pe1-2 C3S_S7_L008_R2_001.qc.fq.gz --pe1-1 C4S_S4_L008_R1_001.qc.fq.gz --pe1-2 C4S_S4_L008_R2_001.qc.fq.gz --pe1-1 C6S_S1_L008_R1_001.qc.fq.gz --pe1-2 C6S_S1_L008_R2_001.qc.fq.gz --pe1-1 C9S_S10_L008_R1_001.qc.fq.gz --pe1-2 C9S_S10_L008_R2_001.qc.fq.gz -o ENV588_Surface_zone.spades.combined

**Comment by asl** [comment]
Well, it should be not located on /mnt/home. Somewhere else more suitable as a scratch dir.

**Comment by jzehnpfennig** [comment]
So I ran SPAdes with the tmp-dir option and directed it to my scratch directory. Now I am getting another error. err -6. However SPAdes did run for about 7 hours. Any suggestions on what to do next?

I attached the spades.log and the params.txt file to this one as well. 
[spades.log](https://github.com/ablab/spades/files/2522421/spades.log)
[params.txt](https://github.com/ablab/spades/files/2522422/params.txt)

**Comment by asl** [comment]
Yes. This is known issue that was fixed in SPAdes 3.13.0. Consider upgrading.

**Comment by jzehnpfennig** [comment]
I have been using SPAdes 3.13.0.
