### ISSUE TITLE
Err code 24 using Anaconda

### ISSUE THREAD

**Issue by andrewjfunk** [ablab/spades#201]
Hi, I'm doing an assembly of a plant genome fro 2x125bp Illumina reads using the Anaconda package manager.

The reads have been trimmed and interleaved into eight files, one for each lane of data.

I've been running into problems with "err code 24".

Log files are attached, thanks. 
[params.txt](https://github.com/ablab/spades/files/2520498/params.txt)
[spades.log](https://github.com/ablab/spades/files/2520545/spades.log)

**Comment by andrewjfunk** [comment]
Well, I just saw that my fellow MSU HPC user is having the same problem. I'll follow along with that thread and delete this one if it turns out to be a problem using the scratch directory.

**Comment by asl** [comment]
Please provide the proper log. There is no error in your spades.log file

**Comment by andrewjfunk** [comment]
Updated.

**Comment by asl** [comment]
Yes, it's likely the same filesystem issue as in #200
