### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by parkjongbin** [ablab/spades#203]
/home/ebkim/BioSW/SPAdes-3.12.0-Linux/bin/spades.py \
    -t 24 -k 15,17,23 --cov-cutoff auto \
    -o Adaptor_Filtered_Reads/SEP2-2nd_AS1D0I0_95perc_over70bp_64cutoff_SPAdes \
    -1 Adaptor_Filtered_Reads/SEP2-2nd_AS1D0I0_95perc_over70bp_64cutoff_F_pair.fastq \
    -2 Adaptor_Filtered_Reads/SEP2-2nd_AS1D0I0_95perc_over70bp_64cutoff_R_pair.fastq \
    -s Adaptor_Filtered_Reads/SEP2-2nd_AS1D0I0_95perc_over70bp_64cutoff_single.fastq \
    --nanopore Adaptor_Filtered_Reads/barcode1_SEP-01_Adapter_Trimmed.fastq

Hello, i've running a spades using illumina short reads and nanopore long reads for hybrid assembly. It work well when only using illumina reads, but when i add a --nanopore option, error was occured as below.

[warnings.log](https://github.com/ablab/spades/files/2548022/warnings.log)
[params.txt](https://github.com/ablab/spades/files/2548023/params.txt)
[spades.log](https://github.com/ablab/spades/files/2548024/spades.log)

spades-core: /spades/src/common/io/reads/single_read.hpp:222: void io::SingleRead::Init(): Assertion `seq_.size() == qual_.size()' failed.
== Error ==  system call for: "['/home/ebkim/BioSW/SPAdes-3.12.0-Linux/bin/spades-core', '/home/ebkim/BioSW/20181105_Phage_Assembly/Adaptor_Filtered_Reads/SEP1-2nd_AS1D0I0_95perc_over70bp_64cutoff_SPAdes_Hybrid/K23/configs/config.info']" finished abnormally, err code: -6
======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Pipeline warnings:
 * It is recommended to specify single reads with --pe<#>-s, --mp<#>-s, --hqmp<#>-s, or --s<#> option instead of -s!
=== Error correction and assembling warnings:
 * 0:03:19.756    16M / 1G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 3
 * 0:02:44.516    16M / 1G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 4
======= Warnings saved to /home/ebkim/BioSW/20181105_Phage_Assembly/Adaptor_Filtered_Reads/SEP1-2nd_AS1D0I0_95perc_over70bp_64cutoff_SPAdes_Hybrid/warnings.log

It works in the virtualbox, so read files and SPAdes software are in the virtualbox folder. Dose anyone can explain about that error and how to fix?

**Comment by asl** [comment]
Your input reads (nanopore ones) are corrupted, they are not in the proper FASTQ format – somewhere the length of the sequence line does not correspond to the end of quality line.

PS: Your set of k-mer lengths does not make much sense. I would suggest you to stick to default set of k-mers unless you're 100% sure what you're doing.

**Comment by parkjongbin** [comment]
Thanks for your comment, i will try.
