### ISSUE TITLE
== Error == running metaspades, finished abnormally, err code: -6

### ISSUE THREAD

**Issue by BurinkiWU** [ablab/spades#205]
I use metaspades.py to hybrid assembly my illumina data and Nanopore data. The command was attached below: 
metaspades.py -1 ~/data/seameta_illumina/seameta_9_illu/seameta_9/seameta-9_illu_1.fa -2 ~/data/seameta_illumina/seameta_9_illu/seameta_9/seameta-9_illu_2.fa --nanopore ../seameta_9_1kb+.fa -o ./ &

Here are the erro showed on the terminal: 
<jemalloc>: Error in calloc(): out of memory

== Error ==  system call for: "['/home/wzq/miniconda3/share/spades-3.12.0-1/bin/spades-core', '/home/wzq/data/seawater_meta_9/workspace/hybrid_raw/K55/configs/config.info', '/home/wzq/data/seawater_meta_9/workspace/hybrid_raw/K55/configs/mda_mode.info', '/home/wzq/data/seawater_meta_9/workspace/hybrid_raw/K55/configs/meta_mode.info']" finished abnormally, err code: -6

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

[params.txt](https://github.com/ablab/spades/files/2564355/params.txt)
[spades.log](https://github.com/ablab/spades/files/2564356/spades.log)

Could you please help me to figure out it? 
Thanks.

**Comment by asl** [comment]
Hello

This looks like a bug we fixed in SPAdes 3.13.0. Please confirm.

**Comment by BurinkiWU** [comment]
Thanks, I will have a try.

**Comment by asl** [comment]
> Thanks, I will have a try.

Please reopen if this is still an issue
