### ISSUE TITLE
meta_spades  contig lenth

### ISSUE THREAD

**Issue by aremkho** [ablab/spades#206]
Dear Anton and Spades team,
Thank you for maintaining  the Spades.
I am wondering if there is any way to set a MAXIMUM contig length  in metaspades?
Many thanks in advance
Arsalan

**Comment by asl** [comment]
No, why? :)

**Comment by arsalane1978** [comment]
Thanks, I am trying to assemble a long gene from a metagenomic  pool of different organisms using illumina 150 PE.
Spades tend to assemble the pool to the longest contig size which is what it suppose to do.
How ever the target genes can not exceed 1000 bp in size. I thought there might be a solution for that.
Cheers

**Comment by asl** [comment]
Sure. Just look into output and cut the necessary parts from the contigs.
