### ISSUE TITLE
metaspades assembling illumina & nanopore data error

### ISSUE THREAD

**Issue by BurinkiWU** [ablab/spades#207]
I use metaspades.py to assembly illumina 150 bps data with nanopore data. An error appeared on the screen. 
The warning.log and spades.log were attached here for your information. Could you please figure out this problem for me? 

My command for metaspades.py:

 nohup ~/tools/SPAdes-3.13.0-Linux/bin/metaspades.py -1 ~/data/seameta_illumina/seameta_9_illu/seameta_9/seameta-9_illu_1.fq -2 ~/data/seameta_illumina/seameta_9_illu/seameta_9/seameta-9_illu_2.fq --nanopore ../seameta_9_1kb+.fa -t 70 -o ./ &

Thanks.
[spades.log](https://github.com/ablab/spades/files/2568001/spades.log)
[warnings.log](https://github.com/ablab/spades/files/2568002/warnings.log)

=== Error correction and assembling warnings:
 * 4:21:53.059    66G / 163G  WARN   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  59)   Less than half of genome in unique edges!
======= Warnings saved to /home/wzq/data/seawater_meta_9/workspace/hybrid_raw/warnings.log

**Comment by asl** [comment]
There are no errors in the attached log files.
