### ISSUE TITLE
metaspades assembling illumina & nanopore data error

### ISSUE THREAD

**Issue by BurinkiWU** [ablab/spades#208]
I used metaspades.py to hybrid assembly illumina & nanopore data, my command was show below: 

Command line: nohup /home/wzq/tools/SPAdes-3.13.0-Linux/bin/metaspades.py	-1 /home/wzq/data/seameta_illumina/seameta_9_illu/seameta_9/seameta-9_illu_1.fq	-2	/home/wzq/data/seameta_illumina/seameta_9_illu/seameta_9/seameta-9_illu_2.fq	--nanopore	/home/wzq/data/seawater_meta_9/workspace/seameta_9_1kb+.fa	-t	70	-o	/home/wzq/data/seawater_meta_9/workspace/hybrid_raw &

=== Error correction and assembling warnings:
 * 4:21:53.059    66G / 163G  WARN   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  59)   Less than half of genome in unique edges!

The spades.log and warning.log were attached for your information. 

Thanks. 
[spades.log](https://github.com/ablab/spades/files/2568992/spades.log)
[warnings.log](https://github.com/ablab/spades/files/2568993/warnings.log)

**Comment by asl** [comment]
There is no error in the logs. The assembly finished successfully.
