### ISSUE TITLE
should --only-error-correction output N-masked sequence?

### ISSUE THREAD

**Issue by wangyugui** [ablab/spades#21]
Should --only-error-correction output N-masked sequence?

Now it output the corrected char?

**Comment by asl** [comment]
Sorry, I don't understand your question. Please elaborate.

**Comment by wangyugui** [comment]
I thought the simplest/safe way for fastq error correct is to mask all low coverage kmer to N. and we can safely use small k-mer such as 31 or even 25 ?

If we output the corrected sequence char, we have to use very big kmer such as 63 or more ?

**Comment by asl** [comment]
See https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-14-S1-S7 for the description of BayesHammer algorithm
