### ISSUE TITLE
Parse error at line 8672: missing colon in auxiliary data. Error code -6

### ISSUE THREAD

**Issue by besnarda** [ablab/spades#210]
Hello, 

Thanks for all your hard work! 
I'm currently working on meta-genome assembly using spades. I know you developed a Metaspades script but for a reason i don't quite understand, I found results of the classic spades more accurate with my data. I was able to proceed with all samples but two. I don't understand what this parse error is about, if you could help me to solve this issue. 
Data are about 30 millions paired reads from illumina sequencing.

Also i'm working on a cluster, so my version is no up to date (3.11)

[params.txt](https://github.com/ablab/spades/files/2589519/params.txt)
[spades.log](https://github.com/ablab/spades/files/2589520/spades.log)

**Comment by besnarda** [comment]
I am mainly interested in virus assembly in my dataset. I have multiple references for my viruses, metaspades seemed to split the genomes I am looking for in small bits. 
I did observe the same problem with spades as I scale up the number of reads from 8 millions to 60 millions. I think it could be due to the presence of a lot of polymorphism in virus sequences but I am not an expert of assembly. 

I will give metaspades another try!

Restart, you mean the whole cluster? I will try to restart the job then.

**Comment by besnarda** [comment]
Problem fixed when restarting with enough space. I suppose it was due to not enough space in my workspace causing a file to be corrupted (not written correctly). Thanks for the help.

**Comment by asl** [comment]
> I am mainly interested in virus assembly in my dataset. I have multiple references for my viruses, metaspades seemed to split the genomes I am looking for in small bits.

Well, if you're having lots of variations then certainly you will have smaller contigs – you need to analyze the assembly graph in order to separate out variations.

In your case SPAdes in multicell mode just removes everything falling under some (arbitrary) coverage threshold. So, beware of misassemblies! You could easily obtain chimeric contigs containing the most abundant parts from different genomes.
