### ISSUE TITLE
error 255 fasta file missing or corrupted

### ISSUE THREAD

**Issue by besnarda** [ablab/spades#213]
Hello,
I have a problem running SPAdes on a sample. The spades log state about a fasta that "doesn't exist or can't be read!". I am wondering if you have ever experience this issue. It is the last and only sample of a serie of 16 that didn't work. 

[params.txt](https://github.com/ablab/spades/files/2600256/params.txt)
[spades.log](https://github.com/ablab/spades/files/2600257/spades.log)

Any help would be appreciated.

**Comment by asl** [comment]
I would suspect some I/O issue on your end since one of SPAdes intermediate files got corrupted or does not exist. I would suggest to check the system log and / or rerun the failed job.

**Comment by asl** [comment]
Please reopen if you're still thinking it's an issue.
