### ISSUE TITLE
SPAdes err code: -6

### ISSUE THREAD

**Issue by lizhiming11** [ablab/spades#214]
I'm trying to do a denovo assembly with pair end reads,but something wrong with it
I received the following error and I don't know what mean of this error, and how can i resolve it.

Command line: /ldfssz1/ST_META/share/flow/anaconda3/bin/metaspades.py   -t      5       -o      /ldfssz1/ST_HEALTH/Aging/lizhiming/work/SkinMeta/Skin242/2.Assembly/DP1807004429_new    -1      /ldfssz1/ST_HEALTH/Aging/lizhiming/work/SkinMeta/Skin10_15/1.Cleandata/DP1807004429_rmHost.1.fq.gz      -2      /ldfssz1/ST_HEALTH/Aging/lizhiming/work/SkinMeta/Skin10_15/1.Cleandata/DP1807004429_rmHost.2.fq.gz      -m      10  

System information:
  SPAdes version: 3.11.1
  Python version: 3.6.1
  OS: Linux-2.6.32-696.30.1.el6.x86_64-x86_64-with-centos-6.9-Final

Output dir: /ldfssz1/ST_HEALTH/Aging/lizhiming/work/SkinMeta/Skin242/2.Assembly/DP1807004429_new
Mode: read error correction and assembling
Debug mode is turned OFF

Thank you in advance!
[params.txt](https://github.com/ablab/spades/files/2602531/params.txt)
[spades.log](https://github.com/ablab/spades/files/2602532/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes

The log reads:

Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t)'. In file '/opt/conda/conda-bld/spades_1506749873610/work/SPAdes-3.11.1/src/common/io/kmers/mmapped_reader.hpp' on line 99. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.


So you're running out of RAM.
