### ISSUE TITLE
Out of memory on running metaspades v3.13.0

### ISSUE THREAD

**Issue by zhanglu295** [ablab/spades#218]
I tried to run metaspades.py (v3.13.0) on a mixture of 20 microbes for 1 lane reads from Illumina X10 system. I allowed memory usage for about 2.5TB, but the assembler still reported "out of memory" issue when K=55. We also sequenced the same sample by BGIseq, and metaspades worked pretty well. Could you help me figure out whether it is the problem of data or bugs in the program? Thank you.  
[params.txt](https://github.com/ablab/spades/files/2626370/params.txt)
[spades.log](https://github.com/ablab/spades/files/2626372/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

It seems that you're having very fragmented assembly. I would check for some possible contamination (e.g. human). But indeed, SPAdes required more than 2.5 Tb of RAM for your dataset
