### ISSUE TITLE
Concatenating Illumina R1* and R2* files

### ISSUE THREAD

**Issue by karinlag** [ablab/spades#22]
I have multiple fastq files for a sample, i.e. multipe R1 and R2 files. I am wondering what effect it will have on the assembly if I concatenate all R1* and R2* files together and then use them in assembly. To be clear, I here mean 

cat R1* > R1_input.fq
cat R2* > R2_input.fq

followed by

spades --pe-1 R1_input.fq --pe-2 R2_input.fq

vs using each R file separately with --pe-1-1. --pe-2-1, --pe-1-2 and --pe-2-2 and so forth.

**Comment by snurk** [comment]
If you provide multiple files through pe1-* .. peN-*, each pair of R1/R2 files will be considered to originate from different libraries (e.g. potentially having different read lenghts, insert size, etc) and will be treated as such during repeat resolution.
If those are multiple files for the same library and sequencing setup, I would suggest concatenating them first to get more reliable results.
BTW, this is a not well documented feature, but you can actually specify same option multiple times and spades will concatenate corresponding files for you, e.g. ```--pe1-1 R1_1.fq --pe1-1 R1_2.fq ... --pe1-2 R2_1.fq --pe1-2 R2_2.fq ...```

**Comment by karinlag** [comment]
Thanks for the explanation, that will make everything that much easier :smile:
