### ISSUE TITLE
trouble with error code -6

### ISSUE THREAD

**Issue by Arno75** [ablab/spades#221]
Hello,

i've got some trouble to launch spades on data set of 80Gb in gzip compressed format.

this is my System information:
  SPAdes version: 3.10.0
  Python version: 2.7.5
  OS: Linux-3.10.0-693.39.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo

my commands line:
spades.py  -k 71,99,127 -m 48 --only-assembler -t 41 --careful --pe1-1 BSI_1_1_clean.fastq.gz --pe1-2 BSI_1_2_clean.fastq.gz --pe2-1 BSI_2_1_clean.fastq.gz  --pe2-2 BSI_2_2_clean.fastq.gz  -o /ccc/scratch/cont007/fg0014/Spades_process_BIS_CD/

The issues :
== Error ==  system call for: "['/ccc/cont007/dsku/lautrec/home/app/fg/fg/products/spades-3.10.0/el7-x86_64-generic/bin/spades', '/ccc/scratch/cont007/fg0014/coulouxa/Spades_process_BIS_CD/K71/configs/config.info',
 '/ccc/scratch/cont007/fg0014/coulouxa/Spades_process_BIS_CD/K71/configs/careful_mode.info']" finished abnormally, err code: -6 

Log File : 
[spades.log](https://github.com/ablab/spades/files/2649357/spades.log)

Thanks in advance for your help

**Comment by asl** [comment]
Please attach spades.log file as you were instructed just 2 lines below the ones you posted.

**Comment by Arno75** [comment]
this is my log file !
[spades.log](https://github.com/ablab/spades/files/2642986/spades.log)

**Comment by OnlyHigh** [comment]
Hi, I'm literally having the same error,  I tried with two versions of python (2.7 and 3.6) and two version of SPADES mode rna (3.12 and 3.13)
[spades.log](https://github.com/ablab/spades/files/2659194/spades.log)
[spades_2.log](https://github.com/ablab/spades/files/2659195/spades_2.log)

Why is this error happening? 
Thanks in advance for the help, 
Cheers, 
Luis Alfonso.

**Comment by OnlyHigh** [comment]
Hi, 
I found that, particularly for me, this error was happening because I was not having enough writing space in the Hard disk,

@Arno75  I suggest you to check how much space in disk for writing do you have, 
Cheers, 
Luis Alfonso.

**Comment by Arno75** [comment]
Hi Luis,
Thanks for your help.

I do not think that the problem comes from space on my disk, because I 
have large storage capacity available during my process.At the end I 
occupy barely a few percent. I have impression that spades have been 
programmed for small bacterial genomes not for eukaryotic ones.

Arnaud

Le 09/12/2018 à 20:52, Luis A. Arteaga-Figueroa a écrit :

**Comment by asl** [comment]
@Arno75 You problem is due to some of SPAdes' intermediate files was corrupted in the process. Usually this happens due to I/O problem on your end. I would suggest to upgrade to at least SPAdes 3.12 that has better diagnostics of I/O error codes (e.g. incomplete writes), etc.

**Comment by asl** [comment]
@OnlyHigh Exactly as I said. And it seems that your OS silently failed a write without indicating this properly...

**Comment by Arno75** [comment]
I'm testing version 3.13,
I'll giving you a feedback as soon as I get results
