### ISSUE TITLE
rnaspades 3.13 err code -6: incorrectly reading --memory parameter?

### ISSUE THREAD

**Issue by kim-fehl** [ablab/spades#224]
Hello, I'm running rnaspades on a big dataset (~60G of gzipped paired-end reads) as a part of [Oyster River Protocol](https://oyster-river-protocol.readthedocs.io/en/latest/). It seems that rnaspades incorrectly reads `--memory` parameter. I use the node with 2T of RAM available and use ` --memory 500 ` parameter value. However, line 80 of the log reads:

`  0:00:00.000     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 5 Gb`

and then the error occurs:

`0:58:11.957    12M / 860M  INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 0.0475074 Gb
  0:58:11.957    12M / 860M  INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 16384
<jemalloc>: Error in malloc(): out of memory. Requested: 432528, active: 4911529984`

Could you please help me with the issue?

[params.txt](https://github.com/ablab/spades/files/2705806/params.txt)
[spades.log](https://github.com/ablab/spades/files/2705807/spades.log)

**Comment by asl** [comment]
SPAdes is correct here. Long story short: you're running out of RAM.

Here what's happening: at the time of failure SPAdes used 4.5 Gb of RAM. However your OS failed to fulfill SPAdes request to allocate 400 kb more. We have no other option than to pass this error to you. 

PS: Also, running single k-mer RNA assembly is not recommended. We're suggesting to stick to default settings unless you're 100% sure what you're doing.

**Comment by kim-fehl** [comment]
You are absolutely right. I've set incorrect memory constraints with qrsh even before starting spades. 

As for your latter note, I am just following the pipeline of Oyster River protocol. It also uses k=55 afterwards, and Trinity assembler too, joining all outputs. Hope it's not meaningless...

**Comment by asl** [comment]
> Hope it's not meaningless...
It's at least questionable...
