### ISSUE TITLE
error code -6 running spades 3.13.0

### ISSUE THREAD

**Issue by DrKADunn** [ablab/spades#225]
I am getting error code -6 when running spades.  I get an error but no warnings.  I have attached the log and parameter files.
[spades.log](https://github.com/ablab/spades/files/2711218/spades.log)
[params.txt](https://github.com/ablab/spades/files/2711219/params.txt)

It doesn't appear to be running out of memory (I set at 24 Gb) but I may be misunderstanding the log file.
Thanks

**Comment by asl** [comment]
While you set memory limit to 24 Gb – how much free RAM is available for your SPAdes job?

**Comment by DrKADunn** [comment]
Yes I have determined this is the issue, I only have 24 Gb available in total on that machine and other jobs are also utilizing it.


Dr Katherine Dunn
Department of Biology
Dalhousie University
Halifax NS






On Jan 11, 2019, at 7:53 AM, Anton Korobeynikov <notifications@github.com<mailto:notifications@github.com>> wrote:


While you set memory limit to 24 Gb – how much free RAM is available for your SPAdes job?
