### ISSUE TITLE
Which one contigs.fasta or scaffolds.fasta should I use for next analysis

### ISSUE THREAD

**Issue by SarahIsme** [ablab/spades#226]
I have a query when I use metaspades.py to assemble my meta-genomic data of sludge.

The command is as follow: 

   spades.py --meta -1 clean_114_6_1P.fq.gz -2 clean_114_6_2P.fq.gz -t 32 -m 30 -k 55,77,99 -o s114-6_DME24960-V

The kmer was set as 55,77,99.

So there were three folders in my output directory as attached Figure 1 (K55, K77, K99).
![Uploading Figure1.PNG…]()

And in K55 or K77 folder, there was a final_contigs.fasta and a simplified_contigs.fasta as attached Figure 2 or [3.](url
![Uploading Figure 2.PNG…]()
![Uploading Figure 3.PNG…]()

)

However, in K99 folder, there was a final_contigs.fasta, a scaffolds.fasta and a simplified_contigs.fasta as attached Figure 4.
[
![Uploading Figure 4.PNG…]()
](url)

Including the contigs.fasta and scaffolds.fasta in output directory, I got seven contigs.fasta and two scaffolds.fasta.

The first question:

Which one contigs.fasta or scaffolds.fasta should I use for next analysis, or need I evaluate the assemble quality of each .fasta file? But there was no scaffolds.fasta for K55 and K77.

The second question:

Could I only use one k-mer to perform the metaspades.py?

**Comment by asl** [comment]
Please refer to SPAdes manual for explanation of SPAdes output: http://cab.spbu.ru/files/release3.13.0/manual.html#sec3.5

> Could I only use one k-mer to perform the metaspades.py?

In general, it's not recommended (unless you're 100% sure what you're doing).

**Comment by hlfreund** [comment]
Hi there! Just to clarify, for binning with metaBAT (for example), I would use the scaffolds.fasta file instead of the contigs.fasta file? I am seeing mixed suggestions online so I just wanted to clarify, thank you so much!
