### ISSUE TITLE
Can't change memory limit. 

### ISSUE THREAD

**Issue by CPTQuesoXI** [ablab/spades#227]
Hello,
I am attempting to run a meta genome assembly with 128Gb of RAM. I specify this however, the memory limit seems to be set to 3Gb which I believe is causing my assembly to run out of memory. I specify the PVMEM to be 54Gb in the PBS script when submitting a job to the High Performance Cluster I am using, however this does not change the memory limit either. Below are the contents of the output file. 

Thank you. 

Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /gpfs/scratch/dlshrewsberry/dvm_assembly/tmp
  Threads: 2
  Memory limit (in Gb): 128

======= SPAdes pipeline started. Log can be found here: /gpfs/scratch/dlshrewsberry/dvm_assembly/spades.log

===== Assembling started.

== Running assembler: K33

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  74)   Loaded config from /gpfs/scratch/dlshrewsberry/dvm_assembly/K33/configs/config.info
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  74)   Loaded config from /gpfs/scratch/dlshrewsberry/dvm_assembly/K33/configs/mda_mode.info
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  74)   Loaded config from /gpfs/scratch/dlshrewsberry/dvm_assembly/K33/configs/meta_mode.info
  0:00:00.000     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 3 Gb
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  87)   Starting SPAdes, built from refs/heads/spades_3.13.0, git revision 8ea46659e9b2aca35444a808db550ac333006f8b
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  88)   Maximum k-mer length: 128
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  89)   Assembling dataset (/gpfs/scratch/dlshrewsberry/dvm_assembly/dataset.info) with K=33
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  90)   Maximum # of threads to use (adjusted due to OMP capabilities): 2
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  51)   SPAdes started
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  58)   Starting from stage: construction
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  65)   Two-step RR enabled: 0
  0:00:00.000     4M / 4M    INFO   StageManager             (stage.cpp                 : 132)   STAGE == de Bruijn graph construction
  0:00:00.000     4M / 4M    INFO    General                 (read_converter.hpp        :  77)   Converting reads to binary format for library #0 (takes a while)
  0:00:00.000     4M / 4M    INFO    General                 (read_converter.hpp        :  78)   Converting paired reads
  0:00:00.215    80M / 100M  INFO    General                 (binary_converter.hpp      :  93)   16384 reads processed
  0:00:00.318    88M / 100M  INFO    General                 (binary_converter.hpp      :  93)   32768 reads processed
  0:00:00.524   112M / 112M  INFO    General                 (binary_converter.hpp      :  93)   65536 reads processed
  0:00:00.936   156M / 156M  INFO    General                 (binary_converter.hpp      :  93)   131072 reads processed
  0:00:01.760   248M / 248M  INFO    General                 (binary_converter.hpp      :  93)   262144 reads processed
  0:00:03.413   432M / 432M  INFO    General                 (binary_converter.hpp      :  93)   524288 reads processed
  0:00:08.937   716M / 716M  INFO    General                 (binary_converter.hpp      :  93)   1048576 reads processed
  0:00:18.047   720M / 720M  INFO    General                 (binary_converter.hpp      :  93)   2097152 reads processed
  0:00:36.513   724M / 724M  INFO    General                 (binary_converter.hpp      :  93)   4194304 reads processed
  0:01:17.218   736M / 736M  INFO    General                 (binary_converter.hpp      :  93)   8388608 reads processed
  0:01:25.013   680M / 736M  INFO    General                 (binary_converter.hpp      : 117)   9159540 reads written
  0:01:26.067     4M / 736M  INFO    General                 (read_converter.hpp        :  87)   Converting single reads
  0:01:26.209   132M / 736M  INFO    General                 (binary_converter.hpp      : 117)   0 reads written
  0:01:26.209     4M / 736M  INFO    General                 (read_converter.hpp        :  95)   Converting merged reads
  0:01:26.350   132M / 736M  INFO    General                 (binary_converter.hpp      : 117)   0 reads written
  0:01:26.351     4M / 736M  INFO    General                 (construction.cpp          : 111)   Max read length 125
  0:01:26.351     4M / 736M  INFO    General                 (construction.cpp          : 117)   Average read length 98.9284
  0:01:26.351     4M / 736M  INFO    General                 (stage.cpp                 : 101)   PROCEDURE == k+1-mer counting
  0:01:26.352     4M / 736M  INFO    General                 (kmer_index_builder.hpp    : 117)   Splitting kmer instances into 4 files using 2 threads. This might take a while.
  0:01:26.352     4M / 736M  INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 32768
  0:01:26.352     4M / 736M  INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 0.499349 Gb
  0:01:26.352     4M / 736M  INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 8377685
  0:01:35.197     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 2071403 reads
  0:01:44.467     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 4127509 reads
  0:01:53.163     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 6173534 reads
  0:02:01.868     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 8211567 reads
  0:02:10.574     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 10247518 reads
  0:02:19.269     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 12293515 reads
  0:02:28.332     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 14332790 reads
  0:02:37.014     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 16374712 reads
  0:02:46.099     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 18395967 reads
  0:02:55.174     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 20422836 reads
  0:03:57.540     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 289)   Processed 34418215 reads
  0:04:07.774     1G / 1G    INFO    General                 (kmer_splitters.hpp        : 295)   Adding contigs from previous K
  0:04:07.776     8M / 1G    INFO    General                 (kmer_splitters.hpp        : 308)   Used 36638160 reads
  0:04:07.776     8M / 1G    INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  0:04:07.776     8M / 1G    ERROR   General                 (mmapped_reader.hpp        : 113)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12
  0:04:07.776     8M / 1G    ERROR   General                 (mmapped_reader.hpp        : 113)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12

== Error ==  system call for: "['/gpfs/scratch/dlshrewsberry/SPAdes/SPAdes-3.13.0-Linux/bin/spades-core', '/gpfs/scratch/dlshrewsberry/dvm_assembly/K33/configs/config.info', '/gpfs/scratch/dlshrewsberry/dvm_assembly/K33/configs/mda_mode.info', '/gpfs/scratch/dlshrewsberry/dvm_assembly/K33/configs/meta_mode.info']" finished abnormally, err code: 255

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

SPAdes cannot go beyond the memory limit imposed by the system (it will need root privileges in order to do so). That said, I would suggest you to contact your system administrator on how the memory limits are set on your HPC cluster.
