### ISSUE TITLE
k-mer counting does not start

### ISSUE THREAD

**Issue by Tahsin-Khan** [ablab/spades#228]
Hi. I am using MetaSpades V 3.13 for assembly of by metagenomic datasets. I have 1 forward and 1 reverse dataset of approx 6.5 gb each. I am running the assembly on Raijin HPC and with 300 gb memory for 2 days. But after approx 8 hours of running the program gets stuck on Starting k-mer counting. This has happened several times. I am expecting a solution to this. If you can help, I would be really grateful. 
Thanks in advance. 
[params.txt](https://github.com/ablab/spades/files/2753954/params.txt)
[spades.log](https://github.com/ablab/spades/files/2753955/spades.log)

**Comment by asl** [comment]
Most probably this is caused either by some I/O problems or heavily swaps on your HPC side. I would suggest to check for possible reasons such as that.

**Comment by asl** [comment]
Please reopen if you're still having this issue (e.g. even after restart or so)

**Comment by quliping** [comment]
> Most probably this is caused either by some I/O problems or heavily swaps on your HPC side. I would suggest to check for possible reasons such as that.

I have also encountered this problem when using metaspades v3.15.5 on a HPC. How can I solve this problem? I don't understand what you mean.
