### ISSUE TITLE
Error code: 5 follow by err code: 255

### ISSUE THREAD

**Issue by cprediger** [ablab/spades#229]
I am a new spades user, and I am trying to assembly a fly's whole genome using de novo approach . I am sending the lag and parameters files.

thank you

[params.txt](https://github.com/ablab/spades/files/2755244/params.txt)
[spades.log](https://github.com/ablab/spades/files/2755245/spades.log)

**Comment by asl** [comment]
The log reads:

```
  2:36:07.569     3G / 3G    ERROR   General                 (kmer_splitters.hpp        : 145)   I/O error! Incomplete write! Reason: Input/output error. Error code: 5
```
So, I would suggest you to ask your system administrator about any problems with I/O problems on your server.
