### ISSUE TITLE
Spades "finished abnormally, err code: -7"

### ISSUE THREAD

**Issue by jlebov** [ablab/spades#230]
Hi I am trying to assemble a bacterial genome from paired-end Illumina reads and I received the following error: " finished abnormally, err code: -7". Can someone help me resolve this?

I have attached my spades.log file and params.txt file. 

Thanks, Jarrett 
[params.txt](https://github.com/ablab/spades/files/2757522/params.txt)
[spades.log](https://github.com/ablab/spades/files/2757523/spades.log)

**Comment by asl** [comment]
Could you try to move SPAdes output folder from GPFS storage?

**Comment by jlebov** [comment]
Hi, Thanks for your reply. I'm not sure what GPFS storage is exactly, but I had submitted my command as a job on a HPC cluster. I've since run the same command straight from the command line instead of using a .sh script and things seem to have worked fine. I may have misused some terminology in this post, but I think I may have inadvertently done what you suggested and things seem to be fine now. Thanks for your help!!!

**Comment by asl** [comment]
Well, then you may want to work with your system administrator to figure out the differences. Many versions of GPFS are known to be extremely broken and this is might be your case.
