### ISSUE TITLE
cmake error; unable to install 

### ISSUE THREAD

**Issue by sankadinesh** [ablab/spades#231]
![spade cmake errors](https://user-images.githubusercontent.com/43870684/51165411-1e276400-18c6-11e9-9055-5c436ee7b92d.jpg)
Please help.
Thanks 
Regards,
Dinesh

**Comment by asl** [comment]
Per SPAdes manual (http://cab.spbu.ru/files/release3.13.0/manual.html#sec2.3) you need to have libbz installed.
