### ISSUE TITLE
How big a genome is  actually big for Spades?

### ISSUE THREAD

**Issue by aremkho** [ablab/spades#232]
Good day Anton,
I wish you a happy and fruitful 2019.
I have been trying to assemble an Antarctic insect genome ~1,2 GB. Spades actually perform reasonably well. I read your warning about using Spades for large genomes. I would like to ask your kind advice and see roughly  what genome size  is  actually "large" for  Spades?
Thanks in advance

**Comment by asl** [comment]
Well.. great it worked for you!

It depends on many factors including the resources you're having, the complexity of the genome, etc. So... you mileage may vary :)
