### ISSUE TITLE
How to deal with err code -6

### ISSUE THREAD

**Issue by Duannai** [ablab/spades#235]
[spades.log](https://github.com/ablab/spades/files/2785695/spades.log)
[params.txt](https://github.com/ablab/spades/files/2785793/params.txt)
Dear developers,

When I firstly assembled the data, the software showed there were too many k-mers (k was set as 55), and told me it needed 37 GB of RAM at least. So I set the RAM as 54 GB, and stopped the other softwares which may consume RAM, but it didn't work.

What should I do next?

Thanks in advance!

**Comment by asl** [comment]
Hello

Unfortunately, it's not possible to predict the memory consumption in advance. We could only estimate the required memory for certain stages and error out earlier. From the log:

```
<jemalloc>: Error in malloc(): out of memory. Requested: 8149096944, active: 53074722816
```

So, it looks like SPAdes required at least 57 Gb of RAM to assemble your dataset.
