### ISSUE TITLE
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'

### ISSUE THREAD

**Issue by Duannai** [ablab/spades#236]
Sorry to bother you.

Is this situation due to the poor RAM?
[params.txt](https://github.com/ablab/spades/files/2794385/params.txt)
[spades.log](https://github.com/ablab/spades/files/2794386/spades.log)

**Comment by asl** [comment]
The log reads

```
 Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So, there is insufficient RAM to run SPAdes
