### ISSUE TITLE
rnaspades.py maximum k-mer length

### ISSUE THREAD

**Issue by cooketho** [ablab/spades#237]
I'm running rnaspades.py on 2x75 bp paired-end reads using the argument `-k 75`. It fails with the following message:

`0:00:00.846     4M / 1G    ERROR   General                 (kmer_index_builder.hpp    : 129)   No kmers were extracted from reads. Check the read lengths and k-mer length settings`

I can get it to run to completion with `-k 73` though. Is there a reason the k-mer length can't be the same as the read length, or is this a bug? I know for sure the reads are 75 characters long.

I understand from reading previous posts that 1/2 the read length is a good k-mer length, so I understand `-k 75` may be too long for 75 bp reads. The reason I ask is I was using rnaspades.py as part of the Oyster River Protocol, which uses `-k 75` by default (probably because it's optimized for longer reads), and it was throwing an error. I want to know if that error is actually due to unexpected behavior on the rnaspades end (i.e. whether one should or should not be able to set k-mer to read length).

Thanks!

[spades.log](https://github.com/ablab/spades/files/2800500/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Using k = 75 actually requires your reads to be 76 bp long, hence the error. Unfortunately, Oyster River Protocol has some questionable settings, and this is one of them.
