### ISSUE TITLE
SPAdes finished abnormally, err code: -9

### ISSUE THREAD

**Issue by Arkadiy-Garber** [ablab/spades#239]
Hi,

Not sure what is causing this issue, but I think I have the latest version of SPAdes, and I am getting this error message:

`== Error ==  system call for: "['/home/arkadiy_garber/bin/SPAdes-3.13.0/bin/spades-hammer', '/home/arkadiy_garber/Ant/SPAdes_1/corrected/configs/config.info']" finished abnormally, err code: -9`

I have checked the /home/arkadiy_garber/bin/SPAdes-3.13.0/bin/ directory and it contains the executable "spades-hammer". So not sure what the problem is.

Thanks,
Arkadiy

**Comment by asl** [comment]
Please attach the params.txt and spades.log files as you were instructed just 1 line below the github link.

Thanks!

**Comment by asl** [comment]
So, it's likely that you're either running out of RAM or there were some I/O issues – this step is both I/O and RAM hungry.

**Comment by Arkadiy-Garber** [comment]
Ok, thanks!

So does this mean that I am not allocating enough memory for the spades job, or that there isn't enough memory in the system for spades?

In any case, I am pretty sure that I provided spades with more than enough memory (500GB) using the -m flag, and the system has a total of 1TB of free RAM. So it is seems likely an I/O issue, which I am not sure how to fix, because I am only providing spades with two files: the forward and reverse reads (which seem to be properly formatted, as far as I can tell).

**Comment by asl** [comment]
You may want to check in the system log whether there were any problems with the storage, etc.

**Comment by sammyjava** [comment]
I've got the same issue running 3.12.0 and it doesn't seem to be complaining about RAM. Still a RAM or I/O issue?
```
  4:32:05.909    68G / 69G   INFO   StageManager             (stage.cpp                 : 132)   STAGE == Mismatch Correction
  4:32:05.909    68G / 69G   INFO    General                 (graph_pack.hpp            : 109)   Normalizing k-mer map. Total 404011155 kmers to process
  4:39:26.897    68G / 77G   INFO    General                 (graph_pack.hpp            : 111)   Normalizing done


== Error ==  system call for: "['/Carnegie/DPB/Homes/Users/shokin/SPAdes-3.12.0-Linux/bin/spades-core', '/Carnegie/DGE/Data/Shared/Labs/Evans/Everyone/Sam/C202SC18121792/MEM20181/K77/configs/config.info']" finished abnormally, err code: -9

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:39:28.010    20G / 27G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 0
 * 2:22:03.535    15G / 26G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 3
 * 2:22:03.540    15G / 26G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 3
======= Warnings saved to /Carnegie/DGE/Data/Shared/Labs/Evans/Everyone/Sam/C202SC18121792/MEM20181/warnings.log

=== ERRORs:
 * system call for: "['/Carnegie/DPB/Homes/Users/shokin/SPAdes-3.12.0-Linux/bin/spades-core', '/Carnegie/DGE/Data/Shared/Labs/Evans/Everyone/Sam/C202SC18121792/MEM20181/K77/configs/config.info']" finished abnormally, err code: -9
```
[params.txt.gz](https://github.com/ablab/spades/files/2958089/params.txt.gz)
[spades.log.gz](https://github.com/ablab/spades/files/2958090/spades.log.gz)

**Comment by Arkadiy-Garber** [comment]
ANTON,

Any thoughts on this? This issue has NOT been resolved FYI.

Attached are some spades.log files from the multiple failures of this program. Your help would be appreciated.

Am I misunderstanding something? There seem to be no memory issues now. I am running spades EXACTLY as I have been running it before. Can you provide any insights on what is causing this errors?

Spasibo
Arkadiy
[spades-1.log](https://github.com/ablab/spades/files/3014951/spades-1.log)
[spades-2.log](https://github.com/ablab/spades/files/3014952/spades-2.log)

**Comment by grean326** [comment]
I am also having the same issue.  Any headway on a fix?

1:25:04.134    10G / 10G   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 16384
  1:25:04.134    10G / 10G   INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 1.49635 Gb
  1:25:04.134    10G / 10G   INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 209715
  1:25:05.353    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /ddn1/vol1/site_scratch/leuven/329/vsc32901/Peruvian_Dataset/D502_assembly/split_input/D502_1_HW3LYCCXX_L3_interleaved_PAIRED_clean_1.fastq
  1:25:28.078    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4925551 reads
  1:26:04.670    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 9850960 reads
  1:26:30.288    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 14789290 reads
  1:27:12.725    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 19720397 reads
  1:27:40.510    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 24640136 reads
  1:28:03.526    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 29586589 reads
  1:28:43.223    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 34585251 reads
  1:29:09.358    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 39554907 reads
  1:29:47.975    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 44450978 reads
  1:30:11.153    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 47808399 reads
  1:30:11.153    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /ddn1/vol1/site_scratch/leuven/329/vsc32901/Peruvian_Dataset/D502_assembly/split_input/D502_1_HW3LYCCXX_L3_interleaved_PAIRED_clean_2.fastq
  1:30:49.583    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 52819079 reads
  1:32:28.224    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 67780825 reads
  1:35:33.074    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /ddn1/vol1/site_scratch/leuven/329/vsc32901/Peruvian_Dataset/D502_1_HW3LYCCXX_L3_SINGLETONS_clean.fq.gz
  1:36:14.845    21G / 21G   INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 100099212 reads processed
  1:36:15.735    10G / 21G   INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  1:37:37.421    10G / 21G   INFO    General                 (kmer_index_builder.hpp    : 127)   K-mer counting done. There are 1175948722 kmers in total.
  1:37:37.421    10G / 21G   INFO    General                 (kmer_index_builder.hpp    : 133)   Merging temporary buckets.
  1:38:15.373    10G / 21G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 314)   Building perfect hash indices
  1:38:52.579    10G / 21G   INFO    General                 (kmer_index_builder.hpp    : 150)   Merging final buckets.
  1:38:58.478    10G / 21G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 336)   Index built. Total 545298916 bytes occupied (3.70968 bits per kmer).
  1:38:58.503   672M / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 356)   Arranging kmers in hash map order
  2:04:38.749    18G / 21G   INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  2:19:17.059    18G / 21G   INFO    General                 (main.cpp                  : 155)   Extracting clusters


== Error ==  system call for: "['/vsc-hard-mounts/leuven-data/329/vsc32901/bioinformatic_tools/SPAdes-3.13.1-Linux/bin/spades-hammer', '/ddn1/vol1/site_scratch/leuven/329/vsc32901/Peruvian_Dataset/D502_assembly/corrected/configs/config.info']" finished abnormally, err code: -9

**Comment by asl** [comment]
Some improvements in this particular step are expected in SPAdes 3.14

**Comment by Arkadiy-Garber** [comment]
Great! Thanks for the update. Looking forward to that version.

**Comment by lroppolo** [comment]
Hi there, 

I am running MetaSPAdes (albeit as a module within another program called [MetaWRAP](https://github.com/bxlab/metaWRAP)), and I am getting the exact same error as the user above. I tried troubleshooting and requesting more RAM (I asked for 210GB of a 256GB max node), but that didn't help me and I'm still running into the same problem. Do you have any other suggestions for this issue that might clear it up? Here are the requested spades.log and params.txt for one of four assemblies I'm running. All four are getting the same error. 
[spades.log](https://github.com/ablab/spades/files/3827289/spades.log)
[params.txt](https://github.com/ablab/spades/files/3827291/params.txt)

_Originally posted by @lroppolo in https://github.com/ablab/spades/issues/349#issuecomment-552096282_

**Comment by asl** [comment]
SPAdes 3.14 was released, closing

**Comment by Elisa12345** [comment]
Hi, I am having a bit of trouble using the newest version of Metaspades 3.15.3 to prepare contigs for my paired end 150 bp metatranscriptome soil samples.  Using the execution command below, an error message is returned which is similar to error messages described above.  To help diagnose the problem, the params.txt and spades.log file are provided.  I hope that this information will help us solve the problem.  Thank you for helping us very much.  

Execution command
python metaspades.py --pe1-1 S_30_R1.ribodepleted.fastq --pe1-2 S_30_R2.ribodepleted.fastq -o S30SPADESOUT --memory 250

Error message
== Error ==  system call for: "['/pscratch/edangelo_uksr/Nsamsa2/SPADES/SPAdes-3.15.3-Linux/bin/spades-hammer', '/pscratch/edangelo_uksr/Nsamsa2/SPADES/SPAdes-3.15.3-Linux/bin/S30SPADESOUT/corrected/configs/config.info']" finished abnormally, OS return value: -7
None



[params.txt](https://github.com/ablab/spades/files/7022666/params.txt)
[spades.log](https://github.com/ablab/spades/files/7022667/spades.log)

**Comment by Arkadiy-Garber** [comment]
Elisa,

I am not sure about that error, as I haven't received that one before, but for a metatranscriptome I would recommend an assembler that is designed for transcript assembly. [Trinity](https://github.com/trinityrnaseq/trinityrnaseq) is a good one that I like to use for RNA seq data.

Cheers,
Arkadiy

**Comment by adler-sudo** [comment]
I also ran into an err code: -9 issue. I believe it was related to insufficient memory allocation as someone mentioned earlier. After allocating additional resources, I was able to successfully complete a metaspades run.
