### ISSUE TITLE
error code -6

### ISSUE THREAD

**Issue by celestialphineas** [ablab/spades#242]
Command line:

```shell
spades.py --careful --sc -t 8 -m 64 -1 mock/28625_R1_paired.fastq -2 mock/28625_R2_paired.fastq -o individual/results/28625
```

Error info:

```
omnigraph::PairInfoPathLengthUpperBound(size_t, size_t, double): Assertion `math::gr(answer, 0.)' failed
```

The total RAM available is 128GB.

[params.txt](https://gist.github.com/celestialphineas/0342a2e2cb64f775dc63617e5c64c4bb)

[spades.log](https://gist.github.com/celestialphineas/0a399a86a4858147157eaf699f44744a)

The issue is not reproduced when the `--sc` parameter is off.

Thank you so much for your work and help!

Edit: I've also validated my .fastq files. There's no problem with the raw data.

PS. I've validated that there is no problem with the raw .fastq files.

**Comment by asl** [comment]
SPAdes 3.6.2 is ancient and contains known problems (and I believe this one as well). Please upgrade to the latest version.
