### ISSUE TITLE
SPAdes-3.13.0 spades.py --test  with python3.7.1 environment fails with err code -6

### ISSUE THREAD

**Issue by mticlla** [ablab/spades#244]

**Comment by asl** [comment]
Please provide us spades.log and params.txt files as you were instructed in the error message just 2 lines above the github link.

**Comment by mticlla** [comment]
Hi there,

I installed SPADES 3.13.0, then I run the test 'spades.py --test' and it finished successfully but when I changed the python environment from 2.7 to 3.7.1 then the test failed. 

I noticed that in the params.txt memory limit was set to 0 when running with Python 3.7.1 but to 250 Gb when running with Python 2.7. I managed to run the test setting again the memory limit:
$spades.py -m 250 --test

Monica
