### ISSUE TITLE
rnaspades 3.13 finished abnormally, err code: -255 and err code: -6

### ISSUE THREAD

**Issue by yyan823** [ablab/spades#245]
Hello,

We're trying to assemble a set of transcriptomes using rnaspades (v. 3.13), they all failed with the same err code: 255 (also err code 24, please see log file for details). And there is one in another set failing with err code 6. Would you please help us to figure out how to solve these?

Thank you!

[err255-params.txt](https://github.com/ablab/spades/files/2869761/err255-params.txt)
[err6-spades.log](https://github.com/ablab/spades/files/2869759/err6-spades.log)
[err255-spades.log](https://github.com/ablab/spades/files/2869760/err255-spades.log)

**Comment by asl** [comment]
For error -255 the log reads:

```
  0:01:22.047    88M / 9G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: Too many open files. Error code: 24. File: /Users/katzlab/Desktop/Ying/Genome_Exploration/Plate6and7/Data/Transcriptomes/Trimmomatic_trimmed/LKH389_Loxodes_sp_small/tmp/spades_1tuR38/construction_J7aU9j/final_kmers_sDtJsM
```

Probably you'd need to increase the open file limit via ```ulimit -r```

As for the another case – how much free RAM is available for your SPAdes job?

**Comment by yyan823** [comment]
> For error -255 the log reads:
> 
> ```
>   0:01:22.047    88M / 9G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: Too many open files. Error code: 24. File: /Users/katzlab/Desktop/Ying/Genome_Exploration/Plate6and7/Data/Transcriptomes/Trimmomatic_trimmed/LKH389_Loxodes_sp_small/tmp/spades_1tuR38/construction_J7aU9j/final_kmers_sDtJsM
> ```
> Probably you'd need to increase the open file limit via `ulimit -r`
> 
> As for the another case – how much free RAM is available for your SPAdes job?

Thank you for quick response. I will try to increase the open file limit then. 

For the other case, I tried with 26G and 45G of RAM for SPAdes, and got the same error.

Thanks!

**Comment by asl** [comment]
Is this the real amount of free RAM available? Of just the memory limits you specified via -m option?

**Comment by yyan823** [comment]
This is the memory limits I set, and we do have 26-40G available at the time. Is this probably not enough?

also I reset the open file limit to 1024 (was 256), and got the same err code again, should I increase to even more?

Thank you!

**Comment by yyan823** [comment]
I just increase open file limit to 2048, now it stopped at err code 6, please see attached files...

Thank you!
[spades.log](https://github.com/ablab/spades/files/2871303/spades.log)
[params.txt](https://github.com/ablab/spades/files/2871304/params.txt)

**Comment by asl** [comment]
Well, now it's likely running out of RAM. How much free RAM is available for your SPAdes job?

**Comment by abdelmalick** [comment]
hi I worked on an assembly with spades for eukaryotic genome, is I ended up with an error (finish abnormally error code 255 . then I have the enceed a 2nd time increasing the ram is still not results
