### ISSUE TITLE
Error in munmap(): Cannot allocate memory

### ISSUE THREAD

**Issue by serjik92** [ablab/spades#247]
Hello, 

Is it a dig deal, if I have this kind of problem with memory allocation?

> .....................................................
> 235:40:15.024   553G / 1611G INFO    General                 (contig_output_stage.cpp   :  40)   Writing GFA to /DNA/metaspades//K55/assembly_graph_with_scaffolds.gfa
> 235:42:58.685   553G / 1611G INFO    General                 (contig_output.hpp         :  22)   Outputting contigs to /DNA/metaspades//K55/before_rr.fasta
> 235:45:11.429   553G / 1611G INFO    General                 (contig_output_stage.cpp   :  51)   Outputting FastG graph to /DNA/metaspades//K55/assembly_graph.fastg
> 236:27:59.218   561G / 1611G INFO    General                 (contig_output_stage.cpp   :  20)   Outputting FastG paths to /DNA/metaspades//K55/final_contigs.paths
> 236:43:17.580   553G / 1611G INFO    General                 (contig_output_stage.cpp   :  20)   Outputting FastG paths to /DNA/metaspades//K55/scaffolds.paths
> 236:57:51.641   553G / 1611G INFO   StageManager             (stage.cpp                 : 132)   STAGE == Second Phase Setup
> 236:57:51.641   553G / 1611G INFO    General                 (second_phase_setup.cpp    :  20)   Preparing second phase
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> .....................................................
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> 238:05:25.712   232G / 1611G INFO    General                 (second_phase_setup.cpp    :  28)   Moving preliminary contigs from /DNA/metaspades//K55/final_contigs.fasta to
>  /DNA/metaspades//K55/first_pe_contigs.fasta
> 238:05:25.713   232G / 1611G INFO    General                 (second_phase_setup.cpp    :  40)   Ready to run second phase
> 238:05:25.713   232G / 1611G INFO   StageManager             (stage.cpp                 : 132)   STAGE == Simplification
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> 238:05:25.848   221G / 1611G INFO    General                 (simplification.cpp        : 357)   Graph simplification started
> 238:05:25.848   221G / 1611G INFO    General                 (graph_simplification.hpp  : 634)   Creating parallel br instance
> 238:05:25.848   221G / 1611G INFO    General                 (simplification.cpp        : 362)   PROCEDURE == Simplification cycle, iteration 1
> 238:05:25.849   221G / 1611G INFO   Simplification           (parallel_processing.hpp   : 165)   Running Tip clipper
> 238:05:30.701   221G / 1611G INFO   Simplification           (parallel_processing.hpp   : 167)   Tip clipper triggered 35 times
> 238:05:30.701   221G / 1611G INFO   Simplification           (parallel_processing.hpp   : 165)   Running Bulge remover
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> .....................................................
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> <jemalloc>: Error in munmap(): Cannot allocate memory
> 238:13:34.040   221G / 1611G INFO   Simplification           (parallel_processing.hpp   : 167)   Bulge remover triggered 136151 times
> 238:13:34.040   221G / 1611G INFO   Simplification           (parallel_processing.hpp   : 165)   Running Low coverage edge remover
> 238:13:38.514   221G / 1611G INFO   Simplification           (parallel_processing.hpp   : 167)   Low coverage edge remover triggered 0 times
> 238:13:38.515   221G / 1611G INFO    General                 (simplification.cpp        : 362)   PROCEDURE == Simplification cycle, iteration 2
> .....................................................
> 

Am I need to reassemble the genome? 
Or it is just free memory problem which is not influence on the assemble process.

Logs, warnings, params att.

Thank you in advance!

[spades.log](https://github.com/ablab/spades/files/2882127/spades.log)
[warnings.log](https://github.com/ablab/spades/files/2882128/warnings.log)
[params.txt](https://github.com/ablab/spades/files/2882129/params.txt)

**Comment by asl** [comment]
This is pretty strange, but probably is fine – basically SPAdes tried to return free memory to your OS, but this operation failed.
