### ISSUE TITLE
Is possible to perform a "stand alone" mismatch correction for genomes after using metaspades?

### ISSUE THREAD

**Issue by pomidorku** [ablab/spades#250]
Hello,
I am new at using SPades.
I have two files (R1.fastq and R2.fastq, i.e., forward and reverse aka paired-end reads) from a single sequencing illumina run. These files contain DNA from several bacterial taxa (as detected by using Kaken2).
I would like to run metaspades to assemble those genomes. The manual states that metaspades cannot be used together with the "MismatchCorrector" option.
My question is, can mismatch correction be performed on the contigs or scaffolds (or any other intermediate step)? If so, what tool would you recommend for this purpose?
Regards

**Comment by pomidorku** [comment]
Hello,
I am new at using SPades.
I have two files (R1.fastq and R2.fastq, i.e., forward and reverse aka paired-end reads) from a single sequencing illumina run. These files contain DNA from several bacterial taxa (as detected by using Kaken2).
I would like to run metaspades to assemble those genomes. The manual states that metaspades cannot be used together with the "MismatchCorrector" option.
My question is, can mismatch correction be performed on the contigs or scaffolds/ or any other intermediate step)? If so, what tool would you recommend for this purpose?
Regards

**Comment by asl** [comment]
Hello

In general it does not make much sense to try to do mismatch correction for metagenomic assemblies. It is very hard to distinguish strain variation from true mismatches, so the correction could produce more harm that useful things.

**Comment by pomidorku** [comment]
OK, thank you very much for your advise.
The situation is the following. We had a target taxon, but the sequences seem to contain the target taxon, plus other taxa. 
I thought the way to address this difficult issue would be to run metaspades, and if we get a complete assembly of the target genome, try to run a mismatch correction on it.
Would you say this is a good way to salvage this (apparently contaminated) sequence run?
Any advise would be appreciated.
Regards,

**Comment by asl** [comment]
Well, you should not certainly expect to obtain "complete assembly of target genome" especially if your data contains close species. So, I would not bother about "mismatch correction" at all.

**Comment by pomidorku** [comment]
OK, I see. Thank you very much

**Comment by pomidorku** [comment]
Just to clarify, the contaminants classify to different bacterial domains from the target genome. The target is a Gammaproteobacteria, and the "foreign" bacteria classify to Alphaproteobacteria, Betaproteobacteria and the Terrabacteria group. That is the reason I thought this can still be salvaged.
But you have more experience than I do.
Thank you.
