### ISSUE TITLE
err code: 255

### ISSUE THREAD

**Issue by ucassee** [ablab/spades#253]
Hello developer,
       I use spade(3.13) to assemble my metagenome. I use the following command ：
`/data2017/share/tools/miniconda3/envs/metawrap-env/share/spades-3.13.0-0/bin/spades.py \
--pe1-1 B10L1_1.fastq      \
--pe1-2 B10L1_2.fastq     \
--pe1-1 B10L19_1.fastq   \
--pe1-2 B10L19_2.fastq   \
--pe1-1 B10L23_1.fastq   \
--pe1-2 B10L23_2.fastq   \
--careful \
-t 30 \
-m 800 \
-k 21,33,55,77,99,127 \
-o B10_all_careful
`
Assembling step is normal:     `Assembling finished. Used k-mer sizes: 21, 33, 55, 77, 99, 127 `   
BUT there is an error in the next step:
== Error ==  system call for: "['/data2017/share/tools/miniconda3/envs/metawrap-env/share/spades-3.13.0-0/bin/spades-corrector-core', '/dataNew/User/zhouyl/sediment/B10/CLEAN_READS/B10_all_careful/mismatch_cor
rector/contigs/configs/corrector.info', '/dataNew/User/zhouyl/sediment/B10/CLEAN_READS/B10_all_careful/misc/assembled_contigs.fasta']" finished abnormally, err code: 255
[params.txt](https://github.com/ablab/spades/files/2922721/params.txt)
[spades.log](https://github.com/ablab/spades/files/2922722/spades.log)
There is a strange thing I have to mention . If I don't use `--careful \`, spades run successfully.

I also want to know whether there are differences in the next three result:
`--pe1-1 B10L1_1.fastq      \
--pe1-2 B10L1_2.fastq     \
--pe1-1 B10L19_1.fastq   \
--pe1-2 B10L19_2.fastq   \
--pe1-1 B10L23_1.fastq   \
--pe1-2 B10L23_2.fastq   \`

`--pe1-1 B10L1_1.fastq      \
--pe1-2 B10L1_2.fastq     \
--pe2-1 B10L19_1.fastq   \
--pe2-2 B10L19_2.fastq   \
--pe3-1 B10L23_1.fastq   \
--pe3-2 B10L23_2.fastq   \`

`--pe1-1 allreads_1.fastq   (cat *1.fastq>allreads_1.fastq   )      \
--pe1-2 allreads_2.fastq    (cat *2.fastq>allreads_2.fastq   )    \`
Hope to your reply!

**Comment by asl** [comment]
> I also want to know whether there are differences in the next three result:

No, it should not be any differences, in this case SPAdes essentially does the same, but internally.

As for the issue – it seems that bwa failed, probably because the genome in question was larger than 2 Gb. We hope to address this issue in the next SPAdes versions.

**Comment by ucassee** [comment]
@asl Thanks for your reply!

>  it seems that bwa failed, probably because the genome in question was larger than 2 Gb

But, why I can run it successfully without `--careful`. They use the same size of metagenome. Anyway, wish you debug it in the next version!

**Comment by asl** [comment]
> But, why I can run it successfully without --careful.

Because it does not use bwa (which is a part of additional mismatch correction step)

**Comment by ucassee** [comment]
@asl  Oh,I get it . So,do you mean the bug is that bwa don't support the metagenome size (>2Gb) in this version?  whether I can divide the large metagenome into small part to use `--careful`

**Comment by asl** [comment]
>  So,do you mean the bug is that bwa don't support the metagenome size (>2Gb) in this version? whether I can divide the large metagenome into small part to use --careful

Oh... So, it seems you're assembling a metagenome in normal isolate multicell mode? This is certainly asking for a trouble since the latter expects the uniform coverage (which is certainly not a case in metagenomic mode).

You need to use metaSPAdes (--meta or metaspades.py). And --careful does not make much sense in metagenomic mode.

**Comment by ucassee** [comment]
In our previous test with other metagenomic data ,  --careful has the better performance in 'N50 and Max length .etc ' So this is why I want to use --careful. But maybe my experience is not suit for all metagenomic data.

**Comment by ucassee** [comment]
Hi @asl ,
     There are always some errors when I use `--careful  ` to run spades(3.13) to assembly metagenome. Could you please help me to handle them? Thanks~

[params.txt](https://github.com/ablab/spades/files/2973384/params.txt)
[spades.log](https://github.com/ablab/spades/files/2973385/spades.log)

**Comment by asl** [comment]
> In our previous test with other metagenomic data , --careful has the better performance in 'N50 and Max length .etc '
Well, N50 and the max length is not an appropriate value without a reference genome and when the length of the assemblies differ :). It's very easy to obtain larger N50 but with lots of misassembled contigs, so please be very careful with such "comparisons".

> There are always some errors when I use --careful to run spades(3.13) to assembly metagenome. 
Again, you're using normal multi-cell mode which expects *even* coverage of the dataset. As a results, you could easily obtain lots of misassemblies / absence of rare strains, etc.  It's highly likely in your case since the coverage is very low and your assembly is very fragmented.

As for this particular problem – you're having only one library longer than 127 bp. Consider using k-mer lengths up to 99.

**Comment by ucassee** [comment]
@asl Thanks for  your reply!
> It's very easy to obtain larger N50 but with lots of misassembled contigs, so please be very careful with such "comparisons".
So, do you mean metaspade module is more suitable way to assemble metagenomic data, even though  its 'N50' is shorter than `--careful`

**Comment by asl** [comment]
Certainly. Not that N50 is not connected with the quality of the assembly in general.

**Comment by dywang0323** [comment]
[Assembly_359-1-1_31568012_stdout.txt](https://github.com/ablab/spades/files/4335069/Assembly_359-1-1_31568012_stdout.txt)
Hello, I use the spades assembly metagenomics data, the error code id -11,  can you help me find out that is there anything run with it. I attached my log here, thank you very much!
[Assembly_359-1-1_31568012_stdout.txt](https://github.com/ablab/spades/files/4335073/Assembly_359-1-1_31568012_stdout.txt)
[Assembly_359-1-1_31568012_stdout.txt](https://github.com/ablab/spades/files/4335075/Assembly_359-1-1_31568012_stdout.txt)
[Assembly_359-1-1_31568012_stdout.txt](https://github.com/ablab/spades/files/4335077/Assembly_359-1-1_31568012_stdout.txt)
