### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by chenyj8** [ablab/spades#256]
Hi,

I found this error when using spades. Do you know what the problem is?

Thanks
[params.txt](https://github.com/ablab/spades/files/2942382/params.txt)
[spades.log](https://github.com/ablab/spades/files/2942383/spades.log)

**Comment by asl** [comment]
Hello

It seems that BayesHammer was unable to open one of input files:
```
spades-hammer: /spades/assembler/src/projects/hammer/hammer_tools.cpp:158: hammer::CorrectionStats hammer::CorrectPairedReadFiles(const KMerData&, const string&, const string&, std::ofstream*, std::ofstream*, std::ofstream*, std::ofstream*, std::ofstream*): Assertion `irsl.is_open()' failed.
```
Please make sure all input files are available during the whole SPAdes job duration
