### ISSUE TITLE
debruijn_graph::CoverageData::inc_coverage(int): Assertion `value >= 0 || coverage_ > unsigned(-value)' failed.

### ISSUE THREAD

**Issue by hjruscheweyh** [ablab/spades#257]
Dear SPAdes developers,

thank you very much for this great assembler. I'm currently using it to assemble >200 metatranscriptomes and got all but 3 assembled (v3.13). The last 3 all fail with the same error at the same position.

  0:41:08.401     4G / 22G   INFO    General                 (construction.cpp          : 508)   Filling coverage and flanking coverage from PHM
=== Stack Trace ===
[0x40ac28]
[0x6fb145]
[0x860afe]
[0x871f84]
[0x8d4539]
spades-core: /spades/assembler/src/common/assembly_graph/core/debruijn_data.hpp:38: void debruijn_graph::CoverageData::inc_coverage(int): Assertion `value >= 0 || coverage_ > unsigned(-value)' failed.

Could you let me know how I can resolve this issue please?

Thanks a lot,

Hans

I have attached the spades log for one sample. Let me know if you want to see the spades log from the 2 other samples.

[params.txt](https://github.com/ablab/spades/files/2955689/params.txt)
[spades.log](https://github.com/ablab/spades/files/2955691/spades.log)

**Comment by asl** [comment]
Hello

> I have attached the spades log for one sample. Let me know if you want to see the spades log from the 2 other samples.

Yes, please, so we will know whether it's the same issue or something different

**Comment by hjruscheweyh** [comment]
There you go

[spades1.log](https://github.com/ablab/spades/files/2956835/spades1.log)
[spades2.log](https://github.com/ablab/spades/files/2956836/spades2.log)
[spades3.log](https://github.com/ablab/spades/files/2956837/spades3.log)

**Comment by asl** [comment]
So, it seems like there are (some) k-mers with coverage exceeding 2^31. That's a lot and it's worth to check what's going on: untrimmed poly A, ribosomal DNA contamination or something else. If you'd share the data with us, then we could see what is the problem.

**Comment by hjruscheweyh** [comment]
Hi Anton,
thank you very much for the feedback. I checked for kmer counts and it looks like you're right. There are plenty of Poly-A of length 33

Do you think increasing the smaller kmer size will solve the issue without changing the results too much?

The current kmer sizes are [33, 49]. But I could increase it to [37, 49]

**Comment by andrewprzh** [comment]
Hi Hans-Joachim!

While rnaSPAdes does poly-A trimming by itself, it appears that there too many of them in you dataset. I'd suggest to trim poly-A tail prior to the assembly, for example using cutadapt
cutadapt  -a "T{30}" -a "A{30}" -A "A{30}" -A "T{30}"

Should not change the results a lot (since rnaSPAdes would throw them out anyway), or at least should not make them worse :)

**Comment by hjruscheweyh** [comment]
Hi!
Thats probably more elegant. But I feel a bit uneasy to change the input files as I already ran 200 assemblies with input files that were processed in the similar fashion. I will try to run with larger k now and let you know if that works.

Thanks,
Hans

**Comment by hjruscheweyh** [comment]
Hi!

So it failed again with giving just a higher k size. I had to fall back removing Poly A/T with cutadapt command. Removed half of the unmerged sequences. Now all 3 assemblies are beyond the point where they used to fail.

Thanks a lot for the help.
Hans
