### ISSUE TITLE
Building issues with GCC 7

### ISSUE THREAD

**Issue by satta** [ablab/spades#26]
While building Debian packages for SPAdes, we noticed that an extra line is necessary in `src/common/utils/segfault_handler.hpp` to make building with GCC 7's `g++` possible:

```diff
--- a/src/common/utils/segfault_handler.hpp
+++ b/src/common/utils/segfault_handler.hpp
@@ -12,6 +12,7 @@
 #include "boost/noncopyable.hpp"
 
 #include <signal.h>
+#include <functional>
 
 struct segfault_handler : boost::noncopyable {
     typedef std::function<void()> callback_t;
```

Please also see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853666 for the original Debian bug report.

**Comment by asl** [comment]
Thanks. This is already fixed in SPAdes development branch and will be a part of 3.11 release

**Comment by satta** [comment]
Excellent, thanks!
