### ISSUE TITLE
error code 255

### ISSUE THREAD

**Issue by jhernandez1409** [ablab/spades#260]
Hi, 

I am trying to run Spades but I get the same error no matter what parameters I used. I changed memory size, deleted "careful" option, set --phred-offset 33 or --phred-offset 64, and set -k or not and its the same error. I think the problem is hammer but I am not sure. Please can someone help me? Attached are the log files. 
[params.txt](https://github.com/ablab/spades/files/2974707/params.txt)
[spades.log](https://github.com/ablab/spades/files/2974708/spades.log)

Thanks,

JoJo

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The log reads:

```
  0:00:00.000     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/jojo/Desktop/Flavo/spades/1_S1.R1.fq.gz
  0:00:00.000     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/jojo/Desktop/Flavo/spades/1_S1.R2.fq.gz
  0:00:00.000     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/jojo/Desktop/Flavo/spades/1_S1.unpaired.R1.fq.gz
  0:00:00.000     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/jojo/Desktop/Flavo/spades/1_S1.unpaired.R2.fq.gz
  0:00:00.000     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 0 reads processed
```

So it seems that your input files are empty.

**Comment by jhernandez1409** [comment]
Hi,

Thank you for your prompt response. I will double check my files.

Thanks again,

JoJo
