### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by mshunjan** [ablab/spades#261]
Here's what I get when I run spades.py --test
 `Command line: ./spades.py       --test

System information:
  SPAdes version: 3.13.0
  Python version: 3.7.1
  OS: Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid

Output dir: /home/mshunjan/SPAdes-3.13.0-Linux/bin/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/mshunjan/SPAdes-3.13.0-Linux/share/spades/test_dataset/ecoli_1K_1.fq.gz']
      right reads: ['/home/mshunjan/SPAdes-3.13.0-Linux/share/spades/test_dataset/ecoli_1K_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/mshunjan/SPAdes-3.13.0-Linux/bin/spades_test/tmp
  Threads: 16
  Memory limit (in Gb): 11

======= SPAdes pipeline started. Log can be found here: /home/mshunjan/SPAdes-3.13.0-Linux/bin/spades_test/spades.log

===== Read error correction started.

== Running read error correction tool: /home/mshunjan/SPAdes-3.13.0-Linux/bin/spades-hammer /home/mshunjan/SPAdes-3.13.0-Linux/bin/spades_test/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===`

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

SPAdes manual () says:
```
SPAdes requires a 64-bit Linux system or Mac OS and Python (supported versions are Python2: 2.4–2.7, and Python3: 3.2 and higher) to be pre-installed on it
```

And we're seeing in your log:
```
OS: Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid
```
Linux subsystem in Windows is an unsupported platform and is known to be buggy.

**Comment by mshunjan** [comment]
For those who are having a similar issue and using Windows Subsystem for Linux, please do not give up. Ignore the reply above by asl, though this is not with any inclination of saying he was not helpful. SPAdes works fine in WSL and there is a simple fix if you get a similar error. Although the binaries for linux are not supported in WSL, you are able to compile the source code yourself. Go to the "Downloading and Compiling SPAdes source code" section of the SPAdes 3.13.0 Manual, and it will show you how. It's working fine for me.

**Comment by JFsanchezherrero** [comment]
Hi there, 

I am having the same problem but with Debian 10.3.

> System information:
>   SPAdes version: 3.14.1
>   Python version: 3.7.3
>   OS: Linux-4.19.0-8-amd64-x86_64-with-debian-10.3

I am going to try to compile it from scratch.

**Comment by antiafl** [comment]
Had exactly the same issue with WSL. Tried compiling SPAdes source code and it worked perfectly. Thanks for the help!

**Comment by LuffyLuffy** [comment]
don't forget to conda remove spades if you tried conda install spades.

then compile it from source.
