### ISSUE TITLE
spades-core: void coverage_model::KMerCoverageModel::Fit(): Assertion `cov_.size() > 10' failed.

### ISSUE THREAD

**Issue by SabeenR** [ablab/spades#262]
Hello,
I'm trying to assemble a large genome sequenced by Illumina. I have successfully assembled 3 other genomes from the same run but this genome is giving me an error.
See attached files.
[params.txt](https://github.com/ablab/spades/files/2980409/params.txt)
[spades.log](https://github.com/ablab/spades/files/2980410/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Do you want to write "small" instead of "large" because your input files contain only 122 reads?

The log reads
```
 Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```
