### ISSUE TITLE
error 255 - failed to determine read length

### ISSUE THREAD

**Issue by najoshi** [ablab/spades#266]
I'm getting this error with a bacterial assembly using two libraries of pacbio ccs reads and one library of paired-end illumina reads. Library #1 is the illumina reads.

Failed to determine read length for library #1. Check that not only merged reads are present.

Can't figure out what that means and how to fix it. Any help would be appreciated.
- Nik.

**Comment by asl** [comment]
Hello

Please attach your params.txt and spades.log files as you were instructed in the error message.

**Comment by najoshi** [comment]
[spades.log](https://github.com/ablab/spades/files/3007476/spades.log)
[params.txt](https://github.com/ablab/spades/files/3007477/params.txt)

**Comment by asl** [comment]
Well, I would suggest you to provide your ccs reads as "pacbio" library type.

**Comment by najoshi** [comment]
According to the manual, for pacbio ccs reads you should use the "-s" option.

**Comment by asl** [comment]
Sure, but here it seems they are of such poor quality, that all of them were "corrected out".

**Comment by najoshi** [comment]
Also, it's the illumina reads it has a problem with, not the pacbio ones.

**Comment by najoshi** [comment]
I see what you're saying about the pacbio... it's because the qualities are all stripped out and replaced with "!".

**Comment by asl** [comment]
Well... it doesn't seem to be a wise solution :)
