### ISSUE TITLE
Repeated stalling

### ISSUE THREAD

**Issue by AdamStuckert** [ablab/spades#27]
Hi,

First, thanks for developing this program. It is straightforward and relatively easy.

I keep running into the same issue though, in which I have assemblies stalling for days to weeks, typically at PathExtender 90% or Gap Closing. I originally tried a few assemblies on a local cluster, and assemblies with ~20gb per forward and reverse read stalled out indefinitely. I have since moved to a larger, more expensive cluster.

I currently am attempting a rather large assembly (forward and reverse reads are each 115 gb) and it has been stuck on PathExtender 90% for over 6 days now. I am running this on a 3 TB node with 42 threads, both of which are specified in my code:

```
rnaspades.py --only-assembler \
-o spades_full-node \
--threads 42 --memory 3000 -k 35 \
-1 $LOCAL/allreads_1P.fq \
-2 $LOCAL/allreads_2P.fq
```

Maximum memory used to date on this assembly is ~820 gb, but this has not increased during the final Path Extender step.

Any thoughts on this? 

Thanks,
Adam

**Comment by andrewprzh** [comment]
Dear Adam

We have fixed several performance bugs in our new version 3.11, which will be out within a day. 

You may also try --fast option (available only for rnaSPAdes), which may increase speed of the exSPAnder step, but result in slightly less accurate assemblies -- some short low-expressed transcripts may be missing.

Best regards
Andrey

**Comment by AdamStuckert** [comment]
Awesome, thanks @andrewprzh ! I'll try the new version when it comes out.

**Comment by AdamStuckert** [comment]
Version 3.11 is MUCH faster. Thanks for a good fix.
