### ISSUE TITLE
Err code -9

### ISSUE THREAD

**Issue by EmilyErin77** [ablab/spades#271]
Hello, 

I have no idea why my SPAdes is running abnormally (error code -9). It's currently allotted 1500gb of RAM. 

Any help and suggestions is extremely appreciated. 

[spades.log](https://github.com/ablab/spades/files/3022119/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The log reads:
```
<jemalloc>: Error in malloc(): out of memory. Requested: 1792, active: 57298386944
```

At the point of fail SPAdes used 53 Gb of RAM and your system failed to fulfill SPAdes request to allocate more. You may want to make sure there is indeed necessary amount of *free* RAM on your system.

PS: I would also suggest upgrading to the latest SPAdes 3.13.0.

**Comment by EmilyErin77** [comment]
I am wondering what I am doing wrong then as I allocated 1500gb of RAM on a 2TB server, any ideas?

**Comment by asl** [comment]
You may want to ask your system administrator about this. It doesn't seem that such amount of free RAM was available to SPAdes.

**Comment by EmilyErin77** [comment]
when I sinfo the server it says 1TB, but if it's on their end then I guess that is how I will proceed, thank you!
