### ISSUE TITLE
Hybrid assembly error code 6

### ISSUE THREAD

**Issue by broganmcgreal** [ablab/spades#272]
Hi there, 

Error running hybrid assembly with pacbio, paired end and mate pair libraries. 
[params.txt](https://github.com/ablab/spades/files/3028602/params.txt)
[spades.log](https://github.com/ablab/spades/files/3028604/spades.log)

Would appreciate any help with this.

**Comment by asl** [comment]
Hello

Your input PacBio reads are corrupted. In particular, for some read the length of sequence in the file does not correspond to the length of quality values.

**Comment by broganmcgreal** [comment]
Great, thanks for such a quick reply.

Cheers,

Brogan McGreal
Research Associate

T: +64 9 925 7096
F: +64 9 925 7001
E: brogan.mcgreal@plantandfood.co.nz
www.plantandfood.co.nz
The New Zealand Institute for Plant & Food Research Limited

Postal Address: Plant & Food Research
Private Bag 92169, Auckland Mail Centre, Auckland 1142, New Zealand
Physical Address: Plant & Food Research
120 Mt Albert Road, Sandringham, Auckland 1025, New Zealand

**Comment by broganmcgreal** [comment]
Thanks for your quick reply.
