### ISSUE TITLE
Error after mismatch_shall_not_pass.hp

### ISSUE THREAD

**Issue by jmtsuji** [ablab/spades#276]
Hello all,

I am hoping to use SPADES 1.13.0 for a short read (Illumina, 2 x 125 bp) metagenomic assembly. I first tried a normal assembly, but the run got stuck at the error correction step, as I think is described in #152 . I then tried to run with the `--only-assembler` flag, because I have already error corrected the reads using [tadpole](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/tadpole-guide/). In this second run, I ran into the following error, for the K=55 assembly (last lines of logfile pasted below):

```
  0:37:46.571    13G / 29G   INFO   StageManager             (stage.cpp                 : 132)   STAGE == Mismatch Correction
  0:37:46.571    13G / 29G   INFO    General                 (graph_pack.hpp            : 109)   Normalizing k-mer map. Total 119793892 kmers to process
  0:39:37.431    13G / 29G   INFO    General                 (graph_pack.hpp            : 111)   Normalizing done
  0:51:13.699    33G / 33G   INFO    General                 (mismatch_shall_not_pass.hp: 189)   Finished collecting potential mismatches positions


== Error ==  system call for: "['/Data/reference_databases/atlas/2.0.0/conda_envs/53ef875d/share/spades-3.13.0-0/bin/spades-core', '/Analysis/jmtsuji/Documents/02_Active_workfolders/49_190205_DNAseq_ELA1718_analysis/04a_atlas_2.0.6_vs4_JGI_metagenomes/Sep2016_L224_25m/assembly/K55/configs/config.info', '/Analysis/jmtsuji/Documents/02_Active_workfolders/49_190205_DNAseq_ELA1718_analysis/04a_atlas_2.0.6_vs4_JGI_metagenomes/Sep2016_L224_25m/assembly/K55/configs/mda_mode.info', '/Analysis/jmtsuji/Documents/02_Active_workfolders/49_190205_DNAseq_ELA1718_analysis/04a_atlas_2.0.6_vs4_JGI_metagenomes/Sep2016_L224_25m/assembly/K55/configs/meta_mode.info']" finished abnormally, err code: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.
```

The full log and params are available here:
- [spades.log.gz](https://github.com/ablab/spades/files/3047100/spades.log.gz)
- [params.txt.gz](https://github.com/ablab/spades/files/3047101/params.txt.gz)

Any idea of what might be causing this? I have followed the same protocol of using the `--only-assembler` flag for other samples and have finished the run without error.

Thanks for your work on this excellent tool.

Jackson

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. The place if crash is very strange. Does the problem reproduce if you'd rerun your SPAdes job?

**Comment by jmtsuji** [comment]
Indeed, I can reproduce the error when I run SPAdes again.

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
