### ISSUE TITLE
Spades not producing any output and getting killed.

### ISSUE THREAD

**Issue by mdimdadi** [ablab/spades#282]
When I run spades with --meta option with 32 threads and 280 GB memory, after some time, spades is getting killed. Nobody is killing it because only I have the sudo power. The log file ends with:
 0:05:40.957   644M / 644M  INFO   K-mer Counting           (kmer_data.cpp             : 294)   Processed 58229925 reads
  0:05:40.957   644M / 644M  INFO   K-mer Counting           (kmer_data.cpp             : 299)   Total 58229925 reads processed
  0:05:43.597   644M / 644M  INFO   K-mer Counting           (kmer_data.cpp             : 306)   Estimated 8298210057 distinct kmers
  0:05:43.618   132M / 644M  INFO   K-mer Counting           (kmer_data.cpp             : 311)   Filtering singleton k-mers
42 8 0
nslots: 17179869184
bits per slot: 8 range: 0000040000000000
  0:05:43.619    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /home/mdimdadi/14777R/FastQ/Passed_Reads/5+6+7_R1_paired.fastq
  0:38:25.840    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 326)   Processed 27571784 reads
  0:38:25.843    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /home/mdimdadi/14777R/FastQ/Passed_Reads/5+6+7_R2_paired.fastq
[params.txt](https://github.com/ablab/spades/files/3076375/params.txt)
[spades.log](https://github.com/ablab/spades/files/3076376/spades.log)

**Comment by asl** [comment]
Well, besides you with sudo power there is also, for example, out of memory killer. Though it's unlikely it is running here if there is indeed 280 Gb of *free* RAM available for your SPAdes job. I would suggest you to check system log – the information should be here.

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
