### ISSUE TITLE
Question: Parameters for TruSeq Small RNA library assembly

### ISSUE THREAD

**Issue by OnlyHigh** [ablab/spades#283]
Hi, 
Rigth now, I'm trying to assembly small RNA datasets, 
When I don't specify the -k (So far I'm specified 11, 21 and 29 for 36 nt reads)  get the error of [#216](https://github.com/ablab/spades/issues/216)
I was wondering what other parameters do I have to modify?
rnaSPADES is tested for small RNA libraries? 
Cheers, 
Luis Alfonso

**Comment by andrewprzh** [comment]
Dear Luis!
Unfortunately, we have never tested rnaSPAdes on small RNA data. Anyway, I'd not suggest to use very small k, 29 should be ok if the coverage of the library is not low. 

The error you are getting is fixed and the new release will be out very soon. If you'd like to try it as soon as possibly you can request an early access version by email.

Best
Andrey

**Comment by OnlyHigh** [comment]
Dear Andrey, 
I'll test it so, and eventually post on this issue how it went...

Ok, I'll wait anxiously the release, 
Cheers, 
Luis Alfonso.
