### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by mdimdadi** [ablab/spades#284]
I have been trying to tun spades for the last couple of days with different threads and memory limit. But every time it fails with the following error message like:
parameter: Threads: 15, Memory limit (in Gb): 190
error: <jemalloc>: Error in malloc(): out of memory. Requested: 24, active: 203121754112

parameter: Threads: 20, Memory limit (in Gb): 200
error: <jemalloc>: Error in malloc(): out of memory. Requested: 24, active: 213741731840

parameter: Threads: 20, Memory limit (in Gb): 250
error: <jemalloc>: Error in malloc(): out of memory. Requested: 39098286576, active: 229449400320

our memory in server: I have created 40GB swap memory to provide more memory after SPADES said I am short of 
[mdimdadi@rameshgoel Passed_Reads]$ free -g
              total        used        free      shared  buff/cache   available
Mem:            251           1         217           0          32         248
Swap:            42           0          41

Does this mean this dataset can't be run through SPADES with the RAM that I have?

Thanks,
Imdad

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Well, memory limit is not a magic option – it just specifies the upper memory limit SPAdes is unable to overcome. Should you need more RAM for assembling, it will obviously fail.
