### ISSUE TITLE
genome size for SPAdes?

### ISSUE THREAD

**Issue by YuanwenGuo** [ablab/spades#285]
Hello,
Since spades is one of the best hyrid assemblers currently available, we are very interested to assemble a highly repetitive plant genome about 1G size with its help. However, seems like spades is usually used for small genome size such as bacterial, we are wondering if spades will be suitable for our case? Currently we have about 50X illumina data and 10X Nanopore data.

Thank you!

Best,
Yuanwen

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Well, SPAdes will be able to process your data provided that you will have enough RAM and disk space. As for results – we have not tested SPAdes on such huge genomes thoroughly.
