### ISSUE TITLE
metagenomics assemble by spades--meta finished abnormally, err code -6

### ISSUE THREAD

**Issue by luernerliu** [ablab/spades#286]
Hi, I got some problems on spades -meta
I'm doing asemble my microbial metagenomics *.fq.gz data. But err code -6 was report:
Error log:
 18:14:51.203    83G / 84G   INFO    General                 (kmer_index_builder.hpp    : 150)   Merging final buckets.
 18:16:34.708    83G / 84G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 336)   Index built. Total 2687294100 bytes occupied (3.70965 bits per kmer).
 18:16:55.039     2G / 84G   INFO   K-mer Counting           (kmer_data.cpp             : 356)   Arranging kmers in hash map order
 18:56:47.518    89G / 89G   INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
 46:33:27.745    89G / 89G   INFO    General                 (main.cpp                  : 155)   Extracting clusters
<jemalloc>: Error in malloc(): out of memory. Requested: 46361988592, active: 225246707712
Issues:
== Error ==  system call for: "['/hwfssz4/BC_COM_FP/BC_CCP/Micro/software/miniconda2/share/spades-3.13.0-0/bin/spades-hammer','/hwfssz6/BC_TS_DA/F18FTSCCKF1669/METgnaM/3.Individual_Assemble/MetaSpades_out/SO109/corrected/configs/config.info']" finished abnormally, err code: -6
Params and log files:
[params.txt](https://github.com/ablab/spades/files/3101000/params.txt)
[spades.log](https://github.com/ablab/spades/files/3101001/spades.log)
Addition：
each of the end-paired (1.fq.gz and 2.fq.gz) data size: about 20G.
my parameters set:thread number 16 ;memory 250G. 
But the  Maximum # of threads to use (adjusted due to OMP capabilities) was just 2 in my log!!.
what is OMP capabilities? and is this related to the appearance of my error? 
Thanks!!

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

```what is OMP capabilities? and is this related to the appearance of my error?```
It is not connected to the error at all. This means that only 2 threads are allowed by your OpenMP runtime. You may want to ask your system administrator how to configure the OpenMP runtime.

As for the error – you're running out of RAM. At the time of crash SPAdes used 178 Gb of RAM and your system failed to fulfill SPAdes request to allocate 41 Gb more.
