### ISSUE TITLE
Err code 6: Out of Memory

### ISSUE THREAD

**Issue by hqtdave** [ablab/spades#287]
Hi all,

I am facing the issue of not having enough memory. Unlike other question about this issue, my report didn't mention anything about how much memory require
I am attaching the Spades log and params file for your convenience.
I tried to run the same assembly with 500GB Memory left on my computer.
Thanks in advance.
[params.txt](https://github.com/ablab/spades/files/3110767/params.txt)
[spades.log](https://github.com/ablab/spades/files/3110768/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Well, while you set SPAdes memory limit to 500 Gb, your OS still failed to fulfill SPAdes request for memory allocation. Also note that you're running this under Windows and this is not one of systems we do support.
