### ISSUE TITLE
(path_extender.hpp         : 885)   Processed 0 paths from 1745888 (0%)

### ISSUE THREAD

**Issue by Lucas-Maciel** [ablab/spades#288]
Hi,

I'm using SPAdes v3.13.0 to assembly a genome of 409Mb using 3 PE Illumina libraries and one PacBio FASTA file with 54Gbases. I used 400gb and 32 threads and it took 100 hours to get to the last 55-mer assembly. However, when I thought that it was finishing it started a process called path extender and it is going to take a life to end. Why is it taking so long and what can I do to improve that?

42:08:06.872   121G / 270G  INFO    General                 (extenders_logic.cpp       :  34)   resolvable_repeat_length_bound set to 10000
 43:04:11.670   121G / 270G  INFO    General                 (extenders_logic.cpp       : 472)   Using 3 paired-end libraries
 43:04:11.670   121G / 270G  INFO    General                 (extenders_logic.cpp       : 473)   Using 3 paired-end scaffolding libraries
 43:04:11.670   121G / 270G  INFO    General                 (extenders_logic.cpp       : 474)   Using 1 single read library
 43:04:14.068   121G / 270G  INFO    General                 (launcher.cpp              : 359)   Filling backbone edges for long reads scaffolding...
 43:04:14.068   121G / 270G  INFO    General                 (launcher.cpp              : 378)    with coverage
 43:04:16.781   121G / 270G  INFO   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  56)   With length cutoff: 500, median long edge coverage: 16.6622, and maximal unique coverage: 0.5
 43:04:16.781   121G / 270G  INFO   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  57)   Unique edges quantity: 223719, unique edges length 542206607, total edges length 663923433
 43:04:16.781   121G / 270G  INFO    General                 (launcher.cpp              : 381)   223719 unique edges
 43:04:16.781   121G / 270G  INFO    General                 (extenders_logic.cpp       : 360)   Creating scaffolding extender for lib 3
 43:04:16.801   121G / 270G  INFO   ExtensionChooser2015     (extension_chooser2015.hpp :  51)   ExtensionChooser2015 created
 43:04:20.357   121G / 270G  INFO    General                 (extenders_logic.cpp       : 386)   Using 1 long reads scaffolding library
 43:04:20.357   121G / 270G  INFO    General                 (launcher.cpp              : 420)   Total number of extenders is 11
 43:04:20.357   121G / 270G  INFO    General                 (path_extender.hpp         : 885)   Processed 0 paths from 1745888 (0%)
 43:54:12.664   123G / 270G  INFO    General                 (path_extender.hpp         : 883)   Processed 128 paths from 1745888 (0%)
 44:37:30.719   125G / 270G  INFO    General                 (path_extender.hpp         : 883)   Processed 256 paths from 1745888 (0%)
 46:21:59.443   129G / 270G  INFO    General                 (path_extender.hpp         : 883)   Processed 512 paths from 1745888 (0%)
 49:00:40.830   134G / 270G  INFO    General                 (path_extender.hpp         : 883)   Processed 1024 paths from 1745888 (0%)
 54:59:40.916   146G / 270G  INFO    General                 (path_extender.hpp         : 883)   Processed 2048 paths from 1745888 (0%)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. The times look reasonable given the genome size in question. Will you please provide us your spades.log file?

**Comment by Lucas-Maciel** [comment]
Thank you for your fast answer.

If it took 11 hours to run 2048 paths (0.001%) it will take a life to end. 

[spades.log](https://github.com/ablab/spades/files/3125161/spades.log)

**Comment by NathanWhelan** [comment]
Was this issue ever resolved? An assembly I am attempting with Spades 3.13.0 is also pretty much hanging at the path_extender step as above. The program is doing something, but at the current pace, the assembly may take years to finish.

**Comment by Lucas-Maciel** [comment]
I gave up using spades

**Comment by andrewprzh** [comment]
The genome is quite large for SPAdes (more than 200 MB) and the assembly graph seems to be very fragmented. We didn't test SPAdes on such data, so probably another assembler it a good choice for now.
I could only suggest to provide all 3 libraries as one since they have similar properties, but that may not give a significant speed increase.

**Comment by andrewprzh** [comment]
Probably doing long-read only assembly with e.g. Canu of Flye and polishing it with short-reads using e.g. Pilon would give better results.
