### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by trichoptera** [ablab/spades#289]
Hi,
I tried to run Spades with Illumina data but got the following error code:
== Error ==  system call for: "['/opt/SPAdes-3.13.0-Linux/bin/spades-core', '/home/jheckenhauer/LB1/Spades/K55/configs/config.info']" finished abnormally, err code: -6

Could you pleas elet me know what the problem might be?

Thanks in advance!
[spades.log](https://github.com/ablab/spades/files/3126551/spades.log)
[params.txt](https://github.com/ablab/spades/files/3126553/params.txt)

**Comment by asl** [comment]
The log reads:

<jemalloc>: Error in malloc(): out of memory. Requested: 256, active: 752021929984

Looks like your assembly is very fragmented and you ran out of RAM

**Comment by trichoptera** [comment]
Thanks!
