### ISSUE TITLE
Spades quits, err code: -9

### ISSUE THREAD

**Issue by laeserman** [ablab/spades#290]
I am running spades on a set of 32 samples. It worked well for 31 samples but it is failing on one sample. I have tried increasing the amount of memory, which has not solved the issue. Any help would be appreciated. I have attached the log and params files here.

Best,
Lauren
[params.txt](https://github.com/ablab/spades/files/3138661/params.txt)
[spades.log](https://github.com/ablab/spades/files/3138662/spades.log)

**Comment by asl** [comment]
You're likely running out of RAM. Please reopen if the problem reproduces with SPAdes 3.15.2
