### ISSUE TITLE
Question about untrusted contig usage

### ISSUE THREAD

**Issue by jolespin** [ablab/spades#292]
I have genomic reads that are specific to an organism (might have a small of contaminants).  What are your thoughts on using contigs from other assemblies in NCBI as untrusted-contigs for helping out with the assembly?  How different can they be for this to still be effective?

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The untrusted contigs option is not intended for reference-assisted assembly. So, the contigs should be of species of the exactly the same strain.

**Comment by jolespin** [comment]
Great to know!  I just wanted to make sure since this is a feature I just recently discovered . Thanks again.

**Comment by phiweger** [comment]
@asl say I assemble a genome w/ long-reads only e.g. using Flye. when I pass this to SPAdes with `--untrusted-contigs`, what happens to regions in the Flye assembly that are not covered by Illumina reads?

Thanks a lot for clarification!

**Comment by asl** [comment]
@phiweger They might close the coverage gaps. Though, I'd suggest to pass PacBio reads as well to produce hybrid assembly.
