### ISSUE TITLE
bug in restart from last

### ISSUE THREAD

**Issue by ucassee** [ablab/spades#294]
Dear developer,
       I use the following command to rerun spades. But it can't work. The error is 

> == Error ==  Please specify option (e.g. -1, -2, -s, etc) for the following paths: last

> /data2017/share/tools/miniconda3/envs/metawrap-env/share/spades-3.13.0-0/bin/spades.py \
--restart from last \
--pe1-1 B10L1_1.fastq  \
--pe1-2 B10L1_2.fastq \
--pe2-1 B10L19_1.fastq \
--pe2-2 B10L19_2.fastq \
--pe3-1 B10L23_1.fastq \
--pe3-2 B10L23_2.fastq \
-t 20 \
-m 800 \
-k 21,33,55,77,99,127 \
-o B10careful

What should I do to debug it. Hope to your reply~

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. 

The first step is carefully reading the documentation since the option is called ``--restart-from`` :)

I do agree that the error message is misleading, we hope to refactor all this a lot in the next SPAdes versions.
