### ISSUE TITLE
bwa in SPAdes

### ISSUE THREAD

**Issue by ucassee** [ablab/spades#295]
Dear developer,
       Running spade need bwa to correct assemble. But I find you use `spades-bwa index -a is` to create index for assembled_contigs.fasta .  But my assembled_contigs.fasta file is to big, so I want to use `bwa index -a bwtsw` to create indext. So I wonder where can I modify this option in your source code.  Hope to your reply! Thanks in advance~

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes

Yes, we are aware about this problem. Unfortunately, `bwtsw` cannot be used for shorter sequences among other problems. Anyway, SPAdes 3.14 will use `ropebwt` algorithm that will solve this problem.

**Comment by ucassee** [comment]
@asl ，thanks for your reply!
Hope you update SPAdes soon. But I still wonder whether can I try to  use `bwtsw` by modify your source code to assemble long sequences  and switch `spades-bwa index -a is` to assemble short sequences manually.

**Comment by asl** [comment]
Sure, SPAdes is open source, so you could certainly modify as you wish.

**Comment by ucassee** [comment]
@asl ,thanks for your reply!
I am a new python learner and  your python source code (spades.py) is a little bit complex for me.  I can't find the command line in spades.py to run bwa  . So I wish you could give me some help to modify the option of bwa!

**Comment by asl** [comment]
The bwa run is not in the python code. You need to change src/projects/corrector.main.cpp

**Comment by asl** [comment]
You have downloaded pre-built binaries. For this kind of change you need to compile SPAdes from sources.

**Comment by ucassee** [comment]
Hi @asl 
       Thanks for your patience and help! 
       I see a line ` string index_line = bwa_string + string(" index ") + "-a " + "is " + genome_screened`   in /src/projects/corrector/dataset_processor.cpp. I will try to modify this line  and compile SPAdes.
       By the way, If I want to remove the compiled SPAdes and recompile a new version. Can I `rm -rf`  the SPAdes-3.13.1 folder directly?

**Comment by asl** [comment]
Sure, why not?

**Comment by asl** [comment]
Looks like the issue was fixed
