### ISSUE TITLE
Spades error code 6

### ISSUE THREAD

**Issue by Vhpmveld** [ablab/spades#297]
I tried using Spades to run a assembly but got the following message:

== Error ==  system call for: "['/usr/lib/spades/bin/spades', '/mnt/StudentFiles/2018-19/vhpmveld/output_spades/BC08/K127/configs/config.info']" finished abnormally, err code: -6

when searching i found that allocating more memory might fix it but even adding "--memory 600" doesn't fix it?

[spades.log](https://github.com/ablab/spades/files/3177550/spades.log)
[warnings.log](https://github.com/ablab/spades/files/3177552/warnings.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

We're seeing in the log:
```
 0:00:03.077   127G / 489M  INFO    General                 (edge_index_builders.hpp   :  80)   Used 0 sequences.
  0:00:03.118   149G / 489M  INFO    General                 (kmer_index_builder.hpp    : 109)   Starting k-mer counting.
=
```

And indeed, the coverage of your input is so uneven, so at k =127 everything is disconnected. Given that:
```
  0:00:00.255    37G / 221M  INFO    General                 (kmer_splitters.hpp        : 310)   Used 24970 reads. Maximum read length 3610
  0:00:00.255    37G / 221M  INFO    General                 (kmer_splitters.hpp        : 311)   Average read length 477.672
```
It does not seems to be a typical Illumina multicel dataset from the genome or part of it.
