### ISSUE TITLE
SPAdes fails mismatch correction with error 255

### ISSUE THREAD

**Issue by JasperGeh** [ablab/spades#298]
Hey everyone!

I am happily using SPAdes since the start of my PhD but ran into trouble the first time yesterday.
SPAdes fails the assebly at the mismatch correction step and I am a bit at a loss. I looked at similar issues but did not find the cause. 
Our pipeline is unchanged since some time and always uses the raw reads straight from our MiSeq, does some light QC with fastp, and assembles with SPAdes. It still works fine on other reads, the issue is only with reads from our last seq run on my machine. A colleague using the same server with the same SPAdes install can assemble just fine.

I see a "Syntax error: "(" unexpected", "bwa failed", and "Failed to align paired reads" in the log but need some professional help at this point :) Thanks a bunch in advance!
[params.txt](https://github.com/ablab/spades/files/3177840/params.txt)
[spades.log](https://github.com/ablab/spades/files/3177841/spades.log)

**Comment by asl** [comment]
Dear Jasper,

Thank you for your interest in SPAdes.

The problem is caused by "(" in the path. So, if you'd move it out of path with special symbols, then everything should be fine.

**Comment by JasperGeh** [comment]
Thank you very much! That was the issue :)
