### ISSUE TITLE
Add a simple README.md

### ISSUE THREAD

**Issue by tseemann** [ablab/spades#3]
# Thanks for making the spades repo public.

A short `README.md` explaining the repo would be helpful, perhaps with links to the HTML manuals. 

Even better, use `gh-pages` branch to publish to https://ablab.github.io/spades

**Comment by asl** [comment]
It seems there are bunch of problems here:
- we are not planning to make a diverged copy of our website here, so gh-pages approach is not an option here. Only wikis might be useful
- README.md is shown only for the default branch. So we'd need to add empty 'master' branch, but... github does not allow pull requests for non-default branches...

**Comment by asl** [comment]
We converted our manual to .md and link it as README.md
