### ISSUE TITLE
== Error ==  exception caught: <class 'PermissionError'>

### ISSUE THREAD

**Issue by jdalsdurf** [ablab/spades#300]
running into errors and unsure how to trace back were error is.  

[params.txt](https://github.com/ablab/spades/files/3188586/params.txt)
[spades.log](https://github.com/ablab/spades/files/3188587/spades.log)

Thanks

**Comment by asl** [comment]
Hello

It seems you do not have necessary permissions to write to /mnt/y/Ion_Torrent_Experiments/20190516/SIV/relabled_reads/SIV_LS19-3319_10May_spades/corrected/configs/

Or there are some other I/O problems there

**Comment by sue93653** [comment]
Good day! 
I'm a beginner at using getorganelle and I encountered this issue regarding SPAdes see below:

ERROR: Error with running SPAdes: == Error ==  exception caught: <class 'PermissionError'>
WARNING: Pre-assembling failed. The estimations for embplant_pt-hitting base-coverage and word size may be misleading.

I'm seeking help from anyone who could give me some ideas to resolve this matter.  Thank you very much in advance.
