### ISSUE TITLE
Assembly finished but output contig file is empty

### ISSUE THREAD

**Issue by juschow** [ablab/spades#301]
Hi everyone,

I'm a beginner using spades 3.11.0 since March2019 , trying to practice doing some assemblies via getting SRA files from papers that i'm interested in.

What I have done:
1. Pulled SRA/ERR files using:
curl -O ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/ERR/ERR238/ERR2383823/ERR2383823.sra

2. fastq-dump --split-files --split-spot --skip-technical --minReadLen 64 --defline-seq @\$ac.\$si --defline-qual "+" ./ERR2383823.sra

3. fastq_pair ERR2383823_1.fastq ERR2383823_2.fastq 

4. spades.py --pe1-1 ERR2383823_1.fastq.paired.fq --pe1-2 ERR2383823_2.fastq.paired.fq -o ERR2383823_spades

From my previous experience I have never encounter this issue. The program runs fine but then all the contigs.fasta output are very small and QUAST said:
*ERROR! None of the assembly files contains correct contigs. Please, provide different files or decrease --min-contig threshold.*

Below is the warning messages I keep getting using different files.
=== Error correction and assembling warnings:
 * 0:00:07.370    96M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:00:09.449   100M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 27
 * 0:00:24.870   188M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 3
 * 0:00:15.447   380M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 2
 * 0:00:15.448   380M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 2
 * 0:00:21.646   408M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 37
 * 0:00:25.948   432M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 39
 * 0:00:26.538   444M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 36
 * 0:00:43.218   124M / 8G    WARN    General                 (pair_info_count.cpp       : 355)   Estimated mean insert size 253 is very small compared to read length 301

Would anybody know how to resolve this issue or any errors I should be aware of?

I've attached the log.file Appreciate for your time to help.

[spades.log](https://github.com/ablab/spades/files/3195504/spades.log)
[warnings.log](https://github.com/ablab/spades/files/3195505/warnings.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. It seems that the dataset in question has very uneven coverage, while you're assembling it in normal isolate mode that assumes even coverage of the genome. I would suggest you to try to figure our what are the problems with the input data.
