### ISSUE TITLE
The multi paired_end meta genome libraries

### ISSUE THREAD

**Issue by Duannai** [ablab/spades#302]
Dear developers,

In the manual, metaspades.py only supports a single paired-end library for metagenome.

I use spades.py for assembling multi-pair-end libraries for metagenome, but it finished with warnings, please check the attached files.
[warnings.log](https://github.com/ablab/spades/files/3196478/warnings.log)

[spades.log](https://github.com/ablab/spades/files/3196476/spades.log)

Could I merge (`cat >>`) all forward reads into a new forward read file (read_1), all reverse reads into a new reverse read file (read_2), and then a new forward_unpaired read file (read_3) and a new reverse_unpaired read file (read_4), and then use metaspades.py for assembling read_1 to read_4?

Best regards,

**Comment by asl** [comment]
Hello

You log shows assembly in multi-cell mode from the single library. How it is connected to your question?

You could only pull the libraries if they are similar (e.g. have the same insert size distribution). Assembling metagenome in normal isolate mode could yield arbitrary results because it expects even coverage of the dataset.

**Comment by Duannai** [comment]
Thank you for your prompt answer.

The libraries have the same insert size distribution, because they are sequences in one batch with the same treatment. So could I merge the multi-paired-end libraries into a single PE libraries, and then use the metaspades.py?

Look forward to Spades v3.12.

**Comment by asl** [comment]
SPAdes 3.12 was releases more than year ago. The current version is SPAdes 3.13.1

**Comment by Duannai** [comment]
sorry for this. 

Could I merge the libraries and use metaspades.py?
