### ISSUE TITLE
Ancient DNA sequencing data: paired-end or single reads?

### ISSUE THREAD

**Issue by alexhbnr** [ablab/spades#306]
I am running metaSPAdes on metagenomic sequencing data. The DNA that was used to construct the sequencing libraries was extracted from ancient samples, so the average read length is about 50 bp long. DNA was converted into a Illumina library and sequenced on a Illumina paired-end sequencing run of 2x76 bp. After removing adapters, the mates of sequencing pair always overlapped so that we usually merge the sequencing data for subsequent analyses.

When running metaSPAdes, I can provide the merged paired-end sequencing data via the option `-merged`, however metaSPAdes requires me to have a non-empty forward and reverse read file. Currently, I am stopped to provide the merged paired-end data, but only provided the non-merged forward and reverse sequencing data because in 9 out of 10 cases, metaSPAdes gets stuck on read error correction on the merged paired-end data. 

What is currently the best way to run metaSPAdes on sequencing data is in principle paired-end but only consists out of merged sequences? Treating them as non-merged and provide via the options `-1` and `-2` and let metaSPAdes determine the insertsizes as 0, or as single reads (`-s`)?

Thanks!

**Comment by asl** [comment]
Alex,

For merged reads you also need to provide the original unmerged data. metaSPAdes does not support single-end reads and insert size 0 will provide various issues.

So, if the run by default has problems – please provide us the spades.log from stuck run and we will try to figure out what could be done here.

**Comment by alexhbnr** [comment]
Thanks Anton for the fast reply. That is good to know.

For the stuck runs, I do not have any particular issues stated in the log files. It just is telling me that it processed the forward read and reverse read files and that is currently processing the merged ones. The machine is running under full load but no output is produced and it doesn't proceed further. I guess it is the same issue as #152.
