### ISSUE TITLE
Err -6 with enough memory available

### ISSUE THREAD

**Issue by lvelosuarez** [ablab/spades#308]
Hello, 
Ia m trying to assemble a metagenomic dataset with SPADES -meta. I got err while doing K55 (kmer index building). 
<jemalloc>: Error in malloc(): out of memory. Requested: 220223904, active: 282641563648
It is using  ~ 282 Gb and requesting 0.22 more. I set -m to 450Gb in the server, so I don't understand why it is not using the free RAM. 
Here is my params and log files. 
Thanks for the help
[spades.log](https://github.com/ablab/spades/files/3231560/spades.log)
[params.txt](https://github.com/ablab/spades/files/3231561/params.txt)

**Comment by asl** [comment]
Well, this is the error we've received from your OS – it was unable to fulfill SPAdes request for memory allocation. You need to make sure that it's indeed 450 Gb of RAM is available for your SPAdes job.
