### ISSUE TITLE
path_extender.hpp appears to only use a single thread

### ISSUE THREAD

**Issue by michaelbarton** [ablab/spades#31]
I've noticed that a spades assembly I've been running has been spending a long period of time in the path_extender.hpp stage, and that it's only using a single thread for this. Would there be a way to parallelise this?

The command I am using is:

```
/usr/local/bin/spades.py 
  --pe1-12 /tmp/tmp.fyFUUmBILZ/unmerged.fq.gz
  --s2 /tmp/tmp.AzsDG8zqLS/merged.fq.gz
  -o /tmp/tmp.rzr9ZjS78c
  --threads 8
  --phred-offset  33 
  --cov-cutoff  auto
  --careful
  -k 25,55,95
```

**Comment by asl** [comment]
Unfortunately, no. It would require full rewrite of repeat resolution step to make this parallel.

**Comment by asl** [comment]
Usually the long running time here is a result of e.g. fragmented assembly. If you'd upload spades.log file we may take a look whether everything is expected, or something is indeed wrong.

**Comment by michaelbarton** [comment]
It's unnormalized single cell data so I assume this is expected. I wouldn't usually assemble single cell data with normalising first, but this is for benchmarking purposes rather than a real-world use case. Here's the CPU graph:

![utilisation](https://user-images.githubusercontent.com/1142/30460932-0aeca508-996f-11e7-9800-f381a1fb8c8e.png)

I can still upload the log file if you would like.

**Comment by asl** [comment]
Yes, please

**Comment by michaelbarton** [comment]
Here is the log file output - https://gist.github.com/michaelbarton/f4f55227ac3b31605b6edc47b393c92a

**Comment by asl** [comment]
So... why you're assembling single cell data in multi-cell mode? Indeed, your assembly is very fragmented with graph N50 around ~100.

**Comment by michaelbarton** [comment]
> So... why you're assembling single cell data in multi-cell mode?

For benchmarking only, this is not how we usually assembly single cell data

**Comment by asl** [comment]
Well... then it seems you'd have to suffer ;)

**Comment by michaelbarton** [comment]
Yes I agree. Thanks for taking a look at this. :)
