### ISSUE TITLE
Scaffold.fa file and scaffolding mechanism

### ISSUE THREAD

**Issue by cssulliv** [ablab/spades#311]
Hi,

I recently did a metaSPades (v3.12.0) assembly for my metagenomic sequences and had a few questions regarding the scaffold output and the scaffolding mechanism utilized by metaSPades.

1) What specific scaffolding algorithm or method is used by metaSPades? How is it different from other scaffolders like SSPACE?

2) How would I be able to differentiate the contents of the contig.fa and scaffold.fa? I read from numerous bioinformatics sites that sometimes they might have the same content if there is nothing to scaffold. 

Thank you in advance for your assistance!

**Comment by asl** [comment]
Hello

> What specific scaffolding algorithm or method is used by metaSPades? How is it different from other scaffolders like SSPACE?
The repeat resolution module in SPAdes is called exSPAnder. It is described in several articles, including:
https://academic.oup.com/bioinformatics/article/30/12/i293/384610
https://academic.oup.com/bioinformatics/article/31/20/3262/195494
https://academic.oup.com/bioinformatics/article/32/7/1009/1743807

> How would I be able to differentiate the contents of the contig.fa and scaffold.fa? I read from numerous bioinformatics sites that sometimes they might have the same content if there is nothing to scaffold.

Indeed, if there is nothing to scaffold, then contigs and scaffolds could be the same (actually, in case of SPAdes and exSPAnder, there are always scaffolds and contigs are just scaffolds broken by stretches of 'N's).
