### ISSUE TITLE
The program was terminated by segmentation fault

### ISSUE THREAD

**Issue by Gin-Wang** [ablab/spades#312]
Hello,
I started to run SPAdes on my own PC, but it did not work well and it showed that 'The program was terminated by segmentation fault'. I serched and someone solve it by "-t 4", but I meet the same problem even set by "-t 1". 
I am quite new at this so I have no way of determining what is it that I am doing wrong.

Best,
Thank you.

Other parameters:
  Dir for temp files: /home/gin/xyp/spades/tmp
  Threads: 4
  Memory limit (in Gb): 31

======= SPAdes pipeline started. Log can be found here: /home/gin/xyp/spades/spades.log

===== Read error correction started. 

== Running read error correction tool: /home/gin/biosoft/SPAdes-3.13.1-Linux/bin/spades-hammer /home/gin/xyp/spades/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===

[spades.log](https://github.com/ablab/spades/files/3270479/spades.log)
[params.txt](https://github.com/ablab/spades/files/3270480/params.txt)

**Comment by Gin-Wang** [comment]
I met the same question when I input “./spades.py —test”. So it may be something wrong for my installing? But i have no idea about how to fix it.

**Comment by asl** [comment]
First step is pretty easy – just two lines above the one with github link there is a request to provide ```params.txt``` and ```spades.log``` files from the output directory.

**Comment by Gin-Wang** [comment]
thanks for your quick respondin! Sorry that i had not uploaded the flies, and now I have been update the comment, thanks for your help!

**Comment by Gin-Wang** [comment]
someone told me that Memory must be larger than 500G. 
I am quite new at this and thought that PC may work it out. So maybe a larger Memory may work well.

**Comment by Gin-Wang** [comment]
someone told me that Memory must be larger than 500G. 
I am quite new at this and thought that PC may work it out. So maybe a larger Memory may work well.

**Comment by yjiakang** [comment]
@Gin-Wang hello, have you resolved the problem? Would it be convenient to tell me how did you deal with the "The program was terminated by segmentation fault"

**Comment by Gin-Wang** [comment]
> @Gin-Wang hello, have you resolved the problem? Would it be convenient to tell me how did you deal with the "The program was terminated by segmentation fault"

i used a independent linux system and it worked. I think the error occured because of my wsl system. Or you may try not to install it by conda,  compiling SPAdes source code instead.

**Comment by ratatosk90** [comment]
Hi!

I'm having exactly the same problem... I cannot run even the test run. 

== Running: /home/joannak/Illumina/SPAdes-3.14.1-Linux/bin/spades-hammer /home/joannak/Illumina/SPAdes-3.14.1-Linux/bin/spades_test/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===

== Error ==  system call for: "['/home/joannak/Illumina/SPAdes-3.14.1-Linux/bin/spades-hammer', '/home/joannak/Illumina/SPAdes-3.14.1-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

Here are the requested files:

[spades.log](https://github.com/ablab/spades/files/4813394/spades.log)
[params.txt](https://github.com/ablab/spades/files/4813395/params.txt)

I'm looking forward to your answer! :)

**Comment by asl** [comment]
@ratatosk90 Please compile SPAdes from sources

**Comment by ratatosk90** [comment]
Worked like a charm! Thank you so much for your fast respose.

**Comment by ReneKat** [comment]
Hello All- @asl 
Unfortunately, I am having the same issue. I am running on WSL, SPAdes compiled from source. 
Attached are the logs:
[spades.log](https://github.com/ablab/spades/files/4875210/spades.log)
[params.txt](https://github.com/ablab/spades/files/4875211/params.txt)

**Comment by asl** [comment]
@ReneKat Given the directory name it does not seem you've compiled it from the sources.

PS: We neither support WSL, nor have possibility to test SPAdes there.

**Comment by ReneKat** [comment]
Hello @asl,
Thank you for your reply! 

This is how I installed:
cd ~/usr/local/bin
sudo wget http://cab.spbu.ru/files/release3.14.0/SPAdes-3.14.0-Linux.tar.gz
sudo tar -xzf SPAdes-3.14.0-Linux.tar.gz
#Add /usr/local/bin/SPAdes-3.14.0-Linux.tar.gz/bin to ~/.profile using nano

Is the installation different for WSL than for Linux? I suppose since WSL is not supported, that may not be a question that can be answered. 
Thanks anyways! 
Best,
Rene

**Comment by asl** [comment]
Well, as I said, you need to compile from sources. You just downloaded the pre-built binaries and extracted then. This is not going to work.

**Comment by yulia-my** [comment]
Hello, @asl! I have the same problem with --test
Previously I installed spades using this: https://github.com/ablab/spades/blob/spades_3.15.3/README.md#downloading-and-compiling-spades-source-code
[params.txt](https://github.com/ablab/spades/files/7852043/params.txt)
[spades.log](https://github.com/ablab/spades/files/7852044/spades.log)
Thank you!

**Comment by asl** [comment]
@yulia-my Please do not hijack closed issues. Your log reads:

```
  File "/home/yulia/miniconda3/envs/spades_env/share/spades-3.13.0-0/share/spades/spades_pipeline/support.py", line 245, in sys_call
    line = process_readline(proc.stdout.readline())
KeyboardInterrupt
```

So, you terminated SPAdes via Ctrl+C. And you're running 3.13.0, not 3.15.3

**Comment by apoorvaj92** [comment]
Had the same error. Was solved when i ran the command as:

```
sudo spades.py --test 
```
because as per https://askubuntu.com/questions/138407/what-is-a-segmentation-fault, "segmentation fault" is an error when the system cannot access some resources. Hope this helps.

**Comment by asl** [comment]
> because as per https://askubuntu.com/questions/138407/what-is-a-segmentation-fault, "segmentation fault" is an error when the system cannot access some resources. Hope this helps.

This is not quite true :)

**Comment by apoorvaj92** [comment]
@asl Oops, my apologies. Have deleted the comment for now. Though I was able to overcome the error by running the command as a root user. However I then noticed that in this instance it seems to run SPAdes 3.13 and not 3.15 (the one i attempted to install by compiling from source). So, it is possible the latter's installation was not proper and the solution is probably a clean reinstall :+1:

**Comment by dhuelgas95** [comment]
I have just run SPAdes v3.15.5 in WSL (Ubuntu 20.04). Before this, I uninstalled all the archives that were in the system when I installed SPAdes using conda and then followed the instructions that come in the SPAdes manual in the section of "Downloading and compiling SPAdes source code" (https://github.com/ablab/spades?tab=readme-ov-file#downloading-and-compiling-spades-source-code). It worked!
