### ISSUE TITLE
rnaspades input/output error

### ISSUE THREAD

**Issue by nickeener** [ablab/spades#314]
I'm trying to run rnaSPAdes on a cluster system using the following command:

`SPAdes/bin/rnaspades.py -o output --only-assembler -t 16 -m 500 -1 scratch/exposed_1_val_1.fq.gz -2 scratch/exposed_2_val_2.fq.gz`

and keep getting the same error. Here's the relevant portion of the log report:

>   1:17:04.549     8G / 9G    INFO    General                 (kmer_splitters.hpp        : 380)   Processed 140966634 kmers
  1:21:52.849     8G / 9G    INFO    General                 (kmer_splitters.hpp        : 380)   Processed 271043851 kmers
  1:31:53.223     8G / 9G    INFO    General                 (kmer_splitters.hpp        : 380)   Processed 537191266 kmers
  1:52:14.874     8G / 9G    INFO    General                 (kmer_splitters.hpp        : 380)   Processed 1077782423 kmers
  2:03:51.201     8G / 9G    INFO    General                 (kmer_splitters.hpp        : 385)   Used 1384382908 kmers.
  2:03:51.430    64M / 9G    INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  2:22:43.809    64M / 9G    INFO    General                 (kmer_index_builder.hpp    : 127)   K-mer counting done. There are 1382925384 kmers in total.
  2:22:43.809    64M / 9G    INFO    General                 (kmer_index_builder.hpp    : 133)   Merging temporary buckets.
  2:28:36.072    64M / 9G    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 314)   Building perfect hash indices
  2:33:07.633   784M / 9G    INFO    General                 (kmer_index_builder.hpp    : 150)   Merging final buckets.
  2:38:35.137   784M / 9G    ERROR   General                 (mmapped_reader.hpp        :  80)   unlink(2) failed. Reason: Input/output error. Error code: 5

> == Error ==  system call for: "['/nfs/thumper.galaxyproject.org/home/nzk5110/SPAdes/bin/spades-core', '/nfs/thumper.galaxyproject.org/home/nzk5110/output/K49/configs/config.info', '/nfs/thumper.galaxyproject.org/home/nzk5110/output/K49/configs/mda_mode.info', '/nfs/thumper.galaxyproject.org/home/nzk5110/output/K49/configs/rna_mode.info']" finished abnormally, err code: 255

I processed the reads myself with trim galore and ran using the `--only-assembler` param because after the processing step it kept reporting an unequal number of reads in the paired end files despite there being an equal number to start out. Any help would be greatly appreciated.

Thanks!

**Comment by asl** [comment]
>  processed the reads myself with trim galore and ran using the --only-assembler param because after the processing step it kept reporting an unequal number of reads in the paired end files despite there being an equal number to start out.

Both errors actually suggest severe problems with I/O subsystem. I would suggest to ask your system administrator about it.
