### ISSUE TITLE
no scaffolds.fasta file

### ISSUE THREAD

**Issue by ucassee** [ablab/spades#315]
Hello, I run spade SPAdes-3.13.0 to assemble. But there is no  scaffolds.fasta in the ouputfile.  I want to know whether there is some problem with my spade.
[spades.log](https://github.com/ablab/spades/files/3274691/spades.log)

**Comment by asl** [comment]
Sure, let us read the log together:

```
* 0:55:46.577    19G / 26G   WARN    General                 (pair_info_count.cpp       : 339)   Unable to estimate insert size for paired library #0
 * 0:55:46.577    19G / 26G   WARN    General                 (pair_info_count.cpp       : 345)   None of paired reads aligned properly. Please, check orientation of your read pairs.
 * 0:55:46.577    19G / 26G   WARN    General                 (repeat_resolving.cpp      :  63)   Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.
```

So, your paired-end reads are likely to be corrupted (e.g. left reads do not correspond to the right ones)
