### ISSUE TITLE
spades 3.13 hpc linux binary

### ISSUE THREAD

**Issue by aleuUH** [ablab/spades#323]

**Comment by aleuUH** [comment]
Hello 

I was wondering if you could release the spades hpc version? 

I am having trouble compiling it from the source code.

Thanks!

**Comment by asl** [comment]
Hello

No, we are not going to release the binaries, the hpcSPAdes should be linked with MPI runtime of your target platform.

**Comment by aleuUH** [comment]
No worries!

Will try it again.
