### ISSUE TITLE
Possible for up-to-date install for deployment in a dockerfile?

### ISSUE THREAD

**Issue by Firedrops** [ablab/spades#324]
I'm trying to write a dockerfile (debian-based) that automatically downloads and installs various toolkits, most of them are done via the `git clone`, `make` method. This ensures that whenever the docker container is initialized, the most updated main branch is used.

However, for SPAdes, I could only find instructions to download and un-tar the current version (3.13.1). While this works, it will eventually be outdated without continuous maintenance.

Is there an alternative download URL that always points the most updated version, or perhaps a `make` implementation of installation?

**Comment by asl** [comment]
Hello

As you might notice, SPAdes releases are also available on Github. Indeed, there is no "latest" version link, though, you could always clone the HEAD branch.

SPAdes used cmake for building, so you could generate makefiles, ninja scripts, etc.
