### ISSUE TITLE
Compile from source failed after ConsensusCore Error 2

### ISSUE THREAD

**Issue by Firedrops** [ablab/spades#325]
I have attempted to use `./spades_compile.sh` found in `spades/assembler/` from a fresh git clone, but it ended at 65% with this error: 
```
[ 65%] Built target ConsensusCore
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
Is there a log I can refer to for more information, or are the developers able to discern the issue from just this?

**Comment by asl** [comment]
The exact error could be easily seen in the console.

**Comment by Firedrops** [comment]
I'm not sure how to intepret and go about fixing this, could you please explain a little more?

**Comment by asl** [comment]
I cannot. There is no information that could be used to diagnose the issue and suggest possible solutions. For example, you can start by providing the build log.

**Comment by Firedrops** [comment]
I have bypassed requiring self-compilation but still always acquiring the latest version with this command
```
curl -s "https://api.github.com/repos/ablab/spades/releases" | grep download | grep Linux.tar.gz | head -n 1 | awk '{print $2}' | xargs curl -L -o /SPAdes.tar.gz
tar -zxvf SPAdes.tar.gz
rm SPAdes.tar.gz
mv SPAdes* SPAdes
export PATH=$Path:/SPAdes/bin/
```
