### ISSUE TITLE
Spades finished abnormally, err code: 255

### ISSUE THREAD

**Issue by taejung315** [ablab/spades#326]
Hi. 

I am keep getting a error message for my bacterial genome assembly. It is paired-ends reads

"Pair of read files /data/tuc
289/bacillus/2_trimmed/SRR2541537_1.trimmedP.fastq.gz and /data/tuc289/bacillus/2_trimmed/SRR2541537_2.trimmedP.fastq.gz cont
ain unequal amount of reads"

I am attaching .log file and param.txt here. 
Could you please let me know what might be the problem? 
Additionally, I used fastq-dump for splitting reads into fastq, and use trimmomatic for trimming sequences. 

[params.txt](https://github.com/ablab/spades/files/3340632/params.txt)
[spades.log](https://github.com/ablab/spades/files/3340633/spades.log)

Thanks!

**Comment by asl** [comment]
Well, the problem is that your files with left and right reads contain unequal number of reads and therefore are clearly corrupted – your left reads should correspond to the right reads.

Please make sure you're using paired-end aware trimmer
