### ISSUE TITLE
The selection criterion of metaspades to output final_contigs.fasta 

### ISSUE THREAD

**Issue by Duannai** [ablab/spades#329]
![WechatIMG896](https://user-images.githubusercontent.com/46950815/60673031-6e60a580-9ea9-11e9-85d0-3e48adb35c50.jpeg)
Please check the attached figure.

I assembled the metagenome data (PE 2×150) using metaspades.py, where the K-mers were set as 33,55,77,99 and 127.

The quality assessment of contigs.fasta files showed the N50 and L50 of K77 are better than those of K127, but K127 was the final_contigs.fasta recommended by Spades.

So which one you think should be used for the downstream analysis?

Thanks in advance!

**Comment by asl** [comment]
We suggest you to redo the assembly using either the default set of k-mer lengths, or at least not going beyond k = 77 for your data. We suggest to tweak the default set of k-mers if you're 100% sure what you're doing.

Note that N50 is not the indicator of "quality of the assembly" in any case. Also, all the files from intermediate steps should never be used for any downstream analysis, they are for assembler's internal use.
