### ISSUE TITLE
Question about minimal number of pair-end read to infer gaps/Ns

### ISSUE THREAD

**Issue by yyan823** [ablab/spades#331]
Hello,

I'm trying to map reads back to several scaffolds from SPAdes assembly (150bp pair-end reads, SPAdes 3.13.0, single cell de novo genome assembly) to have a better understanding of the genome structure, and wondering what is the minimal number of pair-end reads needed for inferring gaps/Ns for resolving scaffolds (if there is a number)?

A following long question is, during assembly process, for example, if there are 1000 reads (150bp)  that can build a 2,000 bp continuous sequence, in the middle of the sequence, there are 3 reads that the first 75 bp of the reads matched perfectly with the other reads/to the continuous sequence, but the rest 75bp are not matched at all (or matched 500bp away), would these 3 reads be taken account for assembly (e.g. build another contig/scaffold) or will just be discarded because the small number of reads?

I have this question because we are dealing with mixed two types genomes within one cell (soma and germline), somatic genome lacks some information from germline, analogical to exon and intron. We just want to get a better idea of if the assembly process would prefer to assemble one genome over another based on the relative ratio in certain area.

Any help will be much appreciated!
Thank you!
Ying

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. 

The first key step in the understanding of assembler is the knowledge, that SPAdes as many other de Bruijn graph based assemblers doest not operate on reads. Instead, it works with k-mer spectrum extracted from reads.

First of all, there is no "minimal number of pair-end reads needed for inferring gaps/Ns for resolving scaffolds".

Next, the situations you described, depending on the k-mer lengths might create different structures in the assembly graph. And depending on the settings (e.g. assembling in multi-cell mode that assumes even coverage) such artifacts might be considered as erroneous and removed from the graph during the simplification stage.

**Comment by yyan823** [comment]
Okay, thank you for explaining it. Thanks!
