### ISSUE TITLE
err code: -24 SPAdes/3.13.0

### ISSUE THREAD

**Issue by kayobianco** [ablab/spades#332]
Hello, I am trying to run metaSPAdes, and I keep running into this error code:

open(2) failed. Reason: Too many open files. Error code: 24. File: /Volumes/BIANCO-HD/Documentos/Illumina/Deborah/A1/spades_output_meta/tmp/spades_fYdugr/construction_YnQnOM/final_kmers_2oJ7hp

I attached the params.txt and spades.log file!
[params.txt](https://github.com/ablab/spades/files/3379304/params.txt)
[spades.log](https://github.com/ablab/spades/files/3379305/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

You log does not contain any errors. Wrong run?

**Comment by kayobianco** [comment]
Sorry,

I attached the wrong file.

I'm attaching the correct file this time.
[params.txt](https://github.com/ablab/spades/files/3382922/params.txt)
[spades.log](https://github.com/ablab/spades/files/3382923/spades.log)

**Comment by osvatic** [comment]
Hi all,

I have received the error in my most recent assembly. Is there a solution to this?

**Comment by asl** [comment]
@kayobianco 

The log reads:
```
  0:00:26.488    72M / 9G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: Too many open files. Error code: 24. File: /Volumes/BIANCO-HD/Documentos/Illumina/Deborah/A1/spades_output_meta/tmp/spades_fYdugr/construction_YnQnOM/final_kmers_2oJ7hp
```

You may want to increase the number of files opened via ulimit -f
