### ISSUE TITLE
Problems about the results

### ISSUE THREAD

**Issue by quliping** [ablab/spades#334]
I got my bacteria genomes successfuly, but I had some problems. I used checkM to check my genomes but the contamination are very high, about 30%-80% are contamination in every genome. Normally, the genome size should be about 4Mb, but most of my results from spades are more than 7Mb.  I'm sure that my bacteria isolates are not contaminated, because I sequenced the 16S rRNA gene and the results  are ok.
 Here is my command:
spades.py -1 ABC.1.fq.gz -2 ABC.2.fq.gz --careful -t 16 -m 64 -o result
What happened?

**Comment by asl** [comment]
No idea. Will you please at least provide the spades.log from these runs?

**Comment by quliping** [comment]
[spades.log](https://github.com/ablab/spades/files/3389917/spades.log)
[1-11spades.log](https://github.com/ablab/spades/files/3389923/1-11spades.log)
[1-42spades.log](https://github.com/ablab/spades/files/3389927/1-42spades.log)
Here are three of my spades.log files. I have more than 300 genomes and all of them have the same prombles.

**Comment by asl** [comment]
From what I could see in the logs, there might be some high-covered contamination there. If you'd attach contigs / scaffolds from one of these then we could advice what's there.

**Comment by quliping** [comment]
[samples.contigs.zip](https://github.com/ablab/spades/files/3389956/samples.contigs.zip)
OK. And here are the contigs of them. Thank you very much.

**Comment by asl** [comment]
As far as I can see, there is lots of short low-covered contigs. Though, some of them contains matches to the genomes that are similar to ones on contigs.

Will it be possible to attach assembly graph as well?

**Comment by quliping** [comment]
[assembly-graph.zip](https://github.com/ablab/spades/files/3389988/assembly-graph.zip)
Do you mean this files?

**Comment by asl** [comment]
Yes. So, there are plenty of low-covered sequences there that were probably were introduced either during the sequencing or library preparation steps. Fortunately, these sequences are not connected with the genome in question and does not influence the contiguity of the assembly.

You could filter out them using the coverage threshold option, however, I would strongly suggest you to analyze the library preparation and sequencing steps for any issues there.

Side note: you're having nice long plasmids there as it seems!
