### ISSUE TITLE
about dipSPAdes!

### ISSUE THREAD

**Issue by sunnycqcn** [ablab/spades#338]
Dear Developer,
We are much appreciated for your developed advanced genome assembly software. 
I saw the guideline about dipSPAdes 1.0 manual. dipSPAdes should be included in SPAdes.  However, I can not find dipSPAdes in the latest version. Did you remove out it or improve it?
If I want to use, could you tell me where can I get it?
Thanks,
Fuyou

**Comment by asl** [comment]
Per SPAdes 3.13.0 release notes (https://github.com/ablab/spades/releases/tag/v3.13.0), dipSPAdes was deprecated and therefore removed. In fact it was not maintained for years and had known issues.

If you're having any questions about it, I would suggest you to contact the corresponding authors of dipSPAdes paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4449708/)

**Comment by sunnycqcn** [comment]
thanks，
fuyou

发自我的 iPhone
