### ISSUE TITLE
SPades read from stdin

### ISSUE THREAD

**Issue by jregalad** [ablab/spades#34]
Is there a way to execute spades by reading form a data stream?

Eg:

zcat  reads.fq.gz | spades.py --12 -

or

zcat reads.fq.gz | spades.py --12 /dev/stdin

If not, any intentions of implementing it?

**Comment by asl** [comment]
No, there is no way to do this since SPAdes reads the input files multiple times. There are no plans to implement this either (essentially because the only solution would be simply to dump the data back to files and also because it conflicts with multiple libraries support).
