### ISSUE TITLE
compile Spades from source code

### ISSUE THREAD

**Issue by cassytha** [ablab/spades#340]
I am using ARCH linux. The linux binary version of Spades does not work on ARCH.

[hui@pi bin]$ pwd
/home/hui/software/SPAdes-3.13.1-Linux/bin
[hui@pi bin]$ ./spades-hammer
The program was terminated by segmentation fault
=== Stack Trace ===
Segmentation fault (core dumped)
[hui@pi bin]$ ./spades-core
Segmentation fault (core dumped)

So I downloaded the source code, extract it and run ./spades_compile.sh, but it is still not working properly.

[hui@pi bin]$ ./spades-hammer
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from /home/snikolenko/algorithmic-biology/assembler/src/hammer/config.inp
Exception caught /home/snikolenko/algorithmic-biology/assembler/src/hammer/config.inp: cannot open file for reading

[spades_compile.log](https://github.com/ablab/spades/files/3415342/spades_compile.log)

**Comment by asl** [comment]
Indeed, pre-built binaries might not be universally usable due to variety of distributions with unique restrictions, etc.

Please refer to SPAdes manual (http://cab.spbu.ru/files/release3.13.1/manual.html#sec3.2) for the information about running SPAdes, its cmdline options, etc.
