### ISSUE TITLE
run spades get error

### ISSUE THREAD

**Issue by alienzj** [ablab/spades#344]
Hello, great spades team member,
I have meet some problem when using spades to do assembly.
All information can be found on the bellow spades.log.

The spades.log is too big, then I upload it to dropbox, and you can download it from 
[spades.log](https://www.dropbox.com/s/2sieurc4j3d256h/spades.log?dl=1)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. It seems you're assembling a metagenome with highly uneven coverage in normal isolate mode that expects a single uniformly covered genome in the input.
