### ISSUE TITLE
finished abnormally, err core -6

### ISSUE THREAD

**Issue by jjurss** [ablab/spades#345]
I have collected lots of short, unpaired Illumina reads for assembly.  SPAdes has run on collections of reads from the same sequencing run before but will not run on this larger file.

[spades.log](https://github.com/ablab/spades/files/3468714/spades.log)
[params.txt](https://github.com/ablab/spades/files/3468715/params.txt)

**Comment by asl** [comment]
The log reads:

```
spades: /spades/src/common/io/reads/single_read.hpp:218: void io::SingleRead::Init(): Assertion `seq_.size() == qual_.size()' failed.
```

So, it's likely your input reads are corrupted (invalid FASTQ): the length of quality sequence for some read does not correspond to the length of nucleotide sequence.
