### ISSUE TITLE
Too many erroneous kmers -  a couple of questions

### ISSUE THREAD

**Issue by mstagliamonte** [ablab/spades#347]
Dear Spaders,

Thank you for this great program. I am trying to assemble some bacterial genomes, but at the end of the run I get the message:

```
=== Error correction and assembling warnings:
 * 0:00:56.688    20M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
```

Reducing the kmer sizes to 21,33 seems to remove some of the warnings. I thought at the beginning this might be due to the short insert size: we are running an Illumina machine with 250x2 , but  our libraries were probably too small., I can see at quality control that the raw reads length varies from 35 to 250. I trimmed to minimum length=100 prior to running SPADES and scanned for adapter contamination. 
I can see from Spades logs though that the samples from which I get warnings have a very similar insert size (400-450) as the ones I do not get warnings for.

I am going to run Quast to have a look at the assembly stats

**My questions:**

1) Do you think the issue is due to too short of an insert size? 
2) I read around regarding assembly quality measurement, but I am not sure what thresholds could be used to define an assembly "good enough" or not, therefore justifying another sequencing run. Would you have any suggestions for a rule of thumb?
I plan to do some whole genome phylogenetics with it. I guess I will take any scaffold > 500nt and see.

Thank you for your kind attention,
Max

**Comment by asl** [comment]
Please provide us your spades.log file from the run with the warning

**Comment by mstagliamonte** [comment]
Here it is:

[Report.spades.39683505_0.txt](https://github.com/ablab/spades/files/3487483/Report.spades.39683505_0.txt)
[Report.spades.39770884.txt](https://github.com/ablab/spades/files/3487484/Report.spades.39770884.txt)
[Report.spades33.39771427.txt](https://github.com/ablab/spades/files/3487485/Report.spades33.39771427.txt)


These are the logs for 3 different runs on the same dataset, using 3 different kmer options. 

Thank you for your kind attention, I appreciate it.

Best,
Max

**Comment by mstagliamonte** [comment]
Those were actually the report from the stout, I think they have the same content as the spades.log files.
Just in case, here they are:


[spades.kAUTO.log](https://github.com/ablab/spades/files/3487509/spades.kAUTO.log)
[spades.maxK33.log](https://github.com/ablab/spades/files/3487510/spades.maxK33.log)
[spades.maxK77.log](https://github.com/ablab/spades/files/3487511/spades.maxK77.log)

**Comment by mstagliamonte** [comment]
Hi, @asl ,

I am sorry to bother you. Did you have the chance to look at my files?

Kind Regards,
Max

**Comment by asl** [comment]
Hello

It seems you're having a bit uneven coverage, hence a warning. It has nothing to do with the insert size.

Unfortunately, there is no silver bullet in the evaluation of the quality of the assembly - you need to study the output and decide whether it's good enough, or not

**Comment by mstagliamonte** [comment]
Thank you for your kind help, I appreciate the feedback.

Kind Regards,
Max
