### ISSUE TITLE
Figuring out where `untrusted-contigs` are used

### ISSUE THREAD

**Issue by smsaladi** [ablab/spades#348]
Thanks for developing and providing this excellent software.

I've been providing sequences via `--untrusted-contigs` and in some cases this improves the overall quality metrics of my alignment. From the docs, I see that they're used for:

> Second option is used for less reliable contigs that may have more errors or contigs of unknown quality. These contigs will be used only for gap closure and repeat resolution.

I'd like to look more closely at where/which gaps were closed by using sequences given in `--untrusted-contigs`. Is there some output that spades logs that I could parse and specifically look at these regions? Is there another better way to figure this out?

Thanks in advance.

**Comment by asl** [comment]
There is no such obvious way, they participate in repeat resolution and gap closure in similar way as e.g. long noisy reads.

Though if you'd provide you spades.log file we might have some clues for this.

For now, the best way is to align one set contigs agains the other one.

**Comment by smsaladi** [comment]
Ah, I see -- ok, thank you.

Just in case, here is the `spades.log` file. Any insight you could share would be great!

[spades.log](https://github.com/ablab/spades/files/3497010/spades.log)

**Comment by asl** [comment]
Oh, wow.

First of all, I would suspect some uneven coverage of the dataset you're assembling. Is it so? Note that you're assembling in multi-cell mode that expects even coverage, so the results might be quite suboptimal (and I'm seeing there are several low covered contigs in the output).

The untrusted contigs indeed closed couple of coverage gaps, but I strongly believe they are not from the same species, so you need to be very careful – as misassemblies and misjoins are possible.

**Comment by smsaladi** [comment]
Thanks again for the response and sorry for the delay. I've been looking into the coverage and was planning on sharing when I got there. Might be a few days...
