### ISSUE TITLE
error -9：spades-hammer config.info

### ISSUE THREAD

**Issue by GH-Nana** [ablab/spades#349]
== Error ==  system call for: "['/lustre/home/shaoxiaona/miniconda3/share/spades-3.13.1-0/bin/spades-hammer', '/lustre/home/shaoxiaona/softwares/data_for_SPAdes/0016sp/corrected/configs/config.info']" finished abnormally, err code: -9
[params.txt](https://github.com/ablab/spades/files/3491327/params.txt)
[spades.log](https://github.com/ablab/spades/files/3491328/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

How much free RAM you're having for your SPAdes job?

**Comment by GH-Nana** [comment]
The job was run in a random node about 40-60G. I will try another node with more RAM. Thank you.

**Comment by asl** [comment]
Please reopen, if this is still an issue

**Comment by lroppolo** [comment]
Hi there, 

I am running MetaSPAdes (albeit as a module within another program called [MetaWRAP](https://github.com/bxlab/metaWRAP)), and I am getting the exact same error as the user above. I tried troubleshooting and requesting more RAM, but that didn't help me and I'm still running into the same problem. Do you have any other suggestions for this issue that might clear it up?
