### ISSUE TITLE
A question about --trusted-contigs / --trusted-contigs

### ISSUE THREAD

**Issue by Wyue1415** [ablab/spades#352]
I have 106 human intestinal samples and want to use spades for assembly, but I don't have enough computer resources (64 threads + 126G RMD). I want to assemble with 3 or 5 samples, and then use the --trusted-contigs or --trusted-contigs parameter to apply the assembly results to the next assembly. I want to know if the --trusted-contigs / --trusted-contigs parameter can be used in my pipeline. Thank you!

**Comment by asl** [comment]
Hello

You still have to assemble all your samples. Also, per SPAdes manual: "Note, that SPAdes does not perform assembly using genomes of closely-related species. Only contigs of the same genome should be specified."

**Comment by Wyue1415** [comment]
Thank for your reply. If I want to use this data for assembly, how much computing resources do I need?106 human gut samples, average 22,078,021 paired-end reads(2x150bp). Can I specify a smaller  k-mer sizes to reduce memory consumption? But will this affect the accuracy of the assembly?

**Comment by asl** [comment]
In general, you cannot estimate the memory consumption just from the input size. The memory consumption depends heavily on e.g. genome size, repeat content, error rate, etc. So, really, no idea. The only answer – you'd need to give it a try.
