### ISSUE TITLE
Save GFA for all k-mers in version 3.13.1

### ISSUE THREAD

**Issue by edgardomortiz** [ablab/spades#353]
I noticed the latest update doesn't save by default the assembly graph for each k-mer size, how can I enable this option?

Edgardo

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Why do you need this? The intermediate steps of SPAdes are quite special and the results are intended for internal consumption only.

**Comment by edgardomortiz** [comment]
I am assembling some chloroplast genomes using several k-mer sizes and I used this feature up to v. 3.13.0 to find out at what k-mer size the graph becomes disconnected. I found it useful as diagnostic for choosing the maximum k-mer size I can use in a dataset.

**Comment by asl** [comment]
Well, this is a bit wrong approach as I already said – the intermediate iterations of SPAdes are quite different from the last one.

**Comment by edgardomortiz** [comment]
Just to be clear, I am talking about these GFAs:
![kmer_gfas](https://user-images.githubusercontent.com/5767612/63838644-03e65600-c97e-11e9-86c1-3bd6fae4153d.png)
They look OK in Bandage, I was assuming that for example, if my graph became disconnected at K127 but it was a circular assembly in K113 then I could use the K113. In other words, if I ran Spades using all those k-mers up to K127 and the graphs looked OK until K113 then I didn't need to rerun the entire analysis to get the K113 (or K93, etc) graph because they were all produced in a single run.
The alternative in v. 3.13.1 would be to run the analysis until K93, if it still looks OK then I restart from there and add the next k-mer, and so on?
Thanks a lot for the help, and sorry for not being more clear before.

**Comment by asl** [comment]
Yes, you need to restart.
