### ISSUE TITLE
SPAdes 3.12.0 error - finished abnormally, err code: -6

### ISSUE THREAD

**Issue by mallen6** [ablab/spades#354]
Hello,
I'm assembling Illumina data from mixed microbial communities and one particular dataset keeps finishing abnormally (around k33) with err code: -6. 

"Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed. "
Somehow the k-mers are not staying sorted??

Other similar datasets I've run with the same parameters and same approx number of reads are completing fine.

params.txt
spades.log

Could you please help with this issue?
Thank you

**Comment by mallen6** [comment]
[params.txt](https://github.com/ablab/spades/files/3527854/params.txt)
[spades.log](https://github.com/ablab/spades/files/3527855/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The reason is some I/O problem that corrupted SPAdes intermediate files. JGI servers are well-known to have these errors, yes.
