### ISSUE TITLE
Troubles in runing spades.py --only-assemblers

### ISSUE THREAD

**Issue by XuanrZhang** [ablab/spades#356]
[spades.log](https://github.com/ablab/spades/files/3538121/spades.log)
[params.txt](https://github.com/ablab/spades/files/3538122/params.txt)

I am trying to use spades.py do assembly only on my single-Illumina-reads,but I met Error code:2.
It also happens, when I used other fasta files as input. The fasta files are single reads, so I use the parameter -s. 

== Error ==  system call for: "['/data/xuanzhan/Downloads/SPAdes-3.13.0-Linux/bin/spades-core', '/dev/shm/assembly/K55/configs/config.info']" finished abnormally, err code: 255

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:00.823    64M / 8G    WARN    General                 (simplification.cpp        : 479)   The determined erroneous connection coverage threshold may be determined improperly
======= Warnings saved to /dev/shm/assembly/warnings.log

=== ERRORs:
 * 0:00:00.532    64M / 8G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /dev/shm/assembly/tmp/spades_i9scl7ds/edge_index_E62uIw/kmers_raw_AsRtZM.1
 * 0:00:00.532    64M / 8G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /dev/shm/assembly/tmp/spades_i9scl7ds/edge_index_E62uIw/kmers_raw_AsRtZM.3
 * 0:00:00.532    64M / 8G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /dev/shm/assembly/tmp/spades_i9scl7ds/edge_index_E62uIw/kmers_raw_AsRtZM.6
 * 0:00:00.532    64M / 8G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /dev/shm/assembly/tmp/spades_i9scl7ds/edge_index_E62uIw/kmers_raw_AsRtZM.9
 * 0:00:00.532    64M / 8G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /dev/shm/assembly/tmp/spades_i9scl7ds/edge_index_E62uIw/kmers_raw_AsRtZM.5
 * 0:00:00.532    64M / 8G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /dev/shm/assembly/tmp/spades_i9scl7ds/edge_index_E62uIw/kmers_raw_AsRtZM.2
 * system call for: "['/data/xuanzhan/Downloads/SPAdes-3.13.0-Linux/bin/spades-core', '/dev/shm/assembly/K55/configs/config.info']" finished abnormally, err code: 255

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes. You're having only few dozen reads that do not seem to correspond to a genome or any part of it, so they do not assemble at all.

**Comment by XuanrZhang** [comment]
Wow! 
Thank you very much for your quick reply!
Is there a minimum of the number of reads to do an assemble?

**Comment by asl** [comment]
No, there is no minimum number of reads. But they do need to correspond to a (part of) genome

**Comment by XuanrZhang** [comment]
Thank you! I will try to run spades.py with a genome reference.
