### ISSUE TITLE
How to determine the -m value

### ISSUE THREAD

**Issue by RamaSravanimeduri** [ablab/spades#357]
I am trying to run a bacterial assembly and  it completes for  k21 and k33, but  with k55 it fails with an error

<jemalloc>: Error in malloc(): out of memory. Requested: 256, active: 266900340736

Could you please help in providing which values can we expect for m.

Thanking you,
Rama

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The -m option allows you to specify the hard memory limit that SPAdes will never overshoot. Should it require more RAM, it will simply crash.

The actual memory consumption depends on the coverage, error rate, genome size, repeat content, etc.

Though, I could hardly imagine that bacterial assembly would require 250 Gb of RAM like in your case. Something is wrong here.
