### ISSUE TITLE
plasmid spades read files?

### ISSUE THREAD

**Issue by sgl07007** [ablab/spades#361]
Hello, 

I know spades innately saves the corrected R1/R2 fastq files for the assembly. However, the plasmid spades program only uses a subset of those reads, so I was wondering if there is a flag or way to pull out just those reads used to build the plasmid assembly and place them in separate R1/R2 files?

Thanks!

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

plasmidSPAdes does not "uses a subset of those reads", it operates directly on the assembly graph (see https://academic.oup.com/bioinformatics/article/32/22/3380/2525610 for more information). So, no, there is no way to pull out those reads, you might simply align the reads back to the contigs and get rid of those that do not align with good IDY
