### ISSUE TITLE
Spades stoped with error code 255

### ISSUE THREAD

**Issue by difey** [ablab/spades#364]
Hello,

I am assembling a metagenomic using Spades. I have met two kinds of errors. Our meachine is a cluster using lustre as file system. Here are the logs. Any idea? 

[255.txt](https://github.com/ablab/spades/files/3614888/255.txt)
[-7.txt](https://github.com/ablab/spades/files/3614889/-7.txt)
[params.txt](https://github.com/ablab/spades/files/3614890/params.txt)

Thanks,
Jay

**Comment by asl** [comment]
Let us look into the logs together:

```
  3:27:31.184    44G / 140G  ERROR   General                 (kmer_splitters.hpp        : 145)   I/O error! Incomplete write! Reason: Input/output error. Error code: 5
```

So, the problem is I/O subsystem on your side.

**Comment by difey** [comment]
> Let us look into the logs together:
> 
> ```
>   3:27:31.184    44G / 140G  ERROR   General                 (kmer_splitters.hpp        : 145)   I/O error! Incomplete write! Reason: Input/output error. Error code: 5
> ```
> 
> So, the problem is I/O subsystem on your side.

So, any suggestion? Does spades have any request for Distributed File System?

Thanks

**Comment by asl** [comment]
This is the question for your system administrator. SPAdes somehow expects that writes to storage may not fail.
