### ISSUE TITLE
SPAdes finished abnormally with err code -6

### ISSUE THREAD

**Issue by AnaSofia94** [ablab/spades#366]
Hi,
I'm trying to run SPAdes, but it stops at the read error correction step with err code -6. You can find SPAdes log here.
I used this command:  spades.py -1 sample1.fastq -2 sample2.fastq --careful --cov-cutoff auto -o output/
Is there anything that I can do to fix this?
Thanks in advance.
[params.txt](https://github.com/ablab/spades/files/3641592/params.txt)
[spades.log](https://github.com/ablab/spades/files/3641593/spades.log)

**Comment by asl** [comment]
The log reads:

```
Verification of expression 'irsl.eof() && irsr.eof()' failed in function 'void hammer::CorrectPairedReadFiles(const KMerData&, size_t&, size_t&, size_t&, size_t&, const string&, const string&, std::ofstream*, std::ofstream*, std::ofstream*, std::ofstream*, std::ofstream*)'. In file '/build/spades-9nQbPn/spades-3.11.1+dfsg/src/projects/hammer/hammer_tools.cpp' on line 188. Message 'Pair of read files sample1.fastq and sample2.fastq contain unequal amount of reads'.
```

So, your input files are corrupted

**Comment by AnaSofia94** [comment]
Can't I use the fasq but already trimmed?

**Comment by asl** [comment]
You need to ensure that your trimming does not screw the pairedness of left and right reads.
