### ISSUE TITLE
Warning error: spades estimated mean insert size is very small compared to read length

### ISSUE THREAD

**Issue by cirodri1** [ablab/spades#368]
Dear all,

When running spades with the following parameters:

spades.py -t 50 --careful --cov-cutoff auto \
-o X_outputspades \
--pe1-1 X_R1.fq \
--pe1-2 X_R2.fq

 I obtained the following error in a few of my bacterial strains:
=== Error correction and assembling warnings:
 * 0:02:18.093   284M / 34G   WARN    General                 (pair_info_count.cpp       : 358)   Estimated mean insert size 104.494 is very small compared to read length 100

Is this a benign message, or would I need to take special precautions and re-run the assembly with different parameters?

Thank you for your help in advance.

Attached please find the spades.log file for one of the runs that had this warning message.

[spades.log](https://github.com/ablab/spades/files/3655324/spades.log)

**Comment by asl** [comment]
Well, the warning mens exactly what it is written there – the observed fragment length is almost identical to the read length.

This is the feature of your input and it's up to you to decide whether this is something expected, or there was a problem with your reads (e.g. fails during library construction, etc.). No assembler options could fix broken input.
