### ISSUE TITLE
RNAspades output folder did not generate the transcript fasta file

### ISSUE THREAD

**Issue by XiaoqiongGu** [ablab/spades#369]
Hi, I am using RNAspades to assemble RNA sequencing paired-end reads. However it turns out that there is no results in the output folder. Is it because my R1 and R2 max read length is not consistent (although they share the same quantity of sequencing reads)? Please see my attached spades log and parameters file. Thanks!
[spades.log](https://github.com/ablab/spades/files/3658817/spades.log)
[params.txt](https://github.com/ablab/spades/files/3658819/params.txt)

**Comment by andrewprzh** [comment]
Hi!
The log seems to be truncated, it stops right after the parameters. If it is really like this, probably rnaSPAdes fails to compute K-mer sizes - we have never tried it on such short reads. Different lengths for left and right reads is ok.
I'd suggest to add -k 29 option and see how it goes, but in general don't expect good assembly out of such short reads.
Best
Andrey
