### ISSUE TITLE
SPAdes on Linus failed to run --test

### ISSUE THREAD

**Issue by claudiavaga** [ablab/spades#370]
I have installed SPAdes on Ubuntu for Windows and when I try to run the test I get this:

System information:
  SPAdes version: 3.12.0
  Python version: 2.7.15
  OS: Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid

Output dir: /home/claudiavaga/SPAdes-3.13.1-Linux/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/claudiavaga/miniconda2/envs/phyluce/share/spades-3.12.0-1/share/spades/test_dataset/ecoli_1K_1.fq.gz']
      right reads: ['/home/claudiavaga/miniconda2/envs/phyluce/share/spades-3.12.0-1/share/spades/test_dataset/ecoli_1K_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/claudiavaga/SPAdes-3.13.1-Linux/spades_test/tmp
  Threads: 16
  Memory limit (in Gb): 7

======= SPAdes pipeline started. Log can be found here: /home/claudiavaga/SPAdes-3.13.1-Linux/spades_test/spades.log

===== Read error correction started.

== Running read error correction tool: /home/claudiavaga/miniconda2/envs/phyluce/share/spades-3.12.0-1/bin/spades-hammer /home/claudiavaga/SPAdes-3.13.1-Linux/spades_test/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===

someone know what is the problem?
Thank you!

**Comment by asl** [comment]
Hello

Linux subsystem in Windows cannot run pre-built binaries. You'd need to compile from sources.
