### ISSUE TITLE
Assembling not working

### ISSUE THREAD

**Issue by syned13** [ablab/spades#371]
I'm trying to do some assembling and I'm getting the following error.
/usr/lib/spades/bin/spades(_ZN13MMappedReaderC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbmlm+0x39d) [0x5648d7482b2d]
/usr/lib/spades/bin/spades(_ZN24MMappedRecordArrayReaderImEC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmblm+0x1b) [0x5648d75e323b]
/usr/lib/spades/bin/spades(_ZN5utils15KMerDiskCounterI10RuntimeSeqILm128EmENS_17kmer_index_traitsIS2_EEE10MergeKMersERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_j+0x62) [0x5648d75f20e2]
/usr/lib/spades/bin/spades(+0x4064c1) [0x5648d75f34c1]
/usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1695e) [0x7efc2f56495e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7efc2f11e6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7efc2ee4788f]
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t)'. In file '/build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/io/kmers/mmapped_reader.hpp' on line 99. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t)'. In file '/build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/io/kmers/mmapped_reader.hpp' on line 99. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
spades: /build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/io/kmers/mmapped_reader.hpp:99: MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t): Assertion `(intptr_t) MappedRegion != -1L' failed.

== Error ==  system call for: "['/usr/lib/spades/bin/spades', '/home/denys/INTEC_ensamblaje/SRR522415_salida_spades/K41/configs/config.info']" finished abnormally, err code: -6

Here are the parameter and log files:
[params.txt](https://github.com/ablab/spades/files/3677828/params.txt)
[spades.log](https://github.com/ablab/spades/files/3677829/spades.log)

**Comment by asl** [comment]
The log reads:
```
Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So, you're running out of RAM
