### ISSUE TITLE
Spades finished abnormally, err code -11

### ISSUE THREAD

**Issue by borjaf696** [ablab/spades#373]
Hi,
I am sure this error is because of my cluster and not because of SPAdes. I am trying to do some test with metaSPAdes and SPAdes but they are not working and they are spitting this message.
Command line: spades.py -1      /home/bfreire/Datasets/Helsinki2.0/10-strain-HCV-20000x/read1.fastq     -2      /home/bfreire/Datasets/Helsinki2.0/10-
strain-HCV-20000x/read2.fastq   -o      /home/bfreire/SPAdes-3.11.1-Linux/bin/new/10HCV -t      32      --debug

System information:
  SPAdes version: 3.11.1
  Python version: 2.7.15
  OS: Linux-4.19.0-5-amd64-x86_64-with-debian-10.0

Output dir: /home/bfreire/SPAdes-3.11.1-Linux/bin/new/10HCV
Mode: read error correction and assembling
Debug mode is turned ON

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic da
taset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/bfreire/Datasets/Helsinki2.0/10-strain-HCV-20000x/read1.fastq']
      right reads: ['/home/bfreire/Datasets/Helsinki2.0/10-strain-HCV-20000x/read2.fastq']
      interlaced reads: not specified
      single reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed (with gzip)
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/bfreire/SPAdes-3.11.1-Linux/bin/new/10HCV/tmp
  Threads: 32
  Memory limit (in Gb): 62

======= SPAdes pipeline started. Log can be found here: /home/bfreire/SPAdes-3.11.1-Linux/bin/new/10HCV/spades.log

===== Read error correction started.

== Running read error correction tool: /home/bfreire/SPAdes-3.11.1-Linux/bin/hammer /home/bfreire/SPAdes-3.11.1-Linux/bin/new/10HCV/corrected/configs/
config.info

The program was terminated by segmentation fault
=== Stack Trace ===

== Error ==  system call for: "['/home/bfreire/SPAdes-3.11.1-Linux/bin/hammer', '/home/bfreire/SPAdes-3.11.1-Linux/bin/new/10HCV/corrected/configs/con
fig.info']" finished abnormally, err code: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

As you can see the failure is just at the start of the program. I have tried both source and binaries, and binaries spit this issue while sources give me:
Building SPAdes from refs/heads/Test, sha: N/A
-- Looking for include file features.h
-- Looking for include file features.h - found
-- Looking for include file sys/cdefs.h
-- Looking for include file sys/cdefs.h - found
-- Looking for atomic_fetchadd_long
-- Looking for atomic_fetchadd_long - not found
-- Looking for OSAtomicAdd64
-- Looking for OSAtomicAdd64 - not found
-- Looking for OSSpinLockLock
-- Looking for OSSpinLockLock - not found
-- Looking for _malloc_thread_cleanup
-- Looking for _malloc_thread_cleanup - not found
-- Looking for _pthread_mutex_init_calloc_cb,
-- Looking for _pthread_mutex_init_calloc_cb, - not found
-- Looking for sbrk
-- Looking for sbrk - found
-- Performing Test JEMALLOC_TLS_MODEL_SUPPORTED
-- Performing Test JEMALLOC_TLS_MODEL_SUPPORTED - Success
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Performing Test JEMALLOC_TLS
-- Performing Test JEMALLOC_TLS - Success
-- Looking for memalign
-- Looking for memalign - found
-- Looking for valloc
-- Looking for valloc - found
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of intmax_t
-- Check size of intmax_t - done
-- Looking for open
-- Looking for open - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file signal.h
-- Looking for include file signal.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file cxxabi.h
-- Looking for include file cxxabi.h - not found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file mach/mach.h
-- Looking for include file mach/mach.h - not found
-- Looking for include file link.h
-- Looking for include file link.h - found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Looking for shm_open
-- Looking for shm_open - not found
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Configuring incomplete, errors occurred!

I have used SPAdes and metaSPAdes in the past and in the same cluster... but they have updated the OS and suddenly it stopped working...
Maybe, some hint I am in a bit hurry.
Thanks in advice

**Comment by asl** [comment]
Hello

Will you please post the full build log?

**Comment by borjaf696** [comment]
I will attach both logs here.
Thanks!
[CMakeOutput.log](https://github.com/ablab/spades/files/3717426/CMakeOutput.log)
[CMakeError.log](https://github.com/ablab/spades/files/3717427/CMakeError.log)

**Comment by asl** [comment]
And the console output, please?

**Comment by borjaf696** [comment]
Attached 
[screen-log.txt](https://github.com/ablab/spades/files/3717873/screen-log.txt)

**Comment by asl** [comment]
Something is horrible wrong as there are no errors in the logs besides the last one...

**Comment by borjaf696** [comment]
Yeah! That was what I assumed when I read the logs and I did not see anything... I think that the problem is related with dependencies or maybe with the OS version or something similar... Thanks for everything. Fortunately, I had a backup plan already running :S
Thanks!
