### ISSUE TITLE
v3.13.1 - traceback hard to interpret

### ISSUE THREAD

**Issue by cmeesters** [ablab/spades#375]
Hi,

I am currently doing a few test runs for a user on our cluster and got this traceback (btw: a really nice feature to embed tracebacks in neatly formatted log files!):

`0:39:02.114    12G / 142G  INFO    General                 (extenders_logic.cpp       : 278)   Estimated coverage of library #0 is 1.7992
  0:39:02.131    12G / 142G  INFO    General                 (extenders_logic.cpp       : 278)   Estimated coverage of library #0 is 1.7992
  0:39:02.233    12G / 142G  INFO    General                 (extenders_logic.cpp       : 278)   Estimated coverage of library #1 is 9.39321
=== Stack Trace ===
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZN5utils16print_stacktraceEv+0x38) [0x5a04b8]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZNK11path_extend18ExtendersGenerator14MakePEExtenderEmb+0x815) [0x8004a5]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZNK11path_extend18ExtendersGenerator18MakeBasicExtendersEv+0x545) [0x802d15]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZN11path_extend18PathExtendLauncher18ConstructExtendersERKNS_16GraphCoverageMapERNS_17UsedUniqueStorageE+0xaf) [0x7de99f]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZN11path_extend18PathExtendLauncher6LaunchEv+0x16a) [0x7dffba]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZN14debruijn_graph16RepeatResolution3runERNS_10graph_packINS_13DeBruijnGraphEEEPKc+0x1827) [0x6578c7]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZN6spades12StageManager3runERN14debruijn_graph10graph_packINS1_13DeBruijnGraphEEEPKc+0xb0) [0x6eb170]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(_ZN6spades15assemble_genomeEv+0xf7b) [0x59f53b]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core(main+0x3d8) [0x59a328]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2b92d30383d5]
/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core() [0x59dc1f]
spades-core: /dev/shm/SPAdes/3.13.1/GCC-8.3.0/SPAdes-3.13.1/src/common/modules/path_extend/weight_counter.hpp:306: path_extend::CoverageAwareIdealInfoProvider::CoverageAwareIdealInfoProvider(const Graph&, const std::shared_ptr<path_extend::PairedInfoLibrary>&, size_t): Assertion `read_length_ > g_.k()' failed.

== Error ==  system call for: "['/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core', '/lustre/miifs03/scratch/m2_zdvhpc/meesters/somedir/K127/configs/config.info']" finished abnormally, err code: -6

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:03:25.919     3G / 72G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 3
 * 0:04:09.465     3G / 107G  WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 2
======= Warnings saved to /lustre/miifs03/scratch/m2_zdvhpc/meesters/somedir/warnings.log

=== ERRORs:
 * system call for: "['/cluster/easybuild/broadwell/software/bio/SPAdes/3.13.1-GCC-8.3.0/bin/spades-core', '/lustre/miifs03/scratch/m2_zdvhpc/meesters/somedir/K127/configs/config.info']" finished abnormally, err code: -6
`

There are a number of things:

- The error message about the config file is given twice.
- It is unclear whether SPades tries to open or read the config.info in question.
- There was no file system issue during the job and I can read the config.info.
- The traceback should be caught resulting in an appropriate error message, shouldn't it? (In this case a translation would be nice - is there in issue with the input?)

Best regards,
Christian

**Comment by cmeesters** [comment]
PS I am sorry for the unbalanced formatting.

**Comment by asl** [comment]
The stacktraces are meant for developer consumption and not for end users. Also, they are issued when something bad is already happened and we should show as much information as possible without having second error in the row. There are not many options available for fancy formatting, etc.

Now back to the exact message:

> The error message about the config file is given twice.

Nothing in the error message is about the config file. There is no problem in the config file. What you considered as "file system issue" is actually spades binary invocation cmdline.

> The traceback should be caught resulting in an appropriate error message, shouldn't it? (In this case a translation would be nice - is there in issue with the input?)

It actually does. See in the log:
```
spades-core: /dev/shm/SPAdes/3.13.1/GCC-8.3.0/SPAdes-3.13.1/src/common/modules/path_extend/weight_counter.hpp:306: path_extend::CoverageAwareIdealInfoProvider::CoverageAwareIdealInfoProvider(const Graph&, const std::shared_ptr<path_extend::PairedInfoLibrary>&, size_t): Assertion read_length_ > g_.k()' failed.
```
So, some of SPAdes' internal assertions failed, hence the premature exit.

In fact, this issue is already fixed in SPAdes mainline and will be part of SPAdes 3.14 release
