### ISSUE TITLE
cloudSPAdes compilation failed

### ISSUE THREAD

**Issue by magcurly** [ablab/spades#376]
With all dependencies installed, cloudSPAdes is still unable to compile. It seems the configuration part is done but a lot warning appears during the make step which stopped with errors I am not capable to understand. If it's possible, please release a compiled binary version of cloudSPAdes.
I am really thrilled to try cloudSPAdes, and the confusing compilation stops me to do that.
Thanks.

**Comment by asl** [comment]
Will you please provide us the build log? It is built the same way as ordinary SPAdes and does not depend on anything.

**Comment by magcurly** [comment]
Hi! I succeed finally on the WSL(Ubuntu 18.04) in Win10. I used to use gcc-9 and cmake 3+ on my server with RedHat Enterprise and a lot warnings popped up during the compilation and stopped suddenly with a make error at 57%. I still don't know what happened to the previous compilation. I guessed the reason might be that the newest gcc-9 did not work perfectly to compile SPAdes or some packages conflict to SPAdes in my environment.
One tiny problem is that in spades_init.py of cloudSPAdes source code package, I noticed that there is a tiny mistake.
`if isfile(os.path.join(spades_home, 'spades')):`
After compilation, there was no binary file called 'spades' in the bin directory. I checked the same file in SPAdes-3.13.0 and here is 'spades-core' instead. It finally worked as I corrected the file name here.
Still I hope it might be better to release a binary version if possible.
Hope you have a good day.

**Comment by colin-heberling** [comment]
I'm having similar issues with compilation.  I agree that a binary release would be very helpful.  See my compilation log attached.  There are a good number of compilation errors and warnings.
[cloudspades_compile.log](https://github.com/ablab/spades/files/13687106/cloudspades_compile.log)

**Comment by colin-heberling** [comment]
Figured it out.  In spades-cloudspades-paper/assembler/src/common/modules/alignment/gap_info.hpp:113, replaced filling_seq_ with filling_seq_.is_initialized().
