### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by otis54** [ablab/spades#377]
I have successfully installed this program on Ubuntu and Leap15.1. I am trying to install this onto a windows subsystem for Linux (WSL) for a colleague who only uses windows, but I have had no luck. The error "The program was terminated by segmentation fault" comes up when i run "./spades.py --test" command. I am able to see the help text by running "./spades.py --help". 

Is it not possible to run this in WSL environment? What am I missing here?

Attached is the params.txt and spades.log

[spades.log](https://github.com/ablab/spades/files/3741793/spades.log)
[params.txt](https://github.com/ablab/spades/files/3741794/params.txt)

Thank you for your help.

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

WSL has many limitations (and is not a supported platform). Among these limitation is inability to run our pre-built binaries. So, you'd need to compile SPAdes there from source.
