### ISSUE TITLE
Errors: 28 and 225

### ISSUE THREAD

**Issue by iagoltk** [ablab/spades#379]
Hi!

I've been trying to assemble a genome with spades. 
I have 6 paired end libraries, an 80 core, 800 gb of RAM server to run my analysis. HDD space is also not a problem. 

I've tried different settings, but I really don't know what's going on.

[params.txt](https://github.com/ablab/spades/files/3763886/params.txt)
[spades.log](https://github.com/ablab/spades/files/3763887/spades.log)

**Comment by asl** [comment]
So, the log reads:

```
  2:01:59.397    34G / 35G   ERROR   General                 (kmer_splitters.hpp        : 145)   I/O error! Incomplete write! Reason: No space left on device. Error code: 28
```

Make sure you're having enough disk space available and / or there are no disk space quotas.

**Comment by DengHAU** [comment]
I also encountered this error and I have 7Tb free disk space, may be bugs in there. I also used multi libraries.

Not be solved yet.
