### ISSUE TITLE
Err code -6 in metagenomic assembly that used to work with SPAdes 3.10

### ISSUE THREAD

**Issue by btemperton** [ablab/spades#38]
I am trying to assemble a viral metagenome using SPAdes.  The dataset consists of ~34M paired 2x300 Nextera reads . The original dataset of 60M reads was normalised with bbnorm prior to assembly. SPAdes gets to k99 and then throws this error:

=== Stack Trace ===
[0x40c26a]
[0x68c636]
[0x6807fb]
[0x7a3959]
[0x7ac4fd]
[0x7ee5a9]
spades: /spades/src/common/utils/kmer_mph/kmer_index_builder.hpp:197: size_t utils::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&, unsigned int) [with Seq = RuntimeSeq<128ul>; traits = utils::kmer_index_traits<RuntimeSeq<128ul> >; size_t = long unsigned int; std::string = std::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed.

== Error ==  system call for: "['/gpfs/ts0/home/bt273/tools/SPAdes-3.11.0-Linux/bin/spades', '/gpfs/ts0/home/bt273/long_read_viromes/L4/spades.bbnorm.short.only/K99/configs/config.info', '/gpfs/ts0/home/bt273/long_read_viromes/L4/spades.bbnorm.short.only/K99/configs/mda_mode.info', '/gpfs/ts0/home/bt273/long_read_viromes/L4/spades.bbnorm.short.only/K99/configs/meta_mode.info']" finished abnormally, err code: -6

====================

We have previously successfully assembled this dataset with the previous version of SPAdes, but want to incorporate nanopore reads in a hybrid metagenomic assembly, once we can get the short-read version working. The assembly is running on a HPC node with 3Gb of RAM.

Please advise.

[spades.log](https://github.com/ablab/spades/files/1344935/spades.log)
[params.txt](https://github.com/ablab/spades/files/1344936/params.txt)

**Comment by asl** [comment]
Dear Ben,

It seems we already answered to this via support e-mail. Have you seen it?

**Comment by btemperton** [comment]
I haven't received any email regarding this issue. Just noticed it was in my spam folder. Will reply asap.

**Comment by asl** [comment]
The reason of this issue is I/O problem. The next version of SPAdes would include more checks to diagnose the problem earlier.

**Comment by klaas-men** [comment]
Hey, I am using SPAdes 3.11.1 and I have a similar problem. What (previous) version of SPAdes should I run to avoid this problem?

from spades.log:
  0:03:04.865    16M / 3G    INFO    General                 (kmer_index_builder.hpp    : 109)   Starting k-mer counting.
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
=== Stack Trace ===
[0x40c26a]
[0x68c666]
[0x68082b]
[0x7a3989]
[0x7ac52d]
[0x7ee5d9]
[0x40c26a]
[0x68c666]
[0x68082b]
[0x7a3989]
[0x7ac52d]
[0x7ee5d9]
spades: /spades/src/common/utils/kmer_mph/kmer_index_builder.hpp:197: size_t utils::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&, unsigned int) [with Seq = RuntimeSeq<128ul>; traits = utils::kmer_index_traits<RuntimeSeq<128ul> >; size_t = long unsigned int; std::string = std::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed.
[0x40c26a]
[0x68c666]
[0x68082b]
[0x68d767]
[0x6a531d]
[0x6a5d9a]
[0x6addf3]
[0x6ae6ca]
[0x6ae81f]
[0x6aec4d]
[0x69a4c4]
[0x541c71]
[0x40a0ee]
spades: /spades/src/common/utils/kmer_mph/kmer_index_builder.hpp:197: size_t utils::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&, unsigned int) [with Seq = RuntimeSeq<128ul>; traits = utils::kmer_index_traits<RuntimeSeq<128ul> >; size_t = long unsigned int; std::string = std::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed.


== Error ==  system call for: "['/home/support/plasmidSPAdes/SPAdes-3.11.1-Linux/bin/spades', '/home/support/plasmidSPAdes/SRR3465539/K55/configs/config.info', '/home/support/plasmidSPAdes/SRR3465539/K55/configs/plasmid_mode.info', '/home/support/plasmidSPAdes/SRR3465539/K55/configs/careful_mode.info']" finished abnormally, err code: -6

**Comment by asl** [comment]
> Hey, I am using SPAdes 3.11.1 and I have a similar problem. What (previous) version of SPAdes should I run to avoid this problem?
There is no problem with SPAdes at all (and thus there is no 'previous version without the problem'). This verification check indicates that some of SPAdes' intermediate files was corrupted due to earlier I/O problem (which was the problem Ben saw). The next version of SPAdes will report this problem much earlier - as soon as problem would happen.

**Comment by klaas-men** [comment]
Hey Anton,

Thank you for your swift responce! You say that intermediate files were corrupted due to an earlier I/O problem. Is this also the case for my problem? If so, how can I fix this I/O problem?

Greetings, Klaas

**Comment by asl** [comment]
> Is this also the case for my problem?

Likely - yes

> If so, how can I fix this I/O problem?

It depends on your system. You may want to analyze system logs for indicators of any errors, etc.
