### ISSUE TITLE
Aligning long nanopore reads to PacBio CCS overlap graph

### ISSUE THREAD

**Issue by eldariont** [ablab/spades#381]
Hi,

first of all, thanks for developing SPAdes and SPAligner! I would like to use SPAligner to align long nanopore reads to a graph. The graph was produced by a custom tool that finds overlaps between PacBio CCS reads. The graph is in GFA format and consists of nodes corresponding to the PacBio reads and edges representing overlaps between the reads. Now I want to align the long Nanopore reads (up to 600kb in length) to the graph and I'm particularly interested in long paths connecting several nodes/reads.

My question is: Can SPAligner be used for this task and if yes, do I need to set specific parameters? As far as I understand from the preprint, SPAligner is designed for de Bruijn graphs where the sequence is attached to the edges and all edges have the same sequence length. My graph has the sequence attached to the nodes and the sequences have varying lengths. Is that a problem?

I already ran SPAligner on my dataset (`spaligner spaligner_config.yaml -d nanopore -g graph.gfa -k 11 -s reads.fasta -t 20`) and got decent results: over 95% of reads get mapped. However, most reads are mapped to only one node and the longer the reads are, the lower is the relative fraction of aligned bases. Reads longer than 100kb have less than 10% of their bases mapped so that I don't get the linkage information I would like to extract from the long reads.

Thanks in advance for your help!
Cheers
David

**Comment by TanyaDvorkina** [comment]
Dear David,

Thank you for pointing out this issue. 
Unfortunately, for now SPAligner is not designed to work on graphs with variable K-mer size. 
Leaving aside the terminology of edges and nodes, SPAligner is suitable for graphs, stored in GFA1 format, where segments ("S") can have variable lengths, while links ("L") have fixed size and represent exact overlaps between two segments. In addition, SPAligner accepts only graphs with odd overlaps.

We will definitely add error handling for variable overlap in future releases to avoid such misunderstanding. 

Best regards,
Tatiana Dvorkina
