### ISSUE TITLE
Error -6

### ISSUE THREAD

**Issue by iagoltk** [ablab/spades#382]
Hello!

I managed to fix the disk space error I had a week ago, and at the start of the assembly, I got an error when the program tried to convert reads to binary format in one of my libraries.

Tried to run the program again using the --restart-from, with no success. 
Searched around and couldn't find a fix.

Thanks in advance :)  
[spades.log](https://github.com/ablab/spades/files/3784760/spades.log)
[params.txt](https://github.com/ablab/spades/files/3784761/params.txt)

**Comment by asl** [comment]
It's again a kind of I/O problem - one of SPAdes-created files could not be read...

**Comment by asl** [comment]
Unfortunately, there is nothing SPAdes could do to overcome I/O problems. If e.g. write is failed or read failed, there is nothing we could do and this usually indicates a fatal error (even more, usually the intermediate files are already corrupted and there is no way to recover). We all rely on reliable disk storage and the troubleshooting of storage problems is certainly outside the scope of SPAdes. 

It should probably be solved on case-by-case basis by a system administrator of the particular machine.

**Comment by cmeesters** [comment]
> ...  is certainly outside the scope of SPAdes.
Yes. On the other hand the error is report a couple of times here, related to the config file written by SPades?

**Comment by asl** [comment]
Not quite. Completely unrelated to any of SPAdes configs. The errors are due to intermediate files produced by SPAdes being corrupted, write failures and / or just written files are unavailable to read. So, all sorts of problems with flaky storage systems.

**Comment by iagoltk** [comment]
I really don't know what is wrong tho.

1.5 ~ 2 TB of free storage shouldn't be the problem, I guess. 
I ran other assemblers, like MaSuRCA, and they were fine. Maybe a reinstall or update could fix the issue. 
Will talk to the administrator again and will get back with  some feedback, if you are interested!

Thank you both for the comments, all the help is appreciated :)
