### ISSUE TITLE
SPAdes finished abnormally, err code: -11

### ISSUE THREAD

**Issue by msheltra** [ablab/spades#386]
I'm using SPAdes to build a transcriptome, but I ran into the following error message: == Error ==  system call for: "['/usr/lib/spades/bin/spades', '/mnt/c/Users/mrs97/Desktop/unix/Practice_RNA_seq/Reads/Non-infected/salbu_uninfected_transcriptome/K99/configs/config.info', '/mnt/c/Users/mrs97/Desktop/unix/Practice_RNA_seq/Reads/Non-infected/salbu_uninfected_transcriptome/K99/configs/mda_mode.info', '/mnt/c/Users/mrs97/Desktop/unix/Practice_RNA_seq/Reads/Non-infected/salbu_uninfected_transcriptome/K99/configs/rna_mode.info']" finished abnormally, err code: -11

I've attached the params.txt and spades.log files as well. Any idea what might be causing this issue?
[params.txt](https://github.com/ablab/spades/files/3841773/params.txt)
[spades.log](https://github.com/ablab/spades/files/3841774/spades.log)

**Comment by asl** [comment]
Hello

Will you please get SPAdes 3.13.2 a try?

**Comment by msheltra** [comment]
That fixed my issue, thanks so much!
