### ISSUE TITLE
error 255 - failed to determine read length of non-existent library 2

### ISSUE THREAD

**Issue by Sandman2127** [ablab/spades#389]
Hello,
I'm getting the error failed to determine read length on a paired end assembly using only Illumina data. 

the error is here:

 1:48:19.992     8M / 976M  ERROR   General                 (construction.cpp          : 102)   Failed to determine read length for library #2. Check that not only merged reads are present.

Whats I think is odd is according to the params.txt I have no #library 2 (no mate pairs), only the paired end libraries. This is true, I have no mate pair library, but spades shouldn't shut down assembly due to lack of mate pairs should it? 

Perhaps I flipped the wrong switch somewhere?

I also noticed this error was a very similar to https://github.com/ablab/spades/issues/266 , however I think you all decided his was caused by very rough Pacbio read qualities. Since I have no reads outside of the Illumina data I'm a bit confused.

Any help would be greatly appreciated. Attached are the log, params.txt and my original configuration yaml. 

[params.txt](https://github.com/ablab/spades/files/3865007/params.txt)
[spades.log](https://github.com/ablab/spades/files/3865008/spades.log)
[configuration.yaml.txt](https://github.com/ablab/spades/files/3865009/configuration.yaml.txt)

**Comment by asl** [comment]
Hello. Your YAML file is clearly malformed:

```
  {
    orientation: "rf",
    type: "mate-pairs",
    right reads: [
    ],
    left reads: [
    ]
  },
  {
    type: "single",
    single reads: [
    ]
  },
  {
    type: "pacbio",
    single reads: [
    ]
  }
```

Hence the error.

**Comment by Sandman2127** [comment]
Thank you very much for the simple fix :), I didn't realize leaving empty sections would be an issue. My apologies, but very happy you were able to help me fix it!
