### ISSUE TITLE
metaSpades: Error ==  exception caught: <class 'KeyboardInterrupt'>

### ISSUE THREAD

**Issue by cmaggior** [ablab/spades#392]
Hello,

I'm receiving the following error in spades (--meta flag): == Error ==  exception caught: <class 'KeyboardInterrupt'>

This is running on a cluster so I don't think anyone is cancelling the command manually. Attached are params.txt and spades.log. Does anyone have any advice?

[params.txt](https://github.com/ablab/spades/files/3876058/params.txt)
[spades.log](https://github.com/ablab/spades/files/3876059/spades.log)

**Comment by asl** [comment]
Well... something was sending this signal to SPAdes process... Does the issue reproduce after restart?

**Comment by cmaggior** [comment]
Not that I've seen, but the server is taking a very long time to run the program. Is that typical for hybridSpades?

**Comment by asl** [comment]
What is "long time"? The time required for assembly depends on many factors including the load of server, I/O latency, the size of the genome in question, error rate, repeat content, coverage, etc.

**Comment by cmaggior** [comment]
After 168 hours the job crashes with the above error message.

**Comment by asl** [comment]
Which one? Can you provide spades.log?

**Comment by cmaggior** [comment]
The spades log from the failed run is attached in the first comment of the issue, but here's a new log as well while the command is still running. What happens is the command runs as far as error correcting the first set of paired-end reads, then fails.
[spades.log](https://github.com/ablab/spades/files/3892327/spades.log)

**Comment by asl** [comment]
There is no error in the last attached spades.log. How does it crash? As I already said, Keyboard interrupt like in the very first spades.log file is due to Ctrl+C signal sent by someone.

**Comment by cmaggior** [comment]
Yes, the command is still running, but if you look at the first log attached, it is still in the same step (processing the first paired-end library) and then 'KeyboardInterrupt'. I am running the script for 168 hours each time, and each time the command doesn't progress beyond error correction in the first paired-end library. Is there a reason why this is happening? I would imagine that 168 hours is more than enough for that.

**Comment by cmaggior** [comment]
There is no indication that the server is timing out in the failed log, as well, so I am not sure what to do. 168 hours is the maximum time I have on each job.

**Comment by asl** [comment]
So, I believe there are two problems here:

1. It seems when job times out at your side, then just Ctrl+C is sent to the process. This yields KeyboardInterrupt event
2. The reason why it takes so long to go through the first step is probably I/O related, as at this very first step reads are just being read and some basic information is collected

**Comment by cmaggior** [comment]
What can I do about that?

**Comment by cmaggior** [comment]
This is the command I'm running:

#!/bin/bash
#SBATCH --nodes=8
#SBATCH --time=168:00:00
#SBATCH --job-name coassemblyHybrid_new
#SBATCH --output=coassemblyHybrid_new

cd $SLURM_SUBMIT_DIR

module load nixpkgs/16.09
module load gcc/7.3.0
module load spades/3.13.0

spades.py -o hybridSpades --meta --nanopore AllMinION.fastq -1 coassembly_R1.fastq.gz -2 coassembly_R2.fastq.gz

Is there something in the command I can change to quicken the input to the server?

**Comment by asl** [comment]
Well, you may want to talk to your system administrator as we have no idea and does not control the disk subsystem on your side...

**Comment by cmaggior** [comment]
Can you tell me if the command above that I'm entering SHOULD work? Thanks for all your help!

**Comment by asl** [comment]
The SPAdes invocation seems to be fine. I cannot say anything wrt the SLURM directives as I have no idea about the configuration of your cluster. Running on 8 nodes probably does not make any sense as SPAdes runs on single node only. And probably you need also see how to configure OpenMP properly for your job as SPAdes is using only single core on your node.

**Comment by cmaggior** [comment]
This issue has been fixed by changing the memory allotment, number of cpus, and invocation to the following:

```#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=9550M

metaspades.py -1 R1.fastq -2 R2.fastq --nanopore nanopore.fastq -o hybridspades```

Thank you!
