### ISSUE TITLE
Err 255, running SPAdes inside of Geneious Prime

### ISSUE THREAD

**Issue by robt8437** [ablab/spades#393]
Hello - I am a new user.  Trying to run SPAdes inside of Geneious Prime for the first time.  

- Windows 10, 64-bit, 32Gb RAM, AMD Ryzen 5 2400G 3.60 GHz, 4 cores / 8 processors
- Configured SPAdes per Geneious Prime, including the Windows Subsystem for Linux (Ubuntu 18.04)
- Run a test data set from Geneious tutorial and it works fine

My Data
- Assembled successfully using SPAdes on Linux Ubuntu installed in a Virtual Machine (Oracle VirtualBox) environment on this same system 
- Assembled successfully using Geneious Prime assembler

- Running my data set using the SPAdes assembler in the Geneious Prime results in the following error:
== Error ==  system call for: "['/mnt/c/Program Files/Geneious Prime/bundledPlugins/com.biomatters.plugins.spades.SPAdesPlugin/com/biomatters/plugins/spades/SPAdes-3.13.0-Windows/bin/spades-corrector-core', '/mnt/c/Users/Robert/Geneious 2020.0 Data/temp/1113/out/mismatch_corrector/contigs/configs/corrector.info', '/mnt/c/Users/Robert/Geneious 2020.0 Data/temp/1113/out/misc/assembled_contigs.fasta']" finished abnormally, err code: 255

- I have tried to adjust the RAM allocation (as high as 28GB).  System appears to run fine. 
- I have tried running a BBDUK to trim data set prior (even though SPAdes does this) 

[spades_PD12R 6 21 19.txt](https://github.com/ablab/spades/files/3880032/spades_PD12R.6.21.19.txt)
[params_PD12R 6 21 19.txt](https://github.com/ablab/spades/files/3880035/params_PD12R.6.21.19.txt)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The log reads:
```
[mem_sam_pe] paired reads have different names: "M03124:323:000000000-C5B3L:1:1101:12492:1578_1:N:0:CTCTCTAC+GTAAGTAG", "M03124:323:000000000-C5B3L:1:1101:12492:1578_2:N:0:CTCTCTAC+GTAAGTAG"
[mem_sam_pe] paired reads have different names: "M03124:323:000000000-C5B3L:1:1101:18362:1686_1:N:0:CTCTCTAC+GTAAGGAG", "M03124:323:000000000-C5B3L:1:1101:18362:1686_2:N:0:CTCTCTAC+GTAAGGAG"
```

Note that neither Geneious nor Windows are supported platforms for SPAdes. You may want to ask Geneious support for more information.

**Comment by robt8437** [comment]
Thank you for the quick response.  So, it is a file naming error?  
I will contact Geneious, but wanted to relay that information correctly.

**Comment by asl** [comment]
Per FASTQ specification the names of left and right reads should be same in the files. This is what bwa complains about
