### ISSUE TITLE
Same number of contigs and scaffolds

### ISSUE THREAD

**Issue by azrasid** [ablab/spades#396]
HI ,
I am running Spades on a human gene. The reads are pair end of length 110 and coverage is 40.
I wonder why I am getting the same number of scaffolds as contigs. Scaffolds number should be less than the contigs.
Here is the command I am using:
**SPAdes-3.13.0-Linux/bin/spades.py -k 55  --12 /genes/cyp2c19/samples_fastq/CYP2C19_1.001_final.fastq -o spadetest**

Is there something I am missing?

**Comment by asl** [comment]
> Scaffolds number should be less than the contigs.

This is not quite true. It's perfectly ok to have scaffolds identical to the contigs in case where is nothing to scaffold.

**Comment by azrasid** [comment]
Hi,
I wanted to know if there is any way of getting few or 1 consensus contig from the many contigs that I am getting when running Spades
