### ISSUE TITLE
Percent of Assembled and Unassembled Reads

### ISSUE THREAD

**Issue by TJrogers86** [ablab/spades#398]
Hello,

I used MetaSPades to assemble my reads and I was wondering if it is possible to find out what percent of my reads actually went into my contigs? This seems like it would be important to know as it will give you an idea of the percent of your metagenome you are able to analyze.

**Comment by asl** [comment]
Yes. Just align your reads back to the contigs and you will have this information.

There is no other direct link between input reads and the output of de Bruijn graph-based assembler.
