### ISSUE TITLE
error code -6     == Error ==  system call for: "['/usr/lib/spades/bin/hammer'

### ISSUE THREAD

**Issue by lasupernova** [ablab/spades#399]
Spades was installed correctly (confirmed with `spades.py --test`)

But I get an error code (-6) with the following error message

`== Error ==  system call for: "['/usr/lib/spades/bin/hammer', '/media/sf_Deep_ARG/Pharmafilter_HiSeq_BaseClear/pear_test/corrected/configs/config.info']" finished abnormally, err code: -6
`
Can you please advise what to do?

[params.txt](https://github.com/ablab/spades/files/3918714/params.txt)
[spades.log](https://github.com/ablab/spades/files/3918715/spades.log)

**Comment by asl** [comment]
The log reads:

```
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t)'. In file '/build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/io/kmers/mmapped_reader.hpp' on line 99. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So you're running out of RAM
