### ISSUE TITLE
Is it possible to increase the limit of k-mer size over 127?

### ISSUE THREAD

**Issue by ilnamkang** [ablab/spades#40]
Hi,

Are there any method to increase the maximum k-mer size beyond the default (127)?

Sometimes, I perform sequencing with 2*300 bp read length. And, I'd like to test the effect of increasing maximum k-mer size beyond 127 (e.g., 151) on assembly quality.

Thanks.

**Comment by asl** [comment]
In theory it is possible, however we do not expose this possibility for users. Note that this also doubles the memory.

**Comment by ilnamkang** [comment]
Your suggestion worked nicely.

I rebuilt the SPAdes using -DSPADES_MAX_K option, and then changed the 'MAX_K' value in the 'options_storage.py' file accordingly.
Now, spades.py accepts k-mer values larger than 127 without error messages.

Thanks for your help.
