### ISSUE TITLE
Running spades on server does not work

### ISSUE THREAD

**Issue by lasupernova** [ablab/spades#401]
I am running spades on the computecanada server. It was installed correctly.

These are the param and spades files:
[spades.log](https://github.com/ablab/spades/files/3941525/spades.log)
[params.txt](https://github.com/ablab/spades/files/3941526/params.txt)

Could you please advice as to what is going wrong?
Thank you

**Comment by asl** [comment]
Per error log, the SPAdes job was interrupted via Ctrl+C keyboard signal sent to SPAdes process.

**Comment by lasupernova** [comment]
I thought that is that the log was saying, but I did not interrupt the SPAdes job. I was running it on a server using sbatch, so it was running in the background after that

**Comment by asl** [comment]
Well, you may want to ask your system administrator when, what might be the problem
