### ISSUE TITLE
Beginer question regarding filtered subreads

### ISSUE THREAD

**Issue by Lamm-a** [ablab/spades#402]
Are the filterd subreads you requier for using pacbio in hybrid assembly simply the output of the pacbio sequencing or must something be done to them first?

**Comment by asl** [comment]
Hello

"filtered subreads" is a standard thing in PacBio terminology. See e.g. http://files.pacb.com/software/smrtanalysis/2.2.0/doc/smrtportal/help/!SSL!/Webhelp/Portal_PacBio_Glossary.htm for more details
