### ISSUE TITLE
Output without scaffolds.fa

### ISSUE THREAD

**Issue by emaubin** [ablab/spades#403]
Hello, 
I'm using Spades for local assembly on specific regions, but i have differents results. Sometime I get an output with a scaffolds.fasta file and sometime I get only a contigs.fasta file, I don't understand why. 
Attached, you can find log file and params file.
Thank you very much. 

Emilie

[params.txt](https://github.com/ablab/spades/files/3944895/params.txt)
[spades.log](https://github.com/ablab/spades/files/3944896/spades.log)

**Comment by asl** [comment]
Hello

This is expected. The log file contains all the relevant information:

```
 * 1:02:48.291   660M / 8G    WARN    General                 (pair_info_count.cpp       : 339)   Unable to estimate insert size for paired library #0
 * 1:02:48.291   660M / 8G    WARN    General                 (pair_info_count.cpp       : 345)   None of paired reads aligned properly. Please, check orientation of your read pairs.
 * 1:02:48.291   660M / 8G    WARN    General                 (repeat_resolving.cpp      :  63)   Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.
```
