### ISSUE TITLE
== Error ==  system call for: "['/mnt/nfs/home/b7040535/Software/SPAdes-3.13.0-Linux/bin/spades-hammer', '/nobackup/b7040535/Mycoplasma_Trichomonas_analysis/SPADES_unmapped_assembly16-12-19/CatTvagTVV_GCA_000770195_ASM77019v1_UNMAPPED/corrected/configs/config.info']" finished abnormally, err code: 255

### ISSUE THREAD

**Issue by NBaileyNCL** [ablab/spades#406]
Hi all,

My spades run is failing with this error message:

== Error ==  system call for: "['/mnt/nfs/home/b7040535/Software/SPAdes-3.13.0-Linux/bin/spades-hammer', '/nobackup/b7040535/Mycoplasma_Trichomonas_analysis/SPADES_unmapped_assembly16-12-19/CatTvagTVV_GCA_000770195_ASM77019v1_UNMAPPED/corrected/configs/config.info']" finished abnormally, err code: 255

I've seen previous posts about it but none of the suggested fixes (set --phred-offset	33, allocate more memory) have worked.

Std output and spades.log are attached

Any help would be much appreciated

[spades.log](https://github.com/ablab/spades/files/3977960/spades.log)

[mycoplasma_unmappedReads_spades_assemble3_17-12-19.txt](https://github.com/ablab/spades/files/3977966/mycoplasma_unmappedReads_spades_assemble3_17-12-19.txt)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Will you please attache the files mentioned in the error message just two lines above the github link?

Thanks!

**Comment by NBaileyNCL** [comment]
Thanks for getting back so quickly. Apologies, meant to include logs but it posted by accident before I was finished

**Comment by asl** [comment]
So, the log reads:

```
  0:30:07.299     6G / 12G   ERROR   General                 (hammer_tools.cpp          : 189)   Pair of read files /nobackup/b7040535/Mycoplasma_Trichomonas_analysis/Raw_data/CatTvagTVV_GCA_000770195.1_ASM77019v1Unmapped.out.mate1COPY.fastq and /nobackup/b7040535/Mycoplasma_Trichomonas_analysis/Raw_data/CatTvagTVV_GCA_000770195.1_ASM77019v1Unmapped.out.mate2.fastq contain unequal amount of reads
```

It's highly likely that your input read files are corrupted.
