### ISSUE TITLE
[Question] Recommended method for merging rnaSPAdes results from multiple samples assembled individually?

### ISSUE THREAD

**Issue by jolespin** [ablab/spades#407]
I assembled each sample individually using `rnaSPAdes v3.13.1` to try and capture sample-specific isoforms.  

**Is there a recommended method for merging these into gene clusters?**  

I've heard of [Lace/Corset](https://github.com/Oshlack/Lace) but this method requires me to remap my reads to the transcripts, [Trinity_gene_splice_modeler.py](https://github.com/trinityrnaseq/trinityrnaseq/wiki/SuperTranscripts) but only works for `Trinity` coassemblies, and [cd-hit](http://weizhongli-lab.org/lab-wiki/doku.php?id=cd-hit-user-guide) seems to be more for clustering and might fail if there are large exons.

**Comment by andrewprzh** [comment]
Dear Josh,

Unfortunately, I never had experience with merging RNA assemblies. However, I know that [Oyster River Protocol ](https://peerj.com/articles/5428/) uses OrthoFuse to do it.

Also, I think assembling all samples together may give something close to desired result. Are that any particular reasons why that might not work? Complex sample specific isoforms?

We are releasing new rnaSPAdes that supports hybrid transcriptome assembly. Once it's out, you may try to assemble all samples together and add your assemblies as long reads. That may improve standard assembly.

**Comment by jolespin** [comment]
Thanks for the suggestion!  The reason I wanted to assemble separately was: (A) it would be quicker ;) and (2) I thought it would be more "realistic" in terms of what was actually there.  I ended up doing a coassembly which just finished.  Since I have a coassembly with `_gX_iY` identifier structure, I'm going to try using [Lace](https://github.com/Oshlack/Lace/wiki/Usage-Documentation) to create [supertranscripts](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1284-1) using the gene cluster as the a priori clusters that would normally be generated from `corset`.  I'll let you know how they turn out.  I want to create `supertranscripts` so I can map all of my samples to them and get a general idea of what genes are expressed instead of specific transcripts. 

Which release will the update `rnaSPAdes` be available in?  Definitely looking forward to testing out your approach!

**Comment by andrewprzh** [comment]
Totally agree on what you pointed out about separate assemblies.
Further analysis you proposed seems reasonable as well, would be glad to know the results :)

We really hope that 3.14 will come out before New Year.
