### ISSUE TITLE
system call for 'command' finished abnormally ,err code :- 6

### ISSUE THREAD

**Issue by ZhenJin1996** [ablab/spades#408]
Hello,this is my first time using SPAdes,and i got trouble with the following error:
Error ==  system call for: "['/home/jinzhen/software/miniconda3/bin/spades-hammer', '/home/jinzhen/spadata/corrected/configs/config.info']" finished abnormally, err code: -6
please help me,thx
System information:
  SPAdes version: 3.13.1
  Python version: 3.7.4
  OS: Linux-4.18.0-80.11.2.el8_0.x86_64-x86_64-with-centos-8.0.1905-Core
[params.txt](https://github.com/ablab/spades/files/3982089/params.txt)
[spades.log](https://github.com/ablab/spades/files/3982090/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The log reads:
```
<jemalloc>: Error in malloc(): out of memory. Requested: 18454936, active: 4194304
```
So, you're running out of RAM.

However, this looks very wrong:
```
  Memory limit (in Gb): 0
```
Are you sure your system is configured properly?

**Comment by ZhenJin1996** [comment]
> Hello
> 
> Thank you for your interest in SPAdes.
> 
> The log reads:
> 
> ```
> <jemalloc>: Error in malloc(): out of memory. Requested: 18454936, active: 4194304
> ```
> 
> So, you're running out of RAM.
> 
> However, this looks very wrong:
> 
> ```
>   Memory limit (in Gb): 0
> ```
> 
> Are you sure your system is configured properly?

Thx, I would check it

**Comment by ZhenJin1996** [comment]
> Hello
> 
> Thank you for your interest in SPAdes.
> 
> The log reads:
> 
> ```
> <jemalloc>: Error in malloc(): out of memory. Requested: 18454936, active: 4194304
> ```
> 
> So, you're running out of RAM.
> 
> However, this looks very wrong:
> 
> ```
>   Memory limit (in Gb): 0
> ```
> 
> Are you sure your system is configured properly?

Thx, I will check it
