### ISSUE TITLE
Requesting help with parameter values

### ISSUE THREAD

**Issue by sagnikbanerjee15** [ablab/spades#41]
Hello,

I will be using spades to assemble reads de-novo. I have aligned my set of reads to a genome and then I have extracted those reads which failed to align. I have decided to assemble those reads de-novo using spades. For those reads which do map to the genome I am using some alignment driven assembler. I have 5 libraries to assemble. I am not sure what value I should use for '-k' and '-cov-cutoff'. I have attached a histogram depicting read length distribution.

Thank you.
![11526_rar3_read_length_distribution](https://user-images.githubusercontent.com/23457977/31818616-84794876-b55e-11e7-83c8-a9c16ba46ecf.png)

**Comment by asl** [comment]
We recommend to use the default values unless there are very good reasons not to do so.

**Comment by sagnikbanerjee15** [comment]
Thank you I will try that
