### ISSUE TITLE
Minimum contig length in metaSPAdes

### ISSUE THREAD

**Issue by Marcoleta-AE** [ablab/spades#410]
Thanks for this awesome tool. I successfully used it to assemble soil  metagenomes using illumina and nanopore reads. However, I could not find what is the minimum size of the assembled contigs (set as default, could it be set to a defined value by the user?). After running QUAST with my assemblies, I can see only # contigs (>= 0 bp) and then (>1000 bp), so I cannot figure out the size of those contigs under 1 kbp.

Thanks for your help!

Best Regards
--

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

There is no minimum contig length. Certainly, the contig could not be shorter than the maximum used k-mer length.
