### ISSUE TITLE
SPAdes pipeline finished WITH WARNINGS! (3.14.0 --test)

### ISSUE THREAD

**Issue by kr-hansen** [ablab/spades#411]
Running Spades from binaries on MacOS 10.14.6.  Running Spades 3.14.0.

Just did the install and went to run the test as outlined in the manual (http://cab.spbu.ru/files/release3.14.0/manual.html):
`./spades.py --test`

Got this output:
======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:01.100     7M / 9M    WARN    General                 (launcher.cpp              : 172)   Your data seems to have high uniform coverage depth. It is strongly recommended to use --isolate option.

When expecting this output:
======= SPAdes pipeline finished.

========= TEST PASSED CORRECTLY.

Looks like it isn't a broken issue, but wanted to note the discrepancy.  I'm guessing this is since the --isolate option is new in 3.14.0.  Is that a correct assessment?

**Comment by asl** [comment]
It's ok. Since --test also accepts bunch of modifiers, e.g. --sc / --isolate / --meta / --plasmid and so on

**Comment by kr-hansen** [comment]
Sounds good.  Thanks.  Mostly just wanted to confirm that though it never says:
"========= TEST PASSED CORRECTLY."

That the test still passed correctly assuming that is the only error.  Both for myself and for future users.

**Comment by asl** [comment]
It's a warning, not error. And it indicates that everything is expected.
