### ISSUE TITLE
finished abnormally, err code: -11

### ISSUE THREAD

**Issue by bvaldebenitom** [ablab/spades#415]
Hi!

I got the following error during the "Closing gaps with long reads" stage:
`== Error ==  system call for: "['/home/user_zhc/PB_20191212/SPAdes-3.13.1/bin/spades-core', '/home/user_zhc/Assembly_HybridAssembly/Assembly_k40_Spades/K77/configs/config.info']" finished abnormally, err code: -11`

I have attached the params.txt and spades.log files.

Any info on what might be the cause?
Thanks!

[params.txt](https://github.com/ablab/spades/files/4022478/params.txt)
[spades.log](https://github.com/ablab/spades/files/4022479/spades.log)

**Comment by asl** [comment]
Hello

Does the problem reproduce with SPAdes 3.14.0?

**Comment by EugenioVE** [comment]
Dear Anton and All,
I am getting the same error when running HybPiper test dataset with SPAdes 3.14.0, any idea what could be the problem?... thanks a lot in advance!
[params.txt](https://github.com/ablab/spades/files/4091747/params.txt)
[spades.log](https://github.com/ablab/spades/files/4091748/spades.log)

**Comment by EugenioVE** [comment]
Just in case it is useful, same outcome with `spades.py --test` after downloading again the Linux Binaries for 3.14.0 and with the 3.13.0 installed with `conda install -c bioconda spades. These are the files for the former test
[params.txt](https://github.com/ablab/spades/files/4092060/params.txt)
[spades.log](https://github.com/ablab/spades/files/4092061/spades.log)

`

**Comment by asl** [comment]
@EugenioVE Please do not hijack unrelated issues. In your case you'd need to compile SPAdes from sources.

**Comment by EugenioVE** [comment]
thanks and sorry, thought it was related

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
