### ISSUE TITLE
No scaffolds in output folder

### ISSUE THREAD

**Issue by maguileraf** [ablab/spades#419]
Hi,

I finished running spades but there is no scaffolds file in my output folder only the contigs.fasta. Attached is my spades.log file.
[spades.log](https://github.com/ablab/spades/files/4035907/spades.log)

**Comment by asl** [comment]
Hello

You're running SPAdes 3.10.0 which is pretty old (released 3 years ago) and has known issues in recovery (--continue) feature. Please consider upgrading to the latest SPAdes 3.14.0. The reported "contigs" are unfortunately unusable.

**Comment by maguileraf** [comment]
Thank you for the prompt response. I will try it now with SPAdes 3.14.0.
