### ISSUE TITLE
Problems with metaspades

### ISSUE THREAD

**Issue by Guitox** [ablab/spades#42]
I have a problem with metaspades. I am running a metagenome assemble and Im getting this error.

finished abnormally, err code: 255 in python

And this is my command:

metaspades.py -1 PM2_forward.Tp.fastq -2 PM2_reverse.Tp.fastq -k 21,31,41,51,61 -o spades_PM2_out

Any ideas?

**Comment by asl** [comment]
Sure. Please attach your params.txt and spades.log files as you were instructed in the error message
