### ISSUE TITLE
== Error ==  system call for: "[~~~~]" finished abnormally, OS return value: 255

### ISSUE THREAD

**Issue by ZhenJin1996** [ablab/spades#420]
Hello, I got trouble with the following error when using SPAdes :
== Error ==  system call for: "['/home/foodbio/biosoft/spades/SPAdes-3.14.0-Linux/bin/spades-hammer', '/home/stu_2/Jinzhen/spades_analysis/corrected/configs/config.info']" finished abnormally, OS return value: 255

System information:
  SPAdes version: 3.14.0
  Python version: 3.7.5
  OS: Linux-2.6.32-696.23.1.el6.x86_64-x86_64-with-centos-6.9-Fina

Thank you ！
[params.txt](https://github.com/ablab/spades/files/4041140/params.txt)
[spades.log](https://github.com/ablab/spades/files/4041142/spades.log)

**Comment by asl** [comment]
Hello

The log clearly reads:
```
  0:45:31.667    15G / 28G   ERROR   General                 (hammer_tools.cpp          : 191)   Pair of read files /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_1.fastq and /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_2.fastq contain unequal amount of reads
```

Hope this helps

**Comment by ZhenJin1996** [comment]
> Hello
> 
> The log clearly reads:
> 
> ```
>   0:45:31.667    15G / 28G   ERROR   General                 (hammer_tools.cpp          : 191)   Pair of read files /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_1.fastq and /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_2.fastq contain unequal amount of reads
> ```
> 
> Hope this helps

Great!Thanks for help,but I am sure the two files I ran contain equal amout of reads,why it happened?

**Comment by asl** [comment]
How have you checked this?

**Comment by ZhenJin1996** [comment]
> How have you checked this?

Oh,sorry.I mean before I ran,they were equally.

**Comment by asl** [comment]
Can you run wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_1.fastq and wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_2.fastq and post the output here?

**Comment by ZhenJin1996** [comment]
> Can you run `wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_1.fastq` and `wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_2.fastq` and post the output here?

Sure,thanks for your help,l will post it later.

**Comment by ZhenJin1996** [comment]
> > Can you run `wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_1.fastq` and `wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_2.fastq` and post the output here?
> 
> Sure,thanks for your help,l will post it later.

Oh, they are unequally,I use the two files from kneaddata output.
[stu_2@jnprobiotics Jinzhen]$ wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_1.fastq 
31910020 /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_1.fastq
[stu_2@jnprobiotics Jinzhen]$ wc -l /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_2.fastq 
3552084 /home/stu_2/Jinzhen/ERR321067/321067_1_kneaddata_paired_2.fastq

**Comment by asl** [comment]
So, they do have unequal number of reads, the error is expected.

**Comment by ZhenJin1996** [comment]
> So, they do have unequal number of reads, the error is expected.

Thank you very much!I would keep supporting your software.

**Comment by camolina-vet** [comment]
hallo, iam with the same error. But I try to test the spades and the error is the same:
tried:
/Users/camilamolina/miniconda3/bin/spades.py --test

and the error:
== Error ==  system call for: "['/Users/camilamolina/miniconda3/bin/spades-hammer', '/Users/camilamolina/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: 22

**Comment by asl** [comment]
@camolina-vet Please do not hijack old closed issues. Open a new one including the files mentioned in the error message
