### ISSUE TITLE
Error with metagenome assembly using nanopore library

### ISSUE THREAD

**Issue by nsng** [ablab/spades#421]
Hi there, 

I have a single library sequenced with nanopore and I am trying to perform a metagenome assembly. I've tried running the command below but I keep getting the following error. 

spades.py --meta --nanopore -s porechop_ter_mats.fastq -o spades_ter_mats

== Error ==  Please specify option (e.g. -1, -2, -s, etc) for the following paths: porechop_ter_mats.fastq

**Comment by asl** [comment]
Hello

SPAdes manual (http://cab.spbu.ru/files/release3.14.0/manual.html#sec3.1) reads:
```
Illumina and IonTorrent libraries should not be assembled together. All other types of input data are compatible. SPAdes should not be used if only PacBio CLR, Oxford Nanopore, Sanger reads or additional contigs are available.
```
