### ISSUE TITLE
== Error ==  system call for: "['/SPAdes-3.14.0-Linux/bin/spades-hammer' OS return value: -6

### ISSUE THREAD

**Issue by rababust** [ablab/spades#423]
[params.txt](https://github.com/ablab/spades/files/4062883/params.txt)
[spades.log](https://github.com/ablab/spades/files/4062884/spades.log)

Hi, i've been working with spades in a server, now I've downloaded Docker and installed orca repository.

When I run spades, and error occurs, I just tried different things, such as, using -m and/or -t parammeters and --tmp-directory.

But I can not fix it. Could you help me please.

Thanks

**Comment by asl** [comment]
Hello
Thank you for your interest in SPAdes.

The log reads:
```
Message 'mmap(2) failed. Reason: Invalid argument. Error code: 22'.
```

It seems that the filesystem you're using on ```/c/Users/rafa_``` is not POSIX-compliant as it does not support memory mapped files. You may need to move to some other directory.
