### ISSUE TITLE
Does spades-read-filter discard reads below the coverage threshold or above?

### ISSUE THREAD

**Issue by shelkmike** [ablab/spades#424]
Based on the description of spades-read-filter I suppose that it is intended to discard reads with low median k-mer coverage. However, when running it with --cov 500 it produces more reads than when running it with --cov 200 on the same input data. Could you please explain how this is possible?
The Spades version is 3.14.0

**Comment by asl** [comment]
It seems to be very weird bug in 3.14. We are going to fix it in 3.14.1.

**Comment by asl** [comment]
Fixed in 3.14.1
