### ISSUE TITLE
err code: -6 while running

### ISSUE THREAD

**Issue by fmascali** [ablab/spades#425]
Hi, I'm trying to run spades over short PE reads and I had an error code 6. Could you explain to me what should I do?
Thank you!

[params.txt](https://github.com/ablab/spades/files/4083359/params.txt)
[spades.log](https://github.com/ablab/spades/files/4083360/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The log reads:
```
Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So, you're out of RAM. Trying SPAdes 3.14 might help a bit.
