### ISSUE TITLE
metaSPAdes.py-short contigs fully covered by longer contigs

### ISSUE THREAD

**Issue by jlli6t** [ablab/spades#426]
Hi developers,

I am using metaSPAdes.py to do assembly with default kmers.

In my case, one 7kbp contig turned out to be fully covered by another 13kbp contig, I am thinking whether they are real repeats or just redundancy while resolving the graph?

Could you suggest? Thank you~

**Comment by andrewprzh** [comment]
Somehow forgot to reply - my bad. 
My guess is that both version are correct. It can be a repeat, but in general SPAdes should not output same sequences twice. More information can be obtained by looking at the graph itself. If this is still a problem, please contact me directly.
