### ISSUE TITLE
Error: SPAdes failed to produce assemblies. 

### ISSUE THREAD

**Issue by limin321** [ablab/spades#427]
Hi  
I am using unicycler to run hybrid assembly of a bacterium genome with both nanopore and illumina data. Spades ran into some issues, could anyone please help me figure out what is going on here? 

My command :  (base) campus-107-113:SJ003 dklabuser$ unicycler -1 SJ003_S12.R1.trimmed.fastq.gz -2 SJ003_S12.R2.trimmed.fastq.gz -s SJ003_S12.R1.trimmed.unpaired.fastq.gz -s SJ003_S12.R2.trimmed.unpaired.fastq.gz -l SJ003_filtered.fastq.gz --existing_long_read_assembly SJ003_unp.fasta --mode bold -o SJ003_bold -t 8 

See spades_assembly/assembly/spades.log for more info below:
Command line: /Users/dklabuser/miniconda3/bin/spades.py	-o	/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly	-k	27,47,63,77,89,99,107,115,121,127	--threads	8	--only-assembler	-1	/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_1.fastq.gz	-2	/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_2.fastq.gz	--only-assembler	-s	/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_u.fastq.gz	

System information:
  SPAdes version: 3.14.0
  Python version: 3.7.4
  OS: Darwin-19.2.0-x86_64-i386-64bit

Output dir: /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_1.fastq.gz']
      right reads: ['/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_2.fastq.gz']
      interlaced reads: not specified
      single reads: ['/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_u.fastq.gz']
      merged reads: not specified
Assembly parameters:
  k: [27, 47, 63, 77, 89, 99, 107, 115, 121, 127]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly/tmp
  Threads: 8
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly/spades.log

/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_1.fastq.gz: max reads length: 301
/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_2.fastq.gz: max reads length: 281
/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_u.fastq.gz: max reads length: 301

Reads length: 301

===== Assembling started. 

===== K27 started. 

== Running: /Users/dklabuser/miniconda3/bin/spades-core /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly/K27/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  73)   Loaded config from /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly/K27/configs/config.info
  0:00:00.000     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 250 Gb
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  83)   Starting SPAdes, built from refs/heads/is-update-spades-to-3.14.0, git revision 45f1eddeb4c895cea74e59e81ab8d523515af1f5
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  84)   Maximum k-mer length: 128
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  85)   Assembling dataset (/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly/dataset.info) with K=27
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  86)   Maximum # of threads to use (adjusted due to OMP capabilities): 8
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  79)   SPAdes started
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  86)   Starting from stage: read_conversion
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  92)   Two-step RR enabled: 0
  0:00:00.000     4M / 4M    INFO   StageManager             (stage.cpp                 : 166)   STAGE == Binary Read Conversion
  0:00:00.000     4M / 4M    INFO    General                 (read_converter.cpp        :  72)   Converting reads to binary format for library #0 (takes a while)
  0:00:00.000     4M / 4M    INFO    General                 (read_converter.cpp        :  73)   Converting paired reads
  0:00:00.780   171M / 171M  ERROR   General                 (paired_readers.cpp        :  39)   The number of left read-pairs is larger than the number of right read-pairs
  0:00:00.780   171M / 171M  ERROR   General                 (paired_readers.cpp        :  41)   Unequal number of read-pairs detected in the following files: /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_1.fastq.gz  /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_2.fastq.gz

== Error ==  system call for: "['/Users/dklabuser/miniconda3/bin/spades-core', '/Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly/K27/configs/config.info']" finished abnormally, OS return value: 255

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/assembly/spades.log

Thank you for using SPAdes!

**Comment by asl** [comment]
Hello

The log reads:
```
0:00:00.780 171M / 171M ERROR General (paired_readers.cpp : 41) Unequal number of read-pairs detected in the following files: /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_1.fastq.gz /Users/dklabuser/Desktop/Unresolved/SJ003/SJ003_bold/spades_assembly/corrected_2.fastq.gz
```

So your input reads are corrupted.
