### ISSUE TITLE
trusted and untrusted contig

### ISSUE THREAD

**Issue by lucaspompeun** [ablab/spades#429]
Hello, I'm interested in understand how the trusted and unstrusted contigs work in spades and in graph generation. Could you please recommend any papers?
Thanks

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

SPAdes manual (http://cab.spbu.ru/files/release3.14.0/manual.html#sec3.1) discusses how these contigs are used. We are not aware about any papers on this matter.
