### ISSUE TITLE
Finished abnormally, err code: -9

### ISSUE THREAD

**Issue by cmaggior** [ablab/spades#430]
I'm receiving the following error message for metaspades: ```finished abnormally, err code: -9```. Params and spades log files are attached. Does anyone have any ideas? I haven't been able to find out what exactly error code -9 is in spades documentation or my own log files.

[params.txt](https://github.com/ablab/spades/files/4100095/params.txt)
 
[spades.log](https://github.com/ablab/spades/files/4100094/spades.log)

**Comment by asl** [comment]
Hello

It's likely that you're running out of RAM as your dataset is quite huge. How much free RAM is available for your SPAdes job?

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
