### ISSUE TITLE
Are paths allowed in the -o flag?

### ISSUE THREAD

**Issue by Lamm-a** [ablab/spades#431]

**Comment by asl** [comment]
Sure!

**Comment by Lamm-a** [comment]
Sorry I hit enter before I added detail to my post . Updated the question now.

**Comment by asl** [comment]
Most probably there are trailing spaces in your $path variable. You may want to quote the arguments

**Comment by Lamm-a** [comment]
I will try quotes but there are not any in $path as you can see above.

**Comment by Lamm-a** [comment]
Using quotes does not resolve the error.

**Comment by asl** [comment]
Then you need to figure out where space is. Maybe changing spades.py to echo would help debugging

**Comment by Lamm-a** [comment]
But there is no space in the $outdir, unless you mean elsewhere?

**Comment by Lamm-a** [comment]
You suggestion of echo has helped:
`
spades.py --isolate -1 /home/lamma/local-blast/termitomycesBGI/clean_short_reads/*.fastq.gz:_2-clean.fastq -2 /home/lamma/local-blast/termitomycesBGI/spades_output --pacbio /home/lamma/local-blast/termitomycesBGI/clean_short_reads/*.fastq.gz:_1-clean.fastq -o`

is the command being submitted but I have no idea why as I believe this should work:

```
path="/home/lamma/local-blast/termitomycesBGI"

for filename in $path/long_reads/*.fastq.gz:
do
    long_read=$filenanme
    short_fwd="$path/clean_short_reads/$(echo $(basename $filename) | awk -F '_long-read.fastq.gz' '{print $1"_1-clean.fastq"}')"
    short_rvs="$path/clean_short_reads/$(echo $(basename $filename) | awk -F '_long-read.fastq.gz' '{print $1"_2-clean.fastq"}')"
    outdir="$path/spades_output"
    sbatch --account abr spades-call.sh $long_read $short_fwd $short_rvs $outdir
done

```

**Comment by asl** [comment]
At least you're having a type in
```
long_read=$filenanme
```
And your for loop condition also looks a bit strange (provided it's shell syntax).

**Comment by Lamm-a** [comment]
a type in? It is indeed shell, what about the syntax is strange?
