### ISSUE TITLE
SPAdes configuration error

### ISSUE THREAD

**Issue by cyanels** [ablab/spades#433]
I'm using SPAdes on a windows subsytem for linux. I know this is buggy but other posts have mentioned that compiling the package yourself allows this to work. However, during the compilation I have received errors which lead to an incomplete configuraion. 

This is where the error occurs:

-- Translating jemalloc_macros.h.in -> jemalloc_macros.h.in.cmake => jemalloc_macros.h
-- Translating jemalloc_defs.h.in -> jemalloc_defs.h.in.cmake => jemalloc_defs.h
-- Translating jemalloc_protos.h.in -> jemalloc_protos.h.in.cmake => jemalloc_protos.h
-- Translating jemalloc_typedefs.h.in -> jemalloc_typedefs.h.in.cmake => jemalloc_typedefs.h
CMake Error at /mnt/c/Users/an18717/OneDrive - University of Bristol/Sequencing/SPAdes-3.14.0/ext/src/jemalloc/build-aux/Utilities.cmake:61 (file):
  file failed to open for reading (No such file or directory):

 /mnt/c/Users/an18717/OneDrive\ -\ University\ of\ Bristol/Sequencing/SPAdes-3.14.0/build_spades/ext/jemalloc/include/jemalloc/jemalloc_defs.h
Call Stack (most recent call first):
  /mnt/c/Users/an18717/OneDrive - University of Bristol/Sequencing/SPAdes-3.14.0/ext/src/jemalloc/build-aux/Utilities.cmake:230 (AppendFileContents)
  /mnt/c/Users/an18717/OneDrive - University of Bristol/Sequencing/SPAdes-3.14.0/ext/src/jemalloc/CMakeLists.txt:307 (CreateJemallocHeader)

and I've attached the make and error logs. 

Any help would be greatly appreciated.

[CMakeOutput.log](https://github.com/ablab/spades/files/4116196/CMakeOutput.log)

[CMakeError.log](https://github.com/ablab/spades/files/4116195/CMakeError.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes

Does the problem reproduce if you'd move everything to the directory w/o spaces in path?

**Comment by cyanels** [comment]
Hi asl, 

That fixes it! Thank you so much for your help!
