### ISSUE TITLE
error code -6

### ISSUE THREAD

**Issue by marina-vn** [ablab/spades#434]
I'm getting this error when I ran spades assembly:

== Error ==  system call for: "['/soft/SPAdes-3.13.0-Linux/bin/spades-core', '/scr/manuel/Marina_scr/1_ensamblajes_RAPROCAN/103_26M/K127/configs/config.info', '/scr/manuel/Marina_scr/1_ensamblajes_RAPROCAN/103_26M/K127/configs/mda_mode.info', '/scr/manuel/Marina_scr/1_ensamblajes_RAPROCAN/103_26M/K127/configs/meta_mode.info']" finished abnormally, err code: -6

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:01:07.122   744M / 9G    WARN    General                 (pair_info_count.cpp       : 358)   Estimated mean insert size 161 is very small compared to read length 151
======= Warnings saved to /scr/manuel/Marina_scr/1_ensamblajes_RAPROCAN/103_26M/warnings.log

=== ERRORs:
 * system call for: "['/soft/SPAdes-3.13.0-Linux/bin/spades-core', '/scr/manuel/Marina_scr/1_ensamblajes_RAPROCAN/103_26M/K127/configs/config.info', '/scr/manuel/Marina_scr/1_ensamblajes_RAPROCAN/103_26M/K127/configs/mda_mode.info', '/scr/manuel/Marina_scr/1_ensamblajes_RAPROCAN/103_26M/K127/configs/meta_mode.info']" finished abnormally, err code: -6

Thanks in advance for your help!

[params.txt](https://github.com/ablab/spades/files/4127792/params.txt)
[spades.log](https://github.com/ablab/spades/files/4127793/spades.log)

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The log reads:
```
  0:01:01.378     1G / 9G    INFO    General                 (pair_info_count.cpp       : 209)   Edge pairs: 67108864 (rough upper limit)
  0:01:01.378     1G / 9G    INFO    General                 (pair_info_count.cpp       : 213)   2 paired reads (4.74333e-05% of all) aligned to long edges
  0:01:01.395   756M / 9G    INFO    General                 (pair_info_count.cpp       : 354)     Insert size = 161, deviation = 0, left quantile = 161, right quantile = 161, read length = 151
```
It's likely that your input reads are corrupted (e.g. the left ones do not correspond to the right ones)

**Comment by dywang0323** [comment]
How to deal with this problem:It's likely that your input reads are corrupted (e.g. the left ones do not correspond to the right ones), because I have the same problem, is there any recommended method.

  Thanks

**Comment by asl** [comment]
You need to analyze your read files. Start from something simple, e.g. just count the number of left and right reads. If you're using some read pre-processing tools, then insure that they are paired-end aware. Then you could proceed with e.g. checking if the read names match, etc.
