### ISSUE TITLE
SPAdes fails with error code -11

### ISSUE THREAD

**Issue by StefanoLonardi** [ablab/spades#435]
I am using SPAdes 3.14.0 - Attached the two requested files

[spades.log](https://github.com/ablab/spades/files/4136809/spades.log)

[params.txt](https://github.com/ablab/spades/files/4136806/params.txt)

Thanks,
Stefano

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Does the problem reproduce with rerun? How much free RAM is available for your SPAdes job?

**Comment by StefanoLonardi** [comment]
I have executed it three times, the last one of which a few minutes ago. SPAdes always crashes with the same error message below.

```
....
  0:01:42.203   903M / 4G    INFO   Simplification           (parallel_processing.hpp   : 167)   Removing isolated edges triggered 266764 times
  0:01:42.204   903M / 4G    INFO    General                 (simplification.cpp        : 496)   Counting average coverage
  0:01:42.213   903M / 4G    INFO    General                 (simplification.cpp        : 502)   Average coverage = 58.2583
  0:01:42.213   903M / 4G    INFO   StageManager             (stage.cpp                 : 166)   STAGE == Mismatch Correction
  0:01:42.213   903M / 4G    INFO    General                 (graph_pack.hpp            : 113)   Normalizing k-mer map. Total 404004 kmers to process
  0:01:42.301   907M / 4G    INFO    General                 (graph_pack.hpp            : 115)   Normalizing done
  0:01:50.353   927M / 4G    INFO    General                 (mismatch_shall_not_pass.hp: 195)   Finished collecting potential mismatches positions
== Error ==  system call for: "['/24-2/home/stelo/sw/SPAdes-3.14.0-Linux/bin/spades-core', '/24-2/home/stelo/pseudomonas/PS4_output2/K77/configs/config.info', '/24-2/h
ome/stelo/pseudomonas/PS4_output2/K77/configs/careful_mode.info']" finished abnormally, OS return value: -11

```

Our server has 256Gb of RAM.

**Comment by amacbride** [comment]
I'm also seeing this consistently with 3.14.0 (on a sever with 256G of RAM) -- this is an Oxford Nanopore dataset, read length is about 3K. I'm trying 3.14.1 this morning to see if that helps. After that, I may try more RAM.

**Comment by sluxlerch** [comment]
I've also been getting this error.

I'm using version 3.14.1 to assemble 739.4M total reads of 150PE Illumina RNA-seq data. I got this error earlier on the script though (see below). My guess it that this indicates it's a RAM issue.

Did running with more RAM fix the problem for anyone else?

`  1:18:01.173    22G / 23G   INFO    General                 (kmer_splitters.hpp        : 364)   Processed 4367340974 kmers
  1:24:42.374    22G / 23G   INFO    General                 (kmer_splitters.hpp        : 364)   Processed 8624923124 kmers
  1:27:42.631    22G / 23G   INFO    General                 (kmer_splitters.hpp        : 369)   Used 10509639109 kmers.
  1:27:43.539   417M / 23G   INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  1:31:01.503   167M / 23G   INFO    General                 (kmer_index_builder.hpp    : 127)   K-mer counting done. There are 10537230085 kmers in total.
  1:31:01.504   167M / 23G   INFO    General                 (kmer_index_builder.hpp    : 133)   Merging temporary buckets.
  1:36:23.488   167M / 23G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 314)   Building perfect hash indices


== Error ==  system call for: "['/opt/packages/spades/3.14.1/bin/spades-core', '/pylon5/mcz3b2p/slerch/exports_raw_reads/ribodep_367/trimmed_final/assemblies/ribo/rnaspades/K45/configs/config.info', '/pylon5/mcz3b2p/slerch/exports_raw_reads/ribodep_367/trimmed_final/assemblies/ribo/rnaspades/K45/configs/mda_mode.info', '/pylon5/mcz3b2p/slerch/exports_raw_reads/ribodep_367/trimmed_final/assemblies/ribo/rnaspades/K45/configs/rna_mode.info']" finished abnormally, OS return value: -11`

**Comment by Nilad** [comment]
Same problem with Spades (3.14.0) in shovill.

**Problem not encounter in (3.15.4)**.

**Comment by asl** [comment]
@Nilad Thanks for the confirmation
