### ISSUE TITLE
Coverage with multiple libraries

### ISSUE THREAD

**Issue by geboro** [ablab/spades#436]
Hello,
I have several genomes resulting with low coverage (~10) even when using 4 PE libraries  with >300,000 quality-filtered reads each. For a bacterial genome, I find the coverage quite low. 
So I was wondering:  is the kmer coverage in the final contigs calculated using only one of the libraries specificed with --pe ?
Cheers!

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The thing here is that coverage of the contigs is not calculated – it's emitted directly from the assembly graph used for the assembly process. So, the values are from all the libraries that contribute to the assembly.
