### ISSUE TITLE
err code: -9,  system call for: "['/usr/lib/spades/bin/hammer', '/mnt/5D5781666397A765/Adarsh/M/spades_output/Untrimmed/corrected/configs/config.info']" finished abnormally

### ISSUE THREAD

**Issue by Adarsh9311** [ablab/spades#437]
Using this command: 
metaspades -k 21,33,55,77,99,127 -1 /mnt/5D5781666397A765/Adarsh/M/R1.fastq -2 /mnt/5D5781666397A765/Adarsh/M/R2.fastq -o /mnt/5D5781666397A765/Adarsh/M/spades_output/Untrimmed

I have used this command before but  with different file, I was not getting any error.

I am now getting this error with this file
system call for: "['/usr/lib/spades/bin/hammer', '/mnt/5D5781666397A765/Adarsh/M/spades_output/Untrimmed/corrected/configs/config.info']" finished abnormally

[params.txt](https://github.com/ablab/spades/files/4143586/params.txt)
[spades.log](https://github.com/ablab/spades/files/4143587/spades.log)

**Comment by asl** [comment]
Hello

Does the issue reproduce with the latest SPAdes 3.14?

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
