### ISSUE TITLE
question about running spades

### ISSUE THREAD

**Issue by xiongqian123456789** [ablab/spades#438]
spades-core: /spades/assembler/src/common/io/reads/single_read.hpp:222: void io::SingleRead::Init(): Assertion `seq_.size() == qual_.size()' failed.

== Error ==  system call for: "['/newlustre/home/huyuxin/software/spades/SPAdes-3.13.0-Linux/bin/spades-core', '/newlustre/home/huyuxin/xq/spades/spades_output/K21/configs/config.info', '/newlustre/home/huyuxin/xq/spades/spades_output/K21/configs/careful_mode.info']" finished abnormally, err code: -6

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

You input files are corrupted – the length of sequence does not correspond to the length of quality line in one of reads.
