### ISSUE TITLE
3.14.0 build failure on Mojave gcc 9.2.0 - ctermid.h 

### ISSUE THREAD

**Issue by tseemann** [ablab/spades#439]
https://github.com/Homebrew/homebrew-core/pull/49729

```
/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include-fixed/stdio.h:222:7: error: conflicting declaration of 'char* ctermid(char*)' with 'C' linkage
  222 | char *ctermid(char *);
      |       ^~~~~~~
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:525,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/boost/config/stdlib/libstdcpp3.hpp:78,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/boost/config.hpp:49,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/boost/numeric/ublas/matrix.hpp:17,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/src/../ext/include/ConsensusCore/Matrix/DenseMatrix.hpp:42,
                 from /tmp/spades-20200203-79405-6jxzjt/SPAdes-3.14.0/ext/src/ConsensusCore/Matrix/DenseMatrix.cpp:39:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_ctermid.h:26:10: note: previous declaration with 'C++' linkage
   26 | char    *ctermid(char *);
      |          ^~~~~~~
```

**Comment by asl** [comment]
What can we do? Seems to be problem with gcc headers in brew.

**Comment by tseemann** [comment]
Have you confirmed gcc-9.2 on MacOS works outside Brew?

**Comment by asl** [comment]
Yes. The problem is that gcc has the process called "fixincludes" that during build time patches on-fly some system headers and stores the copies in the gcc's internal include directory so patched variants are included first. This is very error-prone process on Darwin as headers could change after SDK update and the "fixincluded" one would be bogus like here.

The solution is either "fix" the header inside brew or to build gcc from source, so it'd pick fresh header from SDK. Sorry, but it's not SPAdes bug at all :)

**Comment by tseemann** [comment]
Brew does build gcc from source, so I'll file this issue upstream.
Oddly it didn't have any trouble building all previous versions of spades.
Thanks for answering.

**Comment by asl** [comment]
Yes, it does. But it pre-packages header from old SDK that conflicts with the newer...

I personally just patched fixincluded header locally :)

**Comment by tseemann** [comment]
@asl our friend @sjackman figured out how to solve the problem in case you are interested

https://github.com/Homebrew/homebrew-core/pull/49729/files

**Comment by sjackman** [comment]
I definitely cannot take credit for this fix. Who did figure out how to use `libomp` with SPAdes? Was that you, Torsten?

**Comment by asl** [comment]
Yes, this should work in theory (using clang from brew, not the apple one). I must say that I rarely test this configuration :)

**Comment by sjackman** [comment]
The above PR is using `clang` from Apple along with `libomp`.

**Comment by asl** [comment]
This should be ok in general. Note, however, that Apple clang might be not ABI compatible with libomp. I do not recall examples of this though, but this is something we need to keep in mind :)
