### ISSUE TITLE
SPAdes on a cluster

### ISSUE THREAD

**Issue by SethM55** [ablab/spades#44]
Hello,

Is SPAdes 3.11.1 MPI, or some other form of distributed computing, compliant?  I'm running out of memory when I try to run my assembly on a single node in my cluster and can't find instructions for how to run it with the entire cluster's resources instead of a single node's.

- Seth

**Comment by asl** [comment]
Dear Seth,

No. Currently SPAdes requires a single large node to run on, it cannot be run on a cluster.
