### ISSUE TITLE
== Error ==  exception caught: <class 'ValueError'>

### ISSUE THREAD

**Issue by xiongqian123456789** [ablab/spades#441]
Command line: /home/u4244/anaconda3/envs/spades/bin/spades.py   -k      21,33,55,77     --careful       -1      /home/u4244/data/tb/0-ref/1-mapping/bwa_R1.fastq        -2      /home/u4244/data/tb/0-ref/1-mapping/bwa_R2.fastq        -o      /home/u4244/data/tb/0-ref/2-assembly/spades

System information:
  SPAdes version: 3.14.0
  Python version: 3.8.1
  OS: Linux-4.4.0-166-generic-x86_64-with-glibc2.10

Output dir: /home/u4244/data/tb/0-ref/2-assembly/spades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/u4244/data/tb/0-ref/1-mapping/bwa_R1.fastq']
      right reads: ['/home/u4244/data/tb/0-ref/1-mapping/bwa_R2.fastq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55, 77]
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
 Dir for temp files: /home/u4244/data/tb/0-ref/2-assembly/spades/tmp
  Threads: 16
  Memory limit (in Gb): 94

======= SPAdes pipeline started. Log can be found here: /home/u4244/data/tb/0-ref/2-assembly/spades/spades.log

max() arg is an empty sequence
Traceback (most recent call last):
  File "/home/u4244/anaconda3/envs/spades/bin/spades.py", line 589, in main
    build_pipeline(pipeline, cfg, output_files, tmp_configs_dir, dataset_data, log,
  File "/home/u4244/anaconda3/envs/spades/bin/spades.py", line 529, in build_pipeline
    spades_stage.add_to_pipeline(pipeline, get_stage, cfg, output_files, tmp_configs_dir, dataset_data, log, bin_home,
  File "/home/u4244/anaconda3/envs/spades/share/spades/spades_pipeline/stages/spades_stage.py", line 377, in add_to_pipeline
    pipeline.add(SpadesStage(cfg, get_stage, "as", output_files, tmp_configs_dir,
  File "/home/u4244/anaconda3/envs/spades/share/spades/spades_pipeline/stages/spades_stage.py", line 286, in __init__
    generateK(self.cfg, self.log, self.dataset_data)
  File "/home/u4244/anaconda3/envs/spades/share/spades/spades_pipeline/stages/spades_stage.py", line 121, in generateK
    RL = support.get_primary_max_reads_length(dataset_data, log, ["merged reads"],
  File "/home/u4244/anaconda3/envs/spades/share/spades/spades_pipeline/support.py", line 620, in get_primary_max_reads_length
    max_reads_lenghts = [get_max_reads_length(reads_file, log, num_checked) for reads_file in
  File "/home/u4244/anaconda3/envs/spades/share/spades/spades_pipeline/support.py", line 620, in <listcomp>
    max_reads_lenghts = [get_max_reads_length(reads_file, log, num_checked) for reads_file in
  File "/home/u4244/anaconda3/envs/spades/share/spades/spades_pipeline/support.py", line 651, in get_max_reads_length
    max_reads_length = max(
ValueError: max() arg is an empty sequence

== Error ==  exception caught: <class 'ValueError'>

**Comment by olga24912** [comment]
Hi @xiongqian123456789 

Thank you for your bug report and for using spades! Please, can you check that both files bwa_R1.fastq and bwa_R2.fastq are not empty?

**Comment by asl** [comment]
Please reopen if this is still an issue
