### ISSUE TITLE
merged_input files memory

### ISSUE THREAD

**Issue by ekarsalan** [ablab/spades#447]
Dear Anton,
Thanks for maintaining the list.
I am wondering if merging all input files into two mega files (Forward-Reverse) increases the memory usage of Spades during graph-building steps compared to the feeding multiple forwards and reverse files?
Thanks in advance
Arsalan

**Comment by ekarsalan** [comment]
Good day, Anton! Please ignore the message. I tested and Spades works efficiently in both cases.
Cheers

**Comment by asl** [comment]
The memory consumption does not change whether files are merged or not

**Comment by ekarsalan** [comment]
Thanks Anton! Highly appreciated!
Cheers
