### ISSUE TITLE
Build is getting failed with error code 2="null" and 255="null"

### ISSUE THREAD

**Issue by paratsa** [ablab/spades#448]
Hi All,
    
	When we are building our code we are getting the build error such as 255="null" and 2="null".
	We have no clue how to fix this build error.
	
	Please see the build error in the below mentioned log.
	
	2020-02-12 18:19:46 t-58 WARNING: Error: 255="null" when executing [C:\Clones\Exp\gtag4- 
        main\TSP_VOB\Build\bin\bldcomp.bat, libVAL, OSE]
	2020-01-09 08:50:55 t-52 WARNING: Error: 2="null" when executing 
        [G:\TSP_VOB\Build\bin\bldcomp.bat, libVAL, OSE]
	
       Here bldcomp.bat is the batch file which will invoke the make file the make file inturn will 
       invoke the make.exe,libVAL is the component to be build and the OSE is the configuration for 
       which the build is done.

      Here bldcomp.bat, libVAL and OSE is fed to the processbuilder java process as inputs, while the 
      build is going on the build(processbuilder) is interrupted with the error code 2="null" and 
      255="null"

      Please see the environment details below.

      Rhapsody 8.0.5
      Java Version 7
      Visual studio 2005
      gcc version 4.2.3	
	
	Note : 
	
	1)The configuration can be OSE,WinXP,WinCE and Lint.
	2)The Component can be Utilities,SIM,OSAL,ARCOM,FD,VAL,TRF,SVAL and MSW
	3)The build error is appearing in any component and in any configuration randomly(meaning 
            issue place is not definite).
	
	Please help us to fix this issue.
	
	Thanks in advance.

**Comment by asl** [comment]
Are you sure you're reporting a SPAdes problem?

**Comment by paratsa** [comment]
Sorry, I did not understand your question.

**Comment by asl** [comment]
Me too. If you are reporting the problem with SPAdes, then please attach the log from the console as none of
```
  Rhapsody 8.0.5
  Java Version 7
  Visual studio 2005
  gcc version 4.2.3	
```
applicable to SPAdes.

**Comment by asl** [comment]
Please reopen if you're still thinking it's a SPAdes problem.
