### ISSUE TITLE
spades-core: /spades/assembler/src/common/assembly_graph/core/debruijn_data.hpp:38: void debruijn_graph::CoverageData::inc_coverage(int): Assertion `value >= 0 || coverage_ > unsigned(-value)' failed.

### ISSUE THREAD

**Issue by jaredjurss** [ablab/spades#449]
Hello SPAdes team,

I am assembling some reads and ran into an error.  
Here is the stack trace: 

[0x40ac28]
[0x6fb145]
[0x860afe]
[0x871f84]
[0x8d4539]
spades-core: /spades/assembler/src/common/assembly_graph/core/debruijn_data.hpp:38: void debruijn_graph::CoverageData::inc_coverage(int): Assertion `value >= 0 || coverage_ > unsigned(-value)' failed.
== Error ==  system call for: "['/panfs/biopan03/apps/SPAdes/3.13.0/bin/spades-core', '/panfs/biopan03/home/jjurss/kmer_reads/assembly/K21/configs/config.info']" finished abnormally, err code: -6

I found another solution to this same error which suggested possible untrimmed adapters or poly-A but the reads have already been trimmed and a kmer analysis did not show any polyA kmers.

Thank you!
Jared

[spades.log](https://github.com/ablab/spades/files/4194927/spades.log)
[params.txt](https://github.com/ablab/spades/files/4194929/params.txt)

**Comment by asl** [comment]
Still it's likely that there might some over-represented sequenced in your data. Have you checked for them?

**Comment by jaredjurss** [comment]
I did locate some largely over represented sequences in the data.  What is the best way to go about removing them?  Is cutadapt a good option?

**Comment by asl** [comment]
Any reasonable method would certainly work :) BBtools also contains some kmer filtering tools
