### ISSUE TITLE
Read error correction finished

### ISSUE THREAD

**Issue by FengqingWang0712** [ablab/spades#450]
Dear all,
I'm a beginner. When I assembly some metagenomes, it showed like this and some of the assembly succeed but some failed. Could you please help me find out the problems? 
Error ==  something went wrong and file with corrected reads (/bioinf/home/fwang/nuohe_new/test/assembly-output/corrected/2-1073.FDMS190641995-1a.1.clean.fq.00.0_0.cor.fastq) is missing!
In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

== Error ==  system call for: "['/bioinf/home/fwang/miniconda/miniconda3/bin/python', '/bioinf/home/fwang/miniconda/miniconda3/share/spades/spades_pipeline/scripts/compress_all.py', '--input_file', '/bioinf/home/fwang/nuohe_new/test/assembly-output/corrected/corrected.yaml', '--ext_python_modules_home', '/bioinf/home/fwang/miniconda/miniconda3/share/spades', '--max_threads', '16', '--output_dir', '/bioinf/home/fwang/nuohe_new/test/assembly-output/corrected', '--gzip_output']" finished abnormally, OS return value: 1

Thanks very much.
[params.txt](https://github.com/ablab/spades/files/4204529/params.txt)
[spades.log](https://github.com/ablab/spades/files/4204530/spades.log)

**Comment by asl** [comment]
It's likely an I/O issue. Does the issue reproduce with restart? What if you'd specify --disable-gzip-output?

**Comment by FengqingWang0712** [comment]
> It's likely an I/O issue. Does the issue reproduce with restart? What if you'd specify --disable-gzip-output?
Thanks for your reply. Yes. I tried twice before submitting the issue. It's the same issue. I'll try as you suggested.

**Comment by FengqingWang0712** [comment]
> It's likely an I/O issue. Does the issue reproduce with restart? What if you'd specify --disable-gzip-output?

Hi. It seems succeed. I got the contigs.fasta file. I think there is something wrong with the .fq.gz files I input. This time, I input the unzip .fq file, it's woking. Thanks very much.
