### ISSUE TITLE
spades v.3.13.1 error loading paired-end reads in --rna mode

### ISSUE THREAD

**Issue by homeveg** [ablab/spades#451]
I am trying to make a de-novo hybrid transcriptome assembly, using a 4 Illumina paired-end libraries and 1 ONT long reads library. 
When I start Spades with the following command:
`spades.py --rna --cov-cutoff auto --nanopore ${ONTsample} --threads ${threads} --memory ${max_mem} -o ${WD}/Spades  --pe1-1 ${samples[0]}_R1_AQ20.fastq.gz --pe1-2 ${samples[0]}_R2_AQ20.fastq.gz  --pe2-1 ... `
the run fails with the error message:
> == Error ==  you cannot specify any data types except paired-end, single, trusted-contigs, untrusted-contigs in RNA-Seq mode!
No params.txt or spades.log files are created in the working directory.

I know, that libraries are indeed paired-end libraries...
I found elsewhere, that one can use a --sc mode to perform an transcriptome assembly. Therefore, I've executed the following command: 
`spades.py --sc --cov-cutoff auto --nanopore ${ONTsample} --threads ${threads} --memory ${max_mem} -o ${WD}/Spades  --pe1-1 ${samples[0]}_R1_AQ20.fastq.gz --pe1-2 ${samples[0]}_R2_AQ20.fastq.gz --pe2-1 ...`
resulting in the successful analysis start. The program have created both, params.txt and spades.log files. Below some info from the log file:

> System information:
>   SPAdes version: 3.13.1
>   Python version: 3.7.3
>   OS: Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.7.1908-Core
>   Threads: 120
>   Memory limit (in Gb): 500
> 
> Output dir: /Assembly/Spades
> Mode: read error correction and assembling
> 
> Dataset parameters:
>   Single-cell mode
>   Reads:
>     Library number: 1, library type: paired-end
>       orientation: fr
>       left reads: ['biomek_230_R1_AQ20.fastq.gz']
>       right reads: ['biomek_230_R2_AQ20.fastq.gz']
>       interlaced reads: not specified
>       single reads: not specified
>       merged reads: not specified
> Library number: 2, library type: paired-end ...
> Library number: 3, library type: paired-end ...
> Library number: 4, library type: paired-end ...
> Library number: 5, library type: nanopore ...
> 

So, any suggestions, regarding running a rnaSpades?

**Comment by andrewprzh** [comment]
Hi!

Hybrid transcriptome assembly is supported only since version 3.14.0, so I'd recommend you to try our latest release.

Although --sc option can be used, it may produce transcriptome assembly of sub-optimal quality, e.g. more chimeric contigs etc.

Best
Andrey

**Comment by homeveg** [comment]
Thanks! It was easy :)

Best,
Evgeniy

**Comment by homeveg** [comment]
So, as you suggested, I've installed a 3.14.0 version of Spades (from binary) to be able to run a --rna mode.
I run it 3 time with 2 different errors. 
1) First run with  `--threads 100 --memory 500`  results in the crash during some calculation with the OSError, complaining about lack of RAM. I've increased the memory parameter to 600 ( `--threads 100 --memory 600`) but it crashed with the very same error but at different stage of analysis. After second crash, I've changed the number of threads to 60 (providing 10GB per thread) and it solves the problem with the memory.
2) I've restarted the analysis with `--threads 60 --memory 600` and the Spades pipeline was finished with partial success:

> ===== K33 .. K77 finished
> ===== Copy files finished.
> ===== Assembling finished.
> ===== Breaking scaffolds finished.
> ===== Terminate finished.
> 
>  * Assembled transcripts are in /fungen/funhome/Assembly/Krill/Spades/transcripts.fasta
>  * Paths in the assembly graph corresponding to the transcripts are in /fungen/funhome/Assembly/Krill/Spades/transcripts.paths
>  * Assembly graph is in /fungen/funhome/Assembly/Krill/Spades/assembly_graph.fastg
>  * Assembly graph in GFA format is in /fungen/funhome/Assembly/Krill/Spades/assembly_graph_with_scaffolds.gfa
>
> [Errno 5] Input/output error
> Traceback (most recent call last):
>   File "/fungen/funhome/Software/SPAdes-3.14.0-Linux/bin/spades.py", line 609, in main
>     if not support.log_warnings(log):
>   File "/fungen/funhome/Software/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/support.py", line 402, in log_warnings
>     h.flush()
>   File "/fungen/funhome/Software/miniconda3/lib/python3.7/logging/__init__.py", line 1018, in flush
>     self.stream.flush()
> OSError: [Errno 5] Input/output error
> 
> 
> == Error ==  exception caught: <class 'OSError'>
> 

So, now I am a bit puzzled, did the run finished successfully or not? Is something missing in the results or not? 
In the Spades output folder there are following files and folders:
folders:
```
K33                 
K55
K67
K77
pipeline_state
misc
tmp
```
files:

```
assembly_graph.fastg
before_rr.fasta
input_dataset.yaml
params.txt
spades.log
transcripts.fasta
assembly_graph_with_scaffolds.gfa
dataset.info
run_spades.yaml
transcripts.paths
```

**Comment by andrewprzh** [comment]
This looks like some IO error rather than SPAdes bug. Could you try to restart your run via --continue or --restart-from?

**Comment by homeveg** [comment]
As you suggested,  I run a spades using the follwing command:
`spades.py --continue -o ${WD}/Spades`
The command executed very quickly, producing no errors. In the result, spades updated some files:
```
spades.log
run_spades.yaml
run_spades.sh
dataset.info
params.txt

```
and 2 directories: 

```
configs
tmp

```
According to log files, everything is OK, but scaffolds.fasta file is not created (should it in the --rna mode?):

> ===== Assembling started. 
> 
> ===== Skipping K33 (already processed)
> ===== Skipping K55 (already processed)
> ===== Skipping K67 (already processed)
> ===== Skipping K77 (already processed)
> ===== Skipping Copy files (already processed)
> 
> ===== Assembling finished. 
> 
> ===== Skipping Breaking scaffolds (already processed)
> ===== Skipping Terminate (already processed)
>  * Assembled transcripts are in /fungen/funhome/Assembly/Krill/Spades/transcripts.fasta
>  * Paths in the assembly graph corresponding to the transcripts are in /fungen/funhome/Assembly/Krill/Spades/transcripts.paths
>  * Assembly graph is in /fungen/funhome/Assembly/Krill/Spades/assembly_graph.fastg
>  * Assembly graph in GFA format is in /fungen/funhome/Assembly/Krill/Spades/assembly_graph_with_scaffolds.gfa
> 
> ======= SPAdes pipeline finished.
>

**Comment by andrewprzh** [comment]
Sorry for a late reply! Everything seems to be alright, rnaSPAdes outputs only transcripts.fasta, so nether contigs.fasta nor scaffolds.fasta can be found.

**Comment by homeveg** [comment]
Thanks for the support!
