### ISSUE TITLE
Error with metagenome assembly using PacBio library

### ISSUE THREAD

**Issue by kimnegrette3** [ablab/spades#452]
Hi!
I am trying to perform a metagenome assembly with SPAdes v3.14.0.
I only have seven PacBio Filtered Subreads merged in a single fastq. This is the command line I used:

spades.py --meta --pacbio -s  /hpcfs/home/Filtered_Subreads_Fastq/merged1.fastq -t 8 --only-assembler -m 60 -o /hpcfs/home/metaSPADES/PACBIO

This is the error I get:

== Error ==  Please specify option (e.g. -1, -2, -s, etc) for the following paths: /hpcfs/home/Filtered_Subreads_Fastq/merged1.fastq

I really appreciate any help. Thank you!

**Comment by asl** [comment]
Hello

First of all, I doubt that 7 pacbio reads contains a metagenome or a part of it.

Further more, per http://cab.spbu.ru/files/release3.14.0/manual.html#sec3.1:

To run SPAdes 3.14.0 you need at least one library of the following types:
  * Illumina paired-end/high-quality mate-pairs/unpaired reads
  * IonTorrent paired-end/high-quality mate-pairs/unpaired reads
  * PacBio CCS reads
...
SPAdes should not be used if only PacBio CLR, Oxford Nanopore, Sanger reads or additional contigs are available

**Comment by kimnegrette3** [comment]
Well, it’s a very low-complex metagenome. Thanks anyway.  Enviado desde Correo para Windows 10 De: Anton KorobeynikovEnviado: jueves, 20 de febrero de 2020 3:12 p. m.Para: ablab/spadesCC: kimnegrette3; AuthorAsunto: Re: [ablab/spades] Error with metagenome assembly using PacBio library (#452) HelloFirst of all, I doubt that 7 pacbio reads contains a metagenome or a part of it.Further more, per http://cab.spbu.ru/files/release3.14.0/manual.html#sec3.1:To run SPAdes 3.14.0 you need at least one library of the following types:Illumina paired-end/high-quality mate-pairs/unpaired readsIonTorrent paired-end/high-quality mate-pairs/unpaired readsPacBio CCS reads...SPAdes should not be used if only PacBio CLR, Oxford Nanopore, Sanger reads or additional contigs are available—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kimnegrette3** [comment]
Thanks for your prompt answer. 
It is a very small metagenome, four or five species, one of them eukaryote. 
As suggested, I used CCS reads this time:
spades.py --meta --s1 /hpcfs/home/CCS_Reads_Fastq/merged.ccs.fastq -t 8 --only-assembler -m 60 -o /hpcfs/home/metaSPADES/PACBIO_CCS

and I got this error:
== Error ==  you cannot specify any data types except a single paired-end library (optionally accompanied by a single library of TSLR-contigs, or PacBio reads, or Nanopore reads) in metaSPAdes mode!

How should I modify the command to rum with this type of files? Thanks!

**Comment by asl** [comment]
Well, if you're only having 7 reads and 4 or 5 species, then you do not need assembler at all – simply assign reads to species and you're done, there is nothing to assemble here.

Per error message, metaSPAdes allows only hybrid assemblies with Illumina + PacBio data.

**Comment by kimnegrette3** [comment]
Sorry for the misunderstanding...
I have seven sequencing runs (seven PacBio SMRT-cells), no seven reads.

As you said, we can not use metaSPAdes with only PacBio data. Thank you for the advice.

To solve this issue, do you think we could use one of the next approaches?:
1. Run metaSPAdes using our PacBio data and include a small data set of illumina sequencing just to simulate having a hybrid sequencing
2. Run just SPAdes (no meta) with our PacBio data.
May these approaches give us good results?

Many regards.

**Comment by AgustinPardo** [comment]
Hello, 
I join the conversation because I am trying to use SPAdes(metaSPAdes) with the same type of data (PacBio sequencing).
I find myself with the same problem. Do you think the solutions that @kimnegrette3  proposed (1,2) could be usefull?

Regards from Argentina
