### ISSUE TITLE
Documentation has incorrect name of output assembly graph file

### ISSUE THREAD

**Issue by mbhall88** [ablab/spades#453]
Hi,

I just noticed a small inconsistency in the docs. In the [Spades Output section][1] it says the assembly graph, in GFA format, is output as `<output_dir>/assembly_graph.gfa` when it is actually output as `<output_dir>/assembly_graph_with_scaffolds.gfa`.

[1]: https://github.com/ablab/spades#spades-output

**Comment by andrewprzh** [comment]
Hi! Thanks a lot for noticing, fixed. Will be included in the next release.
