### ISSUE TITLE
Regenerate scaffolds.fasta

### ISSUE THREAD

**Issue by mbhall88** [ablab/spades#454]
Hi,

Is there a way to regenerate the `scaffolds.fasta` file?  

I ran spades within a snakemake pipeline and it completed successfully. Within the snakemake rule though, after spades is finished, I was using `mv` to rename a file and that errored (due to a fault of my own). Because snakemake sees that the spades job "failed" it deletes the files that I specified as being expected output (`scaffolds.fasta`). So, I have all files *except* `scaffolds.fasta` now.  

I tried running spades with `--continue` but it didn't regenerate `scaffolds.fasta`.

**Comment by mbhall88** [comment]
Ah, reading through `run_spades.sh` I think it looks like it is actually copied to the output directory from `K127/scaffolds.fasta`? So, am I correct in saying this is exactly the same as the `scaffolds.fasta` file that will end up in the output directory?

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

No, not always. However, it might be so in your particular case depending on the options (run_spades.sh indeed could be run separately, it's an autogenerated file that represents all stages of the pipeline).
