### ISSUE TITLE
problems about the assembly

### ISSUE THREAD

**Issue by quliping** [ablab/spades#457]
Hello, really need your help. I assembled my genomes with illumina and nanopore reads. First I  trim my reads using trimmomatic and then I assembled them using SPAdes. But every genome was too large. The normal size is 4-5M but my results could reach 7-8M. Here are log file and graph file of one of my samples. It seems like there are two problems. First, there are many short contigs in the assembly. Second, Bandage show me two big circles and it shoule be one. Thank you very much!
[Desktop (2).zip](https://github.com/ablab/spades/files/4259874/Desktop.2.zip)

**Comment by asl** [comment]
Hello

This looks like a contamination. You may want to analyze your contigs to see what's inside.
