### ISSUE TITLE
 The reads contain too many k-mers to fit into available memory Issue

### ISSUE THREAD

**Issue by bioramg** [ablab/spades#461]
Dear sir,
As suggested earlier, I run spades after using bbmap trimming command. My server is a maximum of 188 GB RAM only. How can I run this assembly?

I received an error message like this:

2:05:04.864 5G / 89G INFO General (kmer_index_builder.hpp : 150) Merging final buckets.
2:16:20.748 5G / 89G INFO K-mer Index Building (kmer_index_builder.hpp : 336) Index built. Total 4941279872 bytes occupied (3.70963 bits per kmer).
2:16:21.969 5G / 89G ERROR K-mer Counting (kmer_data.cpp : 348) The reads contain too many k-mers to fit into available memory. You need approx. 396.971GB of free RAM to assemble your dataset

== Error == system call for: "['/home/pmslab/Desktop/Raman/bin/SPAdes-3.14.0-Linux/bin/spades-hammer', '/home/pmslab/Desktop/Raman/Convallaria_mt/keis_hy_asm_3_2_2020/corrected/configs/config.info']" finished abnormally, OS return value: 255

Is there any other tool to use less amount of RAM for this hybrid assembly?
Thank you.

**Comment by asl** [comment]
Well, you're really out of RAM. You may want to perform heavy quality trimming / normalization with the understanding that results might be suboptimal.
