### ISSUE TITLE
failure to run

### ISSUE THREAD

**Issue by Tr1sh** [ablab/spades#462]
== Error ==  the number of files with left paired reads is not equal to the number of files with right paired reads (library number: 1, library type: paired-end)!

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

Will you please let us know what is unclear in the error message?

Thanks!
