### ISSUE TITLE
Spades Error with PacBio reads

### ISSUE THREAD

**Issue by azrasid** [ablab/spades#464]
Hi,
 I am running spades on PacBio reads alone: 
`python3 spades.py --s1 --pacbio pacbio_ccs.fastq -o test2`

I am getting the following error:
== Error ==  Please specify option (e.g. -1, -2, -s, etc) for the following paths: pacbio_ccs.fastq

I would also like to input both short reads and PacBio reads to SPAdes for a hybrid assembly. Can you help provide a test command I can use for this?

Please can you help me with the commands to the above problems.

**Comment by asl** [comment]
Hello

Per SPAdes manual (http://cab.spbu.ru/files/release3.14.0/manual.html#sec3.1):

"PacBio CCS/Reads of Insert reads or pre-corrected (using third-party software) PacBio CLR / Oxford Nanopore reads can be simply provided as single reads to SPAdes".

and

"
--pacbio <file_name>
    File with PacBio CLR reads. For PacBio CCS reads use -s option. More information on PacBio reads is provided in section 3.1.
"

Please also refer to SPAdes manual for the example command lines with different options
