### ISSUE TITLE
bbmap/kmercountexact.sh: line 138: 30199 Killed   

### ISSUE THREAD

**Issue by bioramg** [ablab/spades#466]
Hi,
I have used this command to estimate genome size using the following command:
java -ea -Xmx188g -Xms188g -cp /home/pmslab/Desktop/Raman/bin/bin/bbmap/current/ jgi.KmerCountExact in=trim_CKEMJ1.fastq in2=trim_CKEMJ2.fastq khist=khist_trim_CKEMJ.txt peaks=peaks_trim_CKEMJ.txt -Xmx188g

But i got an error message:
./../bin/bin/bbmap/kmercountexact.sh: line 138: 30199 Killed    

What could be the problem?

**Comment by asl** [comment]
No idea as SPAdes is not involved here. You'd better ask bbmap folks.
