### ISSUE TITLE
Problem with spades crashing while using it in unicycler

### ISSUE THREAD

**Issue by dikshyantg** [ablab/spades#467]
My name is Dikshyant and I am trying to run multiple pair read illumina assembly for a bacteria genome using unicycler which uses spades but the spades is freaking out and crashing . is it because I am using multiple pair read illumina assembly , which I have merged into a single pair ? Thanks
[spades.log](https://github.com/ablab/spades/files/4296586/spades.log)

**Comment by asl** [comment]
Hello

The log reads:
```
[0x408f21]
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/assembler/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So, you're running out of RAM
