### ISSUE TITLE
Determining reason for low quality assembly

### ISSUE THREAD

**Issue by soungalo** [ablab/spades#471]
Hello,
I am running SPAdes v3.14.0 to assemble multiple varieties (individuals) of the same plant species (A. thaliana - estimated genome size 135Mb). The data (fastq) originate from public DBs (SRA/ENA), with slightly different data sets for each variety. For most varieties, results are more than satisfying. However, some varieties end up with poor results in terms of N50 and BUSCO scores.
For example, I have two data sets which are pretty similar in terms of data coverage and read length - both have a single PE library, ~x40 coverage and read length of 51. I apply the same preprocessing steps to both data sets (trimmomatic for quality trimming and FLASH for PE read merging) and then run SPAdes with the same parameters. However, with one data set I get N50 of 13.5k and 95% complete BUSCOs, while the other one has N50 3.7k and 80% complete BUSCOs.
I ran FastQC on the raw data, but everything seems to be fine and high quality for both data sets. Also no significant difference in the fraction of reads filtered/merged during preprocessing.

Since these are genomes of the same species, I don't believe there is something in the genomic sequence of the specific variety that should make it much harder to assemble. Therefore, this probably has something to do with the data, but how can I tell exactly what went wrong? Any ideas for others things to check either regarding the raw data or the assembly process?
The only problems I could think of are sample contamination and heterozygosity. How can I check for these?
Please find attached the run params.txt and spades.log. LMK if you'd like to see other files.
[params.txt](https://github.com/ablab/spades/files/4305808/params.txt)
[spades.log](https://github.com/ablab/spades/files/4305809/spades.log)

Thanks a lot!

**Comment by asl** [comment]
You're having reads of only 50 bp. Therefore the poor assembly results are more than expected. Coverage is also quite low – approx 20x on average.

**Comment by soungalo** [comment]
Thanks for the quick reply. I agree, and if all runs of the type would have produced similar results, I
 wouldn't be asking. However, since I get very different results with similar data, I thought that there might be something else going on and maybe some tweaking of parameters could improve results. I am not expecting a high quality assembly with such data, just something containing >90% of the genes.
Here are the params and log for the other run that produced much better results.
[params.txt](https://github.com/ablab/spades/files/4305883/params.txt)
[spades.log](https://github.com/ablab/spades/files/4305884/spades.log)
