### ISSUE TITLE
Error: finished abnormally, OS return value: -9 on metagenomics datas

### ISSUE THREAD

**Issue by propan2one** [ablab/spades#472]
Hi guys.
I'm working on several WGS metagenomics dataset with a fastq size of 22G with 74,000,000 seqs on average for each R1 and R2 (paired reads, 150bp).
I am getting this error : `finished abnormally, OS return value: -9`

I did my best to try to resolve the error without success. Interestingly when I subsampled my reads (using the command bellow), I manage to have the expected result, we have an organism that we assemble regularly to compare. With this results I am afraid that the complexity of the sample to be assembled may be too great..
```bash
seqtk sample -s100 ${reads1} 300000 > sub1.fastq
seqtk sample -s100 ${reads2} 300000 > sub2.fastq
```

Due to others post with similar error I launched with SPAdes with 340G to be sure it's wasn't a RAM problem.

Could you please help me find what’s going wrong? I have attached logfile, param file and conda env listFile.

[spades.log](https://github.com/ablab/spades/files/4306327/spades.log)
[params.txt](https://github.com/ablab/spades/files/4306328/params.txt)
[SPAdes_env.txt](https://github.com/ablab/spades/files/4306325/SPAdes_env.txt)

The commande line look like this, where `unmappedFastq*` are fastq files from bowtie2 alignment which not match the host genome.
```bash
if [ -s "${outdir}/${ID}/${spadesOut}/spades.log" ]; then
            echo -e '\nAssemblage continue where it fail before... \n'
            spades.py -o ${spadesOut} \
                --restart-from last \
                -t $NCPUS \
                -m $MEM \
                &> ${basefile}_spades.log
else
            echo -e '\nCreating contigs with spades... \n' >> $logfile
            spades.py \
                --memory $MEM \
                -t $NCPUS \
                --pe1-1 $unmappedFastq1 \
                --pe1-2 $unmappedFastq2 \
                --pe1-s $unmappedFastqS \
                --meta \
                --only-assembler \
                -o ${spadesOut} &> ${basefile}_spades.log
fi
```

Many thanks in advance
Propan2one

**Comment by marcomeola** [comment]
@propan2one, got the same error. Could you solve the issue? Was it a RAM problem?

**Comment by asl** [comment]
@propan2one You may want to give the latest SPAdes 3.15 a try. Please reopen if the problem still exists.

**Comment by dluecking** [comment]
@asl Same error in SPAdes 3.15:

```
metaspades.py -1 <sample>_R1_trimmed.fq.gz -2 <sample>_R2_trimmed.fq.gz -t 40 -m 400 --only-assembler -o assembly
```
ran without error for 2h 50m before finishing with the following error message:
```
finished abnormally, OS return value: -9
```

Details about my run:
- SPAdes version: 3.15
- installed via conda
- meta flag
- trimmed with trimmomatic beforehand resulting in: 
- 15,719,790 reads 

Am I doing something wrong?

Thanks

**Comment by asl** [comment]
@dluecking Yes. Please do not hijack old issues. Open a new one.

**Comment by dluecking** [comment]
Ah sorry, thought this is connected enough.
Will remove and open a new one.
