### ISSUE TITLE
Contig polishing tools stopped abruptly - Reg.

### ISSUE THREAD

**Issue by bioramg** [ablab/spades#474]
Hi,
I am doing a hybrid assembly with both Illumina and nanopore raw data sequences. I can able to get K33, 55 and 77. Afterward, it started to run the contig polishing tool and stopped abruptly.

Could you please suggest me what could be the problem? I am herewith enclosing spades.log file for your reference. Please find the attachment.

I have used the following command for this assembly.

$ ./spades.py --pe1-1 Ill_read1.fastq --pe1-2 Ill_read2.fastq --nanopore ONTread.fasta --careful -o ./hyb_asm -m 188

I have a few more questions:
1. If I want to trim adapters on pair-end of Illumina reads, should I use ktrim=r for forward read and ktrim=l for reverse read?

2. Can I use --careful option for the assembly of plant mitochondrial genomes? Normally plant mitochondrial genome contain a lot of repeat regions.

I need suggestions from you. 

Thank you.

[spades.log](https://github.com/ablab/spades/files/4315673/spades.log)

**Comment by asl** [comment]
Hello

Does the problem reproduce if you'd restart?

> If I want to trim adapters on pair-end of Illumina reads, should I use ktrim=r for forward read and ktrim=l for reverse read?

No idea as these are not SPAdes options

> Can I use --careful option for the assembly of plant mitochondrial genomes? Normally plant mitochondrial genome contain a lot of repeat regions.

Then it might be better just to skip the mismatch correction step as the read alignment back to the contigs might be suboptimal

**Comment by bioramg** [comment]
Thank you.. I used --continue option and its running fine... 

Ok fine. I will skip this option and do the assembly again.

Thank you for your valuable comments.
