### ISSUE TITLE
Failed to determine offset

### ISSUE THREAD

**Issue by hygine** [ablab/spades#476]
# 组装 + 16S预测 + 16S blast
2020-03-18 12:57:01:	sh /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/work_sh/assembly.sh && touch /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/work_sh/assembly.sh.done

== Warning ==  No assembly mode was sepcified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option.

Command line: /share/nas1/linhj/bin/software/SPAdes-3.14.0-Linux/bin//spades.py	-k	21,33,55,77,99	--careful	--pe1-1	/share/nas1/linhj/bin/pollution_check/R01_test/R01/Bacteria_X972-01-R01_good_1.fq	--pe1-2	/share/nas1/linhj/bin/pollution_check/R01_test/R01/Bacteria_X972-01-R01_good_2.fq	-o	/share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly

System information:
  SPAdes version: 3.14.0
  Python version: 2.7.8
  OS: Linux-2.6.32-431.11.2.el6.x86_64-x86_64-with-centos-6.5-Final

Output dir: /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/share/nas1/linhj/bin/pollution_check/R01_test/R01/Bacteria_X972-01-R01_good_1.fq']
      right reads: ['/share/nas1/linhj/bin/pollution_check/R01_test/R01/Bacteria_X972-01-R01_good_2.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55, 77, 99]
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/tmp
  Threads: 16
  Memory limit (in Gb): 125

======= SPAdes pipeline started. Log can be found here: /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/spades.log

/share/nas1/linhj/bin/pollution_check/R01_test/R01/Bacteria_X972-01-R01_good_2.fq: max reads length: 150
/share/nas1/linhj/bin/pollution_check/R01_test/R01/Bacteria_X972-01-R01_good_1.fq: max reads length: 150

Reads length: 150

===== Read error correction started.

===== Read error correction started.

== Running: /share/nas1/linhj/bin/software/SPAdes-3.14.0-Linux/bin/spades-hammer /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/corrected/configs/config.info

  0:00:00.079     8M / 11M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.14.0, git revision c831f9be30a4364383cd4ebe5b78cdfcaad1acc9
  0:00:00.687     8M / 11M   INFO    General                 (main.cpp                  :  76)   Loading config from /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/corrected/configs/config.info
  0:00:00.967     8M / 12M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 16
  0:00:00.967     8M / 12M   INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 125 Gb
  0:00:00.967     8M / 12M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  **0:00:01.271     8M / 12M   ERROR   General                 (main.cpp                  :  89)   Failed to determine offset! Specify it manually and restart, please!**

== Error ==  system call for: "['/share/nas1/linhj/bin/software/SPAdes-3.14.0-Linux/bin/spades-hammer', '/share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/corrected/configs/config.info']" finished abnormally, OS return value: 255

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/spades.log

Thank you for using SPAdes!
2020-03-18 12:57:09:	Error: command fail: sh /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/work_sh/assembly.sh && touch /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/work_sh/assembly.sh.done
2020-03-18 12:57:09:	Elaseped time: 8s

**Comment by hygine** [comment]
`$cat /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/corrected/configs/config.info`
; = HAMMER =
; input options: working dir, input files, offset, and possibly kmers
dataset /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/input_dataset.yaml
input_working_dir /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/tmp/hammer_V6Mn1L
input_trim_quality			4
input_qvoffset
output_dir /share/nas1/linhj/bin/pollution_check/R01_test/new_test2_R01/assembly/corrected

; == HAMMER GENERAL ==
; general options
general_do_everything_after_first_iteration	1
general_hard_memory_limit 125
general_max_nthreads 16
general_tau			1
general_max_iterations 1
general_debug			0

; count k-mers
count_do				1
count_numfiles				16
count_merge_nthreads 16
count_split_buffer			0
count_filter_singletons                 0

; hamming graph clustering
hamming_do				1
hamming_blocksize_quadratic_threshold	50

; bayesian subclustering
bayes_do				1
bayes_nthreads 16
bayes_singleton_threshold		0.995
bayes_nonsingleton_threshold		0.9
bayes_use_hamming_dist			0
bayes_discard_only_singletons		0
bayes_debug_output			0
bayes_hammer_mode			0
bayes_write_solid_kmers			0
bayes_write_bad_kmers			0
bayes_initial_refine                    1

; iterative expansion step
expand_do				1
expand_max_iterations			25
expand_nthreads 16
expand_write_each_iteration		0
expand_write_kmers_result		0

; read correction
correct_do				1
correct_discard_bad			0
correct_use_threshold			1
correct_threshold			0.98
correct_nthreads 16
correct_readbuffer			100000
correct_stats                           1

**Comment by asl** [comment]
Your input files are likely to be corrupted as SPAdes is unable to determine the Phred FASTQ offset

**Comment by hygine** [comment]
ok，thank you。
