### ISSUE TITLE
Warning error while running Nanopore and Illumina reads 

### ISSUE THREAD

**Issue by bioramg** [ablab/spades#477]
Hi,
I tried to assemble the plant mitochondrial genome using both Illumina and nanopore reads.
I can able to get contigs but getting the same warning log at the end. 

Please suggest me what could be the problem.
Thank you.
[spades.log](https://github.com/ablab/spades/files/4352803/spades.log)
[warnings.log](https://github.com/ablab/spades/files/4352804/warnings.log)

**Comment by asl** [comment]
Hello

You're having uneven coverage, however assembling in normal multicell mode that assumes that coverage is even. The assembly then can be suboptimal. Hence the warning
