### ISSUE TITLE
metaspades, mismatch_shall_not_pass, Failed with -11

### ISSUE THREAD

**Issue by hjruscheweyh** [ablab/spades#478]
Hi!

I'm experiencing an error with one specific metagenomic dataset in the K55 step. 

I have tried to run 3.12, 3.13 and 3.14. The error persists. Memory shouldn't be an issue (1.1TB)

I have attached the params and spades.log file for the 3.14 run. 

Do you have any explanation?

Thank you for your help in advance.

Hans

[params.txt](https://github.com/ablab/spades/files/4355196/params.txt)
[spades.log](https://github.com/ablab/spades/files/4355198/spades.log)

**Comment by hjruscheweyh** [comment]
So the problem seems to be caused by the `singlereadstream` class. The assembly finishes if I leave the singleton reads out. Do you have an explanation for this?

If you want I can share the reads with you to test.

hans

**Comment by asl** [comment]
Unfortunately, not so, as removing some of reads effectively changes everything in terms of graph, etc.

Having a reproducer would certainly help

**Comment by hjruscheweyh** [comment]
You should get a mail from `cifex.ethz.ch` where you can download the 4 files (r1, r2, singletons, merged). This is not the exact same dataset but a public one which also fails with the same error. Let me know if you can reproduce the error or need any help.

The error appears after ~10 minutes in K55
Thanks,
Hans

**Comment by asl** [comment]
Thanks. Reproduced and fix will be included into SPAdes 3.14.1

**Comment by hjruscheweyh** [comment]
Great
Thanks
