### ISSUE TITLE
Any suggestion for using spades on 50bp read length sequence

### ISSUE THREAD

**Issue by abcdtree** [ablab/spades#479]
I am trying to use spade on 50bp read length sequence instead of 150bp. 
I found the result is not as good as the 150bp cases.
Do you have any recommendation on settings or parameters or pre-jobs to help to ensure the assembly quality?
(I have tried to set the kmer as [21,25,29,33,37])
Thanks, 

Josh

**Comment by asl** [comment]
Hello

Well, this is pretty much expected as your reads are 3 times shorter. Using default parameters would be sufficient, it's highly unlikely something significantly better could be done.
