### ISSUE TITLE
paired-end file not found when running on a cluster

### ISSUE THREAD

**Issue by newlbs** [ablab/spades#48]
Hi, I have been having some errors when I tried to submit the job to a slurm cluster. It seems to run fine if I start the assembly on login lode. However, when I submit the job to standard node, it fails with the follows error:
"== Error ==  file not found......(right reads, library number: 1, library type: paired-end)"

There were not params.txt or spades.log files created. This error is printed to the stdout.

**Comment by asl** [comment]
Well, you'd need to make sure that the file indeed is accessible. You may want to consult your system administrator wrt the file access on cluster.

Keep in mind that SPAdes will be able to utilize single node only, it is not suitable for running of a cluster.
