### ISSUE TITLE
metaspades error code -9 

### ISSUE THREAD

**Issue by reymonera** [ablab/spades#480]
Hi, 

I'm running the following metaspades code in a server:

```
a=3

for (( c=1; c<$a; c++ )); do 

spades.py --meta  \
  -1 $c-*-R1_bowtie.fastq \
  -2 $c-*-R2_bowtie.fastq  \
  --memory 10\
  --threads 1\
  -o $c-assembly ; done 
```
I want to assemble 2 samples.
However, I'm getting the error code: -9

Now, I know this is what you get when you're running out of RAM. However, I performed a free command. And this is what I get:

`free --giga`
```
              total        used        free      shared  buff/cache   available
Mem:             31           1           0           0          29          27
Swap:             7           0           6

```
Seems I have enough ram available for performing the assembly. Any idea what parameter I'll have to change for performing this assembly? Thanks!

I'll attach the spades.log for one of the samples:
[spades.log](https://github.com/ablab/spades/files/4358018/spades.log)

**Comment by asl** [comment]
Hello

Does the problem reproduce with SPAdes 3.14?

**Comment by reymonera** [comment]
Hi,

SPAdes 3.13 is the latest version of the software available at this server. 

Thanks for the reply!

**Comment by XiaowuBioinformatics** [comment]
Hi Reymonera. I got the same issue. Have you fixed it?

**Comment by asl** [comment]
Please reopen if this is still an issue
