### ISSUE TITLE
No final contigs in the out folder

### ISSUE THREAD

**Issue by karlnyr** [ablab/spades#483]
I have been attempting to assemble a metagenome using SPAdes. SPAdes seems to finish all k-mers (21,33,55) and states that it is finished. However, the finishing step, where spades create a final_contig.fasta in the out-folder seems to have been skipped. By looking through the spades.log and files I find some "final" files in the K55 folder. Are these the final files or is there one more step that has gone missing?

[params.txt](https://github.com/ablab/spades/files/4402786/params.txt)
[spades.log](https://github.com/ablab/spades/files/4402787/spades.log)

**Comment by asl** [comment]
Hello

No, SPAdes is not fully finished yet. Did something kill you SPAdes job?

**Comment by karlnyr** [comment]
It very likely that the HPCC timed the job out at the final step. However, the report from that cluster is gone, thus I was wondering whether the job was finished or not.

Thank you for the quick response.

**Comment by asl** [comment]
You could give --continue a try

**Comment by karlnyr** [comment]
Will do
