### ISSUE TITLE
Should genome assembly be used for --fl-rna with rnaspades.py? 

### ISSUE THREAD

**Issue by jolespin** [ablab/spades#484]
I just noticed the following parameter:

```
--fl-rna <file_name>
    File with PacBio/Nanopore/contigs that capture full-length transcripts.
```

I'm using v3.14.0 and was wondering if I should be using --fl-rna with my genome assembly?

**Comment by asl** [comment]
Hello

Thank you for your interest in rnaSPAdes.

Well, genome assembly is certainly different from RNA transcripts. So, no, you should not use this option with your genome assembly.

**Comment by jolespin** [comment]
Ok thank you.  That was my initial thought but when it said "contigs" I wasn't sure if tried to use genomic contigs to help construct transcripts.
