### ISSUE TITLE
Does --s have the same effect of concatenating the *.fastq files?

### ISSUE THREAD

**Issue by felselva** [ablab/spades#485]
Hello,

I am looking for some help to use the best approach to assembly multiple transcriptome libraries, from different sources (different projects), same species.

Let's say this is my set of files:
```
Seqs_A_1.fastq    Seqs_A_2.fastq
Seqs_B_1.fastq    Seqs_B_2.fastq
Seqs_C_1.fastq    Seqs_C_2.fastq
Seqs_D_1.fastq    Seqs_D_2.fastq
Seqs_E_1.fastq    Seqs_E_2.fastq
Seqs_F_1.fastq    Seqs_F_2.fastq
```

First, since they are from different sources, they might differ in quality and in their spacer. I found `--s #` option, and I thought I could use to do the following:

```
--s 1 Seqs_A_1.fastq --s 2 Seqs_A_2.fastq --s 3 Seqs_B_1.fastq \
    --s 4 Seqs_B_2.fastq --s 5 Seqs_C_1.fastq --s 6 Seqs_C_2.fastq \
    --s 7 Seqs_D_1.fastq --s 8 Seqs_D_2.fastq --s 9 Seqs_E_1.fastq \
    --s 10 Seqs_E_2.fastq --s 11 Seqs_F_1.fastq --s 12 Seqs_F_2.fastq
```

Except the option only allows up to 9 files. Will `cat *.fastq > All.fastq` have the same effect as above if using the option `-s All.fastq`?

Thanks in advance, and for the great software!

**Comment by asl** [comment]
Hello

First of all, you could certainly provide any number of libraries using dataset description YAML file. Next, yes, in this particular case concatenating all files into one will provide the same behavior
