### ISSUE TITLE
SPAdes error code -6

### ISSUE THREAD

**Issue by jade-davies** [ablab/spades#486]
Hello,

I am trying to run assembly; the K21 section worked fine, but on the K33 I have had this error code (please see attached).

[assembly_array_output.txt](https://github.com/ablab/spades/files/4449964/assembly_array_output.txt)
[spades.log](https://github.com/ablab/spades/files/4449965/spades.log)

I have attached the assembly_array output SLURM file and also the spades.log

How can I fix this?

Thank you,
Jade

**Comment by asl** [comment]
Hello

Will you pleaser provide your spades.log / params.txt file?

**Comment by jade-davies** [comment]
> Hello
> 
> Will you please provide your spades.log / params.txt file?

Hello,

I have attached the spades.log in the original post now. Thank you

**Comment by asl** [comment]
Are you running multiple jobs using the same output folder?

**Comment by jade-davies** [comment]
Yes that's right, I  was running a parallel array job with 61 samples

**Comment by asl** [comment]
Well... this is not going to work. You need to give each sample separate output directory
