### ISSUE TITLE
Merged paired-end assembly

### ISSUE THREAD

**Issue by ireneortega** [ablab/spades#487]
I have a question regarding merged paired-ends. I have a fastq file containing the extended reads that I got from FLASH and I am not sure if the command I am using is correct. I know this is what it is called "merged" reads in SPAdes manual but I do not know how to provide “Non-empty files with (remaining) unmerged left/right reads (separate)”. This is the command I am using:  

**--merged sample.extendedFrags.fastq -1 sample.notCombined_1.fastq -2 sample.notCombined_2.fastq**

and the execution says 

Files with merged reads were ignored

just after 

======= SPAdes pipeline started. Log can be found here: 

So I do not know if the file sample.extendedFrags.fastq is really being used by SPAdes.

Thanks!

**Comment by asl** [comment]
Hello

Will you please provide us your spades.log file?

**Comment by ireneortega** [comment]
There you have. Thanks!!!

Irene
De: Anton Korobeynikov <notifications@github.com>
Enviado el: miércoles, 8 de abril de 2020 14:49
Para: ablab/spades <spades@noreply.github.com>
CC: IRENE ORTEGA SANZ <iortega@ubu.es>; Author <author@noreply.github.com>
Asunto: Re: [ablab/spades] Merged paired-end assembly (#487)


Hello

Will you please provide us your spades.log file?

**Comment by ireneortega** [comment]
[spades.log](https://github.com/ablab/spades/files/4450636/spades.log)

There you have. Thanks!

**Comment by asl** [comment]
Nothing was ignored. The file with merged reads was skipped when SPAdes determined the read length for obvious reasons
