### ISSUE TITLE
Are there BayesHammer versions?

### ISSUE THREAD

**Issue by Roman-Si** [ablab/spades#488]
Hello everyone, 

I used Spades 3.13.0 for a genome assembly with the BayesHammer error correction module and i have been asked by the reviewers of our manuscript which version of BayesHammer was used. I have searched a bit but could not any information about the bayeshammer versions. Is there such a thing?

Thank you in advance, 
Romanos

**Comment by asl** [comment]
BayesHammer is a part of SPAdes. So you could simple say "BayesHammer as bundled with SPAdes 3.13.0"
