### ISSUE TITLE
error during Compressing corrected reads (with gzip)

### ISSUE THREAD

**Issue by binshuangli** [ablab/spades#49]
During a hybrid assembly with Illumina, Pacbio and Nanopore reads, I encountered the following error:
```
== Error ==  system call for: "['gzip', '-f', '-7', '/gpfs/fs2/scratch/bli16/SPAdes/P212_ai_PB_NP_spades/corrected/P212_ai.read1.00.0_0.cor.fastq']" finished abnormally, err code:
 1
```
Not sure is it because of some dependcy issues or something else. The related files are attached. Please let me know if you need further info. Thank you.

[warnings.log](https://github.com/ablab/spades/files/1492246/warnings.log)
[spades.log](https://github.com/ablab/spades/files/1492247/spades.log)
[params.txt](https://github.com/ablab/spades/files/1492248/params.txt)

**Comment by asl** [comment]
Well, it seems that gzip failed on your system due to some reason. Most probably there was some I/O error (e.g. lack of free disk space).

**Comment by hariszaf** [comment]
Hi! 

I have a similar issue!  And here's the thing! 

When I execute this command by a .sh file it's ok.  However, when I do it as a SLURM job, i get this error here: 

'''
== Error ==  system call for: "['gzip', '-f', '-7', '/mnt/testingSingularity/3.correct_by_BayesHammer/ERR1906853/corrected/filtered_max_ERR1906853_2.fastq.gz.2P.fastq.00.0_0.cor.fastq']" finished abnormally, err code: 127
'''

It 's really weird as it is the exact same thing!! I do have gzip on my environment and its permissions are fine. From command line it works, as a job it doesn't!

Do you have any idea what could be wrong? 

Thank you very much for all your time and help,
Haris

**Comment by asl** [comment]
You may want to ask the administrators of your server. You may want to check your environment, etc. as error code 127 is usually returned by shell when a command / program is not found.

**Comment by hariszaf** [comment]
Is there a specific path where spades is looking for gzip? 

If I try to install in on my own, where is the best to do so? 

Thank you very much for the quick reply!

**Comment by asl** [comment]
Nothing special. SPAdes uses your operating system facilities to run sub-tasks. We have no idea about the specifics of your cluster, so please contact your system administrator for this.
