### ISSUE TITLE
Assembling long Illumina paired reads (2x300)

### ISSUE THREAD

**Issue by ireneortega** [ablab/spades#491]
Hello,

I sequenced bacteria using Illumina 2x300. SPAdes manual recommends using --careful option with long Illumina reads. But the log file warns me " Your data seems to have high uniform coverage depth. It is strongly recommended to use --isolate option". And I can't use both options at the same time. What should I do?

Thanks!

**Comment by asl** [comment]
--isolate implies --careful

**Comment by ireneortega** [comment]
Not sure if careful mode is included in isolate mode. Log file says:
Mismatch careful mode is turned OFF
MismatchCorrector will be SKIPPED. SPades manual says "Do not turn off SPAdes error correction"
