### ISSUE TITLE
Coverage value split between isoforms/similar transcripts?

### ISSUE THREAD

**Issue by NBaileyNCL** [ablab/spades#493]
Hi,

How is the coverage calculated for assembled transcripts in rnaSPAdes.

If you have 2 very similar assembled transcripts/isoforms, which is the case

Reads assembled to produce the transcripts be split between them

Reads which could ambiguously align to either transcript are counted in the coverage of both

**Comment by andrewprzh** [comment]
Hi,

In SPAdes (and in rnaSPAdes) coverage is calculated  as the average coverage for the entire path. So, if two paths share an edge, it will be counted twice (once in each path). So, the last statement is the closest one.

Note that coverage reported by SPAdes is a k-mer coverage, the read coverage. To obtain true read counts I suggest to remap reads back to the assembly.

**Comment by NBaileyNCL** [comment]
Thanks for the help this has answered my question
