### ISSUE TITLE
Spades 3.11 err code: -6 for k=61

### ISSUE THREAD

**Issue by npavlovikj** [ablab/spades#50]
Hi,

I have run **spades 3.11 without error correction** with wide range of k-mers (_19, 21, 23, 25, 27, 31, 35, 39, 41, 43, 45, 47, 51, 55, 59, 61, 63, 67, 71, 81, 91_) on **48.8GB large data** (47GB interleaved Illumina paired-end reads + 1.8GB Illumina single-end reads).
I was able to successfully get the results for all k-mer values, except for one, **61**.
I ran this job twice, and I got the same error:
_spades: /spades/src/common/modules/path_extend/weight_counter.hpp:295: virtual double path_extend::CoverageAwareIdealInfoProvider::EstimatePathCoverage(const path_extend::BidirectionalPath&) const: Assertion `path.Length() > 0' failed.
== Error ==  system call for: "['/util/opt/anaconda/4.3.11/envs/spades-3.11.0/share/spades-3.11.0-0/bin/spades', '/results/spades/311/no_ec/k_61/K61/configs/config.info', '/results/spades/311/no_ec/k_61/K61/configs/mda_mode.info', '/results/spades/311/no_ec/k_61/K61/configs/rna_mode.info']" finished abnormally, err code: -6_

The total memory used by the job is ~233GB, and I am requesting 980GB from my cluster with -m 950.
I don't know why this error occurs for this particular k value only, so I would appreciate any help.
Please find the attachments below:
[params.txt](https://github.com/ablab/spades/files/1503308/params.txt)
[spades.log](https://github.com/ablab/spades/files/1503311/spades.log)

Thank you,
Natasha

**Comment by asl** [comment]
Hello

Please update to the latest SPAdes 3.11.1 where this particular issue is fixed

**Comment by npavlovikj** [comment]
Dear @asl ,

Thank you so much for your prompt reply.
I used SPAdes 3.11. as suggested.
However, after 15 hours of running, I got the exact same error from above.

Thank you,
Natasha

**Comment by asl** [comment]
This issue was fixed in SPAdes 3.11.1, you're using SPAdes 3.11.0.

**Comment by npavlovikj** [comment]
I am sorry, I should have pasted the new error with SPAdes 3,11.1:
_spades: /tools/SPAdes-3.11.1/src/common/modules/path_extend/weight_counter.hpp:295: virtual double path_extend::CoverageAwareIdealInfoProvider::EstimatePathCoverage(const path_extend::BidirectionalPath&) const: Assertion `path.Length() > 0' failed.
== Error ==  system call for: "['/.conda/envs/spades-3.11.1/bin/spades', '/results/spades/311/no_ec/k_61/K61/configs/config.info', '/results/spades/311/no_ec/k_61/K61/configs/mda_mode.info', '/results/spades/311/no_ec/k_61/K61/configs/rna_mode.info']" finished abnormally, err code: -6_

I downloaded the source code for SPAdes 3.11.1 from http://cab.spbu.ru/software/spades/, and installed it per instructions. The md5sum is "**478677b560e2f98db025e8efd5245cdf**  SPAdes-3.11.1.tar.gz".

Thank you,
Natasha
