### ISSUE TITLE
issue err code: -11

### ISSUE THREAD

**Issue by XiaoqiongGu** [ablab/spades#500]
Hi Sir,

I run the spades on one sample (both forward and reverse files), 
the issues come out suggesting err code: -11.
can you please have a check on the spades.log file I uploaded?

Thanks,
Shirley
[spades.log](https://github.com/ablab/spades/files/4572789/spades.log)

**Comment by asl** [comment]
Hello

Are you using pre-built binaries or downloaded SPAdes by yourself?

**Comment by XiaoqiongGu** [comment]
Hi,

I just use anaconda2 to install spades (v3.13.1) and put under one of the environment. Is that a issue?

Thanks,
Shirley

**Comment by asl** [comment]
I would suggest you to contact conda folks as we do not maintain these packages. Most likely the packages were built using the target features that are not available on your system. Tagging @notestaff
