### ISSUE TITLE
How to make scaffold?

### ISSUE THREAD

**Issue by bioramg** [ablab/spades#504]
Hi,
I assembled plant whole genome nanopore sequencing using flye and obtained ~4400 contigs and the longest contig size is 373 Kb.  But, I already had contigs (the longest scaffold is ~500 Kb) which is generated by hybrid assembly of both Illumina and nanopore using spades. Also, I mapped both assembler contigs with reference mitochondrial genes and few contigs contain those genes.  I am having more than ~25 contigs which are having mitochondrial genes. When I tried to make scaffold with ONT contigs, none of the contigs are similar to spades contigs or did not generate scaffold. So, how to improve my assembly and how to make a scaffold? 
Thank you.

**Comment by asl** [comment]
Well, you'd need some other kind of data for scaffolding typically. E.g. mate pairs, optical maps, HiC data, etc.

**Comment by bioramg** [comment]
Thank you.
