### ISSUE TITLE
const: Assertion `path.Length() > 0' failed. finished abnormally, err code: -6

### ISSUE THREAD

**Issue by BaichuanXiao** [ablab/spades#508]
hello:
i had used metaspades to assemble my metagenomic data, whereas here came a problem i cannot solve. hope your help, thx!
[params.txt](https://github.com/ablab/spades/files/4654118/params.txt)
[spades.log](https://github.com/ablab/spades/files/4654119/spades.log)

**Comment by asl** [comment]
Hello

Does the problem reproduce with the latest SPAdes 3.14.1?

The set of k-mers used is really a waste of time and resources. If you're unsure what you're doing simply stick to the default options.

**Comment by BaichuanXiao** [comment]
> Hello
> 
> Does the problem reproduce with the latest SPAdes 3.14.1?
> 
> The set of k-mers used is really a waste of time and resources. If you're unsure what you're doing simply stick to the default options.

well, i'll try the latest version, thank you for your prompt reply.

**Comment by BaichuanXiao** [comment]
> Hello
> 
> Does the problem reproduce with the latest SPAdes 3.14.1?
> 
> The set of k-mers used is really a waste of time and resources. If you're unsure what you're doing simply stick to the default options.

i think, it is actually a problem of memory. when i deploy less k-mers or run in a larger memory node, all goes well.
i found many issues involve memory problem, and i advice the consumed memory imformation in each step can be added into the log text in the later version. thank you again!

**Comment by asl** [comment]
>i found many issues involve memory problem, and i advice the consumed memory imformation in each step can be added into the log text in the later version. thank you again!

The information is already there as you could easily see in the log.
