### ISSUE TITLE
Error using input reads extracted from a merged fastq file

### ISSUE THREAD

**Issue by AndreaQ7** [ablab/spades#509]
Hello everyone,
I am using for the first time SPAdes. 
I have one merged fastq from a shotgun metagenomic experiment of human oral microbiome.
Through the taxonomic identification analysis I have seen that there are sequences belonging to a particular bacterial species, so I have extracted the sequences identified as belonged to this species to a new fastq like that

`seqtk subseq P1.merged.fq.gz IDseq.txt > extractedPo.fq`

Then I wanted to see if there was the possibility for a genome assembly of this species and I have used SPAdes. Reading the manual I have read that I should use the --merged option but when i use it

`python spades.py --merged extractedPo.fq --careful -o spades_results2  `

I get the following message of error

`== Error ==  exception caught: <class 'ValueError'>`

This is my spades.log  (I put it here cause i did not understand how attach it sorry)

> Command line: spades.py	--merged	/home/  extractedPo.fq	--careful	-o	/home/ SPAdes-3.14.1-Linux/spades_results2	
> 
> System information:
>   SPAdes version: 3.14.1
>   Python version: 3.7.6
>   OS: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
> 
> Output dir: /home/ SPAdes-3.14.1-Linux/spades_results2
> Mode: read error correction and assembling
> Debug mode is turned OFF
> 
> Dataset parameters:
>   Standard mode
>   For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
>   Reads:
>     Library number: 1, library type: paired-end
>       orientation: fr
>       left reads: not specified
>       right reads: not specified
>       interlaced reads: not specified
>       single reads: not specified
>       merged reads: ['/home/  extractedPo.fq']
> Read error correction parameters:
>   Iterations: 1
>   PHRED offset will be auto-detected
>   Corrected reads will be compressed
> Assembly parameters:
>   k: automatic selection based on read length
>   Repeat resolution is enabled
>   Mismatch careful mode is turned ON
>   MismatchCorrector will be used
>   Coverage cutoff is turned OFF
> Other parameters:
>   Dir for temp files: /home/ SPAdes-3.14.1-Linux/spades_results2/tmp
>   Threads: 16
>   Memory limit (in Gb): 250
> 
> 
> ======= SPAdes pipeline started. Log can be found here: /home/ SPAdes-3.14.1-Linux/spades_results2/spades.log
> 
> Files with merged reads were ignored.
> max() arg is an empty sequence
> Traceback (most recent call last):
>   File "spades.py", line 594, in main
>     bin_home, ext_python_modules_home, python_modules_home)
>   File "spades.py", line 534, in build_pipeline
>     ext_python_modules_home, python_modules_home)
>   File "/home/ SPAdes-3.14.1-Linux/share/spades/spades_pipeline/stages/spades_stage.py", line 383, in add_to_pipeline
>     dataset_data, log, bin_home, ext_python_modules_home, python_modules_home))
>   File "/home/ SPAdes-3.14.1-Linux/share/spades/spades_pipeline/stages/spades_stage.py", line 291, in __init__
>     generateK(self.cfg, self.log, self.dataset_data)
>   File "/home/ SPAdes-3.14.1-Linux/share/spades/spades_pipeline/stages/spades_stage.py", line 122, in generateK
>     options_storage.READS_TYPES_USED_IN_CONSTRUCTION)
>   File "/home/ SPAdes-3.14.1-Linux/share/spades/spades_pipeline/support.py", line 646, in get_primary_max_reads_length
>     reads_length = max(max_reads_lenghts)
> ValueError: max() arg is an empty sequence
> 
> 
> == Error ==  exception caught: <class 'ValueError'>
> 
> In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
> or report an issue on our GitHub repository github.com/ablab/spades
> Please provide us with params.txt and spades.log files from the output directory.
> 
> SPAdes log can be found here: /home/ SPAdes-3.14.1-Linux/spades_results2/spades.log
> 
> Thank you for using SPAdes!

**Comment by asl** [comment]
Hello

From the same SPAdes manual:
```
Note that non-empty files with the remaining unmerged left/right reads (separate or interlaced) must be provided for the same library (for SPAdes to correctly detect the original read length).
```

We will provide better error message in the further SPAdes releases.

So, SPAdes needs to know the original (unmerged) read lengths and you need to provide at least dummy read pair for this.

**Comment by AndreaQ7** [comment]
Thank you a lot asl for this rapid help!!!
Have a good day
