### ISSUE TITLE
Error in metaspades run

### ISSUE THREAD

**Issue by EdderDaniel** [ablab/spades#510]
Hi! 

I'm getting a weird error while running meta-spades. The program stalls during a certain point in the assembly process and quits after a while. I assembled the same reads using another computer with a previous version of spades (ver3.10.1) and it ran flawlessly.

[spades.log](https://github.com/ablab/spades/files/4669911/spades.log)
[params.txt](https://github.com/ablab/spades/files/4669913/params.txt)

**Comment by asl** [comment]
Does the problem reproduce if you'd restart SPAdes?

**Comment by EdderDaniel** [comment]
Yes. Even after using --continue or giving it more memory, it gets stuck at the same line

**Comment by asl** [comment]
Well... there is nothing at that place to stuck in... I would suspect some I/O issue or something similar. What if you'd move output / scratch dir somewhere else (outside LUSTRE in particular)?

**Comment by EdderDaniel** [comment]
I recompiled SPAdes outside that dir and it worked! Thanks!
