### ISSUE TITLE
Error correction and assembling warnings

### ISSUE THREAD

**Issue by JuFengWang** [ablab/spades#512]
Hello，I get some error while running spades 3.14.0. I want to assemble a 30M genome by Illumina and Pacbio sequence. 
My command : `spades.py -1 NHD1938_L7_1_clean.fq -2 NHD1938_L7_2_clean.fq --pacbioT_musculi_0.fq -o spades --careful`
error: 
=== Error correction and assembling warnings:
 * 0:02:31.720   365M / 5G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 25
 * 0:02:31.722   365M / 5G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 25
 * 0:00:48.849   249M / 5G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 9
 * 0:00:48.851   249M / 5G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 9
 * 0:00:26.644   288M / 5G    WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:12:05.605   647M / 5G    WARN   ScaffoldingUniqueEdgeAna (scaff_supplementary.cpp   :  59)   Less than half of genome in unique edges!
Thanks for your help!

**Comment by asl** [comment]
Will you please provide us your spades.log file?

Thanks!

**Comment by JuFengWang** [comment]
[spades.log](https://github.com/ablab/spades/files/4671606/spades.log)

**Comment by JuFengWang** [comment]
> 
> 
> Will you please provide us your spades.log file?
> 
> Thanks!

[spades.log](https://github.com/ablab/spades/files/4671609/spades.log)

**Comment by asl** [comment]
What you're assembling? It does not look like as normal isolate dataset. For example:

```
  0:02:39.238   262M / 5G    INFO    General                 (simplification.cpp        : 502)   Average coverage = 1259.05
```

**Comment by JuFengWang** [comment]
I mixed mitochondrion DNA with total DNA before third-generation sequencing，so the average coverage of mitochondrion genome is larger than normal.

**Comment by asl** [comment]
Ok, so the warnings are due to non-uniform coverage. The normal multicell mode expects more or less uniformly covered input data. Your results might be suboptimal due to this.
