### ISSUE TITLE
truspades.py :: use sys.executable instead of plain 'python ' string

### ISSUE THREAD

**Issue by EricDeveaud** [ablab/spades#518]
Hello, 

truspades.py in `command_line` must call spades.py whith the same interpreter it was run from, not just plain string hardcoding 'python  '

eg:

change from
```
result = ["Python  " + os.path.join(spades_home, "spades.py"), "--truseq", "-o", os.path.join(output_dir, barcode.id), "--continue", params]
```
to

```
result = [sys.executable + " " + os.path.join(spades_home, "spades.py"), "--truseq", "-o", os.path.join(output_dir, barcode.id), "--continue", params]
```

regards

Eric

**Comment by asl** [comment]
Thanks!

Will be fixed in the next SPAdes release one way or another :)

**Comment by asl** [comment]
truSPAdes is deprecated and will be removed from the next SPAdes release
