### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by mjnetherland19** [ablab/spades#519]
After filtering read fastq files with a custom python script, I attempted to assemble the reads. My script appears to have put the lines in the correct order (fastq format) for each read (although I did not do a thorough test of this). I also made sure that the reverse read file has reads in the same order as the forward read file. 

The spades.log and params.txt files are attached.

I am grateful for any help you can provide.

[spades.log](https://github.com/ablab/spades/files/4707959/spades.log)
[params.txt](https://github.com/ablab/spades/files/4707960/params.txt)

**Comment by asl** [comment]
Hello

Will you please give SPAdes 3.14.1 a try?

**Comment by mjnetherland19** [comment]
Hi asl,

I did as you suggested but got the same result. Files are attached.

[spades.log](https://github.com/ablab/spades/files/4712453/spades.log)
[params.txt](https://github.com/ablab/spades/files/4712454/params.txt)

**Comment by mjnetherland19** [comment]
After doing a more thorough test of my script's efficacy, it did not reproduce the fastq records perfectly. Sorry to bother you unnecessarily and thank you for your help.

**Comment by olga24912** [comment]
Hi, 

Sorry for the long response. Thank you for using SPAdes. In the next version of SPAdes users will get a readable error message in case of an incorrect fastq file. I hope that the next users will spend much less time with a similar problem. 

Thanks for helping make SPAdes better!

**Comment by olga24912** [comment]
It will be fixed in 3.15
