### ISSUE TITLE
Specifying multiple libraries for metaspade

### ISSUE THREAD

**Issue by shekas3** [ablab/spades#52]
I was wondering to know what is the total number of libraries that can be specified for meta-spade? I have 17 samples that I want to be co-assembled altogether. But it sounds like the max number of libraries that can be run together are 9? 

Thanks,
Sharok

**Comment by asl** [comment]
Per SPAdes manual (http://cab.spbu.ru/files/release3.11.1/manual.html#meta) the max number of libraries for metaSPAdes is 1.
