### ISSUE TITLE
== Error ==  system call for: "['/home/pmslab/Desktop/bin/SPAdes-3.14.0-Linux/bin/spades-hammer', '/home/pmslab/Desktop/spades/hybrid_assembly_30/corrected/configs/config.info']" finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by bioramg** [ablab/spades#520]
Hi,
I am trying to assemble the mitochondrial genome with both Illumina pair-end and Nanopore reads. There is no enough memory in my server, so I subsampled to 30% of Illumina reads and full reads of Nanopore. But the assembly has not produced any scaffolds or contigs. What could be a problem? Could you please give suggestions? I am herewith enclosing the log file for your reference.

[spades.log](https://github.com/ablab/spades/files/4717626/spades.log)

**Comment by asl** [comment]
The log reads:

```
 Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So you're still running out of RAM. I may suggest to perform heavy quality trimming as well.

**Comment by bioramg** [comment]
Thank you.
Should I trim again? or shall I subsample further??

**Comment by asl** [comment]
Well, probably start with trimming

**Comment by bioramg** [comment]
Thank you.
