### ISSUE TITLE
Spades 13.14.1 compilation error ?

### ISSUE THREAD

**Issue by sunnykevin19** [ablab/spades#523]
Hi 
Using gcc-9.3.1 in centos 8, suggestions please.
./spades_compile.sh
 164 |     if ((aligned_length < min(read_len_double * 0.4, 40.0)) && (position > read_len_double / 2) && (contig_.length() > read_len_double / 2 + (double) position)) {
      |                                                                                                     ~~~~~~~~~~~~~~^~
[ 95%] Linking CXX executable ../../bin/spades-corrector-core
[ 95%] Built target spades-corrector-core
[ 95%] Linking CXX executable ../../bin/spades-truseq-scfcorrection
[ 95%] Built target spades-truseq-scfcorrection
[ 95%] Linking CXX executable ../../bin/spades-core
[ 95%] Built target spades-core
make: *** [all] Error 2

**Comment by asl** [comment]
Looks like your system is broken as system include `unistd.h` includes `getopt.h`. It should not be there:

```
In file included from /usr/include/unistd.h:893,
                 from /home/sunny/data/softwares/SPAdes3.14.1/src/../ext/include/boost/config/stdlib/libstdcpp3.hpp:78,
                 from /home/sunny/data/softwares/SPAdes3.14.1/src/../ext/include/boost/config.hpp:49,
                 from /home/sunny/data/softwares/SPAdes-.14.1/src/../ext/include/boost/iterator/iterator_facade.hpp:10,
                 from /home/sunny/data/softwares/SPAdes3.14.1/src/common/adt/chained_iterator.hpp:11,
                 from /home/sunny/data/softwares/SPAdes-3.14.1/src/common/pipeline/library.hpp:13,
                 from /home/sunny/data/softwares/SPAdes3.14.1/src/common/pipeline/config_struct.hpp:10,
                 from /home/sunny/data/softwares/SPAdes3.14.1/src/common/io/dataset_support/read_converter.hpp:10,
                 from /home/sunny/data/softwares/SPAdes3.14.1/src/projects/kmercount/kmer_estimating.cpp:10:
/DATA/MarineEcology/sunny/softwares/gcc-9.3.1/include/getopt.h:81:8: note: candidates are: ‘struct option’
```
