### ISSUE TITLE
Using BAM inputs for assembly

### ISSUE THREAD

**Issue by WallyL** [ablab/spades#525]
I see that Ion-Torrent data can be input directly using a BAM file, but it doesn't look like this is an option for other platforms, e.g. Illumina data. 

I'm working on a mapping/extraction/assembly pipeline (PE 75) and would like to skip the fastq extraction step.  I was wondering if there is a way (or any future plans to develop one) to input data directly from the Illumina BAMs.  Just to be clear, each BAM (extracted with BamTools) contains only the reads that map to a single region/record.

Thanks for any suggestions you may have.

**Comment by asl** [comment]
Dear Walt,

So far there are no plans to support BAMs as input for any other modes but IonTorrent and the support is essentially biased towards IonTorrent-generated BAMs.

However, if you'd skip the read error correction and provide the set of k-mers manually, then things will likely work

E.g. running ```spades.py --only-assembler --iontorrent -s <your BAM>```. Note that here iontorrent mode is used to mainly switch various checks, etc. that operate on FASTQ files. No functional changes.

Hope this helps.

**Comment by WallyL** [comment]
Thanks, Anton.  I'll give it a try.
Best,
Walt
