### ISSUE TITLE
When running hybrid assembly does spades correct the long reads with short reads?

### ISSUE THREAD

**Issue by Lamm-a** [ablab/spades#527]
Does spade correct long reads with short reads when runnin ghybrid assembly?

I have been rtrying to do hybrid assembly with spade but I am seeing `Mode: ONLY assembling (without read error correction)` at the top of my logs. Note this is using Pacbio long reads and illumina paired end short reads.

**Comment by asl** [comment]
SPAdes does not correct long reads. See https://pubmed.ncbi.nlm.nih.gov/26589280/ hybridSPAdes paper for more information about the approach

**Comment by Lamm-a** [comment]
So you would advise post Spades correcting of the assembly ouput with the illumina short reads in a 3rd party programme?
