### ISSUE TITLE
Metaspades terminated by segmentation fault (Error code -11)

### ISSUE THREAD

**Issue by dgithae** [ablab/spades#528]
Hello; 

I was using spades v3.13.0 with --meta option to perform a metagenomic assembly from Microbial Community Standard II ([see link](https://www.zymoresearch.com/collections/zymobiomics-microbial-community-standards/products/zymobiomics-microbial-community-standard-ii-log-distribution)). Fastq file sizes are 25G each (total of 50G for both reads). The assembly terminates with a segmentation fault: stack trace error code -11 running the spades-hammer.

I have attached both params and spades log file.  

Please advise; Thanks.
[params.txt](https://github.com/ablab/spades/files/4795631/params.txt)
[spades.log](https://github.com/ablab/spades/files/4795632/spades.log)

**Comment by asl** [comment]
Hello

Does the problem reproduce with the latest SPAdes 3.14.1?

**Comment by hungenlai90** [comment]
I have the same issue with running spades.py --test on Spades 3.14.1 and Python 3.7.6. I'm running them on Ubuntu 20.04 on WSL2 (Win10 Pro)
I get the Segmentation fault and OS return value -11
The log and param file are as followed. Thanks.
[params.txt](https://github.com/ablab/spades/files/4844974/params.txt)
[spades.log](https://github.com/ablab/spades/files/4844976/spades.log)

**Comment by hungenlai90** [comment]
The solution was to compile by source. It seems that the Linux version doesn't work on WSL2.

**Comment by alienzj** [comment]
Oh my god, someone actually used WSL2 to assemble genome.
