### ISSUE TITLE
MetaSpades error

### ISSUE THREAD

**Issue by pbravakos** [ablab/spades#529]
Hi,
I am having a problem running MetaSpades which terminates after some time and don't understand why.
[params.txt](https://github.com/ablab/spades/files/4823788/params.txt)
[spades.log](https://github.com/ablab/spades/files/4823790/spades.log)

When I try to run again Spades with the continue option I get the following error:
```
Traceback (most recent call last):
  File "/home1/pbravakos/Software/SPAdes-3.14.1-Linux/bin/spades.py", line 643, in <module>
    main(sys.argv)
  File "/home1/pbravakos/Software/SPAdes-3.14.1-Linux/bin/spades.py", line 572, in main
    init_parser(args)
  File "/home1/pbravakos/Software/SPAdes-3.14.1-Linux/bin/spades.py", line 560, in init_parser
    os.path.join(options_parser.get_output_dir_from_args(), "params.txt"),
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```
Thanks
Panos

**Comment by asl** [comment]
Hello

The error likely stems from some I/O problem as one of SPAdes intermediate files got corrupted.

**Comment by pbravakos** [comment]
Thanks for the reply.
You believe this is a bug of the program or a problem of the server I am running on? Could it be a memory issue?
Do you have any clue If I changed something in the arguments of the Spades command if I could I avoid the problem?
Best
Panos

**Comment by asl** [comment]
As I said, this is an I/O problem on your server as one of SPAdes intermediate files got corrupted. I would suggest to contact your system administrator
