### ISSUE TITLE
Issue regarding with nanopore option

### ISSUE THREAD

**Issue by aman21392** [ablab/spades#530]
COmmand-- /home/aclab/apps/SPAdes-3.14.1-Linux/bin/spades.py --rna -s combined_T.fastq -o /Drive4/spades/output
I used this command for transcriptome assembly. I have nanopore Direct RNA seq reads through minknow. But i don't understand how can i use --nanopore options in this because i have only 1 fastq file and if i use same fastq file in --nanopore option then it terminate with error:: 
I use command ::- /home/aclab/apps/SPAdes-3.14.1-Linux/bin/spades.py --rna -s combined_T.fastq --nanopore combined_T.fastq -o /Drive4/spades/infected/output
Usage: spades.py [options] -o <output_dir>
spades.py: error: argument --nanopore: expected 1 argument(s)
== Error ==  file combined_T.fastq was specified at least twice

I think nanopore option is necessary for my command because i use nanopore direct RNAseq experiment.
So please help me how can i solve this issue.

**Comment by andrewprzh** [comment]
Hi,

rnaSPAdes can use Nanopore reads only in addition to short accurate Illumina reads. Unfortunately, it was not designed for ONT-only assembly. You may try to use RNA-Bloom https://github.com/bcgsc/RNA-Bloom

All the best
Andrey
