### ISSUE TITLE
Spades hybrid

### ISSUE THREAD

**Issue by jhcaddisfly** [ablab/spades#531]
Hallo,

I want to Assembly low Coverage nanopore data (2.7x) and high coverag illumina data (70x).
Should I give the  --Isolate Parameter?
I would run it like this:
/opt/SPAdes-3.14.0-Linux/bin/spades.py --isolate	-1	illumina_fw.fq	-2	illumina_rv.fq	-s	illumina_single.fq -t	30	--nanopore np.fq -o	spades_HR --cov-cutoff	auto	

Thanks for any advice

**Comment by asl** [comment]
Hello

Given that your Illumina data is not of high coverage we'd not suggest to use --isolate by default.
