### ISSUE TITLE
Compiling metaviral_publication branch of old system with glibc 2.17 (2012)

### ISSUE THREAD

**Issue by ipetrushin** [ablab/spades#533]
Dear SPAdes Team!

Thank you for release.  Trying to compile SPAdes as follows in README, but my system (remote cluster w/ 1TB RAM) is rather old. I installed CMake/C++/GCC and other stuff with conda but cannot update system-wide GLIBC. When compiling got errors like:
`/home/ipetrushin/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../../ext/jemalloc/src/libjemalloc.a(nstime.c.o): undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'`

Which minimal version of GLIBC is required for SPAdes? Is it possible to build SPAdes static at another system (have two systems, where its builds fine).

@Dmitry-Antipov

**Comment by asl** [comment]
SPAdes does not use any modern features of glibc. The clock_gettime was released as a part of glibc 2.2 back in 2002. So, I really doubt your system is that old. It's likely the linker search paths are set improperly within your conda environment.

You can certainly try to build SPAdes statically (pass -DSPADES_STATIC_BUILD=1 to spades_compile.sh), however, you may face different compatibility issues here and there.
