### ISSUE TITLE
== Error ==  system call for:“...”finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by pengouy** [ablab/spades#534]
[params.txt](https://github.com/ablab/spades/files/4856049/params.txt)
[spades.log](https://github.com/ablab/spades/files/4856050/spades.log)
Hi,
I've got some problems when using SPAdes in Supercomputing cloud services platform. It runs well in login node, but this operation is not proper. I should submit my work by using SLURM  workload manager, however, here comes a program error: 
_== Error ==  system call for:“...”finished abnormally, OS return value: -6_
Could you please help me with this?
Wish you all well.

**Comment by asl** [comment]
Hello

It's likely that there was some memory or file corruption as one of SPAdes internal assertion during processing of the input file failed.

**Comment by pengouy** [comment]
Thanks for replying me.
What should I do next? Could I solve this by re-installing SPAdes?
And the key problem is that when I submit my code in command, SPAdes works well. But it fails to run when I submit my scripts in a .sh file.

**Comment by pengouy** [comment]
> Hello
> 
> It's likely that there was some memory or file corruption as one of SPAdes internal assertion during processing of the input file failed.

Thanks for replying me.
What should I do next? Could I solve this by re-installing SPAdes?
And the key problem is that when I submit my code in command, SPAdes works well. But it fails to run when I submit my scripts in a .sh file.

**Comment by asl** [comment]
The problem is likely due to your cluster configuration. You may need to talk to your system administrator about this

**Comment by pengouy** [comment]
> The problem is likely due to your cluster configuration. You may need to talk to your system administrator about this

Problem sovled, thanks a lot~

**Comment by MarcelaHer** [comment]
I've got the same error just now, could you share how you resolved it?

**Comment by pengouy** [comment]
Sure, I asked server administrator and showed him my scripts, then it run successfully by removimg "srun" out from my code.&nbsp;Wish you good luck.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MarcelaHer"<notifications@github.com&gt;; 
发送时间: 2020年7月3日(星期五) 凌晨2:05
收件人: "ablab/spades"<spades@noreply.github.com&gt;; 
抄送: "poy"<907294493@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ablab/spades] == Error ==  system call for:“...”finished abnormally, OS return value: -6 (#534)





 
I've got the same error just now, could you share how you resolved it?
 
&mdash;
