### ISSUE TITLE
Spades finished abnormally, OS return value: -11

### ISSUE THREAD

**Issue by jhcaddisfly** [ablab/spades#535]
Hallo,

I am trying to assemble an insect genome (approx. 350 Mbp) with low coverage Nanopore data (6x) and Illumina data (250x) using
/opt/SPAdes-3.14.0-Linux/bin/spades.py    -m2500  -1 1.fq    -2 2.fq    -s unpaired.fq     --nanopore nano_filtered_reads.fq -t60      -o  /ph2_hybrid  --cov-cutoff auto
 I get the following error message:

== Error ==  system call for: "['/opt/SPAdes-3.14.0-Linux/bin/spades-core', 'ph2_hybrid/K55/configs/config.info']" finished abnormally, OS return value: -11

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:00.001    10M / 12M   WARN   StageManager             (stage.cpp                 : 150)   No saved checkpoint
======= Warnings saved to /home/jheckenhauer /ph2_hybrid/warnings.log

=== ERRORs:
 * system call for: "['/opt/SPAdes-3.14.0-Linux/bin/spades-core', '/ph2_hybrid/K55/configs/config.info']" finished abnormally, OS return value: -11

I starte to resume it using  --continue but this did not help.
Do you have any advice?

Thanks,

J

**Comment by asl** [comment]
Please attach your spades.log file and params.txt as you were instructed in the error message

**Comment by jhcaddisfly** [comment]
[spades.log](https://github.com/ablab/spades/files/4857204/spades.log)
[params.txt](https://github.com/ablab/spades/files/4857205/params.txt)

**Comment by jhcaddisfly** [comment]
[spades.txt](https://github.com/ablab/spades/files/4857243/spades.txt)

**Comment by jhcaddisfly** [comment]
[params.txt](https://github.com/ablab/spades/files/4857251/params.txt)

**Comment by asl** [comment]
Thanks. It's likely a problem that we fixed in SPAdes 3.14.1. Please consider upgrading

**Comment by jhcaddisfly** [comment]
Thank you!

**Comment by tarunpal33** [comment]
Please guide on this:
1:00.406     1M / 12G   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 2.93748 Gb
  0:01:00.406     1M / 12G   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 419430
  0:01:01.723  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 7769762 kmers
  0:01:03.256  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 20256761 kmers
  0:01:11.947  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 88725881 kmers
  0:01:17.798  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 100241533 kmers
  0:01:26.010  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 170667043 kmers
  0:01:27.243  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 182169554 kmers
  0:01:35.382  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 252626116 kmers
  0:01:38.311  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 264120248 kmers
  0:01:46.244  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 334578486 kmers
  0:01:50.417  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 346079206 kmers
  0:01:58.724  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 416522627 kmers
  0:01:59.860  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 428020738 kmers
  0:02:08.138  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 498471287 kmers
  0:02:09.277  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 509974725 kmers
  0:02:17.191  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 580416227 kmers
  0:02:18.364  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 591925563 kmers
  0:02:26.570  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 662346856 kmers
  0:02:28.464  9601M / 12G   INFO    General                 (kmer_splitters.hpp        : 194)   Processed 673856555 kmers
  0:02:30.892  9608M / 12G   ERROR   General                 (kmer_splitter.hpp         : 150)   **I/O error! Incomplete write! Reason: Disk quota exceeded. Error code: 122**


== Error ==  system call for: "['/gpfs0/biores/users/tarun/miniconda3/envs/spades/bin/spades-core', '/gpfs0/biores/users/tarun/miniconda3/envs/spades/bin/assembly_S1/K21/configs/config.info', '/gpfs0/biores/users/tarun/miniconda3/envs/spades/bin/assembly_S1/K21/configs/mda_mode.info', '/gpfs0/biores/users/tarun/miniconda3/envs/spades/bin/assembly_S1/K21/configs/meta_mode.info']" finished abnormally, OS return value: 122
None

**Comment by asl** [comment]
@tarunpal33 Please do not hijack closed issues.

The error could be clearly seen from the log you posted:
```
0:02:30.892 9608M / 12G ERROR General (kmer_splitter.hpp : 150) I/O error! Incomplete write! Reason: Disk quota exceeded. Error code: 122
```

**Comment by tarunpal33** [comment]
I know but ideally how much space it needs? What parameters should I adjust
to run?



Thanks & Regards
Dr. Tarun Pal
Israel

**Comment by tarunpal33** [comment]
I know but ideally how much space it needs? What parameters should I adjust to run?

**Comment by asl** [comment]
This cannot be estimated in advance as it depends on many parameters including e.g. genome size, complexity, coverage, error rate, repeat content, etc.
