### ISSUE TITLE
finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by MarcelaHer** [ablab/spades#537]
Hi, 

My run failed, I am using 94 GB RAM and 24 cores, I think (almost sure) I am short in memory, but the IT department want to see that you guys agree with what I think before they allow me to use more memory. I am using the 3.14 version.
Thank you, Marcela

[spades_try2.log](https://github.com/ablab/spades/files/4862565/spades_try2.log)
[params.txt](https://github.com/ablab/spades/files/4862566/params.txt)

**Comment by asl** [comment]
You might be running out of RAM in this case. Alternatively, there might be a problem with GPFS handling memory-mapped file writes improperly.

**Comment by MarcelaHer** [comment]
Thank you, will let you know how it goes.

**Comment by MarcelaHer** [comment]
Hi, so I increased to 120 GB RAM and 24 cores, failed again said something about not finding file mmapped_reader.hpp... 
I guess I am running out of RAM?
Cheers, Marcela

[params-failedV2-2jul.txt](https://github.com/ablab/spades/files/4864102/params-failedV2-2jul.txt)
[spades-failedV2-2jul.log](https://github.com/ablab/spades/files/4864104/spades-failedV2-2jul.log)

**Comment by MarcelaHer** [comment]
forgot to comment, IT expert told me they haven't had problems with GPFS not handling file writes.

**Comment by asl** [comment]
So, from these logs it's obvious, these are I/O issues:

```
  0:32:11.941    43G / 43G   ERROR   General                 (mmapped_reader.hpp        :  41)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /gpfs/home/pbj20xqu/Spades/SpadesMG1/tmp/hammer_q705ykcp/kmer_counter_fqpROx/final_kmers_RkhKRy
```

and
```
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/pbj20xqu/Spades/SpadesMG1/spades.log'
```

**Comment by MarcelaHer** [comment]
They gave me 250GB RAM and 24 cores and run without problems. Thank you.
