### ISSUE TITLE
Version 3.14.1 Retag

### ISSUE THREAD

**Issue by Rylan12** [ablab/spades#539]
Hi there, Homebrew maintainer here.

We updated our `spades` formula to version 3.14.1 on April 28 ([here's the PR](https://github.com/Homebrew/homebrew-core/pull/53935)) but are now experiencing a sha256 mismatch issue.

I also noticed that the changelog says that version 3.14.1 was released on May 1 (after our update on April 28). 

Was version 3.14.1 retagged/rereleased after April 28?

**Comment by asl** [comment]
Hello

Yes, there were some last-minute fixes that delayed the release and we had to redo everything.

**Comment by Rylan12** [comment]
@asl Thanks for the response and clarification!
