### ISSUE TITLE
err code: -6

### ISSUE THREAD

**Issue by qslin** [ablab/spades#54]
I request 500G memory and 32 cores but get the error below:
```
<jemalloc>: Error in realloc(): out of memory. Requested: 16, active: 254845911040


== Error ==  system call for: "['/isg/shared/apps/SPAdes/3.11.1/bin/spades', '/home/CAM/qlin/LF10_Genome_Assembly_new/SPAdes/t2/SPAdes_out_t2/K77/configs/config.info', '/home/CAM/qlin/LF10_Genome_Assembly_new/SPAdes/t2/SPAdes_out_t2/K77/configs/careful_mode.info']" finished abnormally, err code: -6
```

**Comment by asl** [comment]
Please attach your spades.log and params.txt files as you were suggested just two lines below the ones you posted

**Comment by qslin** [comment]
[spades.log](https://github.com/ablab/spades/files/1566055/spades.log)
[params.txt](https://github.com/ablab/spades/files/1566056/params.txt)

**Comment by asl** [comment]
The memory limit is 250 Gb in your case (from the log):
  Memory limit (in Gb): 250

Make sure you're providing the proper memory limit via -m option
