### ISSUE TITLE
Additional checkpoints would be useful

### ISSUE THREAD

**Issue by stacy734** [ablab/spades#541]
Hi SPAdes developers,
One of the more useful features in SPAdes is the --continue option, which allows the user to restart the process from the last checkpoint.   I use this a lot.
It would be useful to make more checkpoints available to reduce the amount of time spent re-doing steps that completed successfully.

Thanks for producing a great software!

**Comment by ipetrushin** [comment]
Absolutely true. When runnung a dataset for 100-200 hours and stopping due to insuffient memory of disk space, need to clean re-run is really frustrating.
SPAdes the best!

**Comment by asl** [comment]
There are more checkpoints available via --checkpoints=all / last. Note, however, that they might require quite some time to be written / read and consume the disk space (essentially as checkpoint represents the SPAdes internal state, so it could consume the disk space proportional to memory usage)

**Comment by stacy734** [comment]
Thank you!  This is very useful (and also thanks for the heads-up on disk space.)
    On Saturday, August 1, 2020, 07:23:42 AM EDT, Anton Korobeynikov <notifications@github.com> wrote:  
 
 


There are more checkpoints available via --checkpoints=all / last. Note, however, that they might require quite some time to be written / read and consume the disk space (essentially as checkpoint represents the SPAdes internal state, so it could consume the disk space proportional to memory usage)

**Comment by ipetrushin** [comment]
> There are more checkpoints available via --checkpoints=all / last. Note, however, that they might require quite some time to be written / read and consume the disk space (essentially as checkpoint represents the SPAdes internal state, so it could consume the disk space proportional to memory usage)

Thanks a lot! Does these improvements belong to metaviral branch too? @Dmitry-Antipov @asl
