### ISSUE TITLE
Memory requirement prediction

### ISSUE THREAD

**Issue by ipetrushin** [ablab/spades#542]
Dear SPAdes Team!

We're assembling large dataset of metaviral samples from freshwater resevoirs. While the size of required memory depends on the number of threads we set t = 4. With "standart" SPAdes with option --meta assembly took 400 hours with ~800 Gb of RAM (see log attached). With metaviralspades assembly failed twice with insuffient memory error (with t=4, t=16), while 200 Gb RAM free. How can one predict memory requirement for the assembly?

[spades-metaviral-16threads.log](https://github.com/ablab/spades/files/4910462/spades-metaviral-16threads.log)
[spades-metaspades-standart.log](https://github.com/ablab/spades/files/4910448/spades-metaspades-standart.log)
[spades-metaviral.log](https://github.com/ablab/spades/files/4910450/spades-metaviral.log)

Sincerely, Ivan
@Dmitry-Antipov

**Comment by Dmitry-Antipov** [comment]
Looks strange for me - actually memory requirements for metaviralSPAdes and metaSPAdes should be quite the same.
>With metaviralspades assembly failed twice with insuffient memory error (with t=4, t=16), while 200 Gb RAM free
Are you sure you had enough memory physically free on server at that time?

Did you use read error correction prior to assembly?
Also to reduce the memory consumption I'd consider to use some read filtering, for example spades-read-filter

**Comment by ipetrushin** [comment]
Yes, strict filtering was made before assembly. Try next time with control RAM free during assembly.

**Comment by ipetrushin** [comment]
I tried the assembly again with the same settings and free memory logging (see script below):
```
outfile="$HOME/memory-usage.log"

while true
do
echo ""  >> $outfile
echo `date` >> $outfile
tail -n 1 ~/sto/virome/paired-metaviral/spades.log >> $outfile
cat /proc/meminfo | grep Mem >> $outfile
sleep 300
done
```

Tail of SPAdes log:
```
132:48:46.876   504G / 508G  INFO   StageManager             (stage.cpp                 : 160)   STAGE == Preliminary Distance Estimation
132:48:46.877   504G / 508G  INFO    General                 (distance_estimation.cpp   : 174)   Processing library #0
132:48:46.877   504G / 508G  INFO    General                 (distance_estimation.cpp   : 150)   Weight Filter Done
132:48:46.920   504G / 508G  INFO   DistanceEstimator        (distance_estimation.hpp   : 116)   Using SIMPLE distance estimator
<jemalloc>: Error in malloc(): out of memory
 Requested: 131072
```
last lines of memory log
```
Fri Jul 24 18:41:16 +07 2020
132:48:46.920   504G / 508G  INFO   DistanceEstimator        (distance_estimation.hpp   : 116)   Using SIMPLE distance estimator
MemTotal:       990791668 kB
MemFree:        56655676 kB
MemAvailable:   290750936 kB

Fri Jul 24 18:46:16 +07 2020
132:48:46.920   504G / 508G  INFO   DistanceEstimator        (distance_estimation.hpp   : 116)   Using SIMPLE distance estimator
MemTotal:       990791668 kB
MemFree:        56507200 kB
MemAvailable:   290602472 kB

Fri Jul 24 18:51:16 +07 2020
132:48:46.920   504G / 508G  INFO   DistanceEstimator        (distance_estimation.hpp   : 116)   Using SIMPLE distance estimator
MemTotal:       990791668 kB
MemFree:        56361860 kB
MemAvailable:   290457156 kB

Fri Jul 24 18:56:16 +07 2020
Thank you for using SPAdes!
MemTotal:       990791668 kB
MemFree:        665191908 kB
MemAvailable:   899306528 kB
```

So we have almost 300 Gb mem available and malloc returns an error.
Need your advice, @Dmitry-Antipov

Sincerely,
Ivan

**Comment by c-leber** [comment]
Any updates on this @ipetrushin @Dmitry-Antipov ? I am also having some strange memory allocation issues.

**Comment by ipetrushin** [comment]
Nope, didn't tried again since July.

**Comment by Puumanamana** [comment]
Same problem for me too

**Comment by asl** [comment]
Memory allocator was changed in 3.15. Please open new issue with updated information if this is still an issue
