### ISSUE TITLE
metaviralSPAdes compilation failed

### ISSUE THREAD

**Issue by aag1** [ablab/spades#543]
Dear SPAdes team,

I am trying to install metaviralSPAdes using the following commands:
```
export LDFLAGS=-lrt

dir='metaviralSPAdes'
git clone -b 'metaviral_publication' https://github.com/ablab/spades.git ${dir}
cd ${dir}
./assembler/spades_compile.sh
```

Compilation reaches 100%:
```
[100%] Built target form_truealignments
[100%] Linking CXX executable ../../bin/spades-edge-profiles
[100%] Built target spades-edge-profiles
```

But fails with the following error message:
```
../../ext/samtools/libsamtools.a(bam_import.c.o):bam_import.c:function __bam_get_lines: error: undefined reference to 'gzopen64'
../../ext/samtools/libsamtools.a(bam_import.c.o):bam_import.c:function sam_header_read2: error: undefined reference to 'gzopen64'
../../ext/samtools/libsamtools.a(bam_import.c.o):bam_import.c:function sam_open: error: undefined reference to 'gzopen64'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/spades-corrector-core] Error 1
make[1]: *** [projects/corrector/CMakeFiles/spades-corrector-core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

Could you please advise if I can fix it somehow?

Kind regards,
Anastasia

**Comment by aag1** [comment]
P.S. Please find attached full compilation log:
[metaviralSPAdes_compilation.log](https://github.com/ablab/spades/files/4915036/metaviralSPAdes_compilation.log)

**Comment by Dmitry-Antipov** [comment]
If you wish to compile any of the SPAdes family tools including metaviralSPAdes you will need the following libraries to be pre-installed:

g++ (version 5.3.1 or higher)
cmake (version 3.5 or higher)
zlib
libbz2

This error looks like you do not have zlib installed.

**Comment by aag1** [comment]
Dear Dmitry,

Thank you very much for pointing me to zlib! There was indeed a problem with it (apparently I had two versions, zlib 1.2.3 and zlib 1.2.11, loaded simultaneously), and after I fixed it compilation advanced beyond the point of previous error.

Unfortunately, after that the compilation failed with a new error message:
```
CMake Error at cmake_install.cmake:81 (file):
  file INSTALL cannot find
  "/PATH_TO_WORK_DIR/metaviralSPAdes/assembler/src/../manual.html".


make: *** [install] Error 1
```
Full compilation log:
[metaviralSPAdes_compilation2.log](https://github.com/ablab/spades/files/4938329/metaviralSPAdes_compilation2.log)

Sorry for so many questions, but could you please advise if I can fix this new problem somehow?

Kind regards,
Anastasia

**Comment by Dmitry-Antipov** [comment]
Oops - this is my fault. Please revert to previous revision, (git revert HEAD) prior to compiling.

**Comment by aag1** [comment]
Thank you! I successfully reverted the last git commit.

Later, I faced a new problem: folders newly created during compilation were given wrong permissions on my server, resulting in compilation errors. I solved it by adding `USE_SOURCE_PERMISSIONS` to every `install(DIRECTORY` command in the following files:
```
assembler/src/CMakeLists.txt
assembler/src/projects/hammer/CMakeLists.txt
assembler/src/projects/ionhammer/CMakeLists.txt
assembler/src/projects/spades/CMakeLists.txt
assembler/src/spades_pipeline/CMakeLists.txt
```

After that, compilation run without error messages and `bin/spades.py --test` passed correctly. However, the resulting `bin/` does not include metaviralspades.py script or symlink:
```
metaspades.py -> spades.py
plasmidspades.py -> spades.py
rnaspades.py -> spades.py
spaligner
spades-gmapper
spades-core
spades-gbuilder
spades-corrector-core
spades-truseq-scfcorrection
spades-kmercount
spades-read-filter
spades-kmer-estimating
spades-ionhammer
spades-hammer
spades-bwa
truspades.py
spades.py
spades_init.py
```

Could you please advise if metaviralspades.py script or symlink should be present in the `bin/`?

Kind regards,
Anastasia

**Comment by Dmitry-Antipov** [comment]
Sorry, my fault again, thank you for noticing.
With latest commit fixed this and previous issue.
(Actually there is no need in metaviralspades.py script in /bin folder - usually run it from ./assembler/metaviralspades.py but still, it should be copied there also)

>scaffolds.fasta contains the potential complete viral genomes
>K127/before_chromosome_removal.fasta contains all the assembled contigs
Yes, it is correct.

**Comment by aag1** [comment]
Thank you very much!

Kind regards,
Anastasia
