### ISSUE TITLE
 = Error == system call for: "['/home/abb/SPAdes-3.14.1-Linux/bin/spades-hammer', '/media/abb/Raj/spades assembly sal00277/corrected/configs/config.info']" finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by Rajeefa** [ablab/spades#544]
I have run spades before with this command but now its returning this error

**Comment by asl** [comment]
It happens.

Will you please provide us the files that were mentioned just two lines above the github address?

Thanks!

**Comment by hlfreund** [comment]
Hi, I am also getting this same output. I am currently running R1, R2, and merged metagenomic reads with the spades error-correction-only option. 
I didn't have this issue with my normalized reads, but these are non-normalized and I have encountered this error twice. 

I am running spades on a cluster system and am requesting 900gb with two threads, yet received the error "out of memory".

I hope you can help me with this problem, thank you so much!

**Comment by Rajeefa** [comment]
Hi,
I switched to spades 3.13.2 version and it worked. However,I would suggest you to open a thread separate so that the spades team support will help you.

**Comment by ryanjoel** [comment]
This output means run out of RAM. I met the same problem when i run shovill in 40 cups.when i change to --cups 11,it worked.
