### ISSUE TITLE
Error code -6

### ISSUE THREAD

**Issue by corejuke** [ablab/spades#545]
Hello!
Thank you for the excellent program, I often use it.

There was a problem the assembly of the one dataset.
How can this be solved?
Thank!
[spades.log](https://github.com/ablab/spades/files/4923440/spades.log)
[params.txt](https://github.com/ablab/spades/files/4923441/params.txt)
FastQC report:
[C30_1.paired_fastqc.pdf](https://github.com/ablab/spades/files/4923455/C30_1.paired_fastqc.pdf)
[C30_2.paired_fastqc.pdf](https://github.com/ablab/spades/files/4923457/C30_2.paired_fastqc.pdf)

Sincerely, 
Anton K.

**Comment by asl** [comment]
Hello

First of all, the error message is:
```'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'```

And indeed there are many strange things:
  - Your average read length is 93 bp, however, you're using k = 85,95,105
  - It seems that your coverage is non-uniform and very low, still you're assembling in normal multi-cell mode
  - You're only having 25k reads, this is unlikely to be a set of reads from the genome / part of it.
