### ISSUE TITLE
cloudspades: generalizing to any BX:Z tags?

### ISSUE THREAD

**Issue by nick-youngblut** [ablab/spades#546]
cloudspades requires the user to specify the SLR library via the `--gemcode<#>-[12]`  flags, in which `<#>` is the SLR library number `<#>` (`<#>` = 1,2,..,9). 

Why is the SLR library number required? I'm using sequence data generated with a method similar to TELL-seq, so there is no SLR library number. Can I still use cloudspades appropriately (e.g., by just using `--gemcode1` for all libraries)? 

I've tried running `cloudspades --gemcode1-1 read1.fq --gemcode1-2 read2.fq` on my sequence data, and it will run and generate many contigs, but I'm wondering if it is working correctly, given my arbitrary choice of SLR Library 1. 

It would help to include some info in the README about this kind of situation. 

Also, is there any updates to the timeline for integrating cloudspades into spades? The release was last May, and there doesn't seem to be any updates since then.

**Comment by Itolstoganov** [comment]
Hello!

Thank you for your interest in cloudSPAdes. 

If you have only one SLR library, then `--gemcode1-1 read1.fq --gemcode1-2 read2.fq` is correct input option. If you have multiple libraries, the library number option is needed to specify which input file corresponds to which library.

We do not have a specific timeline for integration right now.

**Comment by nick-youngblut** [comment]
Thanks for the clarification!
