### ISSUE TITLE
coronaSPAdes build error

### ISSUE THREAD

**Issue by alienzj** [ablab/spades#547]
I downloaded **coronaSPAdes** from [here](http://cab.spbu.ru/files/coronaSPAdes/SPAdes-3.15.0-corona-2020-07-15.tar.gz).

Then compile it in a conda environment(include c/cxx compilers, openmp, libz, bzip2, cmake, make, etl) using conda-build.

![image](https://user-images.githubusercontent.com/8847420/88050806-1d8e1e80-cb8a-11ea-9862-61e417e1b029.png)

Have friends encountered similar problems?

**Comment by alienzj** [comment]
```bash
$ g++ --version

g++ (crosstool-NG 1.24.0.123_1667d2b) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by alienzj** [comment]
I used g++ 10.1.0 to compile coronaSPAdes successfully, but failed to compile with g++ 7.5.0.

**Comment by asl** [comment]
Thanks, this issue will be fixed in the next snapshot of coronaSPAdes.

In the meantime you could apply the following patch:

```
diff --git a/assembler/ext/src/llvm/raw_ostream.cpp b/assembler/ext/src/llvm/raw_ostream.cpp
index 3b5483f4d6..f771cd01cb 100644
--- a/assembler/ext/src/llvm/raw_ostream.cpp
+++ b/assembler/ext/src/llvm/raw_ostream.cpp
@@ -31,6 +31,7 @@
 #include <iterator>
 #include <sys/stat.h>
 #include <system_error>
+#include <inttypes.h>

 // <fcntl.h> may provide O_BINARY.
 #if defined(HAVE_FCNTL_H)
```

**Comment by alienzj** [comment]
Thanks!
