### ISSUE TITLE
spades-hammer: /opt/conda/conda-bld/spades_1578454341415/work/src/projects/hammer/kmer_data.cpp:388: void KMerDataCounter::FillKMerData(KMerData&): Assertion `data[i].count( )' failed.

### ISSUE THREAD

**Issue by Kaur-Rupinder** [ablab/spades#548]
Hello Sir,
I'm trying to run spades for error correction on 116 fasta files, it's failing the files having sizes in GB, it's working fine with small files. I'm providing it with 12 cores and 100 GB ram. I'm getting these two errors:
1. **spades-hammer: /opt/conda/conda-bld/spades_1578454341415/work/src/projects/hammer/kmer_data.cpp:388: void KMerDataCounter::FillKMerData(KMerData&): Assertion `data[i].count(
)' failed.**

2. **== Error ==  system call for: "['/home/rk/miniconda3/envs/de_novo_ass/bin/spades-hammer', '/mnt/hdd1/heartp/metagenomics/test/data/spade_error/corrected/configs/config.info'
]" finished abnormally, OS return value: -6**
my command line : _spades.py	-1	/mnt/hdd1/heartp/metagenomics/test/data/iu_clean_data/SRR6202082_R1.fastq.gz	-2	/mnt/hdd1/heartp/metagenomics/test/data/iu_clean_data/SRR6202082_R2.fastq.gz	-o /mnt/hdd1/heartp/metagenomics/test/data/spade_error	-t	12	-m	100	--only-error-correction_

And I want to ask 116 (paired-end) files, so do I have to create a new directory each time for each file or I can direct the output in one directory because it shows warnings that output directory must be empty. 

Thank you :)

**Comment by asl** [comment]
Hello.

Will you please attach your spades.log file as shown in the error message?

**Comment by Kaur-Rupinder** [comment]
[spades_error.log](https://github.com/ablab/spades/files/4959564/spades_error.log)

**Comment by asl** [comment]
The errors are likely due to I/O errors on the storage you're using. I'm seeing in the logs indication that some of SPAdes intermediate files were corrupted.
