### ISSUE TITLE
Pacbio corrected reads for hybrid assembly

### ISSUE THREAD

**Issue by faraz89** [ablab/spades#55]
Hi,
I have PacBio corrected subreads and i was thinking of using them instead of pre-corrected subreads for hybrid assembly with Illumina. Is it a better idea to use them?

Thanks.
Faraz.

**Comment by asl** [comment]
You can use them instead of ordinary pacbio reads provided that the coverage is enough.

**Comment by faraz89** [comment]
Thanks for replying.
Coverage is 12X. Good enough?

**Comment by asl** [comment]
Maybe not, it depends on both the quality of the reads and your Illumina data.

**Comment by faraz89** [comment]
Ok, let me explain my data little bit more:
1. The corrected pacbio reads i have is from a hybrid read correction approach . I used the illumina reads (the same one i will be using for spades hybrid assembly) for error correction of pacbio reads.
2. The coverage of illumina reads is 125X, which i feel is decent to do hybrid error correction of pacbio reads.
So these error corrected pacbio (however only 12X) reads are quite error free.

Now, my aim is to use illumina reads (125X) and error corrected pacbio reads (12X) to do hybrid assembly using SPades. And because my reads are already error corrected, i have decided to use --assembly-only parameter in SPades and skipping the read correction step.

What do you think?
Faraz.

**Comment by asl** [comment]
> And because my reads are already error corrected, i have decided to use --assembly-only parameter in SPades and skipping the read correction step.
Not your Illumina reads. SPAdes read error correction step applies only to Illumina / IonTorrent reads. Therefore omitting the option does not make much sense.

**Comment by faraz89** [comment]
Okay. In that case,  also the illlumina reads i have are already trimmed for quality and read length (using third-party software). So error correction in SPades hybrid assembly is really not necessary in my case. Isn't that so?

**Comment by asl** [comment]
First of all, we do not recommend extensive trimming before assembly since such trimming might create coverage gaps in low covered regions or regions with systematic errors. Second, the read error correction procedure is much more sophisticated with trivial trimming.

**Comment by faraz89** [comment]
Many thanks for clearing that up. I'll use the raw ones then. However i am presuming illumina reads should already be adapter trimmed though?

**Comment by asl** [comment]
Sure, all technical sequences should be removed.

**Comment by faraz89** [comment]
Thanks for your patience in answering my queries and developing such a handy tool. Appreciated.

**Comment by faraz89** [comment]
Hi Anton,
I read somewhere that there will be a new SPades version to be released sometime in January. I was about to start hybrid assembly with Illumina and Pacbio reads. Would you recommend me to wait till the new version is released that fixes few bugs? And if you can also please update on the release?

Thanks.
Faraz.
