### ISSUE TITLE
SPAdes error code 6

### ISSUE THREAD

**Issue by edward7498** [ablab/spades#550]
Hello. I'm using SPAdes but I got problems with error code 6

== Error ==  system call for: "['/usr/lib/spades/bin/spades-core', '/home/edward/Documents/Sample_sample_uph_tm3/spades_assembly/K33/configs/config.info', '/home/edward/Documents/Sample_sample_uph_tm3/spades_assembly/K33/configs/careful_mode.info']" finished abnormally, err code: -6

Here is my log and txt files
[params.txt](https://github.com/ablab/spades/files/4965854/params.txt)
[spades.log](https://github.com/ablab/spades/files/4965855/spades.log)

I am very beginner at this. So I really need help.
Thank you

**Comment by asl** [comment]
Hello

The problem is likely due to I/O problem on the storage you're using as one of SPAdes intermediate files got corrupted. And if you're very beginner – why you're specifying some advanced options (e.g k-mer length and your settings does not make any sense)? Stick to the defaults.
