### ISSUE TITLE
Assertion `index_.size() != 0' failed.

### ISSUE THREAD

**Issue by cba017** [ablab/spades#554]
Hi,
I got this error for half of the samples I ran through spades 3.14.0, it's toward the end of the run...
I'm attaching the log for one of the sample.
[spades.log](https://github.com/ablab/spades/files/4994674/spades.log)

**Comment by asl** [comment]
The log reads:

```
 0:01:35.318   761M / 10G   INFO    General                 (pair_info_count.cpp       : 212)   40 paired reads (0.00886664% of all) aligned to long edges
  0:01:35.327   489M / 10G   INFO    General                 (pair_info_count.cpp       : 356)     Insert size = 236.889, deviation = 115.226, left quantile = 124, right quantile = 419, read length = 136
```

So, either your input reads are corrupted (the left ones do not correspond to the right ones) or you're having very fragmented assembly. Make sure you're using paired-end aware trimmer.

Overall, given the # of input reads and the size of the assembly, it's highly unlikely to be a metagenome.
