### ISSUE TITLE
err code: -6  in spades progress

### ISSUE THREAD

**Issue by lstxmu** [ablab/spades#556]
Hi, 
I used the spades to assembly  a plant mitochondrial genome  and got  a error issue **(err code: -6).** The spades.log and params.txt had been attached.  
Please help me to fix the error issue, thanks a lot.

[spades.log](https://github.com/ablab/spades/files/5046726/spades.log)
[params.txt](https://github.com/ablab/spades/files/5046727/params.txt)

**Comment by asl** [comment]
Hello

It seems there was an I/O error on the storage you're using and one of input files was unable for reading. As it is likely that you used external drive for the SPAdes output and scratch dir, I would suggest you not to use it.

**Comment by lstxmu** [comment]
Hi. ASl
Thanks for your reply. But the SPAdes output and scratch are  in the extelrnal drive,  the assembly progress run in the  server local drive.
Did any guy meet this issue before?
Please help me fix this issue, Thanks a lot.

**Comment by asl** [comment]
> But the SPAdes output and scratch are in the extelrnal drive, 

This is exactly the problem I described. SPAdes was unable to read the files from your external drive because they were unavailable. Do not use external drive for any I/O-bound process like assembly job. Unfortunately, we cannot fix the problem with your local hardware.
