### ISSUE TITLE
Assertion `offset_stream' failed and OS return value: -6

### ISSUE THREAD

**Issue by summerXiaHan** [ablab/spades#559]
Hello, 
I am trying to de novo assemble transcriptome with multiple singleEnd RNA-seq libraries, and I met an issue:
<img width="1272" alt="屏幕快照 2020-08-18 下午5 57 16" src="https://user-images.githubusercontent.com/43634319/90499594-4fd86f00-e17c-11ea-8968-7d5b65f684f4.png">

Here are my commands and the running information.
`spades.py -o $outd --rna --dataset $yaml_file -t 30`
[spades.log](https://github.com/ablab/spades/files/5089669/spades.log)

Look forward to your reply, thanks!

**Comment by asl** [comment]
Hello

The problem is likely due to I/O problems. Given the number of input files, I would suggest checking (and increasing) the OS open file limit.
