### ISSUE TITLE
truSPAdes: dataset filename pattern 

### ISSUE THREAD

**Issue by stephanflemming** [ablab/spades#560]
Hi,

following the manual input files needs to have the following name pattern

```
dataset-directory:
reads_L1_R1.fastq
reads_L1_R2.fastq
reads_L2_R1.fastq
reads_L2_R2.fastq
```

That doesn't seem to work. Instead the name pattern from the test dataset is required.

```
dataset-directory:
A_R1.fastq.gz
A_R2.fastq.gz
B_R1.fastq.gz
B_R2.fastq.gz
```

Thanks for SPAdes :-)

Stephan

**Comment by asl** [comment]
Stephan,

Thanks for the report. truSPAdes is not maintained anymore for many reasons (the technology is dead, etc.), so these issues will likely be fixed in radical way when truSPAdes will be deprecated and removed

**Comment by asl** [comment]
truSPAdes is deprecated.
