### ISSUE TITLE
spades-hammer Error

### ISSUE THREAD

**Issue by francicco** [ablab/spades#561]
Hi,

I'm getting this error (SPAdes genome assembler v3.14.0)

```
  0:09:33.136    37M / 9G    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 314)   Building perfect hash indices
The program was terminated by segmentation fault
=== Stack Trace ===
The program was terminated by segmentation fault
=== Stack Trace ===
The program was terminated by segmentation fault
=== Stack Trace ===
The program was terminated by segmentation fault
=== Stack Trace ===
The program was terminated by segmentation fault
=== Stack Trace ===
[0x40a8b9]
[0x40aa26]
[0x5f36b0]
[0x5ec4c3]
[0x448a9a]
[0x449b0b]
[0x5dabae]
[0x5ebd54]
[0x653ea9]
[0x40a8b9]


== Error ==  system call for: "['/home/tk19812/software/SPAdes-3.14.0-Linux/bin/spades-hammer', '/work/tk19812/HeliconiniiProject/Hcly.Htel.refGuidedAssembly/Hcly.SPAdes/corrected/configs/config.info']" finished abnormally, OS return value: 1
```

Thanks a lot
F

**Comment by francicco** [comment]
I also got this error:

```
0:03:49.466    53M / 11G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 314)   Building perfect hash indices


== Error ==  system call for: "['/home/tk19812/software/SPAdes-3.14.0-Linux/bin/spades-core', '/work/tk19812/HeliconiniiProject/Hcly.Htel.refGuidedAssembly/Hcly.wtTrusted.SPAdes/K55/configs/config.info', '/work/tk19812/HeliconiniiProject/Hcly.Htel.refGuidedAssembly/Hcly.wtTrusted.SPAdes/K55/configs/careful_mode.info']" finished abnormally, OS return value: -11

======= SPAdes pipeline finished abnormally and WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:00.002     8M / 13M   WARN   StageManager             (stage.cpp                 : 150)   No saved checkpoint
======= Warnings saved to /work/tk19812/HeliconiniiProject/Hcly.Htel.refGuidedAssembly/Hcly.wtTrusted.SPAdes/warnings.log

=== ERRORs:
 * system call for: "['/home/tk19812/software/SPAdes-3.14.0-Linux/bin/spades-core', '/work/tk19812/HeliconiniiProject/Hcly.Htel.refGuidedAssembly/Hcly.wtTrusted.SPAdes/K55/configs/config.info', '/work/tk19812/HeliconiniiProject/Hcly.Htel.refGuidedAssembly/Hcly.wtTrusted.SPAdes/K55/configs/careful_mode.info']" finished abnormally, OS return value: -11
```

**Comment by asl** [comment]
Will you please provide spades.log file as you were instructed in the error message just after this github link?

Thanks!

**Comment by francicco** [comment]
[spades.log](https://github.com/ablab/spades/files/5122248/spades.log)

Here we go!
Thanks a lot
F

**Comment by asl** [comment]
You are likely run out of RAM. Please ensure that indeed 187 Gb of free RAM is allocated for your SPAdes job. Also note, that trusted-contigs feature is not suitable for "reference guided" assembly.

**Comment by francicco** [comment]
Thanks a lot. I'm using contigs from IDBA as trusted-contigs, is that ok?
F

**Comment by asl** [comment]
Provided that they are not misassembled. Also note that any scaffolds will be split by stretches of N's. So, ragoo-based scaffolding is useless :)

**Comment by francicco** [comment]
I'm filling gaps previously...
To be honest is not extremely efficient...
F

**Comment by behnamMA** [comment]
> You are likely run out of RAM. Please ensure that indeed 187 Gb of free RAM is allocated for your SPAdes job. Also note, that trusted-contigs feature is not suitable for "reference guided" assembly.

I have faced this error too and I can't support more than 8 Gb of RAM for SPAdes's task. In this situation what can I do?  
Thank you.

**Comment by asl** [comment]
> I'm getting a similar error message, but I used to run spades without any problems on my 48gb ram pc...

Then you problem might be different. You can consider opening a new issue and not hijacking old / closed ones.
