### ISSUE TITLE
MetaSPAdes

### ISSUE THREAD

**Issue by Alex-132** [ablab/spades#562]
Hi, 
I ran several MetaSPAdes assemblies (SPAdes Version 3.14.1), but the last assembly has repeatedly not worked and showed the following error:
finished abnormally, OS return value: -6

[params.txt](https://github.com/ablab/spades/files/5101348/params.txt)
[spades.log](https://github.com/ablab/spades/files/5101349/spades.log)

**Comment by Alastor-pentious** [comment]
Same issue here,i ran a "spades --test",and results indicate "== Error ==  system call for: "['/home/yuanchao/miniconda3/envs/megahit/bin/spades-core', '/home/yuanchao/metagenomics-2/assembly-test2/spades_test/K21/configs/config.info']" finished abnormally, OS return value: -6
", i wonder whether my installation directory under conda enviroment was wrong. Ask for help!

**Comment by asl** [comment]
@Alex-132 

The log reads:
```
  8:44:16.954    97G / 336G  INFO    General                 (pair_info_count.cpp       :  39)   Selecting usual mapper
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

Looks like SPAdes was unable to create some of the processing threads. We do not have solution for this as the error was provided by your OS. Restarting the job in less crowded server may help.

@Alastor-pentious You may want to read the error message, provide the files mentioned there and do not hijack the other issues even if they look for some reason similar to you.
