### ISSUE TITLE
Poly-N insertion

### ISSUE THREAD

**Issue by giantoni** [ablab/spades#563]
Hello!

I am using for the first time rnaSPAdes (version 3.14) and I am getting sequences with the insertion of poly-N in the default mode (I did not change any arguments). Is this supposed to happen? Large sequences have some poly-N and I am thinking if this could be a sign that I have chimeric sequences maybe?

Thanks in advance!
Gisele

**Comment by asl** [comment]
Sure. This is called "scaffolding". Please refer to SPAdes manual (https://cab.spbu.ru/files/release3.14.1/manual.html#sec3.5) for more information.
