### ISSUE TITLE
Assertion `seq_.size() == qual_.size()' failed

### ISSUE THREAD

**Issue by thisisliuqing** [ablab/spades#564]
I'm running spades for assambling a bacterial genome. 
I'm using the following command:
~/SPAdes-3.14.1-Linux/bin/./spades.py -o 16969 -k 21,33,55,77,87,97,117 --careful --only-assembler -1 16969.clean.1.fastq.gz -2 16969.clean.2.fastq.gz -t 36

But I get an error:

=== Stack Trace ===
[0x40e089]
[0x42e979]
[0x6c38cd]
[0x4ff943]
[0x6c6c1b]
[0x6c5169]
[0xa0c5c3]
[0x6c975a]
[0x6c9a33]
[0x6c5169]
[0xa0c5c3]
[0x6c975a]
[0x6c9804]
[0x6d43c5]
[0x9642c0]
[0xa07584]
[0xa73489]
Verification of expression 'seq_.size() == qual_.size()' failed in function 'void io::SingleRead::Init()'. In file '/spades/assembler/src/common/io/reads/single_read.hpp' on line 223. Message 'Invalid read: length of sequence should equal to length of quality line'.
Verification of expression 'seq_.size() == qual_.size()' failed in function 'void io::SingleRead::Init()'. In file '/spades/assembler/src/common/io/reads/single_read.hpp' on line 223. Message 'Invalid read: length of sequence should equal to length of quality line'.
spades-core: /spades/assembler/src/common/io/reads/single_read.hpp:223: void io::SingleRead::Init(): Assertion `seq_.size() == qual_.size()' failed.

== Error ==  system call for: "['/home/liu/soft/SPAdes-3.14.1-Linux/bin/spades-core', '/home/liu/F/genome_assem/16969/K21/configs/config.info', '/home/liu/F/genome_assem/16969/K21/configs/careful_mode.info']" finished abnormally, OS return value: -6

**Comment by asl** [comment]
So, as you could see from the log the problem is as follows:

```
 Message 'Invalid read: length of sequence should equal to length of quality line'.
```

Please let us know if there are any other problems.
