### ISSUE TITLE
rnaspades ran with only 1 kmer size

### ISSUE THREAD

**Issue by hungmai1984** [ablab/spades#565]
Hi all,
I am a beginner with spades. I assembled using rnaspades. In the manual, I saw that spades will use 2 kmer size to assemble but in my case it used only one kmer size. Could you explain me why. I attached here the spades log. Thank you
[spades.log](https://github.com/ablab/spades/files/5152416/spades.log)

**Comment by asl** [comment]
Looks like your SPAdes installation is broken:
```
  SPAdes version: 3.11.1
```
But it seems you should be running 3.14?

**Comment by hungmai1984** [comment]
> Looks like your SPAdes installation is broken:
> 
> ```
>   SPAdes version: 3.11.1
> ```
> 
> But it seems you should be running 3.14?
> 
> Likely you run `rnaspades.py`, but wanted `./rnaspades.py`?

Thank you very much, when I downloaded spades 3.14 and installed, it also showed me 3.11. I do not know why. Could you give me the link spades 3.14. Thank you

**Comment by asl** [comment]
Sure: https://cab.spbu.ru/software/spades/

**Comment by hungmai1984** [comment]
> Sure: https://cab.spbu.ru/software/spades/

Thank you Anton for the link. I followed the manual but after compiling, the spades didn't work. It asked me to install spades using sudo apt install spades. But if I did, it installed the spades 3.11.1 from ubuntu. I attached the screen here. Could you tell me how to fix it. Thank you
![Screenshot from 2020-09-01 10-06-54](https://user-images.githubusercontent.com/70543410/91885686-0dfbfe00-ec3d-11ea-850c-c564d294d62e.png)

**Comment by asl** [comment]
We are not supporting SPAdes from Debian / Ubuntu. They are known to be modified by Debian / Ubuntu maintainers and we cannot support this. The message you're seeing it's likely from it.

But again, let me reiterate my question as it seems you're not reading neither it nor manual properly: "I believe you wanted to run spades.py from the current directory via `./spades.py` and not system-wide one via `spades.py`.

**Comment by hungmai1984** [comment]
> > Sure: https://cab.spbu.ru/software/spades/
> 
> Thank you Anton for the link. I followed the manual but after compiling, the spades didn't work. It asked me to install spades using sudo apt install spades. But if I did, it installed the spades 3.11.1 from ubuntu. I attached the screen here. Could you tell me how to fix it. Thank you
> ![Screenshot from 2020-09-01 10-06-54](https://user-images.githubusercontent.com/70543410/91885686-0dfbfe00-ec3d-11ea-850c-c564d294d62e.png)

Thank you so much, I solved the problem

**Comment by hungmai1984** [comment]
Sorry to bother you again Anton,
The rnaspades ran with two kmer size but it switch off the "read error correction". I attached the spades log. Could you help me. Thank you
[spades.log](https://github.com/ablab/spades/files/5159152/spades.log)

**Comment by asl** [comment]
It's ok
