### ISSUE TITLE
Unable to do the kmer counting // OS return value -6

### ISSUE THREAD

**Issue by adriaaula** [ablab/spades#568]
Hello there! 

I ran metaspades for metaG assembly (coassembly, in fact), and it failed starting the kmer counting.
![image](https://user-images.githubusercontent.com/15213478/92232145-4e15e780-eeae-11ea-898f-b62b82578226.png)

The job is sent in a SLURM job system with spades installed locally. 

Any ideas and what is wrong? 

[params.txt](https://github.com/ablab/spades/files/5174359/params.txt)
[spades.log](https://github.com/ablab/spades/files/5174361/spades.log)

Thanks in advance!

**Comment by asl** [comment]
One of SPAdes intermediate files is corrupted likely due to I/O issue on your end.

**Comment by adriaaula** [comment]
Could you develop? 
It is likely not the issue since I have 3 coassemblies, and all three stopped in the same step with the same logs..

**Comment by asl** [comment]
Well, this perfectly confirms the I/O problems then. It seems you're using Lustre and some installations of Lustre are known before to be buggy. You would probably need to ask your system administrator.
