### ISSUE TITLE
What does duplicated nodes in assembly graph file mean

### ISSUE THREAD

**Issue by yaohaobin** [ablab/spades#569]
Dear spades developer,
    I used spades to assemble some pair-end reads. When inspecting the assembly graph (contigs.paths), I see each nodes has two  rows:
     NODE_1_length_1355498_cov_42.5134
     NODE_1_length_1355498_cov_42.5134'

     What does the second line mean? Thanks!

Haobin

**Comment by asl** [comment]
The prime (') symbol indicates reverse-complement sequence

Note that contig.paths is *not* an assembly graph.
