### ISSUE TITLE
<jemalloc>: Error in malloc(): out of memory  Requested: 56

### ISSUE THREAD

**Issue by noisrevni** [ablab/spades#570]
input:
`spades.py --cov-cutoff auto --isolate -m 10 -1 /home/ziyi/BatchThree/JJ26_FDSW202240639-1r/JJ26_FDSW202240639-1r_1.clean.fq.gz -2 /home/ziyi/BatchThree/JJ26_FDSW202240639-1r/JJ26_FDSW202240639-1r_2.clean.fq.gz -o /home/ziyi/BatchThree/JJ26_spades`

print:
<jemalloc>: Error in malloc(): out of memory
 Requested: 56

== Error ==  system call for: "['/home/ziyi/anaconda3/envs/torsten/bin/spades-core', '/home/ziyi/BatchThree/JJ03_spades/K21/configs/config.info', '/home/ziyi/BatchThree/JJ03_spades/K21/configs/isolate_mode.info']" finished abnormally, OS return value: -6

[spades.log](https://github.com/ablab/spades/files/5178247/spades.log)

**Comment by asl** [comment]
So, the log reads:

```
Error in malloc(): out of memory
```

You're running out of RAM
