### ISSUE TITLE
Question Metaspades

### ISSUE THREAD

**Issue by pbravakos** [ablab/spades#571]
Hi,
I am running Metaspades on a SLURM cluster and I notice that during the "Starting k-mer counting" phase of the analysis the system goes to ininteruptible sleep for long period of time (e.g. 30 hours). Is this something normal?

The command i gave was the following
```
./spades.py  --only-assembler        --meta  -k      23,31,43,55,71,83,91    --dataset Reads.yaml   -t   32      -o   CCOSD    --memory  628  --checkpoints   last    --tmp-dir   tmp_CCOSD
```
Thanks

**Comment by asl** [comment]
Hello

No, it is not. You're likely hitting some I/O issues on your storage. You may want to ask your system administrator

**Comment by pbravakos** [comment]
Thanks for the fast response.
In another question, if I stop a running Spades job (with the command I gave above) and try to submit a second job with the command
```
./spades.py --continue
```
then I get the following error 

```
Traceback (most recent call last):
  File "/home1/pbravakos/Software/SPAdes-3.14.1-Linux/bin/spades.py", line 643, in <module>
    main(sys.argv)
  File "/home1/pbravakos/Software/SPAdes-3.14.1-Linux/bin/spades.py", line 572, in main
    init_parser(args)
  File "/home1/pbravakos/Software/SPAdes-3.14.1-Linux/bin/spades.py", line 560, in init_parser
    os.path.join(options_parser.get_output_dir_from_args(), "params.txt"),
  File "/home1/pbravakos/Software/miniconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Do you have any idea why I get this error?

**Comment by asl** [comment]
You are missing the -o option to specify what to continue :)

**Comment by pbravakos** [comment]
Thanks!
