### ISSUE TITLE
question about memory limitation

### ISSUE THREAD

**Issue by Genan-blur** [ablab/spades#572]
Hi:
  There're something wrong with my spades running, I only got 32GB RAM, but the error warns me that I need approx.42.8GB of free RAM.(The reads contain too many k-mers to fit into available memory. You need approx. 42.8GB of free RAM to assemble your dataset)
 Is there any possible way to solve this problem with my 32 GB RAM.
  Please help! Thanks!

**Comment by asl** [comment]
Well, you may try to perform some heavy quality trimming and / or subsampling. Also note that in practice you do not have 32 Gb. In really it's less than 30 due to memory needed for OS, etc.

**Comment by Genan-blur** [comment]
Thanks for your kindly reply,  I will try to trim my data.
