### ISSUE TITLE
metaspade error code 24

### ISSUE THREAD

**Issue by jessikamarquis** [ablab/spades#575]
Hello, this error code 24 keeps coming up -- can someone help me out.

[params.txt](https://github.com/ablab/spades/files/5232440/params.txt)
[spades.log](https://github.com/ablab/spades/files/5232441/spades.log)

== Error ==  system call for: "['/gpfs/fs1/home/j/jronho/jmarquis/miniconda2/share/spades-3.13.0-0/bin/spades-hammer', '/gpfs/fs0/scratch/j/jronho/jmarquis/ASSEMBLY/metaspades/corrected/configs/config.info']" finished abnormally, err code: -24

**Comment by asl** [comment]
Can you give SPAdes  3.14.1 a try?

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
