### ISSUE TITLE
Conflict of directory names (simplified_contigs.fasta vs simplified_contigs) of metaviralspades and spades

### ISSUE THREAD

**Issue by TarkhovAndrei** [ablab/spades#576]
When calculating with different contig lengths, for example, K21, K33, etc. The code is trying to find the previous contigs in the directory `/K21/simplified_contigs.fasta`, whereas it is called '/K21/simplified_contigs'. 

The bug was fixed by changing line 130 in `/spades/assembler/src/spades_pipeline/stages/spades_iteration_stage.py`
from 

`additional_contigs_fname = os.path.join(cfg.output_dir, "K%d" % self.prev_K, "simplified_contigs.fasta")`
to 
`additional_contigs_fname = os.path.join(cfg.output_dir, "K%d" % self.prev_K, "simplified_contigs")`

**Comment by asl** [comment]
The problem must be elsewhere as this situation should never happen. It seems that your SPAdes and metaviralSPAdes installations are somehow mixed e.g. python code from old SPAdes and metaviralSPAdes binaries or vice versa

**Comment by asl** [comment]
metaviralSPAdes is a part of SPAdes 3.15. Please reopen if this is still an issue
