### ISSUE TITLE
Variable length scaffold

### ISSUE THREAD

**Issue by LauraVP1994** [ablab/spades#580]
Dear,

I am using SPADES for the de novo assembly of avian influenza viruses of variable concentrations (sequenced with Illumina MiSeq). Avian influenza genome consists of 8 separate segments and after a first use of SPADES I extract per segment the resulting scaffold. I use this sequence then as reference for Bowtie2 and make new fastq.gz files that map against this reference. Then I use these new fastq.gz files (per segment) to run spades again. This is done at least 5 times and then I check if the resulting scaffold length remains more or less stable. For some samples all of the segments give quite quickly a stable outcome, however some segments of samples this varies a lot (sometimes up to 400 bp)! This happens both in samples with a high and low concentration.

The current parameters I use for the bowtie2 are:
bowtie2 --local -D 25 -R 4 -L 3 -N 1 -p 8 --gbar 1 --mp 3
and for spades: spades.py -k 127 --careful --cov-cutoff auto

Did you already encounter the same problem? Or do you have any tips how this change in scaffold length between loops can be prevented or improved?

Thank you 
Laura

**Comment by asl** [comment]
Hello

Can you given rnaviralSPAdes a try? I don't think that your approach of using SPAdes in normal multicell isolate mode that expects even coverage and does not have enabled any procedures that deal with RNA-seq sequencing artifacts would work :)

Do you happen to have some HMM models for proteins from all these 8 segments?

**Comment by LauraVP1994** [comment]
Dear,

Thank you for the quick response! This was not done with RNA-seq. The viral RNA was amplified with RT-PCR and then sequenced with Illumina MiSeq. 

Kind regards
Laura

**Comment by asl** [comment]
Well, still this is an RNA viral dataset. With uneven coverage, multiple strains and subspecies, right?

**Comment by LauraVP1994** [comment]
Yes, I can try this viralrnaSPADES. Which parameters do you recommend to run this?

Thank you!

**Comment by asl** [comment]
If unsure – stick to defaults. This rules works in the vast majority of cases.

If you're having some HMM models for viral proteins, then you could use it as well to supplement assembly.

rnaviralSPAdes is a part of coronaSPAdes: https://cab.spbu.ru/software/coronaspades/

**Comment by LauraVP1994** [comment]
OK, thank you. I don't have these HMM models unless I can generate this myself?

**Comment by asl** [comment]
Well. I guess given the origin of the data, these models should be well-known and available. Though, you'd know better than myself. In any case, this is something optional.

**Comment by LauraVP1994** [comment]
Dear,

I tried the coronaSPAdes as you recommended, but it doesn't seem to work in almost the same cases as when I used SPAdes. This also happened in samples with a very high coverage, could this be a problem?

Kind regards
Laura

**Comment by asl** [comment]
@LauraVP1994 will it be possible for you to be a bit more verbose? E.g. what you did? What are the problems you're seeing, etc.

**Comment by LauraVP1994** [comment]
As a first step I use the rnaviralspades.py on my influenza sample, next I blast the scaffolds and extract the scaffold of each segment (there are 8 segments in the influenza genome) and I continue for each segment separately. I use bowtie2 to extract the reads that mapped against the scaffold of a particular segment and next I use rnaviralspades.py again to make new scaffolds for this particular segment. Again I blast the scaffolds and extract the sequence and then use bowtie again to extract the reads that mapped against this sequence. I looped this for at least 5 times and the length of the sequences cannot vary more than 20 bp for at least the last five iterations (so iterate until spades becomes more or less stable).  For 3/4 of the sequences this works fine, however it doesn't work for also quite a few samples that have a very high coverage. I read somewhere that SPAdes has maybe trouble with high coverages? Or are there other ways to improve this?

**Comment by asl** [comment]
Why are you doing this? What is the rationale?

Note that segments overlap in the ends. So "extracting reads" is an ambiguous operation as reads may have multiple alignments.

Also, there might be quite a lot of variation there. Have you checked for it?

**Comment by LauraVP1994** [comment]
The influenza genome consists out of 8 segments that are really separate from each other, so they don't overlap each other. The extracting of the reads is done each time starting from the original fastq file for each segment (so if one read is attributed to one segment, it doesn't mean it cannot be attributed to another). The reason for the iteration was to obtain a de novo assembly that is as long as possible and that is stable. At the moment this can change sometimes change each loop: Loop 1 length=1360; Loop 2 length=1141; Loop 3 length=1356; Loop 4 length=1136;  Loop 5 length=1360; Loop 6 length=1141; Loop 7 length=1356; Loop 8 length=1136 ....

**Comment by asl** [comment]
The segments do overlap in the UTRs as they are quite conserved. rnaviralSPAdes was just released as a part of SPAdes 3.15. For assembling influenza data we're suggesting to pair it with Influenza protein HMMs from Rvdp-Prot
[U-RVDBv20.0-prot-influenza.hmm.gz](https://github.com/ablab/spades/files/5819116/U-RVDBv20.0-prot-influenza.hmm.gz)
