### ISSUE TITLE
Error code 2

### ISSUE THREAD

**Issue by flannsmith** [ablab/spades#581]
For a sample I was getting error code 255 - Failed to determine offset. After specifying --phred-offset in the command the new error is: 
`0:00:01.496     1G / 4G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /external_HDD/linda/GW_FVT_SF_Zoo/metapades_assemblies/metaspades_Z001_S125/tmp/hammer_5W9yoO/kmer_splitter_nwKw5B/kmers_raw_fnG5iM.2`

Full error log: 

== Running read error correction tool: /usr/local/src/SPAdes-3.13.0-Linux/bin/spades-hammer /external_HDD/linda/GW_FVT_SF_Zoo/metapades_assemblies/metaspades_Z001_S125/corrected/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.13.0, git revision 8ea46659e9b2aca35444a808db550ac333006f8b
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from /external_HDD/linda/GW_FVT_SF_Zoo/metapades_assemblies/metaspades_Z001_S125/corrected/configs/config.info
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 5
  0:00:00.000     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 250 Gb
  0:00:00.000     4M / 4M    INFO    General                 (hammer_tools.cpp          :  36)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.000     4M / 4M    INFO   K-mer Counting           (kmer_data.cpp             : 280)   Estimating k-mer count
  0:00:00.056    84M / 84M   INFO   K-mer Counting           (kmer_data.cpp             : 285)   Processing /data/users/linda/GW_FVT_SF_Zoo/trimmomatic/Z001_S125_paired_1.fastq.gz
  0:00:00.056    84M / 84M   INFO   K-mer Counting           (kmer_data.cpp             : 285)   Processing /data/users/linda/GW_FVT_SF_Zoo/trimmomatic/Z001_S125_paired_2.fastq.gz
  0:00:00.056    84M / 84M   INFO   K-mer Counting           (kmer_data.cpp             : 299)   Total 0 reads processed
  0:00:01.495     4M / 84M   INFO   K-mer Counting           (kmer_data.cpp             : 311)   Filtering singleton k-mers
38 8 0
nslots: 1073741824
bits per slot: 8 range: 0000004000000000
  0:00:01.495     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /data/users/linda/GW_FVT_SF_Zoo/trimmomatic/Z001_S125_paired_1.fastq.gz
  0:00:01.495     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /data/users/linda/GW_FVT_SF_Zoo/trimmomatic/Z001_S125_paired_2.fastq.gz
  0:00:01.495     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 331)   Total 0 reads processed
  0:00:01.495     1G / 1G    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 301)   Building kmer index
  0:00:01.495     1G / 1G    INFO    General                 (kmer_index_builder.hpp    : 117)   Splitting kmer instances into 80 files using 5 threads. This might take a while.
  0:00:01.495     1G / 1G    INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1024
  0:00:01.495     1G / 1G    INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 16.5818 Gb
  0:00:01.495     1G / 1G    INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 838860
  0:00:01.496     4G / 4G    INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /data/users/linda/GW_FVT_SF_Zoo/trimmomatic/Z001_S125_paired_1.fastq.gz
  0:00:01.496     4G / 4G    INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /data/users/linda/GW_FVT_SF_Zoo/trimmomatic/Z001_S125_paired_2.fastq.gz
  0:00:01.496     4G / 4G    INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 0 reads processed
  0:00:01.496     1G / 4G    INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  0:00:01.496     1G / 4G    ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such file or directory. Error code: 2. File: /external_HDD/linda/GW_FVT_SF_Zoo/metapades_assemblies/metaspades_Z001_S125/tmp/hammer_5W9yoO/kmer_splitter_nwKw5B/kmers_raw_fnG5iM.2

== Error ==  system call for: "['/usr/local/src/SPAdes-3.13.0-Linux/bin/spades-hammer', '/external_HDD/linda/GW_FVT_SF_Zoo/metapades_assemblies/metaspades_Z001_S125/corrected/configs/config.info']" finished abnormally, err code: 255

I deleted the sample's folder containing tmp in an attempt to hard reset metaspades to assemble from scratch but it is still giving this error.

**Comment by asl** [comment]
The log reads:
```
0:00:00.056 84M / 84M INFO K-mer Counting (kmer_data.cpp : 299) Total 0 reads processed
```

Given that Phred offset detection failed previously as well, I'd suspect that your reads are corrupted or not a valid FASTQ.
