### ISSUE TITLE
Spades == Error ==, run finishaed abnormally with OS return value: -9

### ISSUE THREAD

**Issue by Lamm-a** [ablab/spades#584]
I am running metaspades an a fairly large metagenome (~12G) and I am getting the following error very very early into the run:

`== Error ==  system call for: "['/home/lamma/miniconda3/envs/fungal-hybrid-assembly/bin/spades-hammer', '/home/lamma/ABR/Meta_Spades_J/1_data/Each_sample/pilot/spades-output/Unmap_105/corrected/configs/config.info']" finished abnormally, OS return value: -9`

This metaspades is being run on a cluster with a slurm queue system, but other jobs have run fine. I could not identify a cause from the log myself.

Any ideas as to the cause?

Relavent files:
[params.txt](https://github.com/ablab/spades/files/5312212/params.txt)
[spades.log](https://github.com/ablab/spades/files/5312213/spades.log)

**Comment by biobrad** [comment]
@Lamm-a I don't think it is weird. I have 128gig of RAM and I can't run metagenomes on my system.
I have to use our High performance cluster and give it at least 250gig RAM to run metaspades. 
30Gig is going to be no where near enough.

**Comment by asl** [comment]
@Lamm-a you're clearly running out of RAM.
