### ISSUE TITLE
The program was terminated by segmentation fault === Stack Trace ===

### ISSUE THREAD

**Issue by flannsmith** [ablab/spades#585]
**Spades.log** 

Command line: /home/flannsmith/genome_assemblies/SPAdes-3.14.1-Linux/bin/spades.py      -m      20      -t      5       --phred-offset  33      --meta  --pe1-1 /home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_1.fastq.gz     --pe1-2 /home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_2.fastq.gz        -o  /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62

System information:
  SPAdes version: 3.14.1
  Python version: 3.7.3
  OS: Linux-4.19.0-10-cloud-amd64-x86_64-with-debian-10.5

Output dir: /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_1.fastq.gz']
      right reads: ['/home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset: 33
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62/tmp
  Threads: 5
  Memory limit (in Gb): 20

======= SPAdes pipeline started. Log can be found here: /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62/spades.log

/home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_1.fastq.gz: max reads length: 141
/home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_2.fastq.gz: max reads length: 141

Reads length: 141

===== Before start started.

===== Read error correction started.

===== Read error correction started.

== Running: /home/flannsmith/genome_assemblies/SPAdes-3.14.1-Linux/bin/spades-hammer /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===

== Error ==  system call for: "['/home/flannsmith/genome_assemblies/SPAdes-3.14.1-Linux/bin/spades-hammer', '/home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62/corrected/configs/config.info']" finished abnormally, OS return value: -11

**params.txt**

Command line: /home/flannsmith/genome_assemblies/SPAdes-3.14.1-Linux/bin/spades.py      -m      20      -t      5       --phred-offset  33      --meta  --pe1-1 /home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_1.fastq.gz     --pe1-2 /home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_2.fastq.gz        -o  /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62

System information:
  SPAdes version: 3.14.1
  Python version: 3.7.3
  OS: Linux-4.19.0-10-cloud-amd64-x86_64-with-debian-10.5

Output dir: /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_1.fastq.gz']
      right reads: ['/home/flannsmith/genome_assemblies/GW_SF_metapool2/trimmomatic/S2b_S62_paired_2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset: 33
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/flannsmith/genome_assemblies/GW_SF_metapool2/metaspades_assemblies/metaspades_S2b_S62/tmp
  Threads: 5
  Memory limit (in Gb): 20

My VM has 32GB RAM but I specified 20GB limit to see if the segmentation error still occurred. What is the minimum memory requirement for spades?

**Comment by asl** [comment]
Please recompile SPAdes from sources. Likely the precompiled binaries are not compatible with your version of Debian. Please reopen if after recompilation the error is still there
