### ISSUE TITLE
Is the assembled sequence only the forward strand sequence? 

### ISSUE THREAD

**Issue by yangyxt** [ablab/spades#587]
I'm using illumina paired end data as input of spades.py.

I wonder if the contigs.fasta file only show the forward strand sequence?

**Comment by asl** [comment]
There is no way to determine the strand from the input data. So, contigs might belong to any strand.

**Comment by yangyxt** [comment]
> There is no way to determine the strand from the input data. So, contigs might belong to any strand.

According to the manual: 
"By default, SPAdes assumes that paired-end and high-quality mate-pair reads have forward-reverse (fr) orientation and usual mate-pairs have reverse-forward (rf) orientation. However, different orientations can be set for any library by using SPAdes options."

Does that mean by default, SPAdes will use the sequence from read1.fastq and reverse-complement sequence from read2.fastq to generate the contig.fasta file?
