### ISSUE TITLE
metaSpades 3.14.0 Error in malloc(): out of memory (error code -6), but 3.13.1 not

### ISSUE THREAD

**Issue by PandengWang** [ablab/spades#588]
I first used spades.py (version 3.14.0) to assemble my metagenomic data (~30GB), for some samples it returned error code -6 during error correction stage. However, when I assembled the **same dataset** using spades.py version 3.13.1, the whole assembly pipeline could be finished without any error.

Our server has 1TB RAM. I'm sure that when spades.py version 3.14.0 threw the out of memory error, the server still had more than 300 GB available RAM.

Do you have any suggestion? Thanks!

[spades.log](https://github.com/ablab/spades/files/5369768/spades.log)

**Comment by asl** [comment]
Well, unfortunately the error means that SPAdes failed to receive memory from the system. There is no workaround for this problem, your OS simply did not fulfil SPAdes request to allocate more RAM. We have no control over this situation and have to pass the error on you. Maybe some additional trimming / quality filtering of the data will change the situation. As well running in some other time with different pattern of jobs being run on your server.

**Comment by asl** [comment]
Please give the latest SPAdes 3.15.0 a try. Reopen if this is still an issue
