### ISSUE TITLE
Is the assembled sequence by default the same strand as the sequences in read1.fastq file? 

### ISSUE THREAD

**Issue by yangyxt** [ablab/spades#589]
According to the manual:
"By default, SPAdes assumes that paired-end and high-quality mate-pair reads have forward-reverse (fr) orientation and usual mate-pairs have reverse-forward (rf) orientation. However, different orientations can be set for any library by using SPAdes options."

Does that mean by default, SPAdes will use the sequence from read1.fastq and reverse-complement sequence from read2.fastq to generate the contig.fasta file?

**Comment by asl** [comment]
Not that easy. But basically for reads in forward-backward orientation SPAdes assumes that one read comes from one strand and another one – from the opposite one
