### ISSUE TITLE
Question on --careful mode

### ISSUE THREAD

**Issue by tyang39** [ablab/spades#590]
Hello,

I am wondering what you guys consider are "small genomes" to run using careful mode. I am trying to run assemblies on some fungal genomes (50-70Mb) and was wondering if it is recommended to use careful mode or proceed without it? Thank you.

**Comment by asl** [comment]
Might be ok

**Comment by tyang39** [comment]
Running careful mode has resulted in a 0 N's per 100 kbp, can we trust that data? is it valid or is there some kind of underlying computational issue or parameter I should look into?

**Comment by asl** [comment]
Why do you think it is a problem? Contigs per definition do not have N's. And scaffolds might be identical to contigs if there is nothing to scaffold.
