### ISSUE TITLE
How to run SPAdes 3.14.1

### ISSUE THREAD

**Issue by Tinh1425** [ablab/spades#591]
Hello everyone,

I have Illumina sequenced data and I would like to do De Novo Assembly with SPAdes. However, I don't know which commands I should use. Could someone help me with that? Thank you in advance.

Best,

Tinh

**Comment by asl** [comment]
Hello

Have you tried to look into SPAdes manual?  https://cab.spbu.ru/files/release3.14.1/manual.html
Or into "Using SPAdea" paper? https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cpbi.102

Hope this helps

**Comment by Tinh1425** [comment]
Hello Anton,

Thank you for your useful links. I have run and there is a warning with my data as below. Could you give me some suggestions to solve this problem?

====== SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:38.967   104M / 8G    WARN    General                 (pair_info_count.cpp       : 360)   Estimated mean insert size 129.675 is very small compared to read length 132
======= Warnings saved to /home/vimac/Tinh/SPAdes-3.14.1-Linux/bin/spades_output/warnings.log

SPAdes log can be found here: /home/vimac/Tinh/SPAdes-3.14.1-Linux/bin/spades_output/spades.log

**Comment by asl** [comment]
This is the property of your input data. I'd suggest you to talk about this with whoever produced with data for you. It seems that you left reads almost fully overlap with the right ones.

**Comment by Tinh1425** [comment]
Indeed, my data is paired-end reads 2x150. My command I used is as below. Do you think it is correct?

spades.py -o spades_output --pe1-1 clean_1.fastq.gz --pe1-2 clean_2.fastq.gz

**Comment by asl** [comment]
Well, as I said, this is how the library was prepared. The cmdline seems to be correct.
