### ISSUE TITLE
spades --rna terminated abnormally with error code --24 

### ISSUE THREAD

**Issue by anapopov** [ablab/spades#592]
Hi,

I ran a transcriptome assembly with the command below, with and without setting a memory limit and with and without redirecting the --tmp-dir to a /home/ or /scratch/ directory on the computing cluster (I've tried placing the folder in a few places). Each time, assembly fails with an err code -24 message (also fully pasted below). I've attached the params.txt and spades.log files.

For the paired files, the sequence headers match exactly.

Any suggestions?
Thanks!

Command submitted:
~/tools/SPAdes-3.11.1-Linux/bin/spades.py --rna -1 pair_1.fastq -2 pair_2.fastq -s singletons.fastq -o test_out -m 100 --tmp-dir /scratch/j/../final_results/test_out/

Error:
== Error ==  system call for: "['/gpfs/fs1/home/j/jparkin/apopovic/tools/SPAdes-3.11.1-Linux/bin/hammer', '/gpfs/fs0/scratch/j/../test_out/corrected/configs/config.info']" finished abnormally, err code: -24

[params.txt](https://github.com/ablab/spades/files/5403468/params.txt)
[spades.log](https://github.com/ablab/spades/files/5403469/spades.log)

**Comment by anapopov** [comment]
Hours later, I figured it out just after posting the issue!

It was a memory issue after all, despite the -memory flags I tried. It did finish successfully when I logged into a higher memory debug node.

**Comment by asl** [comment]
PS: Please note that the current version of SPAdes is 3.14.1 and it contains lots of improvements towards transcriptome assemblies. Consider upgrading
