### ISSUE TITLE
IUPAC codes

### ISSUE THREAD

**Issue by Tipplynne** [ablab/spades#593]
Good day

Apologies if this is a question that has already been addressed (I could not find any threads related to iupac codes). I have a large Eukaryotic genome assembly (1.2 out of 1.5GB) produced with SPAdes, that we am struggling to polish with Pilon (which we are doing to keep the IUPAC codes for heterozygosity). Is there a way to assemble the genome with the IUPAC codes?

Thanks and kind regards
crystal

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

SPAdes is ACGTN-only. No other nucleotides are going to be produced.
