### ISSUE TITLE
rnaspades missing transcript output

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [ablab/spades#594]
Hello,

I'm trying to use rnaspades on rna-seq data and I am unsure about output as no transcript file is found at the end of a successful run. So, no transcripts.fasta, transcripts.path, hard or soft filtered paths. 

Instead in the K61 folder I can see a final_contigs.fasta. 

I'm using spade 3.14.1 from a conda install, the command launched :
 `rnaspades.py -1 {input.R1} -2 {input.R2} -t 100 -m 2500 -o $(dirname {output}) &>{log}`

Strangely the logs generated by spades always end up corrupted (missing the start) but the ones from redirecting std out are fines, here are both : 
[spades.log](https://github.com/ablab/spades/files/5416357/spades.log)
[assembly.log](https://github.com/ablab/spades/files/5416358/assembly.log)

Do you have any clue?

**Comment by asl** [comment]
Hello

Well, the problem with spades.log should be something local (e.g. a snakemake issue). The log reads:

```
  2:26:14.274    27G / 57G   INFO    General                 (pair_info_count.cpp       : 208)   Edge pairs: 2117894
  2:26:14.283    27G / 57G   INFO    General                 (pair_info_count.cpp       : 212)   0 paired reads (0% of all) aligned to long edges
  2:26:14.629    26G / 57G   WARN    General                 (pair_info_count.cpp       : 341)   Unable to estimate insert size for paired library #0
  2:26:14.639    26G / 57G   WARN    General                 (pair_info_count.cpp       : 347)   None of paired reads aligned properly. Please, check orientation of your read pairs.
```

So, it seems that your input reads are corrupted somehow

**Comment by Sebastien-Raguideau** [comment]
Hi,
Thanks for the swift answer. Yes this part of the log eluded me. What sort of reads malformation do you thinks may be the cause? Something like both reverse transposed? 

I was wondering if this is because I'm doing metaproteomic of prokaryotes where splicing is way more limited. 

Theses reads went through 2 filtering steps, removing rRNA (sortmerna) and removing the main eukaryotic contamination (STAR). Most likely i'm doing something wrong, but somehow both these soft output the reads without my intervention.
I'll do some testing and update/close.
Thanks

**Comment by asl** [comment]
It's highly likely that the preprocessing software you're using is not paired-end aware. So, your left reads do not correspond to the right ones.

**Comment by Sebastien-Raguideau** [comment]
that's the worst.... thanks I'll check that shortly

**Comment by Sebastien-Raguideau** [comment]
Found the issue with my reads, it was totally on me, sorry for wasting your time and thanks for the help!
