### ISSUE TITLE
finished abnormally, OS return value: 4

### ISSUE THREAD

**Issue by taoyongac** [ablab/spades#595]
[params.txt](https://github.com/ablab/spades/files/5434214/params.txt)
[spades.log](https://github.com/ablab/spades/files/5434215/spades.log)

**Comment by asl** [comment]
It looks like your SPAdes installation is corrupted. Are you trying to run just ordinary SPAdes?

**Comment by taoyongac** [comment]
thanks so much for your quick reply, appreciate! Here is the script I running:
"unicycler -1 shAR4_R1_001.fastq.gz -2 shAR4_R2_001.fastq.gz -o output_dirsh_AR4 --keep 0 --mode conservative --no_pilon  --no_rotate“ 

I just uninstalled unicycler & SPAdes, then installed unicycler with conda. Then both unicycler  and SPAdes works.

**Comment by asl** [comment]
Glad it worked out!
