### ISSUE TITLE
spades error -6

### ISSUE THREAD

**Issue by zhanwen-cheng** [ablab/spades#596]
[params.txt](https://github.com/ablab/spades/files/5437321/params.txt)
[spades.log](https://github.com/ablab/spades/files/5437322/spades.log)
Hi, I was running spades 3.14.1 in HPC and it reported following error -6, could you help me check with that?
Thanks~

**Comment by asl** [comment]
Hello

Looks like one of SPAdes intermediate files was corrupted. This might indicate an I/O issue on your end, so I would contact your system administrator.

**Comment by zhanwen-cheng** [comment]
Hi, do you mean that I should contact my system administrator to check this I/O issue?

**Comment by asl** [comment]
Yes

**Comment by zhanwen-cheng** [comment]
Actually twa day ago I ran one pair-ends reads with spades and it succeeded.  little courious about why this I/O issue happened in hybrid assembing?

**Comment by asl** [comment]
Likely due to the way how the cluster runs the jobs, the load, etc.
