### ISSUE TITLE
Spdades finished abnormally

### ISSUE THREAD

**Issue by sajjadasaf** [ablab/spades#597]
I have tried spades many time but every time face same problem  could you check it.

[spades.log](https://github.com/ablab/spades/files/5443044/spades.log)

Error ==  system call for: "['/usr/lib/spades/bin/spades', '/media/SAJJAD/SPAdes-3.14.0-Linux/bin/spades_output/K33/configs/config.info', '/media/SAJJAD/SPAdes-3.14.0-Linux/bin/spades_output/K33/configs/careful_mode.info']" finished abnormally, err code: -6
log file is attached

**Comment by asl** [comment]
The log reads:

```
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t)'. In file '/build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/io/kmers/mmapped_reader.hpp' on line 99. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So, you're running out of RAM
