### ISSUE TITLE
SPAdes finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by yeroslaviz** [ablab/spades#599]
I know this was posted many times here,  but unfortunately I don't see ant possibility it is a RAM problem, as my server has 1Tb of RAM

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           1.0T        7.1G        234G        5.7G        765G        993G
Swap:            0B          0B          0B
```
Which are definitely not all in use at the time of running SPAdes. I hope the denovo assembly doesn't need more than that to run. Does it?

thanks
Assa

[params.txt](https://github.com/ablab/spades/files/5457438/params.txt)
[spades.log](https://github.com/ablab/spades/files/5457439/spades.log)

**Comment by asl** [comment]
You're quite right. Few notes though:

1. You're running SPAdes using memory limit of 250G
2. We cannot control the memory allocation. Essentially, we're just forwarding the memory allocation errors from your OS to you.

**Comment by yeroslaviz** [comment]
Thanks,
is it possible to increase the memory limit?

**Comment by asl** [comment]
Sure. Please refer to SPAdes manual (https://cab.spbu.ru/files/release3.14.1/manual.html#sec3.2) and `-m` option in particular.

**Comment by yeroslaviz** [comment]
ok, I have increased it now to 750Gb. hopefully this is enough.

```
spades.py -m 750 -t 16 -k 21,33,55,77 --careful --pe1-1 R1.fastq.gz --pe1-2 R2.fastq.gz -o WGS/SPAdes
```
