### ISSUE TITLE
SPAdes stop with many threads

### ISSUE THREAD

**Issue by miguelpmachado** [ablab/spades#6]
Hi,

I'm trying to run SPAdes with different number of threads (4, 8, 16, 32 and 64), but for 32 and 64 threads it stops abruptly. Is this expected?

This is my command:
`spades.py --careful --only-assembler --threads 32 --memory 25 --cov-cutoff off -k 55,77,99 -1 /home/msilva/campy_test/32_threads/ERR459548/ERR459548/trimmomatic/ERR459548_2P.fastq.gz -2 /home/msilva/campy_test/32_threads/ERR459548/ERR459548/trimmomatic/ERR459548_1P.fastq.gz -o /home/msilva/campy_test/32_threads/ERR459548/ERR459548/spades/`

In attachment you can find the STDOUT ([stdout.txt](https://github.com/ablab/spades/files/476412/stdout.txt)) and STDERR ([stderr.txt](https://github.com/ablab/spades/files/476411/stderr.txt)).

Thank you in advance.
Best regards,
Miguel

**Comment by asl** [comment]
It seem you're not having enough RAM:

> <jemalloc>: Error in malloc(): out of memory. Requested: 576704, active: 25547505664

Note that SPAdes requires ~ 500 Mb of RAM per threads at this stage, so what you're seeing is expected.
