### ISSUE TITLE
Isolate vs careful mode

### ISSUE THREAD

**Issue by giuferrero** [ablab/spades#600]
Hi,
I recently used Spades 3.14.1 for the assembly of a large number of staphylococcus aureus genomes from NCBI.
Despite, I run all the analyses using the isolate mode obtaining very good results. However, on a small subset of samples, this mode fails (N50 < 15000) while performing the analysis using the careful mode was able to improve, for some samples, the overall assembly.

My question is: despite the isolate mode is very fast, and generally very accurate, it is better to run directly the careful mode every time I plan to assemble a bacterial genome?

Thank you very much in advance,
Best regards,
Ferrero Giulio

**Comment by asl** [comment]
Dear Giulio,

Thank you for your interest in SPAdes. I clearly understand the wish of having "single recipe for genome assembly" that would always work. However, there is no silver bullet and there might be multiple reasons where isolate mode or careful mode would produce suboptimal results. 

You may want to study these cases more detailed as this might indicate some issues with the input data.

Please refer
https://currentprotocols.onlinelibrary.wiley.com/doi/epdf/10.1002/cpbi.102
or 
https://cab.spbu.ru/benchmarking-tools-for-de-novo-microbial-assembly/

for more details
