### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by talimc** [ablab/spades#604]
Hi,

I am at a loss here -- would really appreciate some advice.
I am trying to run SPAdes with paired-end reads from Illumina HiSeq (two libraries, sizes 300bp and 550bp). The expected coverage is 100X, and the expected genome size is approximately 300MB. I ran the assembler on 56 cores with a maximum 600Gb RAM. The reads have been trimmed with Trimmomatic, deduplicated with clumpify and unpaired reads merged. Despite that, I got an error related to memory (error 6). 
[params.txt](https://github.com/ablab/spades/files/5524795/params.txt)
[spades.log](https://github.com/ablab/spades/files/5524796/spades.log)

Previous to this error, I received error 9 which was suggested to have been fixed in version 3.14. However, our IT team at the university had problems installing version 3.14, so they installed 3.13. 

I would greatly appreciate any help on this matter. We don't have a larger server at our disposal; is there any solution to this issue?

Many thanks,

Tali

**Comment by asl** [comment]
Already answered via email: first step is to force your IT to upgrade to the latest SPAdes 3.14.1 which has better memory utilization.

Also, if your single reads are in fact merged ones, I would strongly suggest you to utilize merged read option for them
