### ISSUE TITLE
Error on SPAdes 3.14.1 (code -6; Assertion `data[i].count()' failed.)

### ISSUE THREAD

**Issue by mariasilviamorlino** [ablab/spades#606]
Hello,

I am using SPAdes for yeast sequence analyses and I am trying to incorporate it in a Snakemake pipeline. I get this error message during the execution of spades-hammer (see log for details):
spades-hammer: /opt/conda/conda-bld/spades_1596699678396/work/src/projects/hammer/kmer_data.cpp:388: void KMerDataCounter::FillKMerData(KMerData&): Assertion `data[i].count()' failed.
The weirdest thing is that I only get this error in some instances. If I try relaunching SPAdes, it sometimes performs the assembly successfully. I have tried to check out if there was anything that triggered the error, but I didn't have any success. It seems though that when I am launching the pipeline in a clean folder, it gets stuck in most cases. If necessary I can provide you with the pipeline and environments I am using. However, it would be extra useful for me right now to understand the meaning of this error message.

Thank you!

[spades.log](https://github.com/ablab/spades/files/5567711/spades.log)
[params.txt](https://github.com/ablab/spades/files/5567713/params.txt)

**Comment by asl** [comment]
One of SPAdes intermediate files got corrupted. Usually it's due to I/O issue on your end (and this is why it suddenly worked after rerun).
