### ISSUE TITLE
Skipping processing of scaffolds (empty file) SPADES

### ISSUE THREAD

**Issue by Keyth-ru** [ablab/spades#607]
Hi, all.
 
I'm trying assemble bacterial genome with SPADES, I'm using single library of pared-end sequences 3949727 bp total 

My line command is:
`spades.py -k 21,33,51,77,99,127 -t 4 -1 pared/R1pared.fastq.gz  -2 pared/R2pared.fastq.gz  --careful  -o SPADES`

My trying only use:
`spades.py -1 pared/R1pared.fastq.gz  -2 pared/R2pared.fastq.gz  --careful  -o  SPADES`

and even:
`spades.py -1 pared/R1pared.fastq.gz  -2 pared/R2pared.fastq.gz  -o SPADES`

but ever result with "Skipping processing of scaffolds (empty file)" and **without scaffolds.fasta file in output directory** 

So, Iḿ trying using a different software, a5 but the result is the same, **the scaffolds.fasta file it's not in the output directory**, even in despair I tried with platform online galaxy but the resulted was in error.

Please help me 
#

**Comment by asl** [comment]
Will you please attach your spades.log file?

**Comment by Keyth-ru** [comment]
> Will you please attach your spades.log file?

[spades.log](https://github.com/ablab/spades/files/5577334/spades.log)

Yes, tks

**Comment by asl** [comment]
The log reads (outlined in the end specially for you):
```
======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
...
 * 0:07:44.664   214M / 3G    WARN    General                 (pair_info_count.cpp       : 341)   Unable to estimate insert size for paired library #0
 * 0:07:44.664   214M / 3G    WARN    General                 (pair_info_count.cpp       : 347)   None of paired reads aligned properly. Please, check orientation of your read pairs.
 * 0:07:44.664   214M / 3G    WARN    General                 (repeat_resolving.cpp      :  63)   Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.
``

Hence no scaffolds. If you processed your reads somehow, then ensure whatever tool you're using is not screwing the pairedness of your reads.
