### ISSUE TITLE
Documentation --meta

### ISSUE THREAD

**Issue by jjkoehorst** [ablab/spades#609]
In the documentation it states that

```
--meta   (same as metaspades.py)     This flag is recommended when assembling metagenomic data sets (runs metaSPAdes, see paper for more details). Currently metaSPAdes **_supports only a single short-read library_** which has to be paired-end (we hope to remove this restriction soon). 
```

I am using the JSON file as an input for 2x paired-end datasets and it seems that both are processed correctly. Can I assume the documentation is not up to date and the restriction is removed?

**Comment by asl** [comment]
No, documentation is correct. Likely you're assembling your two datasets as a single library.
