### ISSUE TITLE
== Error ==  system call for: "['/home/wzq/spades/SPAdes-3.11.1-Linux/bin/hammer'

### ISSUE THREAD

**Issue by BurinkiWU** [ablab/spades#61]
The command line:  spades.py --careful -1 B31-max.clean.1.fq -2 B31-max.clean.2.fq -k 21,33,55,77 -o B31_max_output

The last result: 
== Error ==  system call for: "['/home/wzq/spades/SPAdes-3.11.1-Linux/bin/hammer', '/home/wzq/wzq_file/sample.data.from.xy/B31-max/B31_max_output/corrected/configs/config.info']" finished abnormally, err code: -6

How can I fix this problem?
Thank you, all.

**Comment by asl** [comment]
Hello

In order to fix the problem we need to understand what it was. Will you please attach your spades.log and params.txt files as you were instructed just two lines below the ones you posted?

**Comment by BurinkiWU** [comment]
The files are posted on this comment. 
Thanks for your help.
[params.txt](https://github.com/ablab/spades/files/1614790/params.txt)
[spades.log](https://github.com/ablab/spades/files/1614791/spades.log)

**Comment by asl** [comment]
The log reads

Message 'Pair of read files /home/wzq/wzq_file/sample.data.from.xy/B31-max/B31-max.clean.1.fq and /home/wzq/wzq_file/sample.data.from.xy/B31-max/B31-max.clean.2.fq contain unequal amount of reads'.

So, your input files are corrupted

**Comment by BurinkiWU** [comment]
Thx, bro!

**Comment by MichaelAngelou** [comment]
[spades_assemblyHamb89.txt](https://github.com/ablab/spades/files/1630753/spades_assemblyHamb89.txt)


Hello. Good day. Can I follow up on this thread? I am using SPAdes v. 3.10.1 through our university server and I am getting similar error.  I first thought that It was a memory error but after adjusting the memory from 100Gb to 250Gb I still receive the error.  May I ask if you can help me troubleshoot the problem. Attached here is the log and the .submit file. Thank you in advance.

== Error ==  system call for: "['/hpc/soft/spades/3.10.1/bin/hammer', '/home/users/mlnada/spades/spades_Hamb89assembly/corrected/configs/config.info']" finished abnormally, err code: -8

[spades.log](https://github.com/ablab/spades/files/1630751/spades.log)

**Comment by khizirl1** [comment]
I am getting the same error -6, 
[0x5f9c52]
[0x58ada1]
[0x55d191]
[0x408c19]
[0x40123c]
[0x87b11b]
[0x407c01]
Verification of expression 'cov_.size() > 10' failed in function 'void coverage_model::KMerCoverageModel::Fit()'. In file '/spades/assembler/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
Verification of expression 'cov_.size() > 10' failed in function 'void coverage_model::KMerCoverageModel::Fit()'. In file '/spades/assembler/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
spades-core: /spades/assembler/src/common/modules/coverage_model/kmer_coverage_model.cpp:187: void coverage_model::KMerCoverageModel::Fit(): Assertion `cov_.size() > 10' failed.


== Error ==  system call for: "['/opt/tcnjhpc/SPAdes-3.13.0-Linux/bin/spades-core', '/home/hpc/khizirl1/vamplificatum/vamplificatum_filt1.out/K21/configs/config.info', '/home/hpc/khizirl1/vamplificatum/vamplificatum_filt1.out/K21/configs/careful_mode.info']" finished abnormally, err code: -6



params.txt: 
Command line: /opt/tcnjhpc/SPAdes-3.13.0-Linux/bin/spades.py	--careful	-o	/home/hpc/khizirl1/vamplificatum/vamplificatum_filt1.out	-1	/projects/lonicera/ViburnumGenomes/vamp_aligned_R1.fq	-2	/projects/lonicera/ViburnumGenomes/vamp_aligned_R2.fq	

System information:
  SPAdes version: 3.13.0
  Python version: 2.7.5
  OS: Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core

Output dir: /home/hpc/khizirl1/vamplificatum/vamplificatum_filt1.out
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/projects/lonicera/ViburnumGenomes/vamp_aligned_R1.fq']
      right reads: ['/projects/lonicera/ViburnumGenomes/vamp_aligned_R2.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/hpc/khizirl1/vamplificatum/vamplificatum_filt1.out/tmp
  Threads: 16
  Memory limit (in Gb): 187

**Comment by asl** [comment]
@khizirl1 Please *do not* hijack old closed issues. You problem is completely different and is clearly outlined in the error message you posted:
```
'/spades/assembler/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
Verification of expression 'cov_.size() > 10'
```

**Comment by FengqingWang0712** [comment]
read files /home/fwang/test/output/10/clean1.fq and /home/fwang/test/output/20/clean2.fq contain unequal amount of reads


== Error ==  system call for: "['/home/fwang/downloads/SPAdes-3.13.0-Linux/bin/spades-hammer', '/home/fwang/downloads/SPAdes-3.13.0-Linux/bin/spades_assmebly_all_clean/corrected/configs/config.info']" finished abnormally, err code: 255

How can I fix it? Thanks!
[params.txt](https://github.com/ablab/spades/files/3902965/params.txt)
[spades.log](https://github.com/ablab/spades/files/3902966/spades.log)

**Comment by FengqingWang0712** [comment]
I've solved this problem. There is something wrong with the clean.fq I used. Thx all the same!

**Comment by Cheng-HJ** [comment]
Looking for your helpful advice. For error -9 : 
== Error ==  system call for: "['/opt/SPAdes-3.13.1-Linux/bin/spades-hammer', '/home/zhangyunhui/guozihua/metaspades/Mud_assembly/corrected/configs/config.info']" finished abnormally, err code: -9
Thanks a lot. 
[spades.log](https://github.com/ablab/spades/files/9952308/spades.log)
[params.txt](https://github.com/ablab/spades/files/9952309/params.txt)

**Comment by hafizmtalha** [comment]
== Error ==  system call for: "['/home/li/public2/nuomi/yes/share/spades-3.15.5/bin/spades-hammer', '/home/li/public2/nuomi/spades_output/corrected/configs/config.info']" finished abnormally, err code: -9

Im facing this issue. I have sufficient RAM and memory and have tried reisntalling spades as well. but still facing this issue
