### ISSUE TITLE
MetaSPAdes sorted error

### ISSUE THREAD

**Issue by alienzj** [ablab/spades#611]
Hi, spades team, I need help.

SPAdes version:
```SPAdes genome assembler v3.14.1```

[spades.log](https://github.com/ablab/spades/files/5599925/spades.log)

**Comment by asl** [comment]
One of SPAdes intermediate files got corrupted.

We saw many cases of this caused by I/O problems on the storage. So I would suggest moving SPAdes working directory to some other storage system or ask your system administrator whether there were any problems with the I/O.
