### ISSUE TITLE
Genome size is larger than reference genome

### ISSUE THREAD

**Issue by XMTian** [ablab/spades#612]
Hi,

I'm using SPAdes to de novo assemble bacteria genome. I found the genome assembled by SPAdes is always larger in size than reference genome. Could you explain why SPAdes will assemble more sequences?
I noticed that there are a lot of sequences shorter than 500bp, should I remove them?

Thanks in advance,
Xiaomeng

**Comment by asl** [comment]
SPAdes gives you what is in the input data. So, it will happily assemble contamination, host DNA, symbionts, plasmids, sequencing artefacts, etc.

It's up to you do decide what to do, whether you need any further filtering or not and how to do it.
