### ISSUE TITLE
out of memory, but how is this possible? finished abnormally, err code: -6

### ISSUE THREAD

**Issue by willnotburn** [ablab/spades#613]
Running metaspades on a dedicated workstation with 256Gb RAM. I capped the run at -m 250 using -t 46.

The error I get at the end of spades.log is `<jemalloc>: Error in malloc(): out of memory. Requested: 193469998488, active: 116727480320` Isn't 193469998488 is smaller than 250Gb?

Most importantly, what can I do to avoid this? Should I use fewer threads and/or is there another option?

[spades.log](https://github.com/ablab/spades/files/5613012/spades.log)
[params.txt](https://github.com/ablab/spades/files/5613013/params.txt)

**Comment by asl** [comment]
Hello

While 193469998488 is certainly less than 250 Gb, the sum (193469998488+116727480320) is not. `Active` = amount of memory used during the time of crash. And `Requested` is how much memory is needed more.

I would suggest you to wait for the next SPAdes 3.15 release

**Comment by willnotburn** [comment]
Uff. Yeah, I tried with half the threads and got the exact same error with identical memory numbers. What's the timeline for 3.15?

**Comment by asl** [comment]
Hopefully by the end of this year

**Comment by willnotburn** [comment]
Thanks, Anton! Last one: what will be different (just so I know how to use it)? Will it be an integrated optimization or an additional option?

**Comment by Rooksie** [comment]
I am running out of memory, 1.5TB on rnaSpades and metaSpades. Hopeful for an updated version!

**Comment by asl** [comment]
SPAdes 3.15 was released. Please reopen if this is still a problem
