### ISSUE TITLE
error when I run spades-core

### ISSUE THREAD

**Issue by yuanpingdu** [ablab/spades#614]
I have download SPAdes-3.14.0-Linux.tar.gz and  compress it , go to SPAdes-3.14.0-Linux/bin and run ./spades-core, then it output the next message :
Exception caught basic_string::_S_construct null not valid.

I have also run the order ./spades-ionhammer, the output is :
  0:00:00.000     8M / 8M    INFO    General                 (main.cpp                  : 294)   Starting IonHammer, built from refs/heads/spades_3.14.0, git revision c831f9be30a4364383cd4ebe5b78cdfcaad1acc9
  0:00:00.000     8M / 8M    INFO    General                 (main.cpp                  : 298)   Loading config from hammer-it.cfg

run ./spades-hammer,the output is :
  0:00:00.000     8M / 8M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.14.0, git revision c831f9be30a4364383cd4ebe5b78cdfcaad1acc9
  0:00:00.000     8M / 8M    INFO    General                 (main.cpp                  :  76)   Loading config from /home/snikolenko/algorithmic-biology/assembler/src/hammer/config.inp
Exception caught /home/snikolenko/algorithmic-biology/assembler/src/hammer/config.inp: cannot open file for reading

I want to kown what's the problem and how can I run it normally?

**Comment by asl** [comment]
The problem is that you seems have not read the manual. Please consider reading https://cab.spbu.ru/files/release3.14.1/manual.html#sec3 for instructions on running SPAdes.

Hope this will help.
