### ISSUE TITLE
hybrid-SPAdes out of memory error

### ISSUE THREAD

**Issue by drs** [ablab/spades#615]
Hi, 

I have an issue with a hybrid Nanopore + Illumina SPAdes assembly with SPAdes v3.14.1. The genome size is relatively small (~20Mb) and I allowed 350 Gb of RAM for SPAdes. I was monitoring the server resource usage and I don't believe that the RAM usage was that high at any point. The error message is : 

```
   0:18:55.979     5G / 31G   INFO   StatsCounter             (pacbio_read_structures.hpp: 163)   Median fraction of present seeds in maximal alignmnent among reads aligned to the graph: 0
  0:18:55.980     5G / 31G   INFO    General                 (hybrid_aligning.cpp       : 308)   Aligning of long reads finished
  0:18:56.015     4G / 31G   INFO   HybridAligning           (hybrid_aligning.cpp       : 375)   Padding gaps
  0:18:56.016     4G / 31G   INFO   HybridAligning           (hybrid_aligning.cpp       : 379)   Min gap weight set to 2
  0:18:56.034     4G / 31G   INFO    General                 (hybrid_aligning.cpp       : 146)   Closing gaps with long reads
<jemalloc>: Error in malloc(): out of memory
 Requested: 189236
```

[params.txt](https://github.com/ablab/spades/files/5638875/params.txt)
[spades.log](https://github.com/ablab/spades/files/5638876/spades.log)

Thank you
Samuel

**Comment by alienzj** [comment]
I also meet 'out of memory' many times.

**Comment by asl** [comment]
Please give the latest SPAdes 3.15.0 a try. Reopen if this is still an issue
