### ISSUE TITLE
System call for: "['~~~']" finished abnormally, OS return value: -8

### ISSUE THREAD

**Issue by boogsnaxx** [ablab/spades#616]
Using SPAdes-3.14.1 with the `--only-assembler` and `--careful` parameters.

[spades.log](https://github.com/ablab/spades/files/5647294/spades.log)
[params.txt](https://github.com/ablab/spades/files/5647296/params.txt)

**Comment by maesaar** [comment]
@boogsnaxx I was looking your spades log and saw the following warning I have also in my log (but my run still finishes correctly). Do you have any idea what this warning means:

`WARNING: Try to use logger before create one. Level=INFO. Message=Additional contigs is tmp_contigs.fasta`

**Comment by boogsnaxx** [comment]
Solved the problem myself.
I was using a modified example command with the parameter `-t 17` on a machine with only 4 cores. Changing it to `-t 9` fixed the issue.
