### ISSUE TITLE
err code: -6

### ISSUE THREAD

**Issue by FelipeMelis** [ablab/spades#617]
Hello,

I receive an error while I'm running metaspades.py
== Error ==  system call for: "['/opt/SPAdes-3.13.1-Linux/bin/spades-hammer', '/home/fmelis/LoValdivia/BI_spades/corrected/configs/config.info']" finished abnormally, err code: -6

Here is the file that is referenced, params.txt and spades.log

[spades.log](https://github.com/ablab/spades/files/5655408/spades.log)
[params.txt](https://github.com/ablab/spades/files/5655409/params.txt)
[config.info.txt](https://github.com/ablab/spades/files/5655402/config.info.txt)

**Comment by asl** [comment]
The log reads:
```
<jemalloc>: Error in malloc(): out of memory. Requested: 10157163984, active: 49899634688
```

So, you're running out of RAM

**Comment by FelipeMelis** [comment]
I'm using a cluster and I have to allocate the ram memory, how I can calculate how much I'm going to need?

**Comment by asl** [comment]
Unfortunately, there is no way to know before assembly: the memory requirements are not known in advance as they depend on many things including genome size, coverage, error rate, repeat content, ploidy, etc.
