### ISSUE TITLE
== Error ==  system call for: "['/hpc/soft/spades/3.10.1/bin/hammer', '/home/users/mlnada/spades/spades_Hamb89assembly/corrected/configs/config.info']" finished abnormally, err code: -8

### ISSUE THREAD

**Issue by MichaelAngelou** [ablab/spades#62]
[spades_assemblyHamb89.txt](https://github.com/ablab/spades/files/1630762/spades_assemblyHamb89.txt)
Hello Good day. I am Michael Angelou and  currently working on a microbial metagenomics dataset, paired-end (2 x 100) sequenced on Illumina Hiseq2000. I am new to shotgun metagenomics and hoping to learn along the way.   I am using SPAdes v. 3.10.1 through our university server. However, I keep getting the error below and I can't  seem to find the solution to fix this error. I first thought that It was a memory error but after adjusting the memory from 100Gb to 250Gb as suggested somewhere in this page,  I still receive the error.  May I ask if you can help me troubleshoot the problem. Thank you in advance. Attached here is the log file and params.txt 
[spades.log](https://github.com/ablab/spades/files/1630761/spades.log)
 

== Error ==  system call for: "['/hpc/soft/spades/3.10.1/bin/hammer', '/home/users/mlnada/spades/spades_Hamb89assembly/corrected/configs/config.info']" finished abnormally, err code: -8

**Comment by asl** [comment]
I already responded to you via the e-mail.

The log reads:

```
  0:00:02.924     7G / 7G    INFO   K-mer Splitting          (kmer_data.cpp             : 113)   Total 150 reads processed
  0:00:03.626   560M / 7G    INFO    General                 (kmer_index_builder.hpp    : 252)   Starting k-mer counting.
   0:00:03.952   560M / 7G    INFO    General                 (kmer_index_builder.hpp    : 258)   K-mer counting done. There are 0 kmers in total.

```
So, the dataset contains only 150 reads and all the k-mers there are singletons and therefore are filtered out. This certainly cannot be a metagenomic dataset.
