### ISSUE TITLE
input read in output scaffolds.fa? 

### ISSUE THREAD

**Issue by HweeSze** [ablab/spades#620]
Hi team,

thanks for developing such amazing tool!

I have got some metagenomics data that got assembled but I'm also keen to keep those short sequence from the scaffolds.fa. Just wondering is it possible that some input reads will somehow pass through the multiple de Bruijn graphs and output as contigs? 
For ex my read length is 250bp and the largest kmer is 127, is it possible to get a 250bp contig but is actually the reads?

Thanks!

**Comment by asl** [comment]
It's perfectly ok to have very fragmented metagenome assemble depending on the coverage, complexity and strain composition. The isolated read cannot go as output contig. You could check the assembly graph to see where these contigs are located.
