### ISSUE TITLE
spades.py --test              /bin/sh: 39: spades.py: Permission denied

### ISSUE THREAD

**Issue by DJFast** [ablab/spades#621]
Hi all, 

thanks for taking the time to view my post. Essentially, I am working on running metaspades. I have successfully installed the program and am trying to run the test script

#ls -l 
drwxrwxrwx   4 1010 1010     4096 May  1  2020 SPAdes-3.14.1-Linux
-rw-r--r--   1 root root 28378531 May  1  2020 SPAdes-3.14.1-Linux.tar.gz
lrwxrwxrwx   1 root root        7 Nov  6 01:21 bin -> usr/bin
drwxr-xr-x   2 root root     4096 Apr 15  2020 boot
drwxr-xr-x   5 root root      360 Dec 10 15:05 dev
drwxr-xr-x   1 root root     4096 Dec 10 20:27 etc
drwxr-xr-x   2 root root     4096 Apr 15  2020 home
lrwxrwxrwx   1 root root        7 Nov  6 01:21 lib -> usr/lib
lrwxrwxrwx   1 root root        9 Nov  6 01:21 lib32 -> usr/lib32
lrwxrwxrwx   1 root root        9 Nov  6 01:21 lib64 -> usr/lib64
lrwxrwxrwx   1 root root       10 Nov  6 01:21 libx32 -> usr/libx32
drwxr-xr-x   2 root root     4096 Nov  6 01:21 media
drwxr-xr-x   2 root root     4096 Nov  6 01:21 mnt
drwxr-xr-x   2 root root     4096 Dec 10 19:05 my_lab
drwxr-xr-x   2 root root     4096 Nov  6 01:21 opt
dr-xr-xr-x 275 root root        0 Dec 10 15:05 proc
drwx------   2 root root     4096 Nov  6 01:25 root
drwxr-xr-x   1 root root     4096 Nov 25 22:25 run
lrwxrwxrwx   1 root root        8 Nov  6 01:21 sbin -> usr/sbin
drwxr-xr-x   2 root root     4096 Nov  6 01:21 srv
dr-xr-xr-x  11 root root        0 Dec 10 15:06 sys
drwxrwxrwt   1 root root     4096 Dec 10 20:27 tmp
drwxr-xr-x   1 root root     4096 Nov  6 01:21 usr
drwxr-xr-x   1 root root     4096 Nov  6 01:25 var

#cd SPAdes-3.14.1-Linux
#cd bin
#ls -l 
total 66580
drwxr-xr-x 2 root root    4096 Dec 10 20:30 __pycache__
-rwxr-xr-x 1 1010 1010 3471520 Apr 23  2020 cds-mapping-stats
-rwxr-xr-x 1 1010 1010 3638624 Apr 23  2020 cds-subgraphs
-rwxr-xr-x 1 1010 1010 3708320 Apr 23  2020 mag-improve
lrwxrwxrwx 1 1010 1010       9 Apr 23  2020 metaspades.py -> spades.py
lrwxrwxrwx 1 1010 1010       9 Apr 23  2020 plasmidspades.py -> spades.py
lrwxrwxrwx 1 1010 1010       9 Apr 23  2020 rnaspades.py -> spades.py
-rwxr-xr-x 1 1010 1010 1279440 Apr 23  2020 spades-bwa
-rwxr-xr-x 1 1010 1010 3046320 Apr 23  2020 spades-convert-bin-to-fasta
-rwxr-xr-x 1 1010 1010 9970816 Apr 23  2020 spades-core
-rwxr-xr-x 1 1010 1010 3384176 Apr 23  2020 spades-corrector-core
-rwxr-xr-x 1 1010 1010 4098528 Apr 23  2020 spades-gbuilder
-rwxr-xr-x 1 1010 1010 5515872 Apr 23  2020 spades-gmapper
-rwxr-xr-x 1 1010 1010 3575360 Apr 23  2020 spades-gsimplifier
-rwxr-xr-x 1 1010 1010 3467904 Apr 23  2020 spades-hammer
-rwxr-xr-x 1 1010 1010 3969024 Apr 23  2020 spades-ionhammer
-rwxr-xr-x 1 1010 1010 3540848 Apr 23  2020 spades-kmer-estimating
-rwxr-xr-x 1 1010 1010 3326160 Apr 23  2020 spades-kmercount
-rwxr-xr-x 1 1010 1010 3757968 Apr 23  2020 spades-read-filter
-rwxr-xr-x 1 1010 1010 4503872 Apr 23  2020 spades-truseq-scfcorrection
-rwxrwxrwx 1 1010 1010   29569 Apr 20  2020 spades.py
-rw-r--r-- 1 1010 1010    1674 Dec 26  2019 spades_init.py
-rwxr-xr-x 1 1010 1010 3835552 Apr 23  2020 spaligner
-rwxr-xr-x 1 1010 1010    8911 Dec 26  2019 truspades.py

# spades.py --test
/bin/sh: 54: spades.py: Permission denied

As you can see, I have the correct permissions on the file, and python3 is installed 
#python3 --version
Python 3.8.5

If I appending the Python interpreter 
# python3 spades.py --test
Traceback (most recent call last):
  File "spades.py", line 40, in <module>
    from stages.pipeline import Pipeline
  File "/SPAdes-3.14.1-Linux/share/spades/spades_pipeline/stages/pipeline.py", line 12, in <module>
    from distutils import dir_util
ImportError: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)

I am all out of answers. Please any help here would be really appreciated. 
cheers

**Comment by asl** [comment]
Hello

> /bin/sh: 54: spades.py: Permission denied

This one is run via `/usr/bin/env python`. I'd suppose something is broken there on your system.

For some reason Debian / Ubuntu decided to separate out distutils. I would suggest you to run:
```
sudo apt install python3-distutils
```

**Comment by DJFast** [comment]
@asl 
Thanks very much for your reply. I ran the update you suggested. However, I still get the same error. But I think you might have something.
# apt install python3-distutils
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-distutils is already the newest version (3.8.5-1~20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# spades.py --test
/bin/sh: 8: spades.py: Permission denied 

When I go higher level 
# /SPAdes-3.14.1-Linux/bin/spades.py --test
/usr/bin/env: 'python': No such file or directory

So is this what you are saying? That the /usr/bin/env python is broken? thanks so much for you help so far, anything else would be so helpful.

**Comment by asl** [comment]
Something wrt python is broken on your system. I would suggest you to contact your system administrator.

**Comment by DJFast** [comment]
> 
> 
> Something wrt python is broken on your system. I would suggest you to contact your system administrator.

Unfortunately I am one individual without that luxury

**Comment by DJFast** [comment]
> 
> 
> Something wrt python is broken on your system. I would suggest you to contact your system administrator.

So in-case anyone comes across this issue, the solution is to build SPAdes from source code and compile it yourself. Its all in the instruction manual.
