### ISSUE TITLE
Error: system call for: "spades-hammer', 'assembly_spades/corrected/configs/config.info" finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by DOieGYuan** [ablab/spades#622]
Dear author,
       I ran spades 3.14.1 on Redhat 7.7 to assemble 300 GB pair-end reads using 192 cores and 2000 GB RAM. It got an error without the further information to address the problem.
      The process halt at ```K-mer Counting           (kmer_data.cpp             : 351)   Arranging kmers in hash map order``` and the error occurred.
      What's the potentials problem? Thank you for your time!
Yuan

**Comment by DOieGYuan** [comment]
> Please attach the files mentioned in the error message just two lines above the GitHub URL.
> 
> Thanks!

Thank you for your rapid reply! These two files are listed below
[params.txt](https://github.com/ablab/spades/files/5677597/params.txt)
[spades.log](https://github.com/ablab/spades/files/5677598/spades.log)

**Comment by asl** [comment]
Looks like you're running on 24-core machine. Why you're setting '-t 192'?

It looks like the file system on `/ssd` does not support memory mapped files.

**Comment by DOieGYuan** [comment]
> Looks like you're running on 24-core machine. Why you're setting '-t 192'?
> 
> It looks like the file system on `/ssd` does not support memory mapped files.

We ran this task with eight 24-core and 250GB-RAM nodes of a computer cluster using IBM Platform LSF

**Comment by asl** [comment]
> We ran this task with eight 24-core and 250GB-RAM nodes of a computer cluster using IBM Platform LSF

So, this explains everything: you're running out of RAM. SPAdes cannot utilize resources of multiple nodes, it requires a single machine to run on.
