### ISSUE TITLE
allow user to define order of kmer processing

### ISSUE THREAD

**Issue by nick-youngblut** [ablab/spades#623]
spades generally requires the most memory for higher kmers, so if a cluster job is going to die due to a lack of memory, it won't be until near the end of the assembly, which could take days. It would be helpful if the user could select the order in which kmer sizes are processed (eg., `-k 55 33 21`) in order to allow spades jobs to fail fast rather than needlessly using a lot of excess cluster resources.

**Comment by asl** [comment]
This is not possible as shorter k-mers are auxiliary and are used to supplement the longer one.
