### ISSUE TITLE
About err code: -11

### ISSUE THREAD

**Issue by zhang144999** [ablab/spades#627]
Dear developer
Running dipspades with this comand: 
`/home/wj/ZGP/SPAdes-3.12.0-Linux/bin/dipspades.py` --pe1-1 ./WQ03-jirou_1_clean.fq.gz --pe1-2 ./WQ03-jirou_2_clean.fq.gz \
 --pe1-s WQ03-jirou_1_unpaired.fq.gz --pe1-s WQ03-jirou_2_unpaired.fq.gz \
 -t 20 \
 -o `test_dipspades_gene`
The spades.log is show
`The` impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
The impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
The impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
The impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
The impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
The impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
The impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
The impossible happened : collision on 128 bit hashes... please switch to safe branch, and play the lottery.Another more likely explanation might be that you have duplicate keys in your input.                                        If so, you can ignore this message, but be aware that too many duplicate keys will increase ram usage
  2:33:02.216   540M / 11G   INFO    General                 (kmer_index_builder.hpp    : 150)   Merging final buckets.
  2:37:20.375   540M / 11G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 336)   Index built. Total 387671010 bytes occupied (3.7097 bits per kmer).
  2:37:21.233     1G / 11G   INFO   DeBruijnExtensionIndexBu (kmer_extension_index_build:  99)   Building k-mer extensions from k+1-mers
  2:38:14.222     1G / 11G   INFO   DeBruijnExtensionIndexBu (kmer_extension_index_build: 103)   Building k-mer extensions from k+1-mers finished.
  2:38:14.229     1G / 11G   INFO    General                 (stage.cpp                 : 101)   PROCEDURE == Condensing graph
  2:38:14.510     1G / 11G   INFO   UnbranchingPathExtractor (debruijn_graph_constructor: 355)   Extracting unbranching paths
  2:39:38.404     2G / 11G   INFO   UnbranchingPathExtractor (debruijn_graph_constructor: 374)   Extracting unbranching paths finished. 11448847 sequences extracted

== Error ==  system call for: "['/home/wj/ZGP/SPAdes-3.12.0-Linux/bin/spades-core', '/data/nfs/wj/zgp/genome/test_dipspades_gene/spades/K127/configs/config.info', '/data/nfs/wj/zgp/genome/test_dipspades_gene/spades/K127/configs/diploid_mode.info']" finished abnormally, err code: `-11`

The warning show:
`===` Error correction and assembling warnings:
 * 0:40:27.027    11G / 16G   WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:41:07.095    11G / 16G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 14
 * 0:41:07.099    11G / 16G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 14
 * 0:57:19.160     8G / 16G   WARN    General                 (simplification.cpp        : 479)   The determined erroneous connection coverage threshold may be determined improperly
 * 0:41:57.650     7G / 12G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 12
 * 0:41:57.653     7G / 12G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 12
 * 0:40:27.402     7G / 13G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 4
 * 0:40:27.405     7G / 13G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 4
 * 0:52:33.710     5G / 11G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 20
 * 0:52:33.712     5G / 11G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 20
 * 1:11:39.003     5G / 11G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 31
 * 1:11:39.006     5G / 11G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 31
======= Warnings saved to /data/nfs/wj/zgp/genome/test_dipspades_gene/spades/warnings.log

=== ERRORs:
 * system call for: "['/home/wj/ZGP/SPAdes-3.12.0-Linux/bin/spades-core', '/data/nfs/wj/zgp/genome/test_dipspades_gene/spades/K127/configs/config.info', '/data/nfs/wj/zgp/genome/test_dipspades_gene/spades/K127/configs/diploid_mode.info']" finished abnormally, err code: -11
 `
I dont't know what shouled I do.

**Comment by asl** [comment]
Hello

dipSPAdes is deprecated and no longer supported. I would suggest you to write to authors of dipSPAdes paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4449708/
