### ISSUE TITLE
WARNING: Try to use logger before create one. Level=INFO. Message=Additional contigs is tmp_contigs.fasta

### ISSUE THREAD

**Issue by maesaar** [ablab/spades#628]
@asl I am getting the following warning using `SPAdes version: 3.14.1` on Linux and also on Mac. Nevertheless, spades finishes fine. What does it mean and are the results still usable?

Thank you.

**Comment by asl** [comment]
The warning is benign

**Comment by maesaar** [comment]
Thank you for the prompt reply @asl!
