### ISSUE TITLE
metaplasmidspades.py and plasmidspades_plus.py missing in 3.14.1

### ISSUE THREAD

**Issue by diriano** [ablab/spades#629]
Hi,
these two scripts are missing in release 3.14.1, either from the linux binaries or from the tar.gz source code. However I can find them referenced in the manual and I see them in the github repo. But I am having problems compiling from the repo.
Any chance you can make a release that includes these two, and any dependencies?
Thanks,
Diego

**Comment by asl** [comment]
Tagging the author: @Dmitry-Antipov

**Comment by Dmitry-Antipov** [comment]
Hi.
Speaking on metaplasmidspades - yes, it's our bug, will fix it in upcoming release. In 3.14.1 you can use ./spades.py --meta --plasmid option combination - it is exact equivalent with ./metaplasmidspades.py

plasmidspades_plus is just a notation for combination of plasmidSPAdes + plasmidVerify. It is not referenced in spades manual and is not supported now. plasmidspades output can be checked with plasmidVerify (or more novel viralVerify) tools manually.

**Comment by dangchenyuan** [comment]
![image](https://user-images.githubusercontent.com/45260772/103969747-9701e380-51a1-11eb-9372-039bc613568e.png)
sorry to say it does not work when using these two modes simultaneously.

**Comment by Dmitry-Antipov** [comment]
That's look really strange. Since 3.14. this error message looks differently (see https://github.com/ablab/spades/blob/spades_3.14.1/assembler/src/spades_pipeline/options_parser.py#L979 ) Are you sure you are running spades 3.14.1 and not some earlier installed version? This can be checked with spades.py --version

**Comment by dangchenyuan** [comment]
@Dmitry-Antipov Thank you. It worked. I used the conda to install the spades, ans its version is 3.13. Now, I installed it manually.

**Comment by asl** [comment]
Both are part of SPAdes 3.15
