### ISSUE TITLE
error in spades

### ISSUE THREAD

**Issue by khani2000** [ablab/spades#63]
#hi. i run spades fo bacterial genome assembly and get error.i send log file. help me!!!!!

[spades.log](https://github.com/ablab/spades/files/1631596/spades.log)

**Comment by asl** [comment]
The log reads

```
In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So, you're running out of RAM

**Comment by khani2000** [comment]
My system RAM is 16 G and has 24 cpu. How do I assemble my data with my
system? What command? I tested some command and I have got such error

**Comment by asl** [comment]
Well, the required memory depends on the dataset in question. So, you'd need to free more RAM or to move to large machine.

**Comment by khani2000** [comment]
is error correcting different from trimming? input to spades is trimmed
data or raw data?
thanks

**Comment by asl** [comment]
> is error correcting different from trimming?
Yes

> input to spades is trimmed data or raw data?
In general - it should not matter provided that the trimming options are sane
