### ISSUE TITLE
Dynamic monitoring of memory usage

### ISSUE THREAD

**Issue by eecho-ohcee** [ablab/spades#632]
Hi, I'm curious about the memory usage while the program is running.How do I dynamically monitor memory usage while the spades.py program is running?Here is the log file I output.
Looking forward to your answers!
[spades.log](https://github.com/ablab/spades/files/5752866/spades.log)

**Comment by asl** [comment]
Hello

You could look into the log:
```
  0:36:18.709     5G / 19G   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 4096
```

This means that currently SPAdes is using approx 5Gb of RAM as requested from memory allocator. And 19 Gb was the highest value seen so far.
