### ISSUE TITLE
finished abnormally, err code: 1

### ISSUE THREAD

**Issue by FelipeMelis** [ablab/spades#633]
Hello,
I have this error, I was using 200 gb of ram and 50 cpu cores.

The program was terminated by segmentation fault
=== Stack Trace ===
[0x40a709]
[0x40a876]
[0x5b3230]
[0x491e5b]
[0x44046a]
[0x439bac]
[0x59a7be]
[0x5ab8d4]
[0x60b969]

== Error ==  system call for: "['/opt/SPAdes-3.13.1-Linux/bin/spades-hammer', '/home/fmelis/LoValdivia/LoVal2_spades/corrected/configs/config.info']" finished abnormally, err code: 1

The files:

[spades.log](https://github.com/ablab/spades/files/5755681/spades.log)
[params.txt](https://github.com/ablab/spades/files/5755682/params.txt)

Thanks in advance

**Comment by FelipeMelis** [comment]
Any help with this? I can't manage to run this samples.

Thanks in advance

**Comment by asl** [comment]
Will you please give SPAdes 3.15 a try?

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2

**Comment by FelipeMelis** [comment]
Sorry!!!
The problem was solved with SPAdes 3.15.2

Thanks!!!

**Comment by demolnau** [comment]
does SPAdes 3.15.2 have dipspades in there or am I blind?

**Comment by andrewprzh** [comment]
> does SPAdes 3.15.2 have dipspades in there or am I blind?

No, dipSPAdes is deprecated and was removed in 3.13.
