### ISSUE TITLE
Error 255 - Failed to determine read length for library #0. with single library

### ISSUE THREAD

**Issue by Chrislipop** [ablab/spades#634]
Hi,

I am not sure how to fix this issue considering there is only one library and for some reasons it automatically starts with library #0. Sequence downloaded from NCBI

Command line input: metaspades.py -k 33,55,77,89 --phred-offset 33 --only-assembler --merged SRR10481892.fastq -o spades_NA_S92_test/ 

[spades.log](https://github.com/ablab/spades/files/5759652/spades.log)
[params.txt](https://github.com/ablab/spades/files/5759653/params.txt)

[input_dataset.yaml.txt](https://github.com/ablab/spades/files/5759654/input_dataset.yaml.txt)

**Comment by asl** [comment]
Per SPAdes manual – you'd also need to provide original (unmerged) paired-end reads.

Also, I would suggest you to upgrade to the latest SPAdes 3.14.1
