### ISSUE TITLE
Openmp parallel analysis for metaspades

### ISSUE THREAD

**Issue by eecho-ohcee** [ablab/spades#635]
Hello,
I'm now trying to use scalasca tools(https://www.scalasca.org) to analyze the spades during the metagenomic assmble process . I learned earlier that the spades program only supports Openmp parallel. I,please,want to know what part of your program involves Openmp parallel? And I want to independently test the performance of each parallel program, so how do I get the input data that makes the program work properly? Thank you.
Looking forward to your reply.

**Comment by asl** [comment]
Hello

Many parts of SPAdes uses OpenMP. You could easily check the source code for the possible places. As SPAdes is a long and complex process you cannot execute a single parallel region simply. As for the test data - there are lots of input data around, so you could chose the one that suits your needs.

Hope this helps.
