### ISSUE TITLE
Question: yaml PE left and right reads?

### ISSUE THREAD

**Issue by maesaar** [ablab/spades#636]
@asl quick question am I correct that in the yaml file the PE right reads corresponds to Illumina R1s and left reads Illumina R2s?

Thank you

**Comment by asl** [comment]
Quite the opposite!

Please refer to the SPAdes manual for the description: https://cab.spbu.ru/files/release3.14.1/manual.html#sec3.1

```
By default, SPAdes assumes that paired-end and high-quality mate-pair reads have forward-reverse (fr) orientation and usual mate-pairs have reverse-forward (rf) orientation. However, different orientations can be set for any library by using SPAdes options.

To distinguish reads in pairs we refer to them as left and right reads. For forward-reverse orientation, the forward reads correspond to the left reads and the reverse reads, to the right. Similarly, in reverse-forward orientation left and right reads correspond to reverse and forward reads, respectively, etc.
```

**Comment by maesaar** [comment]
1) Just to be sure for example if I have following **reads** that have been **trimmed with trimmomatic**:

```
a) CAMP01-08H_S34_L001_R1_paired.fastq.gz
b) CAMP01-08H_S34_L001_R2_paired.fastq.gz
```

The spades command would be:
`spades.py -1 CAMP01-08H_S34_L001_R1_paired.fastq.gz -2 CAMP01-08H_S34_L001_R2_paired.fastq.gz --sc	--threads 8 --memory 58 -o CAMP01-08H_S34	-k 31,51,71,91,111`

2) When using yaml file with **reads** that have been **trimmed with trimmomatic**:

```
a) CAMP01-08H_S34_L001_R1_paired.fastq.gz
b) CAMP01-08H_S34_L002_R1_paired.fastq.gz
c) CAMP01-08H_S34_L003_R1_paired.fastq.gz
d) CAMP01-08H_S34_L004_R1_paired.fastq.gz
e) CAMP01-08H_S34_L001_R2_paired.fastq.gz
f) CAMP01-08H_S34_L002_R2_paired.fastq.gz
g) CAMP01-08H_S34_L003_R2_paired.fastq.gz
h) CAMP01-08H_S34_L004_R2_paired.fastq.gz
```

The yaml file (CAMP01-08H_S34.yaml) should be constructed as follows:

```
[
      {
        orientation: "fr",
        type: "paired-end",
        right reads: [
"CAMP01-08H_S34_L001_R2_paired.fastq.gz",
"CAMP01-08H_S34_L002_R2_paired.fastq.gz",
"CAMP01-08H_S34_L003_R2_paired.fastq.gz",
"CAMP01-08H_S34_L004_R2_paired.fastq.gz",
       ],
       left reads: [
"CAMP01-08H_S34_L001_R1_paired.fastq.gz",
"CAMP01-08H_S34_L002_R1_paired.fastq.gz",
"CAMP01-08H_S34_L003_R1_paired.fastq.gz",
"CAMP01-08H_S34_L004_R1_paired.fastq.gz",
       ]
     }
   ]
```

The spades command would be:
`spades.py --dataset CAMP01-08H_S34.yaml --sc --threads 8 --memory 58 -o CAMP01-08H_S34 -k 31,51,71,91,111`


@asl Am I now correct and what are the potential consequences when right reads and left reads in yaml file has been switched?

Thank you for prompt answer

**Comment by asl** [comment]
This is called "paired-end reads orientation". And you could found lots of resources dedicated to this starting from basic courses of Illumina sequences and assembly. For example: https://www.cureffi.org/2012/12/19/forward-and-reverse-reads-in-paired-end-sequencing/ and https://www.illumina.com/content/dam/illumina-marketing/documents/products/illumina_sequencing_introduction.pdf

Obviously an assembler will not be able to use paired-end information if the orientation is wrong / unknown / screwed.
