### ISSUE TITLE
Question regarding parameters: --dataset and --pe-1 <#> --pe-2 <#>?

### ISSUE THREAD

**Issue by nbawe** [ablab/spades#638]
Is parameter `--dataset test.yaml` equal to `--pe-1 1 lib_pe1_left_1.fastq --pe-2 1 lib_pe1_right_1.fastq --pe-1 2 lib_pe1_left_2.fastq --pe-2 2 lib_pe1_right_2.fastq` ?

Test yaml example from spades manual:
```
[
      {
        orientation: "fr",
        type: "paired-end",
        right reads: [
          "lib_pe1_right_1.fastq",
          "lib_pe1_right_2.fastq" 
        ],
        left reads: [
          "lib_pe1_left_1.fastq",
          "lib_pe1_left_2.fastq" 
        ]
      }
]
```

**Comment by asl** [comment]
No. Your YAML file contains only 1 library while your cmdline contains 2

**Comment by nbawe** [comment]
Thanks @asl I have no idea how I missed that

**Comment by nbawe** [comment]
@asl But is there possibility to use four files from same library separately in command line like —pe or other parameter without yaml file and dataset parameter?

**Comment by asl** [comment]
Sure

**Comment by nbawe** [comment]
Could you please give an example for four and eight files?

**Comment by nbawe** [comment]
@asl I think i figured it out is this correct just changed the `<#>` always to `1` in `--pe-1 <#>` and `--pe-2 <#>`:

`--pe-1 1 lib_pe1_left_1.fastq --pe-2 1 lib_pe1_right_1.fastq --pe-1 1 lib_pe1_left_2.fastq --pe-2 1 lib_pe1_right_2.fastq`

**Comment by nbawe** [comment]
Yes issue #22 confirms this is correct
