### ISSUE TITLE
Error in mmapped_reader.hpp during k-mer counting

### ISSUE THREAD

**Issue by Alexey-Kovtun** [ablab/spades#640]
Hi!

Sorry, if I accidentially repeat the already solved problem - just couldn't find anything relative.  I'm facing the following problem. I'm runnig a hybrid assembly with nanopore reads. The command is:

/home/a.kovtun/spades/bin/spades.py -k 21,33,55,77,99,127 --only-assembler -1 Acer_illumina_paired_R1.fastq.gz -2 Acer_illumina_paired_R2.fastq.gz --nanopore A_neg_DNA_MSU__with_average_quality_at_least_7__adapters_trimmed.fastq.gz -o Assembly_spades -t 16 -m 300

First two portions of k-mers have assembled without any problems, but on the 3rd one I recieved the following error after "k-mer counting" process started (giving the log for this k-mer below). Could you, please, help me understand, what could be the problem? Thanks in advance!

===== K77 started. 

== Running: /home/a.kovtun/spades/bin/spades-core /gss/a.kovtun/_Acer_genome_/Illumina_reads/Assembly_spades/K77/configs/config.info /gss/a.kovtun/_Acer_genome_/Illumina_reads/Assembly_spades/K77/configs/careful_mode.info

WARNING: Try to use logger before create one. Level=INFO. Message=Additional contigs is /gss/a.kovtun/_Acer_genome_/Illumina_reads/Assembly_spades/K55/simplified_contigs
  0:00:00.000     5M / 11M   INFO    General                 (main.cpp                  :  75)   Loaded config from /gss/a.kovtun/_Acer_genome_/Illumina_reads/Assembly_spades/K77/configs/config.info
  0:00:00.000     5M / 11M   INFO    General                 (main.cpp                  :  75)   Loaded config from /gss/a.kovtun/_Acer_genome_/Illumina_reads/Assembly_spades/K77/configs/careful_mode.info
  0:00:00.000     5M / 11M   INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 300 Gb
  0:00:00.000     5M / 11M   INFO    General                 (main.cpp                  :  85)   Starting SPAdes, built from refs/heads/spades_3.14.1, git revision 0ace7b8b2f948f633d73db4a506c2d19303265ef
  0:00:00.000     5M / 11M   INFO    General                 (main.cpp                  :  86)   Maximum k-mer length: 128
  0:00:00.000     5M / 11M   INFO    General                 (main.cpp                  :  87)   Assembling dataset (/gss/a.kovtun/_Acer_genome_/Illumina_reads/Assembly_spades/dataset.info) with K=77
  0:00:00.000     5M / 11M   INFO    General                 (main.cpp                  :  88)   Maximum # of threads to use (adjusted due to OMP capabilities): 16
  0:00:00.000     5M / 11M   INFO    General                 (pipeline.cpp              : 194)   SPAdes started
  0:00:00.000     5M / 11M   INFO    General                 (pipeline.cpp              : 201)   Starting from stage: read_conversion
  0:00:00.000     5M / 11M   INFO    General                 (pipeline.cpp              : 207)   Two-step RR enabled: 0
  0:00:00.000     5M / 11M   INFO    General                 (pipeline.cpp              : 218)   Will need read mapping, kmer mapper will be attached
  0:00:00.000     5M / 11M   INFO   StageManager             (stage.cpp                 : 166)   STAGE == Binary Read Conversion
  0:00:00.025     5M / 11M   INFO    General                 (read_converter.cpp        :  53)   Binary reads detected
  0:00:00.025     5M / 11M   INFO    General                 (read_converter.cpp        :  53)   Binary reads detected
  0:00:00.025     5M / 11M   INFO   StageManager             (stage.cpp                 : 166)   STAGE == de Bruijn graph construction
  0:00:00.025     5M / 11M   INFO    General                 (construction.cpp          : 115)   Contigs from previous K will be used: /gss/a.kovtun/_Acer_genome_/Illumina_reads/Assembly_spades/K55/simplified_contigs
  0:00:00.035     6M / 11M   INFO    General                 (construction.cpp          : 150)   Max read length 238
  0:00:00.035     6M / 11M   INFO    General                 (construction.cpp          : 156)   Average read length 220.522
  0:00:00.035     6M / 11M   INFO    General                 (stage.cpp                 : 113)   PROCEDURE == k+1-mer counting
  0:00:00.036     6M / 11M   INFO    General                 (kmer_index_builder.hpp    : 117)   Splitting kmer instances into 256 files using 16 threads. This might take a while.
  0:00:00.036     6M / 11M   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 32768
  0:00:00.036     6M / 11M   INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 6.24998 Gb
  0:00:00.036     6M / 11M   INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 87381
  0:00:09.833    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 4853957 reads
  0:00:34.474    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 9718247 reads
  0:00:59.128    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 14597021 reads
  0:01:23.781    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 19494592 reads
  0:01:49.832    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 24398257 reads
  0:02:14.340    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 29340075 reads
  0:02:39.408    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 34314698 reads
  0:03:06.089    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 39368076 reads
  0:03:31.538    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 44363808 reads
  0:03:58.258    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 49314371 reads
  0:04:23.398    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 54327899 reads
  0:05:36.742    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 69224506 reads
  0:11:10.981    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 137191231 reads
  0:22:44.030    11G / 11G   INFO    General                 (kmer_splitters.hpp        : 287)   Processed 273146660 reads
  0:42:50.967   223M / 9G    INFO    General                 (kmer_splitters.hpp        : 293)   Used 513694828 reads
  0:42:50.968   223M / 9G    INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  0:49:26.731   573M / 29G   ERROR   General                 (mmapped_reader.hpp        :  81)   unlink(2) failed. Reason: No such file or directory. Error code: 2

**Comment by asl** [comment]
Please attach the files mentioned in the error message. Thanks!

**Comment by Alexey-Kovtun** [comment]
Sorry, dropped out of for some time. Found the issue. It was about two running conflicting processes on server, gave the same output folder to them both. My bad. Issue closed.
