### ISSUE TITLE
metaspades: finished abnormally, err code: -6

### ISSUE THREAD

**Issue by hfehlnerpeach** [ablab/spades#641]
While running metaspades assembly, I got the error "== Error ==  system call for: [...] finished abnormally, err code: -6" during the K55 assembly step.
I tried running the --continue option with 1000G memory, but I still got the same error. Any idea how to solve this problem? Logs and parameter files attached.
Thanks! 
[params_continue_1000G.txt](https://github.com/ablab/spades/files/5803176/params_continue_1000G.txt)
[spades_100G.log](https://github.com/ablab/spades/files/5803177/spades_100G.log)
[spades_continue_1000G.log](https://github.com/ablab/spades/files/5803179/spades_continue_1000G.log)

**Comment by asl** [comment]
Does the problem reproduce with the latest SPAdes 3.14.1? Do you really have 1000G of free RAM available?

It looks like as some of SPAdes intermediate files got corrupted. Does it still fail if rerun from scratch (you could use `--only-assembler` and take the corrected reads as input to save quite some time)

**Comment by asl** [comment]
Please reopen if this is still an issue
