### ISSUE TITLE
release process question

### ISSUE THREAD

**Issue by chenrui333** [ablab/spades#642]
👋  it looks like the release artifact got uploaded into [here](https://cab.spbu.ru/files/release3.15.0/), but the gitub release is still with the old release? 

In that sense, not sure what would be the source of truth in terms of checking the latest release.

Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/68970

**Comment by asl** [comment]
Please do not hurry. Release is not instantaneous, so it could take some time

**Comment by chenrui333** [comment]
@asl thanks for confirming, where is the place to check the release news? Thanks!

**Comment by asl** [comment]
Typically here: https://twitter.com/spadesassembler
