### ISSUE TITLE
What is the easiest way to rename the graph.

### ISSUE THREAD

**Issue by SilasK** [ablab/spades#643]
Hey Spades Team, I wonder if there is a simple way to rename the assembly graph. What I did until now is just to rename the contigs from `Node_2...` to something like `Sample_1`  but then they are out of synch with the graph. Do you know if there is a simpler way or do you need the contigs names to be so complicated and comprehensive?

**Comment by asl** [comment]
Hello

Well, contig names encode various important information including length and the coverage. What is the problem with them? I guess you could always "trim" the suffix and end with "NODE_N"? Both for FASTA files and GFA.

**Comment by SilasK** [comment]
I know they contain various information of Coverage… As the names of the contigs are used in many places, e.g. a common standard is to use containname_geneNR as naming scheme for genes. I also have different samples assembled separately. So the Node_X wouldn’t be unique.

I think the easiest is to rename as I do but keep the mapping of the renaming. Thank you for your time.

**Comment by asl** [comment]
Well, I do not know which "common standard" you're talking about as contig does not correspond neither to gene, nor to sample. The standard to contig names is quite old starting from Velvet and adopted by many assemblers so far :) But certainly depending on the tasks you'd need to organize your contigs somehow
