### ISSUE TITLE
Error code on HPC

### ISSUE THREAD

**Issue by stephenqub** [ablab/spades#644]
Hi,

Can you please advise on the error from the following log:

Command line: /users/3054016/.conda/envs/spades/bin/metaspades.py	-1	/users/3054016/spades_test/S7R1.fastq.gz	-2	/users/3054016/spades_test/S7R2.fastq.gz	-o	/users/3054016/spades_test/S7_out	

System information:
  SPAdes version: 3.13.1
  Python version: 3.9.1
  OS: Linux-3.10.0-1127.10.1.el7.x86_64-x86_64-with-glibc2.17

Output dir: /users/3054016/spades_test/S7_out
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/users/3054016/spades_test/S7R1.fastq.gz']
      right reads: ['/users/3054016/spades_test/S7R2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /users/3054016/spades_test/S7_out/tmp
  Threads: 16
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /users/3054016/spades_test/S7_out/spades.log

===== Read error correction started. 

== Running read error correction tool: /users/3054016/.conda/envs/spades/share/spades-3.13.1-0/bin/spades-hammer /users/3054016/spades_test/S7_out/corrected/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.13.1, git revision 9a9d54db2ff9abaac718155bf74c12ec9464e8ca
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from /users/3054016/spades_test/S7_out/corrected/configs/config.info
  0:00:00.004     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 1
  0:00:00.004     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 250 Gb
  0:00:00.004     4M / 4M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.079     4M / 4M    INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.079     4M / 4M    INFO    General                 (hammer_tools.cpp          :  36)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.079     4M / 4M    INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.079     4M / 4M    INFO   K-mer Counting           (kmer_data.cpp             : 280)   Estimating k-mer count
  0:00:00.086    20M / 20M   INFO   K-mer Counting           (kmer_data.cpp             : 285)   Processing /users/3054016/spades_test/S7R1.fastq.gz
  0:12:46.025    20M / 20M   INFO   K-mer Counting           (kmer_data.cpp             : 294)   Processed 30692106 reads
  0:12:46.025    20M / 20M   INFO   K-mer Counting           (kmer_data.cpp             : 285)   Processing /users/3054016/spades_test/S7R2.fastq.gz
  0:25:25.232    20M / 20M   INFO   K-mer Counting           (kmer_data.cpp             : 294)   Processed 61384212 reads
  0:25:25.232    20M / 20M   INFO   K-mer Counting           (kmer_data.cpp             : 299)   Total 61384212 reads processed
  0:25:25.485    20M / 20M   INFO   K-mer Counting           (kmer_data.cpp             : 306)   Estimated 2392213493 distinct kmers
  0:25:25.488     4M / 20M   INFO   K-mer Counting           (kmer_data.cpp             : 311)   Filtering singleton k-mers
41 8 0
nslots: 8589934592
bits per slot: 8 range: 0000020000000000
  0:25:25.488    10G / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /users/3054016/spades_test/S7R1.fastq.gz
  1:09:18.685    10G / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 326)   Processed 30692106 reads
  1:09:18.685    10G / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /users/3054016/spades_test/S7R2.fastq.gz
  1:54:49.740    10G / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 326)   Processed 61384212 reads
  1:54:49.740    10G / 10G   INFO   K-mer Counting           (kmer_data.cpp             : 331)   Total 61384212 reads processed
Exception caught Cannot create temporary dir /users/3054016/spades_test/S7_out/tmp/hammer_xuj760u0/kmer_splitter_XXXXXX

== Error ==  system call for: "['/users/3054016/.conda/envs/spades/share/spades-3.13.1-0/bin/spades-hammer', '/users/3054016/spades_test/S7_out/corrected/configs/config.info']" finished abnormally, err code: 4

Thanks very much,

Stephen

**Comment by asl** [comment]
Hello

So, the log reads:
```
Exception caught Cannot create temporary dir /users/3054016/spades_test/S7_out/tmp/hammer_xuj760u0/
```

Please make sure the directory is writable, you are not overshooting your disk quota, etc.
