### ISSUE TITLE
Is the spades 3.15 incompatible with Ubuntu 20.04?

### ISSUE THREAD

**Issue by musa90** [ablab/spades#645]
I'm trying to use spades on Ubuntu 20.04.
I tried to use official binaries (3.14.1 and 3.15.0). To check if it works fine I used --test command and resulted log is:

[spades.log](https://github.com/ablab/spades/files/5818949/spades.log)
also compiling from source code results to same log.

as the manual points the final log should be : 

**_===== Assembling finished. Used k-mer sizes: 21, 33, 55

 * Corrected reads are in spades_test/corrected/
 * Assembled contigs are in spades_test/contigs.fasta
 * Assembled scaffolds are in spades_test/scaffolds.fasta
 * Assembly graph is in spades_test/assembly_graph.fastg
 * Assembly graph in GFA format is in spades_test/assembly_graph_with_scaffolds.gfa
 * Paths in the assembly graph corresponding to the contigs are in spades_test/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in spades_test/scaffolds.paths

======= SPAdes pipeline finished.

========= TEST PASSED CORRECTLY.

SPAdes log can be found here: spades_test/spades.log

Thank you for using SPAdes!_**

In another try I uses bioconda to install Spades using ""conda install spades" code, confusingly it only install version 3.13.0.
Also I tried to install with this code "sudo apt install spades" and installed version was 3.13.0.

--test command with 3.13.0 version results to expected log as manual indicates:

 ===== Assembling finished. Used k-mer sizes: 21, 33, 55 

 * Corrected reads are in /home/biox/spades_test/corrected/
 * Assembled contigs are in /home/biox/spades_test/contigs.fasta
 * Assembled scaffolds are in /home/biox/spades_test/scaffolds.fasta
 * Paths in the assembly graph corresponding to the contigs are in /home/biox/spades_test/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in /home/biox/spades_test/scaffolds.paths
 * Assembly graph is in /home/biox/spades_test/assembly_graph.fastg
 * Assembly graph in GFA format is in /home/biox/spades_test/assembly_graph_with_scaffolds.gfa

======= SPAdes pipeline finished.

========= TEST PASSED CORRECTLY.

SPAdes log can be found here: /home/biox/spades_test/spades.log

Thank you for using SPAdes!

is there a incompatibility with versions of 3.14.1 and 3.15.0 on Ubuntu 20.04?
How can I fix the problem? @asl

**Comment by asl** [comment]
I don't see any incompatibility in the log.
