### ISSUE TITLE
Permissions errors

### ISSUE THREAD

**Issue by Tahausix** [ablab/spades#650]
Hi,

I am having trouble with SPAdes 3.14.1 causing cyclical errors.
I get open(2) failed. Reason Operation not permitted. Error code 1.
Additionally to these is also get OS return value: -6 and 255 interchangablely

I have checked the fastq input files and these are the same length for pe1-1 and pe1-2 but not for pe1-s files. 

Is there anything i could do to narrow down the error?

Cheers

**Comment by asl** [comment]
Well, at least you could provide the files mentioned in the error message, could you?

**Comment by Tahausix** [comment]
[spades - error1.log](https://github.com/ablab/spades/files/5875792/spades.-.error1.log)
Hi,

Sorry, this is the most recent error code, i will attempt to generate the others, but they rewrote as i attempted to troubleshoot the issue.

**Comment by asl** [comment]
So, the log reads:
```
  0:00:06.539   736M / 3G    ERROR   General                 (mmapped_reader.hpp        :  42)   open(2) failed. Reason: Operation not permitted. Error code: 1. File: /home/pmr3lab/Pipeline/ToDoo/trim/X527_S20/tmp/spades_qj0dtvjy/construction_v4LGPw/kmers_raw_wKOfUz.915
```

This is likely an I/O error on your storage. I would suggest you to contact your system administrator. SPAdes was unable to open a temporary file for writing. You may also want to check various quotas, if any, etc.

**Comment by Tahausix** [comment]
cool thank you
