### ISSUE TITLE
"extenders" bug 3.15.0 -metaviral

### ISSUE THREAD

**Issue by runphaster** [ablab/spades#651]
spades-core: /spades/assembler/src/common/modules/path_extend/paired_library.hpp:124: double path_extend::PairedInfoLibraryWithIndex<Index>::CountPairedInfo(path_extend::EdgeId, path_extend::EdgeId, int, bool) const [with Index = const omnigraph::de::PairedIndex<debruijn_graph::DeBruijnGraph, omnigraph::de::PointTraits, omnigraph::de::safe_btree_map>&; path_extend::EdgeId = omnigraph::impl::EdgeId]: Assertion `index_.size() != 0' failed.

== Error ==  system call for: "['/global/u2/n/nolan/SPAdes-3.15.0-Linux/bin/spades-core', '/global/cscratch1/sd/nolan/SVG/SRX4676096/bfc.1K25B32.SRX4676096_v3.15.0/K123/configs/config.info', '/global/cscratch1/sd/nolan/SVG/SRX4676096/bfc.1K25B32.SRX4676096_v3.15.0/K123/configs/mda_mode.info', '/global/cscratch1/sd/nolan/SVG/SRX4676096/bfc.1K25B32.SRX4676096_v3.15.0/K123/configs/meta_mode.info', '/global/cscratch1/sd/nolan/SVG/SRX4676096/bfc.1K25B32.SRX4676096_v3.15.0/K123/configs/plasmid_mode.info', '/global/cscratch1/sd/nolan/SVG/SRX4676096/bfc.1K25B32.SRX4676096_v3.15.0/K123/configs/metaviral_mode.info']" finished abnormally, OS return value: -6

I've never done the attaching files thing... Doesn't look like my drag drop attempt worked

R1.1K25B32.SRX4676096.fasta.gz  R2.1K25B32.SRX4676096.fasta.gz spades.log

**Comment by runphaster** [comment]
[spades.log](https://github.com/ablab/spades/files/5870981/spades.log)



oh well, thought I could get you the input files somehow

**Comment by asl** [comment]
Please reopen when you will have something to attach
