### ISSUE TITLE
Relating to raw reads for transcriptome assembly

### ISSUE THREAD

**Issue by IamAbhishek22** [ablab/spades#652]
In my assembly, I have merged to different raw read sets, one with read length 75bp and other with read length 150 bp into one file (left read file, with merged 75bp and 150 bp raw read sets and right read file similarly, as it is paired end sequenced). Then, I used the merged file for denovo assembly. But, I had following questions:
1 - Will this assembly give me erroneous result?
2 - Will the read length considered for assembly will be about 75 bp, as that is the read length of one set of raw reads in the combined raw read file?
3 - Should I assemble the two raw read sets separately, and then create a single assembled transcriptome using CD-HIT or the assembly together will be enough? 

I am really confused about this. I will thankful for your response

**Comment by asl** [comment]
Tagging @andrewprzh

**Comment by andrewprzh** [comment]
Sorry, somehow missed this issue even after being tagged - my bad.

1. In general - no, but I'd use the as a separate input files .
2. SPAdes uses average and maximum read lengths to define k-mer sizes and various cut-offs. That why I'd suggest to provide them as 2 separate libraries.
3. Can be an option, but would try using SPAdes alone first.

Again, sorry for missing the issue. Please re-open if you still have any questions.
