### ISSUE TITLE
select minimum coverage for pathracer output?

### ISSUE THREAD

**Issue by pawlowac** [ablab/spades#654]
Hi,

Pathracer is working fantastic for assembling full length rRNA sequences, but I am having an issue of it working too well and assembling intact contaminating sequences. Is there any way to either directly edit the GFA file to remove all contigs less than a given cutoff or tell pathracer to ignore contigs with low coverage?

Thank you,
Andrew

**Comment by asl** [comment]
Oh, be very careful with rRNA, as you might end with mosaic alignments easily :)

The thing is: Pathracer does not use any contigs. It uses the assembly graph. So, if you mean "remove all low-covered edges", then yes, it is possible. You'd either edit graph removing all low-covered edges (using "DP" or "KC" tags).

Alternatively, you could use SPAdes' `--cov-cutoff` option - what it does is essentially what you'd want - it removes all edges from the assembly graph under the given threshold.

**Comment by pawlowac** [comment]
Thanks! I had assumed that `--cov-cutoff `option was only implemented post-graph when creating contigs and wouldn't impact the graph itself. I'll just re-run with this option, which will automate the solution since I have ~25 genomes that are contaminated.
