### ISSUE TITLE
Spades.py function program segment positioning

### ISSUE THREAD

**Issue by eecho-ohcee** [ablab/spades#655]
Hello,
         In the process of metagenomic assembly using spades.py, I found that the program mainly carried out Read error correction, Corrected reads compression, Assembling, Copy files, Breaking scaffolds, and Terminate started. I am curious about which program segments implement the above functions, how can I locate them for subsequent time measurement of these program segments?At present, I can only locate the print position of the log file in the executor_local.py program. The following are my command line parameters.
          Looking forward to your answer，thank you.
#
# python spades.py -t 28 -m 1024 --meta -k 21,33,55,77 -1 output_forward_paired.fq.gz -2 output_reverse_paired.fq.gz -o ./spa_out

**Comment by asl** [comment]
Hello

If time measurements are what you are after – then you could simply deduce the time from the log.

Otherwise - you could inspect `run_spades.yaml` and `run_spades.sh` files in the output directory. They are equivalent of running the pipeline via spades.py
