### ISSUE TITLE
how to co-assemble multiple metagenome samples by using metaspades 

### ISSUE THREAD

**Issue by biohuzi** [ablab/spades#656]
hello, I have three pair-end metagenome data as following:  sample1_R1.fq，sample1_R2.fq；sample2_R1.fq，sample2_R2.fq；sample3_R1.fq，sample3_R2.fq. I am wondering how to co-assemble the three  metagenome data above by using metaspades.
Looking forward to your reply，thanks.

**Comment by asl** [comment]
In general we do not recommend co-assembly as this might inflate misassembly rate, etc. However, in such case either merge reads, or provide all of them as a single libraty

**Comment by siduanmiao** [comment]
But if we cat all the sample.fq in a single library, is it also called co-assembly? I felt confused about what is co-assembly. Is it different bewteen we input many files using "--pe" and  just cat them as a single file.
