### ISSUE TITLE
which pipeline should I choose for metaviralspades in SPAdes 3.15.0.

### ISSUE THREAD

**Issue by mol529** [ablab/spades#657]
In the latest release SPAdes 3.15.0, I could not find the pipeline for metaviralspades. 
How do I assembly of viruses from metagenomic data?
Thanks!

**Comment by asl** [comment]
metaviralSPAdes is a part of SPAdes 3.15.0.

It would help if you describe what steps you did to "find the pipeline"?

**Comment by mol529** [comment]
> metaviralSPAdes is a part of SPAdes 3.15.0.
> 
> It would help if you describe what steps you did to "find the pipeline"?

Thanks!
I want to extract viral contigs from metagenomic data.
The first step is assembly using metaviralspades pipeline in the latest release SPAdes 3.15.0. 
According to the "Basic options" in the README.md of SPAdes 3.15.0, I set the parameter as below:
spades.py --metaviral \
  -1 test_1.fastq \
  -2 test_2.fastq \
  -s test.unpaired.fq \
  -o metavirus \
  -t 28 \
  -m 500

However, it failed with the reports as below:

"option --metaviral not recognized
SPAdes genome assembler v3.13.0

Usage: /lustre/software/metaWRAP/1.2.2/bin/spades.py [options] -o <output_dir>

Basic options:
-o      <output_dir>    directory to store all the resulting files (required)
--sc                    this flag is required for MDA (single-cell) data
--meta                  this flag is required for metagenomic sample data
--rna                   this flag is required for RNA-Seq data
--plasmid               runs plasmidSPAdes pipeline for plasmid detection
--iontorrent            this flag is required for IonTorrent data
--test                  runs SPAdes on toy dataset
-h/--help               prints this usage message
-v/--version            prints version
...."

So, I'm confused how to set the parameters for metaviralspades.
Thanks!

**Comment by asl** [comment]
So, maybe the reason is here:
> SPAdes genome assembler v3.13.0

Apparently, 3.13 did not contain metaviral pipeline, 3.15 does.
