### ISSUE TITLE
Tracing identities of reads in each contig

### ISSUE THREAD

**Issue by kislyuk** [ablab/spades#658]
Hi, thanks for developing and maintaining SPAdes.

I'm looking for a way to list the names (FASTA/FASTQ IDs) of reads that were used to assemble each contig (without realigning the reads back to the contigs, which gives no guarantee that the reads will align back to where the assembler used them, increases complexity, and opens things up to configuration mismatches).

Is there any way to trace the read IDs through any SPAdes debug output or intermediate files or something similar?

Thanks.

**Comment by asl** [comment]
Hello

The assembly (as in any de Bruijn graph assembler) is done from k-mers and not from reads. So, the only way is to align reads back to the contigs.

Hope this helps
