### ISSUE TITLE
metaspades.py Error: finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by MDAlamin13** [ablab/spades#663]
Can anyone please explain what's the probable reason of this error?
== Error ==  system call for: "[.......]" finished abnormally, OS return value: -9
[params.txt](https://github.com/ablab/spades/files/5960956/params.txt)
[spades.log](https://github.com/ablab/spades/files/5960958/spades.log)

Note: My **sapdes.py --test**  completed without any error (however raising a warning about the data having high uniform coverage depth). I am adding the log for the --test run also.
[spades_test.log](https://github.com/ablab/spades/files/5961321/spades_test.log)

**Comment by szimmerman92** [comment]
I got this error when I ran out of memory. Could that have been the problem?

**Comment by asl** [comment]
@szimmerman92 You may want to check your system log to check why the process was killed. It might be OOM killer, yes.

**Comment by szimmerman92** [comment]
Thanks! It was definitely the OOM killer.
