### ISSUE TITLE
spades-core Assertion `NewRefCount >= 0 && "Reference count was already zero."' failed.

### ISSUE THREAD

**Issue by DomeJoyce** [ablab/spades#665]
Hi there, 

I'm stucked with the genome assembly of ~800Mb in size.
I have 320Gb of RAM on my server, but here it seems that the error is not related to the RAM size limit.

Can you help me to understand and fix the problem??
here after the error and the param.txt and spades.log files.
[params.txt](https://github.com/ablab/spades/files/5970699/params.txt)
[spades.log](https://github.com/ablab/spades/files/5970700/spades.log)

  1:43:42.908    14G / 28G   INFO    General                 (sequence_mapper_notifier.h:  77)   Processed 33600000 reads
  1:46:07.370    14G / 28G   INFO    General                 (sequence_mapper_notifier.h:  77)   Processed 67158600 reads
  1:47:01.907    14G / 28G   INFO    General                 (sequence_mapper_notifier.h:  95)   Total 72977880 reads processed
  1:47:02.871    11G / 28G   INFO    General                 (gap_closer.cpp            : 448)   Initializing gap closer
  1:47:02.876    11G / 28G   INFO   GapCloser                (gap_closer.cpp            : 355)   Closing short gaps
spades-core: /opt/conda/conda-bld/spades_1612483518499/work/ext/include/llvm/ADT/IntrusiveRefCntPtr.h:98: void llvm::ThreadSafeRefCountedBase<Derived>::Release() const [with Derived = Sequence::ManagedNuclBuffer]: Assertion `NewRefCount >= 0 && "Reference count was already zero."' failed.

== Error ==  system call for: "['/home/software/anaconda3/bin/spades-core', '/mnt/nas/Projects/Domi/Zu_crist/SPADES_run2/K61/configs/config.info', '/mnt/nas/Projects/Domi/Zu_crist/SPADES_run2/K61/configs/careful_mode.info']" finished abnormally, OS return value: -6

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /mnt/nas/Projects/Domi/Zu_crist/SPADES_run2/spades.log

**Comment by asl** [comment]
Hello

This is a known problem with 3.15 which will be fixed by 3.15.1 next week.

PS: The set of k-mer lengths does not make any sense – it's a waste of time.

**Comment by DomeJoyce** [comment]
> Hello
> 
> This is a known problem with 3.15 which will be fixed by 3.15.1 next week.
> 
> PS: The set of k-mer lengths does not make any sense – it's a waste of time.

What's your advice for setting the best k-mers or to intercept the best one? I tough using a large range using small intervals can help assembler to choose the best one at the end.

Thank you for your quick answer

**Comment by asl** [comment]
> What's your advice for setting the best k-mers or to intercept the best one? I tough using a large range using small intervals can help assembler to choose the best one at the end.

SPAdes does not "choose the best one" (see https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cpbi.102 for more information), rather it uses all the information from all k-mers, therefore "small intervals" would almost always mean "extra work for now profit". If unsure – stick to the defaults.

**Comment by asl** [comment]
Fixed in 3.15.1
