### ISSUE TITLE
rnaSpades strand with hybrid data 

### ISSUE THREAD

**Issue by RogerioRibeiro201505534** [ablab/spades#667]
Hello! 
I'm currently trying to assemble a hybrid transcriptome using Illumina data (not strand-specific, FR orientation) and nanopore data (which is stranded specific since It was preprocessed with pychopper). Reading your manual and your 2020 protocol paper I was not able to identify how to specify this data type to the software. Apologies if I missed something obvious.

Cheers
RR

**Comment by asl** [comment]
Taggin @andrewprzh

**Comment by andrewprzh** [comment]
Hi Rogerio!
You have not missed anything obvious. Unfortunately, rnaSPAdes infers transcript strand only using Illumina data (if it is stranded). Long reads are not used for strand identification.
I'd suggest to perform hybrid assembly using --nanopore option and then identify strand by mapping your long reads onto the assembled transcripts using minimap2.

Best
Andrey

**Comment by RogerioRibeiro201505534** [comment]
Hi @andrewprzh  got it! 
I just got a couple more questions

1 - One thing I'm not sure about rnaSpades is how long reads are being used. Are they only used to improve the short reads graphs path? Or are they being used outside of it? I ask because my long reads and my short reads are not from the same samples (they are similar, however, with short reads being from very young and very old leaves and long reads being from intermediary states). 

2- My short reads are from two different libraries preparation methods. For the hybrid assembly, I concatenated my 23 samples (11 prepared with lib A, and 12 prepared from lib B). Should I split my input? 

Best 
RR

**Comment by andrewprzh** [comment]
1. Yes, long reads are used to improve paths in the graph constructed from short reads. So if some transcripts are expressed only the sample that was used for Nanopore sequencing, you may miss them.
2. If you aim for the assembly of the total transcriptome, I'd suggest to use all the data together without splitting it.

**Comment by RogerioRibeiro201505534** [comment]
Thank you! 
You can close this issue if you wish
