### ISSUE TITLE
metaviralspades finished abnormally OS return value -06

### ISSUE THREAD

**Issue by sahutt** [ablab/spades#668]
Hello,

I have 3 metagenomes on which I am trying to run metaviralspades. Two of them completed without issue, but the third has given me a few problems. The first time I ran it, it timed out on my HPC cluster so I ran --continue on it and got the warning that a checkpoint was missing and that the assembly had finished abnormally with a return value of -6. I figured it was an issue with the continue so I cleared the out directory, set the time longer and ran the job from scratch. I got the same error this time around.

Here are the output documents:
[spades.log](https://github.com/ablab/spades/files/6022447/spades.log)
[params.txt](https://github.com/ablab/spades/files/6022449/params.txt)

I appreciate any help you can give me.

**Comment by asl** [comment]
This is a known issue with SPAdes 3.15 that will be fixed in 3.15.2

**Comment by asl** [comment]
Fixed in SPAdes 3.15.2
