### ISSUE TITLE
Some questions about SPAdes pipeline

### ISSUE THREAD

**Issue by zhang-HZAU** [ablab/spades#670]
Dear all,
        I am currently using the spades program for metagenomic assembly. The following are my command line parameters. I have a few questions about the pipeline of spades during use. Question 1: What is the specific role of each module in the pipeline? For example, what is the purpose of reading correction? I sincerely hope you can provide the corresponding references or materials for me to study further. Question 2: How to get the experimental data of the SPAdes performance part on github (see the figure below)? I noticed that there is some information in the program output log, but it seems that the information is not what I want.

 Looking forward to your answer, thank you! 

# spades.py -t 7 -m 1024 --meta -k 21,33,55,77 -1 2122a_R1.fq.gz -2 2122a_R2.fq.gz -o spades_result
![QQ截图20210223102149](https://user-images.githubusercontent.com/73236687/108796692-48c76900-75c4-11eb-91ef-e6de24b24253.png)

**Comment by asl** [comment]
Hello

1. Please refer to https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cpbi.102 - it contains high-level overview as well as references to other papers
2. There are plenty of different tools that could be used to track the memory consumption / disk utilization. E.g. dstat / dool could certainly help
