### ISSUE TITLE
mimalloc: warning: unable to allocate from region: size 4194304

### ISSUE THREAD

**Issue by ZhangZhenmiao** [ablab/spades#672]
Dear SPAdes team,

I am seeking help with the warning of "mimalloc: warning: unable to allocate from region: size 4194304". I am not sure whether it's harmless or it means the failure of memory allocation. Thank you.

This is my log file of SPAdes:
[metaspades_S001.log](https://github.com/ablab/spades/files/6054389/metaspades_S001.log)

**Comment by asl** [comment]
As there is no error in the log and the assembly is up and running, you're ok.
