### ISSUE TITLE
About metaspades

### ISSUE THREAD

**Issue by zhang-HZAU** [ablab/spades#673]
Hi,
I am a novice. I am currently using the spades.py program for metagenomic assembly. I want to know how the spades.py program calls the C++ executable program. The following are my command line parameters. After consulting the information, I found that I mainly call the two parts of the pipeline: spades/assembler/src/projects/hammer/ and spades/assembler/src/projects/spades/ when using it. I now know that C++ programs are compiled by cmake to get executable files. It seems that the C++ project is called by import os in the python program, but I did not find the regular os.system() function in spades.py to implement the call. Looking forward to your answers. 
# spades.py -t 7 -m 1024 --meta -k 21,33,55,77 -1 2122a_R1.fq.gz -2 2122a_R2.fq.gz -o spa_L_n23

**Comment by asl** [comment]
Hello

The pipeline implementation also resides in `spades_pipeline`, you may want to check the code there as well. Anyway, the main question is why you need all this information? If you're a novice and just learning programming, then there are many online-courses around which might suite your better.

**Comment by zhang-HZAU** [comment]
Hello,
As to why I need to know so much information because I have come into contact with metagenomic assembly, I actually found that the overall effect of the spades program assembly is the best, but the program assembly time and memory consumption are relatively large. The teacher wants our team to try to reduce time and memory consumption by optimizing the code. We also want to contribute to the spades project. Taking a step back, this code optimization is also a learning process for us. Still want to ask how the spades.py program calls the C++ executable program? In addition, for the lack of memory and time resources of the spades program, what optimization suggestions do you have? Looking forward to your answers.

**Comment by alienzj** [comment]
@zhang-HZAU https://github.com/ablab/spades/blob/spades_3.15.2/assembler/spades.py#L614

**Comment by asl** [comment]
@zhang-HZAU I'm afraid your teacher does not understand fully the overall complexity of this task. We (SPAdes teams) constantly work on improving the memory consumption and running time of the assembler. In any case, we certainly welcome any patches and improvements.

Good luck!

**Comment by asl** [comment]
@zhang-HZAU I'm afraid your teacher does not understand fully the overall complexity of this task. We (SPAdes teams) constantly work on improving the memory consumption and running time of the assembler. In any case, we certainly welcome any patches and improvements.

Good luck!
