### ISSUE TITLE
Missing information after de novo assembly with SPAdes

### ISSUE THREAD

**Issue by sagrant** [ablab/spades#674]
I am attempting to use SPAdes as a de novo assembler and then align the assembly back to the samples FASTQs I started out with. I have been trying to assemble paired-end low coverage WGS samples with SPAdes, but when I try to re-align the contigs to the original FASTQs, there is a ton of information missing in the SAM files. Mostly it seems like the assembler I'm using is not able to map contig names back to reads, and in the RNAME column of the SAM file there are many asterisks. I have used kallisto, bwa, and minimap2 for alignment but the outputs are all the same. I am wondering if this issue comes from the warnings I get after the SPAdes pipeline is finished, or if there is something else I'm doing wrong. 

Attached are the warnings log and spades log that were output: 
[warnings.log](https://github.com/ablab/spades/files/6072225/warnings.log)
[spades.log](https://github.com/ablab/spades/files/6072226/spades.log)

**Comment by asl** [comment]
Hello

I'm confused. Are you aligning the contigs back to the reads? Not the opposite? This does not make any sense and certainly will never work.

You warnings are likely benign and come from low-covered input data

PS: The current SPades version is 3.15.1

**Comment by sagrant** [comment]
> Hello
> 
> I'm confused. Are you aligning the contigs back to the reads? Not the opposite? This does not make any sense and certainly will never work.
> 
> You warnings are likely benign and come from low-covered input data
> 
> PS: The current SPades version is 3.15.1

Ah sorry: I meant that I am aligning reads from the FASTQs back to the contigs file

**Comment by asl** [comment]
Well, as your assemblies are very low covered it's expected that many reads will not form the contigs.
