### ISSUE TITLE
Trouble running SPAdes on IonTorrent data

### ISSUE THREAD

**Issue by BCMollett** [ablab/spades#679]
Hi, 
I have limited knowledge of processing IonTorrent data but running into a consistent error when running SPAdes.
I cant figure out what the issue is... sorry if its simple and thanks in advance for your help.

Is the below error being caused by my input?

 0:00:00.059    95M / 95M   ERROR   General                 (mmapped_reader.hpp        :  81)   unlink(2) failed. Reason: No such file or directory. Error code: 2 

It also appears that the kmer temp folders might not be being deleted? It is saying that the folder is not empty

[params.txt](https://github.com/ablab/spades/files/6115430/params.txt)
[spades.log](https://github.com/ablab/spades/files/6115431/spades.log)

Thanks,
Ben

**Comment by asl** [comment]
Hello

The log reads:
```
  0:00:00.029     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             :  89)   Processed 0 reads
```

So, either the input file is empty or corrupted.

PS: For assembling Influenza data you may want to use coronaSPAdes (see https://www.biorxiv.org/content/10.1101/2020.07.28.224584v2 for more information)
