### ISSUE TITLE
Node name incongruence between fasta and paths files

### ISSUE THREAD

**Issue by mickey2016** [ablab/spades#68]
Hi,

Node name sometimes does not match between fasta and paths files because length value is different.
e.g.
scaffolds.fasta
>NODE_1238_length_5937_cov_185.149
scaffolds.paths
NODE_1238_length_5935_cov_185.149

I observed this for v.3.9.0.

**Comment by asl** [comment]
Are you using --careful? Does the problem reproduce with the latest 3.11.1 ?

**Comment by mickey2016** [comment]
Using --careful -k 21,33,55,77,99,127.
I'll try later for 3.11.1.

**Comment by asl** [comment]
The lengths might be different, unfortunately, since mismatch corrector corrects short indels as well.

**Comment by mickey2016** [comment]
Thanks. 
Once I know it is, it's ok. I just use node number (NODE_<number>) when I want to match them between the two files.
