### ISSUE TITLE
Failed to determine erroneous kmer threshold

### ISSUE THREAD

**Issue by emmannaemeka** [ablab/spades#680]
Hello,
Please I am having issues trying to assemble a genome using spades. 

I used the commandline 
spades.py -1  /Users/emmannadi/Desktop/Salmonella_genome_fastq/1145S/1145_result_new/21-005-0060_S44_R1.corrected.fq    -2 /Users/emmannadi/Desktop/Salmonella_genome_fastq/1145S/1145_result_new/21-005-0060_S44_R2.corrected.fq -o spades_1145_assembly --careful --threads 4 --only-assembler -k 21,33,55,77,99,127

The assembly finished with a warning. 

i have attached the warning and param files for  more information. 

Thanks

[params.txt](https://github.com/ablab/spades/files/6119029/params.txt)
[spades.log](https://github.com/ablab/spades/files/6119032/spades.log)
[warnings.log](https://github.com/ablab/spades/files/6119033/warnings.log)

**Comment by asl** [comment]
You are having very low covered dataset with uneven coverage hence the warnings. In addition to this, you're assembling 150 bp reads using k-mer length up to 127. This might give suboptimal results especially in your settings.

**Comment by emmannaemeka** [comment]
Thanks for the reply.
First the genome sequence is about 100x coverage. I have tried running with -k 17,21,33 

The warning

=== Error correction and assembling warnings:
 * 0:00:01.265    16M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 1
 * 0:00:01.034    16M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 3
 * 0:00:01.058    16M / 3G    WARN    General                 (simplification.cpp        : 479)   The determined erroneous connection coverage threshold may be determined improperly
 * 0:00:01.126    16M / 3G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 2
======= Warnings saved to /Users/emmannadi/Desktop/Salmonella_genome_fastq/1145S/1145_result_new/spades_1145mm_assembly/warnings.log
