### ISSUE TITLE
mimalloc: error: unable to allocate OS memory...finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by gauss1777** [ablab/spades#681]
Dear SPAdes support team,

I am seeking help with the warning of "mimalloc: error: unable to allocate OS memory...finished abnormally, OS return value: -6". The test "spades.py --test --isolate" was right. I used qsub with pbs file to submit the task. I don't know where is the problem. Thank you.

Log file and other attachments are as below.
[spades_1.zip](https://github.com/ablab/spades/files/6120186/spades_1.zip)

**Comment by asl** [comment]
The log reads:
```
mimalloc: error: unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
```

So you're running out of RAM
