### ISSUE TITLE
Error: The program was terminated by segmentation fault

### ISSUE THREAD

**Issue by kishore556** [ablab/spades#682]
I am trying to correct and assembly the illumina reads with SPAdes on Windows Subsystem Linux UBUNTU 16. 04 LTS. The correction programs starts but get terminated by segmentation fault. I don't understand the problem. Kinldy help me to solve this issue. The program running text as..

(base) kishor@SHOURYA:~/ilumina$ spades.py -1 5_r11.fq.gz -2 5_r12.fq.gz -1 N_r21.fq.gz -2 N_r22.fq.gz  --careful --cov-cutoff auto -o spdiluasmb
Command line: /home/kishor/anaconda3/bin/spades.py      -1      /home/kishor/ilumina/5_r11.fq.gz     -2      /home/kishor/ilumina/5_r12.fq.gz        -1      /home/kishor/ilumina/N_r21.fq.gz     -2      /home/kishor/ilumina/N_r22.fq.gz        --careful       --cov-cutoff    auto
-o      /home/kishor/ilumina/spdiluasmb

System information:
  SPAdes version: 3.13.0
  Python version: 3.8.3
  OS: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.10

Output dir: /home/kishor/ilumina/spdiluasmb
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/kishor/ilumina/5_r11.fq.gz', '/home/kishor/ilumina/N_r21.fq.gz']
      right reads: ['/home/kishor/ilumina/5_r12.fq.gz', '/home/kishor/ilumina/N_r22.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned ON and threshold will be auto-detected
Other parameters:
  Dir for temp files: /home/kishor/ilumina/spdiluasmb/tmp
  Threads: 16
  Memory limit (in Gb): 15

======= SPAdes pipeline started. Log can be found here: /home/kishor/ilumina/spdiluasmb/spades.log

===== Read error correction started.

== Running read error correction tool: /home/kishor/anaconda3/share/spades-3.13.0-0/bin/spades-hammer /home/kishor/ilumina/spdiluasmb/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===
//Program stuck after this point.

Kindly provide me help to track the problem and solve this issue.

**Comment by asl** [comment]
Hello

We neither support not test SPAdes under WSL. You may want to compile SPAdes from sources on this platform. Refer to SPAdes manual https://cab.spbu.ru/files/release3.15.2/manual.html#sec2.3 for more information

**Comment by kishore556** [comment]
Thanks @Anton for suggestion. I compiled the SPAdes from sources. Its running better but got error -6 related to /tmp directory. 
Std runtime Error message as  "Cannot create temporary dir /home/acer/talaro/illumina/spdasmb/tmp/corrector_8iymmcwv/lib1_XXXXXX" 
== Error ==  system call for: "['/usr/lib/spades/bin/spades-corrector-core', '/home/acer/talaro/illumina/spdasmb/mismatch_corrector/contigs/configs/corrector.info', '/home/acer/talaro/illumina/spdasmb/misc/assembled_contigs.fasta']" finished abnormally, err code: -6

How can I overcome this problem?
I got the read assembled files as "assembled_contigs.fasta". Can I further continue the SPAdes for the step 'Mismatch Correction' only?

**Comment by asl** [comment]
You can give `--continue` a try

**Comment by kishore556** [comment]
That --continue option I used in my first try. 
How can I specify tmp directory as it was error related only with tmp directory
Now trying to use --restart-from option for mismatch correction.
