### ISSUE TITLE
metaviral spades output

### ISSUE THREAD

**Issue by AleCisMar** [ablab/spades#683]
Apparently the program runs well until the end. However there is not a scaffolds.fasta file. Instead a number of fasta files can be found within the K127 directory. For example some are named `final_contigs_cutoff_type.fasta`. Is this supposed to happen? Are these the expected output files? I suspect it might be a bug related to the following error:
[spades.log](https://github.com/ablab/spades/files/6134239/spades.log)
[params.txt](https://github.com/ablab/spades/files/6134240/params.txt)

===== K127 finished. 

===== metaextrachromosomal glue files started. 

== Running:  /srv/home/acisneros/SPAdes-3.15.2/share/spades/spades_pipeline/scripts/plasmid_glue.py /srv/home/acisneros/SPAdes-3.15.2/bin/metaviral_spadesMET2/K127

[Errno 13] Permission denied
Traceback (most recent call last):
  File "/srv/home/acisneros/SPAdes-3.15.2/bin/spades.py", line 618, in main
    executor.execute(commands)
  File "/srv/home/acisneros/SPAdes-3.15.2/share/spades/spades_pipeline/executors/executor_local.py", line 37, in execute
    command.run(self.log)
  File "/srv/home/acisneros/SPAdes-3.15.2/share/spades/spades_pipeline/commands_parser.py", line 38, in run
    support.sys_call(self.to_list(), log)
  File "/srv/home/acisneros/SPAdes-3.15.2/share/spades/spades_pipeline/support.py", line 285, in sys_call
    proc = subprocess.Popen(cmd_list, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=cwd)
  File "/srv/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/srv/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

== Error ==  exception caught: <type 'exceptions.OSError'>

**Comment by asl** [comment]
Tagging @Dmitry-Antipov

**Comment by Dmitry-Antipov** [comment]
No, that's not what suppose to happen. Looks like something went wrong with executing permissions on plasmid_glue script.

Can you please run "ls -la  /srv/home/acisneros/SPAdes-3.15.2/share/spades/spades_pipeline/scripts/plasmid_glue.py" and show us the result?

**Comment by AleCisMar** [comment]
~/bin/SPAdes-3.15.2/share/spades/spades_pipeline/scripts$ ls -la
total 52
drwxr-xr-x 2 acisneros acisneros 4096 Mar 12 12:24 .
drwxr-xr-x 7 acisneros acisneros 4096 Mar 12 12:42 ..
-rw-r--r-- 1 acisneros acisneros 1849 Mar 10 08:25 breaking_scaffolds_script.py
-rw-r--r-- 1 acisneros acisneros 3728 Mar 10 08:25 check_test_script.py
-rw-r--r-- 1 acisneros acisneros 4967 Mar 10 08:25 compress_all.py
-rw-r--r-- 1 acisneros acisneros  820 Mar 10 08:25 copy_files.py
-rw-r--r-- 1 acisneros acisneros 3374 Mar 10 08:25 correction_iteration_script.py
-rw-r--r-- 1 acisneros acisneros 1122 Mar 10 08:25 plasmid_glue.py
-rw-r--r-- 1 acisneros acisneros 3435 Mar 10 08:25 postprocessing_script.py
-rw-r--r-- 1 acisneros acisneros 2473 Mar 10 08:25 preprocess_contigs.py
-rw-r--r-- 1 acisneros acisneros 4506 Mar 10 08:25 preprocess_interlaced_reads.py

**Comment by Dmitry-Antipov** [comment]
That's actually OK...
Can you please run /srv/home/acisneros/SPAdes-3.15.2/bin/spades.py --test and /srv/home/acisneros/SPAdes-3.15.2/bin/metaviralspades.py --test ? Do they both finish properly (with message = TEST PASSED CORRECTLY.)?

**Comment by AleCisMar** [comment]
Both finish properly :S

===== metaextrachromosomal glue files started. 


== Running: /srv/home/acisneros/bin/miniconda2/bin/python /srv/home/acisneros/bin/SPAdes-3.15.2/share/spades/spades_pipeline/scripts/plasmid_glue.py /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77

final_contigs___5.linearrepeat.fasta
final_contigs_434.linears.fasta
...
final_contigs_434.circular.fasta
final_contigs__42.circular.fasta
 
===== metaextrachromosomal glue files finished. 


===== Copy files started. 


== Running: /srv/home/acisneros/bin/miniconda2/bin/python /srv/home/acisneros/bin/SPAdes-3.15.2/share/spades/spades_pipeline/scripts/copy_files.py /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/before_rr.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/before_rr.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/assembly_graph_after_simplification.gfa /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/assembly_graph_after_simplification.gfa /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/final_contigs.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/contigs.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/first_pe_contigs.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/first_pe_contigs.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/strain_graph.gfa /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/strain_graph.gfa /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/scaffolds.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/scaffolds.fasta /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/scaffolds.paths /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/scaffolds.paths /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/assembly_graph_with_scaffolds.gfa /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/assembly_graph_with_scaffolds.gfa /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/assembly_graph.fastg /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/assembly_graph.fastg /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/K77/final_contigs.paths /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/contigs.paths


===== Copy files finished. 


===== Assembling finished. 


===== Check test started. 


== Running: /srv/home/acisneros/bin/miniconda2/bin/python /srv/home/acisneros/bin/SPAdes-3.15.2/share/spades/spades_pipeline/scripts/check_test_script.py --mode plasmid --result_contigs_filename /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/contigs.fasta --result_scaffolds_filename /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/scaffolds.fasta

========= TEST PASSED CORRECTLY.

===== Check test finished. 


===== Breaking scaffolds started. 


== Running: /srv/home/acisneros/bin/miniconda2/bin/python /srv/home/acisneros/bin/SPAdes-3.15.2/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/scaffolds.fasta --misc_dir /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/misc --threshold_for_breaking_scaffolds 3


===== Breaking scaffolds finished. 


===== Terminate started. 


===== Terminate finished. 

 * Corrected reads are in /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/corrected/
 * Assembled contigs are in /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/contigs.fasta
 * Assembled scaffolds are in /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/scaffolds.fasta
 * Paths in the assembly graph corresponding to the contigs are in /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/scaffolds.paths
 * Assembly graph is in /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/assembly_graph.fastg
 * Assembly graph in GFA format is in /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/assembly_graph_with_scaffolds.gfa

======= SPAdes pipeline finished.

SPAdes log can be found here: /srv/home/acisneros/bin/SPAdes-3.15.2/bin/spades_test/spades.log

Thank you for using SPAdes!

**Comment by Dmitry-Antipov** [comment]
well, that looks  strange. Possibly something went wrong in your first run with your python installation but I have no idea how this may happen.

What happens if you run ./spades.py --continue -o /srv/home/acisneros/SPAdes-3.15.2/bin/metaviral_spadesMET2 ?

**Comment by AleCisMar** [comment]
That works! Thanks a lot!
