### ISSUE TITLE
About related algorithms

### ISSUE THREAD

**Issue by zhang-HZAU** [ablab/spades#684]
Hello,
Thank you very much for the contribution made by the SPAdes software development team to genome assembly. The software performed well.I,now, want to understand the related algorithms of the SPAdes program for metagenomic assembly. Relevant documents have been found.
①Using SPAdes De Novo Assembler;
②Assembling Single-Cell Genomes and Mini-Metagenomes From Chimeric MDA Products (Nurk et al. (2013);
③SPAdes: A New Genome Assembly Algorithm and Its Applications to Single-Cell Sequencing (Bankevich et al. (2012));
④metaSPAdes: a new versatile metagenomic assembler (Nurk et al. (2017)).
……
However, it is difficult to directly understand the algorithm in the literature. Is there any early literature or material that can assist in understanding the metagenomic assembly algorithm? In addition, do you have any suggestions for understanding related algorithms?
Looking forward to your answer, thank you!

**Comment by asl** [comment]
SPAdes is quite complex assembler – it involves ~10 years of development effort of a team of 5-10 persons. These papers along with the source code is the best references, I'm afraid.
