### ISSUE TITLE
Strange structures in metaspades assembly

### ISSUE THREAD

**Issue by marcomeola** [ablab/spades#685]
I am running the STRONG pipeline (```https://github.com/chrisquince/STRONG```) with metaspades as a first step for a co-assembly on 8 samples. Barcode and quality of Illumina 75 bp and 150 bp reads were trimmed using fastp. 

The assembly graphs output present some strange hairy features (see fig). Has this already been observed in a co-assembly with metaspades? 
The parameters used are set by the STRONG pipeline ```--meta --only-assembler --save-gp```

Happy for any suggestion
![Screenshot 2021-03-11 at 10 23 57](https://user-images.githubusercontent.com/19171667/111468936-6a7cc180-8726-11eb-853c-8e1174e5d016.png)

**Comment by asl** [comment]
This looks like some unclipped tips. SPAdes happily clips lots of tips, so it might be some local modification that pipeline uses. I would suggest you to try to reproduce the issue with the latest SPAdes 3.15 w/o any additional pipelines, etc.

**Comment by marcomeola** [comment]
The hairy structures were due to the k-mer sizes selected. After rerunning the assembly step with 21,33,55 the graphs looked ok. Therefore I close this thread
