### ISSUE TITLE
Running into an error while running hybrid plant genome assembly using SPAdes.

### ISSUE THREAD

**Issue by amanpruthi15** [ablab/spades#687]
I am getting an error while running spades. I have checked my .fq read files. Ran fastq_pair as well and I have the same number of reads in both the files but still getting the same error.

`== Error ==  system call for: "['/home/apruthi/anaconda3/bin/spades-hammer', '/lustre/scratch/apruthmally, OS return value: 255`

If I use `--only-assembly --careful` then I get this error: 

`== Error ==  system call for: "['/home/apruthi/SPAdes/SPAdes-3.12.0-Linux/bin/spades-core', '/lustre/scratch/apruthi/spades/spades_filtered/K21/configs/config.info', '/lustre/scratch/apruthi/spades/spades_filtered/K21/configs/careful_mode.info']" finished abnormally, err code: -6`

**params.txt** 
Command line: /home/apruthi/SPAdes/SPAdes-3.12.0-Linux/bin/spades.py    --nanopore      /lustre/scratch/joh97948/bryum_filtered.fq      -1      /lustre/scratch/apruthi/fastp/Female_R1_paired.fq   -2      /lustre/scratch/apruthi/fastp/Female_R2_paired.fq       -t      128     --careful       --only-assembler        -o      /lustre/scratch/apruthi/spades/spades_filtered

System information:
  SPAdes version: 3.12.0
  Python version: 3.7.3
  OS: Linux-4.18.0-147.8.1.el8_1.x86_64-x86_64-with-centos-8.1.1911-Core

Output dir: /lustre/scratch/apruthi/spades/spades_filtered
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/lustre/scratch/apruthi/fastp/Female_R1_paired.fq']
      right reads: ['/lustre/scratch/apruthi/fastp/Female_R2_paired.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
    Library number: 2, library type: nanopore
      left reads: not specified
      right reads: not specified
      interlaced reads: not specified
      single reads: ['/lustre/scratch/joh97948/bryum_filtered.fq']
      merged reads: not specified
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /lustre/scratch/apruthi/spades/spades_filtered/tmp
  Threads: 128
  Memory limit (in Gb): 250

**spades.log**
Command line: /home/apruthi/SPAdes/SPAdes-3.12.0-Linux/bin/spades.py    --nanopore      /lustre/scratch/joh97948/bryum_filtered.fq      -1      /lustre/scratch/apruthi/fastp/Female_R1_paired.fq   -2      /lustre/scratch/apruthi/fastp/Female_R2_paired.fq       -t      128     --careful       --only-assembler        -o      /lustre/scratch/apruthi/spades/spades_filtered

System information:
  SPAdes version: 3.12.0
  Python version: 3.7.3
  OS: Linux-4.18.0-147.8.1.el8_1.x86_64-x86_64-with-centos-8.1.1911-Core

Output dir: /lustre/scratch/apruthi/spades/spades_filtered
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/lustre/scratch/apruthi/fastp/Female_R1_paired.fq']
      right reads: ['/lustre/scratch/apruthi/fastp/Female_R2_paired.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
    Library number: 2, library type: nanopore
      left reads: not specified
      right reads: not specified
      interlaced reads: not specified
      single reads: ['/lustre/scratch/joh97948/bryum_filtered.fq']
      merged reads: not specified
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /lustre/scratch/apruthi/spades/spades_filtered/tmp
  Threads: 128
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /lustre/scratch/apruthi/spades/spades_filtered/spades.log

===== Assembling started.

== Running assembler: K21

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  74)   Loaded config from /lustre/scratch/apruthi/spades/spades_filtered/K21/configs/config.info
  0:00:00.021     4M / 4M    INFO    General                 (main.cpp                  :  74)   Loaded config from /lustre/scratch/apruthi/spades/spades_filtered/K21/configs/careful_mode.info
  0:00:00.021     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 250 Gb
  0:00:00.021     4M / 4M    INFO    General                 (main.cpp                  :  87)   Starting SPAdes, built from N/A, git revision N/A
  0:00:00.021     4M / 4M    INFO    General                 (main.cpp                  :  88)   Maximum k-mer length: 128
  0:00:00.021     4M / 4M    INFO    General                 (main.cpp                  :  89)   Assembling dataset (/lustre/scratch/apruthi/spades/spades_filtered/dataset.info) with K=21
  0:00:00.021     4M / 4M    INFO    General                 (main.cpp                  :  90)   Maximum # of threads to use (adjusted due to OMP capabilities): 128
  0:00:00.021     4M / 4M    INFO    General                 (launch.hpp                :  51)   SPAdes started
  0:00:00.021     4M / 4M    INFO    General                 (launch.hpp                :  58)   Starting from stage: construction
  0:00:00.021     4M / 4M    INFO    General                 (launch.hpp                :  65)   Two-step RR enabled: 0
  0:00:00.039     4M / 4M    INFO   StageManager             (stage.cpp                 : 132)   STAGE == de Bruijn graph construction
  0:00:00.041     4M / 4M    INFO    General                 (read_converter.hpp        :  77)   Converting reads to binary format for library #0 (takes a while)
  0:00:00.041     4M / 4M    INFO    General                 (read_converter.hpp        :  78)   Converting paired reads
  0:00:00.421    92M / 92M   INFO    General                 (binary_converter.hpp      :  93)   16384 reads processed
  0:00:00.833   112M / 112M  INFO    General                 (binary_converter.hpp      :  93)   32768 reads processed
  0:00:01.175   156M / 156M  INFO    General                 (binary_converter.hpp      :  93)   65536 reads processed
  0:00:01.851   244M / 244M  INFO    General                 (binary_converter.hpp      :  93)   131072 reads processed
  0:00:03.262   420M / 420M  INFO    General                 (binary_converter.hpp      :  93)   262144 reads processed
  0:00:05.932   776M / 776M  INFO    General                 (binary_converter.hpp      :  93)   524288 reads processed
  0:00:15.794     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   1048576 reads processed
  0:00:31.291     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   2097152 reads processed
  0:01:02.180     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   4194304 reads processed
  0:02:08.754     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   8388608 reads processed
  0:04:17.862     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   16777216 reads processed
  0:08:35.598     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   33554432 reads processed
  0:17:13.162     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   67108864 reads processed
  0:34:42.355     1G / 1G    INFO    General                 (binary_converter.hpp      :  93)   134217728 reads processed
  0:42:44.366     1G / 1G    INFO    General                 (binary_converter.hpp      : 117)   164621232 reads written
  0:42:45.336    12M / 1G    INFO    General                 (read_converter.hpp        :  87)   Converting single reads
  0:42:45.510   140M / 1G    INFO    General                 (binary_converter.hpp      : 117)   0 reads written
  0:42:45.514    12M / 1G    INFO    General                 (read_converter.hpp        :  95)   Converting merged reads
  0:42:45.658   144M / 1G    INFO    General                 (binary_converter.hpp      : 117)   0 reads written
  0:42:47.499    12M / 1G    INFO    General                 (construction.cpp          : 111)   Max read length 251
  0:42:47.499    12M / 1G    INFO    General                 (construction.cpp          : 117)   Average read length 236.462
  0:42:47.499    12M / 1G    INFO    General                 (stage.cpp                 : 101)   PROCEDURE == k+1-mer counting
  0:42:47.500    12M / 1G    INFO    General                 (kmer_index_builder.hpp    : 117)   Splitting kmer instances into 16384 files using 128 threads. This might take a while.
  0:42:47.506    12M / 1G    INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 16640
  0:42:47.506    12M / 1G    INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 0.651011 Gb
  0:42:47.506    12M / 1G    INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 16384
<jemalloc>: Error in malloc(): out of memory. Requested: 144176, active: 264190820352

== Error ==  system call for: "['/home/apruthi/SPAdes/SPAdes-3.12.0-Linux/bin/spades-core', '/lustre/scratch/apruthi/spades/spades_filtered/K21/configs/config.info', '/lustre/scratch/apruthi/spades/spades_filtered/K21/configs/careful_mode.info']" finished abnormally, err code: -6

**Comment by asl** [comment]
The log reads:
```
: Error in malloc(): out of memory. Requested: 144176, active: 264190820352
```

So, you're running out of RAM. I would strongly suggest you to upgrade from ancient SPAdes 3.12 to the latest 3.15.2

**Comment by amanpruthi15** [comment]
I did upgrade but still running into an error:
`== Error ==  system call for: "['/home/apruthi/SPAdes-3.15.2-Linux/bin/spades-hammer', '/lustre/scratch/apruthi/spades/spades_filtered/corrected/configs/config.info']" finished abnormally, OS return value: 12`

**Comment by amanpruthi15** [comment]
I have NovaSeq Illumina reads. I have ran fastq_pair as well. Also tried `--onlyassembly` with `--careful` still ran into an error.

**Comment by sci3** [comment]
> I have NovaSeq Illumina reads. I have ran fastq_pair as well. Also tried `--onlyassembly` with `--careful` still ran into an error.

Hi!
Have you solved this problem?
I am in the same problem as you have described
