### ISSUE TITLE
SPADES error code 21, assembly finished abnormally

### ISSUE THREAD

**Issue by DuttaAnik** [ablab/spades#688]
Hi,
I am running the following code to assemble paired end read `spades.py --careful -o Specialization -1 /data1/anik/Kmer_Gwas/examples/resistence_e_coli/sample_anik_kmer_test/example_dir/spec_reads_R1.fastq -2 /data1/anik/Kmer_Gwas/examples/resistence_e_coli/sample_anik_kmer_test/example_dir/spec_reads_R2.fastq`

But I am getting the following error message:
== Error ==  system call for: "['/home/anik/bin/SPAdes-3.15.2-Linux/bin/spades-core', '/data1/anik/Kmer_Gwas/examples/resistence_e_coli/sample_anik_kmer_test/example_dir/Specialization/K21/configs/config.info', '/data1/anik/Kmer_Gwas/examples/resistence_e_coli/sample_anik_kmer_test/example_dir/Specialization/K21/configs/careful_mode.info']" finished abnormally, OS return value: 21

I checked the read length of both the files and they are equal. 

Can you please tell me what is going wrong?
Thank you. I have attached the log and params file to this message.
[params.txt](https://github.com/ablab/spades/files/6184633/params.txt)
[spades.log](https://github.com/ablab/spades/files/6184634/spades.log)

**Comment by asl** [comment]
Hello

The log reads:
```
  0:00:00.125     1M / 18M   ERROR   General                 (kmer_coverage_model.cpp   : 187)   Invalid kmer coverage histogram, make sure that the coverage is indeed uniform
```

Given that your input consists of 9 reads, it's highly unlikely it's a proper part of any genome.

**Comment by AdrianoZaghi** [comment]
Thank you for the support job.
