### ISSUE TITLE
3.15.1: Argument --continue prevents use of --tmpdir

### ISSUE THREAD

**Issue by mmokrejs** [ablab/spades#692]
Hi,
  it seems the runtime checks is too strict and does not allow me to continue a computation while specifying `--tmpdir` . I use `--tmpdir $SCRATCH` and it point to a temporary space on the particular cluster exec node , whcih is always differ. Please send me a patch how to loosen this overly strict check.

`== Error ==  you cannot specify any option except -o with --continue option! Please use '--restart-from last' if you need to change some of the options from the initial run and continue from the last available checkpoint.
`

  I do not want to go via the `--restart-from last` route, seems unnecessary for my purpose.

**Comment by asl** [comment]
Well, this is the intended behaviour and the error message is precise on this matter. `--continue` does not do any compatibility checks, etc. and therefore does not allow any changes in the options. `--restart-from` is a generic facility and allows option changes. `--restart-from last` is fully equivalent to `--continue` in the behavior.

**Comment by mmokrejs** [comment]
`== Error ==  you cannot specify input data (-1, -2, -12, --pe-1, --pe-2 ...) with --restart-from option!`

Aha, so I should have copied over most of the commandline except the data input files.Still I think you could have just allowed for `--tmpdir` to be changed and we could have saved us this discussion. But thank you though.
