### ISSUE TITLE
Where are checkpoint data stored and moved to and when?

### ISSUE THREAD

**Issue by mmokrejs** [ablab/spades#693]
Hi,
  I ran `rnaspades.py -k 43,55,77,99,127 --checkpoints all --tmp-dir $SCRATCHDIR` where `--tmpdir` points to a local SSD disc where a directory tied to `$JOB_ID` is created by `PBS` job management system. My job died quite late with 3-rd k-mer size to be utilized. I speculate that  the temporary data or even checkpoint accumulated  on the SSD drive instead of being moved to `CWD` where the job started off and where is much more space.

  Would you please confirm `--checkpoints all` data is moved to `CWD` as early as possible? I suspect it accumulated on the SSD drive and the actual error was a write error on a full disk.

```
  0:00:00.305     1M / 44M   INFO    General                 (read_conversion.cpp       :  30)   Saving current state to /foo_rnaspades2/K99/saves/read_conversion
  0:00:00.335     1M / 44M   INFO   StageManager             (stage.cpp                 : 185)   STAGE == de Bruijn graph construction (id: construction)
  0:00:00.336     1M / 44M   INFO    General                 (construction.cpp          : 118)   Contigs from previous K will be used: /foo_rnaspades2/K77/simplified_contigs
Exception caught Cannot create temporary dir /scratch.ssd/mmokrejs/job_202191.bar/spades_Gnaq23/construction_XXXXXX

== Error ==  system call for: "['/baz/SPAdes-3.15.1/bin/spades-core', '/foo_rnaspades2/K99/configs/config.info', '/foo_rnaspades2/K99/configs/mda_mode.info', '/foo_rnaspades2/K99/configs/rna_mode.info']" finished abnormally, OS return value: 4
```

**Comment by asl** [comment]
Checkpoints are never written to scratch, they are always written to output dir. In this particular case, SPAdes request' to OS to create a temporary directory failed, there is no way to recover from / workaround this failure

**Comment by mmokrejs** [comment]
Hmm, but the `$SCRATCHDIR` contents are cleared when job finishes so I cannot study what were its contents anymore.

**Comment by asl** [comment]
In your case the checkpoints are in `/foo_rnaspades2/K99/saves/` plus some additional metadata files in `/foo_rnaspades2`.

**Comment by mmokrejs** [comment]
Perfect, please add this to the documentation, also with the statement `Checkpoints are never written to scratch, they are always written to output dir`.
