### ISSUE TITLE
Finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by regisjr42** [ablab/spades#695]
Hello, I am trying to run metatranscriptome data using rnaSPAdes with SPAdes 3.15.2, and found myself hitting this wall when running it. I had somewhat similar issues before and also looked around the board here for this error and, as far as I understand, this is most likely some memory issue. I managed to run successfully some smaller groups of samples, only this (much) larger one that did not work so I think this is plausible, the server I'm using also doesn't have some insane amount of memory (128GB RAM) also.

That being said I wanted some output from you to see I that's really the case.

The error message:
> == Error ==  system call for: "['/home/rantonioli/anaconda3/pkgs/squeezemeta-1.3.1-pl526r36_0/SqueezeMeta/bin/SPAdes/bin/spades-core', '/home/rantonioli/workspace/dataset/AllCtrlOil_SM_spades/data/spades/K73/configs/config.info', '/home/rantonioli/workspace/dataset/AllCtrlOil_SM_spades/data/spades/K73/configs/mda_mode.info', '/home/rantonioli/workspace/dataset/AllCtrlOil_SM_spades/data/spades/K73/configs/rna_mode.info']" finished abnormally, OS return value: -9

And [here](https://we.tl/t-xHoxhOGuzl) are the params.txt and spades.log files.

Thanks for your attention!

**Comment by asl** [comment]
Well, at the time of crash SPAdes wanted to use more than 128 Gb of RAM. So, unfortunately, you're out of luck here.
