### ISSUE TITLE
Plasmid hybrid assembly Illumina-Sanger

### ISSUE THREAD

**Issue by seoanezonjic** [ablab/spades#697]
Hi Spades authors
I have Illumina and sanger reads from a plasmid. I'm interested in perform a hybrid assembly but I need your feedback to perform this process. I have Illumina reads in fastq format and sanger reads in ab1 format (Forward and reverse senses). Which spades configuration should I use? Plasmid or Spades only? I think that is necessary a YAML file but it's not clear to me how to write it in this specific case. 
Thank you in advance
Pedro Seoane

**Comment by asl** [comment]
Hello

First of all, SPAdes accepts only FASTA / FASTQ as input, so you'd need to convert your Sanger reads in this format. No need for YAML is required as you could readily use `--sanger` option to specify your converted Sanger reads.

Hybrid plasmid assemblies is a bit terra incognita (also, plasmid mode essentially assumes a multi-copy plasmid), so we'd suggest to try both and examine the results

**Comment by seoanezonjic** [comment]
Hi @asl 
In other assemblers I've done the ab1 to fastq conversion so if you are ok with this step, I'll use sanger converted files. But there is a thing that surprise me. In other assemblers I had to specify a sanger fastq with forward reads and a sanger converted fastq with reverse reads. In fact, when I built the configuration file for this assembler I had to set which file was in which sense and I had to parse the read files in order to set a specific read id pattern that allow to the assembler recognize the sanger read "pairs".  Your assembler can infer this information from one single sanger file?
Thank you in advance
Pedro Seoane

**Comment by asl** [comment]
Ah, so you're having paired-end Sanger reads? This is quite rare scenario these days. What are the expected insert size and read length?

**Comment by seoanezonjic** [comment]
Yes @asl, I have a rare case xD. In fact, the research group that has this plasmid data only works with sanger and PCR. They perform a digestion and the plasmid fragments are send to sanger sequencing (forward and reverse, but I'm not sure if the service use a real pair-end procedure). So each fragment is very different in length and  the reads (once the low quality regions are removed) are quite variable.  I have 4-5 sanger reads for each plasmid and without quality processing the forward reads are 1008-1099 nt length and the reverse reads are 1453-1743 nt.
The Illumina data come from a whole dna sequencing that was performed to obtain the bacterial genome and I realized that the reads include plasmid reads that we are selecting aligning them against the sanger reads.

**Comment by asl** [comment]
Ok, given the coverage, etc. I would suggest you to ignore the pairedness for the first try and pass them as single-end ones via `--sanger`
