### ISSUE TITLE
Failed to obtained contigs and scaffolds

### ISSUE THREAD

**Issue by vcastroagudin** [ablab/spades#699]
Hello,

I am trying to assembly a genome de Novo, and although Spades does not seem to give errors it warns me in the log file of several failures. Also, the contigs and scaffold in the results file are not really assembled. I got more than 220,000 contigs and the same number of scaffolds with lengths that ranged from 20 to 3kb. There is almost nothing assembled there.
Which can be the problem? is it bad data or bad parameters in the run?
I will appreciate any help you can give me since I am new to this.

Thanks,

Vanina

[params.txt](https://github.com/ablab/spades/files/6217817/params.txt)
[spades.log](https://github.com/ablab/spades/files/6217818/spades.log)
[warnings.log](https://github.com/ablab/spades/files/6217819/warnings.log)

**Comment by asl** [comment]
Hello

What is the expected genome size?

**Comment by vcastroagudin** [comment]
Hello,
the genome is around 55 Mb

**Comment by asl** [comment]
Well, given the very low coverage of your data and the genome size, the results are quite good and expected.

**Comment by asl** [comment]
Please reopen if this is still an issue
