### ISSUE TITLE
SPAdes finished abnormally with err code -9

### ISSUE THREAD

**Issue by miguelpmachado** [ablab/spades#7]
Hi,
I'm trying to run SPAdes, but it stops at the read error correction step with err code -9. You can find SPAdes log [here](https://github.com/ablab/spades/files/479757/spades.log.txt).
I used ENA's fastq files from ERR026213 run accession with the following command: `spades.py --careful --pe1-1 ERR026213_1.fastq.gz --pe1-2 ERR026213_2.fastq.gz --threads 1 --memory 20 -o ./spades`
Is there anything that I can do to fix this?
Thanks in advance.
Best regards,
Miguel Machado

**Comment by asl** [comment]
It seems you're running out of RAM. So, please make sure that indeed all that 20 Gb you promised to SPAdes are available.

**Comment by miguelpmachado** [comment]
Thanks.
Changing --memory to 4 Gb worked
