### ISSUE TITLE
SPAdes-3.11.1 does not re-use existing $outdir/.bin_reads/*.seq contents

### ISSUE THREAD

**Issue by mmokrejs** [ablab/spades#70]
Hi,
  could spades re-use the existing input files already converted to binary? I did not use  `--restart-from` option because I anyway just use `--only-assembler`. There is no checkpoint for that stage available anyway. And, it should be automatic. Just create some file in the .bin_reads/ directory to mark that step as completed.

```
Check-points are:

    ec – start from error correction
    as – restart assembly module from the first iteration
```

**Comment by asl** [comment]
Checkpoints are re-used for --continue and --restart-from options. Otherwise the output directory is cleared, as expected.

**Comment by mmokrejs** [comment]
```
 --continue
    Continues SPAdes run from the specified output folder starting from the last available check-point. Check-points are made after:

    error correction module is finished
    iteration for each specified K value of assembly module is finished
    mismatch correction is finished for contigs or scaffolds
```
Please improve the docs. From the above it is not clear to me that it is worth using --continue for this particular case. I assume I have no checkopoint to start from in my situation, because binary-read-conversion is not a listed checkpoint step. And I do not see a reason why it couldn't be. Likewise, k-mer splitting and counting should be a separate checkpoint too. Or if you disagree, do not blindly zap whole output directory but keep the .bin_reads/ if it seems complete?

**Comment by asl** [comment]
Thanks, we may consider improving the checkpointing in some future releases.
