### ISSUE TITLE
hybrid assembly fails with return value: -24

### ISSUE THREAD

**Issue by nettanetta** [ablab/spades#702]
Hi, 
I'm running Hybrid assembly with spades and I get the following error:
"== Error ==  system call for: "['/.../spades/3.14.1/bin/spades-hammer', '/vol/.../hybrid_assembly_results/hybrid_spades/MOB103REC/corrected/configs/config.info']" finished abnormally, OS return value: -24"

When googling it I see that it means "Too many open files", but I'm not sure what causing it in our case. any ideas?
tnx! 

[hybrid spades log](https://github.com/ablab/spades/files/6242639/hybrid.spades.log)
[params.txt](https://github.com/ablab/spades/files/6242640/params.txt)

**Comment by asl** [comment]
Hello

Does the problem reproduce with the latest SPAdes 3.15.2?

**Comment by nettanetta** [comment]
Hi! tnx for the quick response.
I downloaded the last release (3.15.2) today using the instructions in the readme ("Downloading SPAdes Linux binaries"), but when I run "spades.py -v" I get "SPAdes genome assembler v3.14.1". v3.14.1 version was not previously installed on our cluster, so I think that for some reason: 
`    wget http://cab.spbu.ru/files/release3.15.2/SPAdes-3.15.2-Linux.tar.gz
    tar -xzf SPAdes-3.15.2-Linux.tar.gz
    cd SPAdes-3.15.2-Linux/bin/`
downloaded v3.14.1 instead of 3.15.2.
does it make any sense?

tnx again

**Comment by asl** [comment]
No, I double checked and there is 3.15.2 there:
```
$ SPAdes-3.15.2-Linux/bin/spades.py -v
SPAdes genome assembler v3.15.2
```

You may want to talk to your system administrator about installed versions, paths, etc.

**Comment by asl** [comment]
Please reopen if this is still an issue
