### ISSUE TITLE
compile SPAdes from Source,unknown error

### ISSUE THREAD

**Issue by zhang-HZAU** [ablab/spades#707]
Hi SPAdes team,
I now try to compile from the source code of SPAdes_v3.14.1, and my environment has met the compilation conditions g++ (version 5.3.1 or higher), cmake (version 2.8.12 or higher), zlib, libbz2. I put the corresponding g++ and cmake in my environment variables and source them. However, in the actual compilation process, the g++ compiler in another directory is still used, which causes the compilation to fail. What should I do? (I downloaded the latest version v3.15.2, this problem still exists) In addition, if I want to use Intel's compiler to compile, can I specify the compiler by parameter? The attachment is my g++ version and the output log when SPAdes is compiled.
Looking forward to your answer, thank you~
![1](https://user-images.githubusercontent.com/73236687/114263397-c1b93d80-9a17-11eb-950a-3cd346ec52b9.png)
![2](https://user-images.githubusercontent.com/73236687/114263398-c3830100-9a17-11eb-870c-7396ac76eec1.png)
[CMakeOutput.log](https://github.com/ablab/spades/files/6289491/CMakeOutput.log)

**Comment by asl** [comment]
Hello

Please refer to cmake manual for cmake questions. In particular: https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#how-do-i-use-a-different-compiler
