### ISSUE TITLE
3.15.2 crash - Bad Address - spades-corrector-core

### ISSUE THREAD

**Issue by biobrad** [ablab/spades#709]
Hi Spades Team,

$ spades.py --version
SPAdes genome assembler v3.15.2

I have had a couple of crashes while trying to assemble a bacterial genome, the error I get is:

home/harbj019/results/Klebsiella/518tormes/betakleb1204/assembly/Kpne518_assembly/misc/assembled_contigs.fasta /home/harbj019/results/Klebsiella/518tormes/betakleb1204/cleaned_reads/Kpne518.ok_1.fastq.gz /home/harbj019/results/Klebsiella/518tormes/betakleb1204/cleaned_reads/Kpne518.ok_2.fastq.gz   > /home/harbj019/results/Klebsiella/518tormes/betakleb1204/assembly/Kpne518_assembly/tmp/corrector_ch4pzsnl/lib0_yF3eEg/tmp.sam
[fputs] Bad address
  0:00:07.114     1M / 9M    INFO   DatasetProcessor         (dataset_processor.cpp     : 156)   bwa failed, skipping sublib
  0:00:07.114     1M / 9M    ERROR  DatasetProcessor         (dataset_processor.cpp     : 205)   Failed to align paired reads /home/harbj019/results/Klebsiella/518tormes/betakleb1204/cleaned_reads/Kpne518.ok_1.fastq.gz /home/harbj019/results/Klebsiella/518tormes/betakleb1204/cleaned_reads/Kpne518.ok_2.fastq.gz
== Error ==  system call for: "['/home/harbj019/miniconda3/envs/tormes-beta/bin/spades-corrector-core', '/home/harbj019/results/Klebsiella/518tormes/betakleb1204/assembly/Kpne518_assembly/mismatch_corrector/contigs/configs/corrector.info', '/home/harbj019/results/Klebsiella/518tormes/betakleb1204/assembly/Kpne518_assembly/misc/assembled_contigs.fasta']" finished abnormally, OS return value: 2

I had a look for the various files that are called, tmp.sam seems fine, but the input dataset that gets called  by corrector.info appears to have a line in it that I can't see in previous versions? Not sure if this is what is causing the crash?

cat ../../../input_dataset.yaml
- "left reads":
  - "/home/harbj019/results/Klebsiella/518tormes/betakleb1204/cleaned_reads/Kpne518.ok_1.fastq.gz"
  "number": !!int "1" <<<<<<<<<<<<<<<<<<<< ?
  "orientation": "fr"
  "right reads":
  - "/home/harbj019/results/Klebsiella/518tormes/betakleb1204/cleaned_reads/Kpne518.ok_2.fastq.gz"
  "type": "paired-end"

cheers
[spades.log](https://github.com/ablab/spades/files/6293132/spades.log)

Brad

**Comment by asl** [comment]
Hello

YAML is fine, this is expected difference between 3.15 and previous versions.

It seems that bwa run crashed for some reason unknown to us. Does the problem reproduce if you'd rerun SPAdes?

**Comment by biobrad** [comment]
Thanks for the response, I have re-run spades but it crashed for a different reason this time...

== Error ==  system call for: "['/home/harbj019/miniconda3/envs/tormes-beta/bin/spades-core', '/home/harbj019/results/Klebsiella/518betatest/klebtormestest/assembly/kpne518_assembly/K77/configs/config.info', '/home/harbj019/results/Klebsiella/518betatest/klebtormestest/assembly/kpne518_assembly/K77/configs/careful_mode.info']" finished abnormally, OS return value: -6

and then again:

0:00:01.858     1M / 10M   INFO   DatasetProcessor         (dataset_processor.cpp     : 153)   Running bwa mem ...:/home/harbj019/miniconda3/envs/tormes-beta/bin/spades-bwa mem  -v 1 -t 8  /home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/assembly/623K_assembly/misc/assembled_contigs.fasta /home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/cleaned_reads/623K.ok_1.fastq.gz /home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/cleaned_reads/623K.ok_2.fastq.gz   > /home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/assembly/623K_assembly/tmp/corrector_0xmj88c9/lib0_MZoNRZ/tmp.sam
Segmentation fault (core dumped)
  0:00:02.835     1M / 10M   INFO   DatasetProcessor         (dataset_processor.cpp     : 156)   bwa failed, skipping sublib
  0:00:02.836     1M / 10M   ERROR  DatasetProcessor         (dataset_processor.cpp     : 205)   Failed to align paired reads /home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/cleaned_reads/623K.ok_1.fastq.gz /home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/cleaned_reads/623K.ok_2.fastq.gz
== Error ==  system call for: "['/home/harbj019/miniconda3/envs/tormes-beta/bin/spades-corrector-core', '/home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/assembly/623K_assembly/mismatch_corrector/contigs/configs/corrector.info', '/home/harbj019/results/Klebsiella/klebbetatest/klebtormestest/assembly/623K_assembly/misc/assembled_contigs.fasta']" finished abnormally, OS return value: 2
In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

**Comment by asl** [comment]
Well, it's likely that something is wrong with your systems as this is highly unlikely that these tools crash randomly. Maybe faulty RAM or something like this?

**Comment by biobrad** [comment]
Yes. I am starting to wonder if this could be the issue.

**Comment by biobrad** [comment]
Please mark this issue as resolved.

Indeed it was an error on my end. My bios settings for my RAM was incorrect for the capabilities of my motherboard. should have been 2667 instead of 3200. 

I have adjusted it and now Spades is running without issue.

Thanks for your time and the brilliant spades pipeline. Still the best assembler I have used!

cheers
Brad

**Comment by asl** [comment]
Oh great, that SPAdes was useful as a memory test ;)
