### ISSUE TITLE
Input reads in fasta format to spades

### ISSUE THREAD

**Issue by azrasid** [ablab/spades#712]
HI 
Is it possible to give fasta input reads to Spades?
My reads are in fast file format. 

Regards,Azra

**Comment by asl** [comment]
Sure: https://cab.spbu.ru/files/release3.15.2/manual.html#sec3.1

**Comment by SoSongzhi** [comment]
HI
Is it possible to give fasta input reads to Spades?
My reads are in fasta file format.

Regards,Azra
