### ISSUE TITLE
== Error ==  system call for: "['/home/wang/program/SPAdes-3.15.2/bin/spades-core', '/home/wang/desktop/ZGC1-wxj/a/K77/configs/config.info']" finished abnormally, OS return value: -8

### ISSUE THREAD

**Issue by wang-10000** [ablab/spades#714]
== Error ==  system call for: "['/home/wang/program/SPAdes-3.15.2/bin/spades-core', '/home/wang/desktop/ZGC1-wxj/a/K77/configs/config.info']" finished abnormally, OS return value: -8 
[params.txt](https://github.com/ablab/spades/files/6322481/params.txt)
[spades.log](https://github.com/ablab/spades/files/6322482/spades.log)

**Comment by asl** [comment]
Does the problem reproduce with `--isolate`? How much free RAM is available for your SPAdes job?

**Comment by wang-10000** [comment]
> Does the problem reproduce with `--isolate`? How much free RAM is available for your SPAdes job?

thanks for your reply.  my pc has 16G free RAM for this job.It's a small project, I ran this program successfully  before adding nanopore data. I will try --isolate option later to see if this issue comes again.

**Comment by asl** [comment]
Well, it's likely an OOM situation.

**Comment by wang-10000** [comment]
hello @asl , sure, the memory is not enough.  I run it successfully with another machine which have 64G free memory. Thanks  for your supports.
