### ISSUE TITLE
== Error ==  exception caught: <class 'ValueError'>

### ISSUE THREAD

**Issue by atduggan** [ablab/spades#715]
Hi,

I'm trying to build an assembly limited to only short reads that were merged.  I'm having difficulties finding the error source. I have tried various iterations with and without the --careful and --only-assembler flags but the error log seems to be the same each time. I have checked the input file, it is not empty, I have tried feeding it to SPAdes 3.15.2 both in compressed and uncompressed forms.

[spades.log](https://github.com/ablab/spades/files/6327165/spades.log)
[params.txt](https://github.com/ablab/spades/files/6327167/params.txt)

Any insights welcome.

Thanks.

**Comment by asl** [comment]
You cannot use merged things alone w/o paired-end ones. The error message will be improved though.

**Comment by atduggan** [comment]
Thank you, Anton!
