### ISSUE TITLE
Memory consumption 

### ISSUE THREAD

**Issue by daydayup-echo** [ablab/spades#718]
Hello, SPAdes team
When I actually use SPAdes for assembly, I found that it consumes a lot of memory. As far as I know, SPAdes currently supports OPENMP parallelism. Does SPAdes support MPI cross-node parallelism? This can relieve memory pressure. I found in the issue that SPAdes did not support MPI a few years ago, and now I found a few MPI parallel flag statements in the SPAdes source code. If it is already supported, how can I use the MPI-based parallel SPAdes program in my project?
Looking forward to your answers. Thank you.

**Comment by asl** [comment]
Hello

Using MPI will not reduce the amount of required memory. You could give and experimental work-in-progress hpcSPAdes (https://cab.spbu.ru/software/hpcspades/) a try, however, the memory consumption at the peak points is roughly the same.
