### ISSUE TITLE
Guidance for --threads

### ISSUE THREAD

**Issue by cbird808** [ablab/spades#719]
Can more specific guidance be given on the number of threads to allocate to `spades`?  

I've read the manual and searched the issues.  The default is 16.  Is that optimal?  Is that the max `spades` can take advantage of? If I give it 40 threads, will it be able to use them or am I unnecessarily hogging up resources on the hpc?

**Comment by asl** [comment]
There is no particular magic recipe on the # threads. Some stages of SPAdes are inherently parallel and therefore could use all available threads, some will be I/O bound and some are single-threaded. But the generic advice is the more – the better.

**Comment by cbird808** [comment]
perfect, thank you!
