### ISSUE TITLE
Probelm with spades 3.15.2 and ubuntu 20.04 with python 3.8.5

### ISSUE THREAD

**Issue by musa90** [ablab/spades#723]
I facing some problem with new version of Spades 3.15.2, I think it is not works on Ubuntu 20.04 with python 3.8.5. 
The default version of Spades 3.13.1 on Ubuntu 20.04 works fine with no error.
Also when I tried to Install Spades with conda, spades 3.13.1 was the proposed version. But when I tried to install with conda on virtual environment with python 2.7 the proposed version was 3.15.2, but unfortunately result was like manual installation of version 3.15.2. The --test says: TEST PASSED CORRECTLY. but there is no fasta file.
could you please tell me which version of python is preferred for Spades 3.15.2?
is it possible to provide docker version of the Spades 3.15.2?

**Comment by asl** [comment]
Hello

I still do not follow what the problem is. There is no specific python version requirement for SPAdes it works with 3.8.5.
There are pre-built binaries available at https://cab.spbu.ru/software/spades/

**Comment by asl** [comment]
Please reopen if this is still an issue
