### ISSUE TITLE
mmap(2) failed. Reason: Cannot allocate memory. Error code: 12

### ISSUE THREAD

**Issue by charles-gumbi** [ablab/spades#725]
Dear spades support team 
Thank you for providing and maintaining the spades module. I have been having trouble with using the module to assembly Illumina paired-end reads. I am running the module in a cluster server. The log file suggests that this is an insufficient memory error however I have over 3 Terabytes in my account on the server, so I do not know how this could be an insufficient memory error. I have a feeling there is more to this error than I can interpret from the log file. I have attached the log file from my runs and the slurm script. could you please help me decipher this error?. Any suggestions or assistance would be highly appreciated.
[spades.log](https://github.com/ablab/spades/files/6414990/spades.log)

Humble regards
Bonginkosi

**Comment by asl** [comment]
Hello

The log reads:
```
  9:15:19.038  2453M / 2453M ERROR   General                 (kmer_splitter.hpp         : 150)   I/O error! Incomplete write! Reason: Disk quota exceeded. Error code: 122
```

So, it's not related to out of memory.

In addition to this, not that you're running SPAdes using 250 Gb of RAM memory limit.

**Comment by charles-gumbi** [comment]
Thanks for the swift response. But how can I fix this error? , do I need more/less  RAM?  or maybe there is something wrong with the file system in the server?
charles

**Comment by asl** [comment]
The error message says about "Disk quota exceeded.", so not related to RAM at all. Talk to your system administrator about quotas, etc.

**Comment by charles-gumbi** [comment]
Thank you asl I appreciate the help. 
charles
