### ISSUE TITLE
More pe150 sequences = worse assembly in a marine fish

### ISSUE THREAD

**Issue by cbird808** [ablab/spades#726]
Hi,

I've encountered a curious result that I'm hoping can be explained: the assembly made with more Illumina pe150 sequence scores worse than the assembly with a subset of sequences.  

The quast output files are attached.  The file with `all` in the name has all 9 shotgun libraries we made from the same individual.  The file with `500` in the name has 1 of those 9 shotgun libraries and was constructed from 500ng of genomic DNA.  These data were first trimmed with `fastp` (we utilized all available filters and removed reads < 140 bp) and had optical and PCR duplicates removed with `clumpify.sh`.  These assemblies were made from reads that were not further filtered for contaminant DNA (vectors, virus, proks, fungi, etc) with fastq_screen, but I have those and the results are similar. There's not much putative contaminant DNA in any of the libs. 

[quast-report_scaffolds_Hte_all_spades_contam_R1R2ORPH_21-99_noisolate.txt](https://github.com/ablab/spades/files/6424948/quast-report_scaffolds_Hte_all_spades_contam_R1R2ORPH_21-99_noisolate.txt)
[quast-report_scaffolds_Hte_500_spades_contam_R1R2ORPH_21-99_noisolate.txt](https://github.com/ablab/spades/files/6424949/quast-report_scaffolds_Hte_500_spades_contam_R1R2ORPH_21-99_noisolate.txt)

[spades_Hte-C_500_R1R2ORPH_contam_noisolate.log](https://github.com/ablab/spades/files/6427013/spades_Hte-C_500_R1R2ORPH_contam_noisolate.log)
[spades_Hte-C_all_R1R2ORPH_contam_noisolate.log](https://github.com/ablab/spades/files/6427014/spades_Hte-C_all_R1R2ORPH_contam_noisolate.log)

This is the script that was run for the single library assembly (500)
```
#!/bin/bash -l
#SBATCH --job-name=sp8sHte500
#SBATCH -o sp8s_hte_500_contam_noisolate-%j.out
#SBATCH --time=00:00:00
#SBATCH -p main
#SBATCH --ntasks=40
enable_lmod
module load container_env pire_genome_assembly/2021.03.25
export SINGULARITY_BIND=/home/e1garcia

PROJDIR=/home/cbird/pire_shotgun/hte_spades
FQDIR=/home/e1garcia/shotgun_PIRE/fq_4denovo_fp1_clmp_fp2
TEMPDIR=/scratch/cbird
OUTDIR=$PROJDIR/out_Hte-C_500_R1R2ORPH_contam_noisolate
FQPATTERN=*NoWGA_Hte-CTic_NR_500*  #determines libraries to be assembled
THREADS=40

# assemble genome
crun spades.py \
-k 21,33,55,77,99 \
--pe1-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n1) \
--pe1-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n1) \
--pe1-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n1) \
--threads $THREADS \
--memory 750 \
--tmp-dir $TEMPDIR \
--cov-cutoff auto \
-o $OUTDIR
```

This is the script that was used to assemble all 9 libraries (all).
```
#!/bin/bash -l
#SBATCH --job-name=sp8sHteCnAll
#SBATCH -o sp8s_hte_all_contam_noisolate-%j.out
#SBATCH --time=00:00:00
#SBATCH -p himem
#SBATCH --exclusive
#SBATCH --ntasks=32
enable_lmod
module load container_env pire_genome_assembly/2021.03.25
export SINGULARITY_BIND=/home/e1garcia

PROJDIR=/home/cbird/pire_shotgun/hte_spades
FQDIR=/home/e1garcia/shotgun_PIRE/fq_4denovo_fp1_clmp_fp2
TEMPDIR=/scratch-lustre/cbird
OUTDIR=$PROJDIR/out_Hte-C_all_R1R2ORPH_contam_noisolate
FQPATTERN=*NoWGA_Hte-CTic*  #determines libraries to be assembled
THREADS=32

# assemble genome
crun spades.py \
-k 21,33,55,77,99 \
--pe1-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n1) \
--pe1-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n1) \
--pe1-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n1) \
--pe2-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n2 | tail -n1) \
--pe2-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n2 | tail -n1) \
--pe2-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n2 | tail -n1) \
--pe3-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n3 | tail -n1) \
--pe3-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n3 | tail -n1) \
--pe3-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n3 | tail -n1) \
--pe4-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n4 | tail -n1) \
--pe4-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n4 | tail -n1) \
--pe4-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n4 | tail -n1) \
--pe5-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n5 | tail -n1) \
--pe5-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n5 | tail -n1) \
--pe5-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n5 | tail -n1) \
--pe6-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n6 | tail -n1) \
--pe6-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n6 | tail -n1) \
--pe6-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n6 | tail -n1) \
--pe7-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n7 | tail -n1) \
--pe7-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n7 | tail -n1) \
--pe7-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n7 | tail -n1) \
--pe8-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n8 | tail -n1) \
--pe8-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n8 | tail -n1) \
--pe8-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n8 | tail -n1) \
--pe9-1 $(ls $FQDIR/${FQPATTERN}r1.fq* | head -n9 | tail -n1) \
--pe9-2 $(ls $FQDIR/${FQPATTERN}r2.fq* | head -n9 | tail -n1) \
--pe9-s $(ls $FQDIR/${FQPATTERN}orph.fq* | head -n9 | tail -n1) \
--threads $THREADS \
--memory 750 \
--tmp-dir $TEMPDIR \
--cov-cutoff auto \
-o $OUTDIR
```

Any ideas and/or feedback are much appreciated!

**Comment by cbird808** [comment]
BUSCO results indicate the assembly with more reads has more duplicated buscos:

All 9 libraries
```
	***** Results: *****

	C:78.2%[S:22.0%,D:56.2%],F:8.7%,M:13.1%,n:3640	   
	2847	Complete BUSCOs (C)			   
	800	Complete and single-copy BUSCOs (S)	   
	2047	Complete and duplicated BUSCOs (D)	   
	318	Fragmented BUSCOs (F)			   
	475	Missing BUSCOs (M)			   
	3640	Total BUSCO groups searched		
```   

1 of 9 libraries
```
	***** Results: *****

	C:73.2%[S:72.3%,D:0.9%],F:10.3%,M:16.5%,n:3640	   
	2664	Complete BUSCOs (C)			   
	2633	Complete and single-copy BUSCOs (S)	   
	31	Complete and duplicated BUSCOs (D)	   
	375	Fragmented BUSCOs (F)			   
	601	Missing BUSCOs (M)			   
```

**Comment by asl** [comment]
Will you please attach spades.log files from the both runs?

**Comment by cbird808** [comment]
done, I attached them in orig msg above

**Comment by asl** [comment]
Well, as far as I can see, your datasets have quite an uneven coverage with many coverage gaps. As a result, SPAdes might not detect various coverage thresholds properly and switched to a conservative strategy. Furthermore, you used automatic coverage threshold filtering (which in general makes sense only in the case of even coverage). This option did not do anything on single library case due to overall low coverage, however, triggered for 9-library case.

As a result, I would expect fragmented assemblies in general and more fragmented assembly for 9-library case.

**Comment by cbird808** [comment]
Thank you for taking the time to look at this!  I'm inferring that your recommendation is to set `--cov-cutoff off`.
