### ISSUE TITLE
All or nothing busco results on PE libs from same individual, any way to adjust settings?

### ISSUE THREAD

**Issue by cbird808** [ablab/spades#728]
I've come across another curious result, in replicate libraries from the same individual, some spades assemblies yield ~90% complete buscos while other yield 0%.  First, you'll be happy to know that the "90% libraries" score better than the same libraries assembled with hipmer.  However, when the 0% libraries are assembled with `hipmer`, they may yield up to 25% complete buscos.  This is certainly a data issue, but I'm wondering if there's anything I can do to improve the assembly for libraries that generate a handful of complete buscos?  I know in a previous issue, you recommended that I not set the coverage parameter.  Would that be a solution here also?

This is a log from a 90% lib (you've already looked at this in my last post):
[spades_Hte-C_500_R1R2ORPH_contam_noisolate.log](https://github.com/ablab/spades/files/6429536/spades_Hte-C_500_R1R2ORPH_contam_noisolate.log)

This is a log from a 0% lib:
[spades_Hte-C_3NR_R1R2ORPH_contam_noisolate.log](https://github.com/ablab/spades/files/6429568/spades_Hte-C_3NR_R1R2ORPH_contam_noisolate.log)

Any guidance you can provide is much appreciated!

**Comment by asl** [comment]
You're having very unevenly and low-covered dataset. In the 0% lib case the coverage filtering essentially removed huge part of the assembly (I believe you could easily see this from the assembly length).

In general, I would suggest not to use any additional options unless you're 100% sure what you're doing. Assembling in metagenomic mode might also help, it has less dependence on the coverage, though, it has different aims.
