### ISSUE TITLE
Separate vs Concatenated Libraries?

### ISSUE THREAD

**Issue by cbird808** [ablab/spades#729]
Hi Anton, 

Will feeding libraries from the same individual to spades 1 by 1 versus concatenating them together trigger spades to make different decisions?  

For example, let us consider libraries A and B. They were both made from the same DNA extract from the same individual.  I can feed them to spades as:
```A.r1, A.r2, B.r1, B.r2```
or I could cat them and feed them to spades as: 
```AB.r1, AB.r2```

Hopefully this is my last question for a while as your advice has helped me improve the previously failing assemblies tremendously.  FWIW, I think that whether intentional or not, the behavior where assemblies completely fail when the settings are wrong for the data is a good feature for a "turnkey" assembler. 

Cheers,

Chris

**Comment by asl** [comment]
As explained in https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cpbi.102 and SPAdes manual (https://cab.spbu.ru/files/release3.15.2/manual.html#sec3.1) the sequencing libraries are distinguished by insert size distribution. If it is the same, then it's the same library.
