### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by vyom84** [ablab/spades#730]
Hi,
    I am running a big assembly and keep getting the following error. I check with our IT guys and they didn't see any input-output errors on the grid machine, I am running the job.
[spades.log](https://github.com/ablab/spades/files/6436785/spades.log)
[params.txt](https://github.com/ablab/spades/files/6436786/params.txt)

spades-hammer: /spades/assembler/src/common/utils/kmer_mph/kmer_index_builder.hpp:205: size_t utils::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&) [with Seq = Seq<21ul>; traits = utils::kmer_index_traits<Seq<21ul> >; size_t = long unsigned int; std::string = std::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed.

== Error ==  system call for: "['/local/ifs2_devel/ANNOTATION/hsingh/anaconda3/share/spades-3.13.0-0/bin/spades-hammer', '/local/ifs3_scratch/EUK/hsing/bbmap/assembly5C7/corrected/configs/config.info']" finished abnormally, err code: -6

Please suggest what to do. I have run different assemblies while doing subsampling of the data from 70% to 50% and still the same error.

I have more question, I am running jobs on a 1TB memory server and spades file do show memory given is 1TB, but kmer_splitters say only ~154GB is available for splitting. Can you please explain it.

 57:18:25.538    81G / 81G   INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 153.154 Gb

Does the memory requirement increasing with an increase in the number of threads or remain same.

**Comment by asl** [comment]
One of SPAdes intermediate files got corrupted due to I/O problems on your end. So you might really want to ask your HPC folks harder.

I would strongly suggest you to giver SPAdes 3.15.2 a try, 3.13.0 is more than 2.5 years old. Also, running the assembly of such size using only 2 threads is a bit... painful and might be unwise :)

**Comment by vyom84** [comment]
Thanks for the response. I initially tried with 16 threads (but failed) and can go higher, but I am not sure about the memory requirement as my input files are in big ~350GB. Does the memory requirement remain the same with 16, 32, or 64 threads as compared to a single thread. I asked IT to install the 3.15.2.

**Comment by asl** [comment]
Well... the memory consumption could be higher with more threads, but not that much.
