### ISSUE TITLE
Error on High Sierra: spades(11478,0x7fffa2687340) malloc: *** malloc_zone_unregister() failed for 0x7fffa2678000

### ISSUE THREAD

**Issue by cmkeg** [ablab/spades#74]
After trying to run spades on High Sierra I get an error when running the installation test. Error at bottom.

Command line: /Users/christiankeggi/SPAdes-3.9.0-Darwin/bin/spades.py	--test	

System information:
  SPAdes version: 3.9.0
  Python version: 2.7.10
  OS: Darwin-17.3.0-x86_64-i386-64bit

Output dir: /Users/christiankeggi/Documents/P_amylolyticus_fastq_files/ssuRNA_extraction/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/Users/christiankeggi/SPAdes-3.9.0-Darwin/share/spades/test_dataset/ecoli_1K_1.fq.gz']
      right reads: ['/Users/christiankeggi/SPAdes-3.9.0-Darwin/share/spades/test_dataset/ecoli_1K_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed (with gzip)
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /Users/christiankeggi/Documents/P_amylolyticus_fastq_files/ssuRNA_extraction/spades_test/tmp
  Threads: 16
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /Users/christiankeggi/Documents/P_amylolyticus_fastq_files/ssuRNA_extraction/spades_test/spades.log

===== Read error correction started. 

== Running read error correction tool: /Users/christiankeggi/SPAdes-3.9.0-Darwin/bin/hammer /Users/christiankeggi/Documents/P_amylolyticus_fastq_files/ssuRNA_extraction/spades_test/corrected/configs/config.info

hammer(11472,0x7fffa2687340) malloc: *** malloc_zone_unregister() failed for 0x7fffa2678000

**Comment by asl** [comment]
Please upgrade to the latest SPAdes 3.11.1
