### ISSUE TITLE
<jemalloc>: Error in malloc(): out of memory. 

### ISSUE THREAD

**Issue by ms201420201029** [ablab/spades#75]
== Error ==  system call for: "['/home/mas/software/SPAdes/SPAdes-3.11.1-Linux/bin/hammer', '/data_center_10/Project/RY2017B20G01-1/03.assembly_metaSPAdes/assembly/HC14-P6/output/corrected/configs/config.info']" finished abnormally, err code: -6

**Comment by ms201420201029** [comment]
[spades.log](https://github.com/ablab/spades/files/1684292/spades.log)
[params.txt](https://github.com/ablab/spades/files/1684291/params.txt)
these are the log files.

**Comment by asl** [comment]
So, per error message - you're running out of RAM. Please make sure that enough free RAM is available for your SPAdes job. Here SPAdes used 34 Gb of RAM and your OS failed to fulfill its request to allocate 6 Gb more.

**Comment by ms201420201029** [comment]
Thank you for your reply. Here is another problem. Is it also memory issue?
[params.txt](https://github.com/ablab/spades/files/1687939/params.txt)
[spades.log](https://github.com/ablab/spades/files/1687940/spades.log)

**Comment by asl** [comment]
Let us read the log. The error message reads:

```
Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```
