### ISSUE TITLE
Error : you cannot specify any data types except a single paired-end library

### ISSUE THREAD

**Issue by fujch7** [ablab/spades#762]
Hi,
    Thanks for your amazing tools.
    I tried to perform metagenome assembly using 6 samples clean reads. The command line is as below:
spades.py --meta --pe1-1 /clean/S48-0h.R1.fq --pe2-1 /clean/S48-4-1d.R1.fq --pe3-1 /clean/S48-4-1h.R1.fq --pe4-1 /clean/S48-4-7d.R1.fq --pe5-1/clean/S48-4-15d.R1.fq --pe6-1 /clean/S48-4-29d.R1.fq --pe1-2 /clean/S48-0h.R2.fq --pe2-2 /clean/S48-4-1d.R2.fq --pe3-2 /clean/S48-4-1h.R2.fq --pe4-2 /clean/S48-4-7d.R2.fq --pe5-2 /clean/S48-4-15d.R2.fq --pe6-2 /clean/S48-4-29d.R2.fq -o /clean/spadesAssembly/ >> assembly.log
    And it raised an error:
== Error ==  you cannot specify any data types except a single paired-end library (optionally accompanied by a single library of TSLR-contigs, or PacBio reads, or Nanopore reads) in metaSPAdes mode!
    I did not specify any mode.
    The version is SPAdes genome assembler v3.13.0.

**Comment by asl** [comment]
> I did not specify any mode.

Apparently you did: watch for `--meta` flag in your cmdline.

metaSPAdes options are documented in the manual (https://cab.spbu.ru/files/release3.15.2/manual.html#sec3.2)

PS: SPAdes 3.13 is very old and known to contain issues
