### ISSUE TITLE
== Error ==  exception caught: <class 'OSError'>

### ISSUE THREAD

**Issue by BenjaminJPerry** [ablab/spades#763]
I had this error reported after running SPAdes --metaviral:
"
===== Terminate finished. 

 * Assembled contigs are in /home/perbe24p/gobyBench/SPAdes-metaViral/contigs.fasta
 * Assembled scaffolds are in /home/perbe24p/gobyBench/SPAdes-metaViral/scaffolds.fasta
[Errno 5] Input/output error
Traceback (most recent call last):
  File "/home/perbe24p/tools/spades/bin/spades.py", line 621, in main
    if not support.log_warnings(log):
  File "/home/perbe24p/tools/spades/share/spades/spades_pipeline/support.py", line 434, in log_warnings
    h.flush()
  File "/home/perbe24p/miniconda3/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
OSError: [Errno 5] Input/output error

== Error ==  exception caught: <class 'OSError'>

SPAdes log can be found here: /home/perbe24p/gobyBench/SPAdes-metaViral/spades.log

Thank you for using SPAdes!
"

I am unsure of what it means.

I a using:
"
(base) [perbe24p@almeida SPAdes-metaViral]$ spades.py -v
SPAdes genome assembler v3.15.2
"

**Comment by asl** [comment]
Hello

It looks like an I/O error on your end. Please consider restarting SPADes
