### ISSUE TITLE
Issue running spades 3.11.1 /err code -9)

### ISSUE THREAD

**Issue by Momosandy** [ablab/spades#77]
[params.txt](https://github.com/ablab/spades/files/1693296/params.txt)
[spades.log](https://github.com/ablab/spades/files/1693297/spades.log)

I have used the error correction tools, implemented in Spades, on ITS amplicon data generated on Mi-seq platform previously and concluded its usefulness. I am analysing a new dataset and planning to do the same, unfortunately, this time after several trials,  the analysis stops with an error -9, I tried to look for this, without much success of finding a solution, except that it is related to the memory space (?). I Could anyone help me in figuring out exactly if the problem is related to memory space or storage space for the temp. files? For more details, I  am attaching the log and the param files. 

== Error ==  system call for: "['/cluster/software/VERSIONS/spades/3.11.0/bin/hammer', '/projects/clusteringits/bioinfo1/sundy/bayeshammer/bhclustITS_sm_lib2/corr
ected/configs/config.info']" finished abnormally, err code: -9

Many thanks 

Sandy
Yes I have also emailed the support

**Comment by asl** [comment]
Most probably your job was killed by cluster scheduler due to insufficient RAM. Same answered via e-mail.
