### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range' (K55)

### ISSUE THREAD

**Issue by ZhangZhenmiao** [ablab/spades#770]
Hi,

The spades-core in K55 failed after throwing an error "what():  basic_string::substr: __pos (which is 581) > this->size() (which is 580)". I have seen a similar issue #603, but in my case, the spades program passed read error correction normally (I have done read error correction before running spades with --only-assembler).

[params.txt](https://github.com/ablab/spades/files/6551641/params.txt)
[spades.log](https://github.com/ablab/spades/files/6551642/spades.log)

Thanks!
Zhenmiao

**Comment by asl** [comment]
Hello

Will it be possibly for you to share your trusted contigs with us?

**Comment by ZhangZhenmiao** [comment]
Yes, here is the trusted contigs:

https://drive.google.com/file/d/1oNHJW_-gylWZyBYGvc2upZPT0-QD68AT/view?usp=sharing

**Comment by asl** [comment]
Hello

I believe the issue was fixed in SPAdes 3.15.3 Please reopen if this is still an issue
