### ISSUE TITLE
metaSPADES error, finished abnormally, OS return value: -11

### ISSUE THREAD

**Issue by cedrickalguzar** [ablab/spades#772]
Hello. I was running metaspades in Ubuntu for de novo assembly and co-assembly. However, this error is what I always get:

== Error ==  system call for: "['/opt/spades/SPAdes-3.14.1-Linux/bin/spades-core', '/opt/data/assembly/K21/configs/config.info', '/opt/data/assembly/K21/configs/mda_mode.info', '/opt/data/assembly/K21/configs/meta_mode.info']" finished abnormally, OS return value: -11

Does anyone here know how to fix this issue?

Thank you!

**Comment by asl** [comment]
Maybe

But first step is to attach the files mentioned in the error message.

**Comment by cedrickalguzar** [comment]
> Maybe
> 
> But first step is to attach the files mentioned in the error message.

**Comment by cedrickalguzar** [comment]
Here they are.

[params.txt](https://github.com/ablab/spades/files/6558977/params.txt)
[spades.log](https://github.com/ablab/spades/files/6558978/spades.log)

**Comment by asl** [comment]
So, per SPAdes manual (https://cab.spbu.ru/files/release3.15.2/manual.html#sec2) SPAdes requires Linux or Mac OS system to run. You're running it under WSL which is not Linux (despite all marketing claims). This is completely unsupported platform, we neither release, nor test SPAdes on it, the precompiled binaries will not work there.

You might want to recompile SPAdes from sources (https://cab.spbu.ru/files/release3.15.2/manual.html#sec2.3), other people had some success in running SPAdes there, but your mileage might certainly vary.

**Comment by cedrickalguzar** [comment]
@asl I didn't know this. This is my first time using this platform. Anyway, I will do your suggestions. Thank you!
