### ISSUE TITLE
paired end reads and unpaired reads for spades

### ISSUE THREAD

**Issue by pdhrati02** [ablab/spades#775]
Hi, I ran kneaddata and the kneaddata output has unmatched_1.fq and unmatched_2.fq which are reads whose mates are lost but they themselves passed both trimming and filtering step and then there is paired1.fq and paired2.fq (which are paired reads). 

In this case can one use metaspades with all the 4 files? like -1 paired1.fq -2 paired2.fq -s unmatched_1.fq -s unmatched_2.fq 
Is it possible to use the unpaired read option twice? Or would you suggest merging them into a single file? 

Or would you advice against it? 

Thanks in advance

**Comment by asl** [comment]
Yes, you can specify -s multiple times
