### ISSUE TITLE
SPAdes 3.15.2 on macOS 10.11: OS return value -5

### ISSUE THREAD

**Issue by Nibby** [ablab/spades#776]
Running SPAdes under macOS 10.11 fails with the following message:
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime 
Referenced from: (path redacted)/SPAdes-3.15.2-Darwin/bin/spades-ionhammer 
Expected in: /usr/lib/libSystem.B.dylib 

dyld: Symbol not found: _clock_gettime 
Referenced from: (path redacted)/SPAdes-3.15.2-Darwin/bin/spades-ionhammer 
Expected in: /usr/lib/libSystem.B.dylib  

== Error == 
system call for: "['(path redacted)/SPAdes-3.15.2-Darwin/bin/spades-ionhammer', '(path redacted)/ionhammer.cfg']" finished abnormally, OS return value: -5
```
Seems like it is compiled in a newer version of macOS which uses headers not in the old versions. It was not immediately clear because the supported OS only mentions 64-bit macOS.

**Comment by asl** [comment]
Hello

Unfortunately it is not possible to provide binaries that are uniformly compatible with many MacOS versions, especially with old deprecated ones (last version of 10.11 was released in 2016).

Feel free to compile from sources, if you need binaries for old versions
