### ISSUE TITLE
metaSPAdes error with err code 255

### ISSUE THREAD

**Issue by Chauncy-Fang** [ablab/spades#777]
Hey, recently I used SPAdes to assembly a metagenome, but it always show me the error, even if I grow the threads to 64 and the memory limits to 500 Gb. Could you help me deal with this problem?  The log and txt are below.
**spades.log**
`Command line: /ifs1/Grp1/sunruanyang/miniconda3/envs/nanopore/bin/spades.py	-m	500	-t	64	-1	/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_1.fq.gz	-2	/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_2.fq.gz	-o	/ifs1/Grp1/sunruanyang/fc/rawdata/output	--meta	

System information:
  SPAdes version: 3.13.0
  Python version: 3.6.12
  OS: Linux-3.10.0-1062.el7.x86_64-x86_64-with-centos-7.7.1908-Core

Output dir: /ifs1/Grp1/sunruanyang/fc/rawdata/output
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_1.fq.gz']
      right reads: ['/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /ifs1/Grp1/sunruanyang/fc/rawdata/output/tmp
  Threads: 64
  Memory limit (in Gb): 500

======= SPAdes pipeline started. Log can be found here: /ifs1/Grp1/sunruanyang/fc/rawdata/output/spades.log

===== Read error correction started. 

== Running read error correction tool: /ifs1/Grp1/sunruanyang/miniconda3/envs/nanopore/share/spades-3.13.0-0/bin/spades-hammer /ifs1/Grp1/sunruanyang/fc/rawdata/output/corrected/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.13.0, git revision 8ea46659e9b2aca35444a808db550ac333006f8b
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from /ifs1/Grp1/sunruanyang/fc/rawdata/output/corrected/configs/config.info
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 64
  0:00:00.000     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 500 Gb
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.001     4M / 4M    INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.001     4M / 4M    INFO    General                 (hammer_tools.cpp          :  36)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.001     4M / 4M    INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.001     4M / 4M    INFO   K-mer Counting           (kmer_data.cpp             : 280)   Estimating k-mer count
  0:00:00.444     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 285)   Processing /ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_1.fq.gz
  0:03:53.131     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 294)   Processed 31282760 reads
  0:03:53.132     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 285)   Processing /ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_2.fq.gz
  0:07:58.622     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 294)   Processed 62565520 reads
  0:07:58.624     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 299)   Total 62565520 reads processed
  0:08:07.519     1G / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 306)   Estimated 6126953647 distinct kmers
  0:08:07.937   256M / 1G    INFO   K-mer Counting           (kmer_data.cpp             : 311)   Filtering singleton k-mers
42 8 0
nslots: 17179869184
bits per slot: 8 range: 0000040000000000
  0:08:07.938    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_1.fq.gz
  0:50:45.983    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 326)   Processed 31282760 reads
  0:50:45.984    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 317)   Processing /ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_2.fq.gz
  1:30:30.545    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 326)   Processed 62565520 reads
  1:30:30.545    20G / 20G   INFO   K-mer Counting           (kmer_data.cpp             : 331)   Total 62565520 reads processed
  1:30:30.546    20G / 20G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 301)   Building kmer index
  1:30:30.546    20G / 20G   INFO    General                 (kmer_index_builder.hpp    : 117)   Splitting kmer instances into 1024 files using 64 threads. This might take a while.
  1:30:30.547    20G / 20G   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1152
  1:30:30.547    20G / 20G   INFO    General                 (kmer_splitters.hpp        :  89)   Memory available for splitting buffers: 2.49727 Gb
  1:30:30.547    20G / 20G   INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 65536
  1:30:30.697    55G / 55G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_1.fq.gz
  1:32:48.302    55G / 57G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 16933451 reads
  1:35:02.678    55G / 57G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 31282760 reads
  1:35:02.678    55G / 57G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_2.fq.gz
  1:36:50.247    55G / 57G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 42670407 reads
  1:38:31.688    57G / 57G   ERROR   General                 (kmer_splitters.hpp        : 145)   I/O error! Incomplete write! Reason: Disk quota exceeded. Error code: 122

== Error ==  system call for: "['/ifs1/Grp1/sunruanyang/miniconda3/envs/nanopore/share/spades-3.13.0-0/bin/spades-hammer', '/ifs1/Grp1/sunruanyang/fc/rawdata/output/corrected/configs/config.info']" finished abnormally, err code: 255

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.`

**params.txt**
`Command line: /ifs1/Grp1/sunruanyang/miniconda3/envs/nanopore/bin/spades.py	-m	500	-t	64	-1	/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_1.fq.gz	-2	/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_2.fq.gz	-o	/ifs1/Grp1/sunruanyang/fc/rawdata/output	--meta	

System information:
  SPAdes version: 3.13.0
  Python version: 3.6.12
  OS: Linux-3.10.0-1062.el7.x86_64-x86_64-with-centos-7.7.1908-Core

Output dir: /ifs1/Grp1/sunruanyang/fc/rawdata/output
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_1.fq.gz']
      right reads: ['/ifs1/Grp1/sunruanyang/fc/rawdata/JHW1_BDME200006960-1a_2.fq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /ifs1/Grp1/sunruanyang/fc/rawdata/output/tmp
  Threads: 64
  Memory limit (in Gb): 500

`

**Comment by asl** [comment]
Let is read the log together:

```
1:38:31.688 57G / 57G ERROR General (kmer_splitters.hpp : 145) I/O error! Incomplete write! Reason: Disk quota exceeded. Error code: 122
```

Hopefully the problem is clear

**Comment by gurpreet2301** [comment]
> Let is read the log together:
> 
> ```
> 1:38:31.688 57G / 57G ERROR General (kmer_splitters.hpp : 145) I/O error! Incomplete write! Reason: Disk quota exceeded. Error code: 122
> ```
> 
> Hopefully the problem is clear

This problem persists even if there is enough space left. The issue is something else it seems. Please do not trivialize it!

**Comment by Chauncy-Fang** [comment]
已收到，谢谢！Email receiving!Thanks!

**Comment by asl** [comment]
> > Let is read the log together:
> > ```
> > 1:38:31.688 57G / 57G ERROR General (kmer_splitters.hpp : 145) I/O error! Incomplete write! Reason: Disk quota exceeded. Error code: 122
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hopefully the problem is clear
> 
> This problem persists even if there is enough space left. The issue is something else it seems. Please do not trivialize it!

Well, this is the error SPAdes receives from your operating system. The disk write failed and the reason was provided by the system. There is no way SPAdes could workaround the issue. You may want to check with your system administrator about quotas, etc.

**Comment by gurpreet2301** [comment]
I had 50 GB of space. I have now initiated a run whereby I have close to 20 TB of space to work on! I will update you. But it could easily be a bug in the software.
