### ISSUE TITLE
finished abnormally, OS return value: 21

### ISSUE THREAD

**Issue by ohan-Bioinfo** [ablab/spades#778]
cat spades.log
Command line: /home/fqahtani/miniconda3/bin/spades.py	-k	33	-m	200	--threads	48	-o	/home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33	-1	/home/fqahtani/Data/adult_female/Female_1_1.fastq	-2	/home/fqahtani/Data/adult_female/Female_1_2.fastq

System information:
  SPAdes version: 3.15.2
  Python version: 3.9.1
  OS: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17

Output dir: /home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/fqahtani/Data/adult_female/Female_1_1.fastq']
      right reads: ['/home/fqahtani/Data/adult_female/Female_1_2.fastq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [33]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33/tmp
  Threads: 48
  Memory limit (in Gb): 200

======= SPAdes pipeline started. Log can be found here: /home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33/spades.log

/home/fqahtani/Data/adult_female/Female_1_1.fastq: max reads length: 151
/home/fqahtani/Data/adult_female/Female_1_2.fastq: max reads length: 151

Reads length: 151

===== Before start started.

===== Read error correction started.

===== Read error correction started.

== Running: /home/fqahtani/miniconda3/bin/spades-hammer /home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33/corrected/configs/config.info

  0:00:00.000     1M / 20M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.005     1M / 20M   INFO    General                 (main.cpp                  :  76)   Loading config from /home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33/corrected/configs/config.info
  0:00:00.014     1M / 20M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 32
  0:00:00.019     1M / 20M   INFO    General                 (memory_limit.cpp          :  48)   Memory limit set to 200 Gb
  0:00:00.026     1M / 20M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.036     1M / 20M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.040     1M / 20M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.043     1M / 20M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.045     1M / 20M   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 32 threads. This might take a while.
  0:00:00.046     1M / 20M   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1024
  0:00:00.047     1M / 20M   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 2.08333 Gb
  0:00:00.047     1M / 20M   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 4194304
  0:00:00.301    19G / 19G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/fqahtani/Data/adult_female/Female_1_1.fastq
  0:01:08.877    19G / 29G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 7261711 reads
  0:02:19.093    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 14772055 reads
  0:03:27.485    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 22031526 reads
  0:04:37.863    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 29532439 reads
  0:05:47.810    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 37009790 reads
  0:06:55.710    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 44301219 reads
  0:08:05.192    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 51797391 reads
  0:09:14.832    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 59260297 reads
  0:10:23.381    19G / 30G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 66506982 reads
  0:11:33.583    19G / 31G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 74059121 reads
  0:12:42.721    19G / 31G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 81557603 reads
  0:13:51.644    19G / 31G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 89037505 reads
  0:17:26.385    19G / 31G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/fqahtani/Data/adult_female/Female_1_2.fastq
  0:21:00.086    19G / 31G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 134335969 reads
  0:35:31.244    19G / 31G   INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 223906948 reads processed
  0:35:31.266     1M / 31G   INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  1:52:49.113     1M / 62G   INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 5714951728 kmers in total.
  1:52:49.236     1M / 62G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  1:57:02.037  4035M / 62G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 5714951728 kmers, 4127716928 bytes occupied (5.77813 bits per kmer).
  1:57:02.060  4035M / 62G   ERROR  K-mer Counting           (kmer_data.cpp             : 349)   The reads contain too many k-mers to fit into available memory. You need approx. 212.899GB of free RAM to assemble your dataset

== Error ==  system call for: "['/home/fqahtani/miniconda3/bin/spades-hammer', '/home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33/corrected/configs/config.info']" finished abnormally, OS return value: 21

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/fqahtani/OutPut/SpadesOut/Spadesoutfile_OnePaired/K33/spades.log

Thank you for using SPAdes!

can anyone Help please, I made the run multiple time with different parameters but every time I have different error mostly -9 but this time is 21

**Comment by asl** [comment]
Let us read the log together:

```
1:57:02.060 4035M / 62G ERROR K-mer Counting (kmer_data.cpp : 349) The reads contain too many k-mers to fit into available memory. You need approx. 212.899GB of free RAM to assemble your dataset
```

Hope the problem is clear now
