### ISSUE TITLE
finished abnormally, err code: 255

### ISSUE THREAD

**Issue by utritala** [ablab/spades#779]
Hi there,

I am trying to run SPAdes on a short read Illumina dataset. My command is given below: 
`"SPAdes-3.11.1-Linux/bin/spades.py -1 R1.fastq.gz -2 R2.fastq.gz -t 16 -m 200 --cov-cutoff auto -o spades_SR"`

But it throws an error: 
```
== Error ==  system call for: "['SPAdes-3.11.1-Linux/bin/hammer', 'spades_SR/corrected/configs/config.info']
" finished abnormally, err code: 255
```
Following the previous threads with similar errors, I checked my files and they are definitely not corrupted. What else could be going wrong? Really appreciate any help you could provide. 

Thanks.

**Comment by asl** [comment]
Will you please read the error message (just around this github link) and provide the files mentioned there? Thanks!

**Comment by utritala** [comment]
Thanks for your response. Sorry, I missed that earlier. Please find these files attached.
[params.txt](https://github.com/ablab/spades/files/6594298/params.txt)
[spades.log](https://github.com/ablab/spades/files/6594299/spades.log)

**Comment by asl** [comment]
The log reads:

```
 71:31:05.478     5G / 5G    ERROR  K-mer Counting           (kmer_data.cpp             : 354)   The reads contain too many k-mers to fit into available memory. You need approx. 417.038GB of free RAM to assemble your dataset
```

**Comment by Fum-Abuah** [comment]
Hey, so what would you suggest is the best way to solve this problem
