### ISSUE TITLE
Spades Error :  finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by Solyris83** [ablab/spades#780]
Hi, I am running Spades on Ubuntu 20.4 and it has failed multiple times with error message found below.

== Error ==  system call for: "['/home/ubuntu/software/SPAdes-3.15.2-Linux/bin/spades-core', '/mnt/volume2/test_spades/K55/configs/config.info', '/mnt/volume2/test_spades/K55/configs/mda_mode.info', '/mnt/volume2/test_spades/K55/configs/meta_mode.info']" finished abnormally, OS return value: -9

Needed log and param.txt file attached herein.
[spades_troubleshooting.zip](https://github.com/ablab/spades/files/6595159/spades_troubleshooting.zip)

Please advise on issue.

Thanks and regards
Li

**Comment by asl** [comment]
Your SPAdes job was killed. Likely due to out of RAM. You may want to check your system log.
