### ISSUE TITLE
Command not found on test run

### ISSUE THREAD

**Issue by Minhue** [ablab/spades#784]
Hi, I am trying to run SPAdes on google shell,
I followed the protocol but even the test run  <spades.py --test> does not run. It just says -bash: spades.py: command not found.

I spent hours trying to figure out what's wrong, but the information is quite limited. I would really appreciate your help,

Best,

Minhue

**Comment by asl** [comment]
Hello

Unfortunately, you have not specified which protocol you are using. You may want to ask the authors of protocol.

Likely you have not added SPAdes installation folder in your PATH and / or simply starting it incorrectly. In this case some basic Linux cmdline resources might provide necessary help

**Comment by asl** [comment]
Please reopen if this is still an issue
