### ISSUE TITLE
-6 Code Error During Assembly

### ISSUE THREAD

**Issue by leehwmj** [ablab/spades#787]
Hello

I am a user who used SPAdes through SqueezeMeta.
In the process of proceeding with assembly, SPAdes returned an error of -6 code.

We have already finished the Q&A with SqueezeMetaguys, and the guys concluded that it was an error on the SPAdes side.
(https://github.com/jtamames/SqueezeMeta/issues/304#issue-910160041)

The error code is as follows.
```
== Error == system call for: "['/home/hwlee/anaconda3/envs/SqueezeMeta/SqueezeMeta/bin/SPAdes/spades', '/home/hwlee/analysis/collect-temp-sequencing/HN00149294_Rawdata/HN00149294_RawData_squeezemeta_spades_2/data/spades/K21/configs/config.info', '/home/hwlee/analysis/collect-temp-sequencing/HN00149294_Rawdata/HN00149294_RawData_squeezemeta_spades_2/data/spades/K21/configs/mda_mode.info', '/home/hwlee/analysis/collect-temp-sequencing/HN00149294_Rawdata/HN00149294_RawData_squeezemeta_spades_2/data/spades/K21/configs/meta_mode.
```

I'm attaching two files.
[params.txt.zip](https://github.com/ablab/spades/files/6615495/params.txt.zip)
[spades.log.zip](https://github.com/ablab/spades/files/6615496/spades.log.zip)

I'd like to ask for a way to solve the problem.
If you need anything, you just let me know.

Thank you.

**Comment by asl** [comment]
Hello

One of SPAdes intermediate files got corrupted likely due to I/O error on your side. I would suggest you to contact your system administrator on this issue.

Also, you're using very old SPAdes 3.11, please consider upgrading to the latest SPAdes 3.15.2
