### ISSUE TITLE
Metaplasmidspades contigs that are NOT categorized as "plasmid"

### ISSUE THREAD

**Issue by ilkaybuysal** [ablab/spades#788]
Dear developers,

I'm comparing the plasmid prediction of Metaplasmidspades for known plasmid datasets and would like to calculate True negative(TN) and false negatives for the dataset.
Can we reach the contigs that Metaplasmidspades categorized as "non-plasmid"? 

Thanks in advance.

**Comment by asl** [comment]
Tagging @Dmitry-Antipov

**Comment by Dmitry-Antipov** [comment]
Hi.
Metaplasmidspades is not a plasmid classification tool. Plasmid assembly is improved with iterative removal of non-plasmid edges of the assembly graph. So we do not output non-plasmid sequences (not contigs, these sequences are removed before contig generation).

For the plasmid/nonplasmid classification I can suggest to use viralVerify ( https://github.com/ablab/viralVerify ) - it classifies contigs of viral, chromosomal and plasmid origin based on gene content.

**Comment by ilkaybuysal** [comment]
Hi,

Thanks a lot for the explanatory answer and the suggestion.
