### ISSUE TITLE
"Error: too many files open" while running rnaspades

### ISSUE THREAD

**Issue by shrhops** [ablab/spades#791]
Hello, I'm facing an error while trying to run rnaspades, where the program stops partway through due to "too many files being open". The error code is 255. spades.log and params.txt are attached here. 
[params.txt](https://github.com/ablab/spades/files/6650911/params.txt)
[spades.log](https://github.com/ablab/spades/files/6650912/spades.log)

**Comment by asl** [comment]
Hello

You need to contact your system administrator to increase the limit of # of files opened simultaneously. It seems it is too low.

We do not suggest the usage of SPAded 3.12 for RNA data, it contains lots of known problems and there were many improvements made afterwards. Consider upgrading to 3.15.2
