### ISSUE TITLE
Format of contigs.seq

### ISSUE THREAD

**Issue by balags1** [ablab/spades#792]
Once a genome assembly is completed, in some lower k's folders, for example K21 folder, there is a subfolder 'simplified contigs'. This contains a contigs.seq file. This does not appear to be text format file as would be expected. What exactly is the file's format? Can this be converted into a fasta format?

**Comment by asl** [comment]
Hello

These are internal SPAdes files and are not intended for external consumption. Please refer to SPAdes manual for information about SPAdes output: https://cab.spbu.ru/files/release3.15.2/manual.html#spadesoutsec

**Comment by balags1** [comment]
This however seems to have eliminated the simplified_contigs.fasta sequence output, is there a way to enable that output for the lower k's then?

**Comment by asl** [comment]
These files were always internal SPAdes files and did not represent any result of the assembly. Why do you need them?

**Comment by balags1** [comment]
Version 3.13.1 for example contained a simplified_contigs.fasta file, but you're saying this had nothing to do with the assemblies and were just internal files?
I am asking because I would like to know stagewise, what the quality of assemblies was at each k.

**Comment by asl** [comment]
Right, these are SPAdes internal files and are not intended for estimation of "stagewise quality of assemblies at each k", this is something that does not exist in SPAdes world.

SPAdes uses all information from multiple k-mer lengths to construct a final assembly, it's not doing merely "choose best result from multiple k-mers" as other assembly approaches do.

**Comment by balags1** [comment]
Alright, thank you for answering my queries
