### ISSUE TITLE
How many transcript isoforms does rnaSPAdes report?

### ISSUE THREAD

**Issue by vragh** [ablab/spades#794]
Hi,

Thank you for the great tool!!

I'm looking at the output from a `rnaSPAdes` _de novo_ assembly (short reads), and I see that the contigs are identified in a style similar to that used by the `Trinity` _de novo_ assembler. I.e., `somecontig_somegene_someisoform`.

It appears that in some cases `rnaSPAdes` has resolved as many as 54 isoforms. However, in the output, for each `NODE_x_length_x_cov_x_gx` combo, only a single isoform is in the output (e.g., just `NODE_1234_length_1234_cov_100.00_g123_i12`).

**My question is: where are the rest of the isoforms?** I seem to have only one isoform per gene, for all genes, and all assemblies that I attempted.

I am looking at the `transcripts.fasta` file, by the way. `SPAdes` version is `v3.15.2`.

**Comment by asl** [comment]
Tagging @andrewprzh

**Comment by andrewprzh** [comment]
Hi, could you send me transcript.fasta here or via email address in my github profile so I could have a look?

Thank you
Andrey

**Comment by vragh** [comment]
Hi @andrewprzh ,

I've emailed you the file.

**Comment by andrewprzh** [comment]
Thank you!

I have checked the file and I don't see anything odd there, all genes have isoform ids going from 0 to N.
The thing is that all SPAdes fasta files are ordered by the sequence length, so isoforms of the same gene are not consecutive. 
Hope that helps.

Best
Andrey

**Comment by vragh** [comment]
@andrewprzh ,

Thank you for looking into this, but I'm afraid i don't follow.

I guess I am confused, so let me clarify. If I were to take a `Trinity` assembly, and run it through a `bash` one-liner to count the number of isoforms per "gene", I'd get something like this:

```
$ grep -oP "(?<=^\>)[A-Za-z0-9\._]+(?=_i[0-9]+)" Trinity.Trinity.fasta | sort | uniq -c | sort -n -k 1 | tail
     28 TRINITY_DN98_c1_g1
     29 TRINITY_DN1196_c0_g1
     29 TRINITY_DN522_c0_g1
     29 TRINITY_DN585_c0_g1
     32 TRINITY_DN599_c0_g1
     32 TRINITY_DN738_c0_g1
     33 TRINITY_DN268_c2_g1
     34 TRINITY_DN33_c0_g1
     38 TRINITY_DN361_c0_g1
     50 TRINITY_DN98_c5_g1
```

When I run a `rnaSPAdes` assembly through the same one-liner, I get something like this:
```
$ grep -oP "(?<=^\>)[A-Za-z0-9\._]+(?=_i[0-9]+)" transcripts.fasta | sort | uniq -c | sort -n -k 1 | tail
      1 NODE_9993_length_1212_cov_5.397612_g7722
      1 NODE_9994_length_1212_cov_5.310376_g7723
      1 NODE_9995_length_1212_cov_3.889807_g7724
      1 NODE_9996_length_1212_cov_2.663912_g7725
      1 NODE_9997_length_1212_cov_1.393939_g7726
      1 NODE_9998_length_1211_cov_45.217831_g7727
      1 NODE_9999_length_1211_cov_34.731618_g7727
      1 NODE_999_length_3607_cov_9.287887_g639
      1 NODE_99_length_6978_cov_41.546317_g57
      1 NODE_9_length_11858_cov_73.766170_g1
```

It is true that the `rnaSPAdes` assembly does have sequences with headers like `>NODE_363_length_4843_cov_2549.987288_g3_i18` (indicating there are/were 18 isoforms), but when I `grep` for that gene (i.e., `>NODE_363_length_4843_cov_2549.987288_g3`), I only find that one sequence in the assembly and nothing else. Hence my question: where are the other isoforms?

**Comment by andrewprzh** [comment]
Thank you for your data!
Although gene and isoform is somewhat similar to Trinity, as being part of SPAdes, rnaSPAdes inherits contig naming from SPAdes. Thus, each contig name has 
- individual unique id (NODE_XX)
- length (length_XXXX)
- kmer coverage (cov_XXXX)

Distinct isoforms will have different unique ids, and may have different coverage and length as well. The only thing they share is the gene id (given after _g). For example:
`NODE_217_length_5488_cov_28.472321_g133_i0
NODE_260_length_5302_cov_30.767137_g133_i1`
So, if you'd like to collect all isoform from a single gene, group them by gene number, rather than entire prefix.
E.g. in you case 
`grep "_g3_" transcripts.fasta`
will provide all isoforms of gene #3.

**Comment by vragh** [comment]
HI @andrewprzh ,

Thank you for clarifying that for me!! So the naming is sort of inverted (w.r.t. `Trinity`) in that it goes `<uniqueidentifier>_<geneid>_<isoformid>`?

I wasn't able to find this in the documentation for `rnaSPAdes` (as far as I can recall), so I would be grateful if you could indicate it there prominently.

Thank you so much for your assistance!!

**Comment by andrewprzh** [comment]
>So the naming is sort of inverted (w.r.t. Trinity) in that it goes <uniqueidentifier>_<geneid>_<isoformid>? This is good to know.
Yes:)

>I wasn't able to find this in the documentation for rnaSPAdes (as far as I can recall), so I would be grateful if you could indicate it there prominently.
Section 2.3 contains clarification of contig naming (https://github.com/ablab/spades/blob/spades_3.15.2/assembler/rnaspades_manual.html). Probably I should add information about their order and prefix difference. Thank you for the suggestion!

**Comment by gainett** [comment]
Hello,

On the same line, do you have any script to make a gene-to-transcript map?
I am trying to annotate the transcriptome with Trinotate, and I need such a file.
Thanks,
Guilherme

**Comment by andrewprzh** [comment]
Dear @gainett 

I think this info can be extracted from contig names, sometihng like this:

```
import sys
from Bio import SeqIO
from collections import defaultdict

gene2transcript = defaultdict(list)
for r in SeqIO.parse(sys.argv[1], "fasta"):
    contig_name = r.id
    v = contig_name.split("_")
    gene2transcript[v[-2]].append(v[-1])

print(gene2transcript)

```

P.S. Better create new issues/questions as comments in complete issues could be easily lost.
