### ISSUE TITLE
using metaspades to hybrid assemble Illumina and Pacbio data finished abnormally, OS return value: 2

### ISSUE THREAD

**Issue by Holly202109** [ablab/spades#797]
### Description of bug

I am using metaspades.py to hybrid assemble a PE Illumina data set (this dataset is merged from 3 sequencing dataset with cat, _R1 and _R2 separately) , with a pacbio ccs data, and also provided a contigs file as untrusted_contigs. But the program abormally finished with error messages as follows:

===== Assembling started. 

===== K21 started. 

== Running: /data/SPAdes-3.15.2-Linux/bin/spades-core /data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/config.info /data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/mda_mode.info /data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/meta_mode.info

  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  99)   Loaded config from /data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/config.info
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  99)   Loaded config from /data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/mda_mode.info
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  99)   Loaded config from /data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/meta_mode.info
  0:00:00.000     1M / 10M   INFO    General                 (memory_limit.cpp          :  48)   Memory limit set to 250 Gb
  0:00:00.001     1M / 10M   INFO    General                 (main.cpp                  : 107)   Starting SPAdes, built from refs/heads/spades_3.15.2, git revision aab988a9b4986906b38396da7233bb1ee02982f2
  0:00:00.001     1M / 10M   INFO    General                 (main.cpp                  : 108)   Maximum k-mer length: 128
  0:00:00.001     1M / 10M   INFO    General                 (main.cpp                  : 109)   Assembling dataset (/data/HLP/dataLMFood/READ_QC/LMmix/output_folder/dataset.info) with K=21
  0:00:00.001     1M / 10M   INFO    General                 (main.cpp                  : 110)   Maximum # of threads to use (adjusted due to OMP capabilities): 16
  0:00:00.001     1M / 10M   INFO    General                 (pipeline.cpp              : 212)   SPAdes started
  0:00:00.001     1M / 10M   ERROR   General                 (pipeline.cpp              : 217)   Sorry, current version of metaSPAdes can work either with single library (paired-end only) or in hybrid paired-end + (TSLR or PacBio or Nanopore) mode.

== Error ==  system call for: "['/data/SPAdes-3.15.2-Linux/bin/spades-core', '/data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/config.info', '/data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/mda_mode.info', '/data/HLP/dataLMFood/READ_QC/LMmix/output_folder/K21/configs/meta_mode.info']" finished abnormally, OS return value: 2

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /data/HLP/dataLMFood/READ_QC/LMmix/output_folder/spades.log

Thank you for using SPAdes!

### spades.log

[spades.log](https://github.com/ablab/spades/files/6712864/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6712867/params.txt)

**Comment by asl** [comment]
So, the log reads:

```
0:00:00.001 1M / 10M ERROR General (pipeline.cpp : 217) Sorry, current version of metaSPAdes can work either with single library (paired-end only) or in hybrid paired-end + (TSLR or PacBio or Nanopore) mode.
```

See metaSPAdes manual (https://cab.spbu.ru/files/release3.15.2/manual.html#meta) for more information
