### ISSUE TITLE
SPAdes - out of memory

### ISSUE THREAD

**Issue by miguelpmachado** [ablab/spades#8]
Dear SPAdes team,
I'm trying to run SPAdes in several libraries using 1 thread and a maximum memory of 1 Gb , but it keeps crashing in K55 with 

> <jemalloc>: Error in malloc(): out of memory. Requested: 392167424, active: 398458880
> == Error ==  system call for: "['/biotools/INNUca/src/SPAdes-3.9.0-Linux/bin/spades', '/home/jani/21_STEC/Test/105400_S9_L001/spades/K55/configs/config.info', '/home/jani/21_STEC/Test/105400_S9_L001/spades/K55/configs/careful_mode.info']" finished abnormally, err code: -6

I don't understand why is SPAdes requiring such an amount of memory even if I set the maximum memory to 1 Gb!
Nevertheless, I'm sure I have around 29 Gb of available memory (20 Gb actually free and 9 Gb cached/buffered).

I attached SPAdes stdout ([SPAdes_stdout.txt](https://github.com/ablab/spades/files/566047/SPAdes_stdout.txt))

I hope you can help me solving this problem.
Best regards,
Miguel

**Comment by asl** [comment]
Dear Miguel,

Per manual, -m option allows one to set the hard memory limit for SPAdes. If it will consume more, then the job will be killed. The real amount of RAM necessary is a feature of the input data - one should not assume it is possible to assemble human genome using 1Gb of RAM.

In your case - your OS failed to fulfil SPAdes' request to allocate 370M of RAM while having 370M already allocated by SPAdes. Unfortunately, we have no way to control this, we simply pass the error we received from your OS to you.

**Comment by miguelpmachado** [comment]
Dear Anton,

I can understand that the RAM required to run is a function of the input data. However I'm not understanding why the 370 Mb requested + 370 Mb allocated RAM is a problem when I set the maximum memory to 1 Gb and I have 29 Gb available! Can you explain why is it a problem? Sorry for my ignorance.

Best regards,

Miguel

**Comment by asl** [comment]
SPAdes does not allocate 1 Gb in single chunk. It asks as much as it is necessary. Again, we're simply showing the error which was passed to us from your OS, I have no idea why allocation failed.

**Comment by JonN17** [comment]
I have this error as well.  I have 128 Gigabytes of RAM on a RHEL6 machine and it's having problems requesting 45 Gigabytes.  I'll cross post on RHEL forums but this is clearly a trending issue with metaSPades.
