### ISSUE TITLE
OS return value -11

### ISSUE THREAD

**Issue by HadrienRegue** [ablab/spades#800]
### Description of bug

Hello, 

We trying to launch SPAdes on a new machine with more ressources. However we get an OS return value error on this new machine with the --test option.
SPAdes perfectly work on other machines.

If you need more informations, please tell.

huge Thanks for this tool and the help provided.

Hadrien

### spades.log

[spades.log](https://github.com/ablab/spades/files/6727408/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6727424/params.txt)

### SPAdes version

3.15.0

### Operating System

Linux-5.10.0-0.bpo.5-amd64-x86_64-with-debian-10.9

### Python Version

3.7.10

### Method of SPAdes installation

binaries

**Comment by asl** [comment]
You need to compile SPAdes from sources. Also, the latest version of SPAdes is 3.15.2, not 3.15.0
