### ISSUE TITLE
finished abnormally, OS return value: -9

### ISSUE THREAD

**Issue by spencer411** [ablab/spades#802]
I get this error (finished abnormally, OS return value: -9) when attempting a metagenomic assembly on my institutions HPC using the code below:

spades.py --meta -t 96 -1 Site_1_open_summer_2019_pure_reads_1.fastq -2 Site_1_open_summer_2019_pure_reads_2.fastq -o Site_1_open_summer_2019

Note that I have run this same code with smaller paired read files with no problem, it seems to be specific to large paired reads (which in this case are ~11GB a piece).

I have attached the out file produced by my cluster here (same as the log file I believe
[spades_ass.slurm.uagc20-14.3219425.txt](https://github.com/ablab/spades/files/6727802/spades_ass.slurm.uagc20-14.3219425.txt)
).

**Comment by asl** [comment]
The log contains:

```
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=3219425.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

So, you're running ouf of RAM

**Comment by spencer411** [comment]
Ah, yes sorry, should've noticed that at the bottom... Thanks!
