### ISSUE TITLE
Spades multithreading is not working

### ISSUE THREAD

**Issue by mradz19** [ablab/spades#804]
### Description of bug

I am running a program which utilizes Spades as the assembler, I have noted that during the assembly step spades will default to using 1 thread no matter how many I have designated with the -t option. I also got an email from the sever admin saying that the program wasn't utilising all of the CPU space I had reserved.

```
1:49:40.847     1M / 29M   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 10 files using 1 threads. This might take a while.
```

### spades.log

[spades.log](https://github.com/ablab/spades/files/6775782/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6775790/params.txt)

### SPAdes version

v3.15.2

### Operating System

CentOS Linux v8.4.2105

### Python Version

Python 3.9.2

### Method of SPAdes installation

From Squeezemeta source code

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

The log reads:
```
  0:00:00.004     1M / 14M   INFO    General                 (main.cpp                  : 110)   Maximum # of threads to use (adjusted due to OMP capabilities): 1
```

So, you'd likely need to do something additional in order to enable multiple CPU threads for OpenMP tasks. Likely your system administrator could tell you necessary additional configuration steps. On many computation clusters you'd need to do something like this:
```
export OMP_NUM_THREADS=<number of threads allowed>
```

**Comment by mradz19** [comment]
Thanks Anton, I noticed that spades automatically sets the memory limit as well regardless of what I set the --memory flag to. Is that something else I also need to specify with OMP? I have several terabytes of RAM I can access

**Comment by asl** [comment]
> Thanks Anton, I noticed that spades automatically sets the memory limit as well regardless of what I set the --memory flag to.

How have you determined so? I'm seeing hard memory limit set to 400 Gb in your case.
