### ISSUE TITLE
finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by mradz19** [ablab/spades#805]
### Description of bug

My Spades run is stopping at the k-mer counting step

### spades.log

[spades.log](https://github.com/ablab/spades/files/6780999/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6780998/params.txt)

### SPAdes version

v3.15.2

### Operating System

CentOS Linux v8.4.2105

### Python Version

Python 3.9.2

### Method of SPAdes installation

From Squeezemeta source code

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
One of SPAdes intermediate files got corrupted. Likely this is due to I/O issue on the storage you're using. You may want to ask your system administrator for this.
