### ISSUE TITLE
finished abnormally, OS return value: 4

### ISSUE THREAD

**Issue by iagosch** [ablab/spades#806]
### Description of bug

Hello! I'm not sure why this error is happening, the program stops at "de Bruijn graph construction" in the very beggining of K21 assembly, claiming it can't find an specific file. 

### spades.log

[spades.log](https://github.com/ablab/spades/files/6786511/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6786513/params.txt)

### SPAdes version

SPAdes v3.15.2

### Operating System

Ubuntu 16.04.7 LTS

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

It looks like some I/O issue. Does it reproduce without the last library?

**Comment by iagosch** [comment]
> 
> 
> Hello
> 
> It looks like some I/O issue. Does it reproduce without the last library?

Hi, thanks for your answer.

I'll give it a shot without the last library and write back to you, thanks in advance :).

**Comment by iagosch** [comment]
> 
> 
> Hello
> 
> It looks like some I/O issue. Does it reproduce without the last library?

Hi again! 
Taking out the last library worked. I'll take a look at the files that I have. Thanks! :)
