### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by wangyaxiang008** [ablab/spades#807]
### Description of bug

An error occurred while running spades. The log file is as follows

### spades.log

[spades.zip](https://github.com/ablab/spades/files/6799249/spades.zip)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6799276/params.txt)

### SPAdes version

3.15.2

### Operating System

Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17

### Python Version

Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
You are not quite true that there are no errors reported in the spades.log. Let us read the log together:

```
mimalloc: error: unable to allocate OS memory (41682993152 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
```

So, you are running out of RAM

**Comment by wangyaxiang008** [comment]
Thank you for your quick reply.

My raw data is about 6GB of left reads and 6GB of right reads，and my RAM is set to 40GB . How much RAM should I set for my tasks to work properly.

**Comment by asl** [comment]
It seems your assembly is very fragmented. You may want to check for possible sources of contamination or other sequencing artifacts
