### ISSUE TITLE
MetaSPAdes finished abnormally, OS return value: -6

### ISSUE THREAD

**Issue by Rardoma** [ablab/spades#809]
### Description of bug

Hi c:
It's the first time that I make assemblies, the samples are metagenomes and they're somewhat heavy (9-10 Gb); I'm running MetaSPAdes for this task, but I get the following error:

_== Error == system call for: "[...]" finished abnormally, os return value: -6_

I'd like to know what I can do to solve it.
Best regards!

### spades.log

[spades.log](https://github.com/ablab/spades/files/6825160/spades.log)

### params.txt

[params.zip](https://github.com/ablab/spades/files/6825163/params.zip)

### SPAdes version

SPAdes 3.15.2

### Operating System

Linux-5.4.0-77-generic-x86_64-with-Ubuntu-20.04-focal

### Python Version

Python 2.7.18

### Method of SPAdes installation

manual 

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
The log clearly reads:
```
mimalloc: error: unable to allocate OS memory (10880024576 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
```

So you're running out RAM
