### ISSUE TITLE
<jemalloc>: Error in malloc(): out of memory. Requested: 12786980896, active: 64869105664

### ISSUE THREAD

**Issue by caonetto** [ablab/spades#81]
[params.txt](https://github.com/ablab/spades/files/1710549/params.txt)
[spades.log](https://github.com/ablab/spades/files/1710551/spades.log)

This is the complete error, any ideas??? 

````
<jemalloc>: Error in malloc(): out of memory. Requested: 12786980896, active: 64869105664


== Error ==  system call for: "['/home/users/conetto/miniconda3/pkgs/spades-3.11.1-py27_zlib1.2.8_0/share/spades-3.11.1-0/bin/hammer', '/data/WICgenome/DF3_secondgenome/spades_assembly/corrected/configs/config.info']" finished abnormally, err code: -6
````

thanks in advance.

**Comment by asl** [comment]
Well, per error message you're running out of RAM. At the time of crash SPAdes consumed 60 Gb of RAM and your system failed to allocate 12 Gb more.

**Comment by Buuntu** [comment]
Is there a way to set an upper memory limit or you just have to guess and check?

**Comment by asl** [comment]
There is no upper memory limit. The amount of required RAM depends heavily of many things including genome size, coverage, error rate, repeat content, ploidy, etc.

**Comment by Buuntu** [comment]
So it's normal for it to have a `malloc()` error even when running with 60 GB of RAM on a typical ~5MB genome?

**Comment by asl** [comment]
I have no idea about the genome size. But the dataset itself contained more than 1.5 billion distinct k-mers. So, the memory consumption does look reasonable.

**Comment by rafaeltiveron** [comment]
SPAdes consumes to much.. It needs to improve script, to really use the amount of memory we have on machine, and record as much as possible on disk, to alocate more. I have the same problem. 14 million reads to assembly and I need more than 139 gb. Its insane. Trinity, Chrysalid, Jellyfish, Transabyss don't have the same problem.

**Comment by lbi-usp** [comment]
Mine had the same error, about the same number of distinct k-mers. My server has 1Tb RAM, but when spades crashed it was using only 120gb.
