### ISSUE TITLE
SPAdes exits with "OS return value: -9"

### ISSUE THREAD

**Issue by dluecking** [ablab/spades#812]
### Description of bug

Dear SPAdes team,

I encountered an error with SPAdes, I could not solve for myself. 
After running:
```
spades.py --meta -1 <sample>_R1_trimmed.fq.gz -2 <sample>_R2_trimmed.fq.gz -o out -t 24 -m 400
```
SPAdes ran without any error for a couple of minutes. Then it exited with the following error message:
```
== Error ==  system call for: "['/home/dlueckin/bin/miniconda3/envs/spades/bin/spades-hammer', '/scratch/dlueckin/assemble_bumbago/run1/corrected/configs/config.info']" finished abnormally, OS return value: -9
```
Any idea what this could is greatly appreciated!
Thank you
DL

### spades.log

[spades.log](https://github.com/ablab/spades/files/6848845/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6848858/params.txt)

### SPAdes version

v3.15.2

### Operating System

Debian 4.19.181-1 (2021-03-19) 

### Python Version

Python 3.9.2

### Method of SPAdes installation

conda + mamba

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
It seems that your SPAdes job was killed. Likely due to OOM. You may want to check your system log for more information

**Comment by Nkosinathi15** [comment]
Hello Als.
I had the same issue and I now want to continue where it stopped, 
please assist on how to continue spade from the last step the job stopped.

thank you

**Comment by asl** [comment]
@Nkosinathi15 In general you cannot unless you made checkpoints. Refer to SPAdes manual for command line options for this: https://cab.spbu.ru/files/release3.15.5/manual.html#sec3.2

**Comment by Nkosinathi15** [comment]
Can you please assist me.

I have been trying to de novo assembly sheep genome using short illumine reads but Spades keeps terminating at this stage or at Sub clustering hamming graphs.

[cid:3c8f1dc8-9ee5-474b-8dfa-97714ebc76b8]
Can you assist please

Thank you.
________________________________
