### ISSUE TITLE
spades stuck without any error message

### ISSUE THREAD

**Issue by fconstancias** [ablab/spades#813]
### Description of bug

Thanks for developping spades. 
I am planning to generate individual sample assemblies of chicken cecum shot-gun metagenomic data using both `spades.py --meta` and `spades.py --meta --plasmids`.

I started first to run the `--only-error-correction` before starting the metaspades and metaplasmidspades assemblies.

It worked perfectly fine for a first couple of samples but it get stuck for one particular sample whitout any error message and the job is still running for quite some time already.

### spades.log

[log.zip](https://github.com/ablab/spades/files/6854003/log.zip)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6854005/params.txt)

### SPAdes version

SPAdes 3.15.2

### Operating System

CentOS Linux release 7.3.1611 (Core) 

### Python Version

Python 2.7.5

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

This seems to be known issue with CQF. There is no ETA on fix. The only workaround is to use `--only-assembler`

**Comment by fconstancias** [comment]
Thanks for you answer. Any reason why this error is not affecting the error correction process for all the samples?

**Comment by asl** [comment]
Well, because the problem is data-dependent
