### ISSUE TITLE
Specifying multiple libraries

### ISSUE THREAD

**Issue by sjaenick** [ablab/spades#814]
### Is your feature request related to a problem? Please describe. For generic questions use Q&A section in the Discussions forum above.

I'm trying to perform a metagenome coassembly using multiple input datasets (Illumina PE). Instead of
concatenating all input FASTQ files, it would be nice to directly support multiple input datasets for the
`-1` and `-2` arguments.

### Describe the solution you'd like

Adopt a solution like megahit, where multiple input datasets can be specified as a comma-separated list:

```
  Input options that can be specified for multiple times (supporting plain text and gz/bz2 extensions)
    -1                       <pe1>          comma-separated list of fasta/q paired-end #1 files, paired with files in <pe2>
    -2                       <pe2>          comma-separated list of fasta/q paired-end #2 files, paired with files in <pe1>
```

**Comment by asl** [comment]
Please refer to SPAdes manual (https://cab.spbu.ru/files/release3.15.2/manual.html#sec3.1) on the instructions how multiple files could be specified.

In particular, things like `-1 foo1_1.fastq -1 foo2_1.fastq -2 foo1_2.fastq -2 foo2_2.fastq` are supported for ages.
