### ISSUE TITLE
SPAdes giving an error -9

### ISSUE THREAD

**Issue by absartalat** [ablab/spades#815]
### Description of bug

Dear SPAdes team,
I am running SPAdes on my metagenomic data wit the following code:
$ metaspades.py --pe1-1 Sample-2_R1.fq.gz --pe1-2 Sample-2_R2.fq.gz -o spades_output_s1 -m 400
and it is returning an error with value -9. Kindly suggest me a solution.

### spades.log

[spades.log](https://github.com/ablab/spades/files/6898087/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6898088/params.txt)

### SPAdes version

SPAdes 3.12.0

### Operating System

Ubuntu 20.04.2 LTS

### Method of SPAdes installation

Linux binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Your SPAdes job was killed. Likely due to insufficient RAM, however I would suggest you to check system logs for more information. Also, I would suggest giving the latest SPAdes 3.15.3 a try
