### ISSUE TITLE
spades 3.15.0 assembly err code -6

### ISSUE THREAD

**Issue by JBojko** [ablab/spades#817]
### Description of bug

[params.txt](https://github.com/ablab/spades/files/6902207/params.txt)
Hello, I'm trying to figure out why my data won't assemble. I have a combination of MinION and HiSeq datasets.
[spades.log](https://github.com/ablab/spades/files/6902208/spades.log)

Thank you,

### spades.log

[spades.log](https://github.com/ablab/spades/files/6902211/spades.log)
[params.txt](https://github.com/ablab/spades/files/6902212/params.txt)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6902213/params.txt)
[spades.log](https://github.com/ablab/spades/files/6902214/spades.log)

### SPAdes version

3.15.0

### Operating System

Linux

### Method of SPAdes installation

Unknown

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is a known problem in SPAdes 3.15.0. Please consider upgrading to SPAdes 3.15.3
