### ISSUE TITLE
SPAdes err code: -11 after "Starting k-mer counting."

### ISSUE THREAD

**Issue by tkataras** [ablab/spades#82]
Hello, I am having trouble running SPAdes with paired end data on my University's computing cluster. I have successfully run it on the single end data from the same sample but I have been unable to complete a run in paired end mode. The error seems to crop up during k-mer counting. Here is the error followed by the bash script I used to run SPAdes 3.11.1:
[SPAdes_error_and_code.txt](https://github.com/ablab/spades/files/1721330/SPAdes_error_and_code.txt)

Thank you for your time and any input, 
Theo Kataras

**Comment by asl** [comment]
Please provide us the full spades.log and params.txt files

**Comment by tkataras** [comment]
[spades.log](https://github.com/ablab/spades/files/1721810/spades.log)
[params.txt](https://github.com/ablab/spades/files/1721811/params.txt)

Thank you for looking into this,
-Theo

**Comment by tkataras** [comment]
My apologies, the issue seems to have been storage allocation on my computing cluster. Thank you for time spent on this.

-Theo

**Comment by asl** [comment]
Thanks. The next version of SPAdes would include better handling of write errors.
