### ISSUE TITLE
metaviralSPAdes keeping ony large contigs 

### ISSUE THREAD

**Issue by yinacobian** [ablab/spades#820]
Not an issue anymore. Just a question, is there a length filtering in the contigs.fasta file for metaviralspades?

**Comment by asl** [comment]
Taggin @Dmitry-Antipov

**Comment by Dmitry-Antipov** [comment]
Yes.  We have both straighforward (do not output anything shorter than 1000bp) and not straightforward filtering: do not output contigs that represent only fragments of viruses due to the assembly graph structure.
