### ISSUE TITLE
OS return value: -6

### ISSUE THREAD

**Issue by fanlu-f** [ablab/spades#821]
### Description of bug

I use the same command to run other data. And they all running successfully.Only this one have error.Would you give me sonme idea about how to solve it?

== Error ==  system call for: "['/data/SPAdes-3.15.2-Linux/bin/spades-core', '/data2/cleandata_Food/raw reads/LM/ASSEMBLYLM_Enrich-DNA/K55/configs/config.info', '/data2/cleandata_Food/raw reads/LM/ASSEMBLYLM_Enrich-DNA/K55/configs/mda_mode.info', '/data2/cleandata_Food/raw reads/LM/ASSEMBLYLM_Enrich-DNA/K55/configs/meta_mode.info']" finished abnormally, OS return value: -6

### spades.log

[spades.log](https://github.com/ablab/spades/files/6965562/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6965564/params.txt)

### SPAdes version

SPAdes 3.15.2

### Operating System

LInux-5.8.0-53-generic-x86_64-with-debian-bullseye-sid

### Python Version

Python 3.6.13

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:
```
mimalloc: error: unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
```

So, you're running out of RAM. It seems you need more than 250 Gb that you provided to SPAdes
