### ISSUE TITLE
Error code 12

### ISSUE THREAD

**Issue by AdrianoZaghi** [ablab/spades#822]
### Description of bug

The program starts the assembly of my reads but in 90% of cases it stops before finishing the iteration 0.
The log says that the program can't allocate memory (RAM i suppose. My RAM is 125 Gb).
I need to know how much RAM i need to complete my analysis, considering that my trimmed reads libraries aren't bigger than 5 Gb.
Is there any spades parameter (like k-mer constant) that can be set in order to reduce memory requirement?
Does memory requirement depends only on reads library size?

### spades.log

[spades.log](https://github.com/ablab/spades/files/6968590/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6968591/params.txt)

### SPAdes version

SPAdes  v3.15.2

### Operating System

Debian GNU/Linux 10 (buster)

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The memory consumption depends on many things that are not known before assembly finishes: expected genome size, genome complexity, repeat content, error rate, strain variation, etc. One cannot estimate memory consumption in advance solely from the input file size. So, it seems you'd really need more RAM. You may also try to ensure that indeed all 100 Gb of RAM that you 'promised' to SPAdes are indeed available.

**Comment by AdrianoZaghi** [comment]
Ok, i was suspecting it.
I will look for more RAM.
Big tahk you for the short time answer.

Scarica Outlook per Android<https://aka.ms/ghei36>

________________________________
