### ISSUE TITLE
err code: -7

### ISSUE THREAD

**Issue by Lewis2020JPG** [ablab/spades#823]
### Description of bug

Hi, I was trying to run spades in linux, but got following error:
`== Error ==  system call for: "['/ldfssz1/ST_INFECTION/P17Z10200N0536_Echinococcus/USER/jijingkai/software/SPAdes/SPAdes-3.14.0-Linux/bin/spades-hammer', '/ldfssz1/ST_INFECTION/P17Z10200N0246_Phage_XMF/USER/liuwei/cryosphere/Permafrost2/452/03.2_Spades/corrected/configs/config.info']" finished abnormally, OS return value: -7`

This is my python code:
`python ./spades.py -t 8 -1 ./01.3_prinseq/45_good_out_R1.fastq -2 ./01.3_prinseq/45_good_out_R2.fastq -o ./03.2_Spades`

I can't figure out why my assembly keeps failing. If you have any idea of whats going on from the attached files I'd love to hear them. Thank you so much!!

### spades.log

[spades.log](https://github.com/ablab/spades/files/6992355/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/6992356/params.txt)

### SPAdes version

SPAdes-3.14.0

### Operating System

Linux

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
How much free RAM is available for your SPAdes job? Does the problem reproduce with the latest SPAdes 3.15.3?

**Comment by Lewis2020JPG** [comment]
> How much free RAM is available for your SPAdes job? Does the problem reproduce with the latest SPAdes 3.15.3?

RAM=200G , I'll download the latest SPAdes 3.15.3 to run again.
But in my opinion, whether the *_good_out_fastq data are too large or not?
`-rw-r--r-- 1 3.1G Aug 12 10:39 45_good_out_R1.fastq
-rw-r--r-- 1 3.1G Aug 12 10:40 45_good_out_R2.fastq`

For instance, another sample‘s scarfford_fasta has successfully assembled by SPAdes-3.14.0.
`-rw-r--r-- 1 962M Aug  5 21:33 43_good_out_R1.fastq
-rw-r--r-- 1  962M Aug  5 21:33 43_good_out_R2.fastq`
[spades.log](https://github.com/ablab/spades/files/6996265/spades.log)

**Comment by asl** [comment]
The memory consumption depends on many things that are not known before assembly finishes: expected genome size, genome complexity, repeat content, error rate, strain variation, etc. One cannot estimate memory consumption in advance solely from the input file size. 

Also, it looks like the coverage of your input data is highly uneven, it does not make any sense to assemble in normal multicell mode.

**Comment by Lewis2020JPG** [comment]
Thank you for telling me these, which help me to find the reasons!
My samples are indeed very complicated. While they're from soil, which may involve contamination of animal genomes, but I used SPAdes-3.14.0 to assemble  contigs in order to get microbial information.

**Comment by asl** [comment]
Why don't you use metaSPAdes?

**Comment by Lewis2020JPG** [comment]
Thank you very much! The problem is solved  metaSPAdes and I'll download the latest SPAdes 3.15.3 to try other samples.
By the way, may I ask you whether you systematically compare the effect of assembly  of SPAdes and megahit or not ?

**Comment by asl** [comment]
You could refer to metaSPAdes paper for comparison (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5411777/)
