### ISSUE TITLE
Number of contigs in hybrid and short-only assemblies are the same

### ISSUE THREAD

**Issue by valery-shap** [ablab/spades#824]
### Description of bug

Hello,

I have 2 millions Illumina paired end reads and 177.776 Nanopore long reads for E.coli. There are more then 2500 contigs in short -only and even in hybrid assembly. Only 500 contigs from these are longer then 500 bp. 
What could be the mistake?
I have only one warning :

=== Error correction and assembling warnings:
 * 0:00:37.442    88M / 62G   WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 

There were problems with this sample when using Unicycler too. The hybrid assembly has 5 contigs but lost the 60kb plasmid. 

Valery

### spades.log

[spades.log](https://github.com/ablab/spades/files/7027137/spades.log)
[spades_short.log](https://github.com/ablab/spades/files/7027138/spades_short.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7027139/params.txt)
[params_short.txt](https://github.com/ablab/spades/files/7027140/params_short.txt)

### SPAdes version

Spades 3.15.3

### Operating System

Centos 8

### Method of SPAdes installation

tar package 

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Looks perfectly ok to me. The # of contigs does not  mean anything. As far as I can see, you hybrid  assembly likely contains almost a complete genome and something that might look like a plasmid

**Comment by valery-shap** [comment]
Thank you very much for reply! I was a bit confused about the difference between Unicycler results.

Best regards,
Valery

**Comment by asl** [comment]
Well, we have no idea what Unicycler does (often it does very strange things), however, judging from the logs – I think that the assembly might be suboptimal due to wrong choice of k-mer lengths and the coverage of the dataset.

**Comment by valery-shap** [comment]
I set -k 27,47,63,77,89,99,107,115,121,127 , suppose that it will help for right choice. and cov_cutoff auto. and careful. Could I change smth more in Spades flags to get better results with hybrid assembly? 
I know about contamination in short reads and suppose that there are  huge amount of <500 bp contigs because of this. But even without them I hoped to have much more better results using long (clean) reads too.

A lot of thanks,
Valery

**Comment by asl** [comment]
Both the choice of set of k-mers and coverage filtering is a very poor choice given the coverage of the dataset and read length. Have you found this "recipe" somewhere? The results are only saved because coverage threshold got disabled due to  detected low coverage and your Nanopore reads closed more than 30 coverage gaps. This may explain the suboptimal results.

Also, you need to know the repeat content of a particular strain as some E. coli strains definitely have long repeats that might not be spanned by your ONT reads

**Comment by valery-shap** [comment]
Yes, I took k-mer range from Unicycler Spades part:
`Choosing k-mer range for assembly (2021-08-13 12:18:01)
-------------------------------------------------------
    Unicycler chooses a k-mer range for SPAdes based on the length of the input reads. It uses a wide range of many k-mer sizes to maximise the chance of finding an ideal assembly.

SPAdes maximum k-mer: 127
Median read length: 151
K-mer range: 27, 47, 63, 77, 89, 99, 107, 115, 121, 127
`
I run --isolate without -k,--careful, --cov_cutoff and now I have 8125 contigs with hybrid assembly, only 1300 contigs are bigger then 500 bp.  

A lot of thanks,
Valery
[spades_hybrid_isolate.log](https://github.com/ablab/spades/files/7032202/spades_hybrid_isolate.log)

**Comment by asl** [comment]
> Unicycler chooses a k-mer range for SPAdes based on the length of the input reads. It uses a wide range of many k-mer sizes to maximise the chance of finding an ideal assembly.

This is a very questionable part of the whole Unicycler approach as it does very risky things. In many cases it yields very bad assemblies.

> I run --isolate without -k,--careful, --cov_cutoff and now I have 8125 contigs with hybrid assembly, only 1300 contigs are bigger then 500 bp. It is clinical antibiotic-resistance strain.

As I already said, the # of contigs does not correspond to the "quality" of the assembly. What is the length of the few longest contig? What is N50? Is the result enough for downstream analysis?

**Comment by valery-shap** [comment]
Hybrid assembly spades 3.15.3 (--isolate):
N50 = 875726, L50 = 2, Total length = 6470546, GC % = 52.79, # N's per 100 kbp =  1.24

Short assembly spades 3.15.3 (--careful --cov-cutoff	auto	-k	27,47,63,77,89,99,107,115,121,127):
N50 = 116844, L50 = 17, Total length = 5504007, GC % = 51.01, # N's per 100 kbp =  0.55

The main aim of additional nanopore sequencing was to get whole sequences of plasmids. I expect the inci2 plasmid 50-70kb in this sample (it has the repeats in the structure also). 

Hybrid Unicycler: no plasmid
Long only Unicycler: ~60 kb
Short Spades: it is present but different contigs
Hybrid Spades: ~96 kb
Hybrid MaSurCa (CABOG): ~ 88 kb
Hybrid MaSurCa (Flye): no plasmid

Maybe I'll try plasmid option of Spades. I'll compare all assemblies and hope to find the truth)
Thank you very much for supporting.

Valery

**Comment by asl** [comment]
As far as I can see, there is a high-coverage plasmid there. So, just run plasmidSPAdes and it should be there.

**Comment by valery-shap** [comment]
>NODE_1_length_65571_cov_14.196871_component_0
>NODE_2_length_63122_cov_12.929756_component_0

**>NODE_3_length_59194_cov_15.899792_component_1**
**NODE_3_length_59194_cov_15.899792_component_1	30550	30873	+	IncI2_1	1-324/324**

>NODE_4_length_45203_cov_9.021852_component_0
>NODE_5_length_29259_cov_13.986510_component_0
>NODE_6_length_19657_cov_27.748336_component_0
>NODE_7_length_15735_cov_15.820733_component_0
>NODE_8_length_13759_cov_15.568589_component_0
>NODE_9_length_13259_cov_13.577825_component_0
>NODE_10_length_12757_cov_14.212431_component_0
>NODE_11_length_11664_cov_14.448643_component_0
>NODE_12_length_9661_cov_12.437487_component_0
>NODE_13_length_9647_cov_12.216597_component_0
>NODE_14_length_8508_cov_14.492901_component_0
>NODE_15_length_6260_cov_13.873308_component_0
>NODE_16_length_6022_cov_472.345886_component_0
>NODE_17_length_5727_cov_11.106786_component_0
>NODE_18_length_5585_cov_19.093074_component_0
>NODE_19_length_5582_cov_16.062145_component_0
>NODE_20_length_5548_cov_26.187235_component_0
>NODE_21_length_4329_cov_3.946930_component_0
>NODE_22_length_3402_cov_9.111756_component_0
>NODE_23_length_2826_cov_13.381993_component_0
>NODE_24_length_2651_cov_15.866878_component_0
>NODE_25_length_2340_cov_16.430637_component_0
>NODE_26_length_2070_cov_17.419454_component_0
>NODE_27_length_2000_cov_15.563801_component_0
>NODE_28_length_1757_cov_17.907975_component_0
>NODE_29_length_1571_cov_9.179363_component_0
>NODE_30_length_1448_cov_16.387585_component_0
>NODE_31_length_1405_cov_976.823944_component_0
>NODE_32_length_1104_cov_19.237462_component_1
>NODE_33_length_926_cov_9.534418_component_0
>NODE_34_length_820_cov_403.894661_component_0
>NODE_35_length_773_cov_6.842105_component_0
>NODE_36_length_738_cov_6.631751_component_0
>NODE_37_length_608_cov_36.821206_component_0
>NODE_38_length_571_cov_16.761261_component_1
>NODE_39_length_543_cov_9.901442_component_0
>NODE_40_length_537_cov_27.068293_component_0
>NODE_41_length_529_cov_402.363184_component_0
>NODE_42_length_493_cov_29.945355_component_0
>NODE_43_length_464_cov_382.575668_component_0
>NODE_44_length_369_cov_282.090909_component_0
>NODE_45_length_336_cov_23.435407_component_0
>NODE_46_length_287_cov_11.800000_component_0
>NODE_47_length_267_cov_36.885714_component_0
>NODE_48_length_255_cov_236.710938_component_0
>NODE_49_length_255_cov_15.921875_component_0
>NODE_50_length_254_cov_413.283465_component_0
>NODE_51_length_252_cov_30.712000_component_0
>NODE_52_length_248_cov_30.933884_component_0
>NODE_53_length_248_cov_14.719008_component_0
>NODE_54_length_247_cov_41.158333_component_0
>NODE_55_length_247_cov_22.333333_component_0
>NODE_56_length_240_cov_8.787611_component_1
>NODE_57_length_240_cov_6.345133_component_1
>NODE_58_length_239_cov_5.535714_component_1
>NODE_59_length_234_cov_5.925234_component_0
>NODE_60_length_233_cov_5.933962_component_1
>NODE_61_length_233_cov_5.509434_component_1
>NODE_62_length_233_cov_5.452830_component_1
>NODE_63_length_233_cov_3.084906_component_1
>NODE_64_length_231_cov_27.259615_component_0
>NODE_65_length_224_cov_3.123711_component_0
>NODE_66_length_219_cov_42.163043_component_0
>NODE_67_length_219_cov_3.423913_component_0
>NODE_68_length_217_cov_316.722222_component_0
>NODE_69_length_217_cov_16.744444_component_0
>NODE_70_length_215_cov_36.818182_component_0
>NODE_71_length_206_cov_309.405063_component_0
>NODE_72_length_204_cov_290.025974_component_0
>NODE_73_length_199_cov_31.597222_component_0
>NODE_74_length_199_cov_29.861111_component_0
>NODE_75_length_195_cov_53.367647_component_0
>NODE_76_length_191_cov_397.203125_component_0
>NODE_77_length_186_cov_7.525424_component_0
>NODE_78_length_186_cov_3.644068_component_0
>NODE_79_length_180_cov_29.660377_component_0
>NODE_80_length_180_cov_3.547170_component_0
>NODE_81_length_176_cov_342.142857_component_0
>NODE_82_length_176_cov_14.795918_component_0
>NODE_83_length_176_cov_6.306122_component_0
>NODE_84_length_176_cov_4.183673_component_0
>NODE_85_length_166_cov_262.461538_component_0
>NODE_86_length_166_cov_28.871795_component_0
>NODE_87_length_166_cov_4.487179_component_0
>NODE_88_length_158_cov_390.419355_component_0
>NODE_89_length_155_cov_37.392857_component_0
>NODE_90_length_153_cov_11.038462_component_0
>NODE_91_length_153_cov_7.846154_component_0
>NODE_92_length_153_cov_5.692308_component_0
>NODE_93_length_138_cov_287.363636_component_0
>NODE_94_length_135_cov_13.250000_component_0
>NODE_95_length_135_cov_4.875000_component_0
>NODE_96_length_134_cov_18.428571_component_0
>NODE_97_length_134_cov_12.142857_component_0
>NODE_98_length_134_cov_8.714286_component_1
>NODE_99_length_134_cov_4.142857_component_0
>NODE_100_length_132_cov_393.400000_component_0
>NODE_101_length_132_cov_57.000000_component_0
>NODE_102_length_131_cov_335.750000_component_0
>NODE_103_length_131_cov_305.500000_component_0
>NODE_104_length_131_cov_45.500000_component_0
>NODE_105_length_131_cov_10.500000_component_0
>NODE_106_length_131_cov_7.500000_component_0
>NODE_107_length_130_cov_287.666667_component_0
>NODE_108_length_130_cov_74.000000_component_0
>NODE_109_length_128_cov_181.000000_component_0

Seems that plasmidSpades helps me to find it) and its size looks like truth.
Am I right that Spades supposed 2 plasmids in the sample:
component 0
component 1?
I have 4 replicons by PlasmidFinder.

Best regards,
Valery

**Comment by asl** [comment]
It's hard to tell for sure, since the coverage is quite low and plasmidSPAdes uses coverage and graph topology for this. How have you ran plasmidSPAdes?

**Comment by valery-shap** [comment]
without ticks)
/home/vshapovalova/SPAdes-3.15.3-Linux/bin/spades.py	-1	Escherichia-coli.ok_1.fastq.gz	-2	Escherichia-coli.ok_2.fastq.gz	--nanopore	all_barcode02.fastq.gz	-t	96	--plasmid	-o	hybridspades_plasmid	-m	700

**Comment by asl** [comment]
Ok, can you post the log as well?
