### ISSUE TITLE
Metaspades finished abnormally after the system called : err code: -9

### ISSUE THREAD

**Issue by AlbertRockG** [ablab/spades#826]
### Description of bug

I computed 174437471 reads for a metagenome with gradually 31, 55 and 60 Gb of memory limit. With 31 Gb memory limit, the assembly end with the error : out of memory. That's why I increased the memory limit. But from 55 to 60 Gb the error change. Bellow I provide as suggested the spades.log and the params.txt files. I would like to know what I did wrong to end the assembly of reads, please. 

### spades.log

[spades.log](https://github.com/ablab/spades/files/7044477/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7044479/params.txt)

### SPAdes version

SPAdes v3.13.1

### Operating System

Ubuntu 20.04 LTS

### Python Version

Python 3.8.10

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
You SPAdes job was killed. Likely due to out of memory situation. I would suggest you to check system log for more information. Also I would suggest you to upgrade to the latest SPAdes 3.15.3 which has much better memory consumption performance.

**Comment by AlbertRockG** [comment]
Please, can I reduce the memory consumption by using less threads?

**Comment by asl** [comment]
Memory consumption does not depend on the # of threads in general. It depends on such things like genome size, coverage, error rate, repeat content, etc.

Consider upgrading to SPAdes 3.15.3 which has much better memory consumption performance.

**Comment by AlbertRockG** [comment]
I'll do it. Thanks a lot.

**Comment by asl** [comment]
Please reopen if you're still having issues
