### ISSUE TITLE
mimalloc warnings

### ISSUE THREAD

**Issue by bastiaanvonmeijenfeldt** [ablab/spades#827]
### Description of bug

During metaSPAdes assembly I get mimalloc warnings.

mimalloc: warning: maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)
and
mimalloc: warning: unable to allocate from region: size 46399488

See also the attached log.

I don't get the usual memalloc error. SPAdes does not terminate on these warnings and seems to finish normally.

What do these warnings mean? Can I still trust this assembly or should I change something and rerun? If so, SPAdes should capture these warnings and terminate.

### spades.log

[spades.log](https://github.com/ablab/spades/files/7046305/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7046309/params.txt)

### SPAdes version

SPAdes 3.15.1

### Operating System

Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo

### Python Version

Python 3.7.6

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [x] Yes

**Comment by asl** [comment]
The warnings are benign, you can ignore them
