### ISSUE TITLE
Limited Number of Libraries

### ISSUE THREAD

**Issue by mirand863** [ablab/spades#83]
Hello,

I am having trouble assembling a set of 32 unpaired single reads with SPAdes. The first time I tried, SPAdes gave me this error message:

option --s10 not recognized
SPAdes genome assembler v3.11.1

After I got this error, I read the documentation and found out that SPAdes can only work with 9 files, according to this entry:

--s<#>          <filename>      file with unpaired reads for single reads library number <#> (<#> = 1,2,..,9)

**Is there a way to overcome this limitation?**

Kind Regards,
Fábio

**Comment by mirand863** [comment]
> First of all, why do you want to assemble them as different libraries? This does not make much sense for single reads.

Are you saying I could just concatenate the 32 files and use a single file as input?

**Comment by asl** [comment]
For single reads? Yes. Or just use the same -s option multiple times.

**Comment by mirand863** [comment]
I will try that. Thank you very much!
