### ISSUE TITLE
Spade terminated

### ISSUE THREAD

**Issue by azrasid** [ablab/spades#835]
### Description of bug

Hi , I was running a Nextflow script, where I want to give interlaced input to the SPADES.

**THIS IS THE COMMAND I RAN**
 python3 /opt/exp_soft/bioinf/SPAdes-3.13.0-Linux/bin/spades.py --careful --12 ${fastq} --untrusted-contigs ${ref1} -o ${name}_spades

**And this is a sample fastq file**
[CYP2C19_13.001_final.TXT](https://github.com/ablab/spades/files/7092120/CYP2C19_13.001_final.TXT)

### spades.log

Error executing process > 'run_spade (5)'

Caused by:
  Process `run_spade (5)` terminated with an error exit status (1)

Command executed:

  python3 /opt/exp_soft/bioinf/SPAdes-3.13.0-Linux/bin/spades.py --careful --12 CYP2C19_15.001_final.fastq --untrusted-contigs gref_region.fasta -o CYP2C19_15_spades

Command exit status:
  1

Command output:
        orientation: fr
        left reads: not specified
        right reads: not specified
        interlaced reads: ['CYP2C19_15.001_final.fastq']
        single reads: not specified
        merged reads: not specified
      Library number: 2, library type: untrusted-contigs
        left reads: not specified
        right reads: not specified
        interlaced reads: not specified
        single reads: ['gref_region.fasta']
        merged reads: not specified
  Read error correction parameters:
    Iterations: 1
    PHRED offset will be auto-detected
    Corrected reads will be compressed
  Assembly parameters:
    k: automatic selection based on read length
    Repeat resolution is enabled
    Mismatch careful mode is turned ON
    MismatchCorrector will be used
    Coverage cutoff is turned OFF
  Other parameters:
    Dir for temp files: CYP2C19_15_spades/tmp
    Threads: 16
    Memory limit (in Gb): 110
  
  
  ======= SPAdes pipeline started. Log can be found here: CYP2C19_15_spades/spades.log
  
  == Splitting CYP2C19_15.001_final.fastq into left and right reads (in CYP2C19_15_spades/split_input directory)
  
  ===== Read error correction started. 
  
  
  == Running read error correction tool: /opt/exp_soft/bioinf/SPAdes-3.13.0-Linux/bin/spades-hammer CYP2C19_15_spades/corrected/configs/config.info
  
    0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.13.1, git revision 9a9d54db2ff9abaac718155bf74c12ec9464e8ca
    0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from CYP2C19_15_spades/corrected/configs/config.info
    0:00:00.005     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 1
    0:00:00.005     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 110 Gb
    0:00:00.005     4M / 4M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
    0:00:00.059     4M / 4M    ERROR   General                 (main.cpp                  :  89)   Failed to determine offset! Specify it manually and restart, please!
  
  
  == Error ==  system call for: "['/opt/exp_soft/bioinf/SPAdes-3.13.0-Linux/bin/spades-hammer', 'CYP2C19_15_spades/corrected/configs/config.info']" finished abnormally, err code: 255
  
  In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
  or report an issue on our GitHub repository github.com/ablab/spades
  Please provide us with params.txt and spades.log files from the output directory.
executor >  slurm (9)
[33/f6f209] process > make_ref      [100%] 1 of 1 ✔
[7c/4a877e] process > run_spade (4) [180%] 9 of 5, failed: 9 ✘
[-        ] process > msa_prep1     -
[-        ] process > msa_prep2     -
[-        ] process > vg_msa        -
[-        ] process > make_graph    -
Error executing process > 'run_spade (5)'

Caused by:
  Process `run_spade (5)` terminated with an error exit status (1)

Command executed:

  python3 /opt/exp_soft/bioinf/SPAdes-3.13.0-Linux/bin/spades.py --careful --12 CYP2C19_15.001_final.fastq --untrusted-contigs gref_region.fasta -o CYP2C19_15_spades

Command exit status:
  1

Command output:
        orientation: fr
        left reads: not specified
        right reads: not specified
        interlaced reads: ['CYP2C19_15.001_final.fastq']
        single reads: not specified
        merged reads: not specified
      Library number: 2, library type: untrusted-contigs
        left reads: not specified
        right reads: not specified
        interlaced reads: not specified
        single reads: ['gref_region.fasta']
        merged reads: not specified
  Read error correction parameters:
    Iterations: 1
    PHRED offset will be auto-detected
    Corrected reads will be compressed
  Assembly parameters:
    k: automatic selection based on read length
    Repeat resolution is enabled
    Mismatch careful mode is turned ON
    MismatchCorrector will be used
    Coverage cutoff is turned OFF
  Other parameters:
    Dir for temp files: CYP2C19_15_spades/tmp
    Threads: 16
    Memory limit (in Gb): 110
  
  
  ======= SPAdes pipeline started. Log can be found here: CYP2C19_15_spades/spades.log
  
  == Splitting CYP2C19_15.001_final.fastq into left and right reads (in CYP2C19_15_spades/split_input directory)
  
  ===== Read error correction started. 
  
  
  == Running read error correction tool: /opt/exp_soft/bioinf/SPAdes-3.13.0-Linux/bin/spades-hammer CYP2C19_15_spades/corrected/configs/config.info
  
    0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.13.1, git revision 9a9d54db2ff9abaac718155bf74c12ec9464e8ca
    0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  76)   Loading config from CYP2C19_15_spades/corrected/configs/config.info
    0:00:00.005     4M / 4M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 1
    0:00:00.005     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 110 Gb
    0:00:00.005     4M / 4M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
    0:00:00.059     4M / 4M    ERROR   General                 (main.cpp                  :  89)   Failed to determine offset! Specify it manually and restart, please!
  
  
  == Error ==  system call for: "['/opt/exp_soft/bioinf/SPAdes-3.13.0-Linux/bin/spades-hammer', 'CYP2C19_15_spades/corrected/configs/config.info']" finished abnormally, err code: 255
  
  In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
  or report an issue on our GitHub repository github.com/ablab/spades
  Please provide us with params.txt and spades.log files from the ou

### params.txt

What do I need to paste here?

### SPAdes version

SPAdes-3.13.0

### Operating System

Mac OS

### Python Version

Python 2.7.10 

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The error is clearly seen in the log file. Let us check it together:
```
0:00:00.005     4M / 4M    INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
0:00:00.059     4M / 4M    ERROR   General                 (main.cpp                  :  89)   Failed to determine offset! Specify it manually and restart, please!
```

And indeed, your files are unlikely a valid FASTQ as all quality values are exactly the same. The read error correction relies on quality values and therefore certainly cannot proceed.

**Comment by azrasid** [comment]
Thanks for your reply. I tried adding the option Phred offset and now its working perfectly fine.
If you think adding this option is not a good idea , I am happy to explore more with you. Please let me know what other information I can provide to you.

Another thing , I want to mention is that to generate fastq files I used the command  fastq - to_perfect_reads and it generated fastq files with quality score as I.

Thanks again.
Regards,
Azra

**Comment by asl** [comment]
If these are perfect reads, why do you run the read error correction?

**Comment by azrasid** [comment]
Right, I edit it - all working fine.
