### ISSUE TITLE
setrlimit(2) call failed, errno = 22 on m1 Mac using spades.py --test

### ISSUE THREAD

**Issue by bmalthi** [ablab/spades#839]
### Description of bug

Hi

I have a M1 Mac, and spades is failing even on the base test installation process, the error I'm getting is 

"setrlimit(2) call failed, errno = 22"

Thanks

Ben

### spades.log

[spades.log](https://github.com/ablab/spades/files/7096136/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7096137/params.txt)

### SPAdes version

SPAdes-3.15.3-Darwin

### Operating System

MacOs 12.0 Beta (21A5304g)

### Python Version

3.8.2

### Method of SPAdes installation

binary

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Thanks for the report. So far we do not have a possibility to reproduce, debug and fix issue on M1. Likely you'd need to run SPAdes on the "proper" x86-64 platform, not an emulation.

**Comment by bmalthi** [comment]
thanks

**Comment by Nibby** [comment]
@asl This issue is also observed on non-M1 macOS Monterey machines. AFAIK it is not specific to M1 architecture. See this [related bug report](https://github.com/golang/go/issues/30401) on another project. I am not well versed in C++, could you please investigate whether `memory_limit.cpp` needs some adjustment?

**Comment by asl** [comment]
@Nibby Thanks for letting us know! Apparently a Monterey issue then... oh-well..

**Comment by asl** [comment]
@Nibby @bmalthi we do not have a working Monterey system here in order to fix the things. Will you be able to check our fix?

**Comment by asl** [comment]
The current workaround is to explicitly set the memory limit via `-m` option

**Comment by manshu1234** [comment]
hello, am new to this, so can you explain how to set the memory limit in stepwise. thankyou

**Comment by bmalthi** [comment]
Yeah I'll give it a try

**Comment by bmalthi** [comment]
[params.txt](https://github.com/ablab/spades/files/7596467/params.txt)
[spades.log](https://github.com/ablab/spades/files/7596468/spades.log)

I think it worked with this command
./spades.py --test -m 1024

**Comment by manshu1234** [comment]
Thankyou very much! it worked. This is my first time am working on this. I have files two about 1.7 Gb each, R1 and R2.  I am trying assemble them, but my background is not bioinformatics. If there is anyother software which requires minimum coding, I tried using usagalaxy online server, but its been over a day still there is no datasets have formed.
Thankyou once again @bmalthi

**Comment by oushujun** [comment]
Mac M1 chip user here. System is Monterey.
Specifying -m 1024 works, but based on the manual, that's 1024 Gb of memory. Maybe the units are off?

**Comment by asl** [comment]
> Mac M1 chip user here. System is Monterey. Specifying -m 1024 works, but based on the manual, that's 1024 Gb of memory. Maybe the units are off?

Units are not off. Note that this is not *memory*,  but *memory bar* that SPAdes will never overshoot. It seems one cannot set memory limit on Monterey anymore, setting it high enough makes the error disappear (lower values yields `error` from OS). This is why we said it is broken... 3.15.4 will introduce workaround for this and it won't be hard error anymore, just warning that user is on their own.

**Comment by asl** [comment]
Monterrey workaround introduced in https://github.com/ablab/spades/releases/tag/v3.15.4

**Comment by akimpen** [comment]
> [params.txt](https://github.com/ablab/spades/files/7596467/params.txt) [spades.log](https://github.com/ablab/spades/files/7596468/spades.log)
> 
> I think it worked with this command ./spades.py --test -m 1024

hi, would you know where to find the python script coz when I ran the command it didn't work.
