### ISSUE TITLE
SPADES error code -9

### ISSUE THREAD

**Issue by PierBJX** [ablab/spades#84]
Hi!
I tried to run spades with this command:
`-bash-4.2$ ./spades.py -k 125 --careful --pe1-1 /mnt/gpfs0/home/s280987/Assignment/Raw/reads_1.fq --pe1-2 /mnt/gpfs0/home/s280987/Assignment/Raw/reads_2.fq -o /mnt/gpfs0/home/s280987/Assignment/Result/Spades/`

And I get the error 9 and I don't know why.. 

```
== Error ==  system call for: "['/mnt/gpfs0/home/s280987/SPAdes-3.11.0-Linux/bin/hammer', '/mnt/gpfs0/home/s280987/Assignment/Result/Spades/corrected/configs/config.info']" finished abnormally, err code: -9
```

[params.txt](https://github.com/ablab/spades/files/1725113/params.txt)
[spades.log](https://github.com/ablab/spades/files/1725114/spades.log)

Hope you could help.
Thanks

**Comment by asl** [comment]
Answered via e-mail
