### ISSUE TITLE
plasmidSPAdes 3.13.0 stuck, does not finish?

### ISSUE THREAD

**Issue by vizzerra** [ablab/spades#845]
### Description of bug

plasmidSPAdes appears to get stuck at "chromosome_removal.cpp" for xxxxxxx vertices left for 4/5 plasmid assemblies, with no error message. The data are all very similar, from closely related species, yet only one has finished successfully. I have tried --continue with no success. Is this a memory issue, possibly data issue?

Thank you for your help.

### spades.log

[spades_fail.log](https://github.com/ablab/spades/files/7139288/spades_fail.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7139290/params.txt)

### SPAdes version

SPAdes v3.13.0

### Operating System

Ubuntu 18.04.5 LTS

### Python Version

Python 3.8.5

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Will you please give SPAdes 3.15.3 a try?

Also, the log reads:
```
  1:59:27.498    20G / 48G   WARN    General                 (chromosome_removal.cpp    :  91)   More than 20% of long edges have coverage significantly different from median (total 19517349 of 34511879 bases).
  1:59:27.499    20G / 48G   WARN    General                 (chromosome_removal.cpp    :  92)   In most cases it means that either read coverage is uneven or significant contamination is present - both of these two cases make plasmidSPAdes' results unreliable
  1:59:27.499    20G / 48G   WARN    General                 (chromosome_removal.cpp    :  93)   However, that situation may still be OK if you expect to see large plasmids in your dataset, so plasmidSPAdes will continue to work
```

**Comment by vizzerra** [comment]
> Hello
> 
> Will you please give SPAdes 3.15.3 a try?
> 
> Also, the log reads:
> 
> ```
>   1:59:27.498    20G / 48G   WARN    General                 (chromosome_removal.cpp    :  91)   More than 20% of long edges have coverage significantly different from median (total 19517349 of 34511879 bases).
>   1:59:27.499    20G / 48G   WARN    General                 (chromosome_removal.cpp    :  92)   In most cases it means that either read coverage is uneven or significant contamination is present - both of these two cases make plasmidSPAdes' results unreliable
>   1:59:27.499    20G / 48G   WARN    General                 (chromosome_removal.cpp    :  93)   However, that situation may still be OK if you expect to see large plasmids in your dataset, so plasmidSPAdes will continue to work
> ```

Thank you for your reply. Do you know of any solutions to these or similar issues? I'm having trouble finding any--I've tried filtering reads by read length, removing reads less than the mean, but still ran into the issue using 3.15.3.

**Comment by asl** [comment]
Please reopen if this is still a problem
