### ISSUE TITLE
memory problem.

### ISSUE THREAD

**Issue by apoosakkannu** [ablab/spades#846]
### Description of bug

Hi, I ran many spades assembly jobs. I have problem with few (about 10) jobs with error of exceeding memory. I have attached batch file, log files for your reference. Could you please give some idea to get rid of this problem.

Thanks and looking forward to hear from you. 

### spades.log

Command line: /appl/soft/bio/spades/gcc_9.1.0/3.15.0/bin/metaspades.py	-t	7	--pe1-1	/scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz	--pe1-2	/scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz	-o	/scratch/project_2003832/assembly/rerun2/SRR9850920	

System information:
  SPAdes version: 3.15.0
  Python version: 2.7.5
  OS: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo

Output dir: /scratch/project_2003832/assembly/rerun2/SRR9850920
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz']
      right reads: ['/scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /scratch/project_2003832/assembly/rerun2/SRR9850920/tmp
  Threads: 7
  Memory limit (in Gb): 187

======= SPAdes pipeline started. Log can be found here: /scratch/project_2003832/assembly/rerun2/SRR9850920/spades.log

/scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz: max reads length: 146
/scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz: max reads length: 146

Reads length: 146

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /appl/soft/bio/spades/gcc_9.1.0/3.15.0/bin/spades-hammer /scratch/project_2003832/assembly/rerun2/SRR9850920/corrected/configs/config.info

  0:00:00.000     1M / 12M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.000     1M / 12M   INFO    General                 (main.cpp                  :  76)   Loading config from /scratch/project_2003832/assembly/rerun2/SRR9850920/corrected/configs/config.info
  0:00:00.001     1M / 12M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 7
  0:00:00.001     1M / 12M   INFO    General                 (memory_limit.cpp          :  48)   Memory limit set to 187 Gb
  0:00:00.001     1M / 12M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.002     1M / 12M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.002     1M / 12M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.002     1M / 12M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.002     1M / 12M   INFO   K-mer Counting           (kmer_data.cpp             : 283)   Estimating k-mer count
  0:00:00.056   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 288)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz
  0:02:54.449   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 297)   Processed 41996622 reads
  0:02:54.449   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 288)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz
  0:05:20.057   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 297)   Processed 83993244 reads
  0:05:20.057   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 302)   Total 83993244 reads processed
  0:05:20.511   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 305)   Estimated 4522039550 distinct kmers
  0:05:20.511     1M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 309)   Filtering singleton k-mers
  0:05:20.514    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 315)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz
  0:37:40.062    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 324)   Processed 41996622 reads
  0:37:40.062    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 315)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz
  0:58:17.188    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 324)   Processed 83993244 reads
  0:58:17.188    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 329)   Total 83993244 reads processed
  0:58:17.189    21G / 21G   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 7 threads. This might take a while.
  0:58:17.189    21G / 21G   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 131072
  0:58:17.189    21G / 21G   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 7.93948 Gb
  0:58:17.189    21G / 21G   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 4194304
  0:58:17.190    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz
  0:58:46.256    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1856436 reads
  0:59:14.699    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 3699155 reads
  0:59:43.056    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 5538350 reads
  1:00:11.443    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 7377640 reads
  1:00:39.550    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 9194777 reads
  1:01:08.212    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 11004887 reads
  1:01:36.448    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 12867741 reads
  1:02:05.126    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 14721548 reads
  1:02:33.464    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 16575618 reads
  1:03:01.685    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 18421980 reads
  1:07:19.019    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 34928622 reads
  1:09:05.979    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz
  1:14:51.486    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 69025836 reads
  1:17:47.567    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 83993244 reads processed
  1:17:47.627    21G / 25G   INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  2:47:34.799    21G / 39G   INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 2846929332 kmers in total.
  2:47:38.108    18M / 39G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  2:51:14.832  2051M / 39G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 2846929332 kmers, 2056247008 bytes occupied (5.77815 bits per kmer).
  2:51:14.846  2051M / 39G   INFO   K-mer Counting           (kmer_data.cpp             : 354)   Arranging kmers in hash map order
  2:54:28.336    45G / 45G   INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  4:05:14.182    45G / 45G   INFO    General                 (main.cpp                  : 155)   Extracting clusters:
  4:05:14.357    45G / 45G   INFO    General                 (concurrent_dsu.cpp        :  18)   Connecting to root
  4:05:21.542    45G / 45G   INFO    General                 (concurrent_dsu.cpp        :  34)   Calculating counts
  4:38:13.970   113G / 113G  INFO    General                 (concurrent_dsu.cpp        :  63)   Writing down entries

### params.txt

Command line: /appl/soft/bio/spades/gcc_9.1.0/3.15.0/bin/metaspades.py  -t	10	--pe1-1 /scratch/project_2003832/rawdata/trim/rerun/SRR9850904_1_tri$

System information:
Command line: /appl/soft/bio/spades/gcc_9.1.0/3.15.0/bin/metaspades.py	-t	7	--pe1-1	/scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz	--pe1-2	/scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz	-o	/scratch/project_2003832/assembly/rerun2/SRR9850920	

System information:
  SPAdes version: 3.15.0
  Python version: 2.7.5
  OS: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo

Output dir: /scratch/project_2003832/assembly/rerun2/SRR9850920
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz']
      right reads: ['/scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /scratch/project_2003832/assembly/rerun2/SRR9850920/tmp
  Threads: 7
  Memory limit (in Gb): 187

======= SPAdes pipeline started. Log can be found here: /scratch/project_2003832/assembly/rerun2/SRR9850920/spades.log

/scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz: max reads length: 146
/scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz: max reads length: 146

Reads length: 146

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /appl/soft/bio/spades/gcc_9.1.0/3.15.0/bin/spades-hammer /scratch/project_2003832/assembly/rerun2/SRR9850920/corrected/configs/config.info

  0:00:00.000     1M / 12M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.000     1M / 12M   INFO    General                 (main.cpp                  :  76)   Loading config from /scratch/project_2003832/assembly/rerun2/SRR9850920/corrected/configs/config.info
  0:00:00.001     1M / 12M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 7
  0:00:00.001     1M / 12M   INFO    General                 (memory_limit.cpp          :  48)   Memory limit set to 187 Gb
  0:00:00.001     1M / 12M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.002     1M / 12M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.002     1M / 12M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.002     1M / 12M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.002     1M / 12M   INFO   K-mer Counting           (kmer_data.cpp             : 283)   Estimating k-mer count
  0:00:00.056   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 288)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz
  0:02:54.449   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 297)   Processed 41996622 reads
  0:02:54.449   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 288)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz
  0:05:20.057   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 297)   Processed 83993244 reads
  0:05:20.057   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 302)   Total 83993244 reads processed
  0:05:20.511   113M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 305)   Estimated 4522039550 distinct kmers
  0:05:20.511     1M / 115M  INFO   K-mer Counting           (kmer_data.cpp             : 309)   Filtering singleton k-mers
  0:05:20.514    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 315)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz
  0:37:40.062    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 324)   Processed 41996622 reads
  0:37:40.062    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 315)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz
  0:58:17.188    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 324)   Processed 83993244 reads
  0:58:17.188    21G / 21G   INFO   K-mer Counting           (kmer_data.cpp             : 329)   Total 83993244 reads processed
  0:58:17.189    21G / 21G   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 7 threads. This might take a while.
  0:58:17.189    21G / 21G   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 131072
  0:58:17.189    21G / 21G   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 7.93948 Gb
  0:58:17.189    21G / 21G   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 4194304
  0:58:17.190    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_1_trimmed.fastq.gz
  0:58:46.256    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1856436 reads
  0:59:14.699    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 3699155 reads
  0:59:43.056    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 5538350 reads
  1:00:11.443    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 7377640 reads
  1:00:39.550    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 9194777 reads
  1:01:08.212    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 11004887 reads
  1:01:36.448    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 12867741 reads
  1:02:05.126    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 14721548 reads
  1:02:33.464    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 16575618 reads
  1:03:01.685    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 18421980 reads
  1:07:19.019    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 34928622 reads
  1:09:05.979    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /scratch/project_2003832/rawdata/trim/SRR9850920_2_trimmed.fastq.gz
  1:14:51.486    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 69025836 reads
  1:17:47.567    25G / 25G   INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 83993244 reads processed
  1:17:47.627    21G / 25G   INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  2:47:34.799    21G / 39G   INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 2846929332 kmers in total.
  2:47:38.108    18M / 39G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  2:51:14.832  2051M / 39G   INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 2846929332 kmers, 2056247008 bytes occupied (5.77815 bits per kmer).
  2:51:14.846  2051M / 39G   INFO   K-mer Counting           (kmer_data.cpp             : 354)   Arranging kmers in hash map order
  2:54:28.336    45G / 45G   INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  4:05:14.182    45G / 45G   INFO    General                 (main.cpp                  : 155)   Extracting clusters:
  4:05:14.357    45G / 45G   INFO    General                 (concurrent_dsu.cpp        :  18)   Connecting to root
  4:05:21.542    45G / 45G   INFO    General                 (concurrent_dsu.cpp        :  34)   Calculating counts
  4:38:13.970   113G / 113G  INFO    General                 (concurrent_dsu.cpp        :  63)   Writing down entries
  Python version: 2.7.5
  OS: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo

Output dir: /scratch/project_2003832/assembly/rerun1/SRR9850904
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/scratch/project_2003832/rawdata/trim/rerun/SRR9850904_1_trimmed.fastq.gz']
      right reads: ['/scratch/project_2003832/rawdata/trim/rerun/SRR9850904_2_trimmed.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /scratch/project_2003832/assembly/rerun1/SRR9850904/tmp
  Threads: 10
  Memory limit (in Gb): 250

### SPAdes version

v.3.15.0

### Operating System

Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo

### Python Version

  Python version: 2.7.5

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

There are no errors in the logs. Will you please attach the complete spades.log files?

**Comment by apoosakkannu** [comment]
Hi,
That is the spades.log file. It is what i got it. Thanks.

**Comment by asl** [comment]
Why do you think it's a memory problem? Can you allocate more memory for your SPAdes job then?

**Comment by apoosakkannu** [comment]
[
[array_job_err_8107552_3.txt](https://github.com/ablab/spades/files/7243269/array_job_err_8107552_3.txt)
](url)

**Comment by apoosakkannu** [comment]
i tried to allocate more memory, but still have problem. then got the following error,
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: error: unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:   29192.310 s
   process: user: 239668.648 s, system: 617.842 s, faults: 1
       rss: current: 258742980608, peak: 257914916864
    commit: current: 258742980608, peak: 258742980608


== Error ==  system call for: "['/appl/soft/bio/spades/gcc_9.1.0/3.15.0/bin/spades-core', '/scratch/project_2003832/assembly/rerun1/SRR9850904/K55/configs/c$

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /scratch/project_2003832/assembly/rerun1/SRR9850904/spades.log

Thank you for using SPAdes!

**Comment by asl** [comment]
@apoosakkannu So, per error message, you still ran out of memory, likely SPAdes hit the hard memory limit that you specified via `-m` option (note that it defaults to 250 Gb per https://cab.spbu.ru/files/release3.15.2/manual.html#sec3.2).
