### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by hutumpyancha** [ablab/spades#848]
### Description of bug

Hello, 
I am trying to install Spades on both a linux machine and a Mac machine and there seems to be some issue. I am using the codes under "Downloading Spades binaries"; they appear to be running properly. However, when I am trying to run "spades.py --test" I am getting the error "command not found". Is there some mistake that I am doing while installing that is causing this issue and how should I be able to solve it? Thanks,
Upasana

### spades.log

I don't have aloe file as I am having trouble installing it

### params.txt

Similarly, I do not have the params.txt file too. 

### SPAdes version

Spades version 3.15.3

### Operating System

Linux and Mac

### Python Version

Python 2.7.18

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

The problem is unlikely related to SPAdes and more related to the generic command line issues. Likely some command line tutorial will help to resolve it. Otherwise – I would suggest to contact your system administrator.

**Comment by hutumpyancha** [comment]
okay thank you so much, I think I have been able to solve it. Thanks again.
