### ISSUE TITLE
Cryptic error when outputting FastG graph

### ISSUE THREAD

**Issue by jmtsuji** [ablab/spades#853]
### Description of bug

Thanks for your hard work on SPAdes. I am assembling several metagenomes using the same computational workflow on the same server. However, one of the metagenomes fails for an unknown reason during the "Outputting FastG graph" stage near the end of the K55 assembly. The other metagenomes can all be assembled successfully. As you can see from the log file, I tried re-starting SPAdes on the failed dataset, but I had the same assembly failure a second time. The log file states the following, and does not provide further details:

```
  3:28:19.498    38G / 113G  INFO   StageManager             (stage.cpp                 : 132)   STAGE == Contig Output
  3:28:19.498    38G / 113G  INFO    General                 (contig_output_stage.cpp   :  45)   Writing GFA to assembly//K55/assembly_graph_with_scaffolds.gfa
  3:28:25.478    38G / 113G  INFO    General                 (contig_output.hpp         :  22)   Outputting contigs to assembly//K55/before_rr.fasta
  3:28:31.827    38G / 113G  INFO    General                 (contig_output_stage.cpp   :  56)   Outputting FastG graph to assembly//K55/assembly_graph.fastg


== Error ==  system call for: "['spades-core', 'assembly/K55/configs/config.info', 'assembly/K55/configs/mda_mode.info', 'assembly/K55/configs/meta_mode.info']" finished abnormally, err code: -11
```

I have included my system information and sample processing steps below:

Server information:
- Server: Dell Precision 7920 Tower
- RAM: 512 GB
- CPU: Intel(R) Xeon(R) Silver 4214, 2 units = 24 processor cores
- OS: Ubuntu 20.04.2 LTS
- SPAdes version: 3.13.1

Read preprocessing steps:
- Basic quality control (trimming etc.)
- Error correction using `tadpole.sh` from the BBMap suite, e.g., `tadpole.sh -Xmx340G prealloc=1             in1=assembly/reads/QC_R1.fastq.gz,assembly/reads/QC_se.fastq.gz in2=assembly/reads/QC_R2.fastq.gz             out1=assembly/reads/QC.errorcorr_R1.fastq.gz,assembly/reads/QC.errorcorr_se.fastq.gz out2=assembly/reads/QC.errorcorr_R2.fastq.gz mode=correct threads=30 ecc=t ecco=t`
- Merging of paired-end reads using `bbmerge.sh` from the BBMap suite, e.g., `bbmerge.sh -Xmx340G threads=30 in1=assembly/reads/QC.errorcorr_R1.fastq.gz in2=assembly/reads/QC.errorcorr_R2.fastq.gz outmerged=assembly/reads/QC.errorcorr.merged_me.fastq.gz outu=assembly/reads/QC.errorcorr.merged_R1.fastq.gz outu2=assembly/reads/QC.errorcorr.merged_R2.fastq.gz ecct iterations=5 k=62 extend2=40`

The output FastG file seems to stop prematurely in the middle of a sequence entry:
```
>EDGE_363709305_length_127_cov_10.958333:EDGE_363709307_length_89_cov_14.882353;
AATTCGGCCTGGAATCTGCAGAGCAACGATGTTCACAGTGGCACATCGGCGTATGAACTT
CCCGTCGGAATACCCGGCGGTGGCGAGTATATGGTGGAGTTGGGCAATGAGCTGGTGCTG
ACGAATG
>EDGE_322967222_length_432_cov_4.177719:EDGE_372199733_length_763_cov_8.576271';
CATACGCCGATGTGCCACTGTGAACATCGTTGCTCTGCAGATTCCAGGCCGAATTCAGCC
AGTTGCTTTCGCCGTTCTCAAAGCCATCATAAACCGGATAGACTACCGGGACAGGCGTAT
GTTCGACCACCTCGACATCATCGATATTCCAGCCGTCAGCTGTGCTTGCTGTACTACTGT
CGCTGCGAATGTAAAACTTGATGCGCACATTAGGCTGACCGGCCCACTCGGAGAGATCAA
TCTGCTGCTGATGCCACTGCCGTCGGCTCCTCTCCCGTGCTCCGTAGCGCATGGACCAGG
CGCTTCCATCCTTGGATATATAGAGACAGATCCAGTCGCCGGTGTTCAGTTCAAACCGAT
```

Can you provide any insights on what might have caused the failure? Alternatively, do you have any suggestions for parameters I could change in SPAdes to avoid this error?

Thanks very much,
Jackson

### spades.log

[spades.log](https://github.com/ablab/spades/files/7320636/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7320608/params.txt)

### SPAdes version

SPAdes v3.13.1

### Operating System

Ubuntu 20.04.2 LTS

### Python Version

Python 3.6.13

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Note that it should be faster and consume less RAM ;)
