### ISSUE TITLE
Error 255

### ISSUE THREAD

**Issue by FabyanoLopes** [ablab/spades#86]
Hello my friend!

I'm new user on Spades and I'm trying to use this powerful software.

I performed several attempts and I always got the same error 255. I realy don't know what it could be.

 So, I'm attaching my .log and corrector.info. 

Best,

Fabyano Lopes

[spades.log](https://github.com/ablab/spades/files/1741924/spades.log)
[corrector.info.log](https://github.com/ablab/spades/files/1741925/corrector.info.log)

**Comment by asl** [comment]
The log reads:

```
[mem_sam_pe] paired reads have different names: "NB501934:94:HVG73AFXX:1:11101:23826:16906", "NB501934:94:HVG73AFXX:1:11101:3369:5870"
```

So, your input is likely corrupted – your left reads do not correspond to the right ones. This is also confirmed by bogus insert size detected:
```
  0:02:42.892     1G / 34G   INFO    General                 (pair_info_count.cpp       : 198)   146747 paired reads (2.78801% of all) aligned to long edges
  0:02:43.085   332M / 34G   INFO    General                 (pair_info_count.cpp       : 351)     Insert size = 46447.8, deviation = 84331.3, left quantile = 284, right quantile = 171293, read length = 100
```

Make sure whatever read corrupting / preprocessing steps you're using, they are paired-end aware.

**Comment by FabyanoLopes** [comment]
Ok!

I'll check.

Thanks!!!

**Comment by FabyanoLopes** [comment]
Hello again!

I've checked all outputs generated in all qc steps; however, I didn't find any problem in this steps and I'got the same problem on Spades. First, I used the four pe libraries (8 files) and used bbduk.sh with forcetrimmingright=99 and after I used bbmap for take out all adapters  and phix. Finally, I used sickle pe.

This error 255 I've got when I run spades with --careful parameter; however, when I run spades with --only-assembler, it seems that are all fine.

I believe the command that I'm using to run Spades are ok.

Sorry if my doubt is too basic but I really don't know what I could do to solve this problem.

Thanks again!

**Comment by asl** [comment]
> This error 255 I've got when I run spades with --careful parameter; however, when I run spades with --only-assembler, it seems that are all fine.
No it is not. The insert size is bogus and this indicates that your reads are corrupted. You need to use paired-end aware tools.
