### ISSUE TITLE
Spades == Error ==  system call, finished abnormally, err code: -11

### ISSUE THREAD

**Issue by pdhrati02** [ablab/spades#869]
### Description of bug

Hi @asl
I was using spades and got the following errors:
The program was terminated by segmentation fault
=== Stack Trace ===

== Error ==  system call for: "['/install/software/anaconda3.6.a/share/spades-3.13.0-0/bin/spades-hammer', '/data/Food/analysis/R3930_resistomeanalysis/rm2/metawrap/metaspades/I06Ay2/corrected/configs/config.info']" finished abnormally, err code: -11

But in my case, only 9 out of 90 samples failed. The others ran fine.
I checked that the number of reads in the cleaned reads I am supplying is same for both forward and reverse files for these 9 samples.
Please find attached the params and log file for one of the failed samples. Can you help me with this.

Any help would be appreciated, thank you
DP

### spades.log

[spades.log](https://github.com/ablab/spades/files/7426176/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7426178/params.txt)

### SPAdes version

3.13.0

### Operating System

Linux

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Please reopen if the issue could be reproduced with SPAdes 3.15.4
