### ISSUE TITLE
PlasmidSPAdes error with paired end reads

### ISSUE THREAD

**Issue by gamer3051** [ablab/spades#87]
Hello,
I am trying to run PlasmidSPAdes with two files from Illumina sequencing, one is a forward read and the second a reverse.  The read error correction will not start because of an option-? error which I can't figure out.  This is the output

Kaylas-MBP:~ MacKayla$ cd Downloads
Kaylas-MBP:Downloads MacKayla$ SPAdes/SPAdes-3.11.1-Darwin/bin/spades.py --pe1-1 KS1B0612_S15_L001_R1_001.fastq.gz -–pe1-2 KS1B0612_S15_L001_R2_001.fastq.gz –-plasmid -o Thesis_Data
option -? not recognized
SPAdes genome assembler v3.11.1

followed by a list of the options.  I am running Mac OSX El Capitan with Python 2.7.  I am new to Python so any help is appreciated, thanks!
Kayla

**Comment by gamer3051** [comment]
I ended up getting it to work by taking the test code suggested in the manual, below, and simply switching out the files/text for the ones I was using.  Not sure what the problem was but it is working now. Problem solved 👍 

spades.py --pe1-1 ../share/spades/test_dataset/ecoli_1K_1.fq.gz \
    --pe1-2 ../share/spades/test_dataset/ecoli_1K_2.fq.gz -o spades_test

**Comment by asl** [comment]
The problem was caused by invalid symbol in the command line. Note that your " –-plasmid" contains short dash and long dash.
