### ISSUE TITLE
SPAdes out of memory with 2TB

### ISSUE THREAD

**Issue by hjruscheweyh** [ablab/spades#871]
### Description of bug

Dear SPAdes developer,

im running spades on a few large samples and have observed a pattern of oom errors when using SPAdes 3.15. Even though there is enough free memory on the server (2TB) and I request enough memory in spades (-m 2000), spades seems to fail when requesting less then the maximum avail RAM.
Is my observation correct? Or are the numbers at the bottom of the log not accurate? 

Note: I have observed a similar behaviour with large samples from a different project and running SPAdes on a 3TB RAM server.

Best and thanks,
Hans

### spades.log

[spades.log](https://github.com/ablab/spades/files/7491907/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7491908/params.txt)

### SPAdes version

v3.15.2

### Operating System

Linux-4.18.0-193.28.1.el8_2.x86_64-x86_64-with-redhat-8.2-Ootpa

### Python Version

v3.6.7

### Method of SPAdes installation

Linux binary from GitHub release

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Well, the numbers are correct. Your system failed to fulfil SPAdes request to allocate 4Mb of RAM when the memory consumption was approx 800 Gb. There is no way to recover from this problem. You may want to check with your system administrator whether you indeed have 2 Tb of *free* RAM, whether there are no other processesthat consume memory are running, etc.

**Comment by hjruscheweyh** [comment]
Thanks for the help. Please have a look at the screenshot of the memory consumption at that particular timepoint. There was plenty of RAM left.
<img width="597" alt="Screenshot 2021-11-07 at 09 53 31" src="https://user-images.githubusercontent.com/12255853/140638611-bce2a269-1b39-4d3c-a146-2dc5e5cba29a.png">

**Comment by asl** [comment]
Well, as I said, the failure comes from your OS. It is out of SPAdes control.

**Comment by hjruscheweyh** [comment]
It is maybe out of SPAdes control but maybe it has something to do with mimalloc?
I have ran another assembly on a different system (Xeon instead of Zen2, older Linux kernel, 3TB RAM) and get the same issue at almost the same peak memory of 800GB. Can this be a conincidence? Is there a way to test whether this is caused by mimalloc?

```
System information:
  SPAdes version: 3.15.2
  Python version: 3.6.7
  OS: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo
  Threads: 64
  Memory limit (in Gb): 3000
```


```
 18:33:21.645   539G / 638G  INFO   PairInfoImprover         (pair_info_improver.hpp    : 105)   Paired info stats: missing = 457447126; contradictional = 0
mimalloc: error: unable to allocate OS memory (4194304 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:   69780.477 s
   process: user: 1761358.326 s, system: 92308.857 s, faults: 0
       rss: current: 830539296768, peak: 760085594112
    commit: current: 830539296768, peak: 830560268288
```

**Comment by asl** [comment]
Highly unlikely. As the error comes directly from the failed system call. Given that if fails in the similar place, you can check the system settings – likely they will be similarly configured.

**Comment by hjruscheweyh** [comment]
Do you have an idea what configuration setting that can be? Or any test that can check peak memory?

Btw, I have assembled datasets that require >1TB of RAM with spades version 3.14.1 (so before mimalloc) and didnt have any issues there.

E.g here:

```
 41:36:35.069   396G / 1259G INFO    General                 (pair_info_filters.hpp     : 263)   Done filtering
 41:36:36.435   380G / 1259G INFO    General                 (distance_estimation.cpp   : 157)   Refining clustered pair information
 41:43:13.732   380G / 1259G INFO    General                 (distance_estimation.cpp   : 159)   The refining of clustered pair information has been finished
 41:43:13.737   380G / 1259G INFO    General                 (distance_estimation.cpp   : 161)   Improving paired information
 43:05:29.695   358G / 1259G INFO   PairInfoImprover         (pair_info_improver.hpp    : 103)   Paired info stats: missing = 302387567; contradictional = 0
 44:42:55.212   368G / 1259G INFO   PairInfoImprover         (pair_info_improver.hpp    : 103)   Paired info stats: missing = 83808721; contradictional = 0
 44:42:55.217   368G / 1259G INFO    General                 (distance_estimation.cpp   : 104)   Filling scaffolding index
```

**Comment by asl** [comment]
This one required just 370 Gb of RAM. The old memory allocator (jemalloc) was known to overcommit a lot, so that 1.2Tb is likely an overkill.

**Comment by asl** [comment]
Just to give full explanation: it is the system `mmap` call (https://man7.org/linux/man-pages/man2/mmap.2.html) that returns error here. Maybe the reason is some memory fragmentation or other inability to allocate memory for a process – there is no additional information reported.

**Comment by hjruscheweyh** [comment]
Thank you for the info. I'm now running the same assembly with an older version of spades. Then we might be able to rule out some options.

For now I did random mmap() on the system and I can reach Virt/Res of >1.5TB for the 2TB system without any OOM errors.

**Comment by asl** [comment]
Well, likely the issue is much more subtle, e.g. you'd need to have lots of allocations / frees.

**Comment by asl** [comment]
@hjruscheweyh Maybe the issue is that vm.map_max_count is too low on your system?

Can you check via:
```
cat /proc/sys/vm/max_map_count
```

And see whether it is possible to increase it like this:
```
sudo sysctl -w vm.max_map_count=262144
```

**Comment by hjruscheweyh** [comment]
@asl 
```
[root][~]# cat /proc/sys/vm/max_map_count
65530

[root][~]#  sysctl vm.max_map_count=262144

[root][~]#  cat /proc/sys/vm/max_map_count
262144
```

I now restarted spades with `metaspades.py --continue -o spades`.

Lets see if it works.

Best,
Hans

**Comment by hjruscheweyh** [comment]
Hi @asl

Two things to report:

1. Running v3.14.1 on the same dataset but without updating vm.max_map_count worked beyond the point where v3.15.2 broke. But broke later with the memalloc error.
2. Running v3.15.2 with continue and after updating vm.max_map_count to  262144 worked and produced the typical spades output. 

So it seems that the update of the `max_map_count` variable fixes the issue. 

Can you tell me why you chose `262144` as the value? Reading https://docs.actian.com/vector/4.2/index.html#page/User/Increase_max_map_count_Kernel_Parameter_(Linux).htm states that the value could/should be 1 per 128kb of RAM which, in case of a 2TB server, would > 262144.

I'm very thankful that we found a fix as I will have a large number of deeply sequenced datasets to assemble. 

Would be worth to add this command in to the FAQ section?

best,
Hans

**Comment by asl** [comment]
Well.. these particular guidelines seems to be tuned to a particular memory usage of that product (Vector). My number was quite random, but just a power of two :)

**Comment by hjruscheweyh** [comment]
@asl thank you for the help. I will close this issue now.

**Comment by asl** [comment]
Thanks! We will think how to diagnose such cases in more automatic way...

**Comment by Ghepardo** [comment]
@asl Sorry to post to an issue you have closed, but do you have any further guidance on how to scale this kernel parameter?  You might say that it depends on the size of the input data, but there must be some relationship between that and the number of memory map areas required.  

Or are we faced with having to use guesswork and trial-and-error, helped perhaps by the advice at https://www.ibm.com/docs/en/safer-payments/6.1?topic=settings-increase-virtual-memory-map-size?

**Comment by asl** [comment]
@Ghepardo Indeed, the defaults are not very well suitable for high-memory applications. And it seems there is no good way to predict things in advance, especially judging from the size of the input. So, the guidelines as listed "monitor and increase if more than half are used" seems meaningful to me. I'd at least increase defaults from 64k to something that is several times larger. This might be enough for the majority of applications.
