### ISSUE TITLE
SPAdes error

### ISSUE THREAD

**Issue by Ahmedbargheet** [ablab/spades#874]
### Description of bug

Hi, 

I am running metaSPAdes, but I got the following error.
"== Error ==  system call for: "['/cluster/software/SPAdes/3.13.0-foss-2018b/bin/spades-hammer', '"

### spades.log

[spades.log](https://github.com/ablab/spades/files/7503948/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7503951/params.txt)

### SPAdes version

3.13.0

### Operating System

Saga

### Python Version

2.7.5

### Method of SPAdes installation

Installed by Saga

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Does the problem reproduces with the latest SPAdes 3.15.3?

**Comment by Ahmedbargheet** [comment]
This version is not installed on Saga. There are some data assembled without error, while others showed that error.

**Comment by asl** [comment]
I have no idea what Saga is. You might want to ask your system administrator for help

**Comment by Holyoke** [comment]
> 我不知道什么是佐贺。您可能需要向系统管理员寻求帮助

Hi,sir,I want to know what is the configuration of the computer on which the software is running

**Comment by asl** [comment]
@Ahmedbargheet please reopen if the issue is reproduced by the latest version of SPAdes.
