### ISSUE TITLE
spades-hammer & config.info finished abnormally, OS return value: -11

### ISSUE THREAD

**Issue by mwittep** [ablab/spades#875]
### Description of bug

Similar bug as presented in #862 #869 when running 
`spades.py --test`

`== Error ==  system call for: "['/home/XXX/SPAdes-3.15.3-Linux/bin/spades-hammer', '/home/XXX/test_spades/py38/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11`

I tried both, the Linux binaries and manual compilation. I have even used two different python versions to check if it is some kind of compatibility problem. The issue remains. 

### spades.log

[spades.log](https://github.com/ablab/spades/files/7538711/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7538710/params.txt)

### SPAdes version

3.15.3

### Operating System

Linux-5.1.7-arch1-1-ARCH-x86_64-with-arch

### Python Version

3.6.13 & 3.8.10

### Method of SPAdes installation

binaries & manual compilation

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

The problem seems to be completely different from #862 #869 And might be Arch Linux specific. Will you please attach the log from the run with the binaries compiled from sources?

**Comment by mwittep** [comment]
I was not able to reproduce the error with the compiled version - I don't really know why, but now it works. Thanks for the fast answer!
