### ISSUE TITLE
error during --test : system call for: "['/beegfs/home/gdebaecker/src/SPAdes-3.15.3-Linux/bin/spades-hammer', '/beegfs/home/gdebaecker/src/SPAdes-3.15.3-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11

### ISSUE THREAD

**Issue by sigau** [ablab/spades#876]
### Description of bug

Similar bug as the one on #875  but on Debian: 

While running spades.py --test to verify the good installation of spades we got this error : 
```
The program was terminated by segmentation fault
=== Stack Trace ===

== Error ==  system call for: "['/beegfs/home/gdebaecker/src/SPAdes-3.15.3-Linux/bin/spades-hammer', '/beegfs/home/gdebaecker/src/SPAdes-3.15.3-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -11
```

### spades.log

[spades.log](https://github.com/ablab/spades/files/7561514/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7561521/params.txt)

### SPAdes version

3.15.3

### Operating System

Linux-4.19.0-14-amd64-x86_64-with-debian-10.8

### Python Version

3.7.9

### Method of SPAdes installation

Binary

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Will you please compile SPAdes from sources?

**Comment by sigau** [comment]
It seem there is no more error with compilated code !
Thanks for your quick answer.
