### ISSUE TITLE
exceptions.AttributeError

### ISSUE THREAD

**Issue by mmfacun** [ablab/spades#877]
### Description of bug

Hello.

Please help with my error. I also tried changing the input type option (see below), but same error persists.

I also tried reducing -t to 4 and 2 but error still shows.

`spades.py --sc -o fasta --careful --pe-1 1 ph/SRR6027670_1.fastq.gz --pe-2 1 ph/SRR6027670_2.fastq.gz`

### spades.log

[spades.log](https://github.com/ablab/spades/files/7615055/spades.log)

### params.txt

[Uploading params.txt…]()

### SPAdes version

3.15.3

### Operating System

Windows 10

### Python Version

2.7.12

### Method of SPAdes installation

Docker

### No errors reported in spades.log

- [ ] Yes

**Comment by olga24912** [comment]
Hi @mmfacun

Thank you for using SPAdes and your bug report! We will fix it in the next SPAdes release. 

However, even if it worked properly, you would still have an exit_code=-11 and next ERROR message:
1. WSL is an unsupported platform
2. If SPAdes crashes, then you might want to compile it from sources
3. If nothing works, run on real Linux

So, please, try to follow these recommendations. 

Best, 
Olga

**Comment by asl** [comment]
WSL checks are introduced in https://github.com/ablab/spades/releases/tag/v3.15.4
