### ISSUE TITLE
Spades error while usinng metaspades.py == Error ==  system call for: 

### ISSUE THREAD

**Issue by ap1438** [ablab/spades#879]
### Description of bug

== Error ==  system call for: "['/home/internal/Sys_Bio/group_gaurav01/Tools/SPAdes-3.15.3-Linux/bin/spades-hammer', '/home/internal/Sys_Bio/group_gaurav01/Akash_tab/ICAR_Data/Working_data/Trimmomatic/Metaspades/corrected/configs/config.info']" finished abnormally, OS return value: -9
None

This is the error while running metaspades with this command .      
/Tools/SPAdes-3.15.3-Linux/bin/metaspades.py --pe1-1 SK_1-forward_paired.fq.gz  --pe1-2 SK_1-reverse_paired.fq.gz --pe1-s SK_1-forward_unpaired.fq.gz --pe1-s SK_1-reverse_unpaired.fq.gz -t 10  -o ../Metaspades/

### spades.log

[spades.log](https://github.com/ablab/spades/files/7718447/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7718468/params.txt)

### SPAdes version

SPAdes version: 3.15.3

### Operating System

OS: Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core

### Python Version

Python version: 3.7.10

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [ ] Yes

**Comment by asl** [comment]
Your SPAdes job was killed. Likely more information could be found in the system log.
