### ISSUE TITLE
Need help running spades NGS Bacterial data 

### ISSUE THREAD

**Issue by Gwendoline998** [ablab/spades#88]
Hello everybody, 
I am a beginner with NGS analysis, I am trying to run spades on bacterial data but have error messages don't know how to fix it, could you help me please. I made the QC step + trimming with Trimmomatic then I prepared a script for the genome assembly (reads are 101 bp) 
spades.py -1 frw.fastq -2 rev.fastq --careful --threads 6 -m 12 -k 21,33,55,77 --cov-cutoff auto -o assembly_E_coli
is my script correct ? 
here is the message: 
- left reads: [/auto/plzen1/home/students/frw.fastq]
  orientation: fr
  right reads: [/auto/plzen1/home/students/rev.fastq]
  type: paired-end
please help me to fix it thanks a lottttttttttttttt

**Comment by Gwendoline998** [comment]
Hi asl 
thank's for your comment 
my spades is running for while then finishing, no outputs exept this message 
- left reads: [/auto/plzen1/home/students/SRR1781795_1v2.fastq]
  orientation: fr
  right reads: [/auto/plzen1/home/students/SRR1781795_2v2.fastq]
  type: paired-end
here is the script 
spades.py -1 file1.fastq -2 file2.fastq --careful --threads 6 -m 12 -k 77,99,127 --phred-offset 33 --cov-cutoff auto -o assembly
my reads are more than 230 bp ;(

**Comment by asl** [comment]
Then, I doubt we could help you. Still the files are in the output directory.

You may want to ask your system administrator for the help with running the software.

**Comment by Gwendoline998** [comment]
could the trimming be the reason ? I trimmed my reads on galaxy website may be I selected wrong parameters on Trimmomatic ? what do you think ?

**Comment by asl** [comment]
No idea.

**Comment by Gwendoline998** [comment]
thank"s :=)

**Comment by Gwendoline998** [comment]
Hello again, 

I could perform the genome assembly but its evaluation gave to kinds of scaffolds: scaffolds + scaffolds broken.
what do scaffolds broken means and how can I correct this ???? 

thank"s

**Comment by asl** [comment]
Glad you finally could perform an assembly. Please refer to SPAdes manual (http://cab.spbu.ru/files/release3.11.1/manual.html#sec3.5) with respect to SPAdes output.
