### ISSUE TITLE
OS return value: 4 (reinstall didn't fix the problem)

### ISSUE THREAD

**Issue by maureenbug** [ablab/spades#887]
### Description of bug

I saw a few other people post this same error message ("Exception caught conversion of data to type "i" failed"), but
1) a fresh reinstall of spades doesn't fix the issue, and
2) when I try to run it on data that worked fine with spades a few months ago, I get the same error message

I am also asking around to other users on the cluster, but I wanted to see if perhaps y'all have any ideas of what might be causing this issue

thanks!
maureen

### spades.log

[spades.log](https://github.com/ablab/spades/files/7824125/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7824128/params.txt)

### SPAdes version

3.15.3

### Operating System

linux cluster

### Python Version

3.8.5

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
` 
 Memory limit (in Gb): 100000000000000
`

This setting is certainly bogus. You may want to check your command line options (e.g. `-m` option)
