### ISSUE TITLE
finished abnormally err: -9

### ISSUE THREAD

**Issue by Docolli13** [ablab/spades#89]
I am having a similar issue to #76, however I am able to share the data i am working with. Two paired reads of a cyanobacterial genome. Below is the original output:

Command line: ../../../scripts/SPAdes-build/SPAdes-3.11.1/bin/spades.py	--pe1-1	/galadriel/gerid/projects/Cyano23-Webb/EW-1-23_S1_L001_R1_001.fastq	--pe1-
2	/galadriel/gerid/projects/Cyano23-Webb/EW-1-23_S1_L001_R2_001.fastq	-o	/galadriel/gerid/projects/Cyano23-Webb/SPAdes-assembly/EW-23	

System information:
  SPAdes version: 3.11.1
  Python version: 3.6.4
  OS: Linux-3.13.0-101-generic-x86_64-with-debian-jessie-sid

Output dir: /galadriel/gerid/projects/Cyano23-Webb/SPAdes-assembly/EW-23
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/galadriel/gerid/projects/Cyano23-Webb/EW-1-23_S1_L001_R1_001.fastq']
      right reads: ['/galadriel/gerid/projects/Cyano23-Webb/EW-1-23_S1_L001_R2_001.fastq']
      interlaced reads: not specified
      single reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed (with gzip)
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /galadriel/gerid/projects/Cyano23-Webb/SPAdes-assembly/EW-23/tmp
  Threads: 16
  Memory limit (in Gb): 125

======= SPAdes pipeline started. Log can be found here: /galadriel/gerid/projects/Cyano23-Webb/SPAdes-assembly/EW-23/spades.log

===== Read error correction started. 

== Running read error correction tool: /galadriel/gerid/scripts/SPAdes-build/SPAdes-3.11.1/bin/hammer /galadriel/gerid/projects/Cyano23-Webb/SPAdes-assembly/E
W-23/corrected/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  83)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.003     4M / 4M    INFO    General                 (main.cpp                  :  84)   Loading config from /galadriel/gerid/projects/Cyano23-Webb/SP
Ades-assembly/EW-23/corrected/configs/config.info
  0:00:00.006     4M / 4M    INFO    General                 (memory_limit.hpp          :  51)   Memory limit set to 125 Gb
  0:00:00.006     4M / 4M    INFO    General                 (main.cpp                  :  93)   Trying to determine PHRED offset
  0:00:00.089     4M / 4M    INFO    General                 (main.cpp                  :  99)   Determined value is 33
  0:00:00.090     4M / 4M    INFO    General                 (hammer_tools.cpp          :  36)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 
10 ]
  0:00:00.090     4M / 4M    INFO    General                 (main.cpp                  : 120)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.091     4M / 4M    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 289)   Building kmer index
  0:00:00.091     4M / 4M    INFO    General                 (kmer_index_builder.hpp    : 106)   Splitting kmer instances into 256 buckets using 16 threads. T
his might take a while.
  0:00:00.092     4M / 4M    INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1024
  0:00:00.092     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  74)   Memory available for splitting buffers: 2.60409 Gb
  0:00:00.092     4M / 4M    INFO    General                 (kmer_splitters.hpp        :  82)   Using cell size of 262144
  0:00:03.635     8G / 8G    INFO   K-mer Splitting          (kmer_data.cpp             :  96)   Processing /galadriel/gerid/projects/Cyano23-Webb/EW-1-23_S1_
L001_R1_001.fastq
  0:00:45.008     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 1367052 reads
  0:01:24.954     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 2808731 reads
  0:02:22.142     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 3886468 reads
  0:03:19.682     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 4877073 reads
  0:04:11.213     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 6184252 reads
  0:04:11.214     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             :  96)   Processing /galadriel/gerid/projects/Cyano23-Webb/EW-1-23_S1_
L001_R2_001.fastq
  0:05:24.023     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 7422385 reads
  0:06:37.016     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 8820370 reads
  0:07:58.532     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 10130652 reads
  0:08:57.936     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 106)   Processed 11521229 reads
  0:09:54.821     8G / 9G    INFO   K-mer Splitting          (kmer_data.cpp             : 111)   Total 12368504 reads processed
  0:09:57.449    64M / 9G    INFO    General                 (kmer_index_builder.hpp    : 109)   Starting k-mer counting.
  0:13:47.746    64M / 9G    INFO    General                 (kmer_index_builder.hpp    : 115)   K-mer counting done. There are 1748783794 kmers in total.
  0:13:47.747    64M / 9G    INFO    General                 (kmer_index_builder.hpp    : 121)   Merging temporary buckets.
  0:15:24.271    64M / 9G    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 298)   Building perfect hash indices
  0:18:44.957   964M / 9G    INFO    General                 (kmer_index_builder.hpp    : 137)   Merging final buckets.
  0:20:35.106   964M / 9G    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 320)   Index built. Total 810924052 bytes occupied (3.70966 bits per
 kmer).
  0:20:35.110   964M / 9G    INFO   K-mer Counting           (kmer_data.cpp             : 357)   Arranging kmers in hash map order
  0:29:48.755    27G / 27G   INFO    General                 (main.cpp                  : 155)   Clustering Hamming graph.
  2:50:44.591    27G / 27G   INFO    General                 (main.cpp                  : 162)   Extracting clusters

== Error ==  system call for: "['/galadriel/gerid/scripts/SPAdes-build/SPAdes-3.11.1/bin/hammer', '/galadriel/gerid/projects/Cyano23-Webb/SPAdes-assembly/EW-2
3/corrected/configs/config.info']" finished abnormally, err code: -9

Thank you,
Geri

**Comment by asl** [comment]
No. The issue here is completely different. Most probably you're running out of RAM and SPAdes instance was killed by OOM handler. You may want to check your system log for more information about this.

**Comment by Docolli13** [comment]
Ok. Thanks for the quick response. I'll check.

**Comment by Docolli13** [comment]
How much RAM should SPAdes typically require for assembling a bacterial genome?
We have ~125G of RAM here

**Comment by asl** [comment]
Everything depends on the dataset in question, e.g. coverage, error rate, repeat content, etc. And also you'd need to make sure you're having enough *free* RAM.

In your case it seems you're having quite large dataset with almost 2 billion distinct k-mers inside.
