### ISSUE TITLE
error running plasmidspade - value returned 12 and -6

### ISSUE THREAD

**Issue by blooria** [ablab/spades#896]
### Description of bug

Hi,
I have an error running plasmidspades;
mimalloc: error: unable to allocate OS memory (1421869056 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:    1006.282 s
   process: user: 6805.626 s, system: 76.480 s, faults: 22939
       rss: current: 6217297920, peak: 5428969472
    commit: current: 6217297920, peak: 6217297920

== Error ==  system call for: "['/home/mor/miniconda3/envs/assembly/bin/spades-hammer', '/home/mor/spades_test/test/corrected/configs/config.info']" finished abnormally, OS return value: -6
None

Any help would be appreciated,

### spades.log

Command line: /home/miniconda3/envs/assembly/bin/plasmidspades.py	-1	/home/R1_001.fastq.gz	-2	/home/R2_001.fastq.gz	-o	/home/mor/spades_test/test	

System information:
  SPAdes version: 3.15.3
  Python version: 3.8.12
  OS: Linux-5.13.0-27-generic-x86_64-with-glibc2.10

Output dir: /home/mor/spades_test/test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/mor/Desktop/schneider/4974961_L001-ds.a6bbe2c4dbae4aaab7834b6c23a7cd6b/4974961_S32_L001_R1_001.fastq.gz']
      right reads: ['/home/mor/Desktop/schneider/4974961_L001-ds.a6bbe2c4dbae4aaab7834b6c23a7cd6b/4974961_S32_L001_R2_001.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Extrachromosomal mode is turned ON
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/mor/spades_test/test/tmp
  Threads: 16
  Memory limit (in Gb): 7

======= SPAdes pipeline started. Log can be found here: /home/mor/spades_test/test/spades.log

/home/mor/Desktop/schneider/4974961_L001-ds.a6bbe2c4dbae4aaab7834b6c23a7cd6b/4974961_S32_L001_R1_001.fastq.gz: max reads length: 151
/home/mor/Desktop/schneider/4974961_L001-ds.a6bbe2c4dbae4aaab7834b6c23a7cd6b/4974961_S32_L001_R2_001.fastq.gz: max reads length: 151

Reads length: 151

Default k-mer sizes were set to [21, 33, 55, 77, 99, 127] because estimated read length (151) is equal to or greater than 150

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /home/mor/miniconda3/envs/assembly/bin/spades-hammer /home/mor/spades_test/test/corrected/configs/config.info

  0:00:00.000     1M / 16M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.000     1M / 16M   INFO    General                 (main.cpp                  :  76)   Loading config from /home/mor/spades_test/test/corrected/configs/config.info
  0:00:00.001     1M / 16M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 8
  0:00:00.001     1M / 16M   INFO    General                 (memory_limit.cpp          :  48)   Memory limit set to 7 Gb
  0:00:00.001     1M / 16M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.002     1M / 16M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.002     1M / 16M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.002     1M / 16M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.002     1M / 16M   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 8 threads. This might take a while.
  0:00:00.002     1M / 16M   INFO    General                 (file_limit.hpp            :  32)   Open file limit set to 1024
  0:00:00.003     1M / 16M   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 0.291663 Gb
  0:00:00.003     1M / 16M   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 2446645
  0:00:00.003  2689M / 2689M INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/mor/Desktop/schneider/4974961_L001-ds.a6bbe2c4dbae4aaab7834b6c23a7cd6b/4974961_S32_L001_R1_001.fastq.gz
  0:00:19.573  2689M / 2975M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 989101 reads
  0:00:38.913  2689M / 2989M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1982763 reads
  0:00:58.881  2689M / 2989M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 2968947 reads
  0:01:18.159  2689M / 2989M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 3958157 reads
  0:01:38.242  2689M / 2997M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4953417 reads
  0:01:57.643  2689M / 2997M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 5947862 reads
  0:02:17.622  2689M / 2997M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 6936646 reads
  0:02:36.927  2689M / 2997M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 7928307 reads
  0:02:56.492  2689M / 2997M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 8919072 reads
  0:03:37.009  2689M / 3001M INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/mor/Desktop/schneider/4974961_L001-ds.a6bbe2c4dbae4aaab7834b6c23a7cd6b/4974961_S32_L001_R2_001.fastq.gz
  0:05:35.524  2689M / 3078M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 16911055 reads
  0:07:14.892  2689M / 3080M INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 21914228 reads processed
  0:07:14.892     1M / 3080M INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  0:08:17.229     1M / 3080M INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 177113126 kmers in total.
  0:08:17.230     1M / 3080M INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  0:08:34.685   130M / 3080M INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 177113126 kmers, 127934072 bytes occupied (5.77864 bits per kmer).
  0:08:34.685   130M / 3080M INFO   K-mer Counting           (kmer_data.cpp             : 354)   Arranging kmers in hash map order
  0:08:49.033  2835M / 3080M INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  0:15:55.759  2835M / 3080M INFO    General                 (main.cpp                  : 155)   Extracting clusters:
  0:15:55.760  2835M / 3080M INFO    General                 (concurrent_dsu.cpp        :  18)   Connecting to root
  0:15:57.284  2835M / 3080M INFO    General                 (concurrent_dsu.cpp        :  34)   Calculating counts
  0:16:46.281  5011M / 5178M INFO    General                 (concurrent_dsu.cpp        :  63)   Writing down entries
mimalloc: error: unable to allocate OS memory (1421869056 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
mimalloc: process info:
   elapsed:    1006.282 s
   process: user: 6805.626 s, system: 76.480 s, faults: 22939
       rss: current: 6217297920, peak: 5428969472
    commit: current: 6217297920, peak: 6217297920

== Error ==  system call for: "['/home/mor/miniconda3/envs/assembly/bin/spades-hammer', '/home/mor/spades_test/test/corrected/configs/config.info']" finished abnormally, OS return value: -6
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/mor/spades_test/test/spades.log

Thank you for using SPAdes!

### params.txt

plasmidspades.py -1 /home/R1_001.fastq.gz -2 /home/R2_001.fastq.gz -o test

### SPAdes version

SPAdes genome assembler v3.15.3 [plasmidSPAdes mode]

### Operating System

ubuntu 

### Python Version

Python 3.8.12

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The error clearly reads:

```
mimalloc: error: unable to allocate OS memory (1421869056 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)
```
