### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by jhernandez1409** [ablab/spades#90]
Hi,

I am trying to run Spades to extract plasmids reads and I got this error:

Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Invalid argument. Error code: 22'.
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Invalid argument. Error code: 22'.
hammer: /spades/src/common/io/kmers/mmapped_writer.hpp:94: void MMappedWriter::reserve(size_t): Assertion `(intptr_t) MappedRegion != -1L' failed.

== Error ==  system call for: "['/home/jojo/Desktop/Bioinformatic_software/SPAdes-3.11.1-Linux/bin/hammer', '/media/sf_U_DRIVE/Tanzania/Output_spades/10832wA1_Wat1A9/corrected/configs/config.info']" finished abnormally, err code: -6

Can someone tell me whats the problem and how can I fix it?

Thanks in advance,

JoJo
[spades.log](https://github.com/ablab/spades/files/1800025/spades.log)

**Comment by asl** [comment]
As far s I can see, you're running SPAdes inside a VM and the output directory is on the shared folder. VirtualBox has broken implementation of memory mapped files on top of shared folders, hence the error. In short: you cannot use shared folder as SPAdes scratch directory due to VirtualBox bug.

**Comment by jhernandez1409** [comment]
oh, I see... I will move the folders locally. Thank you so much for your help! :)
