### ISSUE TITLE
mimalloc: warning: maximum regions used:

### ISSUE THREAD

**Issue by Moony00** [ablab/spades#900]
### Description of bug

Good morning and always thanks for your great SPAdes!
Here are some warning messages from mimalloc, and I'm not sure if my SPAdes uses all memory that I intended (the tool is still ongoing).
I've searched MI_HEAP_REGION_MAX_SIZE option in SPAdes manual, but I couldn't find since it was from mimalloc :D.. and I couldn't search any other option about memory, or anything I can do now. It would be really thankful if there's any advice for this memory allocate problem. 
Have a nice day!

-K21
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304

-K33
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304

K55
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
mimalloc: warning: unable to allocate from region: size 4194304
 
K77 (still processing)
mimalloc: warning: maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)mimalloc: warning: mimalloc: warning: mimalloc: warning: maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)unable to allocate from region: size 54788096
mimalloc: warning: mimalloc: warning: mimalloc: warning: maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)mimalloc: warning: mimalloc: warning: maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)mimalloc: warning: mimalloc: warning: mimalloc: warning: unable to allocate from region: size 54788096
unable to allocate from region: size 54788096
unable to allocate from region: size 54788096
mimalloc: warning: unable to allocate from region: size 54788096
maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)mimalloc: warning: mimalloc: warning: mimalloc: warning: unable to allocate from region: size 54788096
mimalloc: warning: unable to allocate from region: size 54788096
maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)unable to allocate from region: size 54788096

### spades.log

[spades.log](https://github.com/ablab/spades/files/7921904/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7921906/params.txt)

### SPAdes version

SPAdes 3.15.3

### Operating System

Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.10

### Python Version

Python 3.8.12

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

So far these warnings are benign. So you can simply ignore them
