### ISSUE TITLE
hammer err code: 6 

### ISSUE THREAD

**Issue by parkjongbin** [ablab/spades#91]
Hello, I've sequenced one bacteria genome using HiSeq platform (2x150bp). Sequencing depths are good (almost 330-fold). I typed the commands like in the below, but some error reported and spades is not working. Those anyone help that problems?

**Command**
**/home/ebkim/BioSW/SPAdes-3.11.1-Linux/bin/spades.py \
    -t 48 -k  21 --careful \
    -o spades_output \
    -1 Adaptor_Filtered_Reads/JB8_AS1D0I0_97perc_over90bp_64cutoff_F_pair.fastq \
    -2 Adaptor_Filtered_Reads/JB8_AS1D0I0_97perc_over90bp_64cutoff_R_pair.fastq \
    -s Adaptor_Filtered_Reads/JB8_AS1D0I0_97perc_over90bp_64cutoff_single.fastq**

=== Stack Trace ===
[0x407a6a]
[0x409561]
[0x40c79b]
[0x40129a]
[0x5442b0]
[0x40620d]
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Invalid argument. Error code: 22'.
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'void MMappedWriter::reserve(size_t)'. In file '/spades/src/common/io/kmers/mmapped_writer.hpp' on line 94. Message 'mmap(2) failed. Reason: Invalid argument. Error code: 22'.
hammer: /spades/src/common/io/kmers/mmapped_writer.hpp:94: void MMappedWriter::reserve(size_t): Assertion `(intptr_t) MappedRegion != -1L' failed.

== Error ==  system call for: "['/home/ebkim/BioSW/SPAdes-3.11.1-Linux/bin/hammer', '/home/ebkim/share/180319_EfaeciumJB00008_HiSeq/Adaptor_Filtered_Reads/JB8_AS1D0I0_97perc_over90bp_64cutoff_17mer/corrected/configs/config.info']" finished abnormally, err code: -6

[params.txt](https://github.com/ablab/spades/files/1840903/params.txt)
[spades.log](https://github.com/ablab/spades/files/1840904/spades.log)

Sincerely,
Department of Animal Life System, Kangwon National University (KNU),
Chuncheon, Republic of Korea.
Lab of Microbial Genomics and Big Data, College of Animal Life Sciences.
Jongbin Park

**Comment by asl** [comment]
Are you running SPAdes inside a VM?

**Comment by parkjongbin** [comment]
Yes, my linux (Lubuntu 17.04) was installed in the Oracle VM VirtualBox. Previous results are good (i've already assembled many genomes using VM), but i don't know why theses commands are shown.

**Comment by asl** [comment]
VirtualBox has a broken implementation of memory mapped files on top of its shared folders. So, you cannot have SPAdes scratch directory located inside VirtualBox shared folder. "Normal" folder inside VM is ok. Input / output files could be located on shared folder. You can use --tmp-dir option to specify the location of scratch folder.

**Comment by parkjongbin** [comment]
Okay, I will try. Thank you very much for your kind explanation.
