### ISSUE TITLE
Error code 28

### ISSUE THREAD

**Issue by asl** [ablab/spades#912]
### Discussed in https://github.com/ablab/spades/discussions/911

<div type='discussions-op-text'>

<sup>Originally posted by **stephen-14** February  9, 2022</sup>
Hello, I've tried to run my assembly with SPAdes 3.12.0 during processing I faced with problem #28. I check the memory of my PC is still enough. 
Thanks for your help!
[params.txt](https://github.com/ablab/spades/files/8039077/params.txt)
[spades.log](https://github.com/ablab/spades/files/8039079/spades.log)
 </div>

**Comment by asl** [comment]
The log clearly reads:

```
  0:02:45.447  9629M / 9629M ERROR   General                 (kmer_splitter.hpp         : 150)   I/O error! Incomplete write! Reason: No space left on device. Error code: 28
```

**Comment by xhx-1** [comment]
Hello, have you solved this problem yet?
