### ISSUE TITLE
Spades err cod -6 for trimmed fastq

### ISSUE THREAD

**Issue by artmisk13** [ablab/spades#915]
### Description of bug

Hi,

I use spades for genome assembly and it had worked fine with my fastq files from Illumina sequencing. However, I trimmed the file (using Trimmomatic) and Spades keeps giving me back this error (attached in spades.log) only when I tried to assemble these trimmed files. Please kindly advise and suggest what I should do.

### spades.log

[spades.log](https://github.com/ablab/spades/files/8048837/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8048839/params.txt)

### SPAdes version

SPAdes v3.13.1

### Operating System

Ubuntu 20.04

### Python Version

Python 3.8.10

### Method of SPAdes installation

ubuntu package installer

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

The log reads:
```
  0:00:28.876   272M / 3G    INFO    General                 (pair_info_count.cpp       : 211)   6 paired reads (0.00198136% of all) aligned to long edges
  0:00:28.879   192M / 3G    INFO    General                 (pair_info_count.cpp       : 353)     Insert size = 305.5, deviation = 72.4494, left quantile = 212, right quantile = 421, read length = 300
```

So, likely your reads are corrupted, e.g. the left ones do not correspond to the right ones. Please ensure you're using a paired-end aware trimmer

**Comment by artmisk13** [comment]
Thanks for the answer!
