### ISSUE TITLE
err code: -9?

### ISSUE THREAD

**Issue by cbeekman** [ablab/spades#917]
### Description of bug

I am wondering if I can get a hint at what went wrong in a recent run based on the error code itself? I can't find any other obvious (to me) clues as to what went wrong in scanning the log file. Is there a place where I can find meaning of different code #'s?

I am running Spades as part of the metawrap pipeline and running batches of ~12 concatenated sample files of somewhat similar # of reads (paired end data, so 2 files per batch). **The first batch was successful** however the second batch of samples errored out (after ~36h or so 😒) with this error message: 

(also see log.txt): == Error ==  system call for: "['/gpfs/home/cbeekman/miniconda2/envs/metawrap/share/spades-3.13.0-0/bin/spades-core', '/users/cbeekman/scratch/GImapping/metaDNA/metawrap/ASSEMBLIES/PSI/metaspades/K55/configs/config.info', '/users/cbeekman/scratch/GImapping/metaDNA/metawrap/ASSEMBLIES/PSI/metaspades/K55/configs/mda_mode.info', '/users/cbeekman/scratch/GImapping/metaDNA/metawrap/ASSEMBLIES/PSI/metaspades/K55/configs/meta_mode.info']" finished abnormally, err code: -9

The first batch of samples that was successful was actually only 11 samples as I had to remove one from this batch, so perhaps the second batch with one more samples worth of reads just put the memory requirement over the limit, ... but previously the error in the case of insufficient memory was pretty obvious. ...?

### spades.log

[spades.log](https://github.com/ablab/spades/files/8064162/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8064165/params.txt)

### SPAdes version

3.13.0

### Operating System

Linux-3.10.0-1062.el7.x86_64-x86_64-with-redhat-7.7-Maipo

### Python Version

2.7.15

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Your SPAdes job was killed. Likely due to OOM, but more information could be found in the system log. Likely you'd need to ask your system administrator for this.

Also, I would strongly suggest you to upgrade from the ancient SPAdes 3.13 to the latest SPAdes 3.15.4 which has much better memory performance among other fixes and improvements

**Comment by cbeekman** [comment]
Ok thanks for your response!
