### ISSUE TITLE
Error during running hybrid assembly with pacbio files

### ISSUE THREAD

**Issue by shrutidabral** [ablab/spades#92]
hello , 

I am using spades for Hybrid assembly of illumina reads with pacbio reads .

command i used is 
./spades.py -t	6 -1 L4_1.fq  -2 L4_2.fq --pacbio  p0.1.subreads.fastq -o 2k_withpacbio 

after this command i got all the files and with messeage of 
=== Error correction and assembling warnings:
 * 0:09:17.997     6G / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 15
 * 0:11:52.721     7G / 8G    WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:12:11.031     7G / 8G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 9
 * 0:12:11.034     7G / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 9
 * 0:15:09.136    10G / 11G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 14
 * 0:15:09.139    10G / 11G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 14
 * 0:19:48.108     9G / 10G   WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 10
 * 0:19:48.110     9G / 10G   WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 10

I can not understand by this warning is came .

**Second time i want to run assembly with 3 dataset of pacbio file** 
command i used is 

./spades.py -t	6 -1 L4_1.fq  -2 L4_2.fq --s1  p0.1.subreads.fastq --s1  p0.2.subreads.fastq  --s3 p0.3.subreads.fastq  -o output_pac

ouput error is 
== Error ==  system call for: "['/home/mobashirm/Documents/SPAdes-3.11.1/bin/hammer', '/home/mobashirm/PRJ2018jan2018/hybrid_genome_assembly/illumina/illuminadata/2k_withpacbio_3file_27march/corrected/configs/config.info']" finished abnormally, err code: 1

I am able to understand how put pacbio files in command .

please help me out .

**Comment by asl** [comment]
Please attache your spades.log and params.txt files as you were instructed in the error message (just 2 lines below the ones you copied).

**Comment by shrutidabral** [comment]
please find the attachment. 

[params.txt](https://github.com/ablab/spades/files/1851800/params.txt)
[spades.log](https://github.com/ablab/spades/files/1851801/spades.log)

**Comment by asl** [comment]
You need to provide PacBio reads via --pacbio option. See http://cab.spbu.ru/files/release3.11.1/manual.html#sec3.1 for more information.

**Comment by shrutidabral** [comment]
Thankyou ,

I did this step also , now getting these error...

=== ERRORs:
 * system call for: "['/home/mobashirm/Documents/SPAdes-3.11.1/bin/spades', '/home/mobashirm/PRJ2018jan2018/hybrid_genome_assembly/illumina/illuminadata/2k_withpacbio_3file_27march_test/K77/configs/config.info', '/home/mobashirm/PRJ2018jan2018/hybrid_genome_assembly/illumina/illuminadata/2k_withpacbio_3file_27march_test/K77/configs/careful_mode.info']" finished abnormally, err code: -6


[params.txt](https://github.com/ablab/spades/files/1854576/params.txt)
[spades.log](https://github.com/ablab/spades/files/1854577/spades.log)



This is my request to you ---
Can you please explain me the relation between coverage and kmer with dataset and what value should assign to kmer ?

**Comment by asl** [comment]
> I did this step also , now getting these error...

This is the known issue of SPAdes 3.11.1 that will be fixed in 3.12

The relation between coverage and k-mer length is very complex. Normally we'd recommend to stick to default settings unless you 100% sure what you're doing
