### ISSUE TITLE
SPAdes crashes with memory allocation error

### ISSUE THREAD

**Issue by fplaza** [ablab/spades#920]
### Description of bug

Hello,

I used SPAdes in hybrid metagenomic mode by combining DNBSEQ-T7 short reads and PacBio CCS reads.
SPAdes crashes with a memory allocation error. Yet the amount of memory available on my machine seems largely sufficient (250 Gb).

Could you help?

### spades.log

[dnbseq_t7.pacbio.spades.log](https://github.com/ablab/spades/files/8077758/dnbseq_t7.pacbio.spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8077759/params.txt)

### SPAdes version

3.15.4

### Operating System

Centos 7

### Python Version

2.7.5

### Method of SPAdes installation

Linux binaries available on GitHub

### No errors reported in spades.log

- [x] Yes

**Comment by asl** [comment]
Likely the reason is the use of CCS reads as normal "single ones". The workaround is to use them as "--pacbio".

**Comment by fplaza** [comment]
Ok. I will give it a try.
However, the documentation says to use the -s option for CCS reads

```
--pacbio <file_name>
    File with PacBio CLR reads. For PacBio CCS reads use -s option

Single librairies are assumed to have high quality and a reasonable coverage. For example, you can provide PacBio CCS reads as a single-read library
```

**Comment by asl** [comment]
Well, highly likely your CCS reads are of worse quality than they used to be several years ago when this suggestion was written.

**Comment by fplaza** [comment]
After mapping reads against the corresponding complete genomes  (this is a mock community), error rate is about 0.3% (mainly indels)

**Comment by asl** [comment]
Well, mapping error rates are always biased towards lower values due to many reasons including e.g. soft / hard clipping, reads that do not align and also differences between assembly process and alignment (note that the reads are assembled together so the "mutual" error rate at least doubles).

**Comment by EisenRa** [comment]
I too have had the same issue as @fplaza for hybrid assembly with HiFi CCS/illumina reads. 

Using '-s' to input the CCS reads (mean 18 passes, median Q42) resulted in stalling/failing at the same step (even with a 1.5 TB RAM node). 

I can confirm that passing the CCS reads through '--pacbio' did allow spades to run to completion.

**Comment by asl** [comment]
@EisenRa Will you please post spades.log from failed and successful runs? We never saw Illumina/HiFi hybrid assemblies, the manual says about "old" CCSv1 reads.

**Comment by asl** [comment]
Please reopen if this is still a problem
