### ISSUE TITLE
metaspades gives no contigs.fasta file

### ISSUE THREAD

**Issue by parulbaranwal** [ablab/spades#921]
### Is your feature request related to a problem? Please describe. For generic questions use Q&A section in the Discussions forum above.

I am using metaspades and I do not find any contigs.fasta file which I assume is the main file. 
I dig into log file and i found the error mentioned below. I dont understand what it means

== Error ==  system call for: "['/home/utad/pbaranw/parul/metaspades/SPAdes-3.15.4/bin/spades-hammer', '/home/utad/pbaranw/parul/spades_output/corrected/configs/config.info']" finished abnormally, OS return value: 21

Would appreciate any help.

thanks

**Comment by asl** [comment]
Please use "Problem / bug report" issue template. Thanks
