### ISSUE TITLE
system call for: "['/home/host/SPAdes-3.15.4-Linux/bin/spades-hammer', '/home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -9 None

### ISSUE THREAD

**Issue by wfavgbbx** [ablab/spades#922]
### Description of bug

== Error ==  system call for: "['/home/host/SPAdes-3.15.4-Linux/bin/spades-hammer', '/home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -9
None

### spades.log

./spades.py --careful --pe1-1 /home/host/Downloads/29566-pair1.fq --pe1-2 /home/host/Downloads/29566-pair2.fq -o ./spades_test

== Warning ==  No assembly mode was specified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option.

Command line: ./spades.py	--careful	--pe1-1	/home/host/Downloads/29566-pair1.fq	--pe1-2	/home/host/Downloads/29566-pair2.fq	-o	/home/host/SPAdes-3.15.4-Linux/bin/spades_test	

System information:
  SPAdes version: 3.15.4
  Python version: 3.9.7
  OS: Linux-5.13.0-30-generic-x86_64-with-glibc2.31

Output dir: /home/host/SPAdes-3.15.4-Linux/bin/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/host/Downloads/29566-pair1.fq']
      right reads: ['/home/host/Downloads/29566-pair2.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/host/SPAdes-3.15.4-Linux/bin/spades_test/tmp
  Threads: 16
  Memory limit (in Gb): 8

======= SPAdes pipeline started. Log can be found here: /home/host/SPAdes-3.15.4-Linux/bin/spades_test/spades.log

/home/host/Downloads/29566-pair1.fq: max reads length: 150
/home/host/Downloads/29566-pair2.fq: max reads length: 150

Reads length: 150

Default k-mer sizes were set to [21, 33, 55, 77] because estimated read length (150) is equal to or greater than 150

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /home/host/SPAdes-3.15.4-Linux/bin/spades-hammer /home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info

  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.15.4, git revision 1a5332e5608a073a9d28a6d0e30836f38dcc5613
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  76)   Loading config from /home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 4
  0:00:00.000     1M / 10M   INFO    General                 (memory_limit.cpp          :  54)   Memory limit set to 8 Gb
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.000     1M / 10M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.001     1M / 10M   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 4 threads. This might take a while.
  0:00:00.001     1M / 10M   INFO    General                 (file_limit.hpp            :  42)   Open file limit set to 1024
  0:00:00.001     1M / 10M   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 0.666659 Gb
  0:00:00.001     1M / 10M   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 4194304
  0:00:00.001  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/host/Downloads/29566-pair1.fq
  0:00:07.688  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 621253 reads
  0:00:15.431  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1255181 reads
  0:00:24.179  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1996652 reads
  0:00:33.966  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 2749173 reads
  0:00:42.341  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 3426694 reads
  0:00:50.384  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4082180 reads
  0:00:50.437  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4085217 reads
  0:00:50.437  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/host/Downloads/29566-pair2.fq
  0:00:59.148  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4761443 reads
  0:01:40.645  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 8170434 reads processed
  0:01:40.645     1M / 1896M INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  0:01:45.354     1M / 1896M INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 208421038 kmers in total.
  0:01:45.354     1M / 1896M INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  0:01:57.235   149M / 1896M INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 208421038 kmers, 150546912 bytes occupied (5.77857 bits per kmer).
  0:01:57.235   149M / 1896M INFO   K-mer Counting           (kmer_data.cpp             : 354)   Arranging kmers in hash map order
  0:02:07.696  3334M / 3458M INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  0:12:22.001  3334M / 3458M INFO    General                 (main.cpp                  : 155)   Extracting clusters:
  0:12:22.001  3334M / 3458M INFO    General                 (concurrent_dsu.cpp        :  18)   Connecting to root
  0:12:23.696  3334M / 3458M INFO    General                 (concurrent_dsu.cpp        :  34)   Calculating counts
  0:12:44.852  5510M / 5629M INFO    General                 (concurrent_dsu.cpp        :  63)   Writing down entries

== Error ==  system call for: "['/home/host/SPAdes-3.15.4-Linux/bin/spades-hammer', '/home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -9
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/host/SPAdes-3.15.4-Linux/bin/spades_test/spades.log

Thank you for using SPAdes!

### params.txt

./spades.py --careful --pe1-1 /home/host/Downloads/29566-pair1.fq --pe1-2 /home/host/Downloads/29566-pair2.fq -o ./spades_test

== Warning ==  No assembly mode was specified! If you intend to assemble high-coverage multi-cell/isolate data, use '--isolate' option.

Command line: ./spades.py	--careful	--pe1-1	/home/host/Downloads/29566-pair1.fq	--pe1-2	/home/host/Downloads/29566-pair2.fq	-o	/home/host/SPAdes-3.15.4-Linux/bin/spades_test	

System information:
  SPAdes version: 3.15.4
  Python version: 3.9.7
  OS: Linux-5.13.0-30-generic-x86_64-with-glibc2.31

Output dir: /home/host/SPAdes-3.15.4-Linux/bin/spades_test
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/host/Downloads/29566-pair1.fq']
      right reads: ['/home/host/Downloads/29566-pair2.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/host/SPAdes-3.15.4-Linux/bin/spades_test/tmp
  Threads: 16
  Memory limit (in Gb): 8

======= SPAdes pipeline started. Log can be found here: /home/host/SPAdes-3.15.4-Linux/bin/spades_test/spades.log

/home/host/Downloads/29566-pair1.fq: max reads length: 150
/home/host/Downloads/29566-pair2.fq: max reads length: 150

Reads length: 150

Default k-mer sizes were set to [21, 33, 55, 77] because estimated read length (150) is equal to or greater than 150

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /home/host/SPAdes-3.15.4-Linux/bin/spades-hammer /home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info

  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/spades_3.15.4, git revision 1a5332e5608a073a9d28a6d0e30836f38dcc5613
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  76)   Loading config from /home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 4
  0:00:00.000     1M / 10M   INFO    General                 (memory_limit.cpp          :  54)   Memory limit set to 8 Gb
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  86)   Trying to determine PHRED offset
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  :  92)   Determined value is 33
  0:00:00.000     1M / 10M   INFO    General                 (hammer_tools.cpp          :  38)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.000     1M / 10M   INFO    General                 (main.cpp                  : 113)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.001     1M / 10M   INFO    General                 (kmer_index_builder.hpp    : 243)   Splitting kmer instances into 16 files using 4 threads. This might take a while.
  0:00:00.001     1M / 10M   INFO    General                 (file_limit.hpp            :  42)   Open file limit set to 1024
  0:00:00.001     1M / 10M   INFO    General                 (kmer_splitter.hpp         :  93)   Memory available for splitting buffers: 0.666659 Gb
  0:00:00.001     1M / 10M   INFO    General                 (kmer_splitter.hpp         : 101)   Using cell size of 4194304
  0:00:00.001  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/host/Downloads/29566-pair1.fq
  0:00:07.688  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 621253 reads
  0:00:15.431  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1255181 reads
  0:00:24.179  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 1996652 reads
  0:00:33.966  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 2749173 reads
  0:00:42.341  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 3426694 reads
  0:00:50.384  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4082180 reads
  0:00:50.437  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4085217 reads
  0:00:50.437  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             :  97)   Processing /home/host/Downloads/29566-pair2.fq
  0:00:59.148  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 107)   Processed 4761443 reads
  0:01:40.645  2305M / 2305M INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 8170434 reads processed
  0:01:40.645     1M / 1896M INFO    General                 (kmer_index_builder.hpp    : 249)   Starting k-mer counting.
  0:01:45.354     1M / 1896M INFO    General                 (kmer_index_builder.hpp    : 260)   K-mer counting done. There are 208421038 kmers in total.
  0:01:45.354     1M / 1896M INFO   K-mer Index Building     (kmer_index_builder.hpp    : 395)   Building perfect hash indices
  0:01:57.235   149M / 1896M INFO   K-mer Index Building     (kmer_index_builder.hpp    : 431)   Index built. Total 208421038 kmers, 150546912 bytes occupied (5.77857 bits per kmer).
  0:01:57.235   149M / 1896M INFO   K-mer Counting           (kmer_data.cpp             : 354)   Arranging kmers in hash map order
  0:02:07.696  3334M / 3458M INFO    General                 (main.cpp                  : 148)   Clustering Hamming graph.
  0:12:22.001  3334M / 3458M INFO    General                 (main.cpp                  : 155)   Extracting clusters:
  0:12:22.001  3334M / 3458M INFO    General                 (concurrent_dsu.cpp        :  18)   Connecting to root
  0:12:23.696  3334M / 3458M INFO    General                 (concurrent_dsu.cpp        :  34)   Calculating counts
  0:12:44.852  5510M / 5629M INFO    General                 (concurrent_dsu.cpp        :  63)   Writing down entries

== Error ==  system call for: "['/home/host/SPAdes-3.15.4-Linux/bin/spades-hammer', '/home/host/SPAdes-3.15.4-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -9
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/host/SPAdes-3.15.4-Linux/bin/spades_test/spades.log

Thank you for using SPAdes!

### SPAdes version

3.15.2

### Operating System

ubuntu

### Python Version

3.8.4

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Your SPAdes job was killed. More information might be available in the system log

**Comment by AbadJavier** [comment]
Podrías considerar aumentar la memoria, tuve el mismo error y utlicé --memory 300 lo cual me resultó bastante bien
