### ISSUE TITLE
An error occurred while running spadea

### ISSUE THREAD

**Issue by Jianz9293** [ablab/spades#926]
### Description of bug

When I am running the command line below, the program is interrupted. Could you please help me check the reason
nohup python /data1/software/SPAdes-3.9.1-Linux/bin/spades.py -1 Y59out.R1.fq -2 Y59out.R2.fq --nanopore /data2/lanlina/Sp_TU_XY/Y_TU/Y_assemblegenome1.fa --untrusted-contigs /data4/lanlina/TU494751/Sp-Y/Y_1_trimout/Y59Soapcontig.fa -t 52 -m 400 -o /Y59_2and3_assemple > Y59_2and3assem.file 2>&1 &

The error message is as follows, but I do not know how to solve it
== Error ==  system call for: "['/data1/software/SPAdes-3.9.1-Linux/bin/hammer', '/data4/lanlina/TU494751/Sp-Y/Y_1_trimout/Y59_2and3_assemple/corrected/configs/config.info']" finished abnormally, err code: -9

### spades.log

[spades.log](https://github.com/ablab/spades/files/8133971/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8133976/params.txt)

### SPAdes version

SPAdes3.9.1

### Operating System

centos 7

### Python Version

python 3.7

### Method of SPAdes installation

SPAdes-3.9.1-Linux

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Your SPAdes job was killed. Likely more information could be found in SPAdes log.

PS: SPAdes 3.9.1 is ancient – consider upgrading.

**Comment by Jianz9293** [comment]
Hello, after I upgraded SPAdes 3.15.4, the following error occurs when I run the program, please help me solve it.
 In addition, I have been running this program for several days. Can I continue to run it after I resolve the error?
Thanks
[spades.log](https://github.com/ablab/spades/files/8158192/spades.log)
[warnings.log](https://github.com/ablab/spades/files/8158191/warnings.log)
[params.txt](https://github.com/ablab/spades/files/8158193/params.txt)

**Comment by asl** [comment]
Again, your SPAdes job was killed. More information likely could be found from the system log file
