### ISSUE TITLE
== Error ==  system call for: "['/share/apps/spades/3.11.1/bin/spades', '/srv/scratch/z9902401/EMP_test_assemblies/metaspades_all_CHO_sam ples/K55/configs/config.info', '/srv/scratch/z9902401/EMP_test_assemblies/metaspades_all_CHO_samples/K55/configs/mda_mode.info', '/srv/sc ratch/z9902401/EMP_test_assemblies/metaspades_all_CHO_samples/K55/configs/meta_mode.info']" finished abnormally, err code: -6

### ISSUE THREAD

**Issue by torstenthomas** [ablab/spades#93]
== Error ==  system call for: "['/share/apps/spades/3.11.1/bin/spades', '/srv/scratch/z9902401/EMP_test_assemblies/metaspades_all_CHO_sam
ples/K55/configs/config.info', '/srv/scratch/z9902401/EMP_test_assemblies/metaspades_all_CHO_samples/K55/configs/mda_mode.info', '/srv/sc
ratch/z9902401/EMP_test_assemblies/metaspades_all_CHO_samples/K55/configs/meta_mode.info']" finished abnormally, err code: -6
[spades.log](https://github.com/ablab/spades/files/1869891/spades.log)
[params.txt](https://github.com/ablab/spades/files/1869892/params.txt)

**Comment by asl** [comment]
Hello

The log reads:

<jemalloc>: Error in malloc(): out of memory. Requested: 64, active: 26944208896

So, you're running out of RAM.
