### ISSUE TITLE
finished abnormally, OS return value: 22

### ISSUE THREAD

**Issue by veedeeve** [ablab/spades#943]
### Description of bug

Performed 
>spades.py -1 SRR_R1_paired.fastq  -2 SRR_R2_paired.fastq -o spades_corrected --only-error-correction

and recieved error code: 22

Output dir: /Users/vydang/hw3/spades_corrected
Mode: ONLY read error correction (without assembling)
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/Users/vydang/hw3/SRR_R1_paired.fastq']
      right reads: ['/Users/vydang/hw3/SRR_R2_paired.fastq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Other parameters:
  Dir for temp files: /Users/vydang/hw3/spades_corrected/tmp
  Threads: 16
  Memory limit (in Gb): 250

======= SPAdes pipeline started. Log can be found here: /Users/vydang/hw3/spades_corrected/spades.log

===== Before start started. 

===== Read error correction started. 

===== Read error correction started. 

== Running: /Users/vydang/miniconda3/envs/denovo/bin/spades-hammer /Users/vydang/hw3/spades_corrected/corrected/configs/config.info

  0:00:00.000     1M / 6M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/master, git revision 54bed604152fd271b68bdf7b78bfd0788ea9e431
  0:00:00.002     1M / 6M    INFO    General                 (main.cpp                  :  76)   Loading config from /Users/vydang/hw3/spades_corrected/corrected/configs/config.info
  0:00:00.003     1M / 7M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 8
  0:00:00.003     1M / 7M    ERROR   General                 (memory_limit.cpp          :  47)   setrlimit(2) call failed, errno = 22

== Error ==  system call for: "['/Users/vydang/miniconda3/envs/denovo/bin/spades-hammer', '/Users/vydang/hw3/spades_corrected/corrected/configs/config.info']" finished abnormally, OS return value: 22

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /Users/vydang/hw3/spades_corrected/spades.log

### spades.log

[spades.log](https://github.com/ablab/spades/files/8204048/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8204052/params.txt)

### SPAdes version

3.15.2

### Operating System

macOS-10.16-x86_64-i386-64bit

### Python Version

3.10.0

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is known MacOS issue. Consider upgrading to SPAdes 3.15.4

**Comment by vkhuy** [comment]
<img width="932" alt="Screen Shot 2023-07-10 at 08 39 14" src="https://github.com/ablab/spades/assets/134928960/55d1ddda-20e2-429b-ac24-b1e4a50291ff">

I have the same issue but I can't find SPAdes 3.15.4 for macOS. Can you help me with this?
