### ISSUE TITLE
err code: -6

### ISSUE THREAD

**Issue by Beta-INC** [ablab/spades#949]
### Description of bug

== Error ==  system call for: "['/usr/lib/spades/bin/hammer', '/home/dell/Documentos/Secuencias/Genoma_Ale/Trimmomatic/PE/Trimm2/spades_error_corrected_reads/corrected/configs/config.info']" finished abnormally, err code: -6

### spades.log

[spades.log](https://github.com/ablab/spades/files/8248560/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8248562/params.txt)

### SPAdes version

3.11.1

### Operating System

Ubuntu

### Python Version

2.7.17

### Method of SPAdes installation

binaries in linux terminal 

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:
```
Message 'Pair of read files /home/dell/Documentos/Secuencias/Genoma_Ale/Trimmomatic/PE/Trimm2/Trim_forwardunPE.fq and /home/dell/Documentos/Secuencias/Genoma_Ale/Trimmomatic/PE/Trimm2/Trim_reverseunPE.fq contain unequal amount of reads'.
```

So, your input reads are corrupted

PS: SPAdes 3.11 is ancient
