### ISSUE TITLE
 err code: -6

### ISSUE THREAD

**Issue by Jigyasa3** [ablab/spades#951]
### Description of bug

Running spades on trimmed fastq files. The script is correct as it runs perfectly for other samples. For this sample, K71 is throwing an error even after recognizing hundreds of kmers.

### spades.log

[spades.log](https://github.com/ablab/spades/files/8312550/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8312551/params.txt)

### SPAdes version

SPAdes 3.11.1

### Operating System

Linux-4.18.0-348.2.1.el8_5.x86_64-x86_64-with-centos-8.5.2111

### Python Version

Python version: 3.7.3

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by GhjuvanGrimaud** [comment]
Hello,

I have the exact same problem (error code -6) for some samples (and only some samples). Could you elaborate a bit more on the fact that the files get corrupted: any solution you can suggest? 

For some samples, spades gets stuck without throwing error (might be related to this error?)

  SPAdes version: 3.14.0
  Python version: 3.7.9
  OS: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo

Thanks
