### ISSUE TITLE
Err code -6 (but maybe completely different)

### ISSUE THREAD

**Issue by GhjuvanGrimaud** [ablab/spades#953]
### Description of bug

Hello,

I have problems running metaspades (error code -6) for some samples (and only some samples). You suggested in a different issue  #951 that "some of SPAdes intermediate files got corrupted. Likely due to I/O problem on your end". Is it the same problem, and if yes, could you elaborate a bit more and provide potential solutions (it would be really helpful)

For some samples, spades gets stuck without throwing error (might be related to this error?)

Thanks

### spades.log

[spades.log](https://github.com/ablab/spades/files/8317965/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8317980/params.txt)

### SPAdes version

3.14.0 

### Operating System

 Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo

### Python Version

3.7.9 

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
  0:07:45.502     5G / 13G   INFO    General                 (pair_info_count.cpp       :  39)   Selecting usual mapper
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

Unfortunately, no further information was provided by your system. Maybe additional information could be found in the system log.

I would also suggest you to give the latest SPAdes 3.15.4 a try

**Comment by GhjuvanGrimaud** [comment]
Thanks. No, nothing more on the system log. Do you have any idea (maybe memory problems on a SLURM system)/have you ever encountered this kind of problem with SPADES?

**Comment by asl** [comment]
It's unlikely a memory problem. More likely an I/O or thread creation problem on your system. Your system provided no further information about the failure.

**Comment by GhjuvanGrimaud** [comment]
Decreasing the threads number from 15 to 6 solves the problem. Thanks

**Comment by asl** [comment]
Ok, so this is certainly something that you can discuss with your system administrator / cluster administrator
