### ISSUE TITLE
System call, finished abnormally, err code 255

### ISSUE THREAD

**Issue by sipesk** [ablab/spades#954]
### Description of bug

Within the metaWRAP bioinformatics pipeline, spades fails with either error code -6 or 255.

### spades.log

[spades.log](https://github.com/ablab/spades/files/8323179/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8323190/params.txt)

### SPAdes version

SPAdes v3.11.1

### Operating System

Linux x86_64

### Python Version

Python 2.7.15

### Method of SPAdes installation

mamba

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
There is no error reported in spades.log file. Please attach the file with the error and reopen the issue.

Thanks

**Comment by sipesk** [comment]
[spades.log.txt](https://github.com/ablab/spades/files/8323427/spades.log.txt)

At the bottom of the spades.log file its reads :
== Error ==  system call for: "['/software/anaconda3/envs/metawrap/share/spades-3.13.0-0/bin/spades-hammer', '/home/katie/viralmarke
rGrIS/data/ASSEMBLY/final_pure_reads/metaspades/corrected/configs/config.info']" finished abnormally, err code: 255


But i cant find with err code 255 relates to.

**Comment by asl** [comment]
The log reads:

```
 0:39:37.691    58G / 58G   INFO   K-mer Splitting          (kmer_data.cpp             : 112)   Total 0 reads processed
  0:39:38.480     5G / 58G   INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  0:39:38.486     5G / 58G   ERROR   General                 (mmapped_reader.hpp        : 100)   open(2) failed. Reason: No such fil
e or directory. Error code: 2. File: /home/katie/viralmarkerGrIS/data/ASSEMBLY/final_pure_reads/metaspades.tmp/hammer_HtEln6/kmer_sp
```

It looks like an I/O error on your end (e.g. reads were deleted / disappeared) as they certainly were used several steps above

**Comment by sipesk** [comment]
Thanks for that, i'll try to consolidate dirs and test with a single PE read.
