### ISSUE TITLE
OS return value: -6 in version 3.15.4

### ISSUE THREAD

**Issue by drelo** [ablab/spades#955]
### Description of bug

We are trying to assemble a  verterbrate genome in a cluster (251Gb, 64 cores). It seems it is asking for too much memory or some step fails before the end.

We noticed there are similar issues but it appeared as fixed in version 3.15.2. 

We launched the job with a simple `nohup ./SPADES/SPAdes-3.15.4-Linux/bin/spades.py --pe1-1 /Trim_het/mahali_R1_trimPair.fastq  --pe1-2  /Trim_het/mahali_R2_trimPair.fastq --isolate --threads 30 -m 230  -o OUT &`

>   4:11:00.950   118G / 165G  INFO  General  (debruijn_graph_constructor: 487)   Total 5493423152 edges to create
> mimalloc: error: unable to allocate OS memory (220842688512 bytes, error code: 12 [Cannot allocate memory], address: (nil), large only: 0, allow large: 1)

Thanks for your help

Andrés

### spades.log

[spades.log](https://github.com/ablab/spades/files/8327606/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8327618/params.txt)

### SPAdes version

SPAdes-3.15.4-Linux

### Operating System

ID_LIKE="fedora" VERSION_ID="8.5"

### Python Version

3.8.12

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Well, it is running out of RAM. You need more RAM to assemble your very large dataset.
