### ISSUE TITLE
--continue is not working

### ISSUE THREAD

**Issue by wangGH73** [ablab/spades#957]
### Description of bug

I use --checkpoint all to run spades workload.
later on, I ctl-c stop the workload and try to start workload with --continue.
Then the application has an exception.

after I ctl-c stop the workload I see the file is there
# ls .bin_reads/
INFO_0 merged_0.off merged_0.seq paired_0.off paired_0.seq single_0.off single_0.seq

however after I start "/root/SPAdes-3.15.3/spades.py -o /data/spades3 --continue"
The file is not there
[root@ip-172-31-21-10 ~]# ls -l /data/spades3/.bin_reads/
total 0

Why does the start-up clean the file that it will be used later on? how to use this checkpoint?

### spades.log

Command line: /root/SPAdes-3.15.3/spades.py -m 2000 --tmp-dir /data -o /data/spades3 --only-assembler -k 33,55,77,99,127 --meta -t 32 --12 /data/test.fq --checkpoints all

System information:
SPAdes version: 3.15.3
Python version: 3.6.8
OS: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-centos-8.4.2105

Output dir: /data/spades3
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
Metagenomic mode
Reads:
Library number: 1, library type: paired-end
orientation: fr
left reads: not specified
right reads: not specified
interlaced reads: ['/data/test.fq']
single reads: not specified
merged reads: not specified
Assembly parameters:
k: [33, 55, 77, 99, 127]
Repeat resolution is enabled
Mismatch careful mode is turned OFF
MismatchCorrector will be SKIPPED
Coverage cutoff is turned OFF
Other parameters:
Dir for temp files: /data
Threads: 32
Memory limit (in Gb): 2000

======= SPAdes pipeline started. Log can be found here: /data/spades3/spades.log

/data/test.fq: max reads length: 151

Reads length: 151
===== Before start started.
===== Preprocess reads started.
===== Preprocess reads finished.
===== Assembling started.
===== K33 started.

== Running: /root/SPAdes-3.15.3/bin/spades-core /data/spades3/K33/configs/config.info /data/spades3/K33/configs/mda_mode.info /data/spades3/K33/configs/meta_mode.info

0:00:00.000 10M INFO General (main.cpp : 99) Loaded config from /data/spades3/K33/configs/config.info
0:00:00.000 10M INFO General (main.cpp : 99) Loaded config from /data/spades3/K33/configs/mda_mode.info
0:00:00.000 10M INFO General (main.cpp : 99) Loaded config from /data/spades3/K33/configs/meta_mode.info
0:00:00.000 10M INFO General (memory_limit.cpp : 48) Memory limit set to 2000 Gb
0:00:00.000 10M INFO General (main.cpp : 107) Starting SPAdes, built from N/A, git revision N/A
0:00:00.000 10M INFO General (main.cpp : 108) Maximum k-mer length: 128
0:00:00.000 10M INFO General (main.cpp : 109) Assembling dataset (/data/spades3/dataset.info) with K=33
0:00:00.000 10M INFO General (main.cpp : 110) Maximum # of threads to use (adjusted due to OMP capabilities): 32
0:00:00.000 10M INFO General (pipeline.cpp : 212) SPAdes started
0:00:00.000 10M INFO General (pipeline.cpp : 225) Starting from stage: read_conversion
0:00:00.000 10M INFO General (pipeline.cpp : 231) Two-step repeat resolution disabled
0:00:00.000 10M INFO GraphCore (graph_core.hpp : 672) Graph created, vertex min_id: 3, edge min_id: 3
0:00:00.000 10M INFO GraphCore (graph_core.hpp : 673) Vertex size: 48, edge size: 40
0:00:00.000 10M INFO General (edge_index.hpp : 115) Size of edge index entries: 12/8
0:00:00.000 10M INFO StageManager (stage.cpp : 185) STAGE == Binary Read Conversion (id: read_conversion)
0:00:00.001 10M INFO General (read_converter.cpp : 72) Converting reads to binary format for library #0 (takes a while)
0:00:00.001 10M INFO General (read_converter.cpp : 73) Converting paired reads
0:00:00.147 45M INFO General (binary_converter.cpp : 96) 16384 reads processed
0:00:00.165 57M INFO General (binary_converter.cpp : 96) 32768 reads processed
0:00:00.284 94M INFO General (binary_converter.cpp : 96) 65536 reads processed
0:00:00.426 128M INFO General (binary_converter.cpp : 96) 131072 reads processed
0:00:00.818 170M INFO General (binary_converter.cpp : 96) 262144 reads processed
0:00:01.510 228M INFO General (binary_converter.cpp : 96) 524288 reads processed
0:00:02.883 352M INFO General (binary_converter.cpp : 96) 1048576 reads processed
0:00:05.757 389M INFO General (binary_converter.cpp : 96) 2097152 reads processed
0:00:11.804 494M INFO General (binary_converter.cpp : 96) 4194304 reads processed
0:00:23.758 600M INFO General (binary_converter.cpp : 96) 8388608 reads processed
0:00:47.543 622M INFO General (binary_converter.cpp : 96) 16777216 reads processed
0:01:29.784 622M INFO General (binary_converter.cpp : 111) 31250000 reads written
0:01:29.786 622M INFO General (read_converter.cpp : 86) Converting single reads
0:01:29.787 622M INFO General (binary_converter.cpp : 111) 0 reads written
0:01:29.787 622M INFO General (read_converter.cpp : 92) Converting merged reads
0:01:29.787 622M INFO General (binary_converter.cpp : 111) 0 reads written
0:01:29.791 622M INFO General (read_conversion.cpp : 30) Saving current state to /data/spades3/K33/saves/read_conversion
0:01:29.791 622M INFO StageManager (stage.cpp : 185) STAGE == de Bruijn graph construction (id: construction)
0:01:29.795 622M INFO General (construction.cpp : 153) Max read length 151
0:01:29.795 622M INFO General (construction.cpp : 159) Average read length 150.381
0:01:29.795 622M INFO General (stage.cpp : 117) PROCEDURE == k+1-mer counting (id: construction:kpomer_counting)
0:01:29.795 622M INFO General (kmer_index_builder.hpp : 243) Splitting kmer instances into 320 files using 32 threads. This might take a wh
ile.
0:01:29.795 622M INFO General (file_limit.hpp : 32) Open file limit set to 1024
0:01:29.795 622M INFO General (kmer_splitter.hpp : 93) Memory available for splitting buffers: 20.8333 Gb
0:01:29.795 622M INFO General (kmer_splitter.hpp : 101) Using cell size of 104857

Traceback (most recent call last):
File "/root/SPAdes-3.15.3/spades.py", line 626, in main
executor.execute(commands)
File "/root/SPAdes-3.15.3/src/spades_pipeline/executors/executor_local.py", line 37, in execute
command.run(self.log)
File "/root/SPAdes-3.15.3/src/spades_pipeline/commands_parser.py", line 38, in run
support.sys_call(self.to_list(), log)
File "/root/SPAdes-3.15.3/src/spades_pipeline/support.py", line 312, in sys_call
line = process_readline(proc.stdout.readline())
KeyboardInterrupt

== Error == exception caught: <class 'KeyboardInterrupt'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /data/spades3/spades.log

Thank you for using SPAdes!

======= SPAdes pipeline continued. Log can be found here: /data/spades3/spades.log

Restored from Command line: /root/SPAdes-3.15.3/spades.py -m 2000 --tmp-dir /data -o /data/spades3 --only-assembler -k 33,55,7
7,99,127 --meta -t 32 --12 /data/test.fq --checkpoints all

Command line: /root/SPAdes-3.15.3/spades.py -m 2000 --tmp-dir /data -o /data/spades3 --only-assembler -k 33,55,77,99,127 --meta
-t 32 --12 /data/test.fq --checkpoints all

System information:
SPAdes version: 3.15.3
Python version: 3.6.8
OS: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-centos-8.4.2105

Output dir: /data/spades3
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
Metagenomic mode
Reads:
Library number: 1, library type: paired-end
orientation: fr
left reads: not specified
right reads: not specified
interlaced reads: ['/data/test.fq']
single reads: not specified
merged reads: not specified
Assembly parameters:
k: [33, 55, 77, 99, 127]
Repeat resolution is enabled
Mismatch careful mode is turned OFF
MismatchCorrector will be SKIPPED
Coverage cutoff is turned OFF
Other parameters:
Dir for temp files: /data
Threads: 32
Memory limit (in Gb): 2000

/data/test.fq: max reads length: 151

Reads length: 151

===== Before start started.

===== Preprocess reads started.

===== Preprocess reads finished.

===== Assembling started.

===== K33 started.

== Running: /root/SPAdes-3.15.3/bin/spades-core /data/spades3/K33/configs/config.info /data/spades3/K33/configs/mda_mode.info /data/spades3/K33/configs/meta_mode.info

0:00:00.000 11M INFO General (main.cpp : 99) Loaded config from /data/spades3/K33/configs/config.info
0:00:00.000 11M INFO General (main.cpp : 99) Loaded config from /data/spades3/K33/configs/mda_mode.info
0:00:00.000 11M INFO General (main.cpp : 99) Loaded config from /data/spades3/K33/configs/meta_mode.info
0:00:00.000 11M INFO General (memory_limit.cpp : 48) Memory limit set to 2000 Gb
0:00:00.000 11M INFO General (main.cpp : 107) Starting SPAdes, built from N/A, git revision N/A
0:00:00.000 11M INFO General (main.cpp : 108) Maximum k-mer length: 128
0:00:00.000 11M INFO General (main.cpp : 109) Assembling dataset (/data/spades3/dataset.info) with K=33
0:00:00.000 11M INFO General (main.cpp : 110) Maximum # of threads to use (adjusted due to OMP capabilities): 32
0:00:00.000 11M INFO General (pipeline.cpp : 212) SPAdes started
0:00:00.000 11M INFO General (pipeline.cpp : 225) Starting from stage: last
0:00:00.000 11M INFO General (pipeline.cpp : 231) Two-step repeat resolution disabled
0:00:00.000 11M INFO GraphCore (graph_core.hpp : 672) Graph created, vertex min_id: 3, edge min_id: 3
0:00:00.000 11M INFO GraphCore (graph_core.hpp : 673) Vertex size: 48, edge size: 40
0:00:00.000 11M INFO General (edge_index.hpp : 115) Size of edge index entries: 12/8
0:00:00.000 11M INFO General (read_conversion.cpp : 21) Loading current state from /data/spades3/K33/saves/read_conversion
0:00:00.001 11M INFO StageManager (stage.cpp : 185) STAGE == de Bruijn graph construction (id: construction)
Exception caught Cannot tell the size of file /data/spades3/.bin_reads/single_0.off: Unknown error -1

== Error == system call for: "['/root/SPAdes-3.15.3/bin/spades-core', '/data/spades3/K33/configs/config.info', '/data/spades3/K33/configs/mda_mode.info', '/data/spades3/K33/configs/meta_mode.info']" finished abnormally, OS return value: 4
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /data/spades3/spades.log

Thank you for using SPAdes!

### params.txt

/root/SPAdes-3.15.3/spades.py -m 2000 --tmp-dir /data -o /data/spades3 --only-assembler -k 33,55,77,99,127 --meta -t $(nproc) --12 /data/test.fq --checkpoints all
/root/SPAdes-3.15.3/spades.py -o /data/spades3 --continue

### SPAdes version

3.15.3

### Operating System

centos 8

### Python Version

Python 3.6.8

### Method of SPAdes installation

compile src

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Dup of #956
