### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by rcgodbole** [ablab/spades#958]
### Description of bug

Run ends abruptly at kmer value 33 showing following errors
=== Error correction and assembling warnings:
 * 0:00:00.853    40M / 7G    WARN    General                 (kmer_coverage_model.cpp   : 327)   Valley value was estimated improperly, reset to 2
 * 0:00:00.853    40M / 7G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 2

### spades.log

[spades.log](https://github.com/ablab/spades/files/8415583/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8415586/params.txt)

### SPAdes version

SPAdes v3.13.0

### Operating System

Ubuntu 18.04.6 LTS

### Python Version

Python 3.8.8

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

The log reads:

```
 Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```

And indeed, it does not seem you're assembling of any meaningful part of a genome. At least you should not do this in normal multicell mode which naturally expects uniform coverage.
