### ISSUE TITLE
Error Code 12 and 6

### ISSUE THREAD

**Issue by EvPegg** [ablab/spades#96]
I am an undergraduate student, entering masters, and am just starting to get into bioinformatics. I have been trying to assemble a bear genome using the spades assembler, however have been running into errors. Please find attached the output log below. What is the specific error that is preventing the assembler from continuing running, and how to I go about fixing it?

[spades.log](https://github.com/ablab/spades/files/1895828/spades.log)

Thanks,

Evan

**Comment by asl** [comment]
Hello

Thank you for your interest in SPAdes.

The log reads
```
Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'
```

So, you're running out of RAM. I doubt you will be able to assemble such huge genome (you're having more than 10 billion distinct k-mers) using only 15 Gb of free RAM.

**Comment by EvPegg** [comment]
Perfect, thank you for the clarification.
