### ISSUE TITLE
 Too many erroneous kmers, the estimates might be unreliable

### ISSUE THREAD

**Issue by asmlgkj** [ablab/spades#962]
### Description of bug

 Too many erroneous kmers, the estimates might be unreliable

### spades.log

Thanks a lot.
I met the same error, mine sample is ctdna human sample,
the error is
=== Error correction and assembling warnings:

0:00:33.645 611M / 3386M WARN General (kmer_coverage_model.cpp : 218) Too many erroneous kmers, the estimates might be unreliable
0:00:54.182 591M / 2711M WARN General (pair_info_count.cpp : 376) Estimated mean insert size 101.664 is very small compared to read length 149
======= Warnings saved to result/warnings.log

### params.txt

spade.py -1 fq1 -2 fq2 -o result

### SPAdes version

3.15.2

### Operating System

centos 7

### Python Version

3.7

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Please attach the complete spades.log file

**Comment by asmlgkj** [comment]
Command line: /local/bin_default/spades.py     -1      /LK1234_file1.fq  -2      /LK1234_file2.fq  -o      /result_LK1234    

System information:
  SPAdes version: 3.14.1
  Python version: 2.7.5
  OS: Linux-3.10.0-1160.42.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core

Output dir: /result_LK1234
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Standard mode
  For multi-cell/isolate data we recommend to use '--isolate' option; for single-cell MDA data use '--sc'; for metagenomic data use '--meta'; for RNA-Seq use '--rna'.
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/LK1234_file1.fq']
      right reads: ['/LK1234_file2.fq']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /result_LK1234/tmp
  Threads: 16
  Memory limit (in Gb): 250


======= SPAdes pipeline started. Log can be found here: /result_LK1234/spades.log

/LK1234_file2.fq: max reads length: 149
/LK1234_file1.fq: max reads length: 149

Reads length: 149


===== Before start started. 


===== Read error correction started. 


===== Read error correction started. 


== Running: /softwares/SPAdes-3.14.1-Linux/bin/spades-hammer /result_LK1234/corrected/configs/config.info

**Comment by asl** [comment]
Please attach the complete spades.log file with an issue, not just some random part of it and reopen the issue.

**Comment by asmlgkj** [comment]
===== K55 finished. 


===== Copy files started. 


== Running: /usr/bin/python /SPAdes-3.14.1-Linux/share/spades/spades_pipeline/scripts/copy_files.py result_LK1234/K55/before_rr.fasta result_LK1234/before_rr.fasta result_LK1234/K55/assembly_graph_after_simplification.gfa result_LK1234/assembly_graph_after_simplification.gfa result_LK1234/K55/final_contigs.fasta result_LK1234/contigs.fasta result_LK1234/K55/first_pe_contigs.fasta result_LK1234/first_pe_contigs.fasta result_LK1234/K55/strain_graph.gfa result_LK1234/strain_graph.gfa result_LK1234/K55/scaffolds.fasta result_LK1234/scaffolds.fasta result_LK1234/K55/scaffolds.paths result_LK1234/scaffolds.paths result_LK1234/K55/assembly_graph_with_scaffolds.gfa result_LK1234/assembly_graph_with_scaffolds.gfa result_LK1234/K55/assembly_graph.fastg result_LK1234/assembly_graph.fastg result_LK1234/K55/final_contigs.paths result_LK1234/contigs.paths


===== Copy files finished. 


===== Assembling finished. 


===== Breaking scaffolds started. 


== Running: /usr/bin/python /SPAdes-3.14.1-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename result_LK1234/scaffolds.fasta --misc_dir result_LK1234/misc --threshold_for_breaking_scaffolds 3


===== Breaking scaffolds finished. 


===== Terminate started. 


===== Terminate finished. 

 * Corrected reads are in result_LK1234/corrected/
 * Assembled contigs are in result_LK1234/contigs.fasta
 * Assembled scaffolds are in result_LK1234/scaffolds.fasta
 * Paths in the assembly graph corresponding to the contigs are in result_LK1234/contigs.paths
 * Paths in the assembly graph corresponding to the scaffolds are in result_LK1234/scaffolds.paths
 * Assembly graph is in result_LK1234/assembly_graph.fastg
 * Assembly graph in GFA format is in result_LK1234/assembly_graph_with_scaffolds.gfa

======= SPAdes pipeline finished WITH WARNINGS!

=== Error correction and assembling warnings:
 * 0:00:06.712   254M / 2G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 29
 * 0:00:06.699   324M / 718M  WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 32
 * 0:00:13.033   186M / 718M  WARN    General                 (pair_info_count.cpp       : 360)   Estimated mean insert size 86.9149 is very small compared to read length 149
======= Warnings saved to result_LK1234/warnings.log

SPAdes log can be found here: result_LK1234/spades.log

Thank you for using SPAdes!
(END)
