### ISSUE TITLE
unable to run spades

### ISSUE THREAD

**Issue by dhiru16** [ablab/spades#963]
### Description of bug

[spades] == Running: /Users/dhirajchundru/opt/anaconda3/envs/shovill/bin/spades-core /Users/dhirajchundru/Desktop/AP_reads/umd_reads/reads_220/paired/assembly/spades/K31/configs/config.info /Users/dhirajchundru/Desktop/AP_reads/umd_reads/reads_220/paired/assembly/spades/K31/configs/isolate_mode.info
[spades] 
[spades]   0:00:00.000     1M / 9M    INFO    General                 (main.cpp                  :  99)   Loaded config from /Users/dhirajchundru/Desktop/AP_reads/umd_reads/reads_220/paired/assembly/spades/K31/configs/config.info
[spades]   0:00:00.000     1M / 9M    INFO    General                 (main.cpp                  :  99)   Loaded config from /Users/dhirajchundru/Desktop/AP_reads/umd_reads/reads_220/paired/assembly/spades/K31/configs/isolate_mode.info
[spades]   0:00:00.000     1M / 9M    ERROR   General                 (memory_limit.cpp          :  47)   setrlimit(2) call failed, errno = 22
[spades] 
[spades] 
[spades] == Error ==  system call for: "['/Users/dhirajchundru/opt/anaconda3/envs/shovill/bin/spades-core', '/Users/dhirajchundru/Desktop/AP_reads/umd_reads/reads_220/paired/assembly/spades/K31/configs/config.info', '/Users/dhirajchundru/Desktop/AP_reads/umd_reads/reads_220/paired/assembly/spades/K31/configs/isolate_mode.info']" finished abnormally, OS return value: 22
<img width="1509" alt="Screen Shot 2022-04-15 at 1 15 18 PM" src="https://user-images.githubusercontent.com/96434814/163604360-829add37-7b9c-43f2-a6d4-9bda26a8ef42.png">

### spades.log

[spades.log](https://github.com/ablab/spades/files/8497320/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8497326/params.txt)

### SPAdes version

3.15.2

### Operating System

macOS-10.16-x86_64-i386-64bit

### Python Version

3.8.13

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is a known issue – consider upgrading to 3.15.4
