### ISSUE TITLE
No <output_dir>/scaffolds.fasta, <output_dir>/contigs.fasta, <output_dir>/assembly_graph_with_scaffolds.gfa, <output_dir>/assembly_graph.fastg, <output_dir>/contigs.paths, <output_dir>/scaffolds.paths generated

### ISSUE THREAD

**Issue by B-1991-ing** [ablab/spades#964]
### Description of bug

Dear spades support team,

I ran the spades.py script for my six trimmed paired end reads samples, but after 10 hours running no resulting contigs or scaffolds generated. My error file is also empty.

My command line: /services/tools/SPAdes/3.15.3/bin/spades.py --meta --pe2-1 Sample2_TM_paired_1.fastq --pe2-2 Sample2_TM_paired_2.fastq --pe3-1 Sample3_TM_paired_1.fastq --pe3-2 Sample3_TM_paired_2.fastq --pe4-1 Sample4_TM_paired_1.fastq --pe4-2 Sample4_TM_paired_2.fastq --pe5-1 Sample5_TM_paired_1.fastq --pe5-2 Sample5_TM_paired_2.fastq --pe6-1 Sample6_TM_paired_1.fastq --pe6-2 Sample6_TM_paired_2.fastq --pe7-1 Sample7_TM_paired_1.fastq --pe7-2 Sample7_TM_paired_2.fastq -k 21,33,55,77 -t 24 -o ./Current_pipeline/Individual_assembly/

Could you help me have a look what is wrong there?

Best,

Bing

### spades.log

[spades.log](https://github.com/ablab/spades/files/8501865/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8501867/params.txt)

### SPAdes version

SPAdes v3.15.3

### Operating System

Computerome 2.0, DTU

### Python Version

Python 3.6.10

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
  0:00:00.001     1M / 4M    ERROR   General                 (pipeline.cpp              : 217)   Sorry, current version of metaSPAdes can work either with single library (paired-end only) or in hybrid paired-end + (TSLR or PacBio or Nanopore) mode.
```

**Comment by B-1991-ing** [comment]
Thank you very much for your reply. 

I specified input data with YAML data set file now. I am dealing with metagenomic data.

Which latest version can work with an unlimited number of libraries?

**Comment by asl** [comment]
There is no such version. metaSPAdes requires a single library

**Comment by B-1991-ing** [comment]
I am not sure what is a single library. I am dealing with 6 metagenome samples, I want to do individual assembly using metaSPAdes.

**Comment by asl** [comment]
Ok, why do you provide all of them at the same time? 1 sample = 1 run. Please refer to SPAdes manual (https://cab.spbu.ru/files/release3.15.4/manual.html#sec3.1) for more information on SPAdes input. Reading https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cpbi.102 might also help

**Comment by B-1991-ing** [comment]
Ok, get it. Thank you very much. I will try 1 sample 1 run.
