### ISSUE TITLE
finished abnormally, err code: -9

### ISSUE THREAD

**Issue by DanielSoenarto** [ablab/spades#966]
### Description of bug

I'm trying to do a de novo assembly using spades. The code can be seen in the log file. It says: 

finished abnormally, err code: -9

Also besides this error, can I ask what is the expected output of the file?

### spades.log

[spades.log](https://github.com/ablab/spades/files/8502199/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8502200/params.txt)

### SPAdes version

SPAdes v3.13.0

### Operating System

Linux-5.13.0-39-generic-x86_64-with-debian-bullseye-sid

### Python Version

3.7.6

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Your SPAdes job was killed. Likely more information could be found in the system log.

Description of the SPAdes output could be readily learned from the manual: https://cab.spbu.ru/files/release3.15.4/manual.html#spadesoutput

Hope this helps

**Comment by DanielSoenarto** [comment]
Hi @asl thank you for your reply.

May I ask where is the location of the system log? I don't know how to find it

**Comment by asl** [comment]
I would suggest you to ask your system administrator

**Comment by DanielSoenarto** [comment]
okay then, thank you @asl
