### ISSUE TITLE
Update REDME to detail which Linux kernels the pre-build binaries will work for.

### ISSUE THREAD

**Issue by nick-pestell** [ablab/spades#969]
### Is your feature request related to a problem? Please describe. For generic questions use Q&A section in the Discussions forum above.

I do not know if the pre-build binaries will work on my Linux system. "New kernels" is too vague.

### Describe the solution you'd like

An update to the README with more details on which versions of the Linux kernel the pre-build binaries will work for.

**Comment by asl** [comment]
Unfortunately we do not have bandwidth to test on all plethora of Linux kernel versions and distributions around. We are relying on reports of our users.

So, I'd simply suggest you to download the binaries and run "spades.py --test".
