### ISSUE TITLE
Adding spades to `PATH`: needs to append `PATH` with initial download location.

### ISSUE THREAD

**Issue by nick-pestell** [ablab/spades#970]
### Description of bug

In order to make spades available from anywhere, I have to append the initial directory where spades is extracted to `$PATH`. Rather than being able to either symlink or copy the folder into a location which is already on the `PATH`. 

This is extremely surprising.  

I would prefer to symlink the `bin` folder to `\usr\local\bin` as this is my generic workflow for user installed software.

### SPAdes version

3.15.4

### Operating System

Ubuntu 20.04

### Python Version

3.8.10

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Feel free to copy / symlink the files to whatever location you'd need to. Again, it might be `/opt/local` or `/usr/local` or just `/opt`, etc. on different systems. Note that just simlinking `bin` is not enough as there are some aux files that are stored in `share` dir that also need to be present and reachable.

When building from sources you can use the standard cmake machinery to install to any location you'd need.

**Comment by nick-pestell** [comment]
Sorry @asl , what I'm saying is, symlinking/copying doesn't appear to work. I just tried to symlink the whole `SPAdes-3.15.4-Linux` folder to `/usr/local/bin` in order to make the `share` directory available too. Unfortunately my system still cant find `spades.py`. When I run `spades.py --test` I receive `bash: spades.py: command not found`. I have confirmed that it works when inside the `bin` directory and running `.\spades.py` and when I append `bin` to the `PATH` .

**Comment by asl** [comment]
Well, AFAIK `PATH` does not resolve recursively. Therefore if you'd put `SPAdes-3.15.4-Linux` inside `/usr/local/bin`, then `SPAdes-3.15.4-Linux/bin` won't be visible. So, if you'd want to go this way, then you'd need to copy the contents of `/SPAdes-3.15.4-Linux/bin` to `/usr/local/bin, `SPAdes-3.15.4-Linux/share` into `/usr/local/share` and so on.

**Comment by nick-pestell** [comment]
Thanks @asl ! I think this was my problem

**Comment by nick-pestell** [comment]
FYI @asl, symlinking just `SPAdes-3.15.4-Linux/bin/spades.py` to `/usr/local/bin` appears to work. By this I mean that running `spades.py --test` works: outputting `========= TEST PASSED CORRECTLY.` I guess this is because it the symlink points to the inistal location where spades was extracted thus, relative paths to other files in `SPAdes-3.15.4-Linux/bin` and `SPAdes-3.15.4-Linux/share` are maintained.
