### ISSUE TITLE
== Error ==  system call for: "..." finished abnormally, err code:-11 

### ISSUE THREAD

**Issue by KarimAI7** [ablab/spades#971]
### Description of bug

I ran LegioCluster which uses SPAdes and it generated an issue:

```

== Running read error correction tool: /SPAdes-3.12.0-Linux/bin/spades-hammer /data/SPAdes/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===


== Error ==  system call for: "['/SPAdes-3.12.0-Linux/bin/spades-hammer', '/data/SPAdes/corrected/configs/config.info']" finished abnormally, err code: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

ATTENTION !!!

 ('KI', 'Spy', 'Spy_sample_2', '/home/karimitani/lp_proj/LegioCluster/reads/Spy/Spy_sample_2_R1_001.fastq.gz', '/home/karimitani/lp_proj/LegioCluster/reads/Spy/Spy_sample_2_R2_001.fastq.gz', ['tutorial_part_2', 'multiple_submissions', 'normal_operations'])

DID NOT COMPLETE SUCCESSFULLY: Command 'docker run --rm=True -u $(id -u):$(id -g) -v "/home/karimitani/lp_proj/LegioCluster/temp/KI220503_123322/:/data" -i staphb/spades:3.12.0 spades.py -1 paired_reads_1.fq -2 paired_reads_2.fq  -k 21,33,55,77 --careful --cov-cutoff auto -o SPAdes' returned non-zero exit status 1.
```

### spades.log

[spades.log](https://github.com/ablab/spades/files/8612311/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8612312/params.txt)

### SPAdes version

SPAdes v3.12.0

### Operating System

Windows 11 64-bit

### Python Version

Python 3.8.10

### Method of SPAdes installation

Through legiocluster

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
From SPAdes manual (https://cab.spbu.ru/files/release3.15.4/manual.html#sec2):
```
SPAdes requires a 64-bit Linux system or Mac OS and Python (supported versions are Python 2.7, and Python3: 3.2 and higher)
```

You are running SPAdes on Windows under WSL which is not quite Linux and the platform is not supported. Pre-built binaries are known not to work there. Others reported some success with SPAdes built from source, so I'd suggest you to take the latest SPAdes and compile it from source.

**Comment by KarimAI7** [comment]
Could I run it through a Virtual Machine? Or will I encounter a similar issue?

**Comment by asl** [comment]
VM might be ok. Albeit slow.
