### ISSUE TITLE
MI_HEAP_REGION_MAX_SIZE limit extension

### ISSUE THREAD

**Issue by JBojko** [ablab/spades#972]
### Description of bug

Hey,

I hope this is an easy one. I'm getting reasonable assemblies from my data, but as I look back through the report I keep getting a warning:

mimalloc: warning: maximum regions used: 256 GiB (perhaps recompile with a larger setting for MI_HEAP_REGION_MAX_SIZE)mimalloc: warning: unable to allocate from region: size 4194304

I've tried to determine how to increase the MI_HEAP_REGION_MAX_SIZE setting, but I can't seem to find the answer anywhere.

Do you know what the consequence is for not having a large enough MI_HEAP_REGION_MAX_SIZE and what the code would be to increase this when running SPAdes?

Thanks.

### spades.log

[spades.log](https://github.com/ablab/spades/files/8685435/spades.log)

### params.txt

spades.py -1 Inf75ncFP_1_paired.fq.gz -2 Inf75ncFP_2_paired.fq.gz -s Inf75ncFP_1_unpaired.fq.gz -s Inf75ncFP_2_unpaired.fq.gz -t 100 --memory 400 --phred-offset 33 -o Inf75ncFP_SPADES

### SPAdes version

spades/3.15.3

### Operating System

Linux server

### Method of SPAdes installation

unknown

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

These warnings are benign, feel free to ignore them
