### ISSUE TITLE
Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.

### ISSUE THREAD

**Issue by asmlgkj** [ablab/spades#974]
### Description of bug

Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.

### spades.log

=== Error correction and assembling warnings:
 * 0:00:19.355   341M / 2G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 28
 * 0:00:10.840   268M / 2G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 33
 * 0:00:11.010   455M / 2G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 41
 * 0:00:22.917   191M / 2G    WARN    General                 (pair_info_count.cpp       : 341)   Unable to estimate insert size for paired library #0
 * 0:00:22.918   191M / 2G    WARN    General                 (pair_info_count.cpp       : 347)   None of paired reads aligned properly. Please, check orientation of your read pairs.
 * 0:00:22.919   191M / 2G    WARN    General                 (repeat_resolving.cpp      :  63)   Insert size was not estimated for any of the paired libraries, repeat resolution module will not run.
======= Warnings saved to /home/a/b/warnings.log

### params.txt

spades.py -1 x_file1.fq -2 x_file2.fq -o dirty

### SPAdes version

v3.14.1

### Operating System

centos 7

### Python Version

3.7

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Well, the error message is quite clear:
```
None of paired reads aligned properly. Please, check orientation of your read pairs.
```

So, your input reads are likely corrupted

**Comment by asmlgkj** [comment]
thanks a lot, here is my steps, I want to get the unmapped reads, then assemble by spades.py, then I get the scaffold.fasta to ncbi_blast to get what maybe the contamination(for example: bactieria or virus)
<br>
samtools view -u  -f 4 -F264 x.sort.bam  > tmps1.bam
samtools view -u -f 8 -F 260 x.sort.bam  > tmps2.bam
samtools view -u -f 12 -F 256 x.sort.bam > tmps3.bam
samtools merge -u - tmps[123].bam | samtools sort -n - unmapped > all_umap.bam
bedtools bamtofastq  -i all_umap.bam -fq  x_file1.fq -fq2 x_file2.fq
spade.py -1 x_file1.fq -2 fq2 x_file2.fq -o dirty
