### ISSUE TITLE
--re

### ISSUE THREAD

**Issue by Wanli-HE** [ablab/spades#984]
### Description of bug

--restart-from problem.

### spades.log

======= SPAdes pipeline continued. Log can be found here: /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/spades.log

Restored from Command line: /mibi/users/Wanli/plasplinev1.2/Plaspline/conda_envs/65be5bf7/bin/spades.py --meta  -1      /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_1.fastq.gz -2      /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_2.fastq.gz -m      1000    -t      35      -k      21,33,55        -o      /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res  -m      999     -t      35      -k      21,33,55,77,99

Command line: /mibi/users/Wanli/plasplinev1.2/Plaspline/conda_envs/65be5bf7/bin/spades.py       --meta  -1      /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_1.fastq.gz -2      /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_2.fastq.gz -m      1000    -t      35      -k      21,33,55        -o      /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res  -m      999     -t      35      -k      21,33,55,77,99  -m
      999     -t      35      -k      21,33,55,77,99
Restart-from=k77
with updated parameters: -m     999     -t      35      -k      21,33,55,77,99

System information:
  SPAdes version: 3.15.3
  Python version: 3.9.0
  OS: Linux-4.19.0-18-amd64-x86_64-with-glibc2.28

Output dir: /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_1.fastq.gz']
      right reads: ['/mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55, 77, 99]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/tmp
  Threads: 35
  Memory limit (in Gb): 999

/mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_1.fastq.gz: max reads length: 151
/mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_qc_2.fastq.gz: max reads length: 151

Reads length: 151

===== Before start started. 

===== Read error correction started. 

===== Skipping Read error correction (already processed)
===== Skipping corrected reads compression (already processed)

===== Read error correction finished. 

===== Assembling started. 

===== Skipping K21 (already processed)
===== Skipping K33 (already processed)
===== Skipping K55 (already processed)

===== K77 started. 

== Running: /mibi/users/Wanli/plasplinev1.2/Plaspline/conda_envs/65be5bf7/bin/spades-core /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/K77/configs/config.info /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/K77/configs/mda_mode.info /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/K77/configs/meta_mode.info

  0:00:00.000     1M / 21M   INFO    General                 (main.cpp                  :  99)   Loaded config from /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/K77/configs/config.info
  0:00:00.008     1M / 21M   INFO    General                 (main.cpp                  :  99)   Loaded config from /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/K77/configs/mda_mode.info
  0:00:00.008     1M / 21M   INFO    General                 (main.cpp                  :  99)   Loaded config from /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/K77/configs/meta_mode.info
  0:00:00.008     1M / 21M   INFO    General                 (memory_limit.cpp          :  48)   Memory limit set to 476.837 Gb
  0:00:00.008     1M / 21M   INFO    General                 (main.cpp                  : 107)   Starting SPAdes, built from N/A, git revision N/A
  0:00:00.009     1M / 21M   INFO    General                 (main.cpp                  : 108)   Maximum k-mer length: 128
  0:00:00.009     1M / 21M   INFO    General                 (main.cpp                  : 109)   Assembling dataset (/mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/dataset.info) with K=77
  0:00:00.009     1M / 21M   INFO    General                 (main.cpp                  : 110)   Maximum # of threads to use (adjusted due to OMP capabilities): 35
  0:00:00.009     1M / 21M   INFO    General                 (pipeline.cpp              : 212)   SPAdes started
  0:00:00.009     1M / 21M   INFO    General                 (pipeline.cpp              : 225)   Starting from stage: read_conversion
  0:00:00.009     1M / 21M   INFO    General                 (pipeline.cpp              : 231)   Two-step repeat resolution disabled
  0:00:00.010     1M / 21M   INFO   GraphCore                (graph_core.hpp            : 672)   Graph created, vertex min_id: 3, edge min_id: 3
  0:00:00.010     1M / 21M   INFO   GraphCore                (graph_core.hpp            : 673)   Vertex size: 48, edge size: 40
  0:00:00.010     1M / 21M   INFO    General                 (edge_index.hpp            : 113)   Size of edge index entries: 12/8
  0:00:00.010     1M / 21M   INFO    General                 (pipeline.cpp              : 242)   Will need read mapping, kmer mapper will be attached
  0:00:00.010     1M / 21M   INFO   StageManager             (stage.cpp                 : 185)   STAGE == Binary Read Conversion (id: read_conversion)
  0:00:00.015     1M / 21M   INFO    General                 (read_converter.cpp        :  72)   Converting reads to binary format for library #0 (takes a while)
  0:00:00.016     1M / 21M   INFO    General                 (read_converter.cpp        :  73)   Converting paired reads
  0:00:00.845    68M / 90M   INFO    General                 (binary_converter.cpp      :  96)   16384 reads processed
  0:00:00.872    72M / 100M  INFO    General                 (binary_converter.cpp      :  96)   32768 reads processed
  0:00:00.932    82M / 120M  INFO    General                 (binary_converter.cpp      :  96)   65536 reads processed
  0:00:01.290    72M / 169M  INFO    General                 (binary_converter.cpp      :  96)   131072 reads processed
  0:00:01.830    81M / 213M  INFO    General                 (binary_converter.cpp      :  96)   262144 reads processed
  0:00:02.994    70M / 284M  INFO    General                 (binary_converter.cpp      :  96)   524288 reads processed
  0:00:05.106    77M / 386M  INFO    General                 (binary_converter.cpp      :  96)   1048576 reads processed
  0:00:09.795    91M / 499M  INFO    General                 (binary_converter.cpp      :  96)   2097152 reads processed
  0:00:18.495    90M / 646M  INFO    General                 (binary_converter.cpp      :  96)   4194304 reads processed

Traceback (most recent call last):
  File "/mibi/users/Wanli/plasplinev1.2/Plaspline/conda_envs/65be5bf7/bin/spades.py", line 626, in main
    executor.execute(commands)
  File "/mibi/users/Wanli/plasplinev1.2/Plaspline/conda_envs/65be5bf7/share/spades/spades_pipeline/executors/executor_local.py", line 37, in execute
    command.run(self.log)
  File "/mibi/users/Wanli/plasplinev1.2/Plaspline/conda_envs/65be5bf7/share/spades/spades_pipeline/commands_parser.py", line 38, in run
    support.sys_call(self.to_list(), log)
  File "/mibi/users/Wanli/plasplinev1.2/Plaspline/conda_envs/65be5bf7/share/spades/spades_pipeline/support.py", line 312, in sys_call
    line = process_readline(proc.stdout.readline())
KeyboardInterrupt

== Error ==  exception caught: <class 'KeyboardInterrupt'>

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /mibi/users/Wanli/hi-c_data/bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res/spades.log

### params.txt

/mibi/Wanli/hi-c_data$ spades.py -m 999 -t 35 -k 21,33,55,77,99 --restart-from k77 -o bbduk.Q15.Nesme-Sludge-SG-S2-L001-001_assemble_res

### SPAdes version

3.15.3

### Operating System

sever

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

Someone (maybe you) terminated SPAdes process via pressing Ctrl+C. There is no bug here.

**Comment by Wanli-HE** [comment]
======= SPAdes pipeline continued. Log can be found here: /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/spades.log

Restored from Command line: /home/projects/ku_00041/apps/wanli/v1.1-plaspline/Plaspline/conda_envs/b8af466e/bin/spades.py	-1	/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_1.fastq.gz	-2	/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_2.fastq.gz	--meta	-m	5000	-t	35	-k	auto	-o	/home/projects/ku_00041/data/DARWIN/ShotgunData/assembly_res/18097D-03-42-S0-L001_assembly_res	-m	999	-t	35	-k	21,33,55,77,99

Command line: /home/projects/ku_00041/apps/wanli/v1.1-plaspline/Plaspline/conda_envs/b8af466e/bin/spades.py	-1	/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_1.fastq.gz	-2	/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_2.fastq.gz	--meta	-m	5000	-t	35	-k	auto	-o	/home/projects/ku_00041/data/DARWIN/ShotgunData/assembly_res/18097D-03-42-S0-L001_assembly_res	-m	999	-t	35	-k	21,33,55,77,99	-m	999	-t	35	-k	21,33,55,77
Restart-from=k77
with updated parameters: -m	999	-t	35	-k	21,33,55,77

System information:
  SPAdes version: 3.15.3
  Python version: 3.9.0
  OS: Linux-3.10.0-1062.4.1.el7.x86_64-x86_64-with-glibc2.17

Output dir: /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_1.fastq.gz']
      right reads: ['/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55, 77]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/tmp
  Threads: 35
  Memory limit (in Gb): 999

/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_1.fastq.gz: max reads length: 150
/home/projects/ku_00041/data/DARWIN/ShotgunData/qc_reads/18097D-03-42-S0-L001_qc_2.fastq.gz: max reads length: 150

Reads length: 150


===== Before start started. 


===== Read error correction started. 

===== Skipping Read error correction (already processed)
===== Skipping corrected reads compression (already processed)

===== Read error correction finished. 


===== Assembling started. 

===== Skipping K21 (already processed)
===== Skipping K33 (already processed)
===== Skipping K55 (already processed)

===== K77 started. 


== Running: /home/projects/ku_00041/apps/wanli/v1.4-plaspline/Plaspline/conda_envs/03def384b7a285ef1559fb7bff6fad42/bin/spades-core /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/config.info /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/mda_mode.info /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/meta_mode.info

  0:00:00.000     1M / 25M   INFO    General                 (main.cpp                  :  99)   Loaded config from /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/config.info
  0:00:00.006     1M / 25M   INFO    General                 (main.cpp                  :  99)   Loaded config from /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/mda_mode.info
  0:00:00.006     1M / 25M   INFO    General                 (main.cpp                  :  99)   Loaded config from /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/meta_mode.info
  0:00:00.006     1M / 25M   INFO    General                 (memory_limit.cpp          :  48)   Memory limit set to 999 Gb
  0:00:00.006     1M / 25M   INFO    General                 (main.cpp                  : 107)   Starting SPAdes, built from N/A, git revision N/A
  0:00:00.006     1M / 25M   INFO    General                 (main.cpp                  : 108)   Maximum k-mer length: 128
  0:00:00.006     1M / 25M   INFO    General                 (main.cpp                  : 109)   Assembling dataset (/home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/dataset.info) with K=77
  0:00:00.006     1M / 25M   INFO    General                 (main.cpp                  : 110)   Maximum # of threads to use (adjusted due to OMP capabilities): 35
  0:00:00.006     1M / 25M   INFO    General                 (pipeline.cpp              : 212)   SPAdes started
  0:00:00.006     1M / 25M   INFO    General                 (pipeline.cpp              : 225)   Starting from stage: read_conversion
  0:00:00.007     1M / 25M   INFO    General                 (pipeline.cpp              : 231)   Two-step repeat resolution enabled
  0:00:00.007     1M / 25M   INFO   GraphCore                (graph_core.hpp            : 672)   Graph created, vertex min_id: 3, edge min_id: 3
  0:00:00.007     1M / 25M   INFO   GraphCore                (graph_core.hpp            : 673)   Vertex size: 48, edge size: 40
  0:00:00.007     1M / 25M   INFO    General                 (edge_index.hpp            : 113)   Size of edge index entries: 12/8
  0:00:00.007     1M / 25M   INFO    General                 (pipeline.cpp              : 242)   Will need read mapping, kmer mapper will be attached
  0:00:00.007     1M / 25M   INFO   StageManager             (stage.cpp                 : 185)   STAGE == Binary Read Conversion (id: read_conversion)
  0:00:00.011     1M / 25M   INFO    General                 (read_converter.cpp        :  72)   Converting reads to binary format for library #0 (takes a while)
  0:00:00.011     1M / 25M   INFO    General                 (read_converter.cpp        :  73)   Converting paired reads
  0:00:00.460    68M / 90M   INFO    General                 (binary_converter.cpp      :  96)   16384 reads processed
  0:00:00.481    73M / 100M  INFO    General                 (binary_converter.cpp      :  96)   32768 reads processed
  0:00:00.517    83M / 121M  INFO    General                 (binary_converter.cpp      :  96)   65536 reads processed
  0:00:00.714    72M / 169M  INFO    General                 (binary_converter.cpp      :  96)   131072 reads processed
  0:00:01.035    82M / 195M  INFO    General                 (binary_converter.cpp      :  96)   262144 reads processed
  0:00:01.761    70M / 264M  INFO    General                 (binary_converter.cpp      :  96)   524288 reads processed
  0:00:03.160    78M / 362M  INFO    General                 (binary_converter.cpp      :  96)   1048576 reads processed
  0:00:05.800    92M / 474M  INFO    General                 (binary_converter.cpp      :  96)   2097152 reads processed
  0:00:11.199    91M / 585M  INFO    General                 (binary_converter.cpp      :  96)   4194304 reads processed
  0:00:21.181    90M / 649M  INFO    General                 (binary_converter.cpp      :  96)   8388608 reads processed
  0:00:45.795    86M / 682M  INFO    General                 (binary_converter.cpp      :  96)   16777216 reads processed
  0:01:28.413    79M / 703M  INFO    General                 (binary_converter.cpp      :  96)   33554432 reads processed
  0:01:46.773    63M / 712M  INFO    General                 (binary_converter.cpp      : 111)   40703454 reads written
  0:01:46.778    41M / 712M  INFO    General                 (read_converter.cpp        :  86)   Converting single reads
  0:01:47.023    73M / 712M  INFO    General                 (binary_converter.cpp      :  96)   16384 reads processed
  0:01:47.039    76M / 712M  INFO    General                 (binary_converter.cpp      :  96)   32768 reads processed
  0:01:47.060    81M / 713M  INFO    General                 (binary_converter.cpp      :  96)   65536 reads processed
  0:01:47.254    75M / 717M  INFO    General                 (binary_converter.cpp      :  96)   131072 reads processed
  0:01:47.522    80M / 717M  INFO    General                 (binary_converter.cpp      :  96)   262144 reads processed
  0:01:48.129    74M / 719M  INFO    General                 (binary_converter.cpp      :  96)   524288 reads processed
  0:01:49.281    78M / 719M  INFO    General                 (binary_converter.cpp      :  96)   1048576 reads processed
  0:01:49.820    71M / 719M  INFO    General                 (binary_converter.cpp      : 111)   1281575 reads written
  0:01:49.826    61M / 719M  INFO    General                 (read_converter.cpp        :  92)   Converting merged reads
  0:01:49.841    71M / 719M  INFO    General                 (binary_converter.cpp      : 111)   0 reads written
  0:01:50.864     1M / 719M  INFO   StageManager             (stage.cpp                 : 185)   STAGE == de Bruijn graph construction (id: construction)
  0:01:50.931     1M / 719M  INFO    General                 (construction.cpp          : 118)   Contigs from previous K will be used: /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K55/simplified_contigs
Exception caught Cannot tell the size of file /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K55/simplified_contigs/contigs.off: Unknown error -1


== Error ==  system call for: "['/home/projects/ku_00041/apps/wanli/v1.4-plaspline/Plaspline/conda_envs/03def384b7a285ef1559fb7bff6fad42/bin/spades-core', '/home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/config.info', '/home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/mda_mode.info', '/home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/K77/configs/meta_mode.info']" finished abnormally, OS return value: 4
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/projects/ku_00041/data/DARWIN/ShotgunData/18097D-03-42-S0-L001_assembly_res/spades.log

**Comment by Wanli-HE** [comment]
ok, i know the problem!  i had solved it
