### ISSUE TITLE
Headers from fasta output file

### ISSUE THREAD

**Issue by PilarLF** [ablab/spades#985]
### Description of bug

Hi!  I did de-novo transcritpome assembly with SPAdes. The headers from the fasta output file are like this:
>NODE_3304_length_4162_cov_29.951530
With de number of the node, his length and the coverage. I was expecting headers similars to Trinity: number of node_ length _gene_isoform. 
This is important because I want to use Trinotate for the functional annotation and enrichment analysis, so I need a file with the genes and transcripts relationships. Did I the assembly wrong?
Thanks in advance, Pilar

### spades.log

[spades.log](https://github.com/ablab/spades/files/8863712/spades.log)

### params.txt

[spadesparam.txt](https://github.com/ablab/spades/files/8863727/spadesparam.txt)

### SPAdes version

v3.13.1

### Operating System

Linux 

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
> Did I the assembly wrong?

Yes, you need to use rnaSPAdes mode. Refer to SPAdes manual (https://cab.spbu.ru/files/release3.15.4/manual.html#sec3.2) for more information

**Comment by PilarLF** [comment]
Thank you so much and thanks for responding so quickly!
