### ISSUE TITLE
Issue running SPAdes on WSL2

### ISSUE THREAD

**Issue by JoshuaIszatt** [ablab/spades#986]
### Description of bug

When attempting assembly this error message comes up:

== Error ==  system call for: "['/home/artemis/miniconda3/share/spades-3.13.0-0/bin/spades-core', '/home/artemis/phage_genomics/assembly_output/BMP1_P_JJI/SPAdes/K21/configs/config.info', '/home/artemis/phage_genomics/assembly_output/BMP1_P_JJI/SPAdes/K21/configs/careful_mode.info']" finished abnormally, err code: -11

### spades.log

[spades.log](https://github.com/ablab/spades/files/8868509/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8868503/params.txt)

### SPAdes version

SPAdes v3.13.0

### Operating System

Ubuntu 20.04

### Python Version

Python 3.9.7

### Method of SPAdes installation

Conda (miniconda)

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
Hello

We do not maintain conda binaries. So, you'd better report this issue to them. Note that WSL2 is not a supported platform (as despite the name it's not Linux). Others reported limited success compiling SPAdes from sources on WSL2.

**Comment by JoshuaIszatt** [comment]
Thanks for the clarification @asl
