### ISSUE TITLE
OS return value: 2

### ISSUE THREAD

**Issue by rjym** [ablab/spades#987]
### Description of bug

I'm running spades with different inputs including pair end libraries, but always end up with different errors.
return value 2 or -6
I have 300gb and 20 CPUs

### spades.log

[spades.log](https://github.com/ablab/spades/files/8881816/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8881817/params.txt)

### SPAdes version

SPAdes version: 3.15.4

### Operating System

Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core

### Python Version

Python version: 2.7.5

### Method of SPAdes installation

module

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log clearly reads:

```
  0:00:01.696    12M / 181M  ERROR   General                 (paired_readers.cpp        :  37)   The number of right read-pairs is larger than the number of left read-pairs
  0:00:01.702    12M / 181M  ERROR   General                 (paired_readers.cpp        :  41)   Unequal number of read-pairs detected in the following files: /project/alfalfa_microbiome/A2-1ummap-trinity/A2-1unm1.fq  /project/alfalfa_microbiome/A2-1ummap-trinity/A2-1unm2.fq
```

So, your input is clearly corrupted

**Comment by rjym** [comment]
Thanks.
