### ISSUE TITLE
rnaSPADES finished abnormally, err code: -9

### ISSUE THREAD

**Issue by tomas-pluskal** [ablab/spades#99]
````
== Error ==  system call for: "['/lab/solexa_weng/testtube/SPAdes-3.11.1-Linux/bin/hammer', '/lab/weng_scratch/Tomas/20180325_Trinity_optimization/rnaspades/out_k35/corrected/configs/config.info']" finished abnormally, err code: -9
````
[params.txt](https://github.com/ablab/spades/files/1898533/params.txt)
[spades.log](https://github.com/ablab/spades/files/1898534/spades.log)

**Comment by tomas-pluskal** [comment]
Possibly the same issue as #97

**Comment by asl** [comment]
Most probably you're running out of RAM. How much free RAM is available for your SPAdes task?

**Comment by tomas-pluskal** [comment]
I guess you are right. I am running this on a cluster, where each node has >200 GB RAM. But it is hard to predict what else is running on the same node. If other memory-intensive jobs get assigned to the same node, it might run out of memory.

I wonder if it is possible for rnaSPADES to give a more meaningful error in such case, instead of "err code: -9".

**Comment by tomas-pluskal** [comment]
I see. I am not the admin of the cluster, so I cannot see the logs.

But I check the vm.overcommit_memory sysctl setting on the cluster nodes, and it is set to 
```vm.overcommit_memory = 0```

So I suppose if memory is running out, the malloc() call should fail and return NULL, as opposed to vm.overcommit_memory = 1 situation, in which malloc() always succeeds. Does rnaSPADES check the return value of malloc().

**Comment by asl** [comment]
Yes, we do check the return codes. However, the problem is much more complex. In reality even if you do not overcommit memory it could be that the system is not able to allocate the memory despite claiming that it is available (and no, if you overcommit, the malloc() could fail as well).

**Comment by asl** [comment]
Please reopen if the problem reproduces with SPAdes 3.15.2
