### ISSUE TITLE
Error when using SPAdes 3.15.4

### ISSUE THREAD

**Issue by Songhaoqiu** [ablab/spades#991]
### Description of bug

Error when kmer=77.

### spades.log

[spades.log](https://github.com/ablab/spades/files/8963093/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/8963116/params.txt)

### SPAdes version

SPAdes 3.15.4

### Operating System

Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-glibc2.17

### Python Version

Python 3.9.7

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
  0:00:06.905     1M / 5272M ERROR   General                 (kmer_coverage_model.cpp   : 187)   Invalid kmer coverage histogram, make sure that the coverage is indeed uniform
```

And indeed, it does not seem that you're assembling a genome or any part of it. Normal multicell mode expects even coverage while you're data is not so.
