### ISSUE TITLE
Exit with exception in 3.15.3 is now OS return value: -11 in 3.15.4

### ISSUE THREAD

**Issue by samwichse** [ablab/spades#993]
### Description of bug

I'm trying to assemble some data with an HMM and the --corona switch, but it was erroring out in 3.15.3 with an exception. So I updated SPAdes to 3.15.4 and running the same command now gives me an OS return value -11

The 3.15.4 error is particularly confusing:

== Error ==  system call for: "['/usr/local/bin/spades-core', '/mnt/Storage_Array/Shared/Sam/PasteBin/UWisc/SPAdes_20106-2/K73/configs/config.info', '/mnt/Storage_Array/Shared/Sam/PasteBin/UWisc/SPAdes_20106-2/K73/configs/mda_mode.info', '/mnt/Storage_Array/Shared/Sam/PasteBin/UWisc/SPAdes_20106-2/K73/configs/meta_mode.info', '/mnt/Storage_Array/Shared/Sam/PasteBin/UWisc/SPAdes_20106-2/K73/configs/rnaviral_mode.info', '/mnt/Storage_Array/Shared/Sam/PasteBin/UWisc/SPAdes_20106-2/K73/configs/hmm_mode.info']" finished abnormally, OS return value: -11.

Both logs and params are included, but I assume only 3.15.4 will be of interest?

### spades.log

[spades_3.15.3.log](https://github.com/ablab/spades/files/8980274/spades_3.15.3.log)
[spades_3.15.4.log](https://github.com/ablab/spades/files/8980278/spades_3.15.4.log)

### params.txt

[params_3.15.3.txt](https://github.com/ablab/spades/files/8980285/params_3.15.3.txt)
[params_3.15.4.txt](https://github.com/ablab/spades/files/8980286/params_3.15.4.txt)

### SPAdes version

3.15.3 and 3.15.4

### Operating System

Centos 7.9 3.10.0-1160.62.1.el7.x86_64 #1 SMP

### Python Version

2.7.5

### Method of SPAdes installation

binaries

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
What are the HMMs you're using?

**Comment by samwichse** [comment]
Just one built on an virus alignment with hmmbuild

HMMER3/f [3.1b2 | February 2015]
NAME  viral_alignment
LENG  7941
MAXL  9826
ALPH  DNA
RF    no
MM    no
CONS  yes
CS    no
MAP   yes
DATE  Thu Jun 23 14:18:40 2022
NSEQ  4
EFFN  3.144531

**Comment by asl** [comment]
I believe you need to use AA HMM

**Comment by samwichse** [comment]
OMG *forehead smack*

Unless they want to make it more idiot proof WRT errors, I'll close this, then.

**Comment by asl** [comment]
Yes, we will add checks in the next release.

**Comment by samwichse** [comment]
Thanks, that would be very helpful!

**Comment by asl** [comment]
Fixed in https://github.com/ablab/spades/releases/tag/v3.15.5
