### ISSUE TITLE
SPAdes finished abnormally,  err code: -6

### ISSUE THREAD

**Issue by jiepan1** [ablab/spades#995]
### Description of bug

Hi,
The assembly finished but I got this message: 
== Error ==  system call for: "['/data/pj/projects/tools/spades/SPAdes-3.9.1-Linux/bin/hammer', '/data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result/corrected/configs/config.info']" finished abnormally, err code: -6

Thanks,
Arkadiy

### spades.log

Command line: /data/pj/projects/tools/spades/SPAdes-3.9.1-Linux/bin/spades.py	-1	/data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r1.fastq-2	/data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r2.fastq	-t	4	-m	20	-o	/data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result	

System information:
  SPAdes version: 3.9.1
  Python version: 3.5.0
  OS: Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core

Output dir: /data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r1.fastq']
      right reads: ['/data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r2.fastq']
      interlaced reads: not specified
      single reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed (with gzip)
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result/tmp
  Threads: 4
  Memory limit (in Gb): 20

======= SPAdes pipeline started. Log can be found here: /data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result/spades.log

===== Read error correction started. 

== Running read error correction tool: /data/pj/projects/tools/spades/SPAdes-3.9.1-Linux/bin/hammer /data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result/corrected/configs/config.info

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  83)   Starting BayesHammer, built from N/A, git revision N/A
  0:00:00.002     4M / 4M    INFO    General                 (main.cpp                  :  84)   Loading config from /data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result/corrected/configs/config.info
  0:00:00.003     4M / 4M    INFO    General                 (memory_limit.hpp          :  47)   Memory limit set to 20 Gb
  0:00:00.003     4M / 4M    INFO    General                 (main.cpp                  :  93)   Trying to determine PHRED offset
  0:00:00.003     4M / 4M    INFO    General                 (main.cpp                  :  99)   Determined value is 33
  0:00:00.004     4M / 4M    INFO    General                 (hammer_tools.cpp          :  36)   Hamming graph threshold tau=1, k=21, subkmer positions = [ 0 10 ]
  0:00:00.004     4M / 4M    INFO    General                 (main.cpp                  : 120)   Size of aux. kmer data 24 bytes
     === ITERATION 0 begins ===
  0:00:00.004     4M / 4M    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 346)   Building kmer index
  0:00:00.004     4M / 4M    INFO   K-mer Splitting          (kmer_data.cpp             :  91)   Splitting kmer instances into 64 buckets. This might take a while.
  0:00:00.004     4M / 4M    INFO    General                 (file_limit.hpp            :  30)   Open file limit set to 1024
  0:00:00.004     4M / 4M    INFO    General                 (kmer_index_builder.hpp    : 105)   Memory available for splitting buffers: 1.66634 Gb
  0:00:00.004     4M / 4M    INFO    General                 (kmer_index_builder.hpp    : 113)   Using cell size of 1048576
  0:00:00.004     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             :  98)   Processing /data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r1.fastq
  0:00:09.724     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 1222760 reads
  0:00:19.490     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 2426422 reads
  0:00:30.008     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 3686239 reads
  0:00:39.531     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 4853594 reads
  0:00:49.317     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 6043803 reads
  0:00:59.597     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 7282492 reads
  0:01:09.417     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 8491490 reads
  0:01:19.878     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 9709413 reads
  0:01:30.260     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 10954704 reads
  0:02:22.591     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 17158057 reads
  0:04:45.919     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 34426376 reads
  0:09:20.707     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 67407499 reads
  0:18:30.169     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 135211174 reads
  0:36:21.619     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 269342286 reads
  0:52:21.274     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             :  98)   Processing /data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r2.fastq
  1:11:38.686     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 108)   Processed 537097745 reads
  1:44:39.738     3G / 3G    INFO   K-mer Splitting          (kmer_data.cpp             : 113)   Total 790908662 reads processed
  1:44:39.738     3G / 3G    INFO    General                 (kmer_index_builder.hpp    : 232)   Starting k-mer counting.
=== Stack Trace ===
=== Stack Trace ===
[0x4278cb]
[0x435827]
[0x5335e9]
[0x53be9d]
[0x57a709]
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t)'. In file '/spades/src/modules/io/kmers_io/mmapped_reader.hpp' on line 98. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
Verification of expression '(intptr_t) MappedRegion != -1L' failed in function 'MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t)'. In file '/spades/src/modules/io/kmers_io/mmapped_reader.hpp' on line 98. Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
hammer: /spades/src/modules/io/kmers_io/mmapped_reader.hpp:98: MMappedReader::MMappedReader(const string&, bool, size_t, off_t, size_t): Assertion `(intptr_t) MappedRegion != -1L' failed.
[0x4278cb]
[0x435827]
[0x5335e9]
[0x53be9d]
[0x57a709]

== Error ==  system call for: "['/data/pj/projects/tools/spades/SPAdes-3.9.1-Linux/bin/hammer', '/data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result/corrected/configs/config.info']" finished abnormally, err code: -6

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
Please provide us with params.txt and spades.log files from the output directory.

### params.txt

System information:
  SPAdes version: 3.9.1
  Python version: 3.5.0
  OS: Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core

Output dir: /data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r1.fastq']
      right reads: ['/data/pj/projects/metaflye/results/gut_PRJEB29152_result/03_bwa/all_id_r2.fastq']
      interlaced reads: not specified
      single reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed (with gzip)
Assembly parameters:
  k: automatic selection based on read length
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /data/pj/projects/metaflye/results/gut_PRJEB29152_result/04_assemble/spades_result/tmp
  Threads: 4
  Memory limit (in Gb): 20

### SPAdes version

3.9.1

### Operating System

Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core

### Python Version

3.5.0

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
Message 'mmap(2) failed. Reason: Cannot allocate memory. Error code: 12'.
```

So you're running out of RAM. I'd suggest you to upgrade from the ancient SPAdes 3.9 to the latest 3.15.4
