### ISSUE TITLE
No fasta file created

### ISSUE THREAD

**Issue by peflanag** [ablab/spades#996]
### Description of bug

Hi, 

I have a few isolates that I ran through SPAdes but 2 of them have resulted in no fasta files while the rest worked fine. The log file says finished abnormally but I don't know what that means.

Any help would be great!

### spades.log

[spades_063.log](https://github.com/ablab/spades/files/9018133/spades_063.log)

[spades_064.log](https://github.com/ablab/spades/files/9018135/spades_064.log)

### params.txt

[params_063.txt](https://github.com/ablab/spades/files/9018144/params_063.txt)

[params_064.txt](https://github.com/ablab/spades/files/9018150/params_064.txt)

### SPAdes version

3.14.0

### Operating System

macOS 12.4

### Python Version

3.8.1

### Method of SPAdes installation

conda

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
The log reads:

```
 Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```

Given that you're having just ~1000 reads, it does not seem to be a proper well-covered genome or even some part of it.
