### ISSUE TITLE
Spades err code 255

### ISSUE THREAD

**Issue by LeonardosMageiros** [ablab/spades#997]
### Description of bug

I am trying to run an array of jobs in a slurm cluster and while some of my jobs are finished successfully, a few of them are abnormally terminated with an error code 255. The fault seems to be while opening mmapped_reader.hp and after the failed execution the temp_SPAdes folder is empty. 

Can you understand what is wrong so I can correct my scripts? 

Thank you very much in advance, 
Leonardos

### spades.log

[spades.log](https://github.com/ablab/spades/files/9019792/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/9019791/params.txt)

### SPAdes version

SPAdes v3.13.0

### Operating System

CentOS-7

### Python Version

Python 2.7.5

### Method of SPAdes installation

preinstalled

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
You output is empty:

```
open(2) failed. Reason: No such file or directory. Error code: 2. File: /net/scratch2/mdehsnpa/CURE/raw_reads/analysis/Results/0001/0001_temp_SPAdes/spades_ZY2BF3/edge_index_62EKZE/kmers_raw_VRqoN8.0
```

Apparently you're assembling just 76 reads which does not look like a good thing to do as this does not constitute a genome or some part of it.

Upgrading to the latest SPAdes 3.15.4 will provide better message
