### ISSUE TITLE
Cannot create temporary file / OS return value: 122

### ISSUE THREAD

**Issue by jiaojiaoguan** [ablab/spades#998]
### Description of bug

  0:44:25.458  5193M / 7289M ERROR  Temporary                (temporary.cpp             :  54)   Cannot create temporary file

== Error ==  system call for: "['/home/yannisun/jiaojiao/SPAdes-3.15.4-Linux/bin/spades-hammer', '/home/yannisun/jiaojiao/simulate/simulate_contig/corrected/configs/config.info']" finished abnormally, OS return value: 122
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/yannisun/jiaojiao/simulate/simulate_contig/spades.log

Thank you for using SPAdes!

### spades.log

[spades.log](https://github.com/ablab/spades/files/9033045/spades.log)

### params.txt

spades.py --meta -t 8 -1 reads1.fq -2 /reads2.fq -o simulate_contig

### SPAdes version

3.15.4

### Operating System

Linux version 3.10.0-957.27.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Mon Jul 29 17:46:05 UTC 2019

### Python Version

Python 3.8.12

### Method of SPAdes installation

manual

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment]
This is an I/O problem on your end. Ensure that you're having enough disk space, you're not exceeded your disk quota and that the scratch dir is writable. You may want to ask your system administrator for help
